# Hypergraph Analysis

In [1]:
import os
import pandas as pd
import hypernetx as hnx
from collections import Counter
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import hypergraph.hyperGraphs as hnb
import hypergraph.visualization as viz

import optim_help.utilities as ut

## Load and pre-process selected hyperedges data

### Hyperedges from CLIQUES EXPANSION - POLY & NPN

In [3]:
sel_he_base_path = '../DATA/selected_HYPEREDGES_data/'

In [4]:
# Hyperedges selected from the polychoric correlation dyadic graph's cliques
cliques_POLY_path = sel_he_base_path + 'POLY'
cliques_POLY_paths = [
    cliques_POLY_path + '/' + f
    for f in os.listdir(cliques_POLY_path)]

# Hyperedges selected from the nonparanormal (NPN) correlation dyadic graph's cliques
cliques_NPN_path = sel_he_base_path + 'NPN'
cliques_NPN_paths = [
    cliques_NPN_path + '/' + f
    for f in os.listdir(cliques_NPN_path)]

# df cols : order, label, omega, node1, node2 ... node6

In [6]:
cliques_NPN_paths

['../DATA/selected_HYPEREDGES_data/NPN/ANBP_selected_he_NPN.csv',
 '../DATA/selected_HYPEREDGES_data/NPN/ANR_selected_he_NPN.csv',
 '../DATA/selected_HYPEREDGES_data/NPN/BED_OSFED_selected_he_NPN.csv',
 '../DATA/selected_HYPEREDGES_data/NPN/BN_selected_he_NPN.csv']

In [7]:
# FROM POLYCHORIC CORRELATION 
syn_POLY = {}
red_POLY = {}
syn_properties_POLY = {}
red_properties_POLY = {}

for hg_path in cliques_POLY_paths:
    diag = hg_path.split('/')[-1].split('_')[0]
    # manually set BED to BED_OSFED
    if diag == 'BED':
        diag = 'BED_OSFED'
    he, he_prop = hnb.preproc_hyperedges(hg_path, 'clique_exp')
    # divide syn and red
    syn_properties_POLY[diag] = {k: v for k, v in he_prop.items() if v.get("label") == "synergy"}
    red_properties_POLY[diag] =  {k: v for k, v in he_prop.items() if v.get("label") == "redundancy"}
    # now divide also the he
    syn_POLY[diag] = {k: he[k] for k in syn_properties_POLY[diag].keys() if k in he}
    red_POLY[diag] =  {k: he[k] for k in red_properties_POLY[diag].keys() if k in he}

In [8]:
# FROM NONPARANORMAL (NPN) CORRELATION 
syn_NPN = {}
red_NPN = {}
syn_properties_NPN = {}
red_properties_NPN = {}

for hg_path in cliques_NPN_paths:
    diag = hg_path.split('/')[-1].split('_')[0]
    # manually set BED to BED_OSFED
    if diag == 'BED':
        diag = 'BED_OSFED'
    he, he_prop = hnb.preproc_hyperedges(hg_path, 'clique_exp')
    # divide syn and red
    syn_properties_NPN[diag] = {k: v for k, v in he_prop.items() if v.get("label") == "synergy"}
    red_properties_NPN[diag] =  {k: v for k, v in he_prop.items() if v.get("label") == "redundancy"}
    # now divide also the he
    syn_NPN[diag] = {k: he[k] for k in syn_properties_NPN[diag].keys() if k in he}
    red_NPN[diag] =  {k: he[k] for k in red_properties_NPN[diag].keys() if k in he}

In [10]:
red_NPN['ANBP']

{'9-55-59': [9, 55, 59], '12-19-32-55-62': [12, 19, 32, 55, 62]}

### Hyperedges from sub-SCALES combination

In [11]:
# Hyperedges selected from the combinations among items in the same sub-scale
scales_path = sel_he_base_path + 'SCALES'
scales_paths = [
    scales_path + '/' + f
    for f in os.listdir(scales_path)]

In [13]:
#pd.read_csv('../DATA/selected_HYPEREDGES_data/selected_df_scales_FINAL_INTRA/ANR_selected_df_scales.csv')
scales_paths

['../DATA/selected_HYPEREDGES_data/SCALES/ANBP_selected_df_scales.csv',
 '../DATA/selected_HYPEREDGES_data/SCALES/ANR_selected_df_scales.csv',
 '../DATA/selected_HYPEREDGES_data/SCALES/BED_OSFED_selected_df_scales.csv',
 '../DATA/selected_HYPEREDGES_data/SCALES/BN_selected_df_scales.csv']

In [14]:
syn_SCALES = {}
red_SCALES = {}
syn_properties_SCALES = {}
red_properties_SCALES = {}

for hg_path in scales_paths:
    diag = hg_path.split('/')[-1].split('_')[0]
    # manually set BED to BED_OSFED
    if diag == 'BED':
        diag = 'BED_OSFED'
    he, he_prop = hnb.preproc_hyperedges(hg_path, 'cliques-exp')
    # divide syn and red
    syn_properties_SCALES[diag] = {k: v for k, v in he_prop.items() if v.get("label") == "synergy"}
    red_properties_SCALES[diag] =  {k: v for k, v in he_prop.items() if v.get("label") == "redundancy"}
    # now divide also the he
    syn_SCALES[diag] = {k: he[k] for k in syn_properties_SCALES[diag].keys() if k in he}
    red_SCALES[diag] =  {k: he[k] for k in red_properties_SCALES[diag].keys() if k in he}

In [13]:
#he # ('1-2-7-19'): {1, 2, 7, 19}
#he_prop # ('1-2-7-19'): {'omega': ...

#### Merge hyperedges/multiplets: POLY, NPN; SCALES.

In [15]:
merged_SYN = {}
merged_RED = {}
merged_prop_SYN = {}
merged_prop_RED = {}

for diag in syn_POLY:
    merged_SYN[diag] = syn_POLY[diag] | syn_NPN[diag] | syn_SCALES[diag]
    merged_prop_SYN[diag] = syn_properties_POLY[diag] | syn_properties_NPN[diag] | syn_properties_SCALES[diag]

    merged_RED[diag] = red_POLY[diag] | red_NPN[diag] | red_SCALES[diag] 
    merged_prop_RED[diag] = red_properties_POLY[diag] | red_properties_NPN[diag] | red_properties_SCALES[diag]

Intersections between scales/poly-npn.

In [23]:
for diag in syn_POLY:
    merged_poly_npn_SYN = syn_POLY[diag] | syn_NPN[diag]
    npol_scales_intersec_SYN = set(merged_poly_npn_SYN.keys()).intersection(set(syn_SCALES[diag].keys())) 
    print('Scales and POLY/NPN SYN intersection is', len(npol_scales_intersec_SYN))

print('\n')
for diag in red_POLY:    
    merged_poly_npn_RED = red_POLY[diag] | red_NPN[diag]
    npol_scales_intersec_RED = set(merged_poly_npn_RED.keys()).intersection(set(red_SCALES[diag].keys())) 
    print('Scales and POLY/NPN RED intersection is', len(npol_scales_intersec_RED))

Scales and POLY/NPN SYN intersection is 88
Scales and POLY/NPN SYN intersection is 83
Scales and POLY/NPN SYN intersection is 44
Scales and POLY/NPN SYN intersection is 77


Scales and POLY/NPN RED intersection is 1
Scales and POLY/NPN RED intersection is 14
Scales and POLY/NPN RED intersection is 7
Scales and POLY/NPN RED intersection is 4

Intersections between poly/npn.

In [16]:
npn_poly_intersec_SYN = {}
npn_poly_intersec_RED = {}

for diag in syn_POLY:
    print(diag)
    npn_poly_intersec_SYN[diag] = set(syn_POLY[diag].keys()).intersection(set(syn_NPN[diag].keys())) 
    npn_poly_intersec_RED[diag] = set(red_POLY[diag].keys()).intersection(set(red_NPN[diag].keys())) 
    print('SYN_poly:', len(syn_POLY[diag]), '- SYN_npn:', len(syn_NPN[diag]), '- SYN_intersec', len(npn_poly_intersec_SYN[diag]))
    print('RED_poly:', len(red_POLY[diag]), '- RED_npn:', len(red_NPN[diag]), '- RED_intersec', len(npn_poly_intersec_RED[diag]))
    
    print('SYN_union:', len(syn_POLY[diag] | syn_NPN[diag]))
    print('RED_union:', len(red_POLY[diag] | red_NPN[diag]))
    print('\n')

ANBP
SYN_poly: 573 - SYN_npn: 592 - SYN_intersec 344
RED_poly: 3 - RED_npn: 2 - RED_intersec 0
SYN_union: 821
RED_union: 5


ANR
SYN_poly: 624 - SYN_npn: 692 - SYN_intersec 167
RED_poly: 22 - RED_npn: 26 - RED_intersec 17
SYN_union: 1149
RED_union: 31


BED_OSFED
SYN_poly: 497 - SYN_npn: 669 - SYN_intersec 343
RED_poly: 18 - RED_npn: 22 - RED_intersec 8
SYN_union: 823
RED_union: 32


BN
SYN_poly: 491 - SYN_npn: 776 - SYN_intersec 228
RED_poly: 3 - RED_npn: 2 - RED_intersec 0
SYN_union: 1039
RED_union: 5

#### Merged hes counts.

#### FILTER (here not needed - already filtered by 0.1 during selection) & CHECK FOR SINGLETONS

In [20]:
merged_SYN_filtered, merged_prop_SYN_filtered = ut.filtering_he(merged_prop_SYN, merged_SYN, threshold=0.10)

ANBP 2086 0 2086 0
ANR 2215 0 2215 0
BED_OSFED 1970 0 1970 0
BN 1817 0 1817 0

In [21]:
merged_RED_filtered, merged_prop_RED_filtered = ut.filtering_he(merged_prop_RED, merged_RED, threshold=0.10)

ANBP 30 0 30 0
ANR 40 0 40 0
BED_OSFED 80 0 80 0
BN 20 0 20 0

In [31]:
for diag in syn_POLY:
    print(diag)
    print('Originals:', len(merged_prop_SYN[diag]), "SYN.", len(merged_prop_RED[diag]), "RED.")
    print('After further filtering', len(merged_prop_SYN_filtered[diag]), "SYN.", len(merged_prop_RED_filtered[diag]), "RED.")
    print('----------------------------------------')

ANBP
Originals: 2086 SYN. 30 RED.
After further filtering 2086 SYN. 30 RED.
----------------------------------------
ANR
Originals: 2215 SYN. 40 RED.
After further filtering 2215 SYN. 40 RED.
----------------------------------------
BED_OSFED
Originals: 1970 SYN. 80 RED.
After further filtering 1970 SYN. 80 RED.
----------------------------------------
BN
Originals: 1817 SYN. 20 RED.
After further filtering 1817 SYN. 20 RED.
----------------------------------------

In [32]:
for d, interactions in merged_prop_SYN_filtered.items():
    print(d)
    d_int = list(interactions.values())
    int_3 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 3]
    int_4 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 4]
    int_5 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 5]
    print('3:', len(int_3), '; 4:', len(int_4), '; 5:', len(int_5))

ANBP
3: 111 ; 4: 1932 ; 5: 43
ANR
3: 8 ; 4: 1850 ; 5: 357
BED_OSFED
3: 190 ; 4: 1769 ; 5: 11
BN
3: 4 ; 4: 1255 ; 5: 558

In [33]:
for d, interactions in merged_prop_RED_filtered.items():
    print(d)
    d_int = list(interactions.values())
    int_3 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 3]
    int_4 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 4]
    int_5 = [i['nodes_numeric'] for i in d_int if len(i['nodes_numeric']) == 5]
    print('3:', len(int_3), '; 4:', len(int_4), '; 5:', len(int_5))

ANBP
3: 17 ; 4: 2 ; 5: 11
ANR
3: 31 ; 4: 2 ; 5: 7
BED_OSFED
3: 13 ; 4: 19 ; 5: 48
BN
3: 13 ; 4: 1 ; 5: 6

In [36]:
# skip dir creation if it already exist
out_dir_sm = "tables"            
os.makedirs(out_dir_sm, exist_ok=True)

with open("tables/summary_SELECTED_HE_filtered.txt", "w") as f:
    print('MERGED - FINAL --------------------------------', file = f)
    for diag in syn_POLY:
        print(diag, file = f)
        print(len(merged_prop_SYN_filtered[diag]), "synergy hyperedges", file = f)
        print(len(merged_prop_RED_filtered[diag]), "redundancy hyperedges", file = f)
        print('----------------------------------------', file = f)
    
    print('\n', file = f)
    print('\n', file = f)
    
    print('POLY ------------------------------------------', file = f)
    for diag, hes in syn_POLY.items():
        print(diag, file = f)
        print(len(syn_POLY[diag]), "synergy hyperedges", file = f)
        print(len(red_POLY[diag]), "redundancy hyperedges", file = f)
        print('----------------------------------------', file = f)
        
    print('\n', file = f)

    print('NPN ------------------------------------------', file = f)
    for diag, hes in syn_NPN.items():
        print(diag, file = f)
        print(len(syn_NPN[diag]), "synergy hyperedges", file = f)
        print(len(red_NPN[diag]), "redundancy hyperedges", file = f)
        print('----------------------------------------', file = f)
        
    print('\n', file = f)
    print('\n', file = f)

    print('SCALES ------------------------------------------', file = f)
    for diag, hes in syn_SCALES.items():
        print(diag, file = f)
        print(len(syn_SCALES[diag]), "synergy hyperedges", file = f)
        print(len(red_SCALES[diag]), "redundancy hyperedges", file = f)
        print('----------------------------------------', file = f)
    
    print('\n', file = f)

### Nodes: description

In [37]:
nodes_labels_path = '../DATA/EDI_det/edi3_items_fixed.csv' 
nodes_items = pd.read_csv(nodes_labels_path)

In [38]:
nodes_items

                                                 desc  id
0   I eat sweets and carbohydrates without feeling...   1
1                 I think that my stomach is too big.   2
2   I wish that I could return to the security of ...   3
3                              I eat when I am upset.   4
4                                        I binge eat.   5
..                                                ...  ..
86  I would rather spend time by myself than with ...  87
87               Suffering makes you a better person.  88
88               I know there are people who love me.  89
89          I feel like I must hurt myself or others.  90
90                I feel that I really know who I am.  91

[91 rows x 2 columns]

In [39]:
nodes_items_dict = dict(zip(nodes_items["id"], nodes_items["desc"]))

## Build the Multiplex HyperGraph

### Partition and Multiplex Construction 

**After all three validation stages:**

1. **Partition by sign:**
   - **Redundant hyperedges:** Ω > 0 (positive layer)
   - **Synergistic hyperedges:** Ω < 0 (negative layer)

2. **Multiplex construction:**
     - Hypergraph 1 (positive): Weighted hyperedges with weight = +|Ω|
         - a layer for each diagnosis
     - Hypergraph 2 (negative): Weighted hyperedges with weight = -|Ω|
         - a layer for each diagnosis
 
Aggregate across all diagnoses by summing hyperedge weights across layers

Result: Multiplex hypergraphs with diagnosis-specific and cross-diagnosis structures

Run this following cell to recompute the tables with the furtherly filtered hyperedges.

In [40]:
merged_SYN = merged_SYN_filtered
merged_prop_SYN = merged_prop_SYN_filtered

merged_RED = merged_RED_filtered
merged_prop_RED = merged_prop_RED_filtered

In [41]:
# check for singletons - no singoletti in neither SYN nor RED
for k, v in merged_RED.items():
    singletons = [e for e in v.values() if len(e) == 1]
    #print(singletons)

#### merged_SYN, merged_RED 
#### merged_prop_SYN, merged_prop_RED

In [42]:
HG_multiplex = {}
for diag in merged_SYN:
    print(diag)
    HG_syn, HG_red = diag + '_SYN', diag + '_RED'
    HG_multiplex[HG_syn] = hnb.build_hypergraph_from_multiplets(merged_SYN[diag], merged_prop_SYN[diag], nodes_items_dict)
    HG_multiplex[HG_red] = hnb.build_hypergraph_from_multiplets(merged_RED[diag], merged_prop_RED[diag], nodes_items_dict)

ANBP
Missing nodes are: 0 set()
Missing nodes are: 71 {1, 3, 4, 6, 7, 8, 10, 11, 13, 14, 16, 17, 18, 20, 21, 23, 24, 25, 26, 27, 29, 30, 33, 35, 36, 37, 40, 41, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 56, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91}
ANR
Missing nodes are: 0 set()
Missing nodes are: 65 {1, 3, 4, 6, 8, 10, 11, 13, 14, 15, 17, 18, 20, 22, 23, 24, 27, 29, 30, 33, 34, 35, 36, 39, 40, 42, 43, 44, 47, 48, 52, 53, 54, 56, 57, 58, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91}
BED_OSFED
Missing nodes are: 0 set()
Missing nodes are: 66 {3, 6, 8, 10, 13, 14, 15, 17, 18, 20, 21, 22, 23, 24, 26, 27, 29, 30, 33, 34, 35, 36, 37, 39, 40, 41, 42, 43, 44, 48, 50, 51, 52, 54, 56, 57, 58, 60, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91}
BN
Missing nodes are: 0 set()
Missing nodes are: 76 {1, 3, 6, 7, 8, 10, 11, 13, 14, 15, 16, 17, 18, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 52, 53, 54, 56, 57, 58, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91}

In [43]:
HG_ANBP_SYN = HG_multiplex['ANBP_SYN']

In [44]:
HG_ANBP_SYN.edges.dataframe.head()

           weight                                    misc_properties
uid
3-35-39 -0.107673  {'omega': -0.1076726411963058, 'label': 'syner...
5-29-71 -0.268419  {'omega': -0.2684185260693716, 'label': 'syner...
6-14-35 -0.116951  {'omega': -0.1169509284954966, 'label': 'syner...
6-18-24 -0.101958  {'omega': -0.1019583143981694, 'label': 'syner...
6-22-35 -0.102736  {'omega': -0.1027355043562199, 'label': 'syner...

In [45]:
common_hes_SYN = set()
for name, hg in HG_multiplex.items():
    if 'SYN' in name:
        print(name, '--------------')
        hg_index = hg.edges.dataframe.index
        print('Singleton search', [a for a in hg_index if a == '71'])
        hg_index_one = [e for e in hg_index if len(e) == 1]
        hg_index = [e for e in hg_index if len(e) > 1] # and e != '71']
        common_hes_SYN = common_hes_SYN | set(hg_index)
        print(name, hg_index_one, len(hg.edges.dataframe))
print(len(common_hes_SYN))

common_hes_RED = set()
for name, hg in HG_multiplex.items():
    if 'RED' in name:
        hg_index = hg.edges.dataframe.index
        hg_index_one = [e for e in hg_index if len(e) == 1]
        hg_index = [e for e in hg_index if len(e) > 1]
        common_hes_RED = common_hes_RED | set(hg_index)
        print(name, hg_index_one, len(hg.edges.dataframe))
print(len(common_hes_RED))

ANBP_SYN --------------
Singleton search []
ANBP_SYN [] 2086
ANR_SYN --------------
Singleton search []
ANR_SYN [] 2215
BED_OSFED_SYN --------------
Singleton search []
BED_OSFED_SYN [] 1970
BN_SYN --------------
Singleton search []
BN_SYN [] 1817
5949
ANBP_RED ['1', '3', '4', '6', '7', '8'] 101
ANR_RED ['1', '3', '4', '6', '8'] 105
BED_OSFED_RED ['3', '6', '8'] 146
BN_RED ['1', '3', '6', '7', '8'] 96
209

In [46]:
HG_ANBP_SYN.nodes.dataframe

     weight                                    misc_properties
uid
3         1  {'desc': 'I wish that I could return to the se...
35        1  {'desc': 'The demands of adulthood are too gre...
39        1  {'desc': 'I feel happy that I am not a child a...
5         1                           {'desc': 'I binge eat.'}
29        1  {'desc': 'As a child, I tried very hard to avo...
..      ...                                                ...
74        1       {'desc': 'I feel trapped in relationships.'}
38        1   {'desc': 'I think about bingeing (overeating).'}
28        1  {'desc': 'I have gone on eating binges where I...
46        1  {'desc': 'I eat moderately in front of others ...
79        1  {'desc': 'I am prone to outbursts of anger or ...

[91 rows x 2 columns]

### Sub-scales description

In [47]:
scales_desc = pd.DataFrame({
    "scale": ['-', 'A', 'B', 'BD', 'DT', 'ED', 'IA', 'ID', 'II', 'LSE', 'MF', 'P', 'PA'],
    "desc": ['-', 'Ascetism', 'Bulimia', 'Body Dissatisfaction', 'Drive for Thinness',
             'Emotional Disregulation', 'Interpersonal Alienation', 'Interoceptive Deficits',
             'Interpersonal Insecurity', 'Low Self Esteem', 'Maturity Fears',
             'Perfectionism', 'Personal Alienation']
})

In [48]:
scales_desc

   scale                      desc
0      -                         -
1      A                  Ascetism
2      B                   Bulimia
3     BD      Body Dissatisfaction
4     DT        Drive for Thinness
5     ED   Emotional Disregulation
6     IA  Interpersonal Alienation
7     ID    Interoceptive Deficits
8     II  Interpersonal Insecurity
9    LSE           Low Self Esteem
10    MF            Maturity Fears
11     P             Perfectionism
12    PA       Personal Alienation

## NODES PROPERTIES

#### Paper: Multiplex measures for higher‑order networks (2024) - Lotito, Montresor, Battiston

### WEIGHTED DEGREE

In [49]:
# layer is the diagnosis
wDeg_layers = {}
H_incS = {}
edges_layers = {}
for layer, HG in HG_multiplex.items():
    '''
    H_inc : (N,E) incidence matrix
    w     : (E,) edge weights
    k_w   : (N,) weighted degree
    k_norm: (N,) normalized weighted degree
    nodes : list of nodes
    edges : list of edges
    '''
    H_inc, w, k_w, k_norm, nodes, edges = hnb.weighted_degrees_normalized(HG)
    H_incS[layer] = H_inc
    edges_layers = edges
    wDeg_layers[layer] = pd.DataFrame({
                                        "node": nodes,
                                        "weighted_degree": k_w,
                                        "normalized_weighted_degree": k_norm
                                    })

In [50]:
wDeg_layers['ANR_SYN'].head(5)

   node  weighted_degree  normalized_weighted_degree
0    13       -39.048483                    0.006114
1    38        -8.290081                    0.001298
2    64       -12.875059                    0.002016
3    89       -38.035279                    0.005955
4     1      -233.933756                    0.036628

In [51]:
M_norm = hnb.combine_layer_weighted_degrees(wDeg_layers, value="normalized_weighted_degree")

In [52]:
print(M_norm.loc['ANR_SYN'].loc[71])

0.0006763729131236449

In [53]:
M_norm

node,1,2,3,4,5,6,7,8,9,10,...,82,83,84,85,86,87,88,89,90,91
ANBP_SYN,0.017934,0.010290,0.021243,0.007000,0.006248,0.007209,0.004872,0.030639,0.002595,0.012318,...,0.014748,0.006752,0.018923,0.018435,0.019554,0.017461,0.006307,0.005099,0.003472,0.008792
ANBP_RED,0.000000,0.033552,0.000000,0.000000,0.022710,0.000000,0.000000,0.000000,0.086605,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ANR_SYN,0.036628,0.013895,0.020345,0.011311,0.004328,0.015154,0.008343,0.041445,0.003999,0.014241,...,0.011583,0.004011,0.016801,0.012754,0.012033,0.012973,0.002277,0.005955,0.002192,0.017497
ANR_RED,0.000000,0.067352,0.000000,0.000000,0.004469,0.000000,0.057268,0.000000,0.131377,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
BED_OSFED_SYN,0.013131,0.008113,0.017657,0.004306,0.001577,0.006401,0.005716,0.029208,0.001836,0.012174,...,0.010866,0.009297,0.029428,0.017805,0.014530,0.021787,0.007987,0.005313,0.002216,0.014103
BED_OSFED_RED,0.026612,0.035642,0.000000,0.020450,0.055445,0.000000,0.030447,0.000000,0.067403,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
BN_SYN,0.032940,0.024449,0.018306,0.008187,0.005143,0.033264,0.006451,0.030393,0.004806,0.021771,...,0.009599,0.005380,0.008016,0.008623,0.009823,0.010861,0.009807,0.023219,0.008568,0.018207
BN_RED,0.000000,0.047696,0.000000,0.011878,0.011878,0.000000,0.000000,0.000000,0.102192,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [54]:
nodes_items_dict = dict(zip(nodes_items['id'], nodes_items['desc']))

In [55]:
HG_desc = M_norm.apply(lambda row: ut.process_row_wn(row, nodes_items_dict), axis=1)

In **HG_desc**, nodes are sorted by weighted degree.

In [56]:
HG_desc

ANBP_SYN         {'row': 'ANBP_SYN', 'nodes': [40, 77, 44, 33, ...
ANBP_RED         {'row': 'ANBP_RED', 'nodes': [55, 62, 45, 19, ...
ANR_SYN          {'row': 'ANR_SYN', 'nodes': [8, 40, 1, 44, 33,...
ANR_RED          {'row': 'ANR_RED', 'nodes': [9, 32, 45, 49, 55...
BED_OSFED_SYN    {'row': 'BED_OSFED_SYN', 'nodes': [40, 77, 44,...
BED_OSFED_RED    {'row': 'BED_OSFED_RED', 'nodes': [62, 45, 9, ...
BN_SYN           {'row': 'BN_SYN', 'nodes': [6, 1, 8, 69, 24, 2...
BN_RED           {'row': 'BN_RED', 'nodes': [55, 62, 45, 9, 19,...
dtype: object

In [57]:
HG_desc.iloc[1]

{'row': 'ANBP_RED',
 'nodes': Index([55, 62, 45, 19, 12, 9, 31, 59, 2, 28, 5, 46, 38, 32, 15, 34, 57, 22, 39,
        58],
       dtype='int64', name='node'),
 'values': array([0.17256359, 0.14723365, 0.12031325, 0.09434717, 0.0928428 ,
        0.08660483, 0.05301958, 0.05166967, 0.03355245, 0.03086954,
        0.02270994, 0.01987267, 0.01915646, 0.01405421, 0.00736833,
        0.00736833, 0.00736833, 0.00636174, 0.00636174, 0.00636174])}

######  HG_desc is a series of dictionaries with keys row (layer, like ANBO:SYN), nodes (of he HG), values (the weighted degree)

#### Mapping item: scale (ex. x: DT)

- items_scales_dict maps nodes (as int - key) to the sub_scale they belong to (as str - value)
- scores are normalized (they sum up to 1)

In [58]:
sub_scales_path = '../DATA/EDI_det/sub_scales.csv' 
sub_scales = pd.read_csv(sub_scales_path)[['item', 'scales']]

scales_df_dict = {name: group for name, group in sub_scales.groupby("scales")}
items_by_scale = sub_scales.groupby("scales")["item"].apply(list).to_dict()
items_scales_dict = sub_scales.set_index("item")["scales"].to_dict()

In [59]:
scales_desc_dict = scales_desc.set_index("scale")["desc"].to_dict()

In [60]:
with open("tables/items_per_HG_filtered.txt", "w") as f:
    for row in HG_desc:
        print(row['row'], file = f)
        for j, v in zip(row['nodes'], row['values']):
            scale = items_scales_dict[j]
            scale_d = '(' + scale + '-' + scales_desc_dict[scale] + ')'
            print(j, round(v, 4), scale_d, ':', nodes_items_dict[j] + '\n', file = f)
        print('*************', file = f)

### NODES' BEHAVIOUR wrt SUB_SCALES

In [62]:
from collections import Counter

data = list(items_scales_dict.items())
# count occurrences of second element
counts = Counter(t[1] for t in data)
# convert to regular dict (optional)
scale_arity = dict(counts)

print(scale_arity)

{'DT': 7, 'BD': 10, 'MF': 8, 'B': 8, 'ID': 9, 'LSE': 6, 'P': 6, 'II': 7, 'IA': 8, 'PA': 6, 'A': 7, 'ED': 8, '-': 1}

#### nodes_scale_activity

In [63]:
nodes_scale_activity = {}
ndigits = 5
for hg in HG_desc:
    nodes = hg['nodes']
    scores = hg['values']
    scale_scores = ut.sum_values_per_scale(nodes, scores, items_scales_dict)
    scores_avg = {k: v/scale_arity[k] for k, v in scale_scores.items()}
    avg_sum = sum(scores_avg.values())
    normalized = {k: v/avg_sum for k, v in scores_avg.items()}
    #rounded = {k: round(v, ndigits) for k, v in scale_scores.items()}
    rounded = {k: round(v, ndigits) for k, v in normalized.items()}
    # they sum up to 1 since they come from normalized values over all the nodes (and they are a sum of all nodes' values)
    # this does not mean that the values themselves are normalized
    # convert to list of tuples
    tuples = list(rounded.items())
    # sort by value descending
    tuples_sorted = sorted(tuples, key=lambda x: x[1], reverse=True)
    nodes_scale_activity[hg['row']] = pd.DataFrame(tuples_sorted, columns=["scale", "value"])

In [64]:
nodes_scale_activity.keys()

dict_keys(['ANBP_SYN', 'ANBP_RED', 'ANR_SYN', 'ANR_RED', 'BED_OSFED_SYN', 'BED_OSFED_RED', 'BN_SYN', 'BN_RED'])

In [65]:
with open('tables/nodes_scale_activity_SYNERGY_RANKED_filtered_norm.txt', "w") as f:
    for hg_name, hg_df in nodes_scale_activity.items():
        if hg_name.split('_')[-1] == 'SYN':
            f.write(f"### DataFrame {hg_name}\n\n")
            hg_df = hg_df.merge(scales_desc, on="scale", how="inner")
            f.write(hg_df[['scale', 'desc', 'value']].to_string())
            f.write("\n\n")

with open('tables/nodes_scale_activity_REDUNDANCY_RANKED_filtered_norm.txt', "w") as f:
    for hg_name, hg_df in nodes_scale_activity.items():
        if hg_name.split('_')[-1] == 'RED':
            f.write(f"### DataFrame {hg_name}\n\n")
            hg_df = hg_df.merge(scales_desc, on="scale", how="inner")
            f.write(hg_df[['scale', 'desc', 'value']].to_string())
            f.write("\n\n")

### Visualize the nodes' degree eCDFs

In [66]:
M_norm_SYN = M_norm[M_norm.index.astype(str).str.contains("SYN")].copy()
M_norm_RED = M_norm[M_norm.index.astype(str).str.contains("RED")].copy()

#### Plots (saved to files)

In [67]:
# skip dir creation if it already exist
out_dir_sm = "plots"            
os.makedirs(out_dir_sm, exist_ok=True)

In [68]:
viz.plot_degree_ecdf(M_norm_SYN, show=False, file_name='plots/ecdf_degree_SYN_layers')

In [69]:
viz.plot_degree_ecdf(M_norm_RED, show=False, file_name='plots/ecdf_degree_RED_layers')

In [70]:
viz.plot_per_layer_degree_distributions(M_norm_SYN, bins=30, show=False, file_name='plots/per_layer_nodes_degree_SYN')

In [71]:
viz.plot_per_layer_degree_distributions(M_norm_RED, bins=30, show=False, file_name='plots/per_layer_nodes_degree_RED')

### Overlapping Degree & Participation Coefficient

Let $k_{i,\alpha}$ denote the (possibly weighted) degree of node $i$ in layer $\alpha$, and let $M$ be the total number of layers.  The **overlapping degree** of node $i$ is defined as:

$ O_i = \sum_{\alpha=1}^{M} k_{i,\alpha}.$

The participation coefficient quantifies how the connectivity of a node is distributed across the layers of the multiplex.
It identifies whether a node acts as a **specialist** (active mostly in a single layer: $P_i \approx 0$) or as a **generalist** (active in multiple layers $P_i \approx 1$).

The **participation coefficient** of node $i$ is then given by: $
P_i = \frac{M}{M - 1}
\left(
1 -
\sum_{\alpha=1}^{M}
\left(
\frac{k_{i,\alpha}}{O_i}
\right)^2
\right).
$

This formula measures how evenly the connectivity of node $i$ is distributed across layers.

The term $ \frac{k_{i,\alpha}}{O_i}$ represents the fraction of the total connectivity of node $i$  that occurs in layer $\alpha$.

The sum of squared fractions, $
\sum_{\alpha=1}^{M}
\left(
\frac{k_{i,\alpha}}{O_i}
\right)^2,
$  is large when the connectivity is concentrated in one or few layers, and small when the connectivity is evenly distributed.

The normalization factor $\frac{M}{M - 1}$ ensures that
$
0 \le P_i \le 1.
$

#### Overlapping Degrees + distributions (saved to files)

In [72]:
O_i = ut.compute_overlapping_degree(M_norm, norm = False)  # Series
O_i_norm = ut.compute_overlapping_degree(M_norm, norm = True)  # Series

In [73]:
O_i_SYN = ut.compute_overlapping_degree(M_norm_SYN, norm = False)  # Series
O_i_norm_SYN = ut.compute_overlapping_degree(M_norm_SYN, norm = True)  # Series

O_i_RED = ut.compute_overlapping_degree(M_norm_RED, norm = False)  # Series
O_i_norm_RED = ut.compute_overlapping_degree(M_norm_RED, norm = True)  # Series

In [74]:
viz.plot_overlapping_degree_distribution(O_i, show=False, file_name='plots/overlapping_coeff')
viz.plot_overlapping_degree_distribution(O_i_norm, show=False, file_name='plots/overlapping_coeff_norm')

In [75]:
viz.plot_overlapping_degree_distribution(O_i_SYN, show=False, file_name='plots/overlapping_coeff_SYN')
viz.plot_overlapping_degree_distribution(O_i_norm_SYN, show=False, file_name='plots/overlapping_coeff_norm_SYN')

viz.plot_overlapping_degree_distribution(O_i_RED, show=False, file_name='plots/overlapping_coeff_RED')
viz.plot_overlapping_degree_distribution(O_i_norm_RED, show=False, file_name='plots/overlapping_coeff_norm_RED')

#### Partecipation coefficients + disribution (saved to files)

In [76]:
M_norm_RED[11]

ANBP_RED         0.000000
ANR_RED          0.000000
BED_OSFED_RED    0.037309
BN_RED           0.000000
Name: 11, dtype: float64

In [77]:
partecipation_coeff = ut.compute_participation_coefficient_v2(M_norm)
partecipation_coeff_SYN = ut.compute_participation_coefficient_v2(M_norm_SYN)
partecipation_coeff_RED = ut.compute_participation_coefficient_v2(M_norm_RED)

In [78]:
viz.plot_participation_distribution(partecipation_coeff, show=False, file_name='plots/part_coeff_nodes')
viz.plot_participation_distribution(partecipation_coeff_SYN, show=False, file_name='plots/part_coeff_nodes_SYN')
viz.plot_participation_distribution(partecipation_coeff_RED, show=False, file_name='plots/part_coeff_nodes_RED')

In [79]:
viz.plot_participation_per_node(partecipation_coeff, show=False, file_name='plots/part_coeff_per_node')
viz.plot_participation_per_node(partecipation_coeff_SYN, show=False, file_name='plots/part_coeff_per_node_SYN')
viz.plot_participation_per_node(partecipation_coeff_RED, show=False, file_name='plots/part_coeff_per_node_RED')

In [80]:
top_specialists = partecipation_coeff.sort_values().head(9).to_frame(name='value')
top_specialists_SYN = partecipation_coeff_SYN.sort_values().head(9).to_frame(name='value')
top_specialists_RED = partecipation_coeff_RED.sort_values().head(9).to_frame(name='value')

In [81]:
# ALL
top_specialists_RED = partecipation_coeff_RED.sort_values().to_frame(name='value')
#top_specialists_RED = top_specialists_RED[top_specialists_RED['value'] > 0]
top_specialists_RED['desc'] = top_specialists_RED.apply(lambda row: nodes_items_dict[row.name], axis=1)

In [82]:
top_specialists['desc'] = top_specialists.apply(lambda row: nodes_items_dict[row.name], axis=1)
top_specialists_SYN['desc'] = top_specialists_SYN.apply(lambda row: nodes_items_dict[row.name], axis=1)
top_specialists_RED['desc'] = top_specialists_RED.apply(lambda row: nodes_items_dict[row.name], axis=1)
top_specialists

         value                                               desc
node
32    0.573907    I am preoccupied with the desire to be thinner.
49    0.584611  If I gain a pound, I worry that I will keep ga...
11    0.597472          I feel extremely guilty after overeating.
16    0.627119                  I am terrified of gaining weight.
64    0.645210  When I am upset, I worry that I will start eat...
46    0.648351  I eat moderately in front of others and stuff ...
29    0.655130  As a child, I tried very hard to avoid disappo...
89    0.684276               I know there are people who love me.
28    0.718067  I have gone on eating binges where I felt that...

In [83]:
top_specialists_SYN

         value                                               desc
node
64    0.752744  When I am upset, I worry that I will start eat...
29    0.764319  As a child, I tried very hard to avoid disappo...
38    0.797574               I think about bingeing (overeating).
89    0.798322               I know there are people who love me.
28    0.828530  I have gone on eating binges where I felt that...
6     0.838090                    I wish that I could be younger.
50    0.840397                I feel that I am a valuable person.
53    0.856540  I have the thought of trying to vomit in order...
46    0.857413  I eat moderately in front of others and stuff ...

In [84]:
top_specialists_RED[0:20]

         value                                               desc
node
1     0.000000  I eat sweets and carbohydrates without feeling...
11    0.000000          I feel extremely guilty after overeating.
22    0.000000           I would rather be an adult than a child.
15    0.000000                       I am open about my feelings.
26    0.000000  I can clearly identify what emotion I am feeling.
41    0.000000                    I have a low opinion of myself.
34    0.000000   I have trouble expressing my emotions to others.
37    0.000000                           I feel safe with myself.
47    0.000000         I feel bloated after eating a normal meal.
50    0.000000                I feel that I am a valuable person.
57    0.000000    I can talk about personal thoughts or feelings.
53    0.000000  I have the thought of trying to vomit in order...
39    0.000000        I feel happy that I am not a child anymore.
58    0.000000  The best years of your life are when you becom...
68    0.000000  I would like to be in total control of my bodi...
61    0.478733                          I eat or drink in secret.
49    0.528823  If I gain a pound, I worry that I will keep ga...
51    0.564179  When I'm upset, I don't know if I'm sad, scare...
60    0.591907  I have feelings that I find difficult to ident...
32    0.599124    I am preoccupied with the desire to be thinner.

In [85]:
len(top_specialists_RED)

91

## HYPEREDGES PROPERTIES

#### Paper: Multiplex measures for higher‑order networks (2024) - Lotito, Montresor, Battiston

In [86]:
HGs_SYN = {name: val for name, val in HG_multiplex.items() if "SYN" in name}
HGs_RED = {name: val for name, val in HG_multiplex.items() if "RED" in name}
#print(HG_multiplex.keys())
#print(HGs_SYN.keys())
#print(HGs_RED.keys())

#### Hyperedges: order distribution per layer

In [87]:
order_stats_df_SYN = hnb.hyperedge_order_discrete_stats(HGs_SYN.values(), HGs_SYN.keys())
order_stats_df_RED = hnb.hyperedge_order_discrete_stats(HGs_RED.values(), HGs_RED.keys())

In [88]:
order_stats_df_SYN

            layer  order  count  fraction
0        ANBP_SYN      3    111  0.053212
1        ANBP_SYN      4   1932  0.926174
2        ANBP_SYN      5     43  0.020614
3         ANR_SYN      3      8  0.003612
4         ANR_SYN      4   1850  0.835214
5         ANR_SYN      5    357  0.161174
6   BED_OSFED_SYN      3    190  0.096447
7   BED_OSFED_SYN      4   1769  0.897970
8   BED_OSFED_SYN      5     11  0.005584
9          BN_SYN      3      4  0.002201
10         BN_SYN      4   1255  0.690699
11         BN_SYN      5    558  0.307100

In [89]:
order_stats_df_RED

            layer  order  count  fraction
0        ANBP_RED      3     17  0.566667
1        ANBP_RED      4      2  0.066667
2        ANBP_RED      5     11  0.366667
3         ANR_RED      3     31  0.775000
4         ANR_RED      4      2  0.050000
5         ANR_RED      5      7  0.175000
6   BED_OSFED_RED      3     13  0.162500
7   BED_OSFED_RED      4     19  0.237500
8   BED_OSFED_RED      5     48  0.600000
9          BN_RED      3     13  0.650000
10         BN_RED      4      1  0.050000
11         BN_RED      5      6  0.300000

In [90]:
viz.plot_hyperedge_order_discrete(order_stats_df_SYN, show=False, file_name='plots/he_order_distro_SYN_layers')
viz.plot_hyperedge_order_discrete(order_stats_df_RED, show=False, file_name='plots/he_order_distro_RED_layers')

### Hyperedges: overlap

In [91]:
edge_to_layers_SYN, overlap_df_SYN = hnb.hyperedge_overlap(HGs_SYN.values(), HGs_SYN.keys())
edge_to_layers_RED, overlap_df_RED = hnb.hyperedge_overlap(HGs_RED.values(), HGs_RED.keys())

sorted_overlap_df_SYN = overlap_df_SYN.sort_values(by="overlap",ascending=False).reset_index(drop=True)
sorted_overlap_df_RED = overlap_df_RED.sort_values(by="overlap",ascending=False).reset_index(drop=True)

In [92]:
common_hes_SYN_list = [tuple([int(i) for i in e.split('-')]) for e in common_hes_SYN] 
#print(common_hes_SYN_list)
sorted_overlap_SYN_keys = [tuple(sorted(e)) for e in sorted_overlap_df_SYN['nodes']]

#print(set(sorted_overlap_SYN_keys) == set(common_hes_SYN_list))

In [93]:
print(len(common_hes_SYN_list), len(sorted_overlap_SYN_keys))

5949 5949

In [94]:
[a for a in sorted(sorted_overlap_SYN_keys) if a not in sorted(common_hes_SYN_list)]

[]

In [98]:
one = [a for a in sorted(common_hes_SYN_list) if a not in sorted(sorted_overlap_SYN_keys)]
print(one)

[]

In [99]:
counts_SYN = hnb.he_overlap_description(sorted_overlap_df_SYN)
counts_SYN

All hes are  5949
Hes compairing in more layers are 1271
Order 3
Hes compairing in more layers are 25
-----
Order 4
Hes compairing in more layers are 1230
-----
Order 5
Hes compairing in more layers are 16
-----

{'ALL': Counter({('BN_SYN', 'ANBP_SYN', 'BED_OSFED_SYN', 'ANR_SYN'): 237,
          ('ANBP_SYN', 'BED_OSFED_SYN', 'ANR_SYN'): 189,
          ('ANBP_SYN', 'BED_OSFED_SYN'): 180,
          ('ANBP_SYN', 'ANR_SYN'): 123,
          ('ANR_SYN', 'BED_OSFED_SYN'): 115,
          ('BN_SYN', 'ANBP_SYN', 'ANR_SYN'): 110,
          ('BN_SYN', 'ANR_SYN'): 84,
          ('BN_SYN', 'ANBP_SYN'): 79,
          ('BN_SYN', 'BED_OSFED_SYN'): 59,
          ('BN_SYN', 'ANBP_SYN', 'BED_OSFED_SYN'): 53,
          ('BN_SYN', 'ANR_SYN', 'BED_OSFED_SYN'): 42}),
 3: Counter({('ANBP_SYN', 'BED_OSFED_SYN'): 25}),
 4: Counter({('BN_SYN', 'ANBP_SYN', 'BED_OSFED_SYN', 'ANR_SYN'): 237,
          ('ANBP_SYN', 'BED_OSFED_SYN', 'ANR_SYN'): 189,
          ('ANBP_SYN', 'BED_OSFED_SYN'): 155,
          ('ANBP_SYN', 'ANR_SYN'): 121,
          ('ANR_SYN', 'BED_OSFED_SYN'): 115,
          ('BN_SYN', 'ANBP_SYN', 'ANR_SYN'): 110,
          ('BN_SYN', 'ANBP_SYN'): 75,
          ('BN_SYN', 'ANR_SYN'): 74,
          ('BN_SYN', 'BED_OSFED_SYN'): 59,
          ('BN_SYN', 'ANBP_SYN', 'BED_OSFED_SYN'): 53,
          ('BN_SYN', 'ANR_SYN', 'BED_OSFED_SYN'): 42}),
 5: Counter({('BN_SYN', 'ANR_SYN'): 10,
          ('BN_SYN', 'ANBP_SYN'): 4,
          ('ANBP_SYN', 'ANR_SYN'): 2})}

In [100]:
#print(len(sorted_overlap_df_RED))
#sorted_overlap_df_RED[sorted_overlap_df_RED['order'] == 1]

In [101]:
counts_RED = hnb.he_overlap_description(sorted_overlap_df_RED)
counts_RED

All hes are  135
Hes compairing in more layers are 23
Order 3
Hes compairing in more layers are 16
-----
Order 4
Hes compairing in more layers are 1
-----
Order 5
Hes compairing in more layers are 6
-----

{'ALL': Counter({('BED_OSFED_RED', 'ANBP_RED'): 5,
          ('BED_OSFED_RED', 'BN_RED', 'ANBP_RED'): 4,
          ('BN_RED', 'BED_OSFED_RED', 'ANR_RED', 'ANBP_RED'): 3,
          ('BN_RED', 'ANR_RED'): 3,
          ('BN_RED', 'ANBP_RED'): 3,
          ('BN_RED', 'ANR_RED', 'ANBP_RED'): 2,
          ('BED_OSFED_RED', 'BN_RED'): 1,
          ('ANR_RED', 'ANBP_RED'): 1,
          ('BED_OSFED_RED', 'ANR_RED'): 1}),
 3: Counter({('BED_OSFED_RED', 'ANBP_RED'): 4,
          ('BN_RED', 'BED_OSFED_RED', 'ANR_RED', 'ANBP_RED'): 3,
          ('BN_RED', 'ANR_RED'): 3,
          ('BN_RED', 'ANR_RED', 'ANBP_RED'): 2,
          ('BN_RED', 'ANBP_RED'): 2,
          ('BED_OSFED_RED', 'BN_RED', 'ANBP_RED'): 1,
          ('ANR_RED', 'ANBP_RED'): 1}),
 4: Counter({('BN_RED', 'ANBP_RED'): 1}),
 5: Counter({('BED_OSFED_RED', 'BN_RED', 'ANBP_RED'): 3,
          ('BED_OSFED_RED', 'BN_RED'): 1,
          ('BED_OSFED_RED', 'ANBP_RED'): 1,
          ('BED_OSFED_RED', 'ANR_RED'): 1})}

In [102]:
viz.hyperedges_order_overlap(overlap_df_SYN, show=False, file_name='plots/he_order_overlap_SYN')
viz.hyperedges_order_overlap(overlap_df_RED, show=False, file_name='plots/he_order_overlap_RED')

#### Hyperedge weights distribution ($\Omega$ - distribution)

In [103]:
he_weight_SYN = hnb.hyperedge_weight_distributions(HGs_SYN.values(), HGs_SYN.keys())
he_weight_stats_SYN = (he_weight_SYN.groupby(["layer", "order"])["weight"]
                                    .agg(["count", "mean", "std", "min", "max"])
                                    .reset_index())

he_weight_RED = hnb.hyperedge_weight_distributions(HGs_RED.values(), HGs_RED.keys())
he_weight_stats_RED = (he_weight_RED.groupby(["layer", "order"])["weight"]
                                    .agg(["count", "mean", "std", "min", "max"])
                                    .reset_index())

In [104]:
he_weight_SYN.head()

      layer  edge_id  order    weight
0  ANBP_SYN  3-35-39      3 -0.107673
1  ANBP_SYN  5-29-71      3 -0.268419
2  ANBP_SYN  6-14-35      3 -0.116951
3  ANBP_SYN  6-18-24      3 -0.101958
4  ANBP_SYN  6-22-35      3 -0.102736

In [105]:
len(he_weight_RED[he_weight_RED['layer'] == 'ANR_RED'])

40

In [106]:
print('Order 3, syn', he_weight_SYN.loc[he_weight_SYN["order"] == 3, "weight"].mean())
print('Order 4, syn', he_weight_SYN.loc[he_weight_SYN["order"] == 4, "weight"].mean())
print('Order 5, syn', he_weight_SYN.loc[he_weight_SYN["order"] == 5, "weight"].mean())

print('Order 3, red', he_weight_RED.loc[he_weight_RED["order"] == 3, "weight"].mean())
print('Order 4, red', he_weight_RED.loc[he_weight_RED["order"] == 4, "weight"].mean())
print('Order 5, red', he_weight_RED.loc[he_weight_RED["order"] == 5, "weight"].mean())

Order 3, syn -0.1366397936990645
Order 4, syn -0.7616814565302984
Order 5, syn -1.166374915136896
Order 3, red 0.18219029682755225
Order 4, red 0.1998885249690657
Order 5, red 0.24398982588170762

In [107]:
he_weight_RED.loc[he_weight_RED["order"] == 4]

             layer      edge_id  order    weight
0         ANBP_RED   9-45-55-59      4  0.229581
1         ANBP_RED  12-19-55-62      4  0.296680
48         ANR_RED    2-9-45-59      4  0.236164
49         ANR_RED  31-55-59-62      4  0.270183
70   BED_OSFED_RED   9-19-45-55      4  0.136479
71   BED_OSFED_RED  12-45-59-62      4  0.206044
72   BED_OSFED_RED  16-25-32-49      4  0.222532
73   BED_OSFED_RED  31-45-59-62      4  0.134481
90   BED_OSFED_RED    2-7-11-16      4  0.102134
91   BED_OSFED_RED    2-7-16-49      4  0.121542
92   BED_OSFED_RED   7-11-16-49      4  0.151479
113  BED_OSFED_RED    2-9-45-62      4  0.125385
114  BED_OSFED_RED    4-5-38-61      4  0.210787
115  BED_OSFED_RED   5-28-38-46      4  0.533101
116  BED_OSFED_RED   7-11-16-32      4  0.199143
117  BED_OSFED_RED   7-16-25-32      4  0.224876
118  BED_OSFED_RED   7-16-32-49      4  0.231925
119  BED_OSFED_RED   9-31-45-62      4  0.150974
120  BED_OSFED_RED   9-31-59-62      4  0.122871
121  BED_OSFED_RED   9-45-59-62      4  0.279756
122  BED_OSFED_RED  11-16-25-32      4  0.182479
123  BED_OSFED_RED  11-16-32-49      4  0.159410
124  BED_OSFED_RED  19-31-45-62      4  0.113239
164         BN_RED  12-19-55-62      4  0.156079

In [108]:
viz.plot_weights_by_layer_all_orders(
    he_weight_SYN,
    out_dir="plots/he_weights_syn_order",
    file_prefix="weights_vs_layer",
    file_ext="png",
    show=False,
)

In [109]:
viz.plot_weights_by_layer_all_orders(
    he_weight_RED,
    out_dir="plots/he_weights_red_order",
    file_prefix="weights_vs_layer",
    file_ext="png",
    show=False,
)

In [110]:
viz.plot_weights_by_order_all_layers(
    he_weight_SYN,
    out_dir="plots/he_weights_syn",
    file_prefix="weights_vs_order",
    file_ext="png",
    show=False,
)

In [111]:
viz.plot_weights_by_order_all_layers(
    he_weight_RED,
    out_dir="plots/he_weights_red",
    file_prefix="weights_vs_order",
    file_ext="png",
    show=False,
)

## Which sub_scales work together?

In [112]:
order_keys = ["sum_w", "n_hyperedges", "pattern_arity"]
ascending = (True, False, False)

### SYNERGY

#### Inter sub_scales (patterns' arity > 1)

In [113]:
# items_scales_dict contains the mapping node: sub_scale
scales_together_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_together_SYN[hg_name] = {}
    for order in (3, 4, 5):
        # weight are negative: ascending true
        scales_together_SYN[hg_name][order] = hnb.pattern_stats_for_order(hg, 
                                                                          items_scales_dict, 
                                                                          order,
                                                                          sorted_by=order_keys,
                                                                          ascending=ascending)

In [114]:
scales_together_SYN['ANBP_SYN'][5].head()

,order,pattern,pattern_arity,n_hyperedges,sum_w,avg_weight,n_he_norm
0,5,"(ED, ID, LSE, P)",4,2,-2.518483,-1.259241,0.04878
1,5,"(A, B, ED, ID)",4,2,-2.030348,-1.015174,0.04878
2,5,"(B, ED, ID, II)",4,2,-2.016732,-1.008366,0.04878
3,5,"(DT, ED)",2,2,-1.881354,-0.940677,0.04878
4,5,"(DT, ED, ID, P)",4,1,-1.407531,-1.407531,0.02439

In [115]:
#scales_together_5_SYN['ANBP_SYN']

#### Intra sub_scales (patterns' arity == 1)

In [116]:
scales_alone_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_alone_SYN[hg_name] = {}
    for order in (3, 4, 5):
        # weight are negative: ascending true
        scales_alone_SYN[hg_name][order] = hnb.pattern_stats_for_order(hg, 
                                                                          items_scales_dict, 
                                                                          order,
                                                                          sorted_by=order_keys,
                                                                          ascending=ascending, 
                                                                          arity=False)

In [125]:
# skip dir creation if it already exist
out_dir_sm = "tables/SYN"            
os.makedirs(out_dir_sm, exist_ok=True)

out_dir_sm = "tables/SYN/3"            
os.makedirs(out_dir_sm, exist_ok=True)
out_dir_sm = "tables/SYN/4"            
os.makedirs(out_dir_sm, exist_ok=True)
out_dir_sm = "tables/SYN/5"            
os.makedirs(out_dir_sm, exist_ok=True)
out_dir_sm = "tables/SYN/ALL"            
os.makedirs(out_dir_sm, exist_ok=True)

out_dir_sm = "tables/RED"            
os.makedirs(out_dir_sm, exist_ok=True)

#### Order 3: FOCUS

In [122]:
scales_together_3_SYN = {}
for layer, table in scales_together_SYN.items():
    table_3 = table[3]
    scales_together_3_SYN[layer] = table_3
    print(layer + ':', len(table_3),'different patterns.')
    
print('--------------------------')

scales_alone_3_SYN = {}
for layer, table in scales_alone_SYN.items():
    table_3 = table[3]
    scales_alone_3_SYN[layer] = table_3
    print(layer + ':', len(table_3),'different patterns.')
    
viz.tables_to_txt_order("tables/SYN/3/scales_together_3_SYN.txt", scales_together_3_SYN)
viz.tables_to_txt_order("tables/SYN/3/scales_alone_3_SYN.txt", scales_alone_3_SYN)

ANBP_SYN: 21 different patterns.
ANR_SYN: 3 different patterns.
BED_OSFED_SYN: 42 different patterns.
BN_SYN: 3 different patterns.
--------------------------
ANBP_SYN: 11 different patterns.
ANR_SYN: 4 different patterns.
BED_OSFED_SYN: 10 different patterns.
BN_SYN: 1 different patterns.

#### Order 4: FOCUS

In [123]:
scales_together_4_SYN = {}
for layer, table in scales_together_SYN.items():
    table_4 = table[4]
    scales_together_4_SYN[layer] = table_4
    print(layer + ':', len(table_4),'different patterns.')
    
print('--------------------------')

scales_alone_4_SYN = {}
for layer, table in scales_alone_SYN.items():
    table_4 = table[4]
    scales_alone_4_SYN[layer] = table_4
    print(layer + ':', len(table_4),'different patterns.')
    
viz.tables_to_txt_order("tables/SYN/4/scales_together_4_SYN.txt", scales_together_4_SYN)
viz.tables_to_txt_order("tables/SYN/4/scales_alone_4_SYN.txt", scales_alone_4_SYN)

ANBP_SYN: 248 different patterns.
ANR_SYN: 232 different patterns.
BED_OSFED_SYN: 244 different patterns.
BN_SYN: 176 different patterns.
--------------------------
ANBP_SYN: 12 different patterns.
ANR_SYN: 12 different patterns.
BED_OSFED_SYN: 12 different patterns.
BN_SYN: 12 different patterns.

#### Order 5: FOCUS

In [124]:
scales_together_5_SYN = {}
for layer, table in scales_together_SYN.items():
    table_5 = table[5]
    scales_together_5_SYN[layer] = table_5
    print(layer + ':', len(table_5),'different patterns.')
    
print('--------------------------')

scales_alone_5_SYN = {}
for layer, table in scales_alone_SYN.items():
    table_5 = table[5]
    scales_alone_5_SYN[layer] = table_5
    print(layer + ':', len(table_5),'different patterns.')

viz.tables_to_txt_order("tables/SYN/5/scales_together_5_SYN.txt", scales_together_5_SYN) 
viz.tables_to_txt_order("tables/SYN/5/scales_alone_5_SYN.txt", scales_alone_5_SYN)

ANBP_SYN: 35 different patterns.
ANR_SYN: 163 different patterns.
BED_OSFED_SYN: 7 different patterns.
BN_SYN: 222 different patterns.
--------------------------
ANBP_SYN: 2 different patterns.
ANR_SYN: 7 different patterns.
BED_OSFED_SYN: 0 different patterns.
BN_SYN: 8 different patterns.

#### One table for ALL ORDERS.

In [127]:
scales_together_ALL_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_together_ALL_SYN[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            sorted_by=order_keys,
                                            ascending=ascending)
    
for layer, table in scales_together_ALL_SYN.items():
    print(layer + ':', len(table),'different patterns.')
    
# scales_together_ALL_SYN['ANBP_SYN'].head()
viz.tables_to_txt("tables/SYN/ALL/scales_together_ALL_SYN.txt", scales_together_ALL_SYN)
viz.tables_to_txt("tables/SYN/ALL/scales_together_ALL_SYN_top.txt", scales_together_ALL_SYN, top=True)

ANBP_SYN: 270 different patterns.
ANR_SYN: 331 different patterns.
BED_OSFED_SYN: 250 different patterns.
BN_SYN: 315 different patterns.

In [128]:
for layer, table in scales_together_ALL_SYN.items():
    print(layer + ':', table["n_hyperedges"].sum())

ANBP_SYN: 1474
ANR_SYN: 1664
BED_OSFED_SYN: 1420
BN_SYN: 1191

#### Observe the one - sub_scaled patters.

In [129]:
scales_alone_ALL_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_alone_ALL_SYN[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            sorted_by=order_keys,
                                            ascending=ascending,
                                            arity = False)

viz.tables_to_txt("tables/SYN/ALL/scales_alone_ALL_SYN.txt", scales_alone_ALL_SYN)

In [130]:
for layer, table in scales_alone_ALL_SYN.items():
    print(layer + ':', table["n_hyperedges"].sum())

ANBP_SYN: 612
ANR_SYN: 551
BED_OSFED_SYN: 550
BN_SYN: 626

#### ALL ORDERS (3 EXCLUDED)

In [131]:
out_dir_sm = "tables/SYN/minus3"            
os.makedirs(out_dir_sm, exist_ok=True)

In [132]:
scales_together_ALL_minus3_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_together_ALL_minus3_SYN[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            exclude_order=True,
                                            excluded_orders=[3],                       
                                            sorted_by=order_keys,
                                            ascending=ascending)
    
for layer, table in scales_together_ALL_minus3_SYN.items():
    print(layer + ':', len(table),'different patterns.')
    
viz.tables_to_txt("tables/SYN/minus3/scales_together_ALL_minus3_SYN.txt", scales_together_ALL_minus3_SYN)
viz.tables_to_txt("tables/SYN/minus3/scales_together_ALL_minus3_SYN_top.txt", scales_together_ALL_minus3_SYN, top=True)

ANBP_SYN: 266 different patterns.
ANR_SYN: 330 different patterns.
BED_OSFED_SYN: 245 different patterns.
BN_SYN: 315 different patterns.

#### Observe the one - sub_scaled patters.

In [133]:
scales_alone_ALL_minus3_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_alone_ALL_minus3_SYN[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            exclude_order=True,
                                            excluded_orders=[3],                          
                                            sorted_by=order_keys,
                                            ascending=ascending,
                                            arity = False)

viz.tables_to_txt("tables/SYN/minus3/scales_alone_ALL_minus3_SYN.txt", scales_alone_ALL_minus3_SYN)

### REDUNDANCY

In [134]:
order_keys = ["sum_w", "n_hyperedges", "pattern_arity"]
ascending = (False, False, False)

#### Inter sub_scales (patterns' arity > 1)

In [135]:
scales_together_RED = {}
for hg_name, hg in HGs_RED.items():
    scales_together_RED[hg_name] = {}
    for order in (3, 4, 5):
        scales_together_RED[hg_name][order] = hnb.pattern_stats_for_order(hg, 
                                                                          items_scales_dict, 
                                                                          order,
                                                                          sorted_by=order_keys,
                                                                          ascending=ascending)

#### Intra sub_scales (patterns' arity == 1)

In [136]:
scales_alone_RED = {}
for hg_name, hg in HGs_RED.items():
    scales_alone_RED[hg_name] = {}
    for order in (3, 4, 5):
        # weight are negative: ascending true
        scales_alone_RED[hg_name][order] = hnb.pattern_stats_for_order(hg, 
                                                                          items_scales_dict, 
                                                                          order,
                                                                          sorted_by=order_keys,
                                                                          ascending=ascending, 
                                                                          arity=False)

#### One table for ALL ORDERS.

In [137]:
scales_together_ALL_RED = {}
for hg_name, hg in HGs_RED.items():
    scales_together_ALL_RED[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            sorted_by=order_keys,
                                            ascending=ascending)

In [138]:
for layer, table in scales_together_ALL_RED.items():
    print(layer + ':', len(table),'different patterns.')

ANBP_RED: 1 different patterns.
ANR_RED: 2 different patterns.
BED_OSFED_RED: 6 different patterns.
BN_RED: 0 different patterns.

In [139]:
viz.tables_to_txt("tables/RED/scales_together_ALL_RED.txt", scales_together_ALL_RED)

#### Observe the one - sub_scaled patterns.

In [140]:
scales_alone_ALL_RED = {}
for hg_name, hg in HGs_RED.items():
    scales_alone_ALL_RED[hg_name] = hnb.pattern_stats_for_layer(hg, items_scales_dict,
                                            sorted_by=order_keys,
                                            ascending=ascending,
                                            arity = False)

In [141]:
viz.tables_to_txt("tables/RED/scales_alone_ALL_RED.txt", scales_alone_ALL_RED)

# -----------------------------------------------------------------------------------------------------------------

#### Patterns - to - hes - list : SYN

In [142]:
scales_hes_SYN = {}
for hg_name, hg in HGs_SYN.items():
    scales_hes_SYN[hg_name] = hnb.pattern_to_hes_list(hg, items_scales_dict, 'weight', True)

In [143]:
for layer, D in scales_hes_SYN.items():
    print(layer)
    for k, val in D.items():
        print(k, len(val))
        print(val)
        print('-----------------')
    print('\n')

ANBP_SYN
frozenset({'MF'}) 59
[([6, 35, 39, 48], -0.6989352646854528), ([3, 35, 39, 48], -0.6441795272257202), ([14, 35, 48, 58], -0.6355424202228441), ([3, 22, 35, 48], -0.6310068752179987), ([3, 14, 35, 39], -0.6301539161109062), ([35, 39, 48, 58], -0.6234347356817054), ([6, 35, 48, 58], -0.6078725474161217), ([3, 14, 35, 58], -0.6046850892365256), ([3, 35, 48, 58], -0.5958617712186438), ([6, 14, 35, 58], -0.5884832497479735), ([6, 14, 35, 39], -0.5680194467001627), ([22, 35, 48, 58], -0.5482270562953921), ([3, 35, 39, 58], -0.5461989308062059), ([3, 6, 35, 58], -0.5428856937865163), ([14, 22, 35, 48], -0.5402764596965106), ([14, 22, 35, 58], -0.5203283844524691), ([14, 35, 39, 48], -0.5145468880743529), ([3, 22, 35, 39], -0.5125488180146647), ([22, 35, 39, 48], -0.5005977644930226), ([3, 14, 22, 35], -0.4873212907188282), ([3, 14, 48, 58], -0.4843490396326899), ([14, 35, 39, 58], -0.4693441340582183), ([3, 39, 48, 58], -0.4673347786111996), ([3, 22, 35, 58], -0.4610389536438184), ([3, 6, 48, 58], -0.4432912825833384), ([14, 22, 35, 39], -0.4399633584183959), ([3, 22, 48, 58], -0.4180833421443957), ([14, 39, 48, 58], -0.4072655206119613), ([6, 14, 39, 48], -0.3966984371136632), ([3, 6, 39, 48], -0.3618203504472284), ([14, 22, 48, 58], -0.3575225275136482), ([3, 22, 39, 48], -0.3425425821103403), ([3, 14, 39, 58], -0.3358902410744377), ([3, 14, 22, 48], -0.3340501636315522), ([3, 6, 39, 58], -0.3339055135343045), ([3, 14, 22, 58], -0.3264438015938289), ([3, 6, 22, 48], -0.322596286642149), ([14, 22, 39, 48], -0.3177489950210201), ([3, 6, 14, 22], -0.3075174354246641), ([3, 14, 39, 48], -0.3042884080496719), ([6, 14, 22, 39], -0.2969398930081866), ([3, 6, 14, 39], -0.2909294550067933), ([6, 14, 22, 48], -0.2891930910980704), ([22, 35, 39, 58], -0.2845203144385984), ([6, 22, 39, 48], -0.2753787650758568), ([3, 6, 22, 58], -0.2673116245000067), ([3, 6, 22, 39], -0.2497905014878405), ([3, 6, 14, 48], -0.1996477140071171), ([6, 35, 58], -0.1279602747694177), ([3, 35, 48], -0.1271863334452483), ([35, 48, 58], -0.1230303913216666), ([3, 14, 22, 39], -0.120683020727057), ([6, 14, 58], -0.1177555812528936), ([6, 14, 35], -0.1169509284954966), ([6, 48, 58], -0.1161573287802077), ([6, 35, 48], -0.1126733859701492), ([3, 35, 39], -0.1076726411963058), ([14, 35, 58], -0.1067339175887109), ([6, 22, 35], -0.1027355043562199)]
-----------------
frozenset({'B', '-', 'P'}) 1
[([5, 29, 71], -0.2684185260693716)]
-----------------
frozenset({'PA', 'MF'}) 11
[([3, 18, 35, 84], -1.1709847592540328), ([14, 18, 35, 84], -1.107845782487555), ([3, 24, 35, 56], -1.1051559712908947), ([18, 35, 58, 84], -1.0982661128924285), ([3, 35, 48, 56], -1.0426947435764724), ([6, 18, 84, 91], -0.8584609913949564), ([6, 18, 56, 84], -0.8541642142748422), ([3, 6, 24, 35], -0.7036466802558934), ([3, 14, 22, 24], -0.691790588748205), ([6, 18, 56, 91], -0.6342277290532792), ([6, 18, 24], -0.1019583143981694)]
-----------------
frozenset({'LSE', 'MF'}) 2
[([6, 35, 42, 48], -0.7366060537596333), ([6, 27, 35], -0.1063668323636015)]
-----------------
frozenset({'ID', 'II'}) 65
[([34, 51, 69, 87], -1.3585186779348604), ([34, 51, 73, 87], -1.264121922414894), ([33, 40, 51, 73], -1.2463506373249942), ([40, 51, 77, 87], -1.2207725196659212), ([8, 51, 73, 77], -1.2105787110168684), ([40, 44, 51, 73], -1.206663879819498), ([21, 34, 69, 87], -1.1904056343322085), ([21, 40, 77, 87], -1.1801890547337024), ([8, 34, 51, 87], -1.173815908569555), ([40, 51, 73, 77], -1.1664127875615051), ([40, 44, 77, 87], -1.158657983962776), ([40, 60, 73, 77], -1.1585860742199685), ([40, 44, 51, 57], -1.1542686208579127), ([34, 69, 77, 87], -1.1539945805792335), ([8, 34, 69, 87], -1.1486050500954832), ([33, 40, 77, 87], -1.1421967427622055), ([34, 60, 69, 87], -1.1359266379768762), ([33, 34, 40, 51], -1.1288082825613657), ([40, 44, 60, 73], -1.124486950971061), ([33, 34, 51, 73], -1.12301460744467), ([8, 34, 40, 51], -1.1214446722649534), ([40, 60, 77, 87], -1.1188750209341656), ([23, 51, 73, 87], -1.1156063914905658), ([21, 34, 44, 87], -1.1088062031363108), ([8, 21, 34, 40], -1.1026585222997625), ([34, 40, 51, 77], -1.0967113333467855), ([33, 34, 69, 87], -1.096261596074683), ([8, 51, 77, 87], -1.0956611743551008), ([8, 34, 51, 69], -1.0932788957435733), ([34, 44, 69, 87], -1.0931428703346953), ([33, 34, 51, 69], -1.092119095405771), ([8, 33, 34, 69], -1.091786501917298), ([8, 33, 77, 87], -1.0890404689475377), ([34, 51, 77, 87], -1.086627720224033), ([33, 34, 44, 69], -1.0822848773099771), ([21, 34, 40, 77], -1.0807612062810996), ([8, 34, 51, 73], -1.079907704348738), ([44, 51, 73, 77], -1.0786770219268504), ([8, 33, 34, 40], -1.0767484826883411), ([8, 15, 23, 34, 57], -0.8865572157913348), ([15, 26, 44, 51], -0.7461740560386403), ([26, 33, 34, 51], -0.67388822496887), ([8, 26, 34, 51], -0.6729800410559719), ([15, 26, 44, 60], -0.6641952508224698), ([15, 21, 26, 44], -0.6615704402480169), ([21, 33, 34, 51], -0.6229667922460926), ([8, 34, 51, 60], -0.6192202099876347), ([33, 34, 51, 60], -0.5809538292047947), ([8, 21, 34, 51], -0.580771129658455), ([15, 26, 51, 60], -0.5478535499605606), ([26, 33, 34, 60], -0.5415666694090149), ([15, 21, 26, 51], -0.5047641985790001), ([21, 26, 33, 34], -0.5028318867372619), ([8, 21, 26, 34], -0.4978626837923698), ([8, 21, 34, 60], -0.4882634828537), ([15, 21, 26, 60], -0.4624462658337798), ([26, 34, 51, 60], -0.4542012694365205), ([8, 26, 34, 60], -0.4459592364905091), ([21, 26, 34, 51], -0.4108161455027108), ([21, 33, 34, 60], -0.3739387070557427), ([15, 23, 26, 34], -0.3735000115473355), ([21, 34, 51, 60], -0.3517775038068542), ([21, 26, 34, 60], -0.2327940503446619), ([8, 34, 51], -0.1162250228707684), ([26, 33, 34], -0.1099200631063261)]
-----------------
frozenset({'ED', 'ID'}) 39
[([40, 51, 77, 85], -1.2610341525580502), ([21, 40, 77, 85], -1.199633590022394), ([8, 40, 77, 85], -1.1994410339458206), ([21, 33, 40, 85], -1.193135995511028), ([21, 70, 77, 85], -1.189945910407168), ([21, 33, 40, 67], -1.1882209980843328), ([40, 67, 70, 77], -1.1854803239248533), ([40, 51, 83, 85], -1.1794425341989196), ([8, 40, 67, 77], -1.1763005855182342), ([40, 51, 67, 77], -1.169145077675296), ([40, 51, 67, 85], -1.1619392393292711), ([40, 51, 70, 85], -1.157547332822741), ([51, 67, 70, 77], -1.1483595981156824), ([40, 67, 77, 85], -1.140174880372285), ([8, 33, 40, 85], -1.132003878195544), ([40, 67, 70, 85], -1.1315828278021804), ([26, 40, 77, 85], -1.131160816602943), ([21, 40, 67, 77], -1.128575221884219), ([40, 44, 67, 77], -1.1268937458153765), ([21, 40, 44, 67], -1.1181209929358786), ([40, 51, 70, 77], -1.11234830321267), ([8, 67, 70, 85], -1.1064773868355855), ([26, 33, 40, 85], -1.1047254701853184), ([40, 60, 67, 85], -1.1019530228678818), ([51, 70, 77, 83], -1.101441947161952), ([33, 40, 67, 85], -1.101241671104951), ([8, 40, 51, 85], -1.100255783159767), ([33, 40, 51, 85], -1.094812380813682), ([21, 33, 70, 77], -1.0917527834193912), ([51, 70, 77, 85], -1.0905568580055878), ([60, 67, 77, 85], -1.0863730519629051), ([40, 60, 77, 85], -1.0848177852240823), ([21, 67, 70, 77], -1.0835738584699328), ([40, 44, 77, 85], -1.0810464859817692), ([67, 70, 77, 85], -1.080657561084223), ([8, 67, 77, 83], -1.0781666889797776), ([44, 60, 77, 85], -0.8851114180454438), ([8, 21, 44, 67], -0.8050452626955433), ([8, 44, 67], -0.1266674356880024)]
-----------------
frozenset({'II', 'BD'}) 2
[([9, 15, 23, 34, 57], -0.8465462965774577), ([9, 57, 59], -0.1099642533343328)]
-----------------
frozenset({'ED', 'A', 'LSE'}) 5
[([10, 27, 66, 85], -0.7165946045210809), ([10, 41, 66, 85], -0.6746035576005767), ([10, 68, 83, 85], -0.6472544263946389), ([27, 41, 66, 85], -0.6127092633893199), ([10, 66, 90], -0.1073085581139512)]
-----------------
frozenset({'IA', 'PA'}) 26
[([18, 54, 65, 84], -1.1824782546570276), ([24, 54, 65, 84], -1.1417233277853782), ([18, 54, 65, 76], -1.139644844744982), ([24, 56, 65, 76], -1.1280987556812114), ([24, 54, 56, 65], -1.127258200569667), ([54, 65, 76, 84], -1.1206279372815755), ([54, 56, 65, 76], -1.1119068789707462), ([17, 24, 54, 65], -1.107425815014473), ([18, 65, 76, 91], -1.0838270754571866), ([54, 56, 65, 84], -1.0808736104776813), ([56, 65, 76, 91], -1.0767620586859294), ([18, 54, 56, 74], -0.8902979448119304), ([17, 18, 30, 74], -0.8468225508716536), ([56, 80, 84, 91], -0.8148546191962431), ([30, 54, 56, 74], -0.7924188672964085), ([20, 80, 84, 91], -0.7834388579789504), ([18, 80, 84, 91], -0.7379892845361837), ([18, 30, 56, 74], -0.6805789555696293), ([18, 56, 80, 84], -0.675998194062096), ([24, 80, 84, 91], -0.6753133256422643), ([18, 56, 80, 91], -0.6292352145219091), ([18, 80, 89, 91], -0.6052535401672081), ([17, 18, 30, 89], -0.5687854691097556), ([76, 80, 91], -0.2614422765352202), ([80, 84, 91], -0.1098561937037612), ([18, 65, 80], -0.1010759354570716)]
-----------------
frozenset({'P', 'PA', 'MF'}) 1
[([24, 35, 36], -0.1243311367349839)]
-----------------
frozenset({'ID', 'PA'}) 47
[([8, 33, 40, 56], -1.1971222883928796), ([21, 40, 44, 84], -1.182485162742875), ([24, 40, 44, 77], -1.1722868626140084), ([40, 51, 56, 84], -1.1697726071284116), ([21, 24, 40, 77], -1.160139389576436), ([20, 26, 40, 56], -1.1568835735520118), ([40, 44, 56, 84], -1.1520974498489451), ([24, 40, 51, 77], -1.1480383074983678), ([21, 40, 56, 84], -1.147393308529583), ([40, 51, 77, 84], -1.147251886629011), ([21, 40, 84, 91], -1.1417909894162896), ([33, 40, 56, 91], -1.129417569411821), ([40, 51, 56, 77], -1.129040009876192), ([8, 21, 40, 56], -1.124060728660762), ([21, 40, 56, 77], -1.109223465980179), ([8, 18, 77, 84], -1.1082589748266187), ([40, 44, 56, 60], -1.1071600878250152), ([18, 33, 40, 91], -1.1057850109378329), ([8, 40, 56, 60], -1.104713944026006), ([8, 18, 33, 40], -1.1045399579727295), ([8, 18, 24, 33], -1.1030521769276262), ([21, 40, 77, 84], -1.098405338192972), ([20, 21, 40, 56], -1.0951037867126985), ([40, 56, 60, 77], -1.0856464042946), ([8, 18, 24, 84], -1.0853711579503482), ([20, 26, 40, 44], -1.0844407571503538), ([20, 40, 44, 56], -1.077619947349156), ([8, 56, 84, 91], -0.9635133589778206), ([18, 33, 84, 91], -0.842218748441951), ([33, 56, 84, 91], -0.824472136944749), ([33, 77, 84, 91], -0.7911483594993882), ([33, 44, 51, 56], -0.7856824500988608), ([18, 21, 44, 51], -0.7826155518689788), ([20, 77, 84, 91], -0.7788008937322992), ([33, 44, 77, 84], -0.7707031971170828), ([33, 51, 56, 84], -0.75745684560329), ([18, 33, 56, 84], -0.747835644272488), ([8, 44, 51, 56], -0.745543130312015), ([18, 33, 56, 91], -0.7055114291272098), ([20, 44, 51, 60], -0.6788242418810526), ([20, 44, 77, 84], -0.6420701614341695), ([8, 20, 44, 77], -0.629061313663037), ([18, 21, 44, 60], -0.626762329643789), ([18, 21, 51, 60], -0.5201371891029858), ([21, 24, 51, 60], -0.4102101684707406), ([18, 33, 91], -0.1116981698867363), ([24, 51, 84], -0.1029319843582161)]
-----------------
frozenset({'P', 'LSE', 'PA'}) 1
[([27, 36, 84], -0.115871996008364)]
-----------------
frozenset({'ED', 'LSE', 'BD'}) 5
[([2, 10, 41, 85], -0.9638610178867176), ([10, 27, 47, 85], -0.6469915810644586), ([10, 41, 47, 85], -0.6415853919825274), ([27, 41, 47, 85], -0.6393462763419073), ([27, 47, 85], -0.1005259043172532)]
-----------------
frozenset({'A', 'LSE', 'PA'}) 6
[([10, 78, 84, 86], -1.1178121638609753), ([10, 78, 84, 91], -0.9704699887591453), ([10, 41, 56, 66], -0.719985283607663), ([27, 41, 56, 66], -0.6575161380046772), ([10, 27, 56, 66], -0.6043507395750822), ([27, 56, 66], -0.111263438366798)]
-----------------
frozenset({'ED', 'LSE', 'PA'}) 14
[([10, 56, 84, 85], -0.7608758427614895), ([10, 67, 84, 85], -0.7395638187747018), ([10, 24, 50, 70], -0.7239071044035974), ([10, 41, 56, 85], -0.6796658601119496), ([27, 56, 84, 85], -0.6623293855184968), ([10, 27, 56, 85], -0.6551701671973511), ([41, 56, 84, 85], -0.6515377879922788), ([41, 83, 84, 85], -0.6260466470759845), ([27, 41, 56, 85], -0.6038694250859713), ([10, 41, 84, 85], -0.6008498617535558), ([10, 18, 50, 90], -0.5853604396210379), ([10, 27, 84, 85], -0.5679901368003577), ([27, 41, 84, 85], -0.5368415212350683), ([41, 56, 85], -0.1125682176977846)]
-----------------
frozenset({'A', 'IA', 'BD'}) 1
[([47, 54, 82], -0.1090821805959105)]
-----------------
frozenset({'ED', 'A'}) 6
[([66, 75, 85, 86], -0.8147402180539736), ([66, 75, 79, 85], -0.7276165576666607), ([66, 68, 85, 86], -0.5740205337874045), ([67, 72, 83, 88], -0.3544520669854165), ([66, 86, 90], -0.1227064156276149), ([68, 83, 85], -0.1113509865177064)]
-----------------
frozenset({'ED'}) 43
[([67, 70, 85, 90], -0.9359059985571108), ([67, 83, 85, 90], -0.8022540006044068), ([67, 70, 83, 90], -0.7995786316668827), ([67, 79, 85, 90], -0.7787821229576011), ([70, 83, 85, 90], -0.7499477103956274), ([67, 70, 83, 85], -0.7435057989851721), ([67, 70, 79, 85], -0.728507319841377), ([67, 70, 79, 90], -0.7195095950832275), ([67, 79, 83, 90], -0.7129844334356576), ([70, 79, 85, 90], -0.6821087539931696), ([67, 70, 79, 83], -0.6089832936315887), ([70, 79, 83, 90], -0.5585632198286419), ([79, 83, 85, 90], -0.5523092840611312), ([70, 79, 83, 85], -0.5387142682209856), ([70, 81, 83, 85], -0.5360524029374467), ([67, 81, 83, 85], -0.525092494948062), ([67, 79, 83, 85], -0.5122708799235056), ([67, 70, 81, 83], -0.4993979556649819), ([67, 70, 79, 81], -0.445412789174064), ([70, 79, 81, 85], -0.4277207513977963), ([67, 70, 81, 85], -0.4251810583682811), ([67, 79, 81, 85], -0.3970721483762993), ([70, 79, 81, 83], -0.3820159330191721), ([67, 70, 72, 83], -0.3794051363801394), ([67, 72, 79, 85], -0.3087459597369317), ([70, 72, 81, 83, 90], -0.2883688123026751), ([67, 70, 72, 85], -0.2749325425292142), ([70, 72, 79, 85], -0.2703443493006681), ([79, 81, 83, 85], -0.2593788150697662), ([70, 72, 79, 83], -0.2468242393094613), ([67, 81, 90], -0.1966792189663415), ([72, 79, 83, 85], -0.157172691278383), ([70, 83, 85], -0.1326741466776635), ([72, 81, 90], -0.1294421655446544), ([67, 72, 81], -0.1268461766681898), ([72, 79, 81], -0.11796621381459), ([72, 81, 83], -0.1177043754851965), ([67, 83, 90], -0.1159234599295579), ([79, 85, 90], -0.1132888227688369), ([67, 81, 85], -0.1114637662048334), ([70, 72, 81], -0.1102950124267874), ([67, 79, 83], -0.1006900166304962), ([67, 83, 85], -0.1000802647083922)]
-----------------
frozenset({'MF', 'DT', 'LSE', 'BD'}) 1
[([1, 2, 6, 27], -0.8368400741612589)]
-----------------
frozenset({'DT', 'BD'}) 24
[([1, 7, 19, 25], -0.761524108931475), ([1, 2, 19, 47], -0.6501091565782815), ([1, 2, 9, 59], -0.6407883077726062), ([1, 2, 7, 19], -0.5484599978384708), ([2, 11, 25, 32], -0.4864302814737762), ([2, 19, 47, 49], -0.4651149295478909), ([1, 45, 49, 59], -0.4544597313741079), ([1, 31, 45, 59, 62], -0.4423101517304637), ([2, 11, 25, 49], -0.4244191265269386), ([1, 19, 32, 55], -0.3872222269859193), ([1, 9, 45, 59], -0.3665517344269346), ([1, 7, 9, 16], -0.3532316498395325), ([7, 9, 16, 25], -0.3363600965957545), ([2, 25, 32, 49], -0.3286258389234753), ([1, 31, 55, 59, 62], -0.2735030167209693), ([1, 9, 32, 55], -0.2585602811759884), ([1, 9, 55, 59], -0.258556539743175), ([2, 11, 32, 49], -0.2480812103947585), ([2, 19, 32, 49], -0.1722233635150232), ([2, 9, 32, 45], -0.1528400677307466), ([1, 19, 31, 55, 62], -0.1401679589305899), ([7, 19, 32, 49], -0.1287129088404448), ([7, 32, 45, 49], -0.1278286583530068), ([2, 32, 45, 49], -0.1255587968483169)]
-----------------
frozenset({'DT', 'P', 'BD'}) 2
[([1, 2, 13, 47], -0.9465494736756064), ([2, 11, 32, 36], -0.4773330433916598)]
-----------------
frozenset({'DT', 'LSE', 'BD'}) 15
[([1, 2, 27, 47], -0.8514897584082597), ([1, 19, 25, 42], -0.836162569320642), ([1, 10, 41, 47], -0.7481171747718278), ([1, 37, 42, 62], -0.7161638122683094), ([1, 27, 45, 55], -0.7089931158204656), ([1, 2, 42, 47], -0.6975754975484705), ([1, 27, 50, 55], -0.68986508134833), ([1, 19, 42, 47], -0.6683048290706317), ([1, 27, 41, 47], -0.6629853664800329), ([1, 10, 27, 47], -0.6544730812362864), ([19, 25, 32, 42], -0.6506484096722858), ([7, 19, 32, 37], -0.2521381806000242), ([7, 32, 37, 45], -0.2433153483021826), ([12, 19, 32, 37, 62], -0.2063091210945593), ([32, 37, 45, 62], -0.1720461960574724)]
-----------------
frozenset({'DT', 'MF'}) 11
[([1, 6, 14, 35], -0.7807182996873507), ([1, 6, 22, 35], -0.7570518965232687), ([1, 6, 35, 39], -0.7060038438180243), ([1, 3, 6, 39], -0.6981944748996192), ([1, 3, 6, 22], -0.6952722546234611), ([1, 3, 6, 35], -0.6861002294397665), ([1, 3, 6, 16], -0.6181352008374681), ([1, 6, 14, 39], -0.6114743799729858), ([1, 6, 14, 22], -0.5858042300051949), ([1, 3, 6, 14], -0.5627492009828075), ([1, 6, 22, 39], -0.4782873125277334)]
-----------------
frozenset({'DT', 'LSE', 'MF'}) 5
[([1, 10, 35, 42], -1.0624548062884287), ([1, 3, 6, 42], -0.8040191047807355), ([1, 6, 35, 42], -0.8012046814998683), ([1, 6, 42, 48], -0.7465084102689126), ([1, 6, 27, 35], -0.6974854900750103)]
-----------------
frozenset({'ED', 'DT', 'MF'}) 1
[([1, 3, 6, 70], -0.8513928227204524)]
-----------------
frozenset({'B', 'DT'}) 22
[([1, 5, 7, 53], -0.9313410627152904), ([1, 25, 32, 53], -0.7957742189686741), ([1, 49, 53, 64], -0.7683817953056149), ([1, 7, 25, 53], -0.7650353265085137), ([1, 25, 49, 53], -0.7402719568484741), ([1, 7, 32, 53], -0.6356972164581371), ([7, 25, 32, 53], -0.6063047230184431), ([7, 25, 49, 53], -0.538657023272993), ([1, 16, 25, 53], -0.5335676502769324), ([1, 11, 61, 64], -0.5119118989543274), ([1, 7, 16, 53], -0.5021257057793491), ([1, 16, 32, 53], -0.4962626381666304), ([1, 7, 49, 53], -0.4783656355350523), ([16, 25, 32, 53], -0.4486955726060735), ([25, 32, 49, 53], -0.4147757858216039), ([7, 16, 25, 53], -0.3883095356017492), ([1, 16, 49, 53], -0.3572145242871016), ([7, 16, 32, 53], -0.2988487506432022), ([7, 32, 49, 53], -0.275826866479484), ([16, 25, 49, 53], -0.2289187031588397), ([7, 16, 49, 53], -0.1586024214671226), ([16, 32, 49, 53], -0.1153824175064919)]
-----------------
frozenset({'DT', 'PA', 'MF'}) 1
[([1, 6, 18, 24], -0.90162813373162)]
-----------------
frozenset({'LSE', 'DT', 'PA', 'MF'}) 2
[([1, 20, 35, 42], -0.8959901061253461), ([1, 6, 18, 27], -0.8500127863366984)]
-----------------
frozenset({'DT'}) 28
[([1, 7, 25, 32], -0.6618583516561571), ([1, 25, 32, 49], -0.5128758884013962), ([1, 16, 25, 32], -0.5004477072486893), ([1, 7, 25, 49], -0.4473449698307448), ([1, 11, 25, 32], -0.4389605088459092), ([1, 7, 16, 25], -0.4337120715356128), ([1, 11, 25, 49], -0.3934065103878055), ([7, 11, 25, 32], -0.3613658300918665), ([1, 7, 11, 25], -0.3590241585167391), ([1, 11, 32, 49], -0.3390146555167561), ([1, 7, 11, 32], -0.3019212763680805), ([1, 11, 16, 49], -0.2902905149085626), ([1, 7, 16, 32], -0.283420016068387), ([11, 16, 25, 32], -0.2819034262301478), ([1, 7, 11, 16], -0.2746322115410855), ([1, 16, 25, 49], -0.2520184296960046), ([11, 25, 32, 49], -0.2239922933931559), ([7, 11, 16, 25], -0.2178650860838651), ([7, 16, 25, 32], -0.2172949617028194), ([1, 16, 32, 49], -0.2151517895570762), ([1, 7, 32, 49], -0.2118571843112349), ([1, 7, 11, 49], -0.2083333259885726), ([7, 11, 25, 49], -0.2027820827216793), ([7, 11, 16, 32], -0.1907068401566043), ([1, 7, 16, 49], -0.1845820433973237), ([7, 25, 32, 49], -0.1658379874668263), ([7, 11, 32, 49], -0.1145784343972202), ([16, 25, 32, 49], -0.101421097746158)]
-----------------
frozenset({'IA', 'DT'}) 2
[([1, 7, 25, 30], -0.8646942165816753), ([1, 7, 30, 89], -0.7512045244452281)]
-----------------
frozenset({'ID', 'DT'}) 33

#### Patterns - to - hes - list : RED

In [144]:
scales_hes_RED = {}
for hg_name, hg in HGs_RED.items():
    scales_hes_RED[hg_name] = hnb.pattern_to_hes_list(hg, items_scales_dict, 'weight', False)

In [145]:
for layer, D in scales_hes_RED.items():
    print(layer)
    for k, val in D.items():
        print(k, len(val))
        print(val)
        print('-----------------')
    print('\n')

ANBP_RED
frozenset({'BD'}) 24
[([31, 45, 55, 59, 62], 0.3631796788126422), ([12, 19, 55, 62], 0.296679539545309), ([9, 45, 55], 0.2810383363406146), ([45, 55, 62], 0.261841682577705), ([9, 45, 55, 59], 0.2295813205180543), ([12, 19, 45, 59, 62], 0.2191317643260752), ([9, 55, 62], 0.2021145460497262), ([9, 45, 62], 0.1963873877675297), ([9, 12, 19, 31, 55], 0.1939259218755147), ([19, 55, 62], 0.1875858541347632), ([2, 12, 19], 0.1802370336264438), ([55, 59, 62], 0.1789274033280428), ([2, 12, 31, 55, 62], 0.169297250329194), ([31, 55, 62], 0.1543661865714227), ([19, 45, 62], 0.1524056163274174), ([9, 55, 59], 0.1491861635656519), ([2, 12, 45, 55, 62], 0.1467427589803875), ([31, 45, 55], 0.1456458760021721), ([12, 55, 62], 0.1441512122864097), ([9, 19, 31, 45, 55], 0.1433750031927232), ([9, 12, 19, 45, 62], 0.1385652261793168), ([9, 12, 19, 45, 55], 0.1326167951041057), ([2, 9, 19, 45, 62], 0.1270093143209827), ([2, 9, 12, 45, 55], 0.116993289111388)]
-----------------
frozenset({'DT', 'BD'}) 1
[([12, 19, 32, 55, 62], 0.3100831268747654)]
-----------------
frozenset({'B'}) 3
[([5, 28, 46], 0.2584298962457403), ([5, 28, 38], 0.2426276988642257), ([28, 38, 46], 0.1800280200938253)]
-----------------
frozenset({'II'}) 1
[([15, 34, 57], 0.1625699901551733)]
-----------------
frozenset({'MF'}) 1
[([22, 39, 58], 0.1403613106857744)]
-----------------


ANR_RED
frozenset({'DT', 'BD'}) 14
[([2, 9, 32, 45, 49], 0.2659780660826989), ([9, 32, 45], 0.2489132594581171), ([7, 9, 32, 45, 49], 0.2401130173179311), ([2, 32, 45], 0.2099659108521177), ([9, 16, 32], 0.2080120035315662), ([2, 16, 32], 0.2073711648469327), ([2, 7, 32, 45, 49], 0.202222192840086), ([9, 32, 49], 0.2018771740753351), ([2, 9, 32], 0.1859735384544389), ([7, 9, 32], 0.1783195480544179), ([9, 16, 49], 0.1780021909387876), ([2, 32, 49], 0.1663952716840633), ([9, 45, 49], 0.1439605285449179), ([2, 7, 16], 0.1359002288262072)]
-----------------
frozenset({'DT'}) 6
[([16, 32, 49], 0.2907638524933063), ([7, 16, 49], 0.262536067528945), ([7, 32, 49], 0.2597107466796267), ([7, 16, 32], 0.2273177254571745), ([16, 25, 49], 0.1569372894437233), ([16, 25, 32], 0.155310043222304)]
-----------------
frozenset({'BD'}) 15
[([31, 55, 59, 62], 0.2701831037812567), ([9, 45, 59], 0.2498984359662674), ([2, 9, 45, 59], 0.2361639591023774), ([9, 19, 45, 55, 62], 0.2046195259029382), ([19, 55, 62], 0.1889112199756368), ([9, 12, 45, 55, 62], 0.1824132763503598), ([55, 59, 62], 0.173056705461347), ([9, 55, 59], 0.1664148233689157), ([2, 9, 45], 0.1613440042361134), ([31, 55, 62], 0.1520938987742148), ([45, 59, 62], 0.1501035780121711), ([45, 55, 59], 0.1492287301167341), ([9, 55, 62], 0.1367748770157959), ([9, 45, 55], 0.1351679335916742), ([9, 59, 62], 0.1311852643314566)]
-----------------
frozenset({'ID'}) 2
[([21, 26, 60], 0.2302225277192562), ([21, 26, 51], 0.2017703200596408)]
-----------------
frozenset({'B'}) 1
[([5, 28, 38, 46, 61], 0.1175188488406213)]
-----------------
frozenset({'LSE', 'BD'}) 1
[([12, 19, 37, 55, 62], 0.1686785556583103)]
-----------------
frozenset({'LSE'}) 1
[([37, 41, 50], 0.1452899190445276)]
-----------------


BED_OSFED_RED
frozenset({'BD'}) 39
[([9, 45, 55, 59, 62], 0.7637829769694413), ([2, 12, 55, 59, 62], 0.3437590946972335), ([9, 12, 19, 45, 62], 0.3380359627777913), ([9, 12, 19, 31, 62], 0.3241609231350999), ([9, 12, 19, 31, 45], 0.3224986713709121), ([9, 19, 45, 47, 62], 0.2994511066771785), ([9, 12, 19, 45, 55], 0.2877931908300688), ([9, 45, 59, 62], 0.2797564122546792), ([12, 31, 55, 59, 62], 0.2635826222497996), ([2, 12, 31, 55, 62], 0.2526761863094577), ([2, 12, 31, 45, 62], 0.2516937961185874), ([2, 9, 12, 31, 62], 0.2330684135906722), ([12, 19, 31, 55, 62], 0.232145797214887), ([9, 12, 19, 59, 62], 0.2266842342182755), ([9, 12, 19, 31, 55], 0.2261257190809011), ([12, 19, 31, 59, 62], 0.2228583346092776), ([19, 31, 55, 59, 62], 0.2159288305957289), ([2, 9, 12, 59, 62], 0.2075453742572968), ([12, 45, 59, 62], 0.2060439480750648), ([9, 12, 45, 47, 55], 0.1968416891304976), ([45, 55, 62], 0.1965189341924702), ([12, 19, 31, 45, 55], 0.1938428101573599), ([9, 12, 19, 55, 59], 0.1811945163101533), ([9, 45, 55], 0.18091704082389), ([2, 12, 19, 45, 55], 0.1690360175786942), ([9, 12, 31, 55, 59], 0.162688880961074), ([2, 12, 45, 47, 62], 0.1598982498022323), ([55, 59, 62], 0.1540386970173735), ([9, 31, 45, 62], 0.1509741659926788), ([9, 55, 62], 0.1386685453404208), ([9, 19, 45, 55], 0.1364791058159458), ([31, 45, 59, 62], 0.1344814600104484), ([2, 9, 45, 62], 0.1253851608073226), ([9, 31, 59, 62], 0.1228709632358597), ([2, 12, 62], 0.1155274355831554), ([9, 12, 19, 31, 59], 0.1143525119723136), ([19, 31, 45, 62], 0.1132389194969771), ([12, 55, 62], 0.112044235522883), ([2, 19, 55, 59, 62], 0.1071153469985404)]
-----------------
frozenset({'DT'}) 11
[([7, 16, 25, 32, 49], 0.4889048428234552), ([7, 16, 32, 49], 0.2319250729123467), ([1, 7, 11, 16, 49], 0.2273698656484661), ([7, 16, 25, 32], 0.2248756735571877), ([16, 25, 32, 49], 0.222531707164368), ([7, 11, 16, 32], 0.1991427176544462), ([11, 16, 25, 32], 0.1824792450118018), ([1, 7, 11, 16, 25], 0.1633682654275787), ([11, 16, 32, 49], 0.1594095967236057), ([7, 11, 16, 49], 0.1514788024431261), ([1, 11, 16, 25, 49], 0.1345001458258963)]
-----------------
frozenset({'A', 'DT', 'BD'}) 1
[([1, 2, 11, 16, 68], 0.10766623923638)]
-----------------
frozenset({'DT', 'BD'}) 12
[([9, 16, 32, 45, 62], 0.4820359051583303), ([1, 7, 9, 11, 16], 0.2535941694296859), ([1, 2, 16, 32, 45], 0.2468750849137961), ([1, 2, 16, 45, 49], 0.2332679962445034), ([12, 19, 31, 32, 45], 0.2234518920529602), ([1, 16, 19, 32, 45], 0.2225180500980705), ([1, 2, 11, 16, 49], 0.1990074095638938), ([1, 11, 16, 47, 49], 0.1362647667362608), ([1, 2, 12, 32, 45], 0.1295312053678472), ([2, 7, 16, 49], 0.1215419267023847), ([1, 9, 11, 16, 19], 0.1182723254735123), ([2, 7, 11, 16], 0.1021344015210186)]
-----------------
frozenset({'B'}) 11
[([4, 5, 28, 38, 46], 0.9044413308352404), ([5, 28, 38, 46, 61], 0.8822551643409895), ([5, 28, 38, 46], 0.5331013218188172), ([5, 38, 46], 0.2645365233168704), ([5, 28, 38], 0.2512835540586309), ([5, 28, 46], 0.2186099531788379), ([4, 5, 38, 61], 0.2107872214924988), ([5, 46, 61], 0.1778039819903529), ([28, 38, 46], 0.1758354840589699), ([4, 5, 46], 0.1573964568689696), ([4, 5, 28], 0.1552638207271233)]
-----------------
frozenset({'B', 'BD'}) 1
[([4, 5, 28, 46, 47], 0.35403800621242)]
-----------------
frozenset({'B', 'DT'}) 2
[([5, 11, 28, 38, 46], 0.5880789596035179), ([7, 16, 32, 49, 53], 0.2408145093367899)]
-----------------
frozenset({'B', 'DT', 'BD'}) 1
[([5, 11, 28, 46, 47], 0.1336729380844303)]
-----------------
frozenset({'A', 'DT'}) 2
[([7, 11, 16, 49, 68], 0.2478988534184409), ([1, 11, 16, 49, 68], 0.1465998698615216)]
-----------------


BN_RED
frozenset({'BD'}) 18
[([12, 19, 31, 55, 62], 0.2511404261833156), ([45, 55, 62], 0.2463196007297057), ([9, 45, 62], 0.1908748235049291), ([9, 45, 55], 0.1861628934966948), ([45, 59, 62], 0.184457437557004), ([45, 55, 59], 0.1763879380143365), ([9, 55, 62], 0.1713393248098196), ([2, 9, 12, 19, 55], 0.1583101041434957), ([55, 59, 62], 0.1576702374410459), ([12, 19, 55, 62], 0.1560788536200021), ([9, 12, 19, 45, 62], 0.1544212961035391), ([2, 19, 31, 55, 62], 0.1524930453983728), ([2, 12, 31, 55, 62], 0.1431226230803908), ([31, 55, 62], 0.1356992694104928), ([9, 55, 59], 0.1344933348468338), ([9, 45, 59], 0.1238605950657394), ([2, 12, 19], 0.1171628254748355), ([9, 12, 19, 31, 55], 0.1041273031663294)]
-----------------
frozenset({'ID'}) 1
[([21, 51, 60], 0.2103563326824389)]
-----------------
frozenset({'B'}) 1
[([4, 5, 38], 0.1422196931366706)]
-----------------