# Diagnosis multiplex hyperedges selection: cliques expansion (POLY)

In [1]:
import pandas as pd
import numpy as np
import hypernetx as hnx
import networkx as nx
import igraph as ig
import matplotlib.pyplot as plt
from itertools import combinations
from math import comb, ceil  # binomial coefficient in Python >=3.8
from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import Dict, Iterable, List, Sequence, Tuple
from scipy.special import erf, erfinv
from scipy.stats import rankdata, norm, multivariate_normal
from scipy.optimize import minimize_scalar
import time
from joblib import Parallel, delayed
from statsmodels.stats.multitest import multipletests
import json
import pickle
from pathlib import Path

import os
import sys

In [2]:
# get parent directory
parent_dir = os.path.abspath("..")
sys.path.append(parent_dir)

import preprocessing.candidate_multiplets as cand_mult

import optim_help.O_Information as o_infoptim
import optim_help.paral_perm_bootstrap as pp_bootopt
import optim_help.BCa_bootstrap as bca_bootopt
import optim_help.mult_sel_minimal as sel

import optim_help.plots.o_info_bootstrap_plots as o_plots
import optim_help.plots.BCa_plots as bca_plots

import optim_help.utilities as ut

C:\Users\utente\anaconda3\envs\thesis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## LOADING DATA

### Data_frames per diagnosis

- **EDI_diags** : the datasets dictionary, where a dataframe of raw data (items as columns, subjects as rows) is associated with the specific diagnosis.

In [3]:
data_path = '../../DATA/EDI_DIAG' # contains csv files for each diagnoses
EDI_diags_paths = [
    data_path + '/' + f
    for f in os.listdir(data_path)
    if f.lower().endswith('.csv') and os.path.isfile(os.path.join(data_path, f))
]

In [4]:
EDI_diags = {}
for path in EDI_diags_paths:
    EDI_diags[Path(path).stem] = ut.preproc_df(path)

In [5]:
EDI_diags.keys()

dict_keys(['ANBP', 'ANR', 'BED_OSFED', 'BN'])

In [6]:
EDI_diags['ANBP'].describe(include='all')

,1,2,3,4,5,6,7,8,9,10,...,82,83,84,85,86,87,88,89,90,91
count,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,...,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000
mean,2.683398,2.598456,1.474903,1.366795,1.254826,1.135135,2.683398,2.073359,2.447876,2.223938,...,1.243243,1.791506,2.274131,2.003861,2.030888,2.054054,1.046332,0.984556,0.911197,2.559846
std,1.291052,1.403538,1.460841,1.381150,1.376972,1.386913,1.452128,1.480632,1.606728,1.387949,...,1.317261,1.376352,1.394253,1.339611,1.465036,1.262524,1.190147,1.181147,1.246635,1.200488
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.500000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000
50%,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,3.000000,2.000000,...,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,3.000000
75%,4.000000,4.000000,3.000000,3.000000,2.000000,2.000000,4.000000,3.000000,4.000000,4.000000,...,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,3.000000
max,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

### Combinatorial explosion: a problem to be addressed.

In [7]:
elements = list(range(1, 92))
sizes = [3, 4, 5]

# Build dict
multiplets_dict = {k: list(combinations(elements, k)) for k in sizes}
for i, l in enumerate([len(L) for L in multiplets_dict.values()]):
    print('Size', sizes[i], ':', l, 'possible combinations.')

# 3 121485    1140  (20 items)
# 4 2672670   4845  (20 items)
# 5 46504458  15504 (20 items)

Size 3 : 121485 possible combinations.
Size 4 : 2672670 possible combinations.
Size 5 : 46504458 possible combinations.

### Graphs, polychoric matrices per diagnosis

Create **dictionaries** containing all the necessary data for further computations:

- **graphs_diags** : a nx graph is associated with the diagnosis;
    - graph is loaded from **graphml** object previously computed in R: graph_from_adjacency_matrix based on **polychoric correlation** and **EBICglasso**;
- **poly_matrices_diags** : the polychoric correlation matrix which the graph is based on is associated with the diagnosis.

In [8]:
# GRAPHS -------------------------------------------------
# C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\DATA\GRAPHS_DIAG\POLY_graphs
graph_data_path = '../../DATA/GRAPHS_DIAG/POLY_graphs'

graphs_diags_paths = [
    graph_data_path + '/' + f
    for f in os.listdir(graph_data_path)]

graphs_diags = {}
for path in graphs_diags_paths:
    G_polychor = nx.read_graphml(path)
    # rename the nodes to have the item index as name
    mapping = {name: str(int(name.replace("n", "")) + 1) for name in G_polychor.nodes()}
    key = Path(path).stem.split('_')[0]
    # manually correct the BED_OSFED key
    if key == 'BED':
        key = 'BED_OSFED'
    graphs_diags[key] = nx.relabel_nodes(G_polychor, mapping) 
    
print(graphs_diags.keys())

dict_keys(['ANBP', 'ANR', 'BED_OSFED', 'BN'])

In [9]:
print(graphs_diags['ANR'].nodes)
print(len(graphs_diags['ANR'].edges))

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91']
759

In [10]:
# POLYCHORIC MATRICES ------------------------------------
poly_matrices_data_path = '../../DATA/GRAPHS_DIAG/POLY_mat'

poly_matrices_paths = [
    poly_matrices_data_path + '/' + f
    for f in os.listdir(poly_matrices_data_path)
    if f.lower().endswith('.csv') and os.path.isfile(os.path.join(poly_matrices_data_path, f))
]

poly_matrices_diags = {}
for path in poly_matrices_paths:
    key = Path(path).stem.split('_')[0]
    # manually correct the BED_OSFED key
    if key == 'BED':
        key = 'BED_OSFED'
    poly_matrices_diags[key] = cand_mult.load_correlation_matrix_R(path)
    
print(poly_matrices_diags.keys())

dict_keys(['ANBP', 'ANR', 'BED_OSFED', 'BN'])

In [11]:
poly_matrices_diags['ANBP'].shape

(91, 91)

## Multiplets Selection

### Assumptions on Graphs

- Graphs are connected and undirected
- Weights can be negative
- Spinglass community detection algorithm can handle negative weights and works well with small graphs


### Goal

Given a set of items (Likert variables), we need to select candidate multiplets that are likely to contain **higher-order dependencies**, so they can be statistically validated with the **Ω-information pipeline**. This selection step is necessary to avoid combinatorial explosion.

### Procedure — Stage 1: Pre-selection

> **Paper cited:** Contisciani, M., Battiston, F., & De Bacco, C. (2022). *Inference of hyperedges and overlapping communities in hypergraphs.* Nature Communications, 13, 7229. https://doi.org/10.1038/s41467-022-34714-7

#### Step 1 — Community Detection and Membership Matrix $U$

Communities are detected from the dyadic item network via **Spinglass** and encoded in a hard membership matrix $U$, which serves as a structural prior for candidate multiplet quality.

- Detect Spinglass communities from the weighted graph
- Convert community assignments to a matrix:

$$U \in \{0,1\}^{N \times K}$$

where $u_i$ is the **one-hot membership vector** for item $i$, and $K$ is the number of detected communities.

#### Step 2 — Inter-community Affinity Matrix $W$

The affinity matrix $W \in \mathbb{R}^{K \times K}$ is estimated from the polychoric/correlation matrix if provided, otherwise from graph edge weights:

$$W_{kl} = \frac{\sum_{i \in \mathcal{C}_k,\ j \in \mathcal{C}_l,\ i < j} |R_{ij}|}{|\{(i,j) : i \in \mathcal{C}_k,\ j \in \mathcal{C}_l,\ i < j\}|}$$

where $R_{ij}$ is the correlation between items $i$ and $j$, and $\mathcal{C}_k$ is the set of items in community $k$.

- **Diagonal** $W_{kk}$: intra-community cohesion
- **Off-diagonal** $W_{kl}$: inter-community affinity — how much communities $k$ and $l$ co-move
- High values indicate strongly coupled communities
- A small ridge $\varepsilon$ is added for numerical stability: $W \leftarrow W + \varepsilon$

#### Step 3 — Seed Generation and Scoring

Candidate multiplets are seeded from **maximal cliques** of size $d \in [d_{\min}, d_{\max}]$, extracted via the Bron-Kerbosch algorithm. Cliques larger than $d_{\max}$ are decomposed into all $k$-subsets within the allowed range, ensuring coverage at multiple scales.

Each candidate hyperedge $e$ is ranked with a relaxed **Contisciani-style score**:

$$S(e) = \kappa(|e|) \sum_{i < j \in e} u_i^\top W u_j$$

Since $u_i$ and $u_j$ are one-hot vectors, this reduces to:

$$u_i^\top W u_j = W_{c(i),\ c(j)}$$

which captures the affinity between the communities of items $i$ and $j$.

The **size penalty** $\kappa$ (default: factorial) is:

$$\kappa(|e|) = \frac{1}{|e|!}$$

This penalty:
- strongly discourages large multiplets, favouring small coherent groups
- matches the hyperedge size prior implicit in Contisciani et al. (2022)

A multiplet scores **high** if:
- its items belong to community pairs with strong affinity (high $W_{kl}$)
- its size is not too large (penalized by $\kappa$)

> The score acts as a **structural prior**: *"Is this group supported by the mesoscale community structure?"*

**Relation to Contisciani et al. (2022).** The original model uses a multiplicative score:

$$\lambda(e) = \sum_k w_{d,k} \prod_{i \in e} u_{ik}$$

which requires all nodes in $e$ to share a common community to yield a non-zero contribution. We adopt a relaxed **additive pairwise** formulation for two reasons: (1) the score serves as a pre-filter to produce a broad but plausible candidate pool, not to infer community structure directly; (2) final hyperedge selection is delegated to Ω-information, which can detect higher-order dependencies spanning multiple communities — candidates that a purely intra-community criterion would suppress prematurely.

#### Step 4 — Greedy Expansion

The highest-scoring seeds are **greedily expanded** by adding neighboring nodes, always starting from the original seed (never from derived candidates, to avoid quality drift and combinatorial explosion).

For each seed of size $d$, the algorithm tries to add $k = 1, 2, \ldots, d_{\max} - d$ nodes from the seed's neighborhood, accepting the expansion only if:

$$S(e_{\text{expanded}}) \geq S(e_{\text{seed}}) \cdot (1 + \delta)$$

where $\delta$ is a minimum relative gain threshold (default: $\delta = 0.05$, i.e. 5%).

This produces, for example:
- size-3 seeds → size-4 and size-5 derived candidates
- size-4 seeds → size-5 derived candidates
- size-5 seeds → kept as-is

Only the **top $m$ best expansions** per (seed, expansion size) pair are retained, to control branching. When the number of possible neighbor subsets exceeds a threshold, random sampling is used instead of full enumeration.

## Summary

The candidate-multiplet procedure begins by extracting the mesoscale structure of the item network. Communities are detected from the dyadic graph and encoded in a hard membership matrix $U$, while an inter-community affinity matrix $W$ is estimated either from polychoric correlations or graph edge weights. These two structural priors capture how strongly different item communities cohere or interact.

Using this information, the algorithm seeds candidate groups by identifying all maximal cliques in the item graph within a chosen size range; large cliques are decomposed so that all relevant subgroups are considered. Each seed is scored using a Contisciani-style hyperedge score, which rewards sets supported by strong within- and between-community affinities while penalizing excessively large groups through the $\kappa$ term.

The highest-scoring seeds are subsequently expanded greedily — always from the original seed — adding neighbors that improve the score by a minimum relative gain, thus capturing near-cliques and other dense, well-supported subsets that may not be perfect cliques. Finally, all candidates are organized by size and returned as structured multiplet sets, ready to be evaluated with the Ω-information bootstrap.

In [12]:
out_dir = "POLY_candidates"            
os.makedirs(out_dir, exist_ok=True)

In [20]:
cfg = cand_mult.CandidateConfig(
    k_min=3,
    k_max=5,
    max_initial=None,  # limit if needed
    kappa_mode="factorial",  # stronger downweight for large sets
    expand_max_size=5,  # allow growth beyond cliques 
    expand_top_per_seed=1,  # keep expansions under control
    expand_min_gain_ratio=0.05,  # +5% score improvement to accept
    top_per_size= None, # None or X to keep top X per size; tune as needed
    expand=True # def is True, set according available resources
)

multiplets_diags = {}
for diagnosis in graphs_diags.keys():
    print(diagnosis)
    start = time.perf_counter()
    
    G_nx = graphs_diags[diagnosis]
    G_ig = ig.Graph.from_networkx(G_nx)  
    weights = G_ig.es["weight"] if "weight" in G_ig.es.attributes() else None

    R = poly_matrices_diags[diagnosis]
    # passing R to function
    multiplets_diags[diagnosis] = cand_mult.build_candidate_multiplets(G_ig, R=R, cfg=cfg)
    
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")
    
    fname = f"{diagnosis}_candidates.pkl"
    fpath = os.path.join(out_dir, fname)
    with open(fpath, "wb") as f:
        pickle.dump(multiplets_diags[diagnosis], f, protocol=pickle.HIGHEST_PROTOCOL)

ANBP
  original candidates   : 689
Expanding original candidates...

── expand_candidates summary ──────────────────
  original candidates   : 689
  new candidates added  : 931
  total pool size       : 1620
  skipped (seen)        : 1170
  skipped (score)       : 0
  seeds with sampling   : 0
───────────────────────────────────────────────

Runtime: 9.806329 s
ANR
  original candidates   : 764
Expanding original candidates...

── expand_candidates summary ──────────────────
  original candidates   : 764
  new candidates added  : 1019
  total pool size       : 1783
  skipped (seen)        : 1440
  skipped (score)       : 0
  seeds with sampling   : 0
───────────────────────────────────────────────

Runtime: 10.547433 s
BED_OSFED
  original candidates   : 581
Expanding original candidates...

── expand_candidates summary ──────────────────
  original candidates   : 581
  new candidates added  : 762
  total pool size       : 1343
  skipped (seen)        : 798
  skipped (score)       : 0
  seeds with sampling   : 0
───────────────────────────────────────────────

Runtime: 7.040161 s
BN
  original candidates   : 578
Expanding original candidates...

── expand_candidates summary ──────────────────
  original candidates   : 578
  new candidates added  : 778
  total pool size       : 1356
  skipped (seen)        : 515
  skipped (score)       : 0
  seeds with sampling   : 0
───────────────────────────────────────────────

Runtime: 7.897457 s

In [22]:
for diag in multiplets_diags:
    print_ = diag
    tot = 0
    for order in multiplets_diags[diag]:
        tot += len(multiplets_diags[diag][order])
        print_ = print_ + ', ' + str(order) + ':' + str(len(multiplets_diags[diag][order]))
    print(print_ + ', TOTAL is', str(tot))

ANBP, 5:689, 4:602, 3:329, TOTAL is 1620
ANR, 5:764, 4:642, 3:377, TOTAL is 1783
BED_OSFED, 5:581, 4:517, 3:245, TOTAL is 1343
BN, 5:578, 4:513, 3:265, TOTAL is 1356

####  Compute $\Omega$-information for each multiplet to filter the pre-selected multiplets.

In [23]:
presel_mults_diags = {}
for diagnosis, multiplets in multiplets_diags.items():
    start = time.perf_counter()
    # multiplets is a dict such as: order: multiplets df
    presel_mults_diags[diagnosis] = pp_bootopt.filter_multiplets_by_omega(multiplets_dict = multiplets,
                                                                             X = EDI_diags[diagnosis],
                                                                             threshold=0.1)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s for {diagnosis}")

Runtime: 3.738761 s for ANBP
Runtime: 4.278381 s for ANR
Runtime: 2.668002 s for BED_OSFED
Runtime: 3.470984 s for BN

In [24]:
for diag in presel_mults_diags:
    print_ = diag
    tot = 0
    for order in presel_mults_diags[diag]:
        tot += len(presel_mults_diags[diag][order])
        print_ = print_ + ', ' + str(order) + ':' + str(len(presel_mults_diags[diag][order]))
    print(print_ + ', TOTAL is', str(tot))

ANBP, 5:683, 4:593, 3:177, TOTAL is 1453
ANR, 5:737, 4:599, 3:138, TOTAL is 1474
BED_OSFED, 5:550, 4:497, 3:178, TOTAL is 1225
BN, 5:575, 4:505, 3:79, TOTAL is 1159

In [25]:
multiplets_diags = presel_mults_diags

## Procedure - Stage 2: Selection

Given a multivariate system X = {X₁, X₂, ..., Xₙ} (representing EDI-3 items), we construct a multiplex hypergraph based on statistically validated higher-order interactions. The global Ω(X₁, ..., Xₙ) summarizes the balance between redundancy and synergy, but can mask localized effects. To identify statistically significant interactions, we evaluate Ω-information on candidate multiplets of order k ∈ {3, 4, 5} through a three-stage validation pipeline, following Marinazzo et al. (2024).

---

### Entropy-Based Ω-Information Computation

**Definition:**

For a set of variables X = {X₁, X₂, ..., Xₖ}, the Ω-information quantifies higher-order interactions:

Ω(X₁, X₂, ..., Xₖ) = Σᵢ H(Xᵢ) - H(X₁, X₂, ..., Xₖ)

Where:
- H(Xᵢ) = Shannon entropy of single variable
- H(X₁, X₂, ..., Xₖ) = Joint entropy of all variables
- Ω > 0: Variables share redundant information
- Ω < 0: Variables interact synergistically (information emerges from combination)

**Computation Method:**

1. **Empirical probability estimation:**
   - Count observed frequencies of each category combination
   - Compute probabilities: P(x₁, x₂, ..., xₖ) = count / n_samples

2. **Entropy calculation:**
   - H(X) = -Σₓ P(x) log P(x)  [typically log₂ or log_e]
   - Applied to marginal distributions for H(Xᵢ)
   - Applied to joint distribution for H(X₁, ..., Xₖ)

3. **Why entropy-based?**
   - Works directly on observed discrete variables (Likert responses)
   - No distributional assumptions required
   - Captures "What is the multivariate interaction in the observed ordinal data?"
   - Computationally efficient for discrete data

---

### Part 1: Significance Testing via Permutation Test

**Purpose:** Identify multiplets with statistically significant Ω-information values.

**Procedure:**

1. **Compute Ω-information** for all candidate multiplets of order k = 3, 4, 5:
   - Ω > 0: Redundancy (overlapping information across variables)
   - Ω < 0: Synergy (emergent, non-decomposable interaction)
   - Ω ≈ 0: No higher-order effect

2. **Column-wise permutation test:**
   - For each multiplet, independently shuffle each variable while preserving marginal distributions
   - This destroys multivariate dependence, yielding a null distribution for Ω
   - Compute two-tailed p-values from null distribution

3. **Multiple comparison correction:**
   - Apply FDR correction via Benjamini–Hochberg method (Benjamini & Hochberg, 1995)
   - Retain multiplets with adjusted p < 0.05

4. **Effect-size filtering:**
   - Apply threshold on absolute Ω: retain only |Ω| ≥ 0.15
   - Rationale: Treat smaller effects as negligible and filter out spurious significance

**Output:** Pruned set of multiplets with significant non-trivial effects

---

#### Implementation Notes

- **Pipeline stages are sequential:** Each stage builds on the validated output of the previous stage
- **Conservative filtering:** Multiple validation criteria ensure low false-positive rate
- **Computational complexity:** O(2^k) for k-multiplet enumeration; practical for k ≤ 5
- **Significance level:** α = 0.05 (with FDR correction in Stage 1)
- **Bootstrap samples:** Recommended n_bootstrap ≥ 1000 for stable CI estimation

---

#### References

- Benjamini, Y., & Hochberg, Y. (1995). Controlling the false discovery rate: A practical and powerful approach to multiple testing. *Journal of the Royal Statistical Society: Series B*, 57(1), 289–300.
- DiCiccio, T. J., & Efron, B. (1996). Bootstrap confidence intervals. *Statistical Science*, 11(3), 189–212.
- Efron, B., & Tibshirani, R. J. (1994). *An introduction to the bootstrap*. Chapman and Hall/CRC.
- Efron, B., & Narasimhan, B. (2020). The automatic percentile bootstrap. *arXiv preprint arXiv:2001.03263*.
- Marinazzo, D., et al. (2024). Ω-information and higher-order interactions in complex systems. *[Citation needed]*.

In [27]:
n_iter_boot = 1000

In [30]:
# skip dir creation if it already exist
out_dir = "POLY_part1_perm_boot"  
os.makedirs(out_dir, exist_ok=True)

perm_boot_diags = {}
for diagnosis, multiplets in multiplets_diags.items():
    start = time.perf_counter()
    # multiplets is a dict such as: order: multiplets df
    perm_boot_diags[diagnosis] = pp_bootopt.perm_bootstrap_parallel(multiplets_dict=multiplets,
                                                                    X=EDI_diags[diagnosis], 
                                                                    n_boot=n_iter_boot)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")
    
    fname = f"{diagnosis}_perm_boot_mults.pkl"
    fpath = os.path.join(out_dir, fname)
    with open(fpath, "wb") as f:
        pickle.dump(perm_boot_diags[diagnosis], f, protocol=pickle.HIGHEST_PROTOCOL)

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=5:   0%|0/683 |          | 00:00

  Multiplets | order=5:  25%|171/683 |██▌       | 01:33

  Multiplets | order=5:  50%|342/683 |█████     | 03:01

  Multiplets | order=5:  75%|513/683 |███████▌  | 04:30

  Multiplets | order=5: 100%|683/683 |██████████| 05:58

Families:  33%|███▎      | 1/3 [05:58<11:56, 358.27s/it][A

  Multiplets | order=4:   0%|0/593 |          | 00:00

  Multiplets | order=4:  25%|149/593 |██▌       | 00:58

  Multiplets | order=4:  50%|298/593 |█████     | 01:57

  Multiplets | order=4:  75%|447/593 |███████▌  | 02:55

  Multiplets | order=4: 100%|593/593 |██████████| 03:54

Families:  67%|██████▋   | 2/3 [09:52<04:45, 285.27s/it][A

  Multiplets | order=3:   0%|0/177 |          | 00:00

  Multiplets | order=3:  25%|45/177 |██▌       | 00:12

  Multiplets | order=3:  51%|90/177 |█████     | 00:24

  Multiplets | order=3:  76%|135/177 |███████▋  | 00:38

  Multiplets | order=3: 100%|177/177 |██████████| 00:50

Runtime: 643.038612 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=5:   0%|0/737 |          | 00:00

  Multiplets | order=5:  25%|185/737 |██▌       | 02:03

  Multiplets | order=5:  50%|370/737 |█████     | 04:03

  Multiplets | order=5:  75%|555/737 |███████▌  | 06:04

  Multiplets | order=5: 100%|737/737 |██████████| 08:05

Families:  33%|███▎      | 1/3 [08:05<16:11, 485.60s/it][A

  Multiplets | order=4:   0%|0/599 |          | 00:00

  Multiplets | order=4:  25%|150/599 |██▌       | 01:14

  Multiplets | order=4:  50%|300/599 |█████     | 02:30

  Multiplets | order=4:  75%|450/599 |███████▌  | 03:44

  Multiplets | order=4: 100%|599/599 |██████████| 04:58

Families:  67%|██████▋   | 2/3 [13:03<06:15, 375.40s/it][A

  Multiplets | order=3:   0%|0/138 |          | 00:00

  Multiplets | order=3:  25%|35/138 |██▌       | 00:12

  Multiplets | order=3:  51%|70/138 |█████     | 00:25

  Multiplets | order=3:  76%|105/138 |███████▌  | 00:37

  Multiplets | order=3: 100%|138/138 |██████████| 00:50

Runtime: 834.313084 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=5:   0%|0/550 |          | 00:00

  Multiplets | order=5:  25%|138/550 |██▌       | 01:03

  Multiplets | order=5:  50%|276/550 |█████     | 02:08

  Multiplets | order=5:  75%|414/550 |███████▌  | 03:14

  Multiplets | order=5: 100%|550/550 |██████████| 04:24

Families:  33%|███▎      | 1/3 [04:24<08:49, 264.77s/it][A

  Multiplets | order=4:   0%|0/497 |          | 00:00

  Multiplets | order=4:  25%|125/497 |██▌       | 00:53

  Multiplets | order=4:  50%|250/497 |█████     | 01:40

  Multiplets | order=4:  75%|375/497 |███████▌  | 02:28

  Multiplets | order=4: 100%|497/497 |██████████| 03:10

Families:  67%|██████▋   | 2/3 [07:35<03:40, 220.99s/it][A

  Multiplets | order=3:   0%|0/178 |          | 00:00

  Multiplets | order=3:  25%|45/178 |██▌       | 00:11

  Multiplets | order=3:  51%|90/178 |█████     | 00:23

  Multiplets | order=3:  76%|135/178 |███████▌  | 00:36

  Multiplets | order=3: 100%|178/178 |██████████| 00:47

Runtime: 502.890184 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=5:   0%|0/575 |          | 00:00

  Multiplets | order=5:  25%|144/575 |██▌       | 01:49

  Multiplets | order=5:  50%|288/575 |█████     | 03:37

  Multiplets | order=5:  75%|432/575 |███████▌  | 05:31

  Multiplets | order=5: 100%|575/575 |██████████| 07:19

Families:  33%|███▎      | 1/3 [07:19<14:39, 439.79s/it][A

  Multiplets | order=4:   0%|0/505 |          | 00:00

  Multiplets | order=4:  25%|127/505 |██▌       | 01:11

  Multiplets | order=4:  50%|254/505 |█████     | 02:22

  Multiplets | order=4:  75%|381/505 |███████▌  | 03:34

  Multiplets | order=4: 100%|505/505 |██████████| 04:43

Families:  67%|██████▋   | 2/3 [12:03<05:48, 348.08s/it][A

  Multiplets | order=3:   0%|0/79 |          | 00:00

  Multiplets | order=3:  25%|20/79 |██▌       | 00:07

  Multiplets | order=3:  51%|40/79 |█████     | 00:15

  Multiplets | order=3:  76%|60/79 |███████▌  | 00:23

  Multiplets | order=3: 100%|79/79 |██████████| 00:31

Runtime: 755.111883 s

### Stage 2, part 1: plots.

In [31]:
base = 'POLY_part1_plots/'
perm_summary_tables = {}
for diag, out in perm_boot_diags.items():
    perm_summary_tables[diag] = o_plots.save_all_figures(out, output_dir=base + diag + "_figures")

Saved -> POLY_part1_plots/ANBP_figures\fig1_null_distributions.pdf
Saved -> POLY_part1_plots/ANBP_figures\fig2_omega_scatter.pdf
Saved -> POLY_part1_plots/ANBP_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:

Saved -> POLY_part1_plots/ANBP_figures\fig4_volcano.pdf
Supplementary table saved → POLY_part1_plots/ANBP_figures\supplementary_table.csv  (1453 multiplets)
Saved -> POLY_part1_plots/ANR_figures\fig1_null_distributions.pdf
Saved -> POLY_part1_plots/ANR_figures\fig2_omega_scatter.pdf
Saved -> POLY_part1_plots/ANR_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:

Saved -> POLY_part1_plots/ANR_figures\fig4_volcano.pdf
Supplementary table saved → POLY_part1_plots/ANR_figures\supplementary_table.csv  (1474 multiplets)
Saved -> POLY_part1_plots/BED_OSFED_figures\fig1_null_distributions.pdf
Saved -> POLY_part1_plots/BED_OSFED_figures\fig2_omega_scatter.pdf
Saved -> POLY_part1_plots/BED_OSFED_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:

Saved -> POLY_part1_plots/BED_OSFED_figures\fig4_volcano.pdf
Supplementary table saved → POLY_part1_plots/BED_OSFED_figures\supplementary_table.csv  (1225 multiplets)
Saved -> POLY_part1_plots/BN_figures\fig1_null_distributions.pdf
Saved -> POLY_part1_plots/BN_figures\fig2_omega_scatter.pdf
Saved -> POLY_part1_plots/BN_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:600: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  def _save(fig: plt.Figure, name: str) -> None:

Saved -> POLY_part1_plots/BN_figures\fig4_volcano.pdf
Supplementary table saved → POLY_part1_plots/BN_figures\supplementary_table.csv  (1159 multiplets)

Load pickle files.

In [32]:
# Load
with open("POLY_part1_perm_boot/ANBP_perm_boot_mults.pkl", "rb") as f:
    ANBP_perm_boot = pickle.load(f)

with open("POLY_part1_perm_boot/ANR_perm_boot_mults.pkl", "rb") as f:
    ANR_perm_boot = pickle.load(f)

with open("POLY_part1_perm_boot/BED_OSFED_perm_boot_mults.pkl", "rb") as f:
    BED_OSFED_perm_boot = pickle.load(f)

with open("POLY_part1_perm_boot/BN_perm_boot_mults.pkl", "rb") as f:
    BN_perm_boot = pickle.load(f)


# rebuild general dictionary
perm_boot_diags = {
    'ANBP' : ANBP_perm_boot,
    'ANR' : ANR_perm_boot,
    'BED_OSFED' : BED_OSFED_perm_boot,
    'BN' : BN_perm_boot,
}

### "Shifted" permutation-based null distribution
In the empirical analyses, the permutation-based null distribution of the $\Omega$-information exhibits a noticeable shift toward negative values (often around $-2$) rather than being centered at zero, as expected from synthetic (benchmark) data. This may originate from a property of applying column-wise permutation tests to real-world categorical data such as Likert-type survey responses. The permutation scheme enforces a null hypothesis of complete statistical independence across variables while **preserving the empirical marginal distributions** of each item. Because real psychometric items typically show unbalanced category frequencies, heterogeneous entropy across items, the expected value of multivariate interaction measures under this form of independence is generally not equal to zero. 

In particular, marginal imbalance inflates both the joint entropy and the exclusion entropies in a direction that systematically
drives the expected O-information into the negative domain. This phenomenon is well aligned with theoretical insights on interaction information and co-information for discrete variables (McGill1954, Bell2003), which show that non-uniform marginals induce baseline shifts even under perfect independence. In contrast, synthetic datasets used for validation usually employ balanced, exchangeable categories, for which the same permutation procedure naturally yields a null distribution centered near zero. 

For applied inference, the appropriate response is therefore to employ a bias-aware testing strategy that evaluates the statistic relative to its empirical null mean (use the two-sided-centered o auto alternative), which assesses $\lvert \Omega_{\mathrm{obs}} - \mathbb{E}[\Omega_{\mathrm{null}}] \rvert$ and thereby provides valid significance testing even when the permutation null is shifted or skewed.

In [33]:
ANBP_perm_boot[3]

{(1, 6, 16): (-0.14771069730976194,
  0.967032967032967,
  array([-0.14512407, -0.11110028, -0.14353703, -0.16173715, -0.1381046 ,
         -0.14211688, -0.11427459, -0.14227955, -0.1489767 , -0.12445348,
         -0.12419961, -0.11348387, -0.17616312, -0.1066426 , -0.1299044 ,
         -0.15575377, -0.14206722, -0.12873968, -0.17543675, -0.14178759,
         -0.11388524, -0.16455285, -0.08935584, -0.14105018, -0.18466994,
         -0.17484292, -0.10373849, -0.21040528, -0.11989299, -0.11374233,
         -0.11819659, -0.14482208, -0.19753199, -0.16430773, -0.1268419 ,
         -0.12849957, -0.14509298, -0.12084224, -0.15896698, -0.14261258,
         -0.11706605, -0.08916505, -0.12804469, -0.18822456, -0.19135722,
         -0.11106579, -0.22664771, -0.12791898, -0.14813732, -0.17733757,
         -0.18609535, -0.15468552, -0.1539704 , -0.14545122, -0.12207776,
         -0.10911636, -0.16496842, -0.13692967, -0.10812948, -0.10435742,
         -0.15327065, -0.14055172, -0.15644533, -0.14428649, -0.10127681,
         -0.1905289 , -0.16288613, -0.12049609, -0.14481729, -0.13930477,
         -0.13248234, -0.18506176, -0.1733243 , -0.20743466, -0.12964376,
         -0.19228621, -0.17135418, -0.15242331, -0.12398782, -0.12968359,
         -0.18653634, -0.132106  , -0.17623927, -0.08337983, -0.19609216,
         -0.14203804, -0.13970417, -0.14886828, -0.14637935, -0.13339407,
         -0.15462554, -0.16292316, -0.16209706, -0.1434292 , -0.14553725,
         -0.17287059, -0.18691439, -0.13934695, -0.11637491, -0.14197985,
         -0.15997586, -0.10434961, -0.09837188, -0.13126891, -0.15940831,
         -0.10052782, -0.13602302, -0.14641748, -0.17562414, -0.12534138,
         -0.16093212, -0.14676395, -0.12350399, -0.13908295, -0.19299949,
         -0.1308709 , -0.18720019, -0.16531206, -0.14143695, -0.15363103,
         -0.16119556, -0.13340613, -0.14206952, -0.13272879, -0.19840654,
         -0.19675783, -0.13540351, -0.14755554, -0.16857485, -0.15576886,
         -0.12312079, -0.11754131, -0.19644633, -0.14297789, -0.18447947,
         -0.1420288 , -0.11402868, -0.1664171 , -0.21345558, -0.15867438,
         -0.15787233, -0.10679363, -0.16213756, -0.10189658, -0.16523596,
         -0.14752897, -0.16824604, -0.13673666, -0.15686082, -0.11563987,
         -0.13581922, -0.127255  , -0.16862654, -0.17875057, -0.16694151,
         -0.1591429 , -0.14625212, -0.12297483, -0.13501172, -0.15645544,
         -0.17188029, -0.16715471, -0.15642532, -0.17080911, -0.16824593,
         -0.17088288, -0.17033109, -0.13850485, -0.15787369, -0.1545137 ,
         -0.16259626, -0.11576183, -0.12909171, -0.16054011, -0.16021531,
         -0.12821063, -0.12367876, -0.12294318, -0.15939487, -0.2019133 ,
         -0.21791829, -0.19681131, -0.17359198, -0.12399865, -0.14617593,
         -0.12068116, -0.15070487, -0.14618962, -0.14428469, -0.11180892,
         -0.1472838 , -0.10877587, -0.14924989, -0.15137149, -0.13131952,
         -0.12231913, -0.12914249, -0.15747895, -0.13613108, -0.10464056,
         -0.1297947 , -0.15568617, -0.13793531, -0.08281944, -0.20131318,
         -0.16122254, -0.22269838, -0.12102998, -0.12741041, -0.17840419,
         -0.11457429, -0.11208303, -0.14313259, -0.12654169, -0.14928159,
         -0.101169  , -0.13360002, -0.1598025 , -0.19736235, -0.14572592,
         -0.14702862, -0.11998051, -0.19748683, -0.16551928, -0.17783322,
         -0.12609045, -0.12524518, -0.11684078, -0.13207291, -0.14032444,
         -0.14662379, -0.15526539, -0.13763763, -0.1586096 , -0.12698039,
         -0.09320078, -0.13436686, -0.13424749, -0.12201925, -0.2005884 ,
         -0.15968166, -0.14074374, -0.18430291, -0.12571604, -0.14304759,
         -0.16373378, -0.11201437, -0.13783694, -0.14299773, -0.15003946,
         -0.12046966, -0.17422153, -0.14704866, -0.1868259 , -0.14334233,
         -0.16830517, -0.16126313, -0.18911283, -0.16310308, -0.09526826,
         -0.14894033, -0.14352173, -0.18845863, -0.16046786, -0.1609926 ,
         -0.16157128, -0.10850835, -0.16269233, -0.16474264, -0.13826106,
         -0.15718222, -0.20490416, -0.15258583, -0.15699925, -0.14665638,
         -0.13925385, -0.18351472, -0.14465018, -0.14583805, -0.15992003,
         -0.14672442, -0.19815653, -0.12872305, -0.15928442, -0.15399483,
         -0.13914705, -0.15915144, -0.11870452, -0.14307382, -0.11019353,
         -0.16832743, -0.17477736, -0.18383849, -0.1703306 , -0.19943666,
         -0.19885648, -0.16182091, -0.1592623 , -0.15871911, -0.13570992,
         -0.11097239, -0.11758599, -0.15819098, -0.10315019, -0.16824549,
         -0.12924706, -0.15789782, -0.15146632, -0.14261485, -0.14392213,
         -0.1344803 , -0.11598173, -0.13310925, -0.20081343, -0.14093223,
         -0.16721198, -0.12967227, -0.15510721, -0.16272301, -0.14876984,
         -0.15109868, -0.10617582, -0.12300196, -0.12009287, -0.15053183,
         -0.16417742, -0.12090831, -0.14403125, -0.1550803 , -0.19072371,
         -0.20425339, -0.1751942 , -0.12642342, -0.12605934, -0.14889404,
         -0.12535313, -0.18064963, -0.17822031, -0.12900471, -0.15607145,
         -0.14234956, -0.07865136, -0.13319737, -0.17002912, -0.15428689,
         -0.13092249, -0.12971803, -0.16015883, -0.15229548, -0.14961462,
         -0.15633707, -0.18725876, -0.16585786, -0.17723148, -0.10862728,
         -0.13144732, -0.18855101, -0.17138525, -0.15961261, -0.13755316,
         -0.17538879, -0.14578046, -0.15912436, -0.16440698, -0.15924647,
         -0.14029468, -0.17618979, -0.15629257, -0.1392929 , -0.15044198,
         -0.14029475, -0.19266416, -0.11432739, -0.10934606, -0.17675675,
         -0.11974781, -0.11409294, -0.11181827, -0.14070222, -0.13366614,
         -0.16124556, -0.1499115 , -0.12200572, -0.14371269, -0.1354624 ,
         -0.14528308, -0.19151858, -0.20875386, -0.17884853, -0.14674114,
         -0.14963695, -0.14262881, -0.14490526, -0.14633515, -0.15622321,
         -0.1388303 , -0.137945  , -0.14468665, -0.1245274 , -0.14093806,
         -0.13784021, -0.1566878 , -0.10266483, -0.15648175, -0.12763377,
         -0.12834915, -0.16700899, -0.15351556, -0.13224735, -0.13007191,
         -0.1234938 , -0.19488176, -0.1556027 , -0.13581058, -0.14741944,
         -0.15013187, -0.14573623, -0.18424873, -0.11448137, -0.11490249,
         -0.16055391, -0.1844719 , -0.15364715, -0.129481  , -0.17353404,
         -0.1924535 , -0.09566307, -0.1181721 , -0.14423314, -0.11333637,
         -0.19263276, -0.13311573, -0.18387693, -0.13083192, -0.16381491,
         -0.15916297, -0.10594645, -0.1028058 , -0.1245763 , -0.11425528,
         -0.12102845, -0.14183642, -0.13209805, -0.11469469, -0.13090423,
         -0.17693116, -0.12382864, -0.15631676, -0.16811937, -0.14225799,
         -0.15340166, -0.16172419, -0.14347549, -0.12823339, -0.11961373,
         -0.18083704, -0.1350671 , -0.13633696, -0.14054222, -0.11655233,
         -0.15472551, -0.15730942, -0.12677028, -0.09079783, -0.14756918,
         -0.18259162, -0.16293264, -0.15665317, -0.15064659, -0.12166889,
         -0.15317371, -0.12454132, -0.15866655, -0.13339549, -0.18009348,
         -0.18080773, -0.1322146 , -0.18392647, -0.15344749, -0.15149711,
         -0.13003514, -0.1184578 , -0.20258744, -0.12165298, -0.16929665,
         -0.14363262, -0.11647053, -0.14756123, -0.1646793 , -0.10647035,
         -0.13377737, -0.14511206, -0.16580862, -0.21651363, -0.12449324,
         -0.20392557, -0.15167926, -0.12791221, -0.09549886, -0.1320294 ,
         -0.17473915, -0.16251352, -0.15648277, -0.15506234, -0.18386934,
         -0.18092096, -0.14118812, -0.11263238, -0.17075633, -0.12085097,
         -0.14172571, -0.14295997, -0.15634647, -0.13127   , -0.15381023,
         -0.15014876, -0.13997409, -0.13415705, -0.12446773, -0.1657901 ,
         -0.13358259, -0.11434412, -0.13392884, -0.17269604, -0.18945357,
         -0.13032772, -0.15660436, -0.18262462, -0.15145836, -0.13209865,
         -0.14696157, -0.16330692, -0.11823714, -0.16629636, -0.18254524,
         -0.15368307, -0.1557219 , -0.12759514, -0.1475045 , -0.12443406,
         -0.15086322, -0.10992538, -0.13185015, -0.14233629, -0.11425931,
         -0.13136885, -0.13773417, -0.15619168, -0.15761355, -0.13632941,
         -0.12446902, -0.16197134, -0.11411287, -0.14138678, -0.13716567,
         -0.14495726, -0.19718159, -0.16168533, -0.12248173, -0.13207286,
         -0.1707804 , -0.20771802, -0.13231778, -0.1521768 , -0.14708133,
         -0.11595021, -0.10767749, -0.1685225 , -0.12669246, -0.1638008 ,
         -0.16322657, -0.16415607, -0.13318883, -0.15188585, -0.15643435,
         -0.16686693, -0.16435385, -0.16449515, -0.16440343, -0.16106958,
         -0.11942501, -0.12239066, -0.12659738, -0.13042105, -0.15342017,
         -0.13609599, -0.14127162, -0.14006797, -0.15239606, -0.14188977,
         -0.14876625, -0.09439511, -0.19708049, -0.18009477, -0.13546481,
         -0.12685878, -0.12597275, -0.11719709, -0.13151332, -0.16482426,
         -0.15753009, -0.14220682, -0.10533747, -0.13651255, -0.14132285,
         -0.1524571 , -0.14970283, -0.15437187, -0.13587883, -0.11818362,
         -0.19032774, -0.15137179, -0.16250256, -0.1211893 , -0.15495183,
         -0.12711855, -0.17571058, -0.14695655, -0.15468422, -0.11471967,
         -0.13251166, -0.13720902, -0.12862372, -0.1323807 , -0.14562277,
         -0.17035752, -0.1511758 , -0.12683656, -0.14831646, -0.17260293,
         -0.21416026, -0.13735145, -0.13793283, -0.14652639, -0.16994296,
         -0.12038781, -0.14157483, -0.13352121, -0.17040307, -0.15431917,
         -0.15734418, -0.11886312, -0.1539768 , -0.16916991, -0.15224502,
         -0.19607351, -0.13592855, -0.18711964, -0.12370388, -0.19204473,
         -0.15247007, -0.12275185, -0.10937958, -0.12814857, -0.12405352,
         -0.19434342, -0.16954642, -0.14401579, -0.11961099, -0.13324401,
         -0.13965403, -0.15105094, -0.18039531, -0.12656952, -0.17856959,
         -0.16398728, -0.14564767, -0.13024424, -0.20463341, -0.19368001,
         -0.15424082, -0.13909692, -0.11423729, -0.12713313, -0.10173609,
         -0.15530268, -0.20059048, -0.12988279, -0.19526215, -0.15621691,
         -0.1442693 , -0.07501225, -0.17255494, -0.15694005, -0.15356092,
         -0.15747888, -0.14953379, -0.16380186, -0.18552628, -0.1139259 ,
         -0.17930335, -0.15095388, -0.14318617, -0.16050655, -0.15016004,
         -0.127384  , -0.21891217, -0.09571058, -0.17644964, -0.13393271,
         -0.14198423, -0.16517397, -0.13574528, -0.11893822, -0.15055399,
         -0.11656987, -0.11735957, -0.12365207, -0.19121731, -0.14680511,
         -0.16635686, -0.15943563, -0.13645893, -0.08501428, -0.16754511,
         -0.1672256 , -0.15621231, -0.16455717, -0.15385676, -0.12101481,
         -0.17455999, -0.16602564, -0.166762  , -0.11429254, -0.14331941,
         -0.16225746, -0.17893543, -0.13584038, -0.18103105, -0.09884243,
         -0.09333274, -0.2203747 , -0.12318558, -0.11633475, -0.14838679,
         -0.08022903, -0.12720172, -0.15477235, -0.20484514, -0.17498685,
         -0.12209426, -0.13030174, -0.13595802, -0.14969226, -0.13638871,
         -0.1883103 , -0.14720093, -0.17777432, -0.14216772, -0.13961431,
         -0.13480484, -0.13029667, -0.16325983, -0.13047733, -0.118773  ,
         -0.15109876, -0.16365064, -0.16653107, -0.15266644, -0.14343494,
         -0.14054396, -0.09118131, -0.14021489, -0.10375063, -0.15617525,
         -0.12453326, -0.16586019, -0.19341113, -0.10992465, -0.2114602 ,
         -0.15009371, -0.13801543, -0.14124178, -0.171754  , -0.1204876 ,
         -0.16290799, -0.14879332, -0.15449961, -0.1313989 , -0.1292799 ,
         -0.17151546, -0.13223387, -0.17262754, -0.13008198, -0.16554435,
         -0.12773253, -0.19783463, -0.10491917, -0.11365327, -0.11471866,
         -0.0999014 , -0.19559147, -0.12874698, -0.10695889, -0.19847699,
         -0.16000565, -0.17451923, -0.14189593, -0.17535972, -0.1533548 ,
         -0.0990376 , -0.13012483, -0.13929473, -0.10726328, -0.14322438,
         -0.11420823, -0.14577538, -0.14405531, -0.12762803, -0.13937895,
         -0.13591156, -0.16732652, -0.13478832, -0.1276036 , -0.14452032,
         -0.14732268, -0.12562063, -0.1245981 , -0.14835719, -0.13584414,
         -0.16734276, -0.14309764, -0.15597149, -0.16377826, -0.14024881,
         -0.14584309, -0.13753239, -0.16025451, -0.12090161, -0.14385124,
         -0.17080955, -0.14715429, -0.15895719, -0.17355453, -0.14518443,
         -0.12140212, -0.10205203, -0.13293516, -0.10644417, -0.1357002 ,
         -0.12078865, -0.12360363, -0.14783825, -0.11878042, -0.14979876,
         -0.10039641, -0.13885553, -0.11135987, -0.12565943, -0.15215262,
         -0.09950267, -0.16541578, -0.13861019, -0.14571192, -0.13778403,
         -0.13114484, -0.1686865 , -0.17214881, -0.11245243, -0.10186388,
         -0.13319774, -0.1907272 , -0.1599717 , -0.1698731 , -0.18203124,
         -0.18033772, -0.15360472, -0.11863379, -0.15369774, -0.16133985,
         -0.10802182, -0.15629259, -0.12605193, -0.16025891, -0.16156742,
         -0.13114244, -0.18516493, -0.1091541 , -0.16014785, -0.13479473,
         -0.12187784, -0.15889306, -0.18652755, -0.12963397, -0.14984516,
         -0.20247846, -0.15135246, -0.17302314, -0.12089102, -0.1499821 ,
         -0.13662965, -0.16342895, -0.16857408, -0.15391169, -0.11092047,
         -0.13414986, -0.18460192, -0.10749691, -0.18358191, -0.12134798,
         -0.10392381, -0.15460218, -0.1697272 , -0.15011519, -0.14481085,
         -0.20968786, -0.13366546, -0.14849971, -0.13682312, -0.12704015,
         -0.1585117 , -0.14817076, -0.15160254, -0.09623468, -0.14392707,
         -0.13466322, -0.15743993, -0.12412169, -0.09317651, -0.16305691,
         -0.12227737, -0.20545693, -0.15374799, -0.15606914, -0.14795341,
         -0.12180639, -0.15595998, -0.12942673, -0.12230337, -0.22213319,
         -0.10638488, -0.15181516, -0.12763896, -0.15322977, -0.14533992,
         -0.18563819, -0.1232702 , -0.12829398, -0.14519992, -0.17787227,
         -0.13646194, -0.16217714, -0.12223782, -0.18783439, -0.13215792,
         -0.18322268, -0.14617786, -0.12042826, -0.11560782, -0.1429493 ,
         -0.12922867, -0.15914639, -0.22601223, -0.16241231, -0.11887101,
         -0.09885436, -0.15594739, -0.14015508, -0.1390413 , -0.13434524,
         -0.13813587, -0.15546577, -0.16154013, -0.15072602, -0.09968559,
         -0.11282727, -0.10515018, -0.11753156, -0.14214783, -0.11720716,
         -0.18783473, -0.13197655, -0.15119276, -0.17619775, -0.17977618,
         -0.12827197, -0.16476683, -0.14802418, -0.12773985, -0.14537556,
         -0.16517842, -0.13770285, -0.12800045, -0.12611044, -0.13046409,
         -0.14520876, -0.14056801, -0.12852061, -0.13890426, -0.1390103 ,
         -0.13105433, -0.15052114, -0.14753348, -0.18386677, -0.16514555,
         -0.14220808, -0.14926667, -0.14702478, -0.14199395, -0.17505513]),
  {'mean_null': -0.14677355718314078,
   'median_null': -0.14549423862429212,
   'std_null': 0.02578978337705859,
   'skew_null': -0.2885295745684782,
   'q025_null': -0.2013281852466137,
   'q975_null': -0.09989600694984171,
   't_obs': 0.000937140126621161}),
 (1, 6, 27): (-0.11194522777220861,
  0.002997002997002997,
  array([-0.19355668, -0.26211612, -0.17567676, -0.16070733, -0.22270284,
         -0.15537951, -0.11412425, -0.21612221, -0.18914077, -0.21864461,
         -0.15472285, -0.19378596, -0.16285626, -0.18318961, -0.18348346,
         -0.15849461, -0.19285899, -0.12952423, -0.21316922, -0.18438457,
         -0.23606663, -0.18914771, -0.22019569, -0.22281134, -0.25117828,
         -0.17090875, -0.15777373, -0.11631933, -0.16678063, -0.219724  ,
         -0.20717736, -0.21005794, -0.18029853, -0.17723085, -0.2344273 ,
         -0.1958546 , -0.23150615, -0.16165356, -0.26237897, -0.2381856 ,
         -0.19211309, -0.21213717, -0.15314285, -0.2132682 , -0.16373425,
         -0.1793709 , -0.19577696, -0.14996683, -0.16481831, -0.22564586,
         -0.17755786, -0.14439459, -0.17941929, -0.27143585, -0.20548107,
         -0.23779675, -0.17959536, -0.17680701, -0.14314818, -0.17490698,
         -0.17005593, -0.23172979, -0.1729704 , -0.13289231, -0.13770885,
         -0.22288424, -0.18617927, -0.22312562, -0.16887803, -0.21918444,
         -0.20665103, -0.20108425, -0.18614078, -0.18798529, -0.22866397,
         -0.19052933, -0.19736044, -0.18316758, -0.16280239, -0.22742755,
         -0.13863492, -0.22870257, -0.11801497, -0.17724539, -0.17976323,
         -0.22684216, -0.19745816, -0.19828605, -0.13382424, -0.19428999,
         -0.21385345, -0.1783906 , -0.23201925, -0.1547921 , -0.19852402,
         -0.18692309, -0.15120336, -0.18644082, -0.15723772, -0.18960192,
         -0.21383641, -0.18654623, -0.20387945, -0.19705152, -0.19097537,
         -0.15607452, -0.20113029, -0.18592572, -0.18379672, -0.1490225 ,
         -0.2107123 , -0.20753771, -0.14593571, -0.20948326, -0.17283573,
         -0.24973556, -0.23898721, -0.23611267, -0.21107505, -0.15017585,
         -0.22572515, -0.20111753, -0.20080092, -0.19523418, -0.22109257,
         -0.17109416, -0.16851657, -0.2328478 , -0.18309442, -0.20229739,
         -0.20274194, -0.20731056, -0.21773595, -0.19308658, -0.23501572,
         -0.19665894, -0.22324127, -0.19355286, -0.20467411, -0.18509206,
         -0.1506095 , -0.19040431, -0.19130619, -0.2333046 , -0.17683927,
         -0.18522543, -0.16499467, -0.18799126, -0.24380988, -0.15982626,
         -0.20600995, -0.27288249, -0.20976264, -0.23067655, -0.19122137,
         -0.22815046, -0.20499941, -0.20471702, -0.17859017, -0.17241298,
         -0.26554998, -0.20948182, -0.21794823, -0.23269138, -0.16343293,
         -0.17301056, -0.18750914, -0.21696897, -0.22611482, -0.19777368,
         -0.21836884, -0.22461673, -0.23956326, -0.25982386, -0.22989605,
         -0.18837297, -0.19844252, -0.2425804 , -0.21533653, -0.20778083,
         -0.25538268, -0.22140381, -0.21134922, -0.18313541, -0.22527376,
         -0.1813848 , -0.20656549, -0.18707522, -0.18111953, -0.2606517 ,
         -0.21460534, -0.24487224, -0.14713955, -0.16131262, -0.21889351,
         -0.19112944, -0.24766065, -0.17215429, -0.15706949, -0.17416934,
         -0.22602556, -0.18220223, -0.17095545, -0.19827911, -0.23511933,
         -0.14347786, -0.16505029, -0.13311305, -0.20622667, -0.22972863,
         -0.21817575, -0.18206225, -0.22328935, -0.14291709, -0.18669438,
         -0.14920263, -0.18354928, -0.26234434, -0.19915635, -0.21661883,
         -0.21082403, -0.24936362, -0.21021519, -0.158997  , -0.20260794,
         -0.2709228 , -0.24545741, -0.17920121, -0.15716148, -0.1516942 ,
         -0.24506066, -0.21342485, -0.17101352, -0.25578588, -0.15656192,
         -0.16740457, -0.14505793, -0.20780142, -0.21839485, -0.22306831,
         -0.21871073, -0.18275808, -0.21491618, -0.20488269, -0.18763779,
         -0.20697887, -0.16491603, -0.16951027, -0.20524802, -0.18068258,
         -0.1871725 , -0.1908004 , -0.14002808, -0.17632288, -0.21644272,
         -0.1970363 , -0.2081214 , -0.17827617, -0.24203369, -0.19905553,
         -0.19688873, -0.18066466, -0.20417053, -0.21107645, -0.18829006,
         -0.17211709, -0.21307118, -0.15031036, -0.21577118, -0.17937563,
         -0.17095522, -0.20204432, -0.15544378, -0.20118181, -0.25076942,
         -0.22152856, -0.21436248, -0.17695639, -0.15721003, -0.18330444,
         -0.2372586 , -0.19598774, -0.19382098, -0.16451854, -0.25687697,
         -0.13752172, -0.15881313, -0.18414632, -0.21134655, -0.18902872,
         -0.16385704, -0.19910101, -0.1829047 , -0.21563667, -0.19984684,
         -0.26999333, -0.20897736, -0.1689096 , -0.13972302, -0.17185359,
         -0.19151169, -0.1529514 , -0.20384213, -0.16799148, -0.16670547,
         -0.20222834, -0.23241811, -0.23335811, -0.23983127, -0.16621049,
         -0.15753752, -0.17653448, -0.1454293 , -0.24086506, -0.18793953,
         -0.20283702, -0.13766364, -0.18826516, -0.1728032 , -0.21973045,
         -0.18966868, -0.2137749 , -0.16812138, -0.14994967, -0.20437624,

In [34]:
ut.summary(ANBP_perm_boot)[3]

{(1, 6, 16): (-0.14771069730976194, 0.967032967032967),
 (1, 6, 27): (-0.11194522777220861, 0.002997002997002997),
 (1, 6, 42): (-0.1280101513527896, 0.04295704295704296),
 (1, 6, 70): (-0.19085848070205103, 0.9050949050949051),
 (1, 13, 47): (-0.160363939390896, 0.43656343656343655),
 (1, 19, 47): (-0.14530435448372003, 0.6873126873126874),
 (1, 27, 47): (-0.1325969524178916, 0.07892107892107893),
 (1, 42, 47): (-0.12220900512239297, 0.06493506493506493),
 (2, 24, 36): (-0.18108155147178806, 0.3336663336663337),
 (3, 14, 35): (-0.16108637641459822, 0.0989010989010989),
 (3, 35, 39): (-0.10767264119630582, 0.003996003996003996),
 (5, 7, 53): (-0.1935612566339966, 0.8041958041958042),
 (5, 12, 29): (-0.182027888500917, 0.3146853146853147),
 (5, 12, 53): (-0.18228783739092336, 0.5794205794205795),
 (5, 12, 69): (-0.10433014878430846, 0.023976023976023976),
 (5, 29, 43): (-0.20233598015785148, 0.8131868131868132),
 (5, 29, 71): (-0.26841852606937167, 0.000999000999000999),
 (6, 14, 35): (-0.1169509284954966, 0.001998001998001998),
 (6, 16, 22): (-0.18705656072829058, 0.11888111888111888),
 (6, 18, 24): (-0.10195831439816949, 0.000999000999000999),
 (6, 18, 27): (-0.14657118238295475, 0.023976023976023976),
 (6, 18, 90): (-0.184502705963844, 0.7342657342657343),
 (6, 22, 35): (-0.10273550435621992, 0.004995004995004995),
 (6, 24, 70): (-0.1960058644704521, 0.7312687312687313),
 (6, 27, 35): (-0.10636683236360156, 0.002997002997002997),
 (6, 35, 42): (-0.1346876666889969, 0.013986013986013986),
 (6, 42, 48): (-0.14216833450901412, 0.11688311688311688),
 (6, 70, 90): (-0.15235153516857913, 0.3786213786213786),
 (7, 25, 30): (-0.20662758864158448, 0.6973026973026973),
 (7, 25, 53): (-0.13579517420607168, 0.016983016983016984),
 (7, 30, 89): (-0.16954669180642057, 0.8281718281718282),
 (8, 21, 67): (-0.1458215067206723, 0.025974025974025976),
 (8, 26, 34): (-0.12069468024401964, 0.00999000999000999),
 (8, 34, 51): (-0.11622502287076841, 0.002997002997002997),
 (8, 34, 54): (-0.15782911557921153, 0.07392607392607392),
 (8, 44, 67): (-0.12666743568800243, 0.005994005994005994),
 (9, 11, 29): (-0.147887153067483, 0.8081918081918081),
 (9, 29, 90): (-0.11094431012939587, 0.03896103896103896),
 (9, 57, 59): (-0.1099642533343328, 0.003996003996003996),
 (10, 42, 63): (-0.18952202427239762, 0.43656343656343655),
 (10, 47, 53): (-0.12637474023539141, 0.01998001998001998),
 (10, 47, 84): (-0.13699439741059471, 0.02097902097902098),
 (10, 50, 53): (-0.14423589265305026, 0.03496503496503497),
 (10, 56, 66): (-0.13869524267506605, 0.016983016983016984),
 (10, 63, 66): (-0.18596226663841975, 0.3776223776223776),
 (10, 66, 85): (-0.20408493657846272, 0.6643356643356644),
 (10, 66, 90): (-0.10730855811395124, 0.002997002997002997),
 (11, 20, 76): (-0.11674522620221062, 0.3696303696303696),
 (11, 27, 36): (-0.1464115813304936, 0.5984015984015985),
 (11, 32, 36): (-0.10051341819172777, 0.08591408591408592),
 (11, 33, 34): (-0.1337390666849938, 0.11588411588411589),
 (11, 36, 76): (-0.1281731194733844, 0.6063936063936064),
 (11, 61, 64): (-0.13915242464782196, 0.12387612387612387),
 (11, 61, 68): (-0.1343148680430879, 0.6293706293706294),
 (11, 63, 64): (-0.16389567607407685, 0.6173826173826173),
 (13, 47, 82): (-0.1319703129130616, 0.061938061938061936),
 (13, 63, 72): (-0.13173450081542448, 0.8351648351648352),
 (14, 22, 35): (-0.1661359423172737, 0.2987012987012987),
 (14, 35, 87): (-0.13935870201094325, 0.01998001998001998),
 (14, 52, 85): (-0.18320860631761882, 0.3126873126873127),
 (14, 85, 87): (-0.183546138201077, 0.35264735264735264),
 (15, 26, 38): (-0.16894646944824743, 0.42157842157842157),
 (15, 57, 67): (-0.11817333589727319, 0.012987012987012988),
 (15, 57, 68): (-0.11784694769640147, 0.16083916083916083),
 (15, 67, 70): (-0.1635855796850496, 0.3046953046953047),
 (15, 70, 71): (-0.18614580087588273, 0.926073926073926),
 (15, 71, 73): (-0.17748911022061797, 0.7152847152847153),
 (16, 25, 51): (-0.13885222324142354, 0.15384615384615385),
 (16, 32, 49): (0.11046722589736824, 0.000999000999000999),
 (17, 20, 76): (-0.15739381994947088, 0.5204795204795205),
 (17, 26, 76): (-0.13025780352577243, 0.1068931068931069),
 (18, 65, 80): (-0.10107593545707161, 0.000999000999000999),
 (18, 84, 88): (-0.11591782537568385, 0.007992007992007992),
 (18, 88, 90): (-0.19752507620720294, 0.5834165834165834),
 (20, 35, 42): (-0.12844536484006674, 0.015984015984015984),
 (20, 35, 66): (-0.13870534803616863, 0.03696303696303696),
 (20, 76, 84): (-0.18867493741800345, 0.996003996003996),
 (23, 39, 73): (-0.14463766421720514, 0.3626373626373626),
 (23, 69, 83): (-0.12918269411668604, 0.04595404595404595),
 (24, 35, 36): (-0.12433113673498397, 0.004995004995004995),
 (24, 35, 60): (-0.14905388617469484, 0.03296703296703297),
 (24, 51, 84): (-0.10293198435821616, 0.000999000999000999),
 (25, 30, 63): (-0.2319085590027523, 0.2997002997002997),
 (25, 32, 53): (-0.13885174382223475, 0.03396603396603397),
 (25, 78, 82): (-0.1865572006030387, 0.5224775224775224),
 (26, 33, 34): (-0.10992006310632618, 0.005994005994005994),
 (26, 34, 76): (-0.15720420314449868, 0.2947052947052947),
 (26, 43, 58): (-0.15003321959795812, 0.17382617382617382),
 (26, 58, 76): (-0.19341683000717147, 0.45854145854145856),
 (27, 36, 84): (-0.11587199600836406, 0.003996003996003996),
 (27, 47, 85): (-0.10052590431725328, 0.001998001998001998),
 (27, 56, 66): (-0.11126343836679808, 0.002997002997002997),
 (27, 66, 85): (-0.20565162942340365, 0.7342657342657343),
 (28, 53, 78): (-0.18025705515035995, 0.26973026973026976),
 (28, 78, 86): (-0.13352466951037378, 0.014985014985014986),
 (29, 82, 90): (-0.10039285901354589, 0.02097902097902098),
 (30, 46, 69): (-0.25090203386590204, 0.06393606393606394),
 (30, 63, 69): (-0.1649509426443636, 0.27472527472527475),
 (30, 74, 75): (-0.10271887209502317, 0.012987012987012988),
 (30, 75, 87): (-0.16230766563569787, 0.32367632367632365),
 (30, 75, 89): (-0.18331282974157403, 0.3386613386613387),
 (32, 36, 78): (-0.15307250321493804, 0.10789210789210789),
 (33, 68, 81): (-0.12440777348706611, 0.5594405594405595),
 (33, 68, 83): (-0.11986968722666269, 0.015984015984015984),
 (33, 77, 81): (-0.1707673926977442, 0.5484515484515484),
 (34, 57, 76): (-0.10512947480705215, 0.01098901098901099),
 (35, 58, 87): (-0.14092019010166368, 0.04495504495504495),
 (35, 60, 64): (-0.1731371902180996, 0.1918081918081918),
 (35, 64, 66): (-0.18074810252805307, 0.2707292707292707),
 (35, 64, 87): (-0.18936047676479006, 0.4085914085914086),
 (35, 65, 66): (-0.1335946266569934, 0.015984015984015984),
 (35, 65, 74): (-0.11793858640338684, 0.000999000999000999),
 (35, 72, 81): (-0.115560060167466, 0.015984015984015984),
 (35, 77, 81): (-0.1347036125811023, 0.2827172827172827),
 (37, 42, 62): (-0.10995327922916687, 0.023976023976023976),
 (37, 71, 73): (-0.1673141042204236, 0.6123876123876124),
 (39, 44, 68): (-0.11773914687907094, 0.06993006993006994),
 (39, 44, 75): (-0.14299233937128086, 0.09090909090909091),
 (39, 47, 68): (-0.12192815318254979, 0.5354645354645354),
 (39, 58, 75): (-0.12430365612703298, 0.10789210789210789),
 (39, 58, 76): (-0.1080256595597131, 0.03596403596403597),
 (40, 60, 73): (-0.22128903815438505, 0.8881118881118881),
 (41, 42, 43): (-0.18348431153681233, 0.48951048951048953),
 (41, 47, 85): (-0.11681526516274943, 0.015984015984015984),
 (41, 56, 85): (-0.11256821769778469, 0.002997002997002997),
 (41, 66, 85): (-0.13532931390709102, 0.025974025974025976),
 (42, 47, 48): (-0.1449135288982344, 0.22877122877122877),
 (42, 50, 69): (-0.13782857357065126, 0.02197802197802198),
 (42, 63, 69): (-0.15348691418710914, 0.054945054945054944),
 (42, 63, 91): (-0.21419465759479905, 0.6893106893106893),
 (42, 75, 86): (-0.1875981895651293, 0.5714285714285714),
 (42, 84, 86): (-0.1288372933609292, 0.011988011988011988),
 (44, 51, 52): (-0.15050369863743107, 0.03696303696303696),
 (45, 69, 78): (-0.17800763618622994, 0.27172827172827174),
 (45, 78, 82): (-0.1472723727577332, 0.05194805194805195),
 (46, 69, 83): (-0.1943271183008335, 0.5774225774225774),
 (47, 54, 82): (-0.10908218059591057, 0.004995004995004995),
 (47, 68, 82): (-0.11281961414415598, 0.26873126873126874),
 (47, 68, 85): (-0.12955351233049583, 0.2967032967032967),
 (47, 82, 84): (-0.13993097246058284, 0.1038961038961039),
 (49, 53, 64): (-0.14360235091403162, 0.12987012987012986),
 (50, 69, 71): (-0.18257697275768336, 0.45354645354645357),
 (50, 70, 71): (-0.20670747402822087, 0.7892107892107892),
 (53, 71, 77): (-0.1670785165782842, 0.2517482517482518),
 (57, 58, 76): (-0.1594289749024025, 0.6603396603396603),
 (57, 68, 89): (-0.13449823213607104, 0.9820179820179821),
 (57, 76, 78): (-0.1811331614078444, 0.7592407592407593),
 (58, 75, 87): (-0.2047242007820067, 0.6133866133866134),
 (60, 78, 82): (-0.15290600458130754, 0.08391608391608392),
 (61, 68, 81): (-0.13018776196059711, 0.4155844155844156),
 (63, 64, 66): (-0.19938811418143487, 0.6673326673326674),
 (63, 66, 68): (-0.15023313107865732, 0.34265734265734266),
 (63, 69, 72): (-0.10256730786066726, 0.25674325674325676),
 (65, 66, 90): (-0.14616559225957104, 0.06593406593406594),
 (65, 67, 90): (-0.1960367643039458, 0.7782217782217782),
 (66, 86, 90): (-0.12270641562761497, 0.007992007992007992),
 (68, 83, 85): (-0.11135098651770647, 0.005994005994005994),
 (69, 72, 76): (-0.11251685831889802, 0.983016983016983),
 (69, 76, 78): (-0.20079463248994855, 0.985014985014985),
 (69, 78, 81): (-0.15818799213371548, 0.6833166833166833),
 (69, 83, 87): (-0.14087568968866293, 0.02197802197802198),
 (70, 71, 77): (-0.18260783935482472, 0.6193806193806194),
 (70, 71, 79): (-0.23770257145060825, 0.027972027972027972),
 (70, 74, 77): (-0.19147041746779792, 1.0),
 (70, 74, 79): (-0.22020566020495203, 0.08691308691308691),
 (71, 77, 86): (-0.178994417749621, 0.3116883116883117),
 (72, 74, 75): (-0.1058166296822396, 0.5074925074925075),
 (72, 75, 88): (-0.12536850801861021, 0.12387612387612387),
 (72, 81, 90): (-0.12944216554465449, 0.000999000999000999),
 (74, 75, 79): (-0.1759658601069063, 0.6603396603396603),
 (74, 86, 90): (-0.1404620895831492, 0.1038961038961039),
 (78, 81, 82): (-0.12244585574656419, 0.21678321678321677),
 (78, 84, 86): (-0.14546801753332517, 0.02097902097902098),
 (78, 84, 91): (-0.14565367032779264, 0.03496503496503497),
 (80, 89, 91): (-0.10334616275200226, 0.025974025974025976),
 (81, 82, 90): (-0.1486837466991897, 0.25874125874125875),
 (82, 88, 90): (-0.19216789484288377, 0.35864135864135865)}

### Filter multiplets - pvalue wise + REDUNDANCY/SYNERGY check
Filter out the non significant multiplets and the ones whose observed and significant $\Omega$ - information shows zero-interaction (set a **tolerance** for what is zero-interaction: **|$\Omega$| <= omega_threshold**.

In [43]:
omega_threshold = 0.1
alpha_significance = 0.05

fdr_neut_filtered_mults_diags = {}
filtered_descriptive = {}
for diagnosis, perm_boot in perm_boot_diags.items():
    fdr_neut_filtered_mults_diags[diagnosis] = ut.fdr_neuter_filter(perm_boot, omega_threshold = omega_threshold)
    filtered_descriptive[diagnosis] = ut.fdr_neuter_filter(perm_boot, omega_threshold = 0)

In [44]:
# here are the fildered multiplets to use for further computations
op_multiplets_diags_F = ut.get_multiplets_as_dict_list_F(fdr_neut_filtered_mults_diags)

In [45]:
#len(set(multiplets_diags['BED'][5]) & set(op_multiplets_diags_['BED'][5]))

The following is useful for **descriptive purposes**: how many multiplets are significant (neuter/synergistic/redudndant)? how many are not?

In [46]:
omega_partitions_diags = {}
for diag, filtered_boot in filtered_descriptive.items():
    omega_partitions_diags[diag] = ut.omega_partition(filtered_boot, alpha = alpha_significance, omega_threshold = omega_threshold)
    
print(ut.describe_omega_partition(omega_partitions_diags))

Diagnosis: ANBP
	 Interation type: syn there are:
	 	 Order: 5 # multiplets: 674
	 	 Order: 4 # multiplets: 528
	 	 Order: 3 # multiplets: 23
	 Interation type: red there are:
	 	 Order: 5 # multiplets: 3
	 	 Order: 4 # multiplets: 4
	 	 Order: 3 # multiplets: 1
	 Interation type: neut there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
	 Interation type: non_sig there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
Diagnosis: ANR
	 Interation type: syn there are:
	 	 Order: 5 # multiplets: 669
	 	 Order: 4 # multiplets: 466
	 	 Order: 3 # multiplets: 2
	 Interation type: red there are:
	 	 Order: 5 # multiplets: 15
	 	 Order: 4 # multiplets: 21
	 	 Order: 3 # multiplets: 31
	 Interation type: neut there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
	 Interation type: non_sig there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
Diagnosis: BED_OSFED
	 Interation type: syn there are:
	 	 Order: 5 # multiplets: 513
	 	 Order: 4 # multiplets: 470
	 	 Order: 3 # multiplets: 64
	 Interation type: red there are:
	 	 Order: 5 # multiplets: 30
	 	 Order: 4 # multiplets: 5
	 	 Order: 3 # multiplets: 3
	 Interation type: neut there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
	 Interation type: non_sig there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
Diagnosis: BN
	 Interation type: syn there are:
	 	 Order: 5 # multiplets: 563
	 	 Order: 4 # multiplets: 389
	 	 Order: 3 # multiplets: 0
	 Interation type: red there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 2
	 	 Order: 3 # multiplets: 5
	 Interation type: neut there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
	 Interation type: non_sig there are:
	 	 Order: 5 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 3 # multiplets: 0
None

### Part 2: Robustness and Stability via Bootstrap

**Purpose:** Validate sign stability and point estimate reliability.

**Procedure:**

1. **Row-wise nonparametric bootstrap resampling:**
   - Resample observations (rows) with replacement n_bootstrap times
   - For each bootstrap sample, recompute Ω-information

2. **Confidence interval computation (BiasCA):**
   - Compute BCa (Bias-Corrected and Accelerated) confidence intervals (DiCiccio & Efron, 1996; Efron & Tibshirani, 1994; Efron & Narasimhan, 2020)
   - Uses jackknife-based acceleration correction
   - Fallback: Percentile confidence intervals if acceleration computation fails

3. **Stability criteria:**
   - **Sign stability:** Retain multiplets whose CI does not include zero
     - Rationale: Ensures consistent classification as redundant or synergistic
   - **Point estimate reliability:** Assess bootstrap distribution for outliers or multimodality
     - Discard if CI is very wide or bootstrap distribution appears unreliable

**Output:** Bootstrap-validated multiplets with stable, reliable effect estimates

#### Compute the bootstrap row wise omega distributions first.

In [48]:
out_dir_sd = "samp_distro_diags_POLY"
os.makedirs(out_dir_sd, exist_ok=True)

bca_samp_distros_diags = {}
for diagnosis, multiplets in op_multiplets_diags_F.items():
    start = time.perf_counter()
    # structure: order: multiple: samp_distro
    ### bca_bootopt.get_boot_stats_parallel is the same as output but handle the parallelism differenty
    bca_samp_distros_diags[diagnosis] = bca_bootopt.get_boot_stats_parallel_chunked(multiplets_dict=multiplets, 
                                                                            X=EDI_diags[diagnosis], 
                                                                            n_boot=n_iter_boot) 
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")
    
    fname = f"{diagnosis}_bca_selected_mults.pkl"
    fpath = os.path.join(out_dir_sd, fname)
    with open(fpath, "wb") as f:
        pickle.dump(bca_samp_distros_diags[diagnosis], f, protocol=pickle.HIGHEST_PROTOCOL)

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 5:   0%|0/677 |          | 00:00


Multiplets | family 5:  15%|100/677 |█▍        | 00:52


Multiplets | family 5:  30%|200/677 |██▉       | 01:39


Multiplets | family 5:  44%|300/677 |████▍     | 02:24


Multiplets | family 5:  59%|400/677 |█████▉    | 03:09


Multiplets | family 5:  74%|500/677 |███████▍  | 03:54


Multiplets | family 5:  89%|600/677 |████████▊ | 04:39


Multiplets | family 5: 100%|677/677 |██████████| 05:14


Families:  33%|███▎      | 1/3 [05:14<10:28, 314.50s/it]A

  [family 5] bootstrap progress: 677/677 multiplets (100%)

Multiplets | family 4:   0%|0/532 |          | 00:00


Multiplets | family 4:  19%|100/532 |█▉        | 00:36


Multiplets | family 4:  38%|200/532 |███▊      | 01:11


Multiplets | family 4:  56%|300/532 |█████▋    | 01:47


Multiplets | family 4:  75%|400/532 |███████▌  | 02:21


Multiplets | family 4:  94%|500/532 |█████████▍| 02:56


Multiplets | family 4: 100%|532/532 |██████████| 03:07


Families:  67%|██████▋   | 2/3 [08:22<04:00, 240.10s/it]A

  [family 4] bootstrap progress: 532/532 multiplets (100%)

Multiplets | family 3:   0%|0/24 |          | 00:00


Multiplets | family 3: 100%|24/24 |██████████| 00:05

  [family 3] bootstrap progress: 24/24 multiplets (100%)
Runtime: 508.218006 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 5:   0%|0/684 |          | 00:00


Multiplets | family 5:  15%|100/684 |█▍        | 00:55


Multiplets | family 5:  29%|200/684 |██▉       | 01:51


Multiplets | family 5:  44%|300/684 |████▍     | 02:46


Multiplets | family 5:  58%|400/684 |█████▊    | 03:42


Multiplets | family 5:  73%|500/684 |███████▎  | 04:38


Multiplets | family 5:  88%|600/684 |████████▊ | 05:33


Multiplets | family 5: 100%|684/684 |██████████| 06:19


Families:  33%|███▎      | 1/3 [06:19<12:39, 379.54s/it]A

  [family 5] bootstrap progress: 684/684 multiplets (100%)

Multiplets | family 4:   0%|0/487 |          | 00:00


Multiplets | family 4:  21%|100/487 |██        | 00:41


Multiplets | family 4:  41%|200/487 |████      | 01:23


Multiplets | family 4:  62%|300/487 |██████▏   | 02:04


Multiplets | family 4:  82%|400/487 |████████▏ | 02:45


Multiplets | family 4: 100%|487/487 |██████████| 03:21


Families:  67%|██████▋   | 2/3 [09:40<04:34, 274.60s/it]A

  [family 4] bootstrap progress: 487/487 multiplets (100%)

Multiplets | family 3:   0%|0/33 |          | 00:00


Multiplets | family 3: 100%|33/33 |██████████| 00:09

  [family 3] bootstrap progress: 33/33 multiplets (100%)
Runtime: 590.239369 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 5:   0%|0/543 |          | 00:00


Multiplets | family 5:  18%|100/543 |█▊        | 00:39


Multiplets | family 5:  37%|200/543 |███▋      | 01:18


Multiplets | family 5:  55%|300/543 |█████▌    | 01:56


Multiplets | family 5:  74%|400/543 |███████▎  | 02:35


Multiplets | family 5:  92%|500/543 |█████████▏| 03:15


Multiplets | family 5: 100%|543/543 |██████████| 03:32


Families:  33%|███▎      | 1/3 [03:32<07:04, 212.27s/it]A

  [family 5] bootstrap progress: 543/543 multiplets (100%)

Multiplets | family 4:   0%|0/475 |          | 00:00


Multiplets | family 4:  21%|100/475 |██        | 00:29


Multiplets | family 4:  42%|200/475 |████▏     | 00:58


Multiplets | family 4:  63%|300/475 |██████▎   | 01:28


Multiplets | family 4:  84%|400/475 |████████▍ | 01:58


Multiplets | family 4: 100%|475/475 |██████████| 02:20


Families:  67%|██████▋   | 2/3 [05:52<02:49, 169.97s/it]A

  [family 4] bootstrap progress: 475/475 multiplets (100%)

Multiplets | family 3:   0%|0/67 |          | 00:00


Multiplets | family 3: 100%|67/67 |██████████| 00:14

  [family 3] bootstrap progress: 67/67 multiplets (100%)
Runtime: 366.813207 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 5:   0%|0/563 |          | 00:00


Multiplets | family 5:  18%|100/563 |█▊        | 01:04


Multiplets | family 5:  36%|200/563 |███▌      | 02:08



Multiplets | family 5:  53%|300/563 |█████▎    | 03:11


Multiplets | family 5:  71%|400/563 |███████   | 04:15


Multiplets | family 5:  89%|500/563 |████████▉ | 05:18


Multiplets | family 5: 100%|563/563 |██████████| 05:58


Families:  33%|███▎      | 1/3 [05:58<11:57, 358.81s/it]A

  [family 5] bootstrap progress: 563/563 multiplets (100%)

Multiplets | family 4:   0%|0/391 |          | 00:00
Multiplets | family 4:  26%|100/391 |██▌       | 00:46
Multiplets | family 4:  51%|200/391 |█████     | 01:34
Multiplets | family 4:  77%|300/391 |███████▋  | 02:20
Multiplets | family 4: 100%|391/391 |██████████| 03:04
Families:  67%|██████▋   | 2/3 [09:03<04:16, 256.15s/it]A

  [family 4] bootstrap progress: 391/391 multiplets (100%)

Multiplets | family 3:   0%|0/5 |          | 00:00
Multiplets | family 3: 100%|5/5 |██████████| 00:02

  [family 3] bootstrap progress: 5/5 multiplets (100%)
Runtime: 545.335277 s

Load pickle files.

In [49]:
# Load
with open("samp_distro_diags_POLY/ANBP_bca_selected_mults.pkl", "rb") as f:
    ANBP_bca_boot = pickle.load(f)

with open("samp_distro_diags_POLY/ANR_bca_selected_mults.pkl", "rb") as f:
    ANR_bca_boot = pickle.load(f)

with open("samp_distro_diags_POLY/BED_OSFED_bca_selected_mults.pkl", "rb") as f:
    BED_OSFED_bca_boot = pickle.load(f)

with open("samp_distro_diags_POLY/BN_bca_selected_mults.pkl", "rb") as f:
    BN_bca_boot = pickle.load(f)


# rebuild general dictionary
bca_samp_distros_diags = {
    'ANBP' : ANBP_bca_boot,
    'ANR' : ANR_bca_boot,
    'BED_OSFED' : BED_OSFED_bca_boot,
    'BN' : BN_bca_boot,
}

#### Assambling information: 
bca_samp_distros_diags contains the emp distros from the bca sampling for each multiplet.
Assemble info from multiplets and sample distributions just computed, by adding to the dict of the fdr survived multiplets info about the BCa sample_distro

In [54]:
BCa_fdr_diags = {}
for diagnosis in bca_samp_distros_diags:
    BCa_fdr_diags[diagnosis] = ut.get_BCa_input_dict_from_fdr(bca_samp_distros_diags[diagnosis],
                                                              fdr_neut_filtered_mults_diags[diagnosis])

BCa_fdr_diags contains the necessary info for computing the BCa (sample_distribution - row wise permutation included)
#### BCa

In [55]:
bca_multiplets_diags = {}
# for diagnosis, multiplets in op_multiplets_diags.items():
for diagnosis, multiplets in BCa_fdr_diags.items():
    start = time.perf_counter()
    # structure: order: multiple: samp_distro
    bca_multiplets_diags[diagnosis] = bca_bootopt.bca_bootstrap_parallel(multiplets_dict=multiplets, 
                                                                            X=EDI_diags[diagnosis])
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 677 multiplets

Families:  33%|███▎      | 1/3 [00:02<00:04,  2.31s/it]

  [BCa | family 5] 677/677 multiplets (100%)

[BCa | family 4] starting – 532 multiplets

Families: 100%|██████████| 3/3 [00:02<00:00,  1.15it/s]

  [BCa | family 4] 532/532 multiplets (100%)

[BCa | family 3] starting – 24 multiplets
  [BCa | family 3] 24/24 multiplets (100%)
Runtime: 2.618394 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 684 multiplets

Families:  33%|███▎      | 1/3 [00:00<00:00,  3.43it/s]

  [BCa | family 5] 684/684 multiplets (100%)

[BCa | family 4] starting – 487 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  5.08it/s]

  [BCa | family 4] 487/487 multiplets (100%)

[BCa | family 3] starting – 33 multiplets
  [BCa | family 3] 33/33 multiplets (100%)
Runtime: 0.594840 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 543 multiplets

Families:  33%|███▎      | 1/3 [00:00<00:00,  3.76it/s]

  [BCa | family 5] 543/543 multiplets (100%)

[BCa | family 4] starting – 475 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  5.41it/s]

  [BCa | family 4] 475/475 multiplets (100%)

[BCa | family 3] starting – 67 multiplets
  [BCa | family 3] 67/67 multiplets (100%)
Runtime: 0.553394 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 563 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  6.56it/s]

  [BCa | family 5] 563/563 multiplets (100%)

[BCa | family 4] starting – 391 multiplets
  [BCa | family 4] 391/391 multiplets (100%)

[BCa | family 3] starting – 5 multiplets
  [BCa | family 3] 5/5 multiplets (100%)
Runtime: 0.457038 s

### CI filtering
When running the BCa_CI_check procedure, the multiplets with not valid pvalue have already been filtered out.

In [58]:
from contextlib import redirect_stdout

BCa_selected_diags = {}
for diagnosis, multiplets in bca_multiplets_diags.items():
    with open(diagnosis + "_CI_warnings_POLY.txt", "w") as f:
        with redirect_stdout(f):
            BCa_selected_diags[diagnosis] = bca_bootopt.BCa_CI_mults_selection(bca_multiplets_diags[diagnosis])

### Stage 2, part 2: BCa_CI: plots and stats

In [59]:
base = 'POLY_part2_plots/'
n_boot = 1000

for diagnosis in bca_samp_distros_diags:
    out_dir = f"{base}{diagnosis}_figures"
    
    # bootstrap sampling
    # boot_arrays = bootstrap_multiplets_chunked(multiplets_dict=multiplets, X=X, n_boot=500)
    boot_arrays = bca_samp_distros_diags[diagnosis]

    # BCa confidence intervals
    # BCa_boot = bca_bootstrap_parallel(multiplets_dict=..., X=X, alpha=0.05)
    BCa_boot = bca_multiplets_diags[diagnosis]
    
    # selection — keeps only {family: {multiplet: hypothesis}}
    # BCa_selected = BCa_CI_mults_selection(BCa_boot, tol=0.05)
    BCa_selected = BCa_selected_diags[diagnosis]
    
    # re-join with full info for the survivors  
    BCa_boot_sel, boot_arrays_sel = bca_bootopt.retrieve_selected_multiplets_info(
        BCa_selected = BCa_selected,
        BCa_boot_full = BCa_boot,
        boot_arrays_full = boot_arrays,
    )              # {family: {multiplet: (obs, lo, hi, diag)}}

    # pick representative multiplets and plot
    reps = bca_plots.pick_representative_multiplets(BCa_boot_sel, 
                                                    boot_arrays_sel)
    bca_plots.plot_all(
        BCa_boot_all = BCa_boot_sel,
        n_samples = EDI_diags[diagnosis].shape[0],
        n_boot = n_boot,
        representative_multiplets = reps,
        output_dir=out_dir,
    )

  Family 5: 52/677 multiplets retrieved.
  Family 4: 530/532 multiplets retrieved.
  Family 3: 21/24 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(1, 27, 45, 55)  Ω=-0.7090  CI=[-0.9114, -0.5208]  margin from 0=0.5208  method=percentile
  most_borderline     multiplet=(8, 21, 51, 60)  Ω=-0.2924  CI=[-0.5591, -0.0056]  margin from 0=0.0056  method=percentile
  most_extreme        multiplet=(25, 33, 40, 51)  Ω=-1.2323  CI=[-1.4444, -0.9570]  margin from 0=0.9570  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → POLY_part2_plots/ANBP_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → POLY_part2_plots/ANBP_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (1, 27, 45, 55) ...
  saved → POLY_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult1_27_45_55.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (8, 21, 51, 60) ...
  saved → POLY_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult8_21_51_60.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (25, 33, 40, 51) ...
  saved → POLY_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult25_33_40_51.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → POLY_part2_plots/ANBP_figures\fig4_summary_table.pdf / .png

All figures saved to 'POLY_part2_plots/ANBP_figures/'.
  Family 5: 331/684 multiplets retrieved.
  Family 4: 471/487 multiplets retrieved.
  Family 3: 20/33 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(23, 57, 69, 87)  Ω=-0.5630  CI=[-0.8749, -0.5183]  margin from 0=0.5183  method=percentile
  most_borderline     multiplet=(37, 41, 50, 78)  Ω=-0.1573  CI=[-0.4208, -0.0013]  margin from 0=0.0013  method=percentile
  most_extreme        multiplet=(1, 33, 34, 52)  Ω=-1.0336  CI=[-1.3265, -0.9484]  margin from 0=0.9484  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → POLY_part2_plots/ANR_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → POLY_part2_plots/ANR_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (23, 57, 69, 87) ...
  saved → POLY_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult23_57_69_87.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (37, 41, 50, 78) ...
  saved → POLY_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult37_41_50_78.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (1, 33, 34, 52) ...
  saved → POLY_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult1_33_34_52.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → POLY_part2_plots/ANR_figures\fig4_summary_table.pdf / .png

All figures saved to 'POLY_part2_plots/ANR_figures/'.
  Family 5: 41/543 multiplets retrieved.
  Family 4: 474/475 multiplets retrieved.
  Family 3: 55/67 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(1, 10, 27, 50)  Ω=-0.7594  CI=[-0.9184, -0.4081]  margin from 0=0.4081  method=percentile
  most_borderline     multiplet=(9, 19, 45, 55)  Ω=+0.1365  CI=[0.0003, 0.4882]  margin from 0=0.0003  method=percentile
  most_extreme        multiplet=(20, 24, 43, 73)  Ω=-1.3193  CI=[-1.4736, -1.0620]  margin from 0=1.0620  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (1, 10, 27, 50) ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult1_10_27_50.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (9, 19, 45, 55) ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult9_19_45_55.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (20, 24, 43, 73) ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult20_24_43_73.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → POLY_part2_plots/BED_OSFED_figures\fig4_summary_table.pdf / .png

All figures saved to 'POLY_part2_plots/BED_OSFED_figures/'.
  Family 5: 288/563 multiplets retrieved.
  Family 4: 268/391 multiplets retrieved.
  Family 3: 3/5 multiplets retrieved.

Representative multiplets selected from family 5:
  most_typical        multiplet=(6, 11, 58, 63, 73)  Ω=-1.2900  CI=[-1.4114, -1.0743]  margin from 0=1.0743  method=percentile
  most_borderline     multiplet=(4, 5, 28, 38, 46)  Ω=-0.4988  CI=[-0.5750, -0.0054]  margin from 0=0.0054  method=percentile
  most_extreme        multiplet=(8, 17, 23, 42, 69)  Ω=-2.0576  CI=[-2.0594, -1.6282]  margin from 0=1.6282  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → POLY_part2_plots/BN_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → POLY_part2_plots/BN_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (6, 11, 58, 63, 73) ...
  saved → POLY_part2_plots/BN_figures\fig3_boot_dist_fam5_mult6_11_58_63_73.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (4, 5, 28, 38, 46) ...
  saved → POLY_part2_plots/BN_figures\fig3_boot_dist_fam5_mult4_5_28_38_46.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (8, 17, 23, 42, 69) ...
  saved → POLY_part2_plots/BN_figures\fig3_boot_dist_fam5_mult8_17_23_42_69.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → POLY_part2_plots/BN_figures\fig4_summary_table.pdf / .png

All figures saved to 'POLY_part2_plots/BN_figures/'.

Save to pickle files.

In [60]:
out_dir_bca = "bca_selected_POLY"  
os.makedirs(out_dir_bca, exist_ok=True)

for diagnosis, bca_multiplets in BCa_selected_diags.items():
    fname = f"{diagnosis}_bca_selected_mults.pkl"
    fpath = os.path.join(out_dir_bca, fname)
    with open(fpath, "wb") as f:
        pickle.dump(bca_multiplets, f, protocol=pickle.HIGHEST_PROTOCOL)

### Hyperedges selection's results

- fdr_neut_filtered_mults_diags (???)

- bca_selected

In [61]:
# Load
with open("bca_selected_POLY/ANBP_bca_selected_mults.pkl", "rb") as f:
    ANBP_bca_sel = pickle.load(f)

with open("bca_selected_POLY/ANR_bca_selected_mults.pkl", "rb") as f:
    ANR_bca_sel = pickle.load(f)

with open("bca_selected_POLY/BED_OSFED_bca_selected_mults.pkl", "rb") as f:
    BED_OSFED_bca_sel = pickle.load(f)

with open("bca_selected_POLY/BN_bca_selected_mults.pkl", "rb") as f:
    BN_bca_sel = pickle.load(f)


# rebuild general dictionary
BCa_selected_diags = {
    'ANBP' : ANBP_bca_sel,
    'ANR' : ANR_bca_sel,
    'BED_OSFED' : BED_OSFED_bca_sel,
    'BN' : BN_bca_sel
}

How many multiplets have been selected? of which type?

In [62]:
ut.describe_hyperedges(BCa_selected_diags)

Diagnosis: ANBP
	 Order 5:
	 	 Synergy: 51 Redundancy: 1
	 Order 4:
	 	 Synergy: 528 Redundancy: 2
	 Order 3:
	 	 Synergy: 21 Redundancy: 0
Diagnosis: ANR
	 Order 5:
	 	 Synergy: 321 Redundancy: 10
	 Order 4:
	 	 Synergy: 464 Redundancy: 7
	 Order 3:
	 	 Synergy: 2 Redundancy: 18
Diagnosis: BED_OSFED
	 Order 5:
	 	 Synergy: 25 Redundancy: 16
	 Order 4:
	 	 Synergy: 470 Redundancy: 4
	 Order 3:
	 	 Synergy: 55 Redundancy: 0
Diagnosis: BN
	 Order 5:
	 	 Synergy: 288 Redundancy: 0
	 Order 4:
	 	 Synergy: 268 Redundancy: 0
	 Order 3:
	 	 Synergy: 0 Redundancy: 3

#### Compute omega for the survived multiplets.

In [63]:
selected_multiplets_diags = {}
for diagnosis, multiplets in BCa_selected_diags.items():
    start = time.perf_counter()
    selected_multiplets_diags[diagnosis] = pp_bootopt.compute_omega_for_multiplets(multiplets_dict=multiplets, 
                                                                                   X=EDI_diags[diagnosis])
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Runtime: 0.941396 s
Runtime: 1.902751 s
Runtime: 0.763786 s
Runtime: 1.308578 s

In [64]:
selected_multiplets_diags['BED_OSFED']

     order       label     omega  node1  node2  node3  node4  node5
0        3     synergy -0.114467      6      7      8   <NA>   <NA>
1        3     synergy -0.107667      6      7     85   <NA>   <NA>
2        3     synergy -0.134632      6     35     76   <NA>   <NA>
3        3     synergy -0.134829      8     27     44   <NA>   <NA>
4        3     synergy -0.124578     10     18     20   <NA>   <NA>
..     ...         ...       ...    ...    ...    ...    ...    ...
565      5  redundancy  0.247899      7     11     16     49     68
566      5  redundancy  0.240815      7     16     32     49     53
567      5     synergy -0.978040      8     12     21     88     90
568      5     synergy -0.402055      9     10     20     42     55
569      5  redundancy  0.223452     12     19     31     32     45

[570 rows x 8 columns]

In [65]:
# skip dir creation if it already exist
out_dir_sm = "selected_cliques_POLY" 
os.makedirs(out_dir_sm, exist_ok=True)

for diagnosis, df in selected_multiplets_diags.items():
    fname = f"{diagnosis}_selected_df_ce.csv"
    fpath = os.path.join(out_dir_sm, fname)
    df.to_csv(fpath, index=False)

### Part 3: MULTIPLETS' CIs COMPARISON (Hierarchical Pruning)

**Purpose:** Remove multiplets that are explained by their lower-order subsets.

**Procedure:**

1. **Comparison with (k-1)-subsets:**
   - For each k-multiplet M with confidence interval CI(M), extract all (k-1)-subsets
   - For each subset S, retrieve its confidence interval CI(S)

2. **Overlap detection:**
   - Check if CI(M) overlaps with CI(S) for any subset
   - Overlap criterion: max(lo_M, lo_S) ≤ min(hi_M, hi_S)

3. **Filtering rule:**
   - **Discard M if** any (k-1)-subset's CI overlaps with M's CI
   - **Rationale:** Overlapping CIs indicate no statistically significant added higher-order effect beyond lower-order structure (Marinazzo et al., 2024)
   - **Keep M if** no subset CI overlaps (genuine k-order effect)

**Output:** Hierarchically-validated multiplets representing true higher-order interactions.

Get the right structure for further functs.

In [66]:
# pre: BCa_selected_diags['ANBP'][5][(-,-,-,-,-)]: synergy/redundancy
selected_as_list = ut.get_selected_INTER(BCa_selected_diags)

Recompute row wise omega distributions for CIs, then CIs (the whole procedure for selected multiplets) - for Hierchical Pruning.

In [67]:
selected_boot_stats = {}
for diagnosis, mults in selected_as_list.items():
    start = time.perf_counter()
    selected_boot_stats[diagnosis] = bca_bootopt.get_boot_stats_parallel(multiplets_dict=mults, 
                                                                            X=EDI_diags[diagnosis], 
                                                                            n_boot=1000)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]
Multiplets | family 5:   0%|          | 0/52 [00:00<?, ?it/s]


  0%|          | 0/52 [00:00<?, ?it/s]


  2%|▏         | 1/52 [00:05<04:39,  5.49s/it]


  6%|▌         | 3/52 [00:05<01:11,  1.46s/it]


 15%|█▌        | 8/52 [00:05<00:18,  2.40it/s]


 21%|██        | 11/52 [00:08<00:27,  1.47it/s]


 27%|██▋       | 14/52 [00:09<00:17,  2.20it/s]


 31%|███       | 16/52 [00:09<00:12,  2.80it/s]


 35%|███▍      | 18/52 [00:12<00:23,  1.47it/s]


 38%|███▊      | 20/52 [00:12<00:16,  1.91it/s]


 42%|████▏     | 22/52 [00:12<00:11,  2.51it/s]


 46%|████▌     | 24/52 [00:13<00:09,  3.00it/s]


 48%|████▊     | 25/52 [00:15<00:20,  1.34it/s]


 52%|█████▏    | 27/52 [00:16<00:13,  1.86it/s]


 54%|█████▍    | 28/52 [00:16<00:13,  1.83it/s]


 60%|█████▉    | 31/52 [00:16<00:07,  2.96it/s]


 62%|██████▏   | 32/52 [00:17<00:07,  2.59it/s]


 63%|██████▎   | 33/52 [00:19<00:12,  1.52it/s]


 65%|██████▌   | 34/52 [00:19<00:10,  1.78it/s]


 67%|██████▋   | 35/52 [00:20<00:09,  1.79it/s]


 69%|██████▉   | 36/52 [00:20<00:07,  2.24it/s]


 71%|███████   | 37/52 [00:20<00:05,  2.82it/s]


 73%|███████▎  | 38/52 [00:20<00:05,  2.77it/s]


 75%|███████▌  | 39/52 [00:20<00:04,  3.14it/s]


 77%|███████▋  | 40/52 [00:21<00:04,  2.75it/s]


 79%|███████▉  | 41/52 [00:22<00:07,  1.46it/s]


 81%|████████  | 42/52 [00:23<00:05,  1.76it/s]


 83%|████████▎ | 43/52 [00:23<00:04,  1.85it/s]


 85%|████████▍ | 44/52 [00:23<00:03,  2.35it/s]


 88%|████████▊ | 46/52 [00:24<00:01,  3.04it/s]


 90%|█████████ | 47/52 [00:24<00:01,  3.56it/s]


 92%|█████████▏| 48/52 [00:24<00:01,  3.17it/s]


 94%|█████████▍| 49/52 [00:25<00:01,  2.12it/s]


 96%|█████████▌| 50/52 [00:25<00:00,  2.56it/s]


 98%|█████████▊| 51/52 [00:26<00:00,  2.77it/s]


100%|██████████| 52/52 [00:26<00:00,  1.98it/s]
Multiplets | family 5:   0%|          | 0/52 [00:26<?, ?it/s]

Multiplets | family 4:   0%|          | 0/530 [00:00<?, ?it/s]


  0%|          | 0/530 [00:00<?, ?it/s]


  0%|          | 1/530 [00:02<22:37,  2.57s/it]


  1%|          | 6/530 [00:02<03:02,  2.86it/s]


  2%|▏         | 9/530 [00:05<04:38,  1.87it/s]


  2%|▏         | 12/530 [00:05<03:03,  2.82it/s]


  3%|▎         | 14/530 [00:05<02:42,  3.18it/s]


  3%|▎         | 17/530 [00:07<03:45,  2.27it/s]


  3%|▎         | 18/530 [00:07<03:31,  2.43it/s]


  4%|▍         | 20/530 [00:08<02:37,  3.23it/s]


  4%|▍         | 21/530 [00:08<02:32,  3.34it/s]


  4%|▍         | 22/530 [00:08<02:19,  3.65it/s]


  5%|▍         | 24/530 [00:08<01:51,  4.53it/s]


  5%|▍         | 25/530 [00:10<04:18,  1.95it/s]


  5%|▍         | 26/530 [00:10<03:47,  2.21it/s]


  5%|▌         | 28/530 [00:10<02:35,  3.22it/s]


  5%|▌         | 29/530 [00:11<02:28,  3.38it/s]


  6%|▌         | 30/530 [00:11<02:08,  3.90it/s]


  6%|▌         | 32/530 [00:11<01:41,  4.92it/s]


  6%|▌         | 33/530 [00:13<04:26,  1.86it/s]


  6%|▋         | 34/530 [00:13<03:53,  2.13it/s]


  7%|▋         | 36/530 [00:13<02:34,  3.20it/s]


  7%|▋         | 37/530 [00:13<02:18,  3.55it/s]


  7%|▋         | 38/530 [00:13<01:58,  4.14it/s]


  8%|▊         | 40/530 [00:14<01:33,  5.21it/s]


  8%|▊         | 41/530 [00:15<04:24,  1.85it/s]


  8%|▊         | 42/530 [00:15<03:40,  2.21it/s]


  8%|▊         | 43/530 [00:16<02:57,  2.74it/s]


  8%|▊         | 45/530 [00:16<02:08,  3.79it/s]


  9%|▊         | 46/530 [00:16<01:51,  4.33it/s]


  9%|▉         | 48/530 [00:16<01:38,  4.88it/s]


  9%|▉         | 49/530 [00:18<04:06,  1.95it/s]


  9%|▉         | 50/530 [00:18<03:40,  2.17it/s]


 10%|▉         | 51/530 [00:18<02:56,  2.72it/s]


 10%|█         | 53/530 [00:18<01:51,  4.28it/s]


 10%|█         | 55/530 [00:19<01:43,  4.59it/s]


 11%|█         | 56/530 [00:19<01:43,  4.57it/s]


 11%|█         | 57/530 [00:21<04:24,  1.79it/s]


 11%|█         | 58/530 [00:21<03:45,  2.10it/s]


 11%|█         | 59/530 [00:21<03:04,  2.56it/s]


 12%|█▏        | 62/530 [00:21<01:51,  4.19it/s]


 12%|█▏        | 63/530 [00:22<01:54,  4.06it/s]


 12%|█▏        | 64/530 [00:22<01:41,  4.58it/s]


 12%|█▏        | 65/530 [00:23<04:20,  1.79it/s]


 12%|█▏        | 66/530 [00:24<03:33,  2.17it/s]


 13%|█▎        | 67/530 [00:24<03:02,  2.54it/s]


 13%|█▎        | 68/530 [00:24<03:02,  2.54it/s]


 13%|█▎        | 70/530 [00:24<01:52,  4.08it/s]


 14%|█▎        | 72/530 [00:25<01:38,  4.63it/s]


 14%|█▍        | 73/530 [00:26<03:34,  2.13it/s]


 14%|█▍        | 74/530 [00:26<03:30,  2.17it/s]


 14%|█▍        | 75/530 [00:27<03:02,  2.49it/s]


 14%|█▍        | 76/530 [00:27<02:26,  3.10it/s]


 15%|█▍        | 77/530 [00:27<02:03,  3.66it/s]


 15%|█▍        | 79/530 [00:27<01:25,  5.30it/s]


 15%|█▌        | 80/530 [00:27<01:39,  4.53it/s]


 15%|█▌        | 81/530 [00:29<03:40,  2.03it/s]


 15%|█▌        | 82/530 [00:29<03:50,  1.94it/s]


 16%|█▌        | 83/530 [00:29<03:01,  2.46it/s]


 16%|█▌        | 85/530 [00:30<02:09,  3.43it/s]


 16%|█▋        | 87/530 [00:30<01:45,  4.21it/s]


 17%|█▋        | 88/530 [00:30<01:37,  4.52it/s]


 17%|█▋        | 89/530 [00:31<03:16,  2.24it/s]


 17%|█▋        | 90/530 [00:32<03:29,  2.10it/s]


 17%|█▋        | 91/530 [00:32<02:49,  2.59it/s]


 17%|█▋        | 92/530 [00:32<02:41,  2.71it/s]


 18%|█▊        | 94/530 [00:33<02:04,  3.49it/s]


 18%|█▊        | 95/530 [00:33<01:52,  3.87it/s]


 18%|█▊        | 96/530 [00:33<01:40,  4.30it/s]


 18%|█▊        | 97/530 [00:34<03:48,  1.90it/s]


 18%|█▊        | 98/530 [00:35<03:00,  2.39it/s]


 19%|█▉        | 100/530 [00:35<02:32,  2.82it/s]


 19%|█▉        | 101/530 [00:35<02:32,  2.82it/s]


 19%|█▉        | 103/530 [00:36<02:06,  3.37it/s]


 20%|█▉        | 104/530 [00:36<02:04,  3.43it/s]


 20%|█▉        | 105/530 [00:37<03:05,  2.29it/s]


 20%|██        | 106/530 [00:37<03:03,  2.31it/s]


 20%|██        | 107/530 [00:38<02:42,  2.60it/s]


 21%|██        | 109/530 [00:38<02:32,  2.76it/s]


 21%|██        | 111/530 [00:39<01:48,  3.87it/s]


 21%|██        | 112/530 [00:39<01:57,  3.55it/s]


 21%|██▏       | 113/530 [00:40<02:51,  2.43it/s]


 22%|██▏       | 114/530 [00:40<03:08,  2.21it/s]


 22%|██▏       | 115/530 [00:40<02:34,  2.69it/s]


 22%|██▏       | 116/530 [00:41<02:13,  3.10it/s]


 22%|██▏       | 117/530 [00:41<02:13,  3.10it/s]


 22%|██▏       | 118/530 [00:41<02:08,  3.21it/s]


 22%|██▏       | 119/530 [00:42<02:04,  3.30it/s]


 23%|██▎       | 120/530 [00:42<02:15,  3.03it/s]


 23%|██▎       | 121/530 [00:43<02:49,  2.41it/s]


 23%|██▎       | 122/530 [00:43<02:39,  2.56it/s]


 23%|██▎       | 123/530 [00:43<02:21,  2.88it/s]


 23%|██▎       | 124/530 [00:43<01:59,  3.40it/s]


 24%|██▎       | 125/530 [00:44<02:16,  2.97it/s]


 24%|██▍       | 126/530 [00:44<02:21,  2.85it/s]


 24%|██▍       | 127/530 [00:44<02:07,  3.17it/s]


 24%|██▍       | 128/530 [00:45<02:01,  3.30it/s]


 24%|██▍       | 129/530 [00:45<02:22,  2.82it/s]


 25%|██▍       | 130/530 [00:45<02:20,  2.85it/s]

 25%|██▍       | 131/530 [00:46<02:19,  2.87it/s]


 25%|██▌       | 133/530 [00:46<02:16,  2.90it/s]


 25%|██▌       | 134/530 [00:47<02:18,  2.87it/s]


 25%|██▌       | 135/530 [00:47<02:09,  3.06it/s]


 26%|██▌       | 136/530 [00:47<01:58,  3.32it/s]


 26%|██▌       | 137/530 [00:48<02:16,  2.88it/s]


 26%|██▌       | 138/530 [00:48<02:03,  3.18it/s]


 26%|██▌       | 139/530 [00:48<02:20,  2.79it/s]


 27%|██▋       | 141/530 [00:49<02:08,  3.02it/s]


 27%|██▋       | 142/530 [00:49<02:11,  2.95it/s]


 27%|██▋       | 143/530 [00:50<02:07,  3.02it/s]


 27%|██▋       | 144/530 [00:50<01:57,  3.29it/s]


 27%|██▋       | 145/530 [00:51<02:25,  2.64it/s]


 28%|██▊       | 146/530 [00:51<02:00,  3.20it/s]


 28%|██▊       | 147/530 [00:51<02:16,  2.80it/s]


 28%|██▊       | 149/530 [00:52<02:15,  2.82it/s]


 28%|██▊       | 150/530 [00:52<02:20,  2.70it/s]


 28%|██▊       | 151/530 [00:52<01:59,  3.17it/s]


 29%|██▊       | 152/530 [00:53<01:56,  3.23it/s]


 29%|██▉       | 153/530 [00:53<02:14,  2.81it/s]


 29%|██▉       | 154/530 [00:53<01:58,  3.17it/s]


 29%|██▉       | 155/530 [00:54<02:06,  2.95it/s]


 29%|██▉       | 156/530 [00:54<01:42,  3.64it/s]


 30%|██▉       | 157/530 [00:55<02:34,  2.42it/s]


 30%|██▉       | 158/530 [00:55<02:21,  2.64it/s]


 30%|███       | 159/530 [00:55<02:06,  2.93it/s]


 30%|███       | 160/530 [00:56<02:12,  2.80it/s]


 30%|███       | 161/530 [00:56<02:18,  2.67it/s]


 31%|███       | 162/530 [00:56<02:03,  2.98it/s]


 31%|███       | 163/530 [00:57<02:35,  2.36it/s]


 31%|███       | 165/530 [00:57<01:51,  3.27it/s]


 31%|███▏      | 166/530 [00:58<02:00,  3.01it/s]


 32%|███▏      | 167/530 [00:58<02:12,  2.75it/s]


 32%|███▏      | 168/530 [00:58<01:54,  3.17it/s]


 32%|███▏      | 169/530 [00:59<02:16,  2.65it/s]


 32%|███▏      | 170/530 [00:59<02:03,  2.92it/s]


 32%|███▏      | 171/530 [01:00<02:35,  2.30it/s]


 33%|███▎      | 173/530 [01:00<01:39,  3.59it/s]


 33%|███▎      | 174/530 [01:01<02:16,  2.60it/s]


 33%|███▎      | 175/530 [01:01<02:04,  2.85it/s]


 33%|███▎      | 177/530 [01:02<01:59,  2.95it/s]


 34%|███▎      | 178/530 [01:02<02:00,  2.93it/s]


 34%|███▍      | 179/530 [01:02<02:11,  2.68it/s]


 34%|███▍      | 180/530 [01:03<01:49,  3.21it/s]


 34%|███▍      | 181/530 [01:03<01:29,  3.90it/s]


 34%|███▍      | 182/530 [01:03<02:18,  2.51it/s]


 35%|███▍      | 183/530 [01:04<01:56,  2.98it/s]


 35%|███▍      | 184/530 [01:04<01:33,  3.69it/s]


 35%|███▍      | 185/530 [01:04<01:48,  3.19it/s]


 35%|███▌      | 186/530 [01:05<01:57,  2.93it/s]


 35%|███▌      | 187/530 [01:05<02:11,  2.60it/s]


 35%|███▌      | 188/530 [01:05<01:57,  2.92it/s]


 36%|███▌      | 190/530 [01:06<02:06,  2.68it/s]


 36%|███▌      | 191/530 [01:06<01:57,  2.89it/s]


 36%|███▋      | 193/530 [01:07<01:45,  3.20it/s]


 37%|███▋      | 194/530 [01:07<01:58,  2.84it/s]


 37%|███▋      | 195/530 [01:08<01:52,  2.98it/s]


 37%|███▋      | 196/530 [01:08<01:58,  2.83it/s]


 37%|███▋      | 197/530 [01:08<01:36,  3.44it/s]


 37%|███▋      | 198/530 [01:09<02:38,  2.10it/s]


 38%|███▊      | 200/530 [01:09<01:35,  3.45it/s]


 38%|███▊      | 201/530 [01:10<02:00,  2.73it/s]


 38%|███▊      | 202/530 [01:10<01:51,  2.95it/s]


 38%|███▊      | 203/530 [01:11<02:02,  2.67it/s]


 38%|███▊      | 204/530 [01:11<02:00,  2.71it/s]


 39%|███▊      | 205/530 [01:11<01:51,  2.93it/s]


 39%|███▉      | 206/530 [01:12<02:12,  2.44it/s]


 39%|███▉      | 207/530 [01:12<01:47,  3.00it/s]


 39%|███▉      | 208/530 [01:12<01:51,  2.89it/s]


 39%|███▉      | 209/530 [01:13<01:46,  3.01it/s]


 40%|███▉      | 210/530 [01:13<01:49,  2.92it/s]


 40%|███▉      | 211/530 [01:13<01:49,  2.92it/s]


 40%|████      | 212/530 [01:14<01:51,  2.86it/s]


 40%|████      | 213/530 [01:14<01:52,  2.82it/s]


 40%|████      | 214/530 [01:15<02:21,  2.23it/s]


 41%|████      | 216/530 [01:15<01:49,  2.88it/s]


 41%|████      | 217/530 [01:15<01:31,  3.42it/s]


 41%|████      | 218/530 [01:16<01:35,  3.25it/s]


 41%|████▏     | 219/530 [01:16<01:27,  3.54it/s]


 42%|████▏     | 220/530 [01:16<01:52,  2.75it/s]


 42%|████▏     | 221/530 [01:17<01:41,  3.06it/s]


 42%|████▏     | 222/530 [01:17<02:13,  2.30it/s]


 42%|████▏     | 223/530 [01:17<01:43,  2.97it/s]


 42%|████▏     | 224/530 [01:18<01:47,  2.85it/s]


 43%|████▎     | 226/530 [01:18<01:23,  3.66it/s]


 43%|████▎     | 227/530 [01:18<01:22,  3.66it/s]


 43%|████▎     | 228/530 [01:19<01:43,  2.93it/s]


 43%|████▎     | 229/530 [01:19<01:38,  3.07it/s]


 43%|████▎     | 230/530 [01:20<02:12,  2.27it/s]


 44%|████▍     | 232/530 [01:21<01:45,  2.82it/s]


 44%|████▍     | 234/530 [01:21<01:23,  3.55it/s]


 44%|████▍     | 235/530 [01:21<01:22,  3.57it/s]


 45%|████▍     | 236/530 [01:22<01:38,  2.98it/s]


 45%|████▍     | 237/530 [01:22<01:31,  3.20it/s]


 45%|████▍     | 238/530 [01:23<02:31,  1.93it/s]


 45%|████▌     | 239/530 [01:23<02:04,  2.34it/s]


 45%|████▌     | 241/530 [01:23<01:25,  3.39it/s]


 46%|████▌     | 242/530 [01:24<01:27,  3.29it/s]


 46%|████▌     | 243/530 [01:24<01:19,  3.62it/s]


 46%|████▌     | 244/530 [01:24<01:28,  3.22it/s]


 46%|████▌     | 245/530 [01:25<01:30,  3.16it/s]


 46%|████▋     | 246/530 [01:26<02:31,  1.88it/s]


 47%|████▋     | 247/530 [01:26<02:05,  2.25it/s]


 47%|████▋     | 248/530 [01:26<01:42,  2.76it/s]


 47%|████▋     | 250/530 [01:27<01:36,  2.90it/s]


 48%|████▊     | 252/530 [01:27<01:14,  3.72it/s]


 48%|████▊     | 253/530 [01:28<01:27,  3.16it/s]


 48%|████▊     | 254/530 [01:29<02:13,  2.06it/s]


 48%|████▊     | 255/530 [01:29<01:54,  2.40it/s]


 48%|████▊     | 257/530 [01:29<01:12,  3.76it/s]


 49%|████▊     | 258/530 [01:29<01:28,  3.09it/s]


 49%|████▉     | 259/530 [01:30<01:21,  3.34it/s]


 49%|████▉     | 260/530 [01:30<01:14,  3.61it/s]


 49%|████▉     | 261/530 [01:30<01:29,  3.00it/s]


 49%|████▉     | 262/530 [01:31<02:22,  1.88it/s]


 50%|████▉     | 264/530 [01:32<01:30,  2.95it/s]


 50%|█████     | 265/530 [01:32<01:26,  3.07it/s]


 50%|█████     | 266/530 [01:32<01:19,  3.32it/s]


 50%|█████     | 267/530 [01:33<01:34,  2.79it/s]


 51%|█████     | 269/530 [01:33<01:22,  3.15it/s]


 51%|█████     | 270/530 [01:34<01:58,  2.19it/s]


 51%|█████▏    | 272/530 [01:34<01:21,  3.17it/s]


 52%|█████▏    | 273/530 [01:35<01:21,  3.15it/s]


 52%|█████▏    | 274/530 [01:35<01:14,  3.42it/s]


 52%|█████▏    | 275/530 [01:35<01:29,  2.86it/s]


 52%|█████▏    | 277/530 [01:36<01:25,  2.97it/s]


 52%|█████▏    | 278/530 [01:37<01:47,  2.35it/s]


 53%|█████▎    | 280/530 [01:37<01:17,  3.21it/s]


 53%|█████▎    | 281/530 [01:38<01:37,  2.56it/s]


 53%|█████▎    | 283/530 [01:38<01:32,  2.68it/s]


 54%|█████▎    | 284/530 [01:38<01:18,  3.13it/s]


 54%|█████▍    | 285/530 [01:39<01:19,  3.08it/s]


 54%|█████▍    | 286/530 [01:40<01:44,  2.34it/s]


 54%|█████▍    | 287/530 [01:40<01:23,  2.90it/s]

 55%|█████▍    | 289/530 [01:40<01:30,  2.66it/s]


 55%|█████▍    | 290/530 [01:41<01:23,  2.86it/s]


 55%|█████▍    | 291/530 [01:41<01:35,  2.51it/s]


 55%|█████▌    | 292/530 [01:42<01:25,  2.80it/s]


 55%|█████▌    | 294/530 [01:42<01:18,  2.99it/s]


 56%|█████▌    | 295/530 [01:42<01:17,  3.05it/s]


 56%|█████▌    | 296/530 [01:43<01:14,  3.13it/s]


 56%|█████▌    | 297/530 [01:43<01:32,  2.53it/s]


 56%|█████▌    | 298/530 [01:43<01:13,  3.15it/s]


 56%|█████▋    | 299/530 [01:44<01:33,  2.47it/s]


 57%|█████▋    | 300/530 [01:44<01:20,  2.86it/s]


 57%|█████▋    | 302/530 [01:45<01:16,  2.96it/s]


 57%|█████▋    | 303/530 [01:45<01:14,  3.06it/s]


 57%|█████▋    | 304/530 [01:45<01:09,  3.25it/s]


 58%|█████▊    | 305/530 [01:46<01:24,  2.65it/s]


 58%|█████▊    | 306/530 [01:46<01:16,  2.94it/s]


 58%|█████▊    | 307/530 [01:47<01:23,  2.66it/s]


 58%|█████▊    | 308/530 [01:47<01:07,  3.31it/s]


 58%|█████▊    | 310/530 [01:48<01:22,  2.68it/s]


 59%|█████▉    | 312/530 [01:48<01:05,  3.35it/s]


 59%|█████▉    | 313/530 [01:49<01:20,  2.69it/s]


 59%|█████▉    | 314/530 [01:49<01:10,  3.06it/s]


 59%|█████▉    | 315/530 [01:49<01:15,  2.84it/s]


 60%|█████▉    | 317/530 [01:50<00:51,  4.16it/s]


 60%|██████    | 318/530 [01:51<01:24,  2.50it/s]


 60%|██████    | 320/530 [01:51<01:07,  3.13it/s]


 61%|██████    | 321/530 [01:52<01:19,  2.62it/s]


 61%|██████    | 322/530 [01:52<01:27,  2.37it/s]


 61%|██████    | 323/530 [01:52<01:10,  2.92it/s]


 61%|██████▏   | 325/530 [01:53<00:55,  3.68it/s]


 62%|██████▏   | 326/530 [01:54<01:30,  2.26it/s]


 62%|██████▏   | 328/530 [01:54<01:04,  3.11it/s]


 62%|██████▏   | 329/530 [01:54<01:09,  2.90it/s]


 62%|██████▏   | 330/530 [01:55<01:17,  2.57it/s]


 62%|██████▏   | 331/530 [01:55<01:03,  3.13it/s]


 63%|██████▎   | 332/530 [01:55<00:55,  3.60it/s]


 63%|██████▎   | 333/530 [01:55<00:54,  3.60it/s]


 63%|██████▎   | 334/530 [01:56<01:28,  2.21it/s]


 63%|██████▎   | 336/530 [01:56<00:59,  3.28it/s]


 64%|██████▎   | 337/530 [01:57<01:05,  2.96it/s]


 64%|██████▍   | 338/530 [01:58<01:18,  2.44it/s]


 64%|██████▍   | 339/530 [01:58<01:09,  2.75it/s]


 64%|██████▍   | 341/530 [01:58<00:47,  3.97it/s]


 65%|██████▍   | 342/530 [01:59<01:21,  2.30it/s]


 65%|██████▍   | 344/530 [01:59<01:05,  2.86it/s]


 65%|██████▌   | 346/530 [02:00<01:09,  2.65it/s]


 66%|██████▌   | 348/530 [02:01<01:00,  3.01it/s]


 66%|██████▌   | 349/530 [02:01<00:53,  3.41it/s]


 66%|██████▌   | 350/530 [02:02<01:07,  2.67it/s]


 66%|██████▌   | 351/530 [02:02<01:00,  2.96it/s]


 66%|██████▋   | 352/530 [02:02<00:59,  2.99it/s]


 67%|██████▋   | 353/530 [02:02<00:52,  3.35it/s]


 67%|██████▋   | 354/530 [02:03<01:12,  2.41it/s]


 67%|██████▋   | 356/530 [02:04<00:58,  3.00it/s]


 68%|██████▊   | 358/530 [02:04<00:59,  2.88it/s]


 68%|██████▊   | 359/530 [02:05<01:00,  2.83it/s]


 68%|██████▊   | 360/530 [02:05<01:00,  2.79it/s]


 68%|██████▊   | 361/530 [02:05<00:51,  3.27it/s]


 68%|██████▊   | 362/530 [02:06<01:02,  2.71it/s]


 69%|██████▊   | 364/530 [02:06<00:52,  3.18it/s]


 69%|██████▉   | 365/530 [02:06<00:44,  3.72it/s]


 69%|██████▉   | 366/530 [02:07<00:59,  2.74it/s]


 69%|██████▉   | 367/530 [02:07<01:05,  2.49it/s]


 69%|██████▉   | 368/530 [02:08<00:58,  2.77it/s]


 70%|██████▉   | 369/530 [02:08<00:50,  3.16it/s]


 70%|██████▉   | 370/530 [02:08<00:55,  2.91it/s]


 70%|███████   | 371/530 [02:08<00:43,  3.65it/s]


 70%|███████   | 372/530 [02:09<00:55,  2.85it/s]


 70%|███████   | 373/530 [02:09<00:46,  3.39it/s]


 71%|███████   | 374/530 [02:10<00:55,  2.82it/s]


 71%|███████   | 375/530 [02:10<01:05,  2.38it/s]


 71%|███████   | 376/530 [02:10<00:55,  2.78it/s]


 71%|███████   | 377/530 [02:11<00:50,  3.04it/s]


 71%|███████▏  | 378/530 [02:11<00:58,  2.59it/s]


 72%|███████▏  | 380/530 [02:12<00:49,  3.01it/s]


 72%|███████▏  | 381/530 [02:12<00:43,  3.43it/s]


 72%|███████▏  | 382/530 [02:12<00:54,  2.73it/s]


 72%|███████▏  | 383/530 [02:13<01:03,  2.30it/s]


 73%|███████▎  | 385/530 [02:13<00:47,  3.07it/s]


 73%|███████▎  | 386/530 [02:14<00:56,  2.55it/s]


 73%|███████▎  | 388/530 [02:15<00:53,  2.67it/s]


 73%|███████▎  | 389/530 [02:15<00:46,  3.06it/s]


 74%|███████▎  | 390/530 [02:15<00:43,  3.23it/s]


 74%|███████▍  | 391/530 [02:16<00:55,  2.49it/s]


 74%|███████▍  | 392/530 [02:16<00:46,  2.94it/s]


 74%|███████▍  | 394/530 [02:17<00:47,  2.86it/s]


 75%|███████▍  | 395/530 [02:17<00:48,  2.79it/s]


 75%|███████▍  | 396/530 [02:18<00:55,  2.42it/s]


 75%|███████▌  | 399/530 [02:19<00:46,  2.83it/s]


 75%|███████▌  | 400/530 [02:19<00:39,  3.26it/s]


 76%|███████▌  | 402/530 [02:19<00:43,  2.98it/s]


 76%|███████▌  | 403/530 [02:20<00:45,  2.80it/s]


 76%|███████▌  | 404/530 [02:20<00:47,  2.64it/s]


 76%|███████▋  | 405/530 [02:21<00:40,  3.09it/s]


 77%|███████▋  | 407/530 [02:21<00:44,  2.76it/s]


 77%|███████▋  | 410/530 [02:22<00:37,  3.20it/s]


 78%|███████▊  | 411/530 [02:23<00:43,  2.73it/s]


 78%|███████▊  | 412/530 [02:23<00:44,  2.62it/s]


 78%|███████▊  | 413/530 [02:23<00:37,  3.08it/s]


 78%|███████▊  | 414/530 [02:23<00:31,  3.63it/s]


 78%|███████▊  | 415/530 [02:24<00:39,  2.89it/s]


 79%|███████▊  | 417/530 [02:24<00:26,  4.21it/s]


 79%|███████▉  | 418/530 [02:25<00:38,  2.94it/s]


 79%|███████▉  | 419/530 [02:26<00:48,  2.30it/s]


 79%|███████▉  | 420/530 [02:26<00:43,  2.55it/s]


 79%|███████▉  | 421/530 [02:26<00:36,  2.99it/s]


 80%|███████▉  | 422/530 [02:26<00:31,  3.42it/s]


 80%|███████▉  | 423/530 [02:27<00:36,  2.92it/s]


 80%|████████  | 424/530 [02:27<00:34,  3.11it/s]


 80%|████████  | 425/530 [02:27<00:30,  3.41it/s]


 80%|████████  | 426/530 [02:28<00:34,  2.99it/s]


 81%|████████  | 427/530 [02:28<00:50,  2.03it/s]


 81%|████████  | 428/530 [02:29<00:41,  2.47it/s]


 81%|████████  | 429/530 [02:29<00:32,  3.13it/s]


 81%|████████▏ | 431/530 [02:29<00:30,  3.23it/s]


 82%|████████▏ | 432/530 [02:30<00:32,  3.00it/s]


 82%|████████▏ | 433/530 [02:30<00:28,  3.46it/s]


 82%|████████▏ | 434/530 [02:30<00:29,  3.29it/s]


 82%|████████▏ | 435/530 [02:31<00:48,  1.96it/s]


 82%|████████▏ | 436/530 [02:32<00:41,  2.29it/s]


 83%|████████▎ | 438/530 [02:32<00:24,  3.69it/s]


 83%|████████▎ | 439/530 [02:32<00:24,  3.70it/s]


 83%|████████▎ | 440/530 [02:33<00:41,  2.14it/s]


 83%|████████▎ | 442/530 [02:33<00:27,  3.21it/s]


 84%|████████▎ | 443/530 [02:34<00:36,  2.37it/s]


 84%|████████▍ | 444/530 [02:34<00:32,  2.67it/s]


 84%|████████▍ | 445/530 [02:34<00:28,  2.96it/s]


 84%|████████▍ | 446/530 [02:35<00:23,  3.56it/s]


 84%|████████▍ | 447/530 [02:35<00:21,  3.82it/s]


 85%|████████▍ | 448/530 [02:36<00:36,  2.24it/s]


 85%|████████▍ | 450/530 [02:36<00:22,  3.54it/s]


 85%|████████▌ | 451/530 [02:37<00:35,  2.25it/s]


 85%|████████▌ | 452/530 [02:37<00:33,  2.33it/s]


 85%|████████▌ | 453/530 [02:37<00:27,  2.84it/s]

 86%|████████▌ | 455/530 [02:38<00:19,  3.78it/s]


 86%|████████▌ | 456/530 [02:38<00:28,  2.59it/s]


 86%|████████▌ | 457/530 [02:39<00:22,  3.18it/s]


 87%|████████▋ | 459/530 [02:40<00:28,  2.49it/s]


 87%|████████▋ | 460/530 [02:40<00:27,  2.50it/s]


 87%|████████▋ | 463/530 [02:40<00:18,  3.68it/s]


 88%|████████▊ | 464/530 [02:41<00:23,  2.85it/s]


 88%|████████▊ | 466/530 [02:42<00:19,  3.35it/s]


 88%|████████▊ | 467/530 [02:42<00:24,  2.54it/s]


 88%|████████▊ | 468/530 [02:43<00:24,  2.50it/s]


 89%|████████▉ | 471/530 [02:43<00:18,  3.25it/s]


 89%|████████▉ | 472/530 [02:44<00:21,  2.68it/s]


 89%|████████▉ | 473/530 [02:44<00:18,  3.10it/s]


 89%|████████▉ | 474/530 [02:44<00:17,  3.26it/s]


 90%|████████▉ | 475/530 [02:45<00:20,  2.66it/s]


 90%|████████▉ | 476/530 [02:45<00:20,  2.64it/s]


 90%|█████████ | 478/530 [02:46<00:13,  3.91it/s]


 90%|█████████ | 479/530 [02:46<00:16,  3.04it/s]


 91%|█████████ | 480/530 [02:47<00:20,  2.40it/s]


 91%|█████████ | 481/530 [02:47<00:17,  2.73it/s]


 91%|█████████ | 482/530 [02:47<00:14,  3.31it/s]


 91%|█████████ | 483/530 [02:48<00:17,  2.64it/s]


 91%|█████████▏| 484/530 [02:48<00:18,  2.51it/s]


 92%|█████████▏| 486/530 [02:48<00:11,  3.67it/s]


 92%|█████████▏| 487/530 [02:49<00:16,  2.59it/s]


 92%|█████████▏| 488/530 [02:49<00:14,  2.87it/s]


 92%|█████████▏| 489/530 [02:50<00:17,  2.29it/s]


 93%|█████████▎| 491/530 [02:50<00:13,  2.95it/s]


 93%|█████████▎| 492/530 [02:51<00:12,  3.07it/s]


 93%|█████████▎| 494/530 [02:51<00:09,  3.71it/s]


 93%|█████████▎| 495/530 [02:52<00:12,  2.82it/s]


 94%|█████████▎| 496/530 [02:52<00:11,  3.01it/s]


 94%|█████████▍| 497/530 [02:53<00:15,  2.20it/s]


 94%|█████████▍| 498/530 [02:53<00:11,  2.74it/s]


 94%|█████████▍| 499/530 [02:53<00:10,  2.91it/s]


 94%|█████████▍| 500/530 [02:53<00:09,  3.21it/s]


 95%|█████████▍| 502/530 [02:54<00:08,  3.41it/s]


 95%|█████████▍| 503/530 [02:55<00:09,  2.81it/s]


 95%|█████████▌| 504/530 [02:55<00:08,  3.22it/s]


 95%|█████████▌| 505/530 [02:56<00:11,  2.26it/s]


 95%|█████████▌| 506/530 [02:56<00:08,  2.83it/s]


 96%|█████████▌| 507/530 [02:56<00:08,  2.72it/s]


 96%|█████████▌| 509/530 [02:56<00:05,  3.83it/s]


 96%|█████████▌| 510/530 [02:57<00:05,  3.64it/s]


 96%|█████████▋| 511/530 [02:57<00:06,  2.85it/s]


 97%|█████████▋| 512/530 [02:57<00:05,  3.11it/s]


 97%|█████████▋| 513/530 [02:58<00:07,  2.27it/s]


 97%|█████████▋| 514/530 [02:58<00:05,  2.88it/s]


 97%|█████████▋| 515/530 [02:59<00:05,  2.59it/s]


 97%|█████████▋| 516/530 [02:59<00:05,  2.75it/s]


 98%|█████████▊| 517/530 [02:59<00:04,  2.97it/s]


 98%|█████████▊| 519/530 [03:00<00:03,  3.43it/s]


 98%|█████████▊| 520/530 [03:01<00:03,  2.54it/s]


 98%|█████████▊| 521/530 [03:01<00:03,  2.54it/s]


 99%|█████████▊| 523/530 [03:02<00:02,  2.45it/s]


 99%|█████████▉| 524/530 [03:02<00:02,  2.85it/s]


 99%|█████████▉| 525/530 [03:02<00:01,  2.86it/s]


 99%|█████████▉| 526/530 [03:03<00:01,  3.36it/s]


 99%|█████████▉| 527/530 [03:03<00:00,  4.09it/s]


100%|█████████▉| 528/530 [03:03<00:00,  3.33it/s]


100%|██████████| 530/530 [03:03<00:00,  2.88it/s]
Families:  67%|██████▋   | 2/3 [03:30<01:59, 119.03s/it]


Multiplets | family 3:   0%|          | 0/21 [00:00<?, ?it/s]



  0%|          | 0/21 [00:00<?, ?it/s]



  5%|▍         | 1/21 [00:01<00:36,  1.82s/it]



 38%|███▊      | 8/21 [00:01<00:02,  5.44it/s]



 52%|█████▏    | 11/21 [00:03<00:03,  3.09it/s]



 71%|███████▏  | 15/21 [00:03<00:01,  4.90it/s]



 86%|████████▌ | 18/21 [00:05<00:00,  3.74it/s]



100%|██████████| 21/21 [00:05<00:00,  4.07it/s]
Families: 100%|██████████| 3/3 [03:35<00:00, 71.80s/it]

Runtime: 215.405191 s

Multiplets | family 3:   0%|          | 0/21 [00:05<?, ?it/s]



Multiplets | family 5:   0%|          | 0/331 [00:00<?, ?it/s]



  0%|          | 0/331 [00:00<?, ?it/s]



  0%|          | 1/331 [00:04<22:11,  4.04s/it]



  2%|▏         | 6/331 [00:04<02:47,  1.94it/s]



  3%|▎         | 9/331 [00:08<04:33,  1.18it/s]



  3%|▎         | 11/331 [00:08<03:22,  1.58it/s]



  4%|▍         | 13/331 [00:08<02:31,  2.10it/s]



  5%|▍         | 15/331 [00:08<01:53,  2.79it/s]



  5%|▌         | 17/331 [00:12<04:20,  1.21it/s]



  5%|▌         | 18/331 [00:12<03:45,  1.39it/s]



  6%|▋         | 21/331 [00:12<02:19,  2.23it/s]



  7%|▋         | 23/331 [00:13<01:46,  2.90it/s]



  7%|▋         | 24/331 [00:13<01:35,  3.21it/s]



  8%|▊         | 25/331 [00:16<04:44,  1.08it/s]



  8%|▊         | 26/331 [00:16<03:51,  1.32it/s]



  8%|▊         | 28/331 [00:17<02:39,  1.90it/s]



  9%|▉         | 29/331 [00:17<02:12,  2.29it/s]



  9%|▉         | 30/331 [00:17<01:56,  2.59it/s]



 10%|▉         | 32/331 [00:17<01:35,  3.14it/s]



 10%|▉         | 33/331 [00:20<04:34,  1.08it/s]



 10%|█         | 34/331 [00:21<03:35,  1.38it/s]



 11%|█         | 35/331 [00:21<02:50,  1.74it/s]



 11%|█         | 36/331 [00:21<02:22,  2.07it/s]



 11%|█▏        | 38/331 [00:22<01:54,  2.56it/s]



 12%|█▏        | 40/331 [00:22<01:36,  3.02it/s]



 12%|█▏        | 41/331 [00:25<04:22,  1.10it/s]



 13%|█▎        | 43/331 [00:26<03:14,  1.48it/s]



 13%|█▎        | 44/331 [00:26<02:49,  1.70it/s]



 14%|█▍        | 46/331 [00:26<02:14,  2.12it/s]



 14%|█▍        | 47/331 [00:27<01:57,  2.43it/s]



 15%|█▍        | 48/331 [00:27<02:02,  2.31it/s]



 15%|█▍        | 49/331 [00:29<03:55,  1.20it/s]



 15%|█▌        | 50/331 [00:30<03:25,  1.37it/s]



 15%|█▌        | 51/331 [00:30<03:03,  1.53it/s]



 16%|█▌        | 53/331 [00:30<01:51,  2.49it/s]



 16%|█▋        | 54/331 [00:31<01:58,  2.34it/s]



 17%|█▋        | 55/331 [00:31<01:39,  2.76it/s]



 17%|█▋        | 56/331 [00:32<02:08,  2.14it/s]



 17%|█▋        | 57/331 [00:33<03:32,  1.29it/s]



 18%|█▊        | 58/331 [00:34<03:25,  1.33it/s]



 18%|█▊        | 59/331 [00:34<02:55,  1.55it/s]



 18%|█▊        | 61/331 [00:35<01:50,  2.43it/s]



 19%|█▊        | 62/331 [00:35<01:50,  2.43it/s]



 19%|█▉        | 64/331 [00:36<02:15,  1.98it/s]



 20%|█▉        | 65/331 [00:38<03:02,  1.46it/s]



 20%|█▉        | 66/331 [00:38<03:08,  1.40it/s]



 20%|██        | 67/331 [00:39<02:36,  1.69it/s]



 21%|██        | 68/331 [00:39<02:04,  2.12it/s]



 21%|██        | 69/331 [00:39<02:08,  2.04it/s]



 21%|██▏       | 71/331 [00:40<01:34,  2.74it/s]



 22%|██▏       | 72/331 [00:41<02:36,  1.66it/s]



 22%|██▏       | 73/331 [00:42<02:50,  1.51it/s]



 22%|██▏       | 74/331 [00:43<02:59,  1.43it/s]



 23%|██▎       | 75/331 [00:43<02:34,  1.66it/s]



 23%|██▎       | 76/331 [00:43<02:02,  2.08it/s]



 23%|██▎       | 77/331 [00:44<02:18,  1.83it/s]



 24%|██▎       | 78/331 [00:44<02:05,  2.01it/s]



 24%|██▍       | 79/331 [00:45<01:53,  2.21it/s]



 24%|██▍       | 80/331 [00:46<02:31,  1.65it/s]



 24%|██▍       | 81/331 [00:46<02:41,  1.55it/s]



 25%|██▍       | 82/331 [00:47<02:48,  1.48it/s]



 25%|██▌       | 83/331 [00:48<02:36,  1.58it/s]



 25%|██▌       | 84/331 [00:48<02:11,  1.87it/s]



 26%|██▌       | 85/331 [00:48<02:01,  2.02it/s]



 26%|██▌       | 86/331 [00:49<01:41,  2.42it/s]



 26%|██▋       | 87/331 [00:49<01:38,  2.49it/s]



 27%|██▋       | 88/331 [00:50<02:19,  1.74it/s]



 27%|██▋       | 89/331 [00:50<02:14,  1.79it/s]



 27%|██▋       | 90/331 [00:51<02:33,  1.56it/s]



 27%|██▋       | 91/331 [00:52<02:36,  1.53it/s]



 28%|██▊       | 92/331 [00:52<02:17,  1.73it/s]



 28%|██▊       | 93/331 [00:53<01:58,  2.00it/s]



 28%|██▊       | 94/331 [00:53<01:39,  2.38it/s]



 29%|██▊       | 95/331 [00:53<01:50,  2.14it/s]



 29%|██▉       | 96/331 [00:55<02:41,  1.45it/s]



 29%|██▉       | 97/331 [00:55<02:08,  1.82it/s]



 30%|██▉       | 98/331 [00:55<02:11,  1.77it/s]



 30%|██▉       | 99/331 [00:56<02:23,  1.62it/s]



 30%|███       | 100/331 [00:57<02:02,  1.89it/s]



 31%|███       | 101/331 [00:57<02:08,  1.79it/s]



 31%|███       | 102/331 [00:57<01:44,  2.20it/s]



 31%|███       | 103/331 [00:58<01:41,  2.24it/s]



 31%|███▏      | 104/331 [00:59<02:39,  1.42it/s]



 32%|███▏      | 105/331 [00:59<02:13,  1.70it/s]



 32%|███▏      | 106/331 [01:00<01:50,  2.04it/s]



 32%|███▏      | 107/331 [01:01<02:27,  1.52it/s]



 33%|███▎      | 109/331 [01:02<02:06,  1.76it/s]



 33%|███▎      | 110/331 [01:02<01:45,  2.10it/s]



 34%|███▎      | 111/331 [01:02<01:47,  2.04it/s]



 34%|███▍      | 112/331 [01:03<02:13,  1.64it/s]



 34%|███▍      | 113/331 [01:04<02:25,  1.49it/s]



 34%|███▍      | 114/331 [01:04<02:00,  1.81it/s]



 35%|███▍      | 115/331 [01:05<01:50,  1.95it/s]



 35%|███▌      | 116/331 [01:06<02:11,  1.64it/s]



 35%|███▌      | 117/331 [01:06<01:47,  2.00it/s]



 36%|███▌      | 118/331 [01:07<02:08,  1.66it/s]



 36%|███▋      | 120/331 [01:08<02:08,  1.65it/s]



 37%|███▋      | 121/331 [01:09<02:03,  1.71it/s]



 37%|███▋      | 122/331 [01:09<02:12,  1.58it/s]



 37%|███▋      | 123/331 [01:09<01:42,  2.02it/s]



 37%|███▋      | 124/331 [01:10<01:49,  1.89it/s]



 38%|███▊      | 125/331 [01:11<01:53,  1.82it/s]



 38%|███▊      | 126/331 [01:11<01:57,  1.74it/s]



 38%|███▊      | 127/331 [01:11<01:30,  2.25it/s]



 39%|███▊      | 128/331 [01:12<02:01,  1.68it/s]



 39%|███▉      | 129/331 [01:13<02:09,  1.56it/s]



 39%|███▉      | 130/331 [01:14<02:05,  1.61it/s]



 40%|███▉      | 131/331 [01:14<02:06,  1.58it/s]



 40%|████      | 133/331 [01:15<01:54,  1.73it/s]



 40%|████      | 134/331 [01:16<01:49,  1.80it/s]



 41%|████      | 135/331 [01:16<01:33,  2.09it/s]



 41%|████      | 136/331 [01:17<01:44,  1.87it/s]



 41%|████▏     | 137/331 [01:17<01:52,  1.72it/s]



 42%|████▏     | 138/331 [01:18<01:52,  1.71it/s]



 42%|████▏     | 139/331 [01:19<01:57,  1.63it/s]



 42%|████▏     | 140/331 [01:19<01:31,  2.08it/s]



 43%|████▎     | 141/331 [01:20<02:01,  1.57it/s]



 43%|████▎     | 142/331 [01:20<01:53,  1.67it/s]



 43%|████▎     | 143/331 [01:21<01:26,  2.16it/s]



 44%|████▎     | 144/331 [01:21<01:26,  2.17it/s]



 44%|████▍     | 145/331 [01:22<01:53,  1.63it/s]



 44%|████▍     | 146/331 [01:23<02:09,  1.43it/s]



 44%|████▍     | 147/331 [01:23<01:43,  1.78it/s]



 45%|████▍     | 148/331 [01:23<01:22,  2.22it/s]



 45%|████▌     | 149/331 [01:25<02:22,  1.28it/s]



 46%|████▌     | 151/331 [01:25<01:38,  1.82it/s]

 46%|████▌     | 153/331 [01:27<01:44,  1.71it/s]



 47%|████▋     | 154/331 [01:28<02:04,  1.42it/s]



 47%|████▋     | 155/331 [01:28<01:42,  1.71it/s]



 47%|████▋     | 157/331 [01:29<01:44,  1.66it/s]



 48%|████▊     | 159/331 [01:30<01:31,  1.89it/s]



 48%|████▊     | 160/331 [01:31<01:27,  1.94it/s]



 49%|████▊     | 161/331 [01:32<01:50,  1.54it/s]



 49%|████▉     | 162/331 [01:32<01:45,  1.60it/s]



 49%|████▉     | 163/331 [01:33<01:39,  1.69it/s]



 50%|████▉     | 165/331 [01:34<01:34,  1.75it/s]



 50%|█████     | 166/331 [01:34<01:25,  1.93it/s]



 50%|█████     | 167/331 [01:35<01:21,  2.00it/s]



 51%|█████     | 168/331 [01:35<01:17,  2.11it/s]



 51%|█████     | 169/331 [01:36<02:00,  1.34it/s]



 52%|█████▏    | 171/331 [01:37<01:32,  1.73it/s]



 52%|█████▏    | 173/331 [01:38<01:18,  2.02it/s]



 53%|█████▎    | 174/331 [01:38<01:16,  2.05it/s]



 53%|█████▎    | 175/331 [01:39<01:07,  2.30it/s]



 53%|█████▎    | 176/331 [01:39<01:16,  2.02it/s]



 53%|█████▎    | 177/331 [01:41<01:52,  1.37it/s]



 54%|█████▍    | 178/331 [01:41<01:40,  1.52it/s]



 54%|█████▍    | 179/331 [01:42<01:25,  1.78it/s]



 54%|█████▍    | 180/331 [01:42<01:13,  2.07it/s]



 55%|█████▍    | 181/331 [01:42<01:12,  2.06it/s]



 55%|█████▍    | 182/331 [01:43<01:18,  1.89it/s]



 55%|█████▌    | 183/331 [01:43<01:07,  2.21it/s]



 56%|█████▌    | 184/331 [01:44<01:39,  1.47it/s]



 56%|█████▌    | 185/331 [01:45<01:35,  1.53it/s]



 56%|█████▌    | 186/331 [01:46<01:52,  1.29it/s]



 57%|█████▋    | 188/331 [01:47<01:23,  1.70it/s]



 57%|█████▋    | 190/331 [01:47<01:00,  2.33it/s]



 58%|█████▊    | 191/331 [01:48<01:21,  1.72it/s]



 58%|█████▊    | 192/331 [01:49<01:33,  1.49it/s]



 58%|█████▊    | 193/331 [01:50<01:31,  1.51it/s]



 59%|█████▊    | 194/331 [01:50<01:16,  1.79it/s]



 59%|█████▉    | 195/331 [01:51<01:24,  1.61it/s]



 59%|█████▉    | 196/331 [01:51<01:11,  1.90it/s]



 60%|█████▉    | 197/331 [01:51<00:59,  2.26it/s]



 60%|██████    | 199/331 [01:53<01:09,  1.91it/s]



 60%|██████    | 200/331 [01:53<01:16,  1.71it/s]



 61%|██████    | 201/331 [01:54<01:15,  1.73it/s]



 61%|██████    | 202/331 [01:54<01:09,  1.86it/s]



 61%|██████▏   | 203/331 [01:55<01:09,  1.85it/s]



 62%|██████▏   | 204/331 [01:55<01:02,  2.04it/s]



 62%|██████▏   | 205/331 [01:56<00:53,  2.37it/s]



 62%|██████▏   | 206/331 [01:56<00:41,  3.04it/s]



 63%|██████▎   | 207/331 [01:57<01:13,  1.70it/s]



 63%|██████▎   | 208/331 [01:58<01:23,  1.47it/s]



 63%|██████▎   | 209/331 [01:58<01:14,  1.64it/s]



 63%|██████▎   | 210/331 [01:59<01:33,  1.29it/s]



 64%|██████▍   | 212/331 [02:00<01:04,  1.85it/s]



 64%|██████▍   | 213/331 [02:00<00:53,  2.19it/s]



 65%|██████▍   | 214/331 [02:00<00:46,  2.53it/s]



 65%|██████▍   | 215/331 [02:02<01:17,  1.49it/s]



 65%|██████▌   | 216/331 [02:02<01:07,  1.70it/s]



 66%|██████▌   | 217/331 [02:03<01:14,  1.52it/s]



 66%|██████▌   | 218/331 [02:04<01:14,  1.51it/s]



 66%|██████▌   | 219/331 [02:04<01:02,  1.80it/s]



 66%|██████▋   | 220/331 [02:04<00:55,  2.00it/s]



 67%|██████▋   | 221/331 [02:05<00:49,  2.24it/s]



 67%|██████▋   | 222/331 [02:05<00:42,  2.59it/s]



 67%|██████▋   | 223/331 [02:06<01:03,  1.70it/s]



 68%|██████▊   | 224/331 [02:07<01:01,  1.73it/s]



 68%|██████▊   | 225/331 [02:08<01:14,  1.42it/s]



 68%|██████▊   | 226/331 [02:08<01:05,  1.60it/s]



 69%|██████▊   | 227/331 [02:08<00:51,  2.03it/s]



 69%|██████▉   | 228/331 [02:09<00:50,  2.05it/s]



 69%|██████▉   | 229/331 [02:09<00:45,  2.26it/s]



 69%|██████▉   | 230/331 [02:09<00:44,  2.26it/s]



 70%|██████▉   | 231/331 [02:10<01:02,  1.60it/s]



 70%|███████   | 232/331 [02:11<00:51,  1.92it/s]



 70%|███████   | 233/331 [02:12<01:06,  1.48it/s]



 71%|███████   | 234/331 [02:13<01:06,  1.45it/s]



 71%|███████   | 235/331 [02:13<00:55,  1.72it/s]



 71%|███████▏  | 236/331 [02:14<00:57,  1.65it/s]



 72%|███████▏  | 238/331 [02:14<00:40,  2.31it/s]



 72%|███████▏  | 239/331 [02:15<00:55,  1.66it/s]



 73%|███████▎  | 240/331 [02:16<00:51,  1.78it/s]



 73%|███████▎  | 241/331 [02:17<01:06,  1.35it/s]



 73%|███████▎  | 242/331 [02:17<00:50,  1.78it/s]



 73%|███████▎  | 243/331 [02:17<00:41,  2.11it/s]



 74%|███████▎  | 244/331 [02:18<00:45,  1.93it/s]



 74%|███████▍  | 245/331 [02:18<00:43,  2.00it/s]



 74%|███████▍  | 246/331 [02:19<00:39,  2.13it/s]



 75%|███████▍  | 247/331 [02:19<00:45,  1.84it/s]



 75%|███████▍  | 248/331 [02:20<00:44,  1.86it/s]



 75%|███████▌  | 249/331 [02:21<00:59,  1.38it/s]



 76%|███████▌  | 250/331 [02:22<00:53,  1.50it/s]



 76%|███████▌  | 251/331 [02:22<00:45,  1.75it/s]



 76%|███████▌  | 252/331 [02:22<00:45,  1.73it/s]



 77%|███████▋  | 254/331 [02:23<00:33,  2.27it/s]



 77%|███████▋  | 255/331 [02:24<00:34,  2.18it/s]



 77%|███████▋  | 256/331 [02:24<00:34,  2.17it/s]



 78%|███████▊  | 257/331 [02:26<00:59,  1.23it/s]



 78%|███████▊  | 258/331 [02:26<00:49,  1.46it/s]



 79%|███████▊  | 260/331 [02:27<00:39,  1.79it/s]



 79%|███████▉  | 262/331 [02:27<00:29,  2.36it/s]



 79%|███████▉  | 263/331 [02:28<00:31,  2.15it/s]



 80%|███████▉  | 264/331 [02:29<00:33,  2.01it/s]



 80%|████████  | 265/331 [02:30<00:50,  1.31it/s]



 80%|████████  | 266/331 [02:30<00:41,  1.58it/s]



 81%|████████  | 267/331 [02:31<00:37,  1.72it/s]



 81%|████████  | 268/331 [02:32<00:42,  1.48it/s]



 82%|████████▏ | 270/331 [02:32<00:26,  2.29it/s]



 82%|████████▏ | 271/331 [02:33<00:28,  2.07it/s]



 82%|████████▏ | 272/331 [02:33<00:33,  1.76it/s]



 82%|████████▏ | 273/331 [02:35<00:43,  1.35it/s]



 83%|████████▎ | 275/331 [02:35<00:31,  1.76it/s]



 83%|████████▎ | 276/331 [02:36<00:30,  1.78it/s]



 84%|████████▎ | 277/331 [02:36<00:30,  1.77it/s]



 84%|████████▍ | 278/331 [02:37<00:25,  2.08it/s]



 84%|████████▍ | 279/331 [02:37<00:24,  2.10it/s]



 85%|████████▍ | 280/331 [02:38<00:29,  1.75it/s]



 85%|████████▍ | 281/331 [02:39<00:34,  1.46it/s]



 85%|████████▌ | 282/331 [02:39<00:27,  1.79it/s]



 85%|████████▌ | 283/331 [02:40<00:32,  1.49it/s]



 86%|████████▌ | 284/331 [02:40<00:23,  1.96it/s]



 86%|████████▌ | 285/331 [02:41<00:28,  1.62it/s]



 86%|████████▋ | 286/331 [02:41<00:21,  2.13it/s]



 87%|████████▋ | 287/331 [02:42<00:21,  2.08it/s]



 87%|████████▋ | 288/331 [02:43<00:29,  1.45it/s]



 87%|████████▋ | 289/331 [02:43<00:25,  1.63it/s]



 88%|████████▊ | 290/331 [02:44<00:20,  2.00it/s]



 88%|████████▊ | 291/331 [02:44<00:23,  1.71it/s]



 89%|████████▊ | 293/331 [02:45<00:21,  1.77it/s]



 89%|████████▉ | 295/331 [02:46<00:16,  2.23it/s]

 89%|████████▉ | 296/331 [02:47<00:23,  1.49it/s]



 90%|████████▉ | 297/331 [02:48<00:21,  1.59it/s]



 90%|█████████ | 298/331 [02:48<00:17,  1.88it/s]



 90%|█████████ | 299/331 [02:49<00:18,  1.75it/s]



 91%|█████████ | 300/331 [02:49<00:14,  2.18it/s]



 91%|█████████ | 301/331 [02:50<00:19,  1.55it/s]



 91%|█████████ | 302/331 [02:51<00:17,  1.63it/s]



 92%|█████████▏| 303/331 [02:51<00:14,  1.87it/s]



 92%|█████████▏| 304/331 [02:52<00:19,  1.41it/s]



 92%|█████████▏| 305/331 [02:53<00:16,  1.58it/s]



 92%|█████████▏| 306/331 [02:53<00:11,  2.11it/s]



 93%|█████████▎| 307/331 [02:54<00:13,  1.77it/s]



 93%|█████████▎| 308/331 [02:54<00:11,  2.00it/s]



 93%|█████████▎| 309/331 [02:55<00:14,  1.55it/s]



 94%|█████████▎| 310/331 [02:55<00:12,  1.66it/s]



 94%|█████████▍| 311/331 [02:56<00:09,  2.11it/s]



 94%|█████████▍| 312/331 [02:57<00:12,  1.54it/s]



 95%|█████████▍| 313/331 [02:57<00:10,  1.74it/s]



 95%|█████████▍| 314/331 [02:57<00:07,  2.28it/s]



 95%|█████████▌| 315/331 [02:58<00:08,  1.86it/s]



 95%|█████████▌| 316/331 [02:58<00:06,  2.39it/s]



 96%|█████████▌| 317/331 [02:59<00:08,  1.57it/s]



 96%|█████████▌| 318/331 [03:00<00:07,  1.71it/s]



 97%|█████████▋| 320/331 [03:01<00:06,  1.66it/s]



 97%|█████████▋| 321/331 [03:01<00:05,  1.81it/s]



 97%|█████████▋| 322/331 [03:01<00:04,  2.22it/s]



 98%|█████████▊| 323/331 [03:02<00:03,  2.03it/s]



 98%|█████████▊| 324/331 [03:02<00:03,  2.30it/s]



 98%|█████████▊| 325/331 [03:03<00:03,  1.92it/s]



 98%|█████████▊| 326/331 [03:04<00:02,  1.86it/s]



 99%|█████████▉| 327/331 [03:04<00:02,  1.78it/s]



 99%|█████████▉| 328/331 [03:05<00:02,  1.43it/s]



 99%|█████████▉| 329/331 [03:06<00:01,  1.78it/s]



100%|█████████▉| 330/331 [03:06<00:00,  2.24it/s]



100%|██████████| 331/331 [03:06<00:00,  1.77it/s]
Families:  33%|███▎      | 1/3 [03:06<06:13, 186.66s/it]



Multiplets | family 4:   0%|          | 0/471 [00:00<?, ?it/s]




  0%|          | 0/471 [00:00<?, ?it/s]




  0%|          | 1/471 [00:02<23:12,  2.96s/it]




  1%|          | 3/471 [00:03<06:20,  1.23it/s]




  1%|▏         | 7/471 [00:03<02:09,  3.60it/s]




  2%|▏         | 10/471 [00:06<04:33,  1.68it/s]




  3%|▎         | 14/471 [00:06<02:45,  2.75it/s]




  3%|▎         | 16/471 [00:06<02:15,  3.35it/s]




  4%|▍         | 18/471 [00:09<04:10,  1.81it/s]




  5%|▍         | 22/471 [00:09<02:42,  2.77it/s]




  5%|▌         | 24/471 [00:09<02:17,  3.26it/s]




  5%|▌         | 25/471 [00:12<04:26,  1.68it/s]




  6%|▌         | 26/471 [00:12<03:49,  1.94it/s]




  6%|▌         | 28/471 [00:12<03:00,  2.45it/s]




  7%|▋         | 31/471 [00:13<02:02,  3.58it/s]




  7%|▋         | 32/471 [00:13<01:59,  3.68it/s]




  7%|▋         | 33/471 [00:15<04:45,  1.54it/s]




  7%|▋         | 34/471 [00:15<04:09,  1.75it/s]




  7%|▋         | 35/471 [00:16<03:29,  2.08it/s]




  8%|▊         | 38/471 [00:16<02:15,  3.20it/s]




  8%|▊         | 39/471 [00:16<02:29,  2.90it/s]




  9%|▊         | 41/471 [00:18<03:45,  1.91it/s]




  9%|▉         | 42/471 [00:19<03:35,  1.99it/s]




  9%|▉         | 43/471 [00:19<02:57,  2.41it/s]




  9%|▉         | 44/471 [00:19<02:28,  2.87it/s]




 10%|▉         | 46/471 [00:19<02:18,  3.07it/s]




 10%|▉         | 47/471 [00:20<02:11,  3.22it/s]




 10%|█         | 48/471 [00:20<01:50,  3.84it/s]




 10%|█         | 49/471 [00:21<04:00,  1.75it/s]




 11%|█         | 50/471 [00:22<03:56,  1.78it/s]




 11%|█         | 51/471 [00:22<03:13,  2.17it/s]




 11%|█         | 52/471 [00:22<02:36,  2.68it/s]




 11%|█▏        | 53/471 [00:22<02:11,  3.18it/s]




 11%|█▏        | 54/471 [00:23<02:23,  2.91it/s]




 12%|█▏        | 55/471 [00:23<01:55,  3.59it/s]




 12%|█▏        | 56/471 [00:23<01:57,  3.54it/s]




 12%|█▏        | 57/471 [00:25<04:17,  1.61it/s]




 12%|█▏        | 58/471 [00:25<03:42,  1.85it/s]




 13%|█▎        | 59/471 [00:25<03:15,  2.11it/s]




 13%|█▎        | 60/471 [00:25<02:35,  2.64it/s]




 13%|█▎        | 61/471 [00:26<02:24,  2.84it/s]




 13%|█▎        | 62/471 [00:26<02:08,  3.18it/s]




 13%|█▎        | 63/471 [00:26<01:59,  3.40it/s]




 14%|█▎        | 64/471 [00:27<02:05,  3.24it/s]




 14%|█▍        | 65/471 [00:28<04:01,  1.68it/s]




 14%|█▍        | 66/471 [00:28<03:29,  1.93it/s]




 14%|█▍        | 67/471 [00:28<03:10,  2.12it/s]




 14%|█▍        | 68/471 [00:29<02:36,  2.58it/s]




 15%|█▍        | 69/471 [00:29<02:41,  2.49it/s]




 15%|█▌        | 71/471 [00:30<02:08,  3.11it/s]




 15%|█▌        | 72/471 [00:30<02:07,  3.13it/s]




 15%|█▌        | 73/471 [00:31<03:20,  1.99it/s]




 16%|█▌        | 74/471 [00:31<03:02,  2.18it/s]




 16%|█▌        | 75/471 [00:32<03:12,  2.05it/s]




 16%|█▌        | 76/471 [00:32<02:29,  2.63it/s]




 16%|█▋        | 77/471 [00:32<02:23,  2.75it/s]




 17%|█▋        | 79/471 [00:33<02:25,  2.70it/s]




 17%|█▋        | 80/471 [00:33<02:14,  2.91it/s]




 17%|█▋        | 81/471 [00:34<02:57,  2.20it/s]




 17%|█▋        | 82/471 [00:35<03:17,  1.97it/s]




 18%|█▊        | 83/471 [00:35<02:52,  2.25it/s]




 18%|█▊        | 84/471 [00:35<02:25,  2.66it/s]




 18%|█▊        | 85/471 [00:36<02:28,  2.60it/s]




 18%|█▊        | 87/471 [00:36<02:07,  3.01it/s]




 19%|█▊        | 88/471 [00:36<02:10,  2.92it/s]




 19%|█▉        | 89/471 [00:37<02:45,  2.30it/s]




 19%|█▉        | 90/471 [00:38<03:19,  1.91it/s]




 19%|█▉        | 91/471 [00:38<02:45,  2.30it/s]




 20%|█▉        | 92/471 [00:38<02:23,  2.65it/s]




 20%|█▉        | 93/471 [00:39<02:46,  2.27it/s]




 20%|█▉        | 94/471 [00:39<02:20,  2.68it/s]




 20%|██        | 95/471 [00:39<02:08,  2.92it/s]




 20%|██        | 96/471 [00:40<01:44,  3.57it/s]




 21%|██        | 97/471 [00:41<03:22,  1.84it/s]




 21%|██        | 98/471 [00:41<03:41,  1.68it/s]




 21%|██        | 99/471 [00:42<03:40,  1.69it/s]




 21%|██▏       | 101/471 [00:43<02:38,  2.33it/s]




 22%|██▏       | 102/471 [00:43<02:34,  2.39it/s]




 22%|██▏       | 103/471 [00:43<02:16,  2.70it/s]




 22%|██▏       | 104/471 [00:43<01:53,  3.24it/s]




 22%|██▏       | 105/471 [00:44<02:40,  2.29it/s]




 23%|██▎       | 106/471 [00:45<03:00,  2.03it/s]




 23%|██▎       | 107/471 [00:45<03:27,  1.76it/s]




 23%|██▎       | 108/471 [00:46<02:55,  2.06it/s]




 23%|██▎       | 109/471 [00:46<02:43,  2.21it/s]




 23%|██▎       | 110/471 [00:47<02:51,  2.11it/s]

 24%|██▍       | 112/471 [00:47<02:12,  2.71it/s]




 24%|██▍       | 113/471 [00:48<02:34,  2.31it/s]




 24%|██▍       | 115/471 [00:49<03:01,  1.96it/s]




 25%|██▍       | 116/471 [00:49<02:42,  2.18it/s]




 25%|██▌       | 118/471 [00:50<02:14,  2.62it/s]




 25%|██▌       | 119/471 [00:50<02:08,  2.74it/s]




 25%|██▌       | 120/471 [00:50<02:05,  2.80it/s]




 26%|██▌       | 121/471 [00:51<02:45,  2.12it/s]




 26%|██▌       | 123/471 [00:52<03:00,  1.92it/s]




 27%|██▋       | 125/471 [00:53<02:03,  2.80it/s]




 27%|██▋       | 126/471 [00:53<02:14,  2.57it/s]




 27%|██▋       | 127/471 [00:53<02:06,  2.73it/s]




 27%|██▋       | 128/471 [00:54<01:49,  3.14it/s]




 27%|██▋       | 129/471 [00:54<02:20,  2.43it/s]




 28%|██▊       | 130/471 [00:54<01:56,  2.93it/s]




 28%|██▊       | 131/471 [00:56<03:16,  1.73it/s]




 28%|██▊       | 132/471 [00:56<02:39,  2.13it/s]




 28%|██▊       | 134/471 [00:56<02:13,  2.53it/s]




 29%|██▊       | 135/471 [00:57<01:58,  2.83it/s]




 29%|██▉       | 137/471 [00:57<02:07,  2.62it/s]




 30%|██▉       | 139/471 [00:59<02:41,  2.06it/s]




 30%|██▉       | 141/471 [00:59<02:11,  2.50it/s]




 30%|███       | 142/471 [01:00<02:08,  2.56it/s]




 30%|███       | 143/471 [01:00<01:59,  2.74it/s]




 31%|███       | 144/471 [01:00<01:56,  2.80it/s]




 31%|███       | 145/471 [01:01<02:05,  2.60it/s]




 31%|███       | 146/471 [01:01<01:54,  2.84it/s]




 31%|███       | 147/471 [01:02<03:05,  1.74it/s]




 31%|███▏      | 148/471 [01:02<02:22,  2.27it/s]




 32%|███▏      | 149/471 [01:03<02:55,  1.83it/s]




 32%|███▏      | 150/471 [01:03<02:25,  2.20it/s]




 32%|███▏      | 152/471 [01:04<01:50,  2.90it/s]




 32%|███▏      | 153/471 [01:04<01:55,  2.74it/s]




 33%|███▎      | 155/471 [01:05<02:28,  2.13it/s]




 33%|███▎      | 156/471 [01:05<02:05,  2.51it/s]




 33%|███▎      | 157/471 [01:06<02:32,  2.06it/s]




 34%|███▎      | 158/471 [01:06<02:06,  2.47it/s]




 34%|███▍      | 159/471 [01:07<01:46,  2.92it/s]




 34%|███▍      | 160/471 [01:07<01:36,  3.21it/s]




 34%|███▍      | 161/471 [01:07<01:50,  2.79it/s]




 35%|███▍      | 163/471 [01:08<02:24,  2.12it/s]




 35%|███▍      | 164/471 [01:09<02:07,  2.40it/s]




 35%|███▌      | 165/471 [01:09<02:31,  2.02it/s]




 35%|███▌      | 166/471 [01:10<02:22,  2.14it/s]




 36%|███▌      | 168/471 [01:10<01:39,  3.04it/s]




 36%|███▌      | 169/471 [01:10<01:33,  3.23it/s]




 36%|███▌      | 170/471 [01:11<01:24,  3.56it/s]




 36%|███▋      | 171/471 [01:12<02:27,  2.04it/s]




 37%|███▋      | 172/471 [01:12<02:13,  2.23it/s]




 37%|███▋      | 173/471 [01:13<02:52,  1.72it/s]




 37%|███▋      | 174/471 [01:13<02:26,  2.03it/s]




 38%|███▊      | 177/471 [01:14<01:28,  3.30it/s]




 38%|███▊      | 178/471 [01:14<01:24,  3.47it/s]




 38%|███▊      | 179/471 [01:15<02:12,  2.20it/s]




 38%|███▊      | 180/471 [01:15<02:06,  2.30it/s]




 38%|███▊      | 181/471 [01:16<02:44,  1.77it/s]




 39%|███▊      | 182/471 [01:17<02:23,  2.01it/s]




 39%|███▉      | 183/471 [01:17<02:03,  2.33it/s]




 39%|███▉      | 185/471 [01:17<01:54,  2.50it/s]




 40%|███▉      | 187/471 [01:18<02:02,  2.31it/s]




 40%|███▉      | 188/471 [01:19<01:57,  2.42it/s]




 40%|████      | 189/471 [01:20<02:21,  1.99it/s]




 40%|████      | 190/471 [01:20<01:58,  2.36it/s]




 41%|████      | 191/471 [01:20<02:06,  2.21it/s]




 41%|████      | 192/471 [01:20<01:41,  2.74it/s]




 41%|████      | 193/471 [01:21<02:01,  2.29it/s]




 41%|████      | 194/471 [01:21<01:45,  2.63it/s]




 41%|████▏     | 195/471 [01:22<02:14,  2.05it/s]




 42%|████▏     | 197/471 [01:23<02:05,  2.19it/s]




 42%|████▏     | 198/471 [01:23<01:44,  2.60it/s]




 42%|████▏     | 199/471 [01:24<01:52,  2.42it/s]




 42%|████▏     | 200/471 [01:24<01:46,  2.53it/s]




 43%|████▎     | 201/471 [01:24<01:58,  2.28it/s]




 43%|████▎     | 202/471 [01:25<01:43,  2.60it/s]




 43%|████▎     | 203/471 [01:26<02:19,  1.93it/s]




 44%|████▎     | 205/471 [01:26<01:51,  2.38it/s]




 44%|████▎     | 206/471 [01:26<01:34,  2.80it/s]




 44%|████▍     | 207/471 [01:27<01:45,  2.50it/s]




 44%|████▍     | 208/471 [01:27<01:42,  2.57it/s]




 44%|████▍     | 209/471 [01:28<01:41,  2.58it/s]




 45%|████▍     | 210/471 [01:28<01:38,  2.65it/s]




 45%|████▍     | 211/471 [01:29<02:14,  1.93it/s]




 45%|████▌     | 213/471 [01:30<01:58,  2.17it/s]




 45%|████▌     | 214/471 [01:30<01:35,  2.68it/s]




 46%|████▌     | 215/471 [01:30<01:47,  2.38it/s]




 46%|████▌     | 216/471 [01:30<01:32,  2.75it/s]




 46%|████▌     | 217/471 [01:31<01:21,  3.10it/s]




 46%|████▋     | 218/471 [01:31<01:35,  2.65it/s]




 46%|████▋     | 219/471 [01:32<02:09,  1.95it/s]




 47%|████▋     | 220/471 [01:32<01:53,  2.21it/s]




 47%|████▋     | 221/471 [01:33<01:59,  2.09it/s]




 47%|████▋     | 222/471 [01:33<01:46,  2.34it/s]




 47%|████▋     | 223/471 [01:34<02:05,  1.97it/s]




 48%|████▊     | 226/471 [01:35<01:43,  2.37it/s]




 48%|████▊     | 227/471 [01:35<01:48,  2.26it/s]




 48%|████▊     | 228/471 [01:36<01:32,  2.63it/s]




 49%|████▊     | 229/471 [01:36<01:49,  2.21it/s]




 49%|████▉     | 230/471 [01:37<01:47,  2.25it/s]




 49%|████▉     | 231/471 [01:37<01:43,  2.32it/s]




 49%|████▉     | 232/471 [01:37<01:26,  2.75it/s]




 50%|████▉     | 234/471 [01:38<01:34,  2.50it/s]




 50%|████▉     | 235/471 [01:39<01:38,  2.40it/s]




 50%|█████     | 236/471 [01:39<01:32,  2.53it/s]




 50%|█████     | 237/471 [01:40<01:55,  2.02it/s]




 51%|█████     | 238/471 [01:40<01:35,  2.43it/s]




 51%|█████     | 239/471 [01:40<01:40,  2.31it/s]




 51%|█████     | 240/471 [01:41<01:23,  2.78it/s]




 51%|█████     | 241/471 [01:41<01:06,  3.44it/s]




 51%|█████▏    | 242/471 [01:41<01:33,  2.44it/s]




 52%|█████▏    | 243/471 [01:42<01:36,  2.36it/s]




 52%|█████▏    | 244/471 [01:42<01:34,  2.39it/s]




 52%|█████▏    | 245/471 [01:43<01:59,  1.89it/s]




 52%|█████▏    | 247/471 [01:44<01:35,  2.34it/s]




 53%|█████▎    | 249/471 [01:44<01:07,  3.31it/s]




 53%|█████▎    | 250/471 [01:45<01:28,  2.50it/s]




 53%|█████▎    | 251/471 [01:45<01:29,  2.45it/s]




 54%|█████▎    | 252/471 [01:46<01:36,  2.27it/s]




 54%|█████▎    | 253/471 [01:46<01:46,  2.05it/s]

 54%|█████▍    | 255/471 [01:47<01:25,  2.53it/s]




 55%|█████▍    | 257/471 [01:48<01:27,  2.44it/s]




 55%|█████▍    | 258/471 [01:48<01:40,  2.11it/s]




 55%|█████▍    | 259/471 [01:49<01:36,  2.19it/s]




 55%|█████▌    | 261/471 [01:50<01:27,  2.41it/s]




 56%|█████▌    | 262/471 [01:50<01:21,  2.58it/s]




 56%|█████▌    | 263/471 [01:50<01:33,  2.22it/s]




 56%|█████▌    | 264/471 [01:51<01:25,  2.42it/s]




 56%|█████▋    | 265/471 [01:51<01:25,  2.42it/s]




 56%|█████▋    | 266/471 [01:52<01:52,  1.82it/s]




 57%|█████▋    | 268/471 [01:52<01:07,  2.99it/s]




 57%|█████▋    | 269/471 [01:53<01:19,  2.55it/s]




 57%|█████▋    | 270/471 [01:53<01:10,  2.85it/s]




 58%|█████▊    | 271/471 [01:54<01:28,  2.26it/s]




 58%|█████▊    | 272/471 [01:54<01:31,  2.17it/s]




 58%|█████▊    | 273/471 [01:55<01:37,  2.03it/s]




 58%|█████▊    | 274/471 [01:55<01:36,  2.03it/s]




 59%|█████▊    | 276/471 [01:56<01:06,  2.93it/s]




 59%|█████▉    | 277/471 [01:56<01:08,  2.85it/s]




 59%|█████▉    | 278/471 [01:56<01:13,  2.61it/s]




 59%|█████▉    | 279/471 [01:57<01:27,  2.21it/s]




 59%|█████▉    | 280/471 [01:57<01:18,  2.43it/s]




 60%|█████▉    | 281/471 [01:58<01:34,  2.02it/s]




 60%|█████▉    | 282/471 [01:58<01:22,  2.29it/s]




 60%|██████    | 283/471 [01:59<01:08,  2.73it/s]




 60%|██████    | 284/471 [01:59<00:59,  3.12it/s]




 61%|██████    | 285/471 [01:59<01:05,  2.83it/s]




 61%|██████    | 286/471 [02:00<01:18,  2.34it/s]




 61%|██████    | 287/471 [02:00<01:18,  2.35it/s]




 61%|██████    | 288/471 [02:01<01:12,  2.51it/s]




 61%|██████▏   | 289/471 [02:01<01:31,  1.99it/s]




 62%|██████▏   | 291/471 [02:02<01:10,  2.57it/s]




 62%|██████▏   | 293/471 [02:02<01:04,  2.77it/s]




 62%|██████▏   | 294/471 [02:03<01:13,  2.39it/s]




 63%|██████▎   | 295/471 [02:03<01:11,  2.47it/s]




 63%|██████▎   | 296/471 [02:04<01:07,  2.59it/s]




 63%|██████▎   | 297/471 [02:05<01:29,  1.94it/s]




 63%|██████▎   | 299/471 [02:05<01:09,  2.48it/s]




 64%|██████▎   | 300/471 [02:05<00:57,  3.00it/s]




 64%|██████▍   | 301/471 [02:06<01:00,  2.79it/s]




 64%|██████▍   | 302/471 [02:06<01:18,  2.15it/s]




 64%|██████▍   | 303/471 [02:07<01:04,  2.60it/s]




 65%|██████▍   | 304/471 [02:07<01:14,  2.25it/s]




 65%|██████▍   | 305/471 [02:08<01:24,  1.96it/s]




 65%|██████▍   | 306/471 [02:08<01:05,  2.51it/s]




 65%|██████▌   | 307/471 [02:09<01:14,  2.19it/s]




 65%|██████▌   | 308/471 [02:09<00:59,  2.76it/s]




 66%|██████▌   | 309/471 [02:09<00:51,  3.16it/s]




 66%|██████▌   | 310/471 [02:10<01:10,  2.28it/s]




 66%|██████▌   | 311/471 [02:10<01:09,  2.30it/s]




 66%|██████▌   | 312/471 [02:11<01:13,  2.16it/s]




 66%|██████▋   | 313/471 [02:12<01:36,  1.63it/s]




 67%|██████▋   | 315/471 [02:12<01:16,  2.05it/s]




 67%|██████▋   | 317/471 [02:12<00:48,  3.17it/s]




 68%|██████▊   | 318/471 [02:13<01:04,  2.36it/s]




 68%|██████▊   | 319/471 [02:14<01:00,  2.52it/s]




 68%|██████▊   | 320/471 [02:14<01:19,  1.91it/s]




 68%|██████▊   | 321/471 [02:15<01:14,  2.02it/s]




 68%|██████▊   | 322/471 [02:15<01:12,  2.07it/s]




 69%|██████▊   | 323/471 [02:16<01:01,  2.42it/s]




 69%|██████▉   | 325/471 [02:16<00:38,  3.79it/s]




 69%|██████▉   | 326/471 [02:17<01:07,  2.15it/s]




 69%|██████▉   | 327/471 [02:17<01:00,  2.39it/s]




 70%|██████▉   | 328/471 [02:18<01:17,  1.84it/s]




 70%|██████▉   | 329/471 [02:18<01:05,  2.18it/s]




 70%|███████   | 330/471 [02:19<01:03,  2.24it/s]




 70%|███████   | 331/471 [02:19<00:54,  2.55it/s]




 70%|███████   | 332/471 [02:19<00:43,  3.20it/s]




 71%|███████   | 334/471 [02:20<01:01,  2.23it/s]




 71%|███████   | 335/471 [02:20<00:54,  2.51it/s]




 71%|███████▏  | 336/471 [02:21<01:01,  2.20it/s]




 72%|███████▏  | 337/471 [02:22<01:19,  1.69it/s]




 72%|███████▏  | 340/471 [02:22<00:42,  3.10it/s]




 72%|███████▏  | 341/471 [02:23<00:43,  3.02it/s]




 73%|███████▎  | 342/471 [02:24<01:00,  2.14it/s]




 73%|███████▎  | 343/471 [02:24<00:54,  2.34it/s]




 73%|███████▎  | 344/471 [02:24<00:50,  2.51it/s]




 73%|███████▎  | 345/471 [02:25<01:15,  1.66it/s]




 74%|███████▎  | 347/471 [02:25<00:44,  2.76it/s]




 74%|███████▍  | 348/471 [02:26<00:40,  3.02it/s]




 74%|███████▍  | 349/471 [02:26<00:38,  3.19it/s]




 74%|███████▍  | 350/471 [02:27<01:02,  1.93it/s]




 75%|███████▍  | 351/471 [02:27<00:52,  2.28it/s]




 75%|███████▍  | 352/471 [02:28<00:46,  2.57it/s]




 75%|███████▍  | 353/471 [02:29<01:09,  1.71it/s]




 75%|███████▌  | 355/471 [02:29<00:40,  2.83it/s]




 76%|███████▌  | 356/471 [02:29<00:39,  2.93it/s]




 76%|███████▌  | 357/471 [02:29<00:33,  3.42it/s]




 76%|███████▌  | 358/471 [02:30<00:56,  2.02it/s]




 76%|███████▌  | 359/471 [02:30<00:47,  2.37it/s]




 76%|███████▋  | 360/471 [02:31<00:41,  2.66it/s]




 77%|███████▋  | 361/471 [02:32<01:03,  1.74it/s]




 77%|███████▋  | 362/471 [02:32<00:47,  2.28it/s]




 77%|███████▋  | 364/471 [02:32<00:31,  3.38it/s]




 77%|███████▋  | 365/471 [02:32<00:31,  3.36it/s]




 78%|███████▊  | 366/471 [02:33<00:50,  2.09it/s]




 78%|███████▊  | 367/471 [02:34<00:42,  2.43it/s]




 78%|███████▊  | 368/471 [02:34<00:39,  2.64it/s]




 78%|███████▊  | 369/471 [02:35<00:50,  2.00it/s]




 79%|███████▊  | 370/471 [02:35<00:43,  2.31it/s]




 79%|███████▉  | 371/471 [02:35<00:41,  2.40it/s]




 79%|███████▉  | 372/471 [02:36<00:33,  2.93it/s]




 79%|███████▉  | 373/471 [02:36<00:26,  3.64it/s]




 79%|███████▉  | 374/471 [02:37<00:49,  1.96it/s]




 80%|███████▉  | 375/471 [02:37<00:41,  2.31it/s]




 80%|███████▉  | 376/471 [02:37<00:37,  2.51it/s]




 80%|████████  | 377/471 [02:38<00:55,  1.68it/s]




 80%|████████  | 378/471 [02:39<00:42,  2.18it/s]




 81%|████████  | 380/471 [02:39<00:40,  2.26it/s]




 81%|████████  | 381/471 [02:40<00:32,  2.73it/s]




 81%|████████  | 382/471 [02:40<00:40,  2.17it/s]




 82%|████████▏ | 384/471 [02:41<00:29,  2.94it/s]




 82%|████████▏ | 385/471 [02:42<00:41,  2.08it/s]




 82%|████████▏ | 386/471 [02:42<00:39,  2.17it/s]




 82%|████████▏ | 387/471 [02:42<00:32,  2.58it/s]




 82%|████████▏ | 388/471 [02:43<00:39,  2.12it/s]




 83%|████████▎ | 390/471 [02:43<00:31,  2.59it/s]




 83%|████████▎ | 391/471 [02:44<00:31,  2.51it/s]

 83%|████████▎ | 392/471 [02:44<00:28,  2.77it/s]




 83%|████████▎ | 393/471 [02:45<00:40,  1.92it/s]




 84%|████████▎ | 394/471 [02:45<00:35,  2.15it/s]




 84%|████████▍ | 395/471 [02:46<00:42,  1.79it/s]




 84%|████████▍ | 396/471 [02:47<00:38,  1.97it/s]




 84%|████████▍ | 397/471 [02:47<00:31,  2.38it/s]




 85%|████████▍ | 398/471 [02:47<00:24,  3.00it/s]




 85%|████████▍ | 399/471 [02:47<00:20,  3.47it/s]




 85%|████████▍ | 400/471 [02:48<00:34,  2.04it/s]




 85%|████████▌ | 401/471 [02:48<00:34,  2.06it/s]




 85%|████████▌ | 402/471 [02:49<00:29,  2.36it/s]




 86%|████████▌ | 403/471 [02:50<00:40,  1.66it/s]




 86%|████████▌ | 405/471 [02:50<00:23,  2.78it/s]




 86%|████████▌ | 406/471 [02:50<00:21,  3.08it/s]




 86%|████████▋ | 407/471 [02:50<00:19,  3.30it/s]




 87%|████████▋ | 408/471 [02:51<00:31,  2.02it/s]




 87%|████████▋ | 409/471 [02:52<00:27,  2.28it/s]




 87%|████████▋ | 410/471 [02:52<00:25,  2.43it/s]




 87%|████████▋ | 411/471 [02:53<00:35,  1.70it/s]




 88%|████████▊ | 413/471 [02:53<00:20,  2.84it/s]




 88%|████████▊ | 414/471 [02:54<00:23,  2.43it/s]




 88%|████████▊ | 415/471 [02:54<00:21,  2.62it/s]




 88%|████████▊ | 416/471 [02:55<00:25,  2.20it/s]




 89%|████████▊ | 417/471 [02:55<00:21,  2.48it/s]




 89%|████████▊ | 418/471 [02:56<00:24,  2.15it/s]




 89%|████████▉ | 419/471 [02:56<00:28,  1.85it/s]




 89%|████████▉ | 420/471 [02:57<00:21,  2.33it/s]




 89%|████████▉ | 421/471 [02:57<00:17,  2.86it/s]




 90%|████████▉ | 422/471 [02:57<00:17,  2.80it/s]




 90%|████████▉ | 423/471 [02:57<00:17,  2.80it/s]




 90%|█████████ | 424/471 [02:58<00:21,  2.16it/s]




 90%|█████████ | 425/471 [02:58<00:19,  2.37it/s]




 90%|█████████ | 426/471 [02:59<00:20,  2.22it/s]




 91%|█████████ | 427/471 [03:00<00:21,  2.05it/s]




 91%|█████████ | 428/471 [03:00<00:18,  2.38it/s]




 91%|█████████ | 429/471 [03:00<00:15,  2.72it/s]




 91%|█████████▏| 430/471 [03:00<00:13,  3.03it/s]




 92%|█████████▏| 431/471 [03:01<00:15,  2.51it/s]




 92%|█████████▏| 432/471 [03:01<00:16,  2.34it/s]




 92%|█████████▏| 433/471 [03:02<00:14,  2.56it/s]




 92%|█████████▏| 434/471 [03:02<00:15,  2.32it/s]




 92%|█████████▏| 435/471 [03:03<00:18,  1.93it/s]




 93%|█████████▎| 436/471 [03:03<00:14,  2.34it/s]




 93%|█████████▎| 437/471 [03:03<00:12,  2.82it/s]




 93%|█████████▎| 438/471 [03:04<00:10,  3.14it/s]




 93%|█████████▎| 439/471 [03:04<00:14,  2.18it/s]




 93%|█████████▎| 440/471 [03:05<00:12,  2.40it/s]




 94%|█████████▎| 441/471 [03:05<00:11,  2.59it/s]




 94%|█████████▍| 442/471 [03:05<00:12,  2.31it/s]




 94%|█████████▍| 443/471 [03:06<00:14,  1.93it/s]




 94%|█████████▍| 444/471 [03:06<00:10,  2.51it/s]




 94%|█████████▍| 445/471 [03:07<00:09,  2.74it/s]




 95%|█████████▍| 446/471 [03:07<00:10,  2.49it/s]




 95%|█████████▍| 447/471 [03:08<00:13,  1.81it/s]




 95%|█████████▌| 448/471 [03:08<00:09,  2.37it/s]




 96%|█████████▌| 450/471 [03:09<00:08,  2.61it/s]




 96%|█████████▌| 451/471 [03:09<00:08,  2.28it/s]




 96%|█████████▌| 452/471 [03:10<00:09,  2.08it/s]




 96%|█████████▌| 453/471 [03:10<00:07,  2.33it/s]




 96%|█████████▋| 454/471 [03:11<00:08,  2.12it/s]




 97%|█████████▋| 455/471 [03:11<00:06,  2.31it/s]




 97%|█████████▋| 456/471 [03:12<00:05,  2.53it/s]




 97%|█████████▋| 457/471 [03:12<00:04,  2.88it/s]




 97%|█████████▋| 458/471 [03:12<00:04,  2.72it/s]




 97%|█████████▋| 459/471 [03:13<00:04,  2.46it/s]




 98%|█████████▊| 460/471 [03:14<00:05,  1.83it/s]




 98%|█████████▊| 461/471 [03:14<00:04,  2.35it/s]




 98%|█████████▊| 462/471 [03:14<00:03,  2.34it/s]




 98%|█████████▊| 463/471 [03:15<00:03,  2.17it/s]




 99%|█████████▊| 464/471 [03:15<00:02,  2.83it/s]




 99%|█████████▊| 465/471 [03:15<00:02,  2.79it/s]




 99%|█████████▉| 466/471 [03:15<00:01,  2.81it/s]




 99%|█████████▉| 467/471 [03:16<00:01,  2.85it/s]




 99%|█████████▉| 468/471 [03:16<00:01,  2.39it/s]




100%|█████████▉| 469/471 [03:17<00:00,  2.66it/s]




100%|█████████▉| 470/471 [03:17<00:00,  3.34it/s]




100%|██████████| 471/471 [03:17<00:00,  2.38it/s]
Families:  67%|██████▋   | 2/3 [06:24<03:13, 193.08s/it]




Multiplets | family 3:   0%|          | 0/20 [00:00<?, ?it/s]





  0%|          | 0/20 [00:00<?, ?it/s]





  5%|▌         | 1/20 [00:02<00:39,  2.08s/it]





 40%|████      | 8/20 [00:02<00:02,  4.95it/s]





 65%|██████▌   | 13/20 [00:04<00:02,  3.23it/s]





 85%|████████▌ | 17/20 [00:06<00:01,  2.82it/s]





100%|██████████| 20/20 [00:06<00:00,  3.23it/s]
Families: 100%|██████████| 3/3 [06:30<00:00, 130.15s/it]

Runtime: 390.444078 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]





Multiplets | family 5:   0%|          | 0/41 [00:00<?, ?it/s]






  0%|          | 0/41 [00:00<?, ?it/s]






  2%|▏         | 1/41 [00:03<02:08,  3.21s/it]






  7%|▋         | 3/41 [00:03<00:33,  1.12it/s]






Multiplets | family 3:   0%|          | 0/20 [00:09<?, ?it/s]







 22%|██▏       | 9/41 [00:06<00:19,  1.63it/s]






 24%|██▍       | 10/41 [00:06<00:16,  1.85it/s]






 29%|██▉       | 12/41 [00:06<00:10,  2.64it/s]






 34%|███▍      | 14/41 [00:06<00:07,  3.56it/s]






 41%|████▏     | 17/41 [00:09<00:12,  1.98it/s]






 44%|████▍     | 18/41 [00:09<00:10,  2.11it/s]






 49%|████▉     | 20/41 [00:09<00:07,  2.75it/s]






 56%|█████▌    | 23/41 [00:09<00:04,  4.31it/s]






 61%|██████    | 25/41 [00:12<00:07,  2.07it/s]






 63%|██████▎   | 26/41 [00:12<00:06,  2.16it/s]






 66%|██████▌   | 27/41 [00:12<00:05,  2.45it/s]






 73%|███████▎  | 30/41 [00:12<00:02,  4.13it/s]






 80%|████████  | 33/41 [00:15<00:03,  2.24it/s]






 83%|████████▎ | 34/41 [00:15<00:03,  2.17it/s]






 85%|████████▌ | 35/41 [00:15<00:02,  2.29it/s]






 88%|████████▊ | 36/41 [00:16<00:01,  2.57it/s]






 93%|█████████▎| 38/41 [00:16<00:00,  3.48it/s]






100%|██████████| 41/41 [00:17<00:00,  2.30it/s]
Families:  33%|███▎      | 1/3 [00:17<00:35, 17.87s/it]




Multiplets | family 4:   0%|          | 0/474 [00:00<?, ?it/s]






  0%|          | 0/474 [00:00<?, ?it/s]






  0%|          | 1/474 [00:02<20:00,  2.54s/it]






  1%|          | 4/474 [00:02<03:58,  1.97it/s]






  1%|▏         | 6/474 [00:02<02:39,  2.93it/s]






Multiplets | family 4:   0%|          | 0/530 [10:02<?, ?it/s]
Multiplets | family 5:   0%|          | 0/331 [06:53<?, ?it/s]
Multiplets | family 4:   0%|          | 0/471 [03:46<?, ?it/s]
Multiplets | family 5:   0%|          | 0/41 [00:23<?, ?it/s]







  3%|▎         | 12/474 [00:05<02:51,  2.69it/s]






  3%|▎         | 13/474 [00:05<02:37,  2.93it/s]






  3%|▎         | 16/474 [00:05<01:38,  4.63it/s]






  4%|▍         | 18/474 [00:07<03:03,  2.48it/s]






  4%|▍         | 20/474 [00:07<02:29,  3.05it/s]






  4%|▍         | 21/474 [00:08<02:35,  2.92it/s]






  5%|▍         | 23/474 [00:08<01:54,  3.95it/s]






  5%|▌         | 25/474 [00:10<03:27,  2.16it/s]






  5%|▌         | 26/474 [00:10<03:09,  2.36it/s]






  6%|▌         | 29/474 [00:10<02:07,  3.48it/s]






  6%|▋         | 30/474 [00:11<01:56,  3.83it/s]






  7%|▋         | 31/474 [00:11<01:47,  4.13it/s]






  7%|▋         | 33/474 [00:12<03:02,  2.41it/s]






  7%|▋         | 34/474 [00:12<02:56,  2.49it/s]






  7%|▋         | 35/474 [00:13<02:37,  2.79it/s]






  8%|▊         | 38/474 [00:13<01:30,  4.83it/s]






  8%|▊         | 39/474 [00:13<01:34,  4.59it/s]






  9%|▊         | 41/474 [00:15<02:58,  2.42it/s]






  9%|▉         | 42/474 [00:15<03:04,  2.35it/s]






  9%|▉         | 44/474 [00:15<02:05,  3.44it/s]






  9%|▉         | 45/474 [00:15<01:57,  3.65it/s]






 10%|▉         | 47/474 [00:16<01:22,  5.16it/s]






 10%|█         | 49/474 [00:17<02:33,  2.77it/s]






 11%|█         | 50/474 [00:17<02:48,  2.51it/s]






 11%|█         | 52/474 [00:18<01:58,  3.57it/s]






 11%|█         | 53/474 [00:18<01:46,  3.97it/s]






 12%|█▏        | 55/474 [00:18<01:26,  4.87it/s]






 12%|█▏        | 56/474 [00:18<01:23,  5.03it/s]






 12%|█▏        | 57/474 [00:19<02:50,  2.45it/s]






 12%|█▏        | 58/474 [00:20<02:55,  2.37it/s]






 12%|█▏        | 59/474 [00:20<02:31,  2.74it/s]






 13%|█▎        | 60/474 [00:20<02:07,  3.25it/s]






 13%|█▎        | 61/474 [00:20<01:56,  3.56it/s]






 14%|█▎        | 64/474 [00:21<01:18,  5.25it/s]






 14%|█▎        | 65/474 [00:22<02:21,  2.89it/s]






 14%|█▍        | 66/474 [00:22<02:27,  2.77it/s]






 14%|█▍        | 67/474 [00:22<02:18,  2.94it/s]






 14%|█▍        | 68/474 [00:23<02:13,  3.05it/s]






 15%|█▍        | 69/474 [00:23<01:49,  3.70it/s]






 15%|█▍        | 70/474 [00:23<01:33,  4.31it/s]






 15%|█▌        | 72/474 [00:23<01:08,  5.88it/s]






 15%|█▌        | 73/474 [00:24<02:25,  2.75it/s]






 16%|█▌        | 74/474 [00:24<02:30,  2.66it/s]






 16%|█▌        | 75/474 [00:25<02:08,  3.11it/s]






 16%|█▌        | 76/474 [00:25<02:33,  2.60it/s]






 16%|█▌        | 77/474 [00:25<02:02,  3.25it/s]






 16%|█▋        | 78/474 [00:25<01:41,  3.89it/s]






 17%|█▋        | 80/474 [00:26<01:07,  5.80it/s]






 17%|█▋        | 81/474 [00:27<02:39,  2.46it/s]






 17%|█▋        | 82/474 [00:27<02:46,  2.35it/s]






 18%|█▊        | 83/474 [00:27<02:21,  2.76it/s]






 18%|█▊        | 84/474 [00:28<02:20,  2.77it/s]






 18%|█▊        | 86/474 [00:28<01:46,  3.65it/s]






 19%|█▊        | 88/474 [00:28<01:25,  4.51it/s]






 19%|█▉        | 89/474 [00:29<02:15,  2.84it/s]






 19%|█▉        | 90/474 [00:30<02:39,  2.41it/s]






 19%|█▉        | 91/474 [00:30<02:20,  2.73it/s]






 20%|█▉        | 93/474 [00:30<01:39,  3.81it/s]






 20%|█▉        | 94/474 [00:31<01:57,  3.22it/s]






 20%|██        | 97/474 [00:32<01:53,  3.31it/s]






 21%|██        | 98/474 [00:32<02:21,  2.65it/s]






 21%|██        | 99/474 [00:32<02:02,  3.07it/s]






 21%|██        | 100/474 [00:33<01:54,  3.27it/s]






 21%|██▏       | 101/474 [00:33<01:47,  3.46it/s]






 22%|██▏       | 102/474 [00:33<01:46,  3.49it/s]






 22%|██▏       | 103/474 [00:33<01:51,  3.33it/s]






 22%|██▏       | 105/474 [00:34<02:14,  2.75it/s]






 22%|██▏       | 106/474 [00:35<02:20,  2.62it/s]






 23%|██▎       | 108/474 [00:35<01:48,  3.38it/s]






 23%|██▎       | 109/474 [00:36<01:54,  3.19it/s]






 23%|██▎       | 111/474 [00:36<01:36,  3.77it/s]






 24%|██▎       | 112/474 [00:36<01:27,  4.15it/s]






 24%|██▍       | 113/474 [00:37<02:11,  2.74it/s]






 24%|██▍       | 114/474 [00:37<02:22,  2.53it/s]






 24%|██▍       | 116/474 [00:38<01:40,  3.56it/s]

 25%|██▍       | 117/474 [00:38<01:48,  3.30it/s]






 25%|██▍       | 118/474 [00:38<01:34,  3.78it/s]






 25%|██▌       | 119/474 [00:38<01:42,  3.48it/s]






 25%|██▌       | 120/474 [00:39<01:24,  4.19it/s]






 26%|██▌       | 121/474 [00:39<02:05,  2.82it/s]






 26%|██▌       | 122/474 [00:40<02:08,  2.74it/s]






 26%|██▌       | 123/474 [00:40<01:55,  3.05it/s]






 26%|██▋       | 125/474 [00:40<01:41,  3.45it/s]






 27%|██▋       | 127/474 [00:41<01:36,  3.59it/s]






 27%|██▋       | 129/474 [00:41<01:38,  3.49it/s]






 27%|██▋       | 130/474 [00:42<01:48,  3.17it/s]






 28%|██▊       | 131/474 [00:42<01:41,  3.39it/s]






 28%|██▊       | 132/474 [00:42<01:27,  3.92it/s]






 28%|██▊       | 133/474 [00:43<01:42,  3.31it/s]






 28%|██▊       | 135/474 [00:43<01:39,  3.41it/s]






 29%|██▉       | 137/474 [00:44<01:39,  3.39it/s]






 29%|██▉       | 138/474 [00:44<01:46,  3.16it/s]






 29%|██▉       | 139/474 [00:44<01:37,  3.45it/s]






 30%|██▉       | 140/474 [00:44<01:21,  4.11it/s]






 30%|██▉       | 141/474 [00:45<01:49,  3.05it/s]






 30%|███       | 143/474 [00:46<01:34,  3.52it/s]






 31%|███       | 145/474 [00:46<01:37,  3.37it/s]






 31%|███       | 146/474 [00:46<01:37,  3.36it/s]






 31%|███       | 147/474 [00:47<01:39,  3.28it/s]






 31%|███       | 148/474 [00:47<01:38,  3.31it/s]






 31%|███▏      | 149/474 [00:48<02:20,  2.32it/s]






 32%|███▏      | 150/474 [00:48<02:02,  2.64it/s]






 32%|███▏      | 151/474 [00:48<01:39,  3.25it/s]






 32%|███▏      | 152/474 [00:49<01:42,  3.14it/s]






 32%|███▏      | 153/474 [00:49<02:14,  2.39it/s]






 32%|███▏      | 154/474 [00:50<02:30,  2.12it/s]






 33%|███▎      | 155/474 [00:50<02:29,  2.13it/s]






 33%|███▎      | 157/474 [00:51<02:31,  2.09it/s]






 33%|███▎      | 158/474 [00:52<02:12,  2.39it/s]






 34%|███▍      | 160/474 [00:52<01:56,  2.70it/s]






 34%|███▍      | 161/474 [00:52<01:53,  2.76it/s]






 34%|███▍      | 162/474 [00:53<02:21,  2.20it/s]






 34%|███▍      | 163/474 [00:54<02:20,  2.22it/s]






 35%|███▍      | 165/474 [00:54<02:04,  2.48it/s]






 35%|███▌      | 166/474 [00:54<01:45,  2.92it/s]






 35%|███▌      | 168/474 [00:55<01:30,  3.37it/s]






 36%|███▌      | 169/474 [00:55<01:33,  3.25it/s]






 36%|███▌      | 170/474 [00:56<01:54,  2.66it/s]






 36%|███▌      | 171/474 [00:56<01:59,  2.54it/s]






 36%|███▋      | 173/474 [00:57<01:56,  2.58it/s]






 37%|███▋      | 176/474 [00:58<01:25,  3.49it/s]






 37%|███▋      | 177/474 [00:58<01:27,  3.38it/s]






 38%|███▊      | 178/474 [00:58<01:45,  2.81it/s]






 38%|███▊      | 179/474 [00:59<01:45,  2.81it/s]






 38%|███▊      | 181/474 [01:00<01:41,  2.89it/s]






 39%|███▊      | 183/474 [01:00<01:10,  4.14it/s]






 39%|███▉      | 184/474 [01:00<01:17,  3.75it/s]






 39%|███▉      | 185/474 [01:00<01:23,  3.46it/s]






 39%|███▉      | 186/474 [01:01<01:34,  3.06it/s]






 39%|███▉      | 187/474 [01:01<01:43,  2.77it/s]






 40%|███▉      | 188/474 [01:02<01:35,  2.99it/s]






 40%|███▉      | 189/474 [01:02<01:39,  2.87it/s]






 40%|████      | 191/474 [01:02<01:13,  3.87it/s]






 41%|████      | 192/474 [01:02<01:15,  3.74it/s]






 41%|████      | 193/474 [01:03<01:39,  2.82it/s]






 41%|████      | 194/474 [01:03<01:35,  2.93it/s]






 41%|████      | 195/474 [01:04<01:39,  2.81it/s]






 41%|████▏     | 196/474 [01:04<01:31,  3.05it/s]






 42%|████▏     | 197/474 [01:05<01:59,  2.32it/s]






 42%|████▏     | 198/474 [01:05<01:33,  2.96it/s]






 42%|████▏     | 199/474 [01:05<01:27,  3.13it/s]






 42%|████▏     | 201/474 [01:06<01:25,  3.20it/s]






 43%|████▎     | 202/474 [01:06<01:32,  2.95it/s]






 43%|████▎     | 203/474 [01:06<01:30,  3.00it/s]






 43%|████▎     | 204/474 [01:07<01:34,  2.87it/s]






 43%|████▎     | 205/474 [01:07<01:47,  2.51it/s]






 43%|████▎     | 206/474 [01:08<01:32,  2.89it/s]






 44%|████▎     | 207/474 [01:08<01:18,  3.38it/s]






 44%|████▍     | 208/474 [01:08<01:11,  3.73it/s]






 44%|████▍     | 209/474 [01:08<01:19,  3.33it/s]






 44%|████▍     | 210/474 [01:09<01:46,  2.49it/s]






 45%|████▍     | 212/474 [01:10<01:29,  2.93it/s]






 45%|████▍     | 213/474 [01:10<01:46,  2.46it/s]






 45%|████▌     | 215/474 [01:10<01:15,  3.41it/s]






 46%|████▌     | 216/474 [01:11<01:18,  3.28it/s]






 46%|████▌     | 217/474 [01:11<01:13,  3.48it/s]






 46%|████▌     | 218/474 [01:12<01:39,  2.58it/s]






 46%|████▋     | 220/474 [01:12<01:34,  2.69it/s]






 47%|████▋     | 221/474 [01:13<01:37,  2.59it/s]






 47%|████▋     | 223/474 [01:13<01:12,  3.44it/s]






 47%|████▋     | 224/474 [01:13<01:12,  3.46it/s]






 48%|████▊     | 226/474 [01:14<01:18,  3.15it/s]






 48%|████▊     | 227/474 [01:16<02:28,  1.67it/s]






 49%|████▉     | 232/474 [01:16<01:05,  3.72it/s]






 49%|████▉     | 233/474 [01:16<01:01,  3.90it/s]






 49%|████▉     | 234/474 [01:17<01:14,  3.22it/s]






 50%|████▉     | 235/474 [01:19<02:24,  1.65it/s]






 50%|█████     | 238/474 [01:19<01:21,  2.88it/s]






 51%|█████     | 240/474 [01:19<01:03,  3.68it/s]






 51%|█████     | 241/474 [01:19<00:57,  4.03it/s]






 51%|█████     | 242/474 [01:20<01:14,  3.12it/s]






 51%|█████▏    | 243/474 [01:21<02:33,  1.50it/s]






 52%|█████▏    | 246/474 [01:22<01:22,  2.76it/s]






 52%|█████▏    | 247/474 [01:22<01:16,  2.95it/s]






 53%|█████▎    | 249/474 [01:22<00:54,  4.16it/s]






 53%|█████▎    | 251/474 [01:24<01:59,  1.87it/s]






 53%|█████▎    | 252/474 [01:24<01:42,  2.17it/s]






 54%|█████▎    | 254/474 [01:24<01:11,  3.09it/s]






 54%|█████▍    | 256/474 [01:25<00:55,  3.89it/s]






 54%|█████▍    | 258/474 [01:25<00:54,  3.95it/s]






 55%|█████▍    | 259/474 [01:27<01:55,  1.86it/s]

 55%|█████▌    | 262/474 [01:27<01:11,  2.98it/s]






 55%|█████▌    | 263/474 [01:27<01:02,  3.38it/s]






 56%|█████▌    | 264/474 [01:28<00:56,  3.70it/s]






 56%|█████▌    | 266/474 [01:28<00:49,  4.16it/s]






 56%|█████▋    | 267/474 [01:30<02:00,  1.72it/s]






 57%|█████▋    | 269/474 [01:30<01:26,  2.37it/s]






 57%|█████▋    | 270/474 [01:30<01:13,  2.78it/s]






 58%|█████▊    | 274/474 [01:31<00:45,  4.38it/s]






 58%|█████▊    | 275/474 [01:32<01:35,  2.08it/s]






 58%|█████▊    | 276/474 [01:33<01:22,  2.39it/s]






 58%|█████▊    | 277/474 [01:33<01:17,  2.55it/s]






 59%|█████▉    | 279/474 [01:33<00:53,  3.63it/s]






 59%|█████▉    | 282/474 [01:34<00:41,  4.61it/s]






 60%|█████▉    | 283/474 [01:36<01:47,  1.78it/s]






 60%|██████    | 285/474 [01:36<01:23,  2.26it/s]






 61%|██████    | 287/474 [01:36<00:59,  3.16it/s]






 61%|██████    | 289/474 [01:36<00:44,  4.13it/s]






 61%|██████▏   | 291/474 [01:39<01:36,  1.89it/s]






 62%|██████▏   | 292/474 [01:39<01:39,  1.83it/s]






 62%|██████▏   | 293/474 [01:40<01:26,  2.08it/s]






 62%|██████▏   | 295/474 [01:40<00:57,  3.09it/s]






 62%|██████▏   | 296/474 [01:40<00:50,  3.55it/s]






 63%|██████▎   | 297/474 [01:40<00:42,  4.17it/s]






 63%|██████▎   | 298/474 [01:40<00:37,  4.69it/s]






 63%|██████▎   | 299/474 [01:42<01:46,  1.65it/s]






 63%|██████▎   | 300/474 [01:42<01:33,  1.87it/s]






 64%|██████▎   | 301/474 [01:42<01:16,  2.26it/s]






 64%|██████▎   | 302/474 [01:42<00:59,  2.90it/s]






 64%|██████▍   | 304/474 [01:43<00:37,  4.55it/s]






 64%|██████▍   | 305/474 [01:43<00:34,  4.96it/s]






 65%|██████▍   | 306/474 [01:43<00:31,  5.30it/s]






 65%|██████▍   | 307/474 [01:44<01:29,  1.86it/s]






 65%|██████▍   | 308/474 [01:45<01:26,  1.93it/s]






 65%|██████▌   | 310/474 [01:45<00:54,  3.00it/s]






 66%|██████▌   | 311/474 [01:45<00:45,  3.59it/s]






 66%|██████▌   | 314/474 [01:45<00:29,  5.37it/s]






 66%|██████▋   | 315/474 [01:47<01:08,  2.31it/s]






 67%|██████▋   | 316/474 [01:47<01:11,  2.22it/s]






 67%|██████▋   | 318/474 [01:48<00:49,  3.18it/s]






 67%|██████▋   | 319/474 [01:48<00:42,  3.66it/s]






 68%|██████▊   | 322/474 [01:48<00:26,  5.67it/s]






 68%|██████▊   | 323/474 [01:50<01:08,  2.20it/s]






 68%|██████▊   | 324/474 [01:50<01:06,  2.26it/s]






 69%|██████▊   | 325/474 [01:50<00:57,  2.57it/s]






 69%|██████▉   | 326/474 [01:50<00:48,  3.04it/s]






 69%|██████▉   | 328/474 [01:50<00:31,  4.65it/s]






 70%|██████▉   | 330/474 [01:51<00:26,  5.54it/s]






 70%|██████▉   | 331/474 [01:52<01:02,  2.29it/s]






 70%|███████   | 332/474 [01:53<01:03,  2.25it/s]






 70%|███████   | 333/474 [01:53<00:55,  2.53it/s]






 70%|███████   | 334/474 [01:53<00:45,  3.05it/s]






 71%|███████   | 335/474 [01:53<00:42,  3.30it/s]






 71%|███████   | 337/474 [01:53<00:28,  4.89it/s]






 71%|███████▏  | 338/474 [01:53<00:27,  5.00it/s]






 72%|███████▏  | 339/474 [01:55<01:01,  2.18it/s]






 72%|███████▏  | 340/474 [01:55<01:07,  1.99it/s]






 72%|███████▏  | 342/474 [01:56<00:44,  2.94it/s]






 72%|███████▏  | 343/474 [01:56<00:37,  3.47it/s]






 73%|███████▎  | 344/474 [01:56<00:37,  3.50it/s]






 73%|███████▎  | 346/474 [01:56<00:24,  5.15it/s]






 73%|███████▎  | 347/474 [01:57<00:51,  2.47it/s]






 73%|███████▎  | 348/474 [01:58<00:55,  2.27it/s]






 74%|███████▎  | 349/474 [01:58<00:51,  2.43it/s]






 74%|███████▍  | 350/474 [01:58<00:40,  3.05it/s]






 74%|███████▍  | 352/474 [01:58<00:28,  4.27it/s]






 74%|███████▍  | 353/474 [01:59<00:25,  4.72it/s]






 75%|███████▍  | 355/474 [02:00<00:43,  2.73it/s]






 75%|███████▌  | 356/474 [02:00<00:51,  2.30it/s]






 75%|███████▌  | 357/474 [02:01<00:45,  2.58it/s]






 76%|███████▌  | 358/474 [02:01<00:40,  2.90it/s]






 76%|███████▌  | 360/474 [02:01<00:28,  4.01it/s]






 76%|███████▋  | 362/474 [02:01<00:19,  5.64it/s]






 77%|███████▋  | 363/474 [02:03<00:48,  2.31it/s]






 77%|███████▋  | 364/474 [02:03<00:53,  2.06it/s]






 77%|███████▋  | 366/474 [02:04<00:37,  2.87it/s]






 77%|███████▋  | 367/474 [02:04<00:33,  3.18it/s]






 78%|███████▊  | 369/474 [02:04<00:22,  4.68it/s]






 78%|███████▊  | 371/474 [02:05<00:41,  2.48it/s]






 78%|███████▊  | 372/474 [02:06<00:46,  2.18it/s]






 79%|███████▊  | 373/474 [02:06<00:39,  2.54it/s]






 79%|███████▉  | 374/474 [02:07<00:36,  2.70it/s]






 79%|███████▉  | 376/474 [02:07<00:24,  4.08it/s]






 80%|███████▉  | 379/474 [02:08<00:35,  2.65it/s]






 80%|████████  | 380/474 [02:09<00:38,  2.46it/s]






 80%|████████  | 381/474 [02:09<00:33,  2.76it/s]






 81%|████████  | 382/474 [02:09<00:31,  2.95it/s]






 81%|████████  | 383/474 [02:09<00:29,  3.12it/s]






 81%|████████  | 385/474 [02:10<00:18,  4.74it/s]






 81%|████████▏ | 386/474 [02:10<00:16,  5.36it/s]






 82%|████████▏ | 387/474 [02:11<00:40,  2.14it/s]






 82%|████████▏ | 388/474 [02:11<00:39,  2.16it/s]






 82%|████████▏ | 389/474 [02:12<00:31,  2.71it/s]






 82%|████████▏ | 390/474 [02:12<00:32,  2.58it/s]






 82%|████████▏ | 391/474 [02:12<00:26,  3.18it/s]






 83%|████████▎ | 393/474 [02:12<00:16,  4.98it/s]






 83%|████████▎ | 394/474 [02:12<00:14,  5.43it/s]






 83%|████████▎ | 395/474 [02:14<00:37,  2.13it/s]






 84%|████████▎ | 396/474 [02:14<00:37,  2.09it/s]






 84%|████████▍ | 398/474 [02:15<00:28,  2.69it/s]






 84%|████████▍ | 400/474 [02:15<00:18,  3.95it/s]






 85%|████████▌ | 403/474 [02:16<00:25,  2.78it/s]






 85%|████████▌ | 404/474 [02:17<00:28,  2.44it/s]






 86%|████████▌ | 406/474 [02:17<00:23,  2.93it/s]






 86%|████████▌ | 407/474 [02:17<00:19,  3.39it/s]






 87%|████████▋ | 411/474 [02:19<00:21,  2.95it/s]






 87%|████████▋ | 412/474 [02:20<00:23,  2.65it/s]

 87%|████████▋ | 414/474 [02:20<00:20,  2.98it/s]






 88%|████████▊ | 415/474 [02:20<00:17,  3.37it/s]






 88%|████████▊ | 418/474 [02:20<00:10,  5.50it/s]






 89%|████████▊ | 420/474 [02:22<00:21,  2.48it/s]






 89%|████████▉ | 422/474 [02:23<00:18,  2.75it/s]






 89%|████████▉ | 423/474 [02:23<00:16,  3.15it/s]






 90%|████████▉ | 425/474 [02:23<00:11,  4.31it/s]






 90%|█████████ | 427/474 [02:24<00:17,  2.68it/s]






 90%|█████████ | 428/474 [02:25<00:18,  2.49it/s]






 91%|█████████ | 430/474 [02:25<00:15,  2.84it/s]






 91%|█████████ | 431/474 [02:25<00:13,  3.18it/s]






 91%|█████████▏| 433/474 [02:26<00:09,  4.53it/s]






 92%|█████████▏| 435/474 [02:27<00:15,  2.51it/s]






 92%|█████████▏| 436/474 [02:27<00:14,  2.63it/s]






 92%|█████████▏| 438/474 [02:28<00:12,  2.88it/s]






 93%|█████████▎| 439/474 [02:28<00:10,  3.28it/s]






 93%|█████████▎| 441/474 [02:28<00:08,  4.08it/s]






 93%|█████████▎| 443/474 [02:30<00:11,  2.59it/s]






 94%|█████████▎| 444/474 [02:30<00:11,  2.69it/s]






 94%|█████████▍| 446/474 [02:31<00:09,  2.83it/s]






 95%|█████████▍| 448/474 [02:31<00:06,  3.81it/s]






 95%|█████████▍| 449/474 [02:31<00:06,  3.80it/s]






 95%|█████████▍| 450/474 [02:31<00:05,  4.19it/s]






 95%|█████████▌| 451/474 [02:32<00:10,  2.15it/s]






 95%|█████████▌| 452/474 [02:33<00:09,  2.39it/s]






 96%|█████████▌| 453/474 [02:33<00:07,  2.73it/s]






 96%|█████████▌| 454/474 [02:33<00:07,  2.58it/s]






 96%|█████████▌| 456/474 [02:33<00:04,  4.00it/s]






 96%|█████████▋| 457/474 [02:34<00:04,  3.98it/s]






 97%|█████████▋| 458/474 [02:34<00:03,  4.27it/s]






 97%|█████████▋| 459/474 [02:35<00:06,  2.45it/s]






 97%|█████████▋| 460/474 [02:35<00:05,  2.34it/s]






 97%|█████████▋| 461/474 [02:35<00:04,  2.86it/s]






 97%|█████████▋| 462/474 [02:36<00:04,  2.70it/s]






 98%|█████████▊| 465/474 [02:36<00:01,  4.68it/s]






 98%|█████████▊| 466/474 [02:36<00:01,  4.86it/s]






 99%|█████████▊| 467/474 [02:37<00:02,  2.87it/s]






 99%|█████████▊| 468/474 [02:38<00:02,  2.36it/s]






 99%|█████████▉| 470/474 [02:38<00:01,  2.89it/s]






 99%|█████████▉| 471/474 [02:38<00:00,  3.17it/s]






100%|█████████▉| 472/474 [02:39<00:00,  3.65it/s]






100%|██████████| 474/474 [02:39<00:00,  2.97it/s]
Families:  67%|██████▋   | 2/3 [02:57<01:41, 101.13s/it]
Multiplets | family 3:   0%|          | 0/55 [00:00<?, ?it/s]


  0%|          | 0/55 [00:00<?, ?it/s]


  2%|▏         | 1/55 [00:01<01:40,  1.86s/it]


  7%|▋         | 4/55 [00:01<00:19,  2.59it/s]


 15%|█▍        | 8/55 [00:02<00:07,  5.91it/s]


 20%|██        | 11/55 [00:03<00:14,  3.12it/s]


 24%|██▎       | 13/55 [00:03<00:10,  3.95it/s]


 29%|██▉       | 16/55 [00:04<00:06,  5.68it/s]


 33%|███▎      | 18/55 [00:05<00:12,  2.88it/s]


 36%|███▋      | 20/55 [00:05<00:09,  3.70it/s]


 40%|████      | 22/55 [00:05<00:07,  4.67it/s]


 45%|████▌     | 25/55 [00:07<00:09,  3.07it/s]


 49%|████▉     | 27/55 [00:07<00:07,  3.88it/s]


 53%|█████▎    | 29/55 [00:07<00:05,  4.83it/s]


 56%|█████▋    | 31/55 [00:07<00:03,  6.08it/s]


 60%|██████    | 33/55 [00:09<00:07,  3.07it/s]


 64%|██████▎   | 35/55 [00:09<00:05,  3.94it/s]


 67%|██████▋   | 37/55 [00:09<00:03,  5.04it/s]


 71%|███████   | 39/55 [00:09<00:02,  6.27it/s]


 75%|███████▍  | 41/55 [00:11<00:04,  3.12it/s]


 78%|███████▊  | 43/55 [00:11<00:02,  4.02it/s]


 82%|████████▏ | 45/55 [00:11<00:01,  5.12it/s]


 85%|████████▌ | 47/55 [00:11<00:01,  6.12it/s]


 89%|████████▉ | 49/55 [00:12<00:01,  3.29it/s]


 91%|█████████ | 50/55 [00:13<00:01,  3.60it/s]


100%|██████████| 55/55 [00:13<00:00,  4.13it/s]
Families: 100%|██████████| 3/3 [03:10<00:00, 63.54s/it]

Runtime: 190.636744 s

Multiplets | family 3:   0%|          | 0/55 [00:13<?, ?it/s]

Multiplets | family 5:   0%|          | 0/288 [00:00<?, ?it/s]


  0%|          | 0/288 [00:00<?, ?it/s]


  0%|          | 1/288 [00:05<25:08,  5.26s/it]


  1%|          | 2/288 [00:05<10:47,  2.26s/it]


  1%|          | 3/288 [00:05<06:03,  1.28s/it]


  1%|▏         | 4/288 [00:05<03:51,  1.23it/s]


  2%|▏         | 5/288 [00:05<02:41,  1.76it/s]


  2%|▏         | 6/288 [00:05<02:04,  2.26it/s]


  3%|▎         | 8/288 [00:06<01:13,  3.81it/s]


  3%|▎         | 9/288 [00:10<06:19,  1.36s/it]


  3%|▎         | 10/288 [00:10<05:02,  1.09s/it]


  4%|▍         | 11/288 [00:11<03:49,  1.21it/s]


  5%|▍         | 14/288 [00:11<02:04,  2.20it/s]


  6%|▌         | 16/288 [00:11<01:39,  2.74it/s]


  6%|▌         | 17/288 [00:15<04:55,  1.09s/it]


  6%|▋         | 18/288 [00:16<04:26,  1.01it/s]


  7%|▋         | 20/288 [00:16<02:59,  1.49it/s]


  8%|▊         | 22/288 [00:17<02:05,  2.12it/s]


  8%|▊         | 23/288 [00:17<01:55,  2.30it/s]


  8%|▊         | 24/288 [00:17<01:54,  2.30it/s]


  9%|▊         | 25/288 [00:21<05:47,  1.32s/it]


  9%|▉         | 26/288 [00:22<04:38,  1.06s/it]


  9%|▉         | 27/288 [00:22<03:53,  1.12it/s]


 10%|▉         | 28/288 [00:22<03:04,  1.41it/s]


 10%|█         | 30/288 [00:23<01:54,  2.25it/s]


 11%|█         | 31/288 [00:23<01:44,  2.45it/s]


 11%|█         | 32/288 [00:24<01:53,  2.25it/s]


 11%|█▏        | 33/288 [00:27<05:41,  1.34s/it]


 12%|█▏        | 34/288 [00:28<04:31,  1.07s/it]


 12%|█▏        | 35/288 [00:28<03:27,  1.22it/s]


 12%|█▎        | 36/288 [00:28<02:56,  1.43it/s]


 13%|█▎        | 37/288 [00:29<02:30,  1.67it/s]


 14%|█▎        | 39/288 [00:29<01:37,  2.54it/s]


 14%|█▍        | 40/288 [00:30<01:58,  2.09it/s]


 14%|█▍        | 41/288 [00:33<05:06,  1.24s/it]


 15%|█▍        | 42/288 [00:33<04:11,  1.02s/it]


 15%|█▌        | 44/288 [00:34<02:51,  1.42it/s]


 16%|█▌        | 45/288 [00:34<02:28,  1.63it/s]


 16%|█▌        | 46/288 [00:34<01:57,  2.07it/s]


 16%|█▋        | 47/288 [00:35<01:44,  2.31it/s]


 17%|█▋        | 48/288 [00:36<02:11,  1.83it/s]


 17%|█▋        | 49/288 [00:39<04:57,  1.25s/it]


 17%|█▋        | 50/288 [00:39<04:09,  1.05s/it]


 18%|█▊        | 51/288 [00:40<03:19,  1.19it/s]


 18%|█▊        | 52/288 [00:40<02:48,  1.40it/s]


 18%|█▊        | 53/288 [00:40<02:19,  1.68it/s]


 19%|█▉        | 54/288 [00:41<01:58,  1.98it/s]


 19%|█▉        | 55/288 [00:41<01:30,  2.58it/s]


 19%|█▉        | 56/288 [00:42<02:16,  1.71it/s]


 20%|█▉        | 57/288 [00:44<04:38,  1.21s/it]


 20%|██        | 58/288 [00:45<03:49,  1.00it/s]


 20%|██        | 59/288 [00:45<03:11,  1.20it/s]


 21%|██        | 60/288 [00:46<02:36,  1.46it/s]


 21%|██        | 61/288 [00:46<02:18,  1.63it/s]


 22%|██▏       | 62/288 [00:46<01:51,  2.03it/s]


 22%|██▏       | 63/288 [00:47<01:30,  2.50it/s]


 22%|██▏       | 64/288 [00:48<02:10,  1.72it/s]


 23%|██▎       | 65/288 [00:50<04:16,  1.15s/it]


 23%|██▎       | 66/288 [00:51<04:05,  1.10s/it]


 23%|██▎       | 67/288 [00:51<03:09,  1.17it/s]


 24%|██▎       | 68/288 [00:51<02:24,  1.52it/s]


 24%|██▍       | 69/288 [00:52<02:21,  1.55it/s]


 24%|██▍       | 70/288 [00:52<01:57,  1.86it/s]


 25%|██▍       | 71/288 [00:53<01:55,  1.88it/s]


 25%|██▌       | 72/288 [00:54<02:20,  1.53it/s]


 25%|██▌       | 73/288 [00:56<03:38,  1.02s/it]


 26%|██▌       | 74/288 [00:57<03:54,  1.10s/it]


 26%|██▋       | 76/288 [00:57<02:17,  1.55it/s]


 27%|██▋       | 77/288 [00:58<02:26,  1.44it/s]


 27%|██▋       | 78/288 [00:58<02:02,  1.72it/s]


 27%|██▋       | 79/288 [00:59<01:59,  1.75it/s]


 28%|██▊       | 80/288 [01:00<02:23,  1.45it/s]


 28%|██▊       | 81/288 [01:01<03:09,  1.09it/s]


 28%|██▊       | 82/288 [01:02<03:17,  1.05it/s]


 29%|██▉       | 83/288 [01:03<02:27,  1.39it/s]


 29%|██▉       | 84/288 [01:03<01:52,  1.82it/s]


 30%|██▉       | 85/288 [01:04<02:08,  1.59it/s]


 30%|██▉       | 86/288 [01:04<01:46,  1.90it/s]


 30%|███       | 87/288 [01:05<01:58,  1.70it/s]


 31%|███       | 88/288 [01:06<02:33,  1.30it/s]


 31%|███       | 89/288 [01:07<02:50,  1.17it/s]


 31%|███▏      | 90/288 [01:08<03:23,  1.03s/it]


 32%|███▏      | 91/288 [01:08<02:30,  1.31it/s]


 32%|███▏      | 93/288 [01:10<02:21,  1.38it/s]


 33%|███▎      | 95/288 [01:10<01:48,  1.78it/s]


 33%|███▎      | 96/288 [01:12<02:28,  1.30it/s]


 34%|███▎      | 97/288 [01:12<02:19,  1.37it/s]


 34%|███▍      | 98/288 [01:14<02:58,  1.06it/s]


 35%|███▍      | 100/288 [01:14<01:55,  1.62it/s]


 35%|███▌      | 101/288 [01:15<02:13,  1.40it/s]


 35%|███▌      | 102/288 [01:16<01:48,  1.72it/s]


 36%|███▌      | 103/288 [01:16<01:33,  1.98it/s]


 36%|███▌      | 104/288 [01:17<02:27,  1.25it/s]


 36%|███▋      | 105/288 [01:18<01:59,  1.53it/s]


 37%|███▋      | 106/288 [01:19<02:50,  1.07it/s]


 37%|███▋      | 107/288 [01:19<02:06,  1.43it/s]


 38%|███▊      | 108/288 [01:20<01:44,  1.72it/s]


 38%|███▊      | 109/288 [01:21<02:06,  1.41it/s]


 38%|███▊      | 110/288 [01:21<01:41,  1.76it/s]


 39%|███▊      | 111/288 [01:22<01:38,  1.80it/s]


 39%|███▉      | 112/288 [01:23<02:37,  1.12it/s]


 39%|███▉      | 113/288 [01:24<02:05,  1.39it/s]


 40%|███▉      | 114/288 [01:25<02:46,  1.05it/s]


 40%|███▉      | 115/288 [01:26<02:22,  1.21it/s]


 40%|████      | 116/288 [01:26<01:51,  1.54it/s]


 41%|████      | 117/288 [01:26<01:45,  1.61it/s]


 41%|████      | 118/288 [01:27<01:57,  1.45it/s]


 41%|████▏     | 119/288 [01:28<01:47,  1.57it/s]


 42%|████▏     | 120/288 [01:29<02:21,  1.19it/s]


 42%|████▏     | 122/288 [01:31<02:19,  1.19it/s]


 43%|████▎     | 123/288 [01:31<02:05,  1.32it/s]


 43%|████▎     | 124/288 [01:32<01:44,  1.57it/s]


 43%|████▎     | 125/288 [01:32<01:34,  1.73it/s]


 44%|████▍     | 126/288 [01:33<01:49,  1.47it/s]


 44%|████▍     | 127/288 [01:33<01:35,  1.69it/s]


 44%|████▍     | 128/288 [01:34<02:01,  1.32it/s]


 45%|████▍     | 129/288 [01:35<01:43,  1.53it/s]


 45%|████▌     | 130/288 [01:36<02:12,  1.19it/s]


 45%|████▌     | 131/288 [01:37<01:58,  1.32it/s]


 46%|████▌     | 132/288 [01:37<01:34,  1.65it/s]


 46%|████▌     | 133/288 [01:38<01:33,  1.66it/s]


 47%|████▋     | 134/288 [01:39<01:57,  1.31it/s]


 47%|████▋     | 135/288 [01:39<01:28,  1.74it/s]


 47%|████▋     | 136/288 [01:40<01:46,  1.42it/s]


 48%|████▊     | 137/288 [01:41<01:55,  1.30it/s]


 48%|████▊     | 138/288 [01:42<02:30,  1.00s/it]


 48%|████▊     | 139/288 [01:42<01:48,  1.37it/s]


 49%|████▊     | 140/288 [01:43<01:22,  1.79it/s]


 49%|████▉     | 141/288 [01:44<01:40,  1.46it/s]


 49%|████▉     | 142/288 [01:45<02:01,  1.21it/s]


 50%|████▉     | 143/288 [01:45<01:42,  1.42it/s]


 50%|█████     | 144/288 [01:46<01:31,  1.57it/s]


 50%|█████     | 145/288 [01:46<01:36,  1.48it/s]


 51%|█████     | 146/288 [01:48<02:10,  1.09it/s]

 52%|█████▏    | 149/288 [01:49<01:24,  1.65it/s]


 52%|█████▏    | 150/288 [01:50<01:39,  1.39it/s]


 52%|█████▏    | 151/288 [01:50<01:28,  1.55it/s]


 53%|█████▎    | 152/288 [01:51<01:17,  1.76it/s]


 53%|█████▎    | 153/288 [01:52<01:28,  1.53it/s]


 53%|█████▎    | 154/288 [01:53<01:50,  1.21it/s]


 54%|█████▍    | 156/288 [01:53<01:12,  1.81it/s]


 55%|█████▍    | 157/288 [01:54<01:12,  1.80it/s]


 55%|█████▍    | 158/288 [01:55<01:40,  1.29it/s]


 55%|█████▌    | 159/288 [01:56<01:30,  1.43it/s]


 56%|█████▌    | 160/288 [01:57<01:29,  1.42it/s]


 56%|█████▌    | 161/288 [01:57<01:14,  1.70it/s]


 56%|█████▋    | 162/288 [01:58<01:37,  1.29it/s]


 57%|█████▋    | 163/288 [01:58<01:21,  1.54it/s]


 57%|█████▋    | 164/288 [01:59<01:13,  1.69it/s]


 57%|█████▋    | 165/288 [01:59<01:06,  1.85it/s]


 58%|█████▊    | 166/288 [02:01<01:41,  1.21it/s]


 58%|█████▊    | 167/288 [02:01<01:25,  1.41it/s]


 58%|█████▊    | 168/288 [02:02<01:16,  1.56it/s]


 59%|█████▊    | 169/288 [02:02<01:18,  1.52it/s]


 59%|█████▉    | 170/288 [02:03<01:19,  1.49it/s]


 59%|█████▉    | 171/288 [02:04<01:14,  1.57it/s]


 60%|█████▉    | 172/288 [02:04<01:04,  1.79it/s]


 60%|██████    | 173/288 [02:05<00:59,  1.92it/s]


 60%|██████    | 174/288 [02:06<01:25,  1.33it/s]


 61%|██████    | 175/288 [02:06<01:19,  1.43it/s]


 61%|██████    | 176/288 [02:07<01:03,  1.78it/s]


 61%|██████▏   | 177/288 [02:08<01:17,  1.43it/s]


 62%|██████▏   | 178/288 [02:08<01:11,  1.54it/s]


 62%|██████▏   | 179/288 [02:09<01:17,  1.41it/s]


 63%|██████▎   | 181/288 [02:10<00:58,  1.82it/s]


 63%|██████▎   | 182/288 [02:11<01:21,  1.30it/s]


 64%|██████▍   | 184/288 [02:12<01:01,  1.68it/s]


 64%|██████▍   | 185/288 [02:13<01:05,  1.57it/s]


 65%|██████▍   | 186/288 [02:14<01:17,  1.32it/s]


 65%|██████▍   | 187/288 [02:14<01:02,  1.62it/s]


 65%|██████▌   | 188/288 [02:14<00:55,  1.80it/s]


 66%|██████▌   | 189/288 [02:15<00:49,  1.99it/s]


 66%|██████▌   | 190/288 [02:16<01:13,  1.33it/s]


 66%|██████▋   | 191/288 [02:16<00:55,  1.76it/s]


 67%|██████▋   | 192/288 [02:17<00:53,  1.78it/s]


 67%|██████▋   | 193/288 [02:18<01:13,  1.29it/s]


 67%|██████▋   | 194/288 [02:19<01:15,  1.25it/s]


 68%|██████▊   | 195/288 [02:19<00:55,  1.67it/s]


 68%|██████▊   | 196/288 [02:20<00:50,  1.81it/s]


 68%|██████▊   | 197/288 [02:20<00:45,  2.00it/s]


 69%|██████▉   | 198/288 [02:21<01:05,  1.38it/s]


 69%|██████▉   | 199/288 [02:21<00:50,  1.77it/s]


 69%|██████▉   | 200/288 [02:22<00:42,  2.09it/s]


 70%|██████▉   | 201/288 [02:23<01:09,  1.25it/s]


 70%|███████   | 202/288 [02:24<01:09,  1.23it/s]


 70%|███████   | 203/288 [02:24<00:51,  1.66it/s]


 71%|███████   | 204/288 [02:25<00:47,  1.78it/s]


 71%|███████   | 205/288 [02:25<00:48,  1.69it/s]


 72%|███████▏  | 206/288 [02:26<00:52,  1.57it/s]


 72%|███████▏  | 207/288 [02:26<00:42,  1.90it/s]


 72%|███████▏  | 208/288 [02:27<00:45,  1.77it/s]


 73%|███████▎  | 209/288 [02:28<00:57,  1.37it/s]


 73%|███████▎  | 210/288 [02:29<01:05,  1.19it/s]


 73%|███████▎  | 211/288 [02:30<00:55,  1.40it/s]


 74%|███████▎  | 212/288 [02:30<00:41,  1.83it/s]


 74%|███████▍  | 213/288 [02:31<00:59,  1.26it/s]


 74%|███████▍  | 214/288 [02:31<00:47,  1.56it/s]


 75%|███████▍  | 215/288 [02:32<00:38,  1.89it/s]


 75%|███████▌  | 216/288 [02:32<00:32,  2.23it/s]


 75%|███████▌  | 217/288 [02:33<00:53,  1.34it/s]


 76%|███████▌  | 218/288 [02:35<01:01,  1.13it/s]


 76%|███████▌  | 219/288 [02:35<00:48,  1.43it/s]


 76%|███████▋  | 220/288 [02:35<00:36,  1.89it/s]


 77%|███████▋  | 221/288 [02:36<00:50,  1.32it/s]


 77%|███████▋  | 222/288 [02:36<00:37,  1.74it/s]


 77%|███████▋  | 223/288 [02:37<00:32,  2.03it/s]


 78%|███████▊  | 224/288 [02:37<00:27,  2.36it/s]


 78%|███████▊  | 225/288 [02:38<00:47,  1.33it/s]


 78%|███████▊  | 226/288 [02:40<00:55,  1.12it/s]


 79%|███████▉  | 227/288 [02:40<00:42,  1.42it/s]


 80%|███████▉  | 229/288 [02:41<00:43,  1.35it/s]


 80%|███████▉  | 230/288 [02:42<00:36,  1.59it/s]


 80%|████████  | 231/288 [02:42<00:32,  1.77it/s]


 81%|████████  | 232/288 [02:43<00:31,  1.76it/s]


 81%|████████  | 233/288 [02:44<00:40,  1.35it/s]


 81%|████████▏ | 234/288 [02:45<00:44,  1.21it/s]


 82%|████████▏ | 235/288 [02:45<00:37,  1.43it/s]


 82%|████████▏ | 236/288 [02:46<00:35,  1.48it/s]


 82%|████████▏ | 237/288 [02:47<00:32,  1.55it/s]


 83%|████████▎ | 238/288 [02:47<00:32,  1.55it/s]


 83%|████████▎ | 239/288 [02:48<00:28,  1.72it/s]


 83%|████████▎ | 240/288 [02:48<00:26,  1.78it/s]


 84%|████████▎ | 241/288 [02:49<00:33,  1.40it/s]


 84%|████████▍ | 242/288 [02:50<00:34,  1.32it/s]


 84%|████████▍ | 243/288 [02:51<00:32,  1.40it/s]


 85%|████████▍ | 244/288 [02:51<00:26,  1.64it/s]


 85%|████████▌ | 245/288 [02:52<00:26,  1.64it/s]


 85%|████████▌ | 246/288 [02:53<00:29,  1.44it/s]


 86%|████████▌ | 247/288 [02:53<00:22,  1.86it/s]


 86%|████████▌ | 248/288 [02:53<00:21,  1.88it/s]


 86%|████████▋ | 249/288 [02:54<00:29,  1.34it/s]


 87%|████████▋ | 250/288 [02:55<00:24,  1.54it/s]


 87%|████████▋ | 251/288 [02:56<00:26,  1.39it/s]


 88%|████████▊ | 252/288 [02:56<00:19,  1.82it/s]


 88%|████████▊ | 253/288 [02:57<00:21,  1.65it/s]


 88%|████████▊ | 254/288 [02:57<00:22,  1.53it/s]


 89%|████████▉ | 256/288 [02:59<00:20,  1.52it/s]


 89%|████████▉ | 257/288 [03:00<00:22,  1.38it/s]


 90%|████████▉ | 258/288 [03:00<00:19,  1.54it/s]


 90%|████████▉ | 259/288 [03:01<00:21,  1.32it/s]


 90%|█████████ | 260/288 [03:02<00:19,  1.43it/s]


 91%|█████████ | 261/288 [03:02<00:14,  1.86it/s]


 91%|█████████ | 262/288 [03:02<00:13,  1.86it/s]


 91%|█████████▏| 263/288 [03:03<00:14,  1.75it/s]


 92%|█████████▏| 264/288 [03:04<00:17,  1.41it/s]


 92%|█████████▏| 265/288 [03:05<00:16,  1.36it/s]


 92%|█████████▏| 266/288 [03:05<00:13,  1.61it/s]


 93%|█████████▎| 267/288 [03:06<00:15,  1.35it/s]


 93%|█████████▎| 268/288 [03:07<00:13,  1.45it/s]


 94%|█████████▍| 270/288 [03:08<00:09,  1.81it/s]


 94%|█████████▍| 271/288 [03:08<00:08,  1.97it/s]


 94%|█████████▍| 272/288 [03:09<00:10,  1.53it/s]


 95%|█████████▍| 273/288 [03:10<00:10,  1.41it/s]


 95%|█████████▌| 274/288 [03:10<00:07,  1.78it/s]


 95%|█████████▌| 275/288 [03:11<00:09,  1.34it/s]


 96%|█████████▌| 276/288 [03:12<00:07,  1.53it/s]


 97%|█████████▋| 278/288 [03:13<00:05,  1.86it/s]


 97%|█████████▋| 279/288 [03:13<00:05,  1.76it/s]


 97%|█████████▋| 280/288 [03:14<00:05,  1.33it/s]


 98%|█████████▊| 281/288 [03:15<00:04,  1.42it/s]


 98%|█████████▊| 282/288 [03:15<00:03,  1.81it/s]


 98%|█████████▊| 283/288 [03:16<00:03,  1.51it/s]


 99%|█████████▊| 284/288 [03:17<00:02,  1.58it/s]


 99%|█████████▉| 285/288 [03:17<00:01,  1.99it/s]


 99%|█████████▉| 286/288 [03:17<00:00,  2.11it/s]


100%|█████████▉| 287/288 [03:18<00:00,  2.47it/s]


100%|██████████| 288/288 [03:18<00:00,  1.45it/s]
Families:  33%|███▎      | 1/3 [03:18<06:37, 198.68s/it]

Multiplets | family 4:   0%|          | 0/268 [00:00<?, ?it/s]



  0%|          | 0/268 [00:00<?, ?it/s]



  0%|          | 1/268 [00:03<15:41,  3.52s/it]



  1%|          | 2/268 [00:03<06:43,  1.52s/it]



  3%|▎         | 7/268 [00:03<01:20,  3.25it/s]



  4%|▎         | 10/268 [00:07<02:47,  1.54it/s]



  4%|▍         | 12/268 [00:07<02:03,  2.07it/s]



  6%|▌         | 15/268 [00:07<01:20,  3.15it/s]



  6%|▋         | 17/268 [00:10<02:47,  1.50it/s]



  7%|▋         | 19/268 [00:10<02:06,  1.97it/s]



  8%|▊         | 21/268 [00:11<01:39,  2.47it/s]



  9%|▊         | 23/268 [00:11<01:15,  3.26it/s]



  9%|▉         | 25/268 [00:14<02:45,  1.47it/s]



 10%|▉         | 26/268 [00:14<02:22,  1.69it/s]



 10%|█         | 27/268 [00:14<02:04,  1.94it/s]



 10%|█         | 28/268 [00:14<01:42,  2.34it/s]



 11%|█         | 29/268 [00:15<01:25,  2.81it/s]



 12%|█▏        | 31/268 [00:15<01:09,  3.41it/s]



 12%|█▏        | 33/268 [00:18<02:40,  1.46it/s]



 13%|█▎        | 35/268 [00:18<01:56,  2.00it/s]



 13%|█▎        | 36/268 [00:18<01:38,  2.35it/s]



 14%|█▍        | 37/268 [00:18<01:31,  2.54it/s]



 15%|█▍        | 39/268 [00:19<01:11,  3.20it/s]



 15%|█▍        | 40/268 [00:19<01:03,  3.61it/s]



 15%|█▌        | 41/268 [00:21<02:58,  1.27it/s]



 16%|█▌        | 43/268 [00:22<01:56,  1.93it/s]



 16%|█▋        | 44/268 [00:22<01:37,  2.30it/s]



 17%|█▋        | 45/268 [00:22<01:35,  2.35it/s]



 17%|█▋        | 46/268 [00:22<01:20,  2.75it/s]



 18%|█▊        | 47/268 [00:23<01:16,  2.87it/s]



 18%|█▊        | 48/268 [00:23<01:10,  3.14it/s]



 18%|█▊        | 49/268 [00:25<02:58,  1.23it/s]



 19%|█▊        | 50/268 [00:25<02:16,  1.60it/s]



 19%|█▉        | 51/268 [00:25<01:43,  2.09it/s]



 19%|█▉        | 52/268 [00:26<01:38,  2.19it/s]



 20%|█▉        | 53/268 [00:26<01:21,  2.63it/s]



 20%|██        | 54/268 [00:26<01:19,  2.70it/s]



 21%|██        | 55/268 [00:26<01:06,  3.21it/s]



 21%|██        | 56/268 [00:27<01:08,  3.10it/s]



 21%|██▏       | 57/268 [00:29<02:45,  1.28it/s]



 22%|██▏       | 58/268 [00:29<02:11,  1.60it/s]



 22%|██▏       | 59/268 [00:29<01:42,  2.04it/s]



 22%|██▏       | 60/268 [00:30<01:50,  1.88it/s]



 23%|██▎       | 62/268 [00:31<01:44,  1.98it/s]



 24%|██▍       | 64/268 [00:31<01:07,  3.03it/s]



 24%|██▍       | 65/268 [00:32<01:55,  1.76it/s]



 25%|██▍       | 66/268 [00:33<01:48,  1.86it/s]



 25%|██▌       | 67/268 [00:33<01:43,  1.95it/s]



 25%|██▌       | 68/268 [00:33<01:31,  2.19it/s]



 26%|██▌       | 69/268 [00:34<01:27,  2.29it/s]



 26%|██▌       | 70/268 [00:34<01:38,  2.01it/s]



 26%|██▋       | 71/268 [00:34<01:17,  2.55it/s]



 27%|██▋       | 72/268 [00:35<01:05,  2.97it/s]



 27%|██▋       | 73/268 [00:36<01:51,  1.75it/s]



 28%|██▊       | 74/268 [00:36<01:39,  1.95it/s]



 28%|██▊       | 75/268 [00:37<01:34,  2.04it/s]



 28%|██▊       | 76/268 [00:37<01:26,  2.23it/s]



 29%|██▊       | 77/268 [00:37<01:20,  2.38it/s]



 29%|██▉       | 78/268 [00:38<01:36,  1.96it/s]



 29%|██▉       | 79/268 [00:38<01:15,  2.51it/s]



 30%|██▉       | 80/268 [00:38<01:05,  2.87it/s]



 30%|███       | 81/268 [00:39<01:39,  1.88it/s]



 31%|███       | 82/268 [00:40<01:37,  1.91it/s]



 31%|███       | 83/268 [00:40<01:36,  1.93it/s]



 31%|███▏      | 84/268 [00:41<01:21,  2.25it/s]



 32%|███▏      | 85/268 [00:41<01:15,  2.42it/s]



 32%|███▏      | 86/268 [00:42<01:34,  1.93it/s]



 32%|███▏      | 87/268 [00:42<01:22,  2.21it/s]



 33%|███▎      | 89/268 [00:43<01:23,  2.14it/s]



 34%|███▎      | 90/268 [00:43<01:22,  2.15it/s]



 34%|███▍      | 91/268 [00:44<01:46,  1.65it/s]



 34%|███▍      | 92/268 [00:45<01:24,  2.09it/s]



 35%|███▍      | 93/268 [00:45<01:16,  2.28it/s]



 35%|███▌      | 94/268 [00:45<01:17,  2.25it/s]



 35%|███▌      | 95/268 [00:46<01:09,  2.51it/s]



 36%|███▌      | 96/268 [00:46<01:07,  2.56it/s]



 36%|███▌      | 97/268 [00:47<01:37,  1.76it/s]



 37%|███▋      | 98/268 [00:48<01:37,  1.75it/s]



 37%|███▋      | 99/268 [00:48<01:39,  1.70it/s]



 37%|███▋      | 100/268 [00:49<01:24,  1.99it/s]



 38%|███▊      | 101/268 [00:49<01:07,  2.48it/s]



 38%|███▊      | 102/268 [00:49<01:07,  2.46it/s]



 38%|███▊      | 103/268 [00:49<00:59,  2.79it/s]



 39%|███▉      | 104/268 [00:50<01:07,  2.44it/s]



 39%|███▉      | 105/268 [00:51<01:23,  1.95it/s]



 40%|███▉      | 106/268 [00:51<01:22,  1.97it/s]



 40%|███▉      | 107/268 [00:52<01:38,  1.63it/s]



 40%|████      | 108/268 [00:52<01:24,  1.89it/s]



 41%|████      | 109/268 [00:52<01:03,  2.50it/s]



 41%|████      | 110/268 [00:53<01:00,  2.62it/s]



 41%|████▏     | 111/268 [00:53<00:56,  2.78it/s]



 42%|████▏     | 112/268 [00:54<01:01,  2.55it/s]



 42%|████▏     | 113/268 [00:54<01:15,  2.06it/s]



 43%|████▎     | 114/268 [00:55<01:16,  2.00it/s]



 43%|████▎     | 115/268 [00:56<01:35,  1.61it/s]



 43%|████▎     | 116/268 [00:56<01:18,  1.93it/s]



 44%|████▍     | 118/268 [00:56<00:56,  2.66it/s]



 44%|████▍     | 119/268 [00:57<00:57,  2.61it/s]



 45%|████▍     | 120/268 [00:57<00:58,  2.52it/s]



 45%|████▌     | 121/268 [00:58<01:09,  2.13it/s]



 46%|████▌     | 122/268 [00:59<01:14,  1.96it/s]



 46%|████▌     | 123/268 [01:00<01:39,  1.46it/s]



 47%|████▋     | 125/268 [01:00<01:13,  1.95it/s]



 47%|████▋     | 126/268 [01:00<01:03,  2.23it/s]



 48%|████▊     | 128/268 [01:01<00:46,  3.00it/s]



 48%|████▊     | 129/268 [01:02<01:09,  2.00it/s]



 49%|████▊     | 130/268 [01:03<01:13,  1.87it/s]



 49%|████▉     | 131/268 [01:03<01:24,  1.62it/s]



 50%|████▉     | 133/268 [01:04<01:05,  2.06it/s]



 50%|█████     | 134/268 [01:04<00:58,  2.30it/s]



 50%|█████     | 135/268 [01:04<00:47,  2.81it/s]



 51%|█████     | 137/268 [01:06<00:58,  2.22it/s]



 51%|█████▏    | 138/268 [01:06<01:06,  1.94it/s]



 52%|█████▏    | 139/268 [01:07<01:17,  1.66it/s]



 52%|█████▏    | 140/268 [01:07<01:01,  2.10it/s]



 53%|█████▎    | 141/268 [01:08<00:56,  2.25it/s]



 53%|█████▎    | 142/268 [01:08<00:52,  2.39it/s]



 53%|█████▎    | 143/268 [01:08<00:42,  2.94it/s]



 54%|█████▍    | 145/268 [01:09<00:49,  2.49it/s]



 54%|█████▍    | 146/268 [01:10<01:02,  1.94it/s]



 55%|█████▍    | 147/268 [01:11<01:12,  1.66it/s]



 55%|█████▌    | 148/268 [01:11<01:05,  1.83it/s]



 56%|█████▌    | 149/268 [01:11<00:50,  2.34it/s]



 56%|█████▌    | 150/268 [01:12<00:46,  2.53it/s]



 56%|█████▋    | 151/268 [01:12<00:42,  2.78it/s]



 57%|█████▋    | 152/268 [01:12<00:33,  3.44it/s]



 57%|█████▋    | 153/268 [01:13<00:46,  2.45it/s]

 57%|█████▋    | 154/268 [01:14<01:03,  1.80it/s]



 58%|█████▊    | 155/268 [01:14<01:11,  1.57it/s]



 58%|█████▊    | 156/268 [01:15<01:07,  1.65it/s]



 59%|█████▊    | 157/268 [01:15<00:54,  2.02it/s]



 59%|█████▉    | 158/268 [01:15<00:43,  2.52it/s]



 59%|█████▉    | 159/268 [01:16<00:39,  2.75it/s]



 60%|█████▉    | 160/268 [01:16<00:31,  3.43it/s]



 60%|██████    | 161/268 [01:16<00:41,  2.55it/s]



 60%|██████    | 162/268 [01:18<01:03,  1.66it/s]



 61%|██████    | 163/268 [01:19<01:18,  1.34it/s]



 61%|██████    | 164/268 [01:19<01:06,  1.57it/s]



 62%|██████▏   | 165/268 [01:19<00:51,  1.98it/s]



 62%|██████▏   | 166/268 [01:19<00:40,  2.49it/s]



 62%|██████▏   | 167/268 [01:20<00:48,  2.09it/s]



 63%|██████▎   | 169/268 [01:21<00:40,  2.47it/s]



 63%|██████▎   | 170/268 [01:22<00:58,  1.68it/s]



 64%|██████▍   | 171/268 [01:23<01:06,  1.46it/s]



 64%|██████▍   | 172/268 [01:23<01:04,  1.48it/s]



 65%|██████▍   | 174/268 [01:24<00:44,  2.10it/s]



 65%|██████▌   | 175/268 [01:24<00:40,  2.32it/s]



 66%|██████▌   | 176/268 [01:24<00:36,  2.53it/s]



 66%|██████▌   | 177/268 [01:25<00:37,  2.45it/s]



 66%|██████▋   | 178/268 [01:26<00:56,  1.61it/s]



 67%|██████▋   | 179/268 [01:27<00:58,  1.53it/s]



 67%|██████▋   | 180/268 [01:27<00:55,  1.59it/s]



 68%|██████▊   | 182/268 [01:28<00:37,  2.32it/s]



 68%|██████▊   | 183/268 [01:28<00:36,  2.35it/s]



 69%|██████▊   | 184/268 [01:28<00:29,  2.82it/s]



 69%|██████▉   | 185/268 [01:29<00:31,  2.63it/s]



 69%|██████▉   | 186/268 [01:30<00:48,  1.71it/s]



 70%|██████▉   | 187/268 [01:31<00:50,  1.61it/s]



 70%|███████   | 188/268 [01:31<00:54,  1.47it/s]



 71%|███████   | 189/268 [01:32<00:46,  1.69it/s]



 71%|███████   | 190/268 [01:32<00:40,  1.94it/s]



 72%|███████▏  | 192/268 [01:32<00:24,  3.14it/s]



 72%|███████▏  | 193/268 [01:33<00:31,  2.41it/s]



 72%|███████▏  | 194/268 [01:34<00:37,  1.99it/s]



 73%|███████▎  | 195/268 [01:35<00:54,  1.34it/s]



 73%|███████▎  | 196/268 [01:36<00:51,  1.39it/s]



 74%|███████▎  | 197/268 [01:36<00:42,  1.66it/s]



 74%|███████▍  | 198/268 [01:36<00:32,  2.18it/s]



 74%|███████▍  | 199/268 [01:36<00:24,  2.81it/s]



 75%|███████▍  | 200/268 [01:37<00:26,  2.61it/s]



 75%|███████▌  | 201/268 [01:37<00:22,  3.01it/s]



 75%|███████▌  | 202/268 [01:38<00:28,  2.31it/s]



 76%|███████▌  | 203/268 [01:39<00:53,  1.21it/s]



 76%|███████▌  | 204/268 [01:40<00:45,  1.41it/s]



 76%|███████▋  | 205/268 [01:40<00:37,  1.69it/s]



 77%|███████▋  | 206/268 [01:40<00:29,  2.13it/s]



 78%|███████▊  | 208/268 [01:41<00:23,  2.54it/s]



 78%|███████▊  | 210/268 [01:42<00:21,  2.67it/s]



 79%|███████▊  | 211/268 [01:43<00:37,  1.54it/s]



 79%|███████▉  | 212/268 [01:44<00:33,  1.65it/s]



 79%|███████▉  | 213/268 [01:44<00:29,  1.88it/s]



 80%|███████▉  | 214/268 [01:44<00:23,  2.32it/s]



 81%|████████  | 216/268 [01:45<00:20,  2.59it/s]



 81%|████████▏ | 218/268 [01:45<00:18,  2.76it/s]



 82%|████████▏ | 219/268 [01:47<00:32,  1.51it/s]



 82%|████████▏ | 220/268 [01:48<00:29,  1.63it/s]



 82%|████████▏ | 221/268 [01:48<00:27,  1.72it/s]



 83%|████████▎ | 223/268 [01:48<00:18,  2.46it/s]



 84%|████████▎ | 224/268 [01:49<00:18,  2.44it/s]



 84%|████████▍ | 226/268 [01:50<00:16,  2.53it/s]



 85%|████████▍ | 227/268 [01:51<00:26,  1.53it/s]



 85%|████████▌ | 228/268 [01:52<00:23,  1.67it/s]



 85%|████████▌ | 229/268 [01:52<00:21,  1.78it/s]



 86%|████████▌ | 230/268 [01:52<00:19,  1.99it/s]



 86%|████████▌ | 231/268 [01:53<00:15,  2.32it/s]



 87%|████████▋ | 232/268 [01:53<00:12,  2.95it/s]



 87%|████████▋ | 234/268 [01:54<00:12,  2.77it/s]



 88%|████████▊ | 235/268 [01:55<00:20,  1.59it/s]



 88%|████████▊ | 236/268 [01:56<00:21,  1.50it/s]



 89%|████████▉ | 238/268 [01:56<00:14,  2.00it/s]



 89%|████████▉ | 239/268 [01:57<00:14,  2.05it/s]



 90%|████████▉ | 240/268 [01:57<00:11,  2.49it/s]



 90%|█████████ | 242/268 [01:57<00:08,  2.95it/s]



 91%|█████████ | 243/268 [01:59<00:15,  1.65it/s]



 91%|█████████ | 244/268 [02:00<00:15,  1.57it/s]



 92%|█████████▏| 246/268 [02:00<00:10,  2.05it/s]



 92%|█████████▏| 247/268 [02:01<00:10,  2.10it/s]



 93%|█████████▎| 249/268 [02:01<00:06,  3.05it/s]



 93%|█████████▎| 250/268 [02:01<00:06,  2.98it/s]



 94%|█████████▎| 251/268 [02:03<00:10,  1.59it/s]



 94%|█████████▍| 252/268 [02:04<00:10,  1.46it/s]



 95%|█████████▍| 254/268 [02:04<00:07,  1.96it/s]



 95%|█████████▌| 255/268 [02:05<00:06,  2.03it/s]



 96%|█████████▌| 257/268 [02:05<00:03,  2.79it/s]



 96%|█████████▋| 258/268 [02:05<00:03,  2.79it/s]



 97%|█████████▋| 259/268 [02:07<00:06,  1.44it/s]



 97%|█████████▋| 260/268 [02:08<00:05,  1.47it/s]



 97%|█████████▋| 261/268 [02:08<00:03,  1.78it/s]



 98%|█████████▊| 262/268 [02:08<00:03,  1.81it/s]



 98%|█████████▊| 263/268 [02:09<00:02,  2.33it/s]



 99%|█████████▉| 265/268 [02:09<00:01,  2.85it/s]



 99%|█████████▉| 266/268 [02:09<00:00,  3.29it/s]



100%|█████████▉| 267/268 [02:10<00:00,  2.12it/s]



100%|██████████| 268/268 [02:10<00:00,  2.05it/s]
Families:  67%|██████▋   | 2/3 [05:29<02:38, 158.87s/it]



Multiplets | family 3:   0%|          | 0/3 [00:00<?, ?it/s]





  0%|          | 0/3 [00:00<?, ?it/s]





100%|██████████| 3/3 [00:01<00:00,  1.92it/s]
Families: 100%|██████████| 3/3 [05:31<00:00, 110.42s/it]

Runtime: 331.257738 s

In [68]:
for diagnosis, diag_data in selected_boot_stats.items():
    for order, mults in diag_data.items():
        for mult, distro in mults.items():
            selected_boot_stats[diagnosis][order][mult] = {
                'observed_O' : o_infoptim.o_information(EDI_diags[diagnosis][list(mult)]),
                'samp_distro' : distro
            }

Multiplets | family 3:   0%|          | 0/3 [00:01<?, ?it/s]
Multiplets | family 5:   0%|          | 0/288 [05:35<?, ?it/s]
Multiplets | family 4:   0%|          | 0/268 [02:16<?, ?it/s]

In [69]:
bca_final = {}
for diagnosis, mult_scales in selected_boot_stats.items():
    start = time.perf_counter()
    # structure: order: multiple: samp_distro
    bca_final[diagnosis] = bca_bootopt.bca_bootstrap_parallel(multiplets_dict=mult_scales, 
                                                                            X=EDI_diags[diagnosis])
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 52 multiplets
  [BCa | family 5] 52/52 multiplets (100%)

[BCa | family 4] starting – 530 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  9.34it/s]

  [BCa | family 4] 530/530 multiplets (100%)

[BCa | family 3] starting – 21 multiplets
  [BCa | family 3] 21/21 multiplets (100%)
Runtime: 0.321626 s

Families:  33%|███▎      | 1/3 [00:00<00:00,  6.49it/s]

[BCa | family 5] starting – 331 multiplets
  [BCa | family 5] 331/331 multiplets (100%)

[BCa | family 4] starting – 471 multiplets

Families:  67%|██████▋   | 2/3 [00:00<00:00,  5.92it/s]

  [BCa | family 4] 471/471 multiplets (100%)

[BCa | family 3] starting – 20 multiplets
  [BCa | family 3] 20/20 multiplets (100%)

Families: 100%|██████████| 3/3 [00:00<00:00,  8.39it/s]

Runtime: 0.356930 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 5] starting – 41 multiplets
  [BCa | family 5] 41/41 multiplets (100%)

[BCa | family 4] starting – 474 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00, 10.89it/s]

  [BCa | family 4] 474/474 multiplets (100%)

[BCa | family 3] starting – 55 multiplets
  [BCa | family 3] 55/55 multiplets (100%)
Runtime: 0.277762 s

Families:  33%|███▎      | 1/3 [00:00<00:00,  7.84it/s]

[BCa | family 5] starting – 288 multiplets
  [BCa | family 5] 288/288 multiplets (100%)

[BCa | family 4] starting – 268 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00, 10.80it/s]

  [BCa | family 4] 268/268 multiplets (100%)

[BCa | family 3] starting – 3 multiplets
  [BCa | family 3] 3/3 multiplets (100%)
Runtime: 0.281130 s

#### Hierarchical Pruning: actually filtering out the overlapping multiplets

In [70]:
filtered_D = {} 
discarded_D = {}
for diagnose, orders in bca_final.items():
    filtered, discarded = sel.select_multiplets_minimal(orders)
    filtered_D[diagnose] = filtered
    discarded_D[diagnose] = discarded

### POLY - FINAL STEP ( $\Omega$ - DF)

In [71]:
sel_finale = {}
for diagnosis, sel_mults in filtered_D.items():
    sel_finale[diagnosis] = pp_bootopt.compute_omega_for_multiplets(multiplets_dict=sel_mults, 
                                                                                   X=EDI_diags[diagnosis])
    ap = sel_finale[diagnosis]
    sel_finale[diagnosis]["label"] = np.where(ap["omega"] < 0, "synergy", "redundancy")

In [72]:
sel_finale['ANR'].head()

   order       label     omega  node1  node2  node3  node4  node5
0      3  redundancy  0.135900      2      7     16   <NA>   <NA>
1      3  redundancy  0.185974      2      9     32   <NA>   <NA>
2      3  redundancy  0.207371      2     16     32   <NA>   <NA>
3      3  redundancy  0.166395      2     32     49   <NA>   <NA>
4      3  redundancy  0.178320      7      9     32   <NA>   <NA>

In [73]:
# skip dir creation if it already exist
out_dir_sm = "selected_he_POLY"            
os.makedirs(out_dir_sm, exist_ok=True)

for diagnosis, df in sel_finale.items():
    fname = f"{diagnosis}_selected_he_POLY.csv"
    fpath = os.path.join(out_dir_sm, fname)
    df.to_csv(fpath, index=False)
# then move the files to DATA/selected_HYPEREDGES_data/POLY folder.

### Partition and Multiplex Construction 

**After all three validation stages:**

**Partition by sign:**
   - **Redundant hyperedges:** Ω > 0 (positive layer)
   - **Synergistic hyperedges:** Ω < 0 (negative layer)
   
**Final Output:** 
- Conservative set of statistically significant, stable, and genuinely higher-order multiplets