# Diagnosis multiplex hyperedges selection: intra/inter sub-scales

In [1]:
import os
import sys
import pandas as pd
import numpy as np
import time
from pathlib import Path
import pickle
import networkx as nx
from itertools import chain

In [85]:
# get parent directory
parent_dir = os.path.abspath("..")
sys.path.append(parent_dir)

import optim_help.utilities as ut

import optim_help.O_Information as o_infoptim
import optim_help.paral_perm_bootstrap as pp_bootopt
import optim_help.BCa_bootstrap as bca_bootopt
import optim_help.mult_sel_minimal as sel

import optim_help.plots.o_info_bootstrap_plots as o_plots
import optim_help.plots.BCa_plots as bca_plots

### Import data

In [3]:
data_path = '../../DATA/EDI_DIAG' # contains csv files for each diagnoses
EDI_diags_paths = [
    data_path + '/' + f
    for f in os.listdir(data_path)
    if f.lower().endswith('.csv') and os.path.isfile(os.path.join(data_path, f))
]

EDI_diags = {}
for path in EDI_diags_paths:
    EDI_diags[Path(path).stem] = ut.preproc_df(path)
    
print(EDI_diags.keys())

dict_keys(['ANBP', 'ANR', 'BED_OSFED', 'BN'])

In [4]:
EDI_diags['ANBP'].describe(include='all')

,1,2,3,4,5,6,7,8,9,10,...,82,83,84,85,86,87,88,89,90,91
count,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,...,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000
mean,2.683398,2.598456,1.474903,1.366795,1.254826,1.135135,2.683398,2.073359,2.447876,2.223938,...,1.243243,1.791506,2.274131,2.003861,2.030888,2.054054,1.046332,0.984556,0.911197,2.559846
std,1.291052,1.403538,1.460841,1.381150,1.376972,1.386913,1.452128,1.480632,1.606728,1.387949,...,1.317261,1.376352,1.394253,1.339611,1.465036,1.262524,1.190147,1.181147,1.246635,1.200488
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.500000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000
50%,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,3.000000,2.000000,...,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,3.000000
75%,4.000000,4.000000,3.000000,3.000000,2.000000,2.000000,4.000000,3.000000,4.000000,4.000000,...,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,3.000000
max,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

### Import sub_scales data and get candidate multiplets

In [5]:
sub_scales_path = '../../DATA/EDI_det/sub_scales.csv' 
sub_scales = pd.read_csv(sub_scales_path)[['item', 'scales']]

In [6]:
scales_df_dict = {name: group for name, group in sub_scales.groupby("scales")}
items_by_scale = sub_scales.groupby("scales")["item"].apply(list).to_dict()
del items_by_scale['-']

In [7]:
items_by_scale

{'A': [66, 68, 75, 78, 82, 86, 88],
 'B': [4, 5, 28, 38, 46, 53, 61, 64],
 'BD': [2, 9, 12, 19, 31, 45, 47, 55, 59, 62],
 'DT': [1, 7, 11, 16, 25, 32, 49],
 'ED': [67, 70, 72, 79, 81, 83, 85, 90],
 'IA': [17, 30, 54, 65, 74, 76, 80, 89],
 'ID': [8, 21, 26, 33, 40, 44, 51, 60, 77],
 'II': [15, 23, 34, 57, 69, 73, 87],
 'LSE': [10, 27, 37, 41, 42, 50],
 'MF': [3, 6, 14, 22, 35, 39, 48, 58],
 'P': [13, 29, 36, 43, 52, 63],
 'PA': [18, 20, 24, 56, 84, 91]}

In [8]:
all_sub_scales = items_by_scale.copy()  
all_sub_scales['-'] = [71]

In [9]:
all_sub_scales

{'A': [66, 68, 75, 78, 82, 86, 88],
 'B': [4, 5, 28, 38, 46, 53, 61, 64],
 'BD': [2, 9, 12, 19, 31, 45, 47, 55, 59, 62],
 'DT': [1, 7, 11, 16, 25, 32, 49],
 'ED': [67, 70, 72, 79, 81, 83, 85, 90],
 'IA': [17, 30, 54, 65, 74, 76, 80, 89],
 'ID': [8, 21, 26, 33, 40, 44, 51, 60, 77],
 'II': [15, 23, 34, 57, 69, 73, 87],
 'LSE': [10, 27, 37, 41, 42, 50],
 'MF': [3, 6, 14, 22, 35, 39, 48, 58],
 'P': [13, 29, 36, 43, 52, 63],
 'PA': [18, 20, 24, 56, 84, 91],
 '-': [71]}

#### Use the general graph - not diagnosis based, to check links and select inter scales multiplets.

In [10]:
# GRAPHS -------------------------------------------------
graph_data_path = '../../DATA/network_ALL_article.graphml'

G_all = nx.read_graphml(graph_data_path)
# rename the nodes to have the item index as name
mapping = {name: str(int(name.replace("n", "")) + 1) for name in G_all.nodes()}
G_all = nx.relabel_nodes(G_all, mapping)

#### Get all combination multiplets - order: 3, 4, 5

In [11]:
intra_candidate = ut.all_mults_combinations(items_by_scale) # ALL intra combinations

two_inter_candidate = ut.two_interscale_mults_combinations_G_k(all_sub_scales, G_all)
#order_inter_candidate = ut.order_interscale_mults_combinations_G(all_sub_scales, G_all)
# this takes some minutes

In [12]:
total = 0
for couple, results in two_inter_candidate.items():
    for order, combos in results.items():
        total += len(combos)
print(total)

#for couple, results in order_inter_candidate.items():
#    for order, combos in results.items():
#        total += len(combos)
#print(total)

115722

In [13]:
#inter_candidates = {}
#for order in (3,4,5):
#    two_inter = two_inter_candidate[order].values()
#    order_inter = order_inter_candidate[order].values()
#    inter_candidates[order] = list(chain.from_iterable(two_inter)) + list(chain.from_iterable(order_inter))

#inter_multiplets = ut.multiplets_to_df(inter_candidates)

In [14]:
inter_multiplets = ut.multiplets_to_df(two_inter_candidate)

In [15]:
inter_candidate_F = {}
inter_candidate_omega_F = {}
for diagnosis, data in EDI_diags.items():
    start = time.perf_counter()
    inter_candidate_F[diagnosis], inter_candidate_omega_F[diagnosis] = pp_bootopt.filter_multiplets_by_omega(multiplets_dict = inter_multiplets,
                                                                             X = EDI_diags[diagnosis],
                                                                             threshold=0.1)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Runtime: 274.523096 s
Runtime: 314.894484 s
Runtime: 237.837107 s
Runtime: 353.171676 s

In [58]:
def get_perc(order):
    if order == 3:
        return 0.10
    if order == 4:
        return 0.05
    else:
        return 0.01
    
inter_candidate_FF = {}
for diag, order_df in inter_candidate_omega_F.items():
    print('Diagnosis:', diag)
    inter_candidate_FF[diag] = {}
    for order, df in order_df.items():
        perc = get_perc(order)
        
        df_pos = df[df["omega"] > 0].reset_index(drop=True)
        df_neg = df[df["omega"] < 0].reset_index(drop=True)
        print(f"Order {order}, Positive: {len(df_pos)}, Negative: {len(df_neg)}")
        
        top_pos = df_pos.head(max(1, int(np.ceil(perc * len(df_pos)))))
        top_neg = df_neg.head(max(1, int(np.ceil(perc * len(df_neg)))))
        print(f"Order {order}, Positive: {len(top_pos)}, Negative: {len(top_neg)}")
        
        inter_candidate_FF[diag][order] = pd.concat([top_pos.drop(columns="omega"),
                               top_neg.drop(columns="omega"),],ignore_index=True,)
        print(f"Order {order}, Total: {len(inter_candidate_FF[diag][order])}")
    print('\n')

Diagnosis: ANBP
Order 3, Positive: 1, Negative: 736
Order 3, Positive: 1, Negative: 74
Order 3, Total: 75
Order 4, Positive: 5, Negative: 15625
Order 4, Positive: 1, Negative: 782
Order 4, Total: 783
Order 5, Positive: 71, Negative: 98329
Order 5, Positive: 1, Negative: 984
Order 5, Total: 985


Diagnosis: ANR
Order 3, Positive: 20, Negative: 279
Order 3, Positive: 2, Negative: 28
Order 3, Total: 30
Order 4, Positive: 55, Negative: 15105
Order 4, Positive: 3, Negative: 756
Order 4, Total: 759
Order 5, Positive: 176, Negative: 97270
Order 5, Positive: 2, Negative: 973
Order 5, Total: 975


Diagnosis: BED_OSFED
Order 3, Positive: 0, Negative: 864
Order 3, Positive: 0, Negative: 87
Order 3, Total: 87
Order 4, Positive: 38, Negative: 15163
Order 4, Positive: 2, Negative: 759
Order 4, Total: 761
Order 5, Positive: 3352, Negative: 90411
Order 5, Positive: 34, Negative: 905
Order 5, Total: 939


Diagnosis: BN
Order 3, Positive: 0, Negative: 319
Order 3, Positive: 0, Negative: 32
Order 3, Total: 32
Order 4, Positive: 0, Negative: 15623
Order 4, Positive: 0, Negative: 782
Order 4, Total: 782
Order 5, Positive: 61, Negative: 98410
Order 5, Positive: 1, Negative: 985
Order 5, Total: 986

In [59]:
inter_candidate_FF['BN'][5]

     node1  node2  node3  node4  node5
0        9     45     55     62     32
1       15     73     87     43     63
2       57     73     87     43     63
3       40     44     77     43     52
4       21     40     44     43     63
..     ...    ...    ...    ...    ...
981     54     74     15     69     87
982      8     40     51     77     73
983      5     61     33     40     77
984     65     74     76     43     63
985      4     46     67     70     83

[986 rows x 5 columns]

In [60]:
for diag in inter_candidate_FF:
    tot = 0
    for order in inter_candidate_FF[diag]:
        tot += len(inter_candidate_FF[diag][order])
        print_ = diag + ', ' + str(order) + ':' + str(len(inter_candidate_FF[diag][order]))
    print(diag + ', TOTAL is', str(tot))

ANBP, TOTAL is 1843
ANR, TOTAL is 1764
BED_OSFED, TOTAL is 1787
BN, TOTAL is 1800

In [66]:
intra_candidate_df = {}
for scale, mult_cand in intra_candidate.items():
    intra_candidate_df[scale] = {k: pd.DataFrame(v, columns=[f"node{i+1}" for i in range(k)]) for k, v in mult_cand.items()}

Convert structure of INTRA by merging DFs of same order:
    intra[scale][order] = DF ----> intra[order] = DF

In [69]:
intra_DFs = {}

for order in (3,4,5):
    intra_DFs[order] = pd.concat(
        [scale_dict[order] for scale_dict in intra_candidate_df.values()],
        ignore_index=True,
    )
    print(len(intra_DFs[order]))

593
766
683

In [70]:
intra_DFs[3].head()

   node1  node2  node3
0     66     68     75
1     66     68     78
2     66     68     82
3     66     68     86
4     66     68     88

#### Merge INTRA + INTER

In [71]:
multiplets_diag = {}
for diagnosis, inter_data in inter_candidate_FF.items():
    multiplets_diag[diagnosis] = {}
    for order, inter in inter_data.items():
        multiplets_diag[diagnosis][order] = pd.concat([intra_DFs[order],
                                      inter_candidate_FF[diagnosis][order]], ignore_index=True,)

In [80]:
multiplets_diag['BN'][3].head()

   node1  node2  node3
0     66     68     75
1     66     68     78
2     66     68     82
3     66     68     86
4     66     68     88

### Compute $\Omega$-information and perform the permutation test to select the multiplets

In [74]:
n_boot_perm = 1000 # before: 400

In [81]:
out_dir = "perm_boot_SCALES"            
os.makedirs(out_dir, exist_ok=True)

perm_boot_diag_scale = {}
for diagnosis in EDI_diags:
    start = time.perf_counter()
    
    perm_boot_diag_scale[diagnosis] = pp_bootopt.perm_bootstrap_parallel(multiplets_dict=multiplets_diag[diagnosis],
                                                                        X=EDI_diags[diagnosis], 
                                                                        n_boot=n_boot_perm)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")
    
    fname = f"{diagnosis}_perm_scales.pkl"
    fpath = os.path.join(out_dir, fname)
    with open(fpath, "wb") as f:
        pickle.dump(perm_boot_diag_scale[diagnosis], f, protocol=pickle.HIGHEST_PROTOCOL)

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=3:   0%|0/668 |          | 00:00

  Multiplets | order=3:  25%|167/668 |██▌       | 00:48

  Multiplets | order=3:  50%|334/668 |█████     | 01:33

  Multiplets | order=3:  75%|501/668 |███████▌  | 02:20

  Multiplets | order=3: 100%|668/668 |██████████| 03:07

Families:  33%|███▎      | 1/3 [03:07<06:14, 187.32s/it][A

  Multiplets | order=4:   0%|0/1549 |          | 00:00

  Multiplets | order=4:  25%|388/1549 |██▌       | 02:39

  Multiplets | order=4:  50%|776/1549 |█████     | 05:20

  Multiplets | order=4:  75%|1164/1549 |███████▌  | 08:02

  Multiplets | order=4: 100%|1549/1549 |██████████| 10:40

Families:  67%|██████▋   | 2/3 [13:48<07:34, 454.07s/it]

  Multiplets | order=5:   0%|0/1668 |          | 00:00

  Multiplets | order=5:  25%|417/1668 |██▌       | 03:45

  Multiplets | order=5:  50%|834/1668 |█████     | 07:28

  Multiplets | order=5:  75%|1251/1668 |███████▌  | 11:11

  Multiplets | order=5: 100%|1668/1668 |██████████| 14:55

Runtime: 1723.289139 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=3:   0%|0/623 |          | 00:00

  Multiplets | order=3:  25%|156/623 |██▌       | 00:52

  Multiplets | order=3:  50%|312/623 |█████     | 01:48

  Multiplets | order=3:  75%|468/623 |███████▌  | 02:45

  Multiplets | order=3: 100%|623/623 |██████████| 03:40

Families:  33%|███▎      | 1/3 [03:40<07:21, 220.57s/it][A

  Multiplets | order=4:   0%|0/1525 |          | 00:00

  Multiplets | order=4:  25%|382/1525 |██▌       | 03:08

  Multiplets | order=4:  50%|764/1525 |█████     | 06:20

  Multiplets | order=4:  75%|1146/1525 |███████▌  | 09:32

  Multiplets | order=4: 100%|1525/1525 |██████████| 12:41

Families:  67%|██████▋   | 2/3 [16:22<08:58, 538.81s/it]

  Multiplets | order=5:   0%|0/1658 |          | 00:00

  Multiplets | order=5:  25%|415/1658 |██▌       | 04:35

  Multiplets | order=5:  50%|830/1658 |█████     | 09:15

  Multiplets | order=5:  75%|1245/1658 |███████▌  | 13:54

  Multiplets | order=5: 100%|1658/1658 |██████████| 18:31

Runtime: 2093.638107 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=3:   0%|0/680 |          | 00:00

  Multiplets | order=3:  25%|170/680 |██▌       | 00:41

  Multiplets | order=3:  50%|340/680 |█████     | 01:22

  Multiplets | order=3:  75%|510/680 |███████▌  | 02:05

  Multiplets | order=3: 100%|680/680 |██████████| 02:47

Families:  33%|███▎      | 1/3 [02:47<05:35, 167.52s/it][A

  Multiplets | order=4:   0%|0/1527 |          | 00:00

  Multiplets | order=4:  25%|382/1527 |██▌       | 02:11

  Multiplets | order=4:  50%|764/1527 |█████     | 04:27

  Multiplets | order=4:  75%|1146/1527 |███████▌  | 06:42

  Multiplets | order=4: 100%|1527/1527 |██████████| 08:57

Families:  67%|██████▋   | 2/3 [11:44<06:24, 384.91s/it]

  Multiplets | order=5:   0%|0/1622 |          | 00:00

  Multiplets | order=5:  25%|406/1622 |██▌       | 03:08

  Multiplets | order=5:  50%|812/1622 |█████     | 06:13

  Multiplets | order=5:  75%|1218/1622 |███████▌  | 09:20

  Multiplets | order=5: 100%|1622/1622 |██████████| 12:34

Runtime: 1459.213836 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

  Multiplets | order=3:   0%|0/625 |          | 00:00

  Multiplets | order=3:  25%|157/625 |██▌       | 01:01

  Multiplets | order=3:  50%|314/625 |█████     | 02:02

  Multiplets | order=3:  75%|471/625 |███████▌  | 03:04

  Multiplets | order=3: 100%|625/625 |██████████| 04:04

Families:  33%|███▎      | 1/3 [04:04<08:08, 244.49s/it][A

  Multiplets | order=4:   0%|0/1548 |          | 00:00

  Multiplets | order=4:  25%|387/1548 |██▌       | 03:45

  Multiplets | order=4:  50%|774/1548 |█████     | 07:30

  Multiplets | order=4:  75%|1161/1548 |███████▌  | 11:17

  Multiplets | order=4: 100%|1548/1548 |██████████| 15:04

Families:  67%|██████▋   | 2/3 [19:08<10:32, 632.51s/it]

  Multiplets | order=5:   0%|0/1669 |          | 00:00

  Multiplets | order=5:  25%|418/1669 |██▌       | 05:26

  Multiplets | order=5:  50%|836/1669 |█████     | 10:46

  Multiplets | order=5:  75%|1254/1669 |███████▌  | 16:08

  Multiplets | order=5: 100%|1669/1669 |██████████| 21:29

Runtime: 2438.357294 s

Load pickle files.

In [82]:
# Load
with open("perm_boot_SCALES/ANBP_perm_scales.pkl", "rb") as f:
    ANBP_perm_scales = pickle.load(f)

with open("perm_boot_SCALES/ANR_perm_scales.pkl", "rb") as f:
    ANR_perm_scales = pickle.load(f)

with open("perm_boot_SCALES/BED_OSFED_perm_scales.pkl", "rb") as f:
    BED_OSFED_perm_scales = pickle.load(f)

with open("perm_boot_SCALES/BN_perm_scales.pkl", "rb") as f:
    BN_perm_scales = pickle.load(f)

# rebuild general dictionary
perm_diags_scales = {
    'ANBP' : ANBP_perm_scales,
    'ANR' : ANR_perm_scales,
    'BED_OSFED' : BED_OSFED_perm_scales,
    'BN' : BN_perm_scales
}

In [83]:
len(perm_diags_scales['ANBP'][5])

1668

In [86]:
base = 'SCALES_part1_plots/'
perm_summary_tables = {}
for diag, out in perm_diags_scales.items():
    perm_summary_tables[diag] = o_plots.save_all_figures(out, output_dir=base + diag + "_figures")

Saved -> SCALES_part1_plots/ANBP_figures\fig1_null_distributions.pdf
Saved -> SCALES_part1_plots/ANBP_figures\fig2_omega_scatter.pdf
Saved -> SCALES_part1_plots/ANBP_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")

Saved -> SCALES_part1_plots/ANBP_figures\fig4_volcano.pdf
Supplementary table saved → SCALES_part1_plots/ANBP_figures\supplementary_table.csv  (3885 multiplets)
Saved -> SCALES_part1_plots/ANR_figures\fig1_null_distributions.pdf
Saved -> SCALES_part1_plots/ANR_figures\fig2_omega_scatter.pdf
Saved -> SCALES_part1_plots/ANR_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")

Saved -> SCALES_part1_plots/ANR_figures\fig4_volcano.pdf
Supplementary table saved → SCALES_part1_plots/ANR_figures\supplementary_table.csv  (3806 multiplets)
Saved -> SCALES_part1_plots/BED_OSFED_figures\fig1_null_distributions.pdf
Saved -> SCALES_part1_plots/BED_OSFED_figures\fig2_omega_scatter.pdf
Saved -> SCALES_part1_plots/BED_OSFED_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")

Saved -> SCALES_part1_plots/BED_OSFED_figures\fig4_volcano.pdf
Supplementary table saved → SCALES_part1_plots/BED_OSFED_figures\supplementary_table.csv  (3829 multiplets)
Saved -> SCALES_part1_plots/BN_figures\fig1_null_distributions.pdf
Saved -> SCALES_part1_plots/BN_figures\fig2_omega_scatter.pdf
Saved -> SCALES_part1_plots/BN_figures\fig3_omega_violin.pdf

C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")
C:\Users\utente\Documents\DataScience\TESI_MAGISTRALE\CODE\optim_help\plots\o_info_bootstrap_plots.py:602: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from font(s) Arial.
  fig.savefig(path, dpi=dpi, bbox_inches="tight")

Saved -> SCALES_part1_plots/BN_figures\fig4_volcano.pdf
Supplementary table saved → SCALES_part1_plots/BN_figures\supplementary_table.csv  (3842 multiplets)

#### Filter multiplets - pvalue wise + REDUNDANCY/SYNERGY check
- Filter out the multiplets whose observed $\Omega$ is not significant (pvalue based)
- Filter out the multiplets whose observed and significant $\Omega$ - information shows zero-interaction (set a tolerance for what is zero-interaction: |$\Omega$| < 0.05

In [90]:
omega_threshold = 0.10
#alpha_significance = 0.05

fdr_neut_filtered_mults_diags = {}
filtered_descriptive = {}
for diagnosis, perm_scales in perm_diags_scales.items():
    fdr_neut_filtered_mults_diags[diagnosis] = ut.fdr_neuter_filter(perm_scales, omega_threshold = omega_threshold)
    filtered_descriptive[diagnosis] = ut.fdr_neuter_filter(perm_scales, omega_threshold = 0)

In [92]:
omega_partitions_diags = {}
for diag, filtered_boot in filtered_descriptive.items():
    omega_partitions_diags[diag] = ut.omega_partition(filtered_boot, alpha = alpha_significance, omega_threshold = omega_threshold)
    
print(ut.describe_omega_partition(omega_partitions_diags))

Diagnosis: ANBP
	 Interation type: syn there are:
	 	 Order: 3 # multiplets: 111
	 	 Order: 4 # multiplets: 1346
	 	 Order: 5 # multiplets: 1545
	 Interation type: red there are:
	 	 Order: 3 # multiplets: 45
	 	 Order: 4 # multiplets: 41
	 	 Order: 5 # multiplets: 55
	 Interation type: neut there are:
	 	 Order: 3 # multiplets: 298
	 	 Order: 4 # multiplets: 90
	 	 Order: 5 # multiplets: 62
	 Interation type: non_sig there are:
	 	 Order: 3 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 5 # multiplets: 0
Diagnosis: ANR
	 Interation type: syn there are:
	 	 Order: 3 # multiplets: 9
	 	 Order: 4 # multiplets: 1151
	 	 Order: 5 # multiplets: 1527
	 Interation type: red there are:
	 	 Order: 3 # multiplets: 37
	 	 Order: 4 # multiplets: 34
	 	 Order: 5 # multiplets: 32
	 Interation type: neut there are:
	 	 Order: 3 # multiplets: 355
	 	 Order: 4 # multiplets: 99
	 	 Order: 5 # multiplets: 73
	 Interation type: non_sig there are:
	 	 Order: 3 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 5 # multiplets: 0
Diagnosis: BED_OSFED
	 Interation type: syn there are:
	 	 Order: 3 # multiplets: 122
	 	 Order: 4 # multiplets: 1188
	 	 Order: 5 # multiplets: 1227
	 Interation type: red there are:
	 	 Order: 3 # multiplets: 22
	 	 Order: 4 # multiplets: 63
	 	 Order: 5 # multiplets: 233
	 Interation type: neut there are:
	 	 Order: 3 # multiplets: 178
	 	 Order: 4 # multiplets: 122
	 	 Order: 5 # multiplets: 94
	 Interation type: non_sig there are:
	 	 Order: 3 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 5 # multiplets: 0
Diagnosis: BN
	 Interation type: syn there are:
	 	 Order: 3 # multiplets: 6
	 	 Order: 4 # multiplets: 1282
	 	 Order: 5 # multiplets: 1578
	 Interation type: red there are:
	 	 Order: 3 # multiplets: 16
	 	 Order: 4 # multiplets: 23
	 	 Order: 5 # multiplets: 38
	 Interation type: neut there are:
	 	 Order: 3 # multiplets: 367
	 	 Order: 4 # multiplets: 66
	 	 Order: 5 # multiplets: 51
	 Interation type: non_sig there are:
	 	 Order: 3 # multiplets: 0
	 	 Order: 4 # multiplets: 0
	 	 Order: 5 # multiplets: 0
None

### BCa 

#### Bias Corrected permutation distribution

BCa preparation: get the sampling distribution (permute ROWS)

In [91]:
# here are the fildered multiplets to use for further computations
op_multiplets_diags_F = ut.get_multiplets_as_dict_list_F(fdr_neut_filtered_mults_diags)

In [93]:
bca_sampD_diags_inter = {}
for diagnosis, mults in op_multiplets_diags_F.items():
    start = time.perf_counter()
    bca_sampD_diags_inter[diagnosis] = bca_bootopt.get_boot_stats_parallel(multiplets_dict=mults, 
                                                                            X=EDI_diags[diagnosis], 
                                                                            n_boot=n_boot_perm)
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]
Multiplets | family 3:   0%|          | 0/156 [00:00<?, ?it/s]

  0%|          | 0/156 [00:00<?, ?it/s]

  1%|          | 1/156 [00:04<10:25,  4.04s/it]

  5%|▌         | 8/156 [00:04<00:56,  2.61it/s]

  8%|▊         | 12/156 [00:06<01:05,  2.21it/s]

  9%|▉         | 14/156 [00:06<00:51,  2.77it/s]

 10%|█         | 16/156 [00:06<00:41,  3.40it/s]

 12%|█▏        | 18/156 [00:08<01:02,  2.20it/s]

 13%|█▎        | 21/156 [00:08<00:46,  2.91it/s]

 15%|█▌        | 24/156 [00:09<00:31,  4.15it/s]

 17%|█▋        | 26/156 [00:10<00:47,  2.74it/s]

 18%|█▊        | 28/156 [00:10<00:37,  3.40it/s]

 19%|█▉        | 30/156 [00:11<00:33,  3.75it/s]

 20%|█▉        | 31/156 [00:11<00:30,  4.16it/s]

 21%|██        | 33/156 [00:12<00:45,  2.67it/s]

 23%|██▎       | 36/156 [00:13<00:34,  3.43it/s]

 24%|██▍       | 38/156 [00:13<00:27,  4.36it/s]

 25%|██▌       | 39/156 [00:13<00:27,  4.32it/s]

 26%|██▋       | 41/156 [00:14<00:38,  3.00it/s]

 28%|██▊       | 43/156 [00:14<00:28,  4.03it/s]

 28%|██▊       | 44/156 [00:15<00:31,  3.52it/s]

 29%|██▉       | 45/156 [00:15<00:27,  4.04it/s]

 30%|███       | 47/156 [00:15<00:24,  4.47it/s]

 31%|███▏      | 49/156 [00:16<00:32,  3.27it/s]

 33%|███▎      | 51/156 [00:16<00:25,  4.08it/s]

 33%|███▎      | 52/156 [00:17<00:31,  3.32it/s]

 35%|███▌      | 55/156 [00:17<00:22,  4.41it/s]

 37%|███▋      | 57/156 [00:18<00:27,  3.56it/s]

 37%|███▋      | 58/156 [00:18<00:25,  3.89it/s]

 38%|███▊      | 59/156 [00:18<00:24,  3.92it/s]

 38%|███▊      | 60/156 [00:19<00:28,  3.39it/s]

 39%|███▉      | 61/156 [00:19<00:24,  3.87it/s]

 40%|████      | 63/156 [00:19<00:21,  4.28it/s]

 42%|████▏     | 65/156 [00:20<00:27,  3.25it/s]

 43%|████▎     | 67/156 [00:21<00:24,  3.62it/s]

 44%|████▎     | 68/156 [00:21<00:26,  3.37it/s]

 45%|████▍     | 70/156 [00:21<00:19,  4.44it/s]

 46%|████▌     | 72/156 [00:22<00:18,  4.61it/s]

 47%|████▋     | 73/156 [00:22<00:21,  3.88it/s]

 47%|████▋     | 74/156 [00:22<00:19,  4.16it/s]

 48%|████▊     | 75/156 [00:23<00:22,  3.58it/s]

 49%|████▊     | 76/156 [00:23<00:24,  3.22it/s]

 49%|████▉     | 77/156 [00:23<00:22,  3.51it/s]

 51%|█████     | 79/156 [00:23<00:15,  5.08it/s]

 51%|█████▏    | 80/156 [00:24<00:17,  4.27it/s]

 52%|█████▏    | 81/156 [00:24<00:22,  3.35it/s]

 53%|█████▎    | 82/156 [00:24<00:20,  3.57it/s]

 53%|█████▎    | 83/156 [00:25<00:17,  4.07it/s]

 54%|█████▍    | 84/156 [00:25<00:21,  3.37it/s]

 54%|█████▍    | 85/156 [00:26<00:26,  2.73it/s]

 55%|█████▌    | 86/156 [00:26<00:22,  3.06it/s]

 56%|█████▌    | 87/156 [00:26<00:18,  3.70it/s]

 57%|█████▋    | 89/156 [00:26<00:17,  3.84it/s]

 58%|█████▊    | 90/156 [00:27<00:15,  4.31it/s]

 59%|█████▉    | 92/156 [00:27<00:15,  4.15it/s]

 60%|█████▉    | 93/156 [00:28<00:21,  2.96it/s]

 61%|██████    | 95/156 [00:28<00:15,  3.89it/s]

 62%|██████▏   | 97/156 [00:28<00:14,  4.16it/s]

 63%|██████▎   | 98/156 [00:29<00:12,  4.49it/s]

 64%|██████▍   | 100/156 [00:29<00:14,  3.83it/s]

 65%|██████▍   | 101/156 [00:30<00:17,  3.22it/s]

 66%|██████▌   | 103/156 [00:30<00:13,  3.99it/s]

 67%|██████▋   | 104/156 [00:30<00:11,  4.55it/s]

 67%|██████▋   | 105/156 [00:31<00:12,  3.98it/s]

 69%|██████▉   | 108/156 [00:31<00:11,  4.12it/s]

 70%|██████▉   | 109/156 [00:32<00:13,  3.44it/s]

 71%|███████   | 111/156 [00:32<00:11,  3.93it/s]

 72%|███████▏  | 112/156 [00:32<00:09,  4.47it/s]

 72%|███████▏  | 113/156 [00:32<00:10,  4.24it/s]

 74%|███████▍  | 116/156 [00:33<00:10,  3.87it/s]

 75%|███████▌  | 117/156 [00:34<00:10,  3.60it/s]

 76%|███████▌  | 118/156 [00:34<00:09,  3.81it/s]

 76%|███████▋  | 119/156 [00:34<00:09,  3.80it/s]

 77%|███████▋  | 120/156 [00:34<00:08,  4.21it/s]

 78%|███████▊  | 121/156 [00:34<00:07,  4.59it/s]

 79%|███████▉  | 123/156 [00:35<00:04,  6.77it/s]

 79%|███████▉  | 124/156 [00:35<00:09,  3.43it/s]

 80%|████████  | 125/156 [00:36<00:09,  3.37it/s]

 81%|████████  | 126/156 [00:36<00:08,  3.41it/s]

 81%|████████▏ | 127/156 [00:36<00:09,  3.07it/s]

 83%|████████▎ | 129/156 [00:37<00:06,  4.30it/s]

 85%|████████▍ | 132/156 [00:37<00:05,  4.31it/s]

 85%|████████▌ | 133/156 [00:38<00:05,  3.87it/s]

 86%|████████▌ | 134/156 [00:38<00:05,  3.70it/s]

 87%|████████▋ | 135/156 [00:38<00:06,  3.47it/s]

 87%|████████▋ | 136/156 [00:38<00:05,  3.89it/s]

 88%|████████▊ | 138/156 [00:39<00:03,  5.51it/s]

 89%|████████▉ | 139/156 [00:39<00:03,  5.44it/s]

 90%|████████▉ | 140/156 [00:39<00:03,  4.24it/s]

 90%|█████████ | 141/156 [00:40<00:04,  3.64it/s]

 91%|█████████ | 142/156 [00:40<00:04,  3.10it/s]

 92%|█████████▏| 143/156 [00:40<00:04,  3.09it/s]

 92%|█████████▏| 144/156 [00:41<00:03,  3.54it/s]

 94%|█████████▎| 146/156 [00:41<00:02,  4.56it/s]

 94%|█████████▍| 147/156 [00:41<00:01,  5.05it/s]

 95%|█████████▍| 148/156 [00:41<00:01,  4.49it/s]

 96%|█████████▌| 149/156 [00:42<00:01,  3.69it/s]

 96%|█████████▌| 150/156 [00:42<00:02,  2.68it/s]

 97%|█████████▋| 152/156 [00:43<00:01,  3.78it/s]

 99%|█████████▊| 154/156 [00:43<00:00,  4.75it/s]

100%|██████████| 156/156 [00:43<00:00,  3.58it/s]
Multiplets | family 3:   0%|          | 0/156 [00:43<?, ?it/s]

Multiplets | family 4:   0%|          | 0/1387 [00:00<?, ?it/s]

  0%|          | 0/1387 [00:00<?, ?it/s]

  0%|          | 1/1387 [00:02<1:01:31,  2.66s/it]

  0%|          | 4/1387 [00:02<12:19,  1.87it/s]

  0%|          | 6/1387 [00:02<07:41,  2.99it/s]

  1%|          | 9/1387 [00:05<12:35,  1.82it/s]

  1%|          | 10/1387 [00:05<10:45,  2.13it/s]

  1%|          | 12/1387 [00:05<07:43,  2.97it/s]

  1%|          | 14/1387 [00:05<05:34,  4.11it/s]

  1%|          | 16/1387 [00:05<04:14,  5.38it/s]

  1%|▏         | 18/1387 [00:08<10:54,  2.09it/s]

  1%|▏         | 20/1387 [00:08<08:13,  2.77it/s]

  2%|▏         | 21/1387 [00:08<07:24,  3.07it/s]

  2%|▏         | 23/1387 [00:08<05:17,  4.29it/s]

  2%|▏         | 25/1387 [00:10<11:11,  2.03it/s]

  2%|▏         | 26/1387 [00:10<10:06,  2.24it/s]

  2%|▏         | 28/1387 [00:11<07:53,  2.87it/s]

  2%|▏         | 30/1387 [00:11<05:42,  3.97it/s]

  2%|▏         | 31/1387 [00:11<05:09,  4.37it/s]

  2%|▏         | 33/1387 [00:13<11:32,  1.95it/s]

  3%|▎         | 35/1387 [00:13<08:37,  2.61it/s]

  3%|▎         | 36/1387 [00:13<07:39,  2.94it/s]

  3%|▎         | 39/1387 [00:14<05:35,  4.01it/s]

  3%|▎         | 41/1387 [00:16<10:08,  2.21it/s]

  3%|▎         | 43/1387 [00:16<07:58,  2.81it/s]

  3%|▎         | 45/1387 [00:16<06:27,  3.47it/s]

  3%|▎         | 47/1387 [00:17<06:00,  3.72it/s]

  4%|▎         | 49/1387 [00:18<09:39,  2.31it/s]

  4%|▎         | 51/1387 [00:19<07:41,  2.90it/s]

  4%|▍         | 53/1387 [00:19<06:23,  3.48it/s]

  4%|▍         | 54/1387 [00:19<05:46,  3.85it/s]

  4%|▍         | 55/1387 [00:19<06:04,  3.65it/s]

  4%|▍         | 57/1387 [00:21<10:08,  2.19it/s]

  4%|▍         | 58/1387 [00:21<08:38,  2.56it/s]

  4%|▍         | 59/1387 [00:21<07:17,  3.04it/s]

  4%|▍         | 60/1387 [00:21<07:01,  3.15it/s]

  4%|▍         | 62/1387 [00:22<05:30,  4.01it/s]

  5%|▍         | 63/1387 [00:22<05:22,  4.10it/s]

  5%|▍         | 65/1387 [00:24<10:28,  2.10it/s]

  5%|▍         | 67/1387 [00:24<08:01,  2.74it/s]

  5%|▍         | 68/1387 [00:24<07:05,  3.10it/s]

  5%|▍         | 69/1387 [00:24<06:02,  3.64it/s]

  5%|▌         | 70/1387 [00:24<06:19,  3.47it/s]

  5%|▌         | 71/1387 [00:25<05:53,  3.72it/s]

  5%|▌         | 73/1387 [00:26<10:24,  2.10it/s]

  5%|▌         | 74/1387 [00:26<08:34,  2.55it/s]

  5%|▌         | 75/1387 [00:27<08:25,  2.60it/s]

  6%|▌         | 77/1387 [00:27<06:12,  3.51it/s]

  6%|▌         | 78/1387 [00:27<05:41,  3.83it/s]

  6%|▌         | 79/1387 [00:27<05:05,  4.29it/s]

  6%|▌         | 80/1387 [00:27<04:21,  5.00it/s]

  6%|▌         | 81/1387 [00:29<12:08,  1.79it/s]

  6%|▌         | 82/1387 [00:29<10:44,  2.03it/s]

  6%|▌         | 84/1387 [00:30<07:48,  2.78it/s]

  6%|▌         | 86/1387 [00:30<05:30,  3.94it/s]

  6%|▋         | 87/1387 [00:30<06:12,  3.49it/s]

  6%|▋         | 89/1387 [00:32<09:40,  2.24it/s]

  6%|▋         | 90/1387 [00:32<08:54,  2.43it/s]

  7%|▋         | 92/1387 [00:32<07:05,  3.04it/s]

  7%|▋         | 93/1387 [00:32<06:23,  3.38it/s]

  7%|▋         | 94/1387 [00:33<05:36,  3.84it/s]

  7%|▋         | 95/1387 [00:33<05:52,  3.67it/s]

  7%|▋         | 97/1387 [00:34<09:33,  2.25it/s]

  7%|▋         | 98/1387 [00:34<08:15,  2.60it/s]

  7%|▋         | 100/1387 [00:35<07:36,  2.82it/s]

  7%|▋         | 102/1387 [00:35<05:56,  3.60it/s]

  7%|▋         | 103/1387 [00:36<05:31,  3.88it/s]

  7%|▋         | 104/1387 [00:36<05:17,  4.04it/s]

  8%|▊         | 105/1387 [00:37<10:35,  2.02it/s]

  8%|▊         | 106/1387 [00:37<09:21,  2.28it/s]

  8%|▊         | 108/1387 [00:38<07:32,  2.83it/s]

  8%|▊         | 110/1387 [00:38<06:14,  3.41it/s]

  8%|▊         | 112/1387 [00:38<05:07,  4.14it/s]

  8%|▊         | 113/1387 [00:40<10:00,  2.12it/s]

  8%|▊         | 114/1387 [00:40<08:34,  2.47it/s]

  8%|▊         | 115/1387 [00:40<07:10,  2.96it/s]

  8%|▊         | 116/1387 [00:41<07:15,  2.92it/s]

  9%|▊         | 118/1387 [00:41<06:36,  3.20it/s]

  9%|▊         | 120/1387 [00:41<04:59,  4.23it/s]

  9%|▊         | 121/1387 [00:43<11:38,  1.81it/s]

  9%|▉         | 122/1387 [00:43<10:09,  2.07it/s]

  9%|▉         | 124/1387 [00:43<06:47,  3.10it/s]

  9%|▉         | 125/1387 [00:44<06:00,  3.50it/s]

  9%|▉         | 126/1387 [00:44<06:56,  3.03it/s]

  9%|▉         | 127/1387 [00:44<06:13,  3.38it/s]

  9%|▉         | 128/1387 [00:45<07:42,  2.72it/s]

  9%|▉         | 129/1387 [00:46<12:20,  1.70it/s]

  9%|▉         | 130/1387 [00:46<09:39,  2.17it/s]

  9%|▉         | 131/1387 [00:46<07:57,  2.63it/s]

 10%|▉         | 132/1387 [00:46<06:23,  3.28it/s]

 10%|▉         | 133/1387 [00:47<07:18,  2.86it/s]

 10%|▉         | 134/1387 [00:47<06:04,  3.44it/s]

 10%|▉         | 135/1387 [00:47<05:31,  3.78it/s]

 10%|▉         | 136/1387 [00:48<06:28,  3.22it/s]

 10%|▉         | 137/1387 [00:49<10:33,  1.97it/s]

 10%|▉         | 138/1387 [00:49<08:51,  2.35it/s]

 10%|█         | 139/1387 [00:49<07:25,  2.80it/s]

 10%|█         | 140/1387 [00:49<05:49,  3.57it/s]

 10%|█         | 141/1387 [00:50<07:32,  2.76it/s]

 10%|█         | 142/1387 [00:50<06:15,  3.31it/s]

 10%|█         | 143/1387 [00:50<05:29,  3.77it/s]

 10%|█         | 144/1387 [00:50<05:54,  3.51it/s]

 10%|█         | 145/1387 [00:51<10:08,  2.04it/s]

 11%|█         | 146/1387 [00:51<07:57,  2.60it/s]

 11%|█         | 147/1387 [00:52<06:33,  3.15it/s]

 11%|█         | 149/1387 [00:52<07:29,  2.76it/s]

 11%|█         | 150/1387 [00:53<06:25,  3.21it/s]

 11%|█         | 152/1387 [00:53<05:27,  3.77it/s]

 11%|█         | 153/1387 [00:54<08:24,  2.45it/s]

 11%|█         | 154/1387 [00:54<07:13,  2.84it/s]

 11%|█         | 155/1387 [00:54<07:13,  2.84it/s]

 11%|█         | 156/1387 [00:55<06:26,  3.19it/s]

 11%|█▏        | 157/1387 [00:55<08:00,  2.56it/s]

 11%|█▏        | 158/1387 [00:56<07:24,  2.76it/s]

 11%|█▏        | 159/1387 [00:56<06:24,  3.20it/s]

 12%|█▏        | 160/1387 [00:56<06:13,  3.28it/s]

 12%|█▏        | 161/1387 [00:57<08:47,  2.32it/s]

 12%|█▏        | 163/1387 [00:57<07:22,  2.76it/s]

 12%|█▏        | 164/1387 [00:57<06:08,  3.32it/s]

 12%|█▏        | 165/1387 [00:58<07:33,  2.69it/s]

 12%|█▏        | 166/1387 [00:58<07:52,  2.59it/s]

 12%|█▏        | 167/1387 [00:59<09:21,  2.17it/s]

 12%|█▏        | 169/1387 [01:00<07:40,  2.64it/s]

 12%|█▏        | 170/1387 [01:00<07:49,  2.59it/s]

 12%|█▏        | 171/1387 [01:01<08:25,  2.40it/s]

 12%|█▏        | 173/1387 [01:01<08:44,  2.32it/s]

 13%|█▎        | 175/1387 [01:02<07:40,  2.63it/s]

 13%|█▎        | 176/1387 [01:02<07:51,  2.57it/s]

 13%|█▎        | 178/1387 [01:03<07:33,  2.66it/s]

 13%|█▎        | 179/1387 [01:03<06:34,  3.06it/s]

 13%|█▎        | 180/1387 [01:04<06:26,  3.13it/s]

 13%|█▎        | 181/1387 [01:04<07:40,  2.62it/s]

 13%|█▎        | 183/1387 [01:05<08:56,  2.24it/s]

 13%|█▎        | 184/1387 [01:05<07:35,  2.64it/s]

 13%|█▎        | 185/1387 [01:06<07:02,  2.85it/s]

 13%|█▎        | 186/1387 [01:06<07:16,  2.75it/s]

 14%|█▎        | 188/1387 [01:07<06:52,  2.91it/s]

 14%|█▎        | 189/1387 [01:07<06:51,  2.91it/s]

 14%|█▍        | 191/1387 [01:08<08:02,  2.48it/s]

 14%|█▍        | 192/1387 [01:08<07:07,  2.79it/s]

 14%|█▍        | 193/1387 [01:08<06:18,  3.16it/s]

 14%|█▍        | 194/1387 [01:09<07:27,  2.66it/s]

 14%|█▍        | 196/1387 [01:10<06:54,  2.87it/s]

 14%|█▍        | 197/1387 [01:10<06:57,  2.85it/s]

 14%|█▍        | 199/1387 [01:11<08:41,  2.28it/s]

 14%|█▍        | 200/1387 [01:11<07:32,  2.62it/s]

 15%|█▍        | 202/1387 [01:12<06:44,  2.93it/s]

 15%|█▍        | 203/1387 [01:12<05:54,  3.34it/s]

 15%|█▍        | 204/1387 [01:13<08:53,  2.22it/s]

 15%|█▍        | 206/1387 [01:13<05:49,  3.38it/s]

 15%|█▍        | 207/1387 [01:14<09:38,  2.04it/s]

 15%|█▍        | 208/1387 [01:15<08:45,  2.24it/s]

 15%|█▌        | 209/1387 [01:15<07:11,  2.73it/s]

 15%|█▌        | 211/1387 [01:15<04:41,  4.18it/s]

 15%|█▌        | 212/1387 [01:16<08:45,  2.24it/s]

 15%|█▌        | 213/1387 [01:16<08:51,  2.21it/s]

 16%|█▌        | 215/1387 [01:17<08:44,  2.23it/s]

 16%|█▌        | 217/1387 [01:18<06:44,  2.89it/s]

 16%|█▌        | 219/1387 [01:18<04:51,  4.01it/s]

 16%|█▌        | 220/1387 [01:19<10:15,  1.90it/s]

 16%|█▌        | 222/1387 [01:20<07:19,  2.65it/s]

 16%|█▌        | 223/1387 [01:20<08:02,  2.41it/s]

 16%|█▌        | 224/1387 [01:21<07:48,  2.48it/s]

 16%|█▌        | 225/1387 [01:21<06:39,  2.91it/s]

 16%|█▋        | 226/1387 [01:21<06:55,  2.79it/s]

 16%|█▋        | 228/1387 [01:22<09:24,  2.05it/s]

 17%|█▋        | 230/1387 [01:23<06:12,  3.11it/s]

 17%|█▋        | 231/1387 [01:23<07:51,  2.45it/s]

 17%|█▋        | 232/1387 [01:24<07:09,  2.69it/s]

 17%|█▋        | 233/1387 [01:24<06:26,  2.99it/s]

 17%|█▋        | 234/1387 [01:24<06:45,  2.84it/s]

 17%|█▋        | 236/1387 [01:25<08:01,  2.39it/s]

 17%|█▋        | 238/1387 [01:25<05:51,  3.27it/s]

 17%|█▋        | 239/1387 [01:26<06:53,  2.77it/s]

 17%|█▋        | 240/1387 [01:26<07:09,  2.67it/s]

 17%|█▋        | 242/1387 [01:27<06:46,  2.82it/s]

 18%|█▊        | 244/1387 [01:28<07:21,  2.59it/s]

 18%|█▊        | 245/1387 [01:28<06:20,  3.00it/s]

 18%|█▊        | 247/1387 [01:29<06:35,  2.88it/s]

 18%|█▊        | 248/1387 [01:29<06:59,  2.72it/s]

 18%|█▊        | 249/1387 [01:29<06:10,  3.08it/s]

 18%|█▊        | 250/1387 [01:30<06:54,  2.74it/s]

 18%|█▊        | 252/1387 [01:31<08:28,  2.23it/s]

 18%|█▊        | 254/1387 [01:31<05:54,  3.20it/s]

 18%|█▊        | 255/1387 [01:31<05:43,  3.30it/s]

 18%|█▊        | 256/1387 [01:32<06:22,  2.95it/s]

 19%|█▊        | 257/1387 [01:32<05:42,  3.30it/s]

 19%|█▊        | 258/1387 [01:33<07:37,  2.47it/s]

 19%|█▊        | 260/1387 [01:34<09:15,  2.03it/s]

 19%|█▉        | 261/1387 [01:34<08:12,  2.29it/s]

 19%|█▉        | 262/1387 [01:34<06:52,  2.73it/s]

 19%|█▉        | 263/1387 [01:35<05:33,  3.37it/s]

 19%|█▉        | 264/1387 [01:35<05:58,  3.13it/s]

 19%|█▉        | 265/1387 [01:35<05:31,  3.39it/s]

 19%|█▉        | 266/1387 [01:36<09:05,  2.05it/s]

 19%|█▉        | 267/1387 [01:36<07:11,  2.59it/s]

 19%|█▉        | 268/1387 [01:37<08:51,  2.11it/s]

 19%|█▉        | 269/1387 [01:37<07:44,  2.41it/s]

 19%|█▉        | 270/1387 [01:38<07:54,  2.36it/s]

 20%|█▉        | 271/1387 [01:38<06:07,  3.04it/s]

 20%|█▉        | 272/1387 [01:38<05:06,  3.63it/s]

 20%|█▉        | 273/1387 [01:38<05:31,  3.36it/s]

 20%|█▉        | 274/1387 [01:39<08:07,  2.28it/s]

 20%|█▉        | 275/1387 [01:39<06:36,  2.81it/s]

 20%|█▉        | 276/1387 [01:40<08:32,  2.17it/s]

 20%|█▉        | 277/1387 [01:40<08:11,  2.26it/s]

 20%|██        | 278/1387 [01:41<07:43,  2.39it/s]

 20%|██        | 280/1387 [01:41<05:30,  3.35it/s]

 20%|██        | 281/1387 [01:41<06:03,  3.05it/s]

 20%|██        | 282/1387 [01:42<07:15,  2.54it/s]

 20%|██        | 283/1387 [01:42<06:38,  2.77it/s]

 20%|██        | 284/1387 [01:43<09:51,  1.86it/s]

 21%|██        | 285/1387 [01:43<07:36,  2.42it/s]

 21%|██        | 286/1387 [01:44<09:11,  2.00it/s]

 21%|██        | 289/1387 [01:44<05:05,  3.59it/s]

 21%|██        | 290/1387 [01:45<06:57,  2.63it/s]

 21%|██        | 291/1387 [01:45<05:52,  3.11it/s]

 21%|██        | 292/1387 [01:46<08:32,  2.14it/s]

 21%|██        | 294/1387 [01:47<07:03,  2.58it/s]

 21%|██▏       | 295/1387 [01:47<06:07,  2.97it/s]

 21%|██▏       | 296/1387 [01:47<05:28,  3.32it/s]

 21%|██▏       | 297/1387 [01:47<05:25,  3.34it/s]

 21%|██▏       | 298/1387 [01:48<06:53,  2.63it/s]

 22%|██▏       | 300/1387 [01:49<07:32,  2.40it/s]

 22%|██▏       | 302/1387 [01:50<07:58,  2.27it/s]

 22%|██▏       | 304/1387 [01:50<06:11,  2.91it/s]

 22%|██▏       | 305/1387 [01:51<06:13,  2.89it/s]

 22%|██▏       | 306/1387 [01:51<05:48,  3.10it/s]

 22%|██▏       | 307/1387 [01:51<05:44,  3.14it/s]

 22%|██▏       | 308/1387 [01:52<07:10,  2.51it/s]

 22%|██▏       | 309/1387 [01:52<07:39,  2.35it/s]

 22%|██▏       | 310/1387 [01:53<08:00,  2.24it/s]

 22%|██▏       | 311/1387 [01:53<06:35,  2.72it/s]

 22%|██▏       | 312/1387 [01:54<07:55,  2.26it/s]

 23%|██▎       | 313/1387 [01:54<06:21,  2.82it/s]

 23%|██▎       | 314/1387 [01:54<05:35,  3.20it/s]

 23%|██▎       | 315/1387 [01:54<06:10,  2.89it/s]

 23%|██▎       | 316/1387 [01:55<08:51,  2.02it/s]

 23%|██▎       | 317/1387 [01:55<07:12,  2.47it/s]

 23%|██▎       | 318/1387 [01:56<07:36,  2.34it/s]

 23%|██▎       | 319/1387 [01:56<06:26,  2.76it/s]

 23%|██▎       | 320/1387 [01:56<06:26,  2.76it/s]

 23%|██▎       | 321/1387 [01:57<06:17,  2.83it/s]

 23%|██▎       | 322/1387 [01:57<05:47,  3.07it/s]

 23%|██▎       | 323/1387 [01:57<05:05,  3.49it/s]

 23%|██▎       | 324/1387 [01:58<07:04,  2.51it/s]

 23%|██▎       | 325/1387 [01:58<06:52,  2.57it/s]

 24%|██▎       | 326/1387 [01:59<06:38,  2.66it/s]

 24%|██▎       | 327/1387 [01:59<05:26,  3.24it/s]

 24%|██▎       | 328/1387 [01:59<06:35,  2.68it/s]

 24%|██▎       | 329/1387 [02:00<06:50,  2.58it/s]

 24%|██▍       | 331/1387 [02:00<05:38,  3.12it/s]

 24%|██▍       | 332/1387 [02:01<06:34,  2.67it/s]

 24%|██▍       | 333/1387 [02:01<07:28,  2.35it/s]

 24%|██▍       | 335/1387 [02:02<05:29,  3.20it/s]

 24%|██▍       | 336/1387 [02:02<06:08,  2.85it/s]

 24%|██▍       | 337/1387 [02:02<06:23,  2.74it/s]

 24%|██▍       | 338/1387 [02:03<05:23,  3.24it/s]

 24%|██▍       | 339/1387 [02:03<05:43,  3.05it/s]

 25%|██▍       | 340/1387 [02:03<06:21,  2.75it/s]

 25%|██▍       | 341/1387 [02:04<09:39,  1.81it/s]

 25%|██▍       | 344/1387 [02:05<06:28,  2.68it/s]

 25%|██▍       | 345/1387 [02:05<05:34,  3.11it/s]

 25%|██▍       | 346/1387 [02:05<04:49,  3.60it/s]

 25%|██▌       | 347/1387 [02:06<05:06,  3.39it/s]

 25%|██▌       | 348/1387 [02:06<06:35,  2.63it/s]

 25%|██▌       | 349/1387 [02:07<08:31,  2.03it/s]

 25%|██▌       | 350/1387 [02:07<06:50,  2.53it/s]

 25%|██▌       | 352/1387 [02:08<06:05,  2.83it/s]

 25%|██▌       | 353/1387 [02:08<05:23,  3.19it/s]

 26%|██▌       | 354/1387 [02:08<04:51,  3.54it/s]

 26%|██▌       | 355/1387 [02:09<05:21,  3.21it/s]

 26%|██▌       | 356/1387 [02:09<06:19,  2.72it/s]

 26%|██▌       | 357/1387 [02:10<07:44,  2.22it/s]

 26%|██▌       | 358/1387 [02:10<06:21,  2.70it/s]

 26%|██▌       | 360/1387 [02:11<05:48,  2.95it/s]

 26%|██▌       | 361/1387 [02:11<05:31,  3.09it/s]

 26%|██▌       | 362/1387 [02:11<04:58,  3.43it/s]

 26%|██▌       | 363/1387 [02:11<05:21,  3.19it/s]

 26%|██▌       | 364/1387 [02:12<06:31,  2.61it/s]

 26%|██▋       | 365/1387 [02:13<07:01,  2.42it/s]

 26%|██▋       | 366/1387 [02:13<06:14,  2.73it/s]

 27%|██▋       | 368/1387 [02:13<05:36,  3.03it/s]

 27%|██▋       | 369/1387 [02:14<05:43,  2.96it/s]

 27%|██▋       | 370/1387 [02:14<05:10,  3.27it/s]

 27%|██▋       | 371/1387 [02:14<05:35,  3.02it/s]

 27%|██▋       | 372/1387 [02:15<06:44,  2.51it/s]

 27%|██▋       | 373/1387 [02:15<06:22,  2.65it/s]

 27%|██▋       | 374/1387 [02:15<05:45,  2.93it/s]

 27%|██▋       | 375/1387 [02:16<05:16,  3.20it/s]

 27%|██▋       | 376/1387 [02:16<05:38,  2.98it/s]

 27%|██▋       | 377/1387 [02:17<06:31,  2.58it/s]

 27%|██▋       | 379/1387 [02:17<05:54,  2.84it/s]

 27%|██▋       | 380/1387 [02:18<06:25,  2.62it/s]

 27%|██▋       | 381/1387 [02:18<05:48,  2.89it/s]

 28%|██▊       | 382/1387 [02:18<05:35,  3.00it/s]

 28%|██▊       | 383/1387 [02:19<05:46,  2.90it/s]

 28%|██▊       | 384/1387 [02:19<05:01,  3.33it/s]

 28%|██▊       | 385/1387 [02:19<06:25,  2.60it/s]

 28%|██▊       | 386/1387 [02:20<05:54,  2.82it/s]

 28%|██▊       | 387/1387 [02:20<05:40,  2.94it/s]

 28%|██▊       | 388/1387 [02:20<06:16,  2.65it/s]

 28%|██▊       | 389/1387 [02:21<07:14,  2.30it/s]

 28%|██▊       | 391/1387 [02:22<05:42,  2.90it/s]

 28%|██▊       | 393/1387 [02:22<06:06,  2.71it/s]

 28%|██▊       | 394/1387 [02:23<06:02,  2.74it/s]

 28%|██▊       | 395/1387 [02:23<06:12,  2.67it/s]

 29%|██▊       | 396/1387 [02:23<05:32,  2.98it/s]

 29%|██▊       | 397/1387 [02:24<06:01,  2.74it/s]

 29%|██▊       | 398/1387 [02:24<04:56,  3.33it/s]

 29%|██▉       | 399/1387 [02:24<06:14,  2.64it/s]

 29%|██▉       | 401/1387 [02:25<05:47,  2.84it/s]

 29%|██▉       | 402/1387 [02:26<06:20,  2.59it/s]

 29%|██▉       | 403/1387 [02:26<06:08,  2.67it/s]

 29%|██▉       | 404/1387 [02:26<05:02,  3.25it/s]

 29%|██▉       | 405/1387 [02:26<05:21,  3.06it/s]

 29%|██▉       | 406/1387 [02:27<05:15,  3.11it/s]

 29%|██▉       | 407/1387 [02:27<06:02,  2.70it/s]

 29%|██▉       | 409/1387 [02:28<05:23,  3.03it/s]

 30%|██▉       | 410/1387 [02:28<06:05,  2.67it/s]

 30%|██▉       | 411/1387 [02:29<06:21,  2.56it/s]

 30%|██▉       | 412/1387 [02:29<05:16,  3.08it/s]

 30%|██▉       | 413/1387 [02:29<05:23,  3.01it/s]

 30%|██▉       | 414/1387 [02:29<04:56,  3.28it/s]

 30%|██▉       | 415/1387 [02:30<05:47,  2.80it/s]

 30%|██▉       | 416/1387 [02:30<05:08,  3.15it/s]

 30%|███       | 417/1387 [02:31<05:19,  3.04it/s]

 30%|███       | 418/1387 [02:31<06:12,  2.60it/s]

 30%|███       | 419/1387 [02:32<07:15,  2.22it/s]

 30%|███       | 421/1387 [02:32<05:05,  3.16it/s]

 30%|███       | 422/1387 [02:32<05:22,  2.99it/s]

 30%|███       | 423/1387 [02:33<05:51,  2.74it/s]

 31%|███       | 424/1387 [02:33<04:54,  3.27it/s]

 31%|███       | 425/1387 [02:33<04:41,  3.42it/s]

 31%|███       | 426/1387 [02:34<06:00,  2.67it/s]

 31%|███       | 427/1387 [02:34<06:57,  2.30it/s]

 31%|███       | 429/1387 [02:35<05:01,  3.18it/s]

 31%|███       | 430/1387 [02:35<05:19,  3.00it/s]

 31%|███       | 431/1387 [02:36<05:44,  2.77it/s]

 31%|███       | 432/1387 [02:36<06:12,  2.57it/s]

 31%|███▏      | 434/1387 [02:37<05:32,  2.87it/s]

 31%|███▏      | 435/1387 [02:37<06:00,  2.64it/s]

 31%|███▏      | 436/1387 [02:37<05:59,  2.64it/s]

 32%|███▏      | 437/1387 [02:38<05:43,  2.77it/s]

 32%|███▏      | 438/1387 [02:38<05:11,  3.05it/s]

 32%|███▏      | 439/1387 [02:38<04:48,  3.28it/s]

 32%|███▏      | 440/1387 [02:39<07:01,  2.25it/s]

 32%|███▏      | 442/1387 [02:40<06:33,  2.40it/s]

 32%|███▏      | 444/1387 [02:40<05:56,  2.65it/s]

 32%|███▏      | 445/1387 [02:41<05:10,  3.03it/s]

 32%|███▏      | 446/1387 [02:41<04:39,  3.37it/s]

 32%|███▏      | 447/1387 [02:41<05:18,  2.95it/s]

 32%|███▏      | 448/1387 [02:42<06:17,  2.48it/s]

 32%|███▏      | 449/1387 [02:42<05:06,  3.06it/s]

 32%|███▏      | 450/1387 [02:43<07:11,  2.17it/s]

 33%|███▎      | 451/1387 [02:43<05:37,  2.77it/s]

 33%|███▎      | 452/1387 [02:43<06:14,  2.50it/s]

 33%|███▎      | 454/1387 [02:44<04:24,  3.52it/s]

 33%|███▎      | 455/1387 [02:44<04:56,  3.14it/s]

 33%|███▎      | 456/1387 [02:45<06:03,  2.56it/s]

 33%|███▎      | 458/1387 [02:45<06:06,  2.53it/s]

 33%|███▎      | 459/1387 [02:46<05:06,  3.03it/s]

 33%|███▎      | 460/1387 [02:46<05:39,  2.73it/s]

 33%|███▎      | 462/1387 [02:46<04:26,  3.47it/s]

 33%|███▎      | 463/1387 [02:47<04:49,  3.20it/s]

 33%|███▎      | 464/1387 [02:47<05:40,  2.71it/s]

 34%|███▎      | 466/1387 [02:48<06:29,  2.36it/s]

 34%|███▎      | 468/1387 [02:49<05:35,  2.74it/s]

 34%|███▍      | 469/1387 [02:49<05:19,  2.88it/s]

 34%|███▍      | 470/1387 [02:50<05:15,  2.91it/s]

 34%|███▍      | 471/1387 [02:50<05:04,  3.01it/s]

 34%|███▍      | 472/1387 [02:50<04:44,  3.22it/s]

 34%|███▍      | 473/1387 [02:50<04:27,  3.42it/s]

 34%|███▍      | 474/1387 [02:51<07:08,  2.13it/s]

 34%|███▍      | 475/1387 [02:52<06:23,  2.38it/s]

 34%|███▍      | 476/1387 [02:52<05:45,  2.64it/s]

 34%|███▍      | 477/1387 [02:52<05:40,  2.67it/s]

 34%|███▍      | 478/1387 [02:52<04:48,  3.15it/s]

 35%|███▍      | 479/1387 [02:53<06:00,  2.52it/s]

 35%|███▍      | 481/1387 [02:53<04:53,  3.09it/s]

 35%|███▍      | 482/1387 [02:54<06:16,  2.41it/s]

 35%|███▍      | 483/1387 [02:54<05:18,  2.84it/s]

 35%|███▍      | 484/1387 [02:55<04:51,  3.09it/s]

 35%|███▍      | 485/1387 [02:55<06:13,  2.42it/s]

 35%|███▌      | 487/1387 [02:56<05:05,  2.94it/s]

 35%|███▌      | 488/1387 [02:56<04:25,  3.39it/s]

 35%|███▌      | 489/1387 [02:56<05:38,  2.66it/s]

 35%|███▌      | 490/1387 [02:57<06:21,  2.35it/s]

 35%|███▌      | 492/1387 [02:57<04:32,  3.28it/s]

 36%|███▌      | 493/1387 [02:58<05:49,  2.55it/s]

 36%|███▌      | 495/1387 [02:58<04:45,  3.12it/s]

 36%|███▌      | 496/1387 [02:59<04:16,  3.48it/s]

 36%|███▌      | 497/1387 [02:59<05:33,  2.67it/s]

 36%|███▌      | 498/1387 [03:00<06:29,  2.28it/s]

 36%|███▌      | 500/1387 [03:00<04:11,  3.52it/s]

 36%|███▌      | 501/1387 [03:01<05:49,  2.54it/s]

 36%|███▋      | 503/1387 [03:01<04:33,  3.23it/s]

 36%|███▋      | 504/1387 [03:01<04:06,  3.59it/s]

 36%|███▋      | 505/1387 [03:02<05:39,  2.60it/s]

 36%|███▋      | 506/1387 [03:03<06:39,  2.21it/s]

 37%|███▋      | 508/1387 [03:03<04:08,  3.54it/s]

 37%|███▋      | 509/1387 [03:04<06:04,  2.41it/s]

 37%|███▋      | 510/1387 [03:04<05:22,  2.72it/s]

 37%|███▋      | 511/1387 [03:04<05:17,  2.76it/s]

 37%|███▋      | 512/1387 [03:04<04:41,  3.11it/s]

 37%|███▋      | 513/1387 [03:05<05:29,  2.65it/s]

 37%|███▋      | 514/1387 [03:06<06:55,  2.10it/s]

 37%|███▋      | 515/1387 [03:06<05:21,  2.71it/s]

 37%|███▋      | 516/1387 [03:06<05:39,  2.57it/s]

 37%|███▋      | 517/1387 [03:06<04:37,  3.14it/s]

 37%|███▋      | 518/1387 [03:07<06:00,  2.41it/s]

 37%|███▋      | 519/1387 [03:07<05:02,  2.87it/s]

 38%|███▊      | 521/1387 [03:08<05:50,  2.47it/s]

 38%|███▊      | 522/1387 [03:09<06:02,  2.39it/s]

 38%|███▊      | 523/1387 [03:09<05:42,  2.52it/s]

 38%|███▊      | 524/1387 [03:09<05:07,  2.81it/s]

 38%|███▊      | 525/1387 [03:10<05:09,  2.79it/s]

 38%|███▊      | 526/1387 [03:10<05:10,  2.77it/s]

 38%|███▊      | 527/1387 [03:10<05:47,  2.47it/s]

 38%|███▊      | 529/1387 [03:11<05:12,  2.75it/s]

 38%|███▊      | 530/1387 [03:11<04:46,  2.99it/s]

 38%|███▊      | 531/1387 [03:12<05:06,  2.79it/s]

 38%|███▊      | 532/1387 [03:12<05:37,  2.54it/s]

 38%|███▊      | 533/1387 [03:12<04:50,  2.94it/s]

 39%|███▊      | 534/1387 [03:13<05:30,  2.58it/s]

 39%|███▊      | 535/1387 [03:13<04:58,  2.85it/s]

 39%|███▊      | 536/1387 [03:13<04:30,  3.15it/s]

 39%|███▊      | 537/1387 [03:14<05:01,  2.82it/s]

 39%|███▉      | 538/1387 [03:14<04:34,  3.10it/s]

 39%|███▉      | 539/1387 [03:15<05:04,  2.78it/s]

 39%|███▉      | 540/1387 [03:15<05:00,  2.81it/s]

 39%|███▉      | 541/1387 [03:15<04:45,  2.96it/s]

 39%|███▉      | 542/1387 [03:16<05:15,  2.68it/s]

 39%|███▉      | 543/1387 [03:16<05:05,  2.76it/s]

 39%|███▉      | 545/1387 [03:17<04:41,  2.99it/s]

 39%|███▉      | 546/1387 [03:17<04:23,  3.20it/s]

 39%|███▉      | 547/1387 [03:17<05:07,  2.73it/s]

 40%|███▉      | 548/1387 [03:18<04:46,  2.93it/s]

 40%|███▉      | 549/1387 [03:18<04:16,  3.27it/s]

 40%|███▉      | 550/1387 [03:18<05:24,  2.58it/s]

 40%|███▉      | 551/1387 [03:19<04:57,  2.81it/s]

 40%|███▉      | 552/1387 [03:19<04:04,  3.41it/s]

 40%|███▉      | 553/1387 [03:20<05:56,  2.34it/s]

 40%|███▉      | 554/1387 [03:20<04:45,  2.92it/s]

 40%|████      | 555/1387 [03:21<06:42,  2.07it/s]

 40%|████      | 556/1387 [03:21<05:08,  2.70it/s]

 40%|████      | 557/1387 [03:21<06:36,  2.09it/s]

 40%|████      | 559/1387 [03:22<05:02,  2.74it/s]

 40%|████      | 561/1387 [03:23<06:03,  2.27it/s]

 41%|████      | 563/1387 [03:24<05:47,  2.37it/s]

 41%|████      | 564/1387 [03:24<06:34,  2.09it/s]

 41%|████      | 565/1387 [03:25<05:26,  2.52it/s]

 41%|████      | 566/1387 [03:25<06:07,  2.23it/s]

 41%|████      | 567/1387 [03:25<04:56,  2.77it/s]

 41%|████      | 568/1387 [03:26<04:56,  2.76it/s]

 41%|████      | 569/1387 [03:26<05:40,  2.40it/s]

 41%|████      | 570/1387 [03:26<05:14,  2.60it/s]

 41%|████      | 571/1387 [03:27<04:18,  3.16it/s]

 41%|████      | 572/1387 [03:27<06:00,  2.26it/s]

 41%|████▏     | 573/1387 [03:28<05:15,  2.58it/s]

 41%|████▏     | 574/1387 [03:28<05:08,  2.64it/s]

 41%|████▏     | 575/1387 [03:28<04:52,  2.78it/s]

 42%|████▏     | 576/1387 [03:29<05:16,  2.56it/s]

 42%|████▏     | 577/1387 [03:29<05:45,  2.34it/s]

 42%|████▏     | 578/1387 [03:30<05:07,  2.63it/s]

 42%|████▏     | 579/1387 [03:30<04:40,  2.88it/s]

 42%|████▏     | 580/1387 [03:30<05:21,  2.51it/s]

 42%|████▏     | 581/1387 [03:31<04:27,  3.02it/s]

 42%|████▏     | 582/1387 [03:31<04:29,  2.99it/s]

 42%|████▏     | 583/1387 [03:31<04:12,  3.19it/s]

 42%|████▏     | 584/1387 [03:32<05:00,  2.67it/s]

 42%|████▏     | 585/1387 [03:32<05:24,  2.47it/s]

 42%|████▏     | 586/1387 [03:32<04:49,  2.76it/s]

 42%|████▏     | 587/1387 [03:33<04:25,  3.01it/s]

 42%|████▏     | 588/1387 [03:33<04:56,  2.69it/s]

 42%|████▏     | 589/1387 [03:33<04:15,  3.12it/s]

 43%|████▎     | 590/1387 [03:34<05:07,  2.59it/s]

 43%|████▎     | 591/1387 [03:34<04:45,  2.79it/s]

 43%|████▎     | 592/1387 [03:34<04:38,  2.86it/s]

 43%|████▎     | 593/1387 [03:35<06:10,  2.14it/s]

 43%|████▎     | 594/1387 [03:35<04:50,  2.73it/s]

 43%|████▎     | 595/1387 [03:36<05:12,  2.54it/s]

 43%|████▎     | 596/1387 [03:36<05:27,  2.42it/s]

 43%|████▎     | 597/1387 [03:36<04:42,  2.79it/s]

 43%|████▎     | 598/1387 [03:37<04:04,  3.23it/s]

 43%|████▎     | 599/1387 [03:37<05:50,  2.25it/s]

 43%|████▎     | 600/1387 [03:38<04:41,  2.79it/s]

 43%|████▎     | 601/1387 [03:38<06:28,  2.02it/s]

 43%|████▎     | 602/1387 [03:39<05:32,  2.36it/s]

 43%|████▎     | 603/1387 [03:39<05:07,  2.55it/s]

 44%|████▎     | 604/1387 [03:40<06:34,  1.99it/s]

 44%|████▎     | 605/1387 [03:40<05:47,  2.25it/s]

 44%|████▍     | 607/1387 [03:41<05:38,  2.30it/s]

 44%|████▍     | 608/1387 [03:41<05:02,  2.57it/s]

 44%|████▍     | 609/1387 [03:41<04:28,  2.90it/s]

 44%|████▍     | 610/1387 [03:42<03:55,  3.29it/s]

 44%|████▍     | 611/1387 [03:42<04:21,  2.97it/s]

 44%|████▍     | 612/1387 [03:43<05:15,  2.45it/s]

 44%|████▍     | 613/1387 [03:43<05:31,  2.34it/s]

 44%|████▍     | 614/1387 [03:43<04:21,  2.95it/s]

 44%|████▍     | 615/1387 [03:44<05:19,  2.42it/s]

 44%|████▍     | 616/1387 [03:44<05:38,  2.28it/s]

 45%|████▍     | 618/1387 [03:44<03:31,  3.64it/s]

 45%|████▍     | 619/1387 [03:45<04:05,  3.13it/s]

 45%|████▍     | 620/1387 [03:46<05:10,  2.47it/s]

 45%|████▍     | 621/1387 [03:46<05:23,  2.37it/s]

 45%|████▍     | 623/1387 [03:47<05:04,  2.51it/s]

 45%|████▍     | 624/1387 [03:47<04:46,  2.66it/s]

 45%|████▌     | 625/1387 [03:47<03:58,  3.19it/s]

 45%|████▌     | 626/1387 [03:47<03:33,  3.57it/s]

 45%|████▌     | 627/1387 [03:48<03:56,  3.22it/s]

 45%|████▌     | 628/1387 [03:48<04:42,  2.69it/s]

 45%|████▌     | 629/1387 [03:49<05:14,  2.41it/s]

 45%|████▌     | 631/1387 [03:50<04:53,  2.57it/s]

 46%|████▌     | 632/1387 [03:50<04:25,  2.84it/s]

 46%|████▌     | 633/1387 [03:50<03:53,  3.23it/s]

 46%|████▌     | 634/1387 [03:50<03:35,  3.49it/s]

 46%|████▌     | 635/1387 [03:51<03:55,  3.19it/s]

 46%|████▌     | 636/1387 [03:51<04:25,  2.83it/s]

 46%|████▌     | 637/1387 [03:52<05:14,  2.38it/s]

 46%|████▌     | 639/1387 [03:52<05:20,  2.33it/s]

 46%|████▌     | 640/1387 [03:53<04:49,  2.58it/s]

 46%|████▋     | 642/1387 [03:53<03:48,  3.25it/s]

 46%|████▋     | 643/1387 [03:54<04:31,  2.74it/s]

 46%|████▋     | 644/1387 [03:54<05:00,  2.47it/s]

 47%|████▋     | 645/1387 [03:54<04:34,  2.71it/s]

 47%|████▋     | 646/1387 [03:55<04:30,  2.74it/s]

 47%|████▋     | 647/1387 [03:55<04:43,  2.61it/s]

 47%|████▋     | 648/1387 [03:55<04:10,  2.95it/s]

 47%|████▋     | 649/1387 [03:56<04:05,  3.00it/s]

 47%|████▋     | 650/1387 [03:56<03:41,  3.33it/s]

 47%|████▋     | 651/1387 [03:57<05:26,  2.25it/s]

 47%|████▋     | 652/1387 [03:57<05:22,  2.28it/s]

 47%|████▋     | 654/1387 [03:58<04:16,  2.85it/s]

 47%|████▋     | 655/1387 [03:58<05:08,  2.37it/s]

 47%|████▋     | 657/1387 [03:59<03:24,  3.57it/s]

 47%|████▋     | 658/1387 [03:59<03:44,  3.24it/s]

 48%|████▊     | 659/1387 [04:00<05:53,  2.06it/s]

 48%|████▊     | 660/1387 [04:00<05:02,  2.40it/s]

 48%|████▊     | 661/1387 [04:00<04:03,  2.99it/s]

 48%|████▊     | 662/1387 [04:01<04:46,  2.53it/s]

 48%|████▊     | 663/1387 [04:01<04:45,  2.53it/s]

 48%|████▊     | 665/1387 [04:01<03:10,  3.78it/s]

 48%|████▊     | 666/1387 [04:02<03:43,  3.23it/s]

 48%|████▊     | 667/1387 [04:03<06:06,  1.96it/s]

 48%|████▊     | 668/1387 [04:03<05:16,  2.27it/s]

 48%|████▊     | 669/1387 [04:03<04:14,  2.83it/s]

 48%|████▊     | 670/1387 [04:04<04:49,  2.48it/s]

 48%|████▊     | 671/1387 [04:04<04:42,  2.53it/s]

 48%|████▊     | 672/1387 [04:04<03:42,  3.21it/s]

 49%|████▊     | 674/1387 [04:05<03:46,  3.14it/s]

 49%|████▊     | 675/1387 [04:06<05:03,  2.34it/s]

 49%|████▊     | 676/1387 [04:06<04:54,  2.42it/s]

 49%|████▉     | 677/1387 [04:06<03:57,  2.99it/s]

 49%|████▉     | 678/1387 [04:07<04:11,  2.82it/s]

 49%|████▉     | 679/1387 [04:07<04:13,  2.80it/s]

 49%|████▉     | 680/1387 [04:07<03:29,  3.38it/s]

 49%|████▉     | 681/1387 [04:07<02:54,  4.04it/s]

 49%|████▉     | 682/1387 [04:08<03:53,  3.02it/s]

 49%|████▉     | 683/1387 [04:09<05:20,  2.20it/s]

 49%|████▉     | 684/1387 [04:09<05:12,  2.25it/s]

 49%|████▉     | 685/1387 [04:10<05:19,  2.20it/s]

 49%|████▉     | 686/1387 [04:10<04:34,  2.55it/s]

 50%|████▉     | 688/1387 [04:10<03:24,  3.42it/s]

 50%|████▉     | 689/1387 [04:11<03:44,  3.11it/s]

 50%|████▉     | 690/1387 [04:11<03:51,  3.01it/s]

 50%|████▉     | 691/1387 [04:12<05:15,  2.20it/s]

 50%|████▉     | 692/1387 [04:12<04:51,  2.39it/s]

 50%|████▉     | 693/1387 [04:12<04:39,  2.48it/s]

 50%|█████     | 694/1387 [04:13<04:21,  2.65it/s]

 50%|█████     | 695/1387 [04:13<03:34,  3.23it/s]

 50%|█████     | 696/1387 [04:13<03:39,  3.15it/s]

 50%|█████     | 697/1387 [04:14<03:59,  2.88it/s]

 50%|█████     | 698/1387 [04:14<04:39,  2.46it/s]

 50%|█████     | 699/1387 [04:15<04:49,  2.38it/s]

 50%|█████     | 700/1387 [04:15<04:12,  2.72it/s]

 51%|█████     | 701/1387 [04:15<04:56,  2.32it/s]

 51%|█████     | 703/1387 [04:16<04:04,  2.80it/s]

 51%|█████     | 705/1387 [04:16<03:43,  3.06it/s]

 51%|█████     | 706/1387 [04:17<03:58,  2.86it/s]

 51%|█████     | 707/1387 [04:17<04:34,  2.47it/s]

 51%|█████     | 708/1387 [04:18<03:49,  2.95it/s]

 51%|█████     | 709/1387 [04:18<04:21,  2.59it/s]

 51%|█████▏    | 711/1387 [04:19<03:47,  2.97it/s]

 51%|█████▏    | 712/1387 [04:19<03:11,  3.52it/s]

 51%|█████▏    | 713/1387 [04:19<03:34,  3.15it/s]

 51%|█████▏    | 714/1387 [04:20<04:05,  2.75it/s]

 52%|█████▏    | 715/1387 [04:20<04:49,  2.32it/s]

 52%|█████▏    | 717/1387 [04:21<04:11,  2.66it/s]

 52%|█████▏    | 719/1387 [04:21<03:44,  2.97it/s]

 52%|█████▏    | 720/1387 [04:22<03:19,  3.34it/s]

 52%|█████▏    | 721/1387 [04:22<03:22,  3.29it/s]

 52%|█████▏    | 722/1387 [04:23<04:10,  2.66it/s]

 52%|█████▏    | 723/1387 [04:23<04:33,  2.43it/s]

 52%|█████▏    | 724/1387 [04:23<03:38,  3.04it/s]

 52%|█████▏    | 725/1387 [04:24<04:14,  2.60it/s]

 52%|█████▏    | 726/1387 [04:24<04:01,  2.74it/s]

 52%|█████▏    | 727/1387 [04:24<03:58,  2.76it/s]

 52%|█████▏    | 728/1387 [04:25<03:31,  3.11it/s]

 53%|█████▎    | 729/1387 [04:25<02:59,  3.66it/s]

 53%|█████▎    | 730/1387 [04:26<05:35,  1.96it/s]

 53%|█████▎    | 731/1387 [04:26<04:22,  2.50it/s]

 53%|█████▎    | 732/1387 [04:26<03:33,  3.07it/s]

 53%|█████▎    | 733/1387 [04:27<03:45,  2.90it/s]

 53%|█████▎    | 734/1387 [04:27<04:53,  2.23it/s]

 53%|█████▎    | 735/1387 [04:27<03:57,  2.75it/s]

 53%|█████▎    | 736/1387 [04:28<03:42,  2.93it/s]

 53%|█████▎    | 738/1387 [04:29<04:56,  2.19it/s]

 53%|█████▎    | 739/1387 [04:29<04:07,  2.61it/s]

 53%|█████▎    | 740/1387 [04:29<03:39,  2.95it/s]

 53%|█████▎    | 741/1387 [04:29<03:03,  3.52it/s]

 53%|█████▎    | 742/1387 [04:30<04:16,  2.51it/s]

 54%|█████▎    | 743/1387 [04:30<03:51,  2.79it/s]

 54%|█████▎    | 744/1387 [04:31<03:28,  3.09it/s]

 54%|█████▍    | 746/1387 [04:32<04:42,  2.27it/s]

 54%|█████▍    | 747/1387 [04:32<04:02,  2.64it/s]

 54%|█████▍    | 748/1387 [04:32<03:27,  3.07it/s]

 54%|█████▍    | 750/1387 [04:33<03:43,  2.86it/s]

 54%|█████▍    | 751/1387 [04:33<03:41,  2.87it/s]

 54%|█████▍    | 752/1387 [04:33<03:05,  3.42it/s]

 54%|█████▍    | 753/1387 [04:33<02:40,  3.96it/s]

 54%|█████▍    | 754/1387 [04:35<05:15,  2.01it/s]

 54%|█████▍    | 755/1387 [04:35<04:17,  2.45it/s]

 55%|█████▍    | 756/1387 [04:35<03:34,  2.94it/s]

 55%|█████▍    | 758/1387 [04:36<03:59,  2.63it/s]

 55%|█████▍    | 759/1387 [04:36<03:37,  2.89it/s]

 55%|█████▍    | 761/1387 [04:36<02:56,  3.55it/s]

 55%|█████▍    | 762/1387 [04:37<04:34,  2.28it/s]

 55%|█████▌    | 763/1387 [04:38<03:53,  2.67it/s]

 55%|█████▌    | 764/1387 [04:38<03:43,  2.79it/s]

 55%|█████▌    | 766/1387 [04:39<03:46,  2.74it/s]

 55%|█████▌    | 767/1387 [04:39<03:18,  3.12it/s]

 55%|█████▌    | 769/1387 [04:39<02:59,  3.45it/s]

 56%|█████▌    | 770/1387 [04:40<04:34,  2.25it/s]

 56%|█████▌    | 771/1387 [04:41<04:03,  2.53it/s]

 56%|█████▌    | 772/1387 [04:41<03:29,  2.94it/s]

 56%|█████▌    | 774/1387 [04:41<03:35,  2.85it/s]

 56%|█████▌    | 775/1387 [04:42<03:19,  3.07it/s]

 56%|█████▌    | 777/1387 [04:42<03:22,  3.01it/s]

 56%|█████▌    | 778/1387 [04:43<04:18,  2.35it/s]

 56%|█████▌    | 779/1387 [04:44<04:21,  2.33it/s]

 56%|█████▋    | 782/1387 [04:44<03:16,  3.09it/s]

 56%|█████▋    | 783/1387 [04:45<03:27,  2.91it/s]

 57%|█████▋    | 785/1387 [04:45<03:40,  2.73it/s]

 57%|█████▋    | 786/1387 [04:46<03:57,  2.53it/s]

 57%|█████▋    | 787/1387 [04:46<04:08,  2.41it/s]

 57%|█████▋    | 788/1387 [04:47<03:25,  2.92it/s]

 57%|█████▋    | 790/1387 [04:47<03:05,  3.22it/s]

 57%|█████▋    | 791/1387 [04:47<03:02,  3.27it/s]

 57%|█████▋    | 792/1387 [04:48<03:00,  3.30it/s]

 57%|█████▋    | 793/1387 [04:48<03:46,  2.62it/s]

 57%|█████▋    | 794/1387 [04:49<04:19,  2.29it/s]

 57%|█████▋    | 795/1387 [04:49<04:20,  2.27it/s]

 57%|█████▋    | 797/1387 [04:50<03:02,  3.24it/s]

 58%|█████▊    | 798/1387 [04:50<03:11,  3.07it/s]

 58%|█████▊    | 799/1387 [04:50<02:42,  3.62it/s]

 58%|█████▊    | 800/1387 [04:51<03:01,  3.24it/s]

 58%|█████▊    | 801/1387 [04:51<04:00,  2.44it/s]

 58%|█████▊    | 802/1387 [04:52<04:36,  2.11it/s]

 58%|█████▊    | 803/1387 [04:52<04:00,  2.42it/s]

 58%|█████▊    | 805/1387 [04:52<02:50,  3.41it/s]

 58%|█████▊    | 806/1387 [04:53<03:12,  3.01it/s]

 58%|█████▊    | 807/1387 [04:53<02:49,  3.43it/s]

 58%|█████▊    | 808/1387 [04:53<03:02,  3.17it/s]

 58%|█████▊    | 809/1387 [04:54<03:58,  2.42it/s]

 58%|█████▊    | 810/1387 [04:55<04:36,  2.09it/s]

 58%|█████▊    | 811/1387 [04:55<04:01,  2.39it/s]

 59%|█████▊    | 813/1387 [04:55<02:45,  3.48it/s]

 59%|█████▊    | 814/1387 [04:56<03:23,  2.82it/s]

 59%|█████▉    | 815/1387 [04:56<02:52,  3.32it/s]

 59%|█████▉    | 816/1387 [04:56<02:56,  3.23it/s]

 59%|█████▉    | 817/1387 [04:57<04:14,  2.24it/s]

 59%|█████▉    | 818/1387 [04:58<04:29,  2.11it/s]

 59%|█████▉    | 820/1387 [04:58<03:13,  2.93it/s]

 59%|█████▉    | 822/1387 [04:59<03:12,  2.93it/s]

 59%|█████▉    | 823/1387 [04:59<02:57,  3.17it/s]

 59%|█████▉    | 824/1387 [04:59<03:16,  2.87it/s]

 59%|█████▉    | 825/1387 [05:00<03:58,  2.36it/s]

 60%|█████▉    | 826/1387 [05:00<04:08,  2.25it/s]

 60%|█████▉    | 828/1387 [05:01<03:47,  2.46it/s]

 60%|█████▉    | 830/1387 [05:01<02:42,  3.44it/s]

 60%|█████▉    | 831/1387 [05:02<02:53,  3.21it/s]

 60%|█████▉    | 832/1387 [05:02<03:37,  2.56it/s]

 60%|██████    | 833/1387 [05:03<03:39,  2.52it/s]

 60%|██████    | 834/1387 [05:03<04:01,  2.29it/s]

 60%|██████    | 835/1387 [05:04<03:49,  2.40it/s]

 60%|██████    | 836/1387 [05:04<03:24,  2.69it/s]

 60%|██████    | 837/1387 [05:04<02:53,  3.16it/s]

 60%|██████    | 838/1387 [05:04<02:36,  3.51it/s]

 60%|██████    | 839/1387 [05:05<03:37,  2.51it/s]

 61%|██████    | 840/1387 [05:05<03:29,  2.61it/s]

 61%|██████    | 841/1387 [05:06<04:12,  2.16it/s]

 61%|██████    | 842/1387 [05:06<04:05,  2.22it/s]

 61%|██████    | 843/1387 [05:07<03:24,  2.66it/s]

 61%|██████    | 844/1387 [05:07<02:53,  3.13it/s]

 61%|██████    | 845/1387 [05:07<03:22,  2.67it/s]

 61%|██████    | 847/1387 [05:08<02:50,  3.17it/s]

 61%|██████    | 848/1387 [05:08<03:26,  2.61it/s]

 61%|██████    | 849/1387 [05:09<04:08,  2.17it/s]

 61%|██████▏   | 850/1387 [05:09<03:41,  2.43it/s]

 61%|██████▏   | 851/1387 [05:10<03:08,  2.85it/s]

 61%|██████▏   | 852/1387 [05:10<03:06,  2.86it/s]

 61%|██████▏   | 853/1387 [05:10<03:13,  2.77it/s]

 62%|██████▏   | 854/1387 [05:10<02:33,  3.48it/s]

 62%|██████▏   | 855/1387 [05:11<02:31,  3.51it/s]

 62%|██████▏   | 856/1387 [05:11<03:11,  2.77it/s]

 62%|██████▏   | 857/1387 [05:12<04:17,  2.06it/s]

 62%|██████▏   | 858/1387 [05:13<04:15,  2.07it/s]

 62%|██████▏   | 859/1387 [05:13<03:46,  2.33it/s]

 62%|██████▏   | 861/1387 [05:13<02:35,  3.38it/s]

 62%|██████▏   | 862/1387 [05:14<02:49,  3.09it/s]

 62%|██████▏   | 864/1387 [05:14<03:21,  2.60it/s]

 62%|██████▏   | 865/1387 [05:15<03:40,  2.37it/s]

 62%|██████▏   | 866/1387 [05:16<04:09,  2.09it/s]

 63%|██████▎   | 867/1387 [05:16<03:33,  2.43it/s]

 63%|██████▎   | 868/1387 [05:16<02:49,  3.06it/s]

 63%|██████▎   | 869/1387 [05:16<02:29,  3.46it/s]

 63%|██████▎   | 870/1387 [05:17<02:40,  3.23it/s]

 63%|██████▎   | 871/1387 [05:17<02:09,  3.99it/s]

 63%|██████▎   | 872/1387 [05:17<03:02,  2.83it/s]

 63%|██████▎   | 873/1387 [05:18<03:55,  2.18it/s]

 63%|██████▎   | 874/1387 [05:18<04:04,  2.10it/s]

 63%|██████▎   | 875/1387 [05:19<03:48,  2.24it/s]

 63%|██████▎   | 876/1387 [05:19<02:56,  2.89it/s]

 63%|██████▎   | 878/1387 [05:20<02:36,  3.25it/s]

 63%|██████▎   | 879/1387 [05:20<02:23,  3.55it/s]

 63%|██████▎   | 880/1387 [05:20<03:04,  2.75it/s]

 64%|██████▎   | 881/1387 [05:21<03:46,  2.24it/s]

 64%|██████▎   | 882/1387 [05:21<03:32,  2.38it/s]

 64%|██████▎   | 883/1387 [05:22<03:14,  2.59it/s]

 64%|██████▎   | 884/1387 [05:22<02:49,  2.96it/s]

 64%|██████▍   | 886/1387 [05:22<02:25,  3.44it/s]

 64%|██████▍   | 887/1387 [05:22<02:07,  3.91it/s]

 64%|██████▍   | 888/1387 [05:23<03:03,  2.71it/s]

 64%|██████▍   | 889/1387 [05:24<03:46,  2.19it/s]

 64%|██████▍   | 890/1387 [05:24<03:22,  2.45it/s]

 64%|██████▍   | 891/1387 [05:24<03:09,  2.62it/s]

 64%|██████▍   | 892/1387 [05:25<02:47,  2.96it/s]

 64%|██████▍   | 893/1387 [05:25<02:13,  3.70it/s]

 64%|██████▍   | 894/1387 [05:25<02:27,  3.34it/s]

 65%|██████▍   | 896/1387 [05:26<02:59,  2.74it/s]

 65%|██████▍   | 897/1387 [05:27<03:34,  2.28it/s]

 65%|██████▍   | 898/1387 [05:27<03:14,  2.51it/s]

 65%|██████▍   | 899/1387 [05:27<03:21,  2.42it/s]

 65%|██████▍   | 900/1387 [05:28<02:48,  2.89it/s]

 65%|██████▌   | 902/1387 [05:28<02:07,  3.80it/s]

 65%|██████▌   | 903/1387 [05:28<02:01,  3.98it/s]

 65%|██████▌   | 904/1387 [05:29<03:41,  2.18it/s]

 65%|██████▌   | 905/1387 [05:30<03:35,  2.24it/s]

 65%|██████▌   | 906/1387 [05:30<03:32,  2.26it/s]

 65%|██████▌   | 907/1387 [05:30<02:56,  2.73it/s]

 65%|██████▌   | 908/1387 [05:30<02:33,  3.13it/s]

 66%|██████▌   | 910/1387 [05:31<02:31,  3.15it/s]

 66%|██████▌   | 912/1387 [05:32<03:04,  2.58it/s]

 66%|██████▌   | 913/1387 [05:33<03:12,  2.46it/s]

 66%|██████▌   | 914/1387 [05:33<03:08,  2.51it/s]

 66%|██████▌   | 915/1387 [05:33<02:48,  2.80it/s]

 66%|██████▌   | 916/1387 [05:33<02:48,  2.80it/s]

 66%|██████▌   | 917/1387 [05:34<02:20,  3.35it/s]

 66%|██████▌   | 918/1387 [05:34<02:45,  2.83it/s]

 66%|██████▋   | 920/1387 [05:35<02:53,  2.69it/s]

 66%|██████▋   | 921/1387 [05:35<03:03,  2.53it/s]

 66%|██████▋   | 922/1387 [05:36<03:12,  2.42it/s]

 67%|██████▋   | 923/1387 [05:36<02:59,  2.58it/s]

 67%|██████▋   | 924/1387 [05:36<02:39,  2.90it/s]

 67%|██████▋   | 925/1387 [05:37<02:34,  2.98it/s]

 67%|██████▋   | 926/1387 [05:37<02:15,  3.40it/s]

 67%|██████▋   | 927/1387 [05:37<02:07,  3.61it/s]

 67%|██████▋   | 928/1387 [05:38<03:07,  2.45it/s]

 67%|██████▋   | 929/1387 [05:38<03:36,  2.12it/s]

 67%|██████▋   | 930/1387 [05:39<03:04,  2.48it/s]

 67%|██████▋   | 931/1387 [05:39<02:44,  2.77it/s]

 67%|██████▋   | 932/1387 [05:39<02:29,  3.03it/s]

 67%|██████▋   | 933/1387 [05:40<02:21,  3.20it/s]

 67%|██████▋   | 934/1387 [05:40<02:33,  2.96it/s]

 67%|██████▋   | 936/1387 [05:41<02:46,  2.70it/s]

 68%|██████▊   | 937/1387 [05:42<03:34,  2.09it/s]

 68%|██████▊   | 938/1387 [05:42<02:57,  2.53it/s]

 68%|██████▊   | 939/1387 [05:42<02:52,  2.60it/s]

 68%|██████▊   | 940/1387 [05:42<02:27,  3.03it/s]

 68%|██████▊   | 941/1387 [05:42<02:15,  3.28it/s]

 68%|██████▊   | 942/1387 [05:43<02:20,  3.17it/s]

 68%|██████▊   | 944/1387 [05:44<03:04,  2.40it/s]

 68%|██████▊   | 945/1387 [05:44<03:08,  2.35it/s]

 68%|██████▊   | 946/1387 [05:45<03:17,  2.23it/s]

 68%|██████▊   | 948/1387 [05:45<02:12,  3.31it/s]

 68%|██████▊   | 949/1387 [05:45<02:00,  3.62it/s]

 68%|██████▊   | 950/1387 [05:46<02:36,  2.80it/s]

 69%|██████▊   | 951/1387 [05:46<02:31,  2.88it/s]

 69%|██████▊   | 952/1387 [05:47<03:16,  2.22it/s]

 69%|██████▊   | 953/1387 [05:47<02:52,  2.52it/s]

 69%|██████▉   | 954/1387 [05:48<03:16,  2.20it/s]

 69%|██████▉   | 955/1387 [05:48<03:06,  2.31it/s]

 69%|██████▉   | 956/1387 [05:48<02:25,  2.96it/s]

 69%|██████▉   | 958/1387 [05:49<02:29,  2.86it/s]

 69%|██████▉   | 959/1387 [05:49<02:08,  3.34it/s]

 69%|██████▉   | 960/1387 [05:50<03:07,  2.27it/s]

 69%|██████▉   | 961/1387 [05:50<02:28,  2.87it/s]

 69%|██████▉   | 962/1387 [05:51<02:57,  2.39it/s]

 69%|██████▉   | 963/1387 [05:51<02:37,  2.70it/s]

 70%|██████▉   | 964/1387 [05:51<02:33,  2.75it/s]

 70%|██████▉   | 966/1387 [05:52<02:13,  3.16it/s]

 70%|██████▉   | 967/1387 [05:52<02:13,  3.15it/s]

 70%|██████▉   | 968/1387 [05:53<03:11,  2.19it/s]

 70%|██████▉   | 970/1387 [05:53<02:31,  2.75it/s]

 70%|███████   | 971/1387 [05:54<02:31,  2.74it/s]

 70%|███████   | 972/1387 [05:54<02:18,  3.00it/s]

 70%|███████   | 973/1387 [05:54<01:57,  3.52it/s]

 70%|███████   | 974/1387 [05:55<02:03,  3.36it/s]

 70%|███████   | 975/1387 [05:55<02:13,  3.08it/s]

 70%|███████   | 976/1387 [05:56<03:21,  2.04it/s]

 70%|███████   | 977/1387 [05:56<02:34,  2.65it/s]

 71%|███████   | 978/1387 [05:56<02:32,  2.67it/s]

 71%|███████   | 979/1387 [05:57<02:40,  2.55it/s]

 71%|███████   | 980/1387 [05:57<02:14,  3.02it/s]

 71%|███████   | 981/1387 [05:57<02:03,  3.30it/s]

 71%|███████   | 982/1387 [05:57<01:47,  3.76it/s]

 71%|███████   | 983/1387 [05:58<02:10,  3.09it/s]

 71%|███████   | 984/1387 [05:59<03:13,  2.08it/s]

 71%|███████   | 985/1387 [05:59<02:33,  2.63it/s]

 71%|███████   | 986/1387 [05:59<03:04,  2.17it/s]

 71%|███████   | 987/1387 [06:00<02:22,  2.80it/s]

 71%|███████   | 988/1387 [06:00<02:00,  3.32it/s]

 71%|███████▏  | 989/1387 [06:00<02:38,  2.51it/s]

 71%|███████▏  | 990/1387 [06:01<02:10,  3.04it/s]

 71%|███████▏  | 991/1387 [06:01<02:01,  3.26it/s]

 72%|███████▏  | 992/1387 [06:02<02:59,  2.20it/s]

 72%|███████▏  | 993/1387 [06:02<02:51,  2.30it/s]

 72%|███████▏  | 994/1387 [06:02<02:44,  2.39it/s]

 72%|███████▏  | 996/1387 [06:03<02:07,  3.07it/s]

 72%|███████▏  | 997/1387 [06:03<02:17,  2.84it/s]

 72%|███████▏  | 998/1387 [06:04<02:18,  2.81it/s]

 72%|███████▏  | 999/1387 [06:04<01:55,  3.35it/s]

 72%|███████▏  | 1000/1387 [06:05<03:07,  2.07it/s]

 72%|███████▏  | 1001/1387 [06:05<02:31,  2.55it/s]

 72%|███████▏  | 1002/1387 [06:05<02:55,  2.20it/s]

 72%|███████▏  | 1003/1387 [06:06<02:28,  2.58it/s]

 72%|███████▏  | 1004/1387 [06:06<02:03,  3.10it/s]

 72%|███████▏  | 1005/1387 [06:06<01:54,  3.34it/s]

 73%|███████▎  | 1006/1387 [06:07<02:25,  2.61it/s]

 73%|███████▎  | 1008/1387 [06:08<02:44,  2.30it/s]

 73%|███████▎  | 1010/1387 [06:08<02:30,  2.50it/s]

 73%|███████▎  | 1011/1387 [06:08<02:08,  2.93it/s]

 73%|███████▎  | 1012/1387 [06:09<02:02,  3.06it/s]

 73%|███████▎  | 1013/1387 [06:09<01:47,  3.48it/s]

 73%|███████▎  | 1014/1387 [06:10<02:25,  2.56it/s]

 73%|███████▎  | 1016/1387 [06:10<02:31,  2.45it/s]

 73%|███████▎  | 1017/1387 [06:11<02:16,  2.70it/s]

 73%|███████▎  | 1018/1387 [06:11<02:20,  2.63it/s]

 73%|███████▎  | 1019/1387 [06:11<02:12,  2.78it/s]

 74%|███████▎  | 1020/1387 [06:12<02:09,  2.83it/s]

 74%|███████▎  | 1021/1387 [06:12<01:53,  3.22it/s]

 74%|███████▎  | 1022/1387 [06:12<02:11,  2.77it/s]

 74%|███████▍  | 1024/1387 [06:13<02:19,  2.59it/s]

 74%|███████▍  | 1025/1387 [06:14<02:11,  2.75it/s]

 74%|███████▍  | 1026/1387 [06:14<02:16,  2.65it/s]

 74%|███████▍  | 1027/1387 [06:14<02:04,  2.89it/s]

 74%|███████▍  | 1028/1387 [06:15<02:24,  2.48it/s]

 74%|███████▍  | 1030/1387 [06:15<01:56,  3.06it/s]

 74%|███████▍  | 1032/1387 [06:16<02:26,  2.43it/s]

 74%|███████▍  | 1033/1387 [06:16<02:03,  2.86it/s]

 75%|███████▍  | 1034/1387 [06:17<02:14,  2.62it/s]

 75%|███████▍  | 1035/1387 [06:17<02:12,  2.66it/s]

 75%|███████▍  | 1036/1387 [06:18<02:00,  2.92it/s]

 75%|███████▍  | 1037/1387 [06:18<01:40,  3.47it/s]

 75%|███████▍  | 1038/1387 [06:18<01:52,  3.09it/s]

 75%|███████▍  | 1039/1387 [06:18<01:44,  3.32it/s]

 75%|███████▍  | 1040/1387 [06:19<02:43,  2.12it/s]

 75%|███████▌  | 1042/1387 [06:20<02:20,  2.45it/s]

 75%|███████▌  | 1043/1387 [06:20<02:23,  2.40it/s]

 75%|███████▌  | 1044/1387 [06:21<02:00,  2.84it/s]

 75%|███████▌  | 1046/1387 [06:21<01:49,  3.11it/s]

 75%|███████▌  | 1047/1387 [06:21<01:33,  3.64it/s]

 76%|███████▌  | 1048/1387 [06:22<02:44,  2.06it/s]

 76%|███████▌  | 1050/1387 [06:23<02:07,  2.65it/s]

 76%|███████▌  | 1051/1387 [06:23<02:23,  2.34it/s]

 76%|███████▌  | 1053/1387 [06:24<01:34,  3.54it/s]

 76%|███████▌  | 1054/1387 [06:24<01:55,  2.88it/s]

 76%|███████▌  | 1056/1387 [06:25<02:22,  2.32it/s]

 76%|███████▋  | 1058/1387 [06:26<01:57,  2.81it/s]

 76%|███████▋  | 1059/1387 [06:26<02:05,  2.61it/s]

 76%|███████▋  | 1060/1387 [06:27<02:08,  2.54it/s]

 77%|███████▋  | 1062/1387 [06:27<01:44,  3.10it/s]

 77%|███████▋  | 1064/1387 [06:28<02:09,  2.50it/s]

 77%|███████▋  | 1065/1387 [06:28<01:51,  2.88it/s]

 77%|███████▋  | 1066/1387 [06:29<01:50,  2.91it/s]

 77%|███████▋  | 1067/1387 [06:29<01:56,  2.76it/s]

 77%|███████▋  | 1068/1387 [06:30<02:24,  2.21it/s]

 77%|███████▋  | 1069/1387 [06:30<01:58,  2.67it/s]

 77%|███████▋  | 1072/1387 [06:31<01:54,  2.74it/s]

 77%|███████▋  | 1073/1387 [06:31<02:00,  2.61it/s]

 78%|███████▊  | 1075/1387 [06:32<01:56,  2.67it/s]

 78%|███████▊  | 1076/1387 [06:33<02:06,  2.47it/s]

 78%|███████▊  | 1078/1387 [06:33<01:27,  3.54it/s]

 78%|███████▊  | 1080/1387 [06:34<02:17,  2.24it/s]

 78%|███████▊  | 1082/1387 [06:35<01:54,  2.65it/s]

 78%|███████▊  | 1083/1387 [06:35<01:44,  2.92it/s]

 78%|███████▊  | 1084/1387 [06:35<01:53,  2.66it/s]

 78%|███████▊  | 1086/1387 [06:36<01:29,  3.36it/s]

 78%|███████▊  | 1087/1387 [06:36<01:33,  3.20it/s]

 78%|███████▊  | 1088/1387 [06:37<02:25,  2.06it/s]

 79%|███████▊  | 1089/1387 [06:37<01:57,  2.54it/s]

 79%|███████▊  | 1090/1387 [06:38<01:43,  2.87it/s]

 79%|███████▊  | 1091/1387 [06:38<01:25,  3.45it/s]

 79%|███████▊  | 1092/1387 [06:38<02:05,  2.36it/s]

 79%|███████▉  | 1093/1387 [06:39<01:38,  2.99it/s]

 79%|███████▉  | 1094/1387 [06:39<01:32,  3.17it/s]

 79%|███████▉  | 1095/1387 [06:39<01:21,  3.58it/s]

 79%|███████▉  | 1096/1387 [06:40<02:36,  1.86it/s]

 79%|███████▉  | 1098/1387 [06:40<01:37,  2.96it/s]

 79%|███████▉  | 1099/1387 [06:41<01:30,  3.17it/s]

 79%|███████▉  | 1100/1387 [06:41<02:04,  2.31it/s]

 79%|███████▉  | 1102/1387 [06:42<01:21,  3.48it/s]

 80%|███████▉  | 1103/1387 [06:42<01:33,  3.04it/s]

 80%|███████▉  | 1104/1387 [06:43<02:22,  1.98it/s]

 80%|███████▉  | 1105/1387 [06:43<01:58,  2.38it/s]

 80%|███████▉  | 1106/1387 [06:43<01:33,  3.01it/s]

 80%|███████▉  | 1107/1387 [06:43<01:16,  3.64it/s]

 80%|███████▉  | 1108/1387 [06:44<01:53,  2.46it/s]

 80%|███████▉  | 1109/1387 [06:44<01:30,  3.07it/s]

 80%|████████  | 1110/1387 [06:45<01:26,  3.21it/s]

 80%|████████  | 1111/1387 [06:45<01:31,  3.00it/s]

 80%|████████  | 1112/1387 [06:46<02:14,  2.04it/s]

 80%|████████  | 1113/1387 [06:46<01:58,  2.32it/s]

 80%|████████  | 1115/1387 [06:46<01:09,  3.89it/s]

 80%|████████  | 1116/1387 [06:47<01:48,  2.50it/s]

 81%|████████  | 1117/1387 [06:47<01:37,  2.77it/s]

 81%|████████  | 1119/1387 [06:48<01:23,  3.22it/s]

 81%|████████  | 1120/1387 [06:49<02:12,  2.02it/s]

 81%|████████  | 1122/1387 [06:49<01:31,  2.91it/s]

 81%|████████  | 1124/1387 [06:50<01:41,  2.60it/s]

 81%|████████  | 1125/1387 [06:50<01:33,  2.80it/s]

 81%|████████  | 1126/1387 [06:51<01:35,  2.74it/s]

 81%|████████▏ | 1128/1387 [06:52<01:51,  2.33it/s]

 81%|████████▏ | 1129/1387 [06:52<01:46,  2.42it/s]

 82%|████████▏ | 1131/1387 [06:52<01:10,  3.61it/s]

 82%|████████▏ | 1132/1387 [06:53<01:51,  2.29it/s]

 82%|████████▏ | 1134/1387 [06:54<01:19,  3.17it/s]

 82%|████████▏ | 1135/1387 [06:54<01:28,  2.85it/s]

 82%|████████▏ | 1136/1387 [06:55<01:46,  2.36it/s]

 82%|████████▏ | 1137/1387 [06:55<01:40,  2.48it/s]

 82%|████████▏ | 1138/1387 [06:55<01:22,  3.00it/s]

 82%|████████▏ | 1140/1387 [06:56<01:39,  2.48it/s]

 82%|████████▏ | 1141/1387 [06:56<01:23,  2.94it/s]

 82%|████████▏ | 1142/1387 [06:56<01:14,  3.27it/s]

 82%|████████▏ | 1143/1387 [06:57<01:22,  2.97it/s]

 82%|████████▏ | 1144/1387 [06:58<01:45,  2.29it/s]

 83%|████████▎ | 1145/1387 [06:58<01:28,  2.72it/s]

 83%|████████▎ | 1146/1387 [06:58<01:18,  3.09it/s]

 83%|████████▎ | 1148/1387 [06:59<01:33,  2.55it/s]

 83%|████████▎ | 1149/1387 [06:59<01:18,  3.04it/s]

 83%|████████▎ | 1150/1387 [06:59<01:13,  3.24it/s]

 83%|████████▎ | 1151/1387 [07:00<01:14,  3.16it/s]

 83%|████████▎ | 1152/1387 [07:01<01:50,  2.12it/s]

 83%|████████▎ | 1154/1387 [07:01<01:13,  3.16it/s]

 83%|████████▎ | 1156/1387 [07:02<01:26,  2.67it/s]

 83%|████████▎ | 1157/1387 [07:02<01:16,  2.99it/s]

 83%|████████▎ | 1158/1387 [07:02<01:17,  2.94it/s]

 84%|████████▎ | 1159/1387 [07:03<01:16,  2.98it/s]

 84%|████████▎ | 1160/1387 [07:04<01:55,  1.97it/s]

 84%|████████▍ | 1162/1387 [07:04<01:15,  2.98it/s]

 84%|████████▍ | 1164/1387 [07:05<01:24,  2.63it/s]

 84%|████████▍ | 1165/1387 [07:05<01:22,  2.70it/s]

 84%|████████▍ | 1166/1387 [07:05<01:16,  2.90it/s]

 84%|████████▍ | 1167/1387 [07:05<01:07,  3.27it/s]

 84%|████████▍ | 1168/1387 [07:06<01:42,  2.14it/s]

 84%|████████▍ | 1169/1387 [07:07<01:30,  2.40it/s]

 84%|████████▍ | 1170/1387 [07:07<01:30,  2.41it/s]

 84%|████████▍ | 1172/1387 [07:08<01:22,  2.62it/s]

 85%|████████▍ | 1173/1387 [07:08<01:12,  2.95it/s]

 85%|████████▍ | 1174/1387 [07:08<01:03,  3.34it/s]

 85%|████████▍ | 1175/1387 [07:08<01:00,  3.50it/s]

 85%|████████▍ | 1176/1387 [07:09<01:28,  2.37it/s]

 85%|████████▍ | 1177/1387 [07:10<01:46,  1.98it/s]

 85%|████████▌ | 1179/1387 [07:10<01:16,  2.71it/s]

 85%|████████▌ | 1180/1387 [07:11<01:20,  2.59it/s]

 85%|████████▌ | 1182/1387 [07:11<01:01,  3.33it/s]

 85%|████████▌ | 1183/1387 [07:12<01:09,  2.93it/s]

 85%|████████▌ | 1184/1387 [07:12<01:21,  2.48it/s]

 85%|████████▌ | 1185/1387 [07:13<01:33,  2.16it/s]

 86%|████████▌ | 1187/1387 [07:13<01:05,  3.04it/s]

 86%|████████▌ | 1188/1387 [07:14<01:15,  2.63it/s]

 86%|████████▌ | 1190/1387 [07:14<00:58,  3.37it/s]

 86%|████████▌ | 1191/1387 [07:14<01:02,  3.11it/s]

 86%|████████▌ | 1192/1387 [07:15<01:14,  2.61it/s]

 86%|████████▌ | 1193/1387 [07:16<01:26,  2.24it/s]

 86%|████████▌ | 1195/1387 [07:16<00:59,  3.22it/s]

 86%|████████▌ | 1196/1387 [07:16<01:11,  2.69it/s]

 86%|████████▋ | 1198/1387 [07:17<00:56,  3.35it/s]

 86%|████████▋ | 1199/1387 [07:17<00:59,  3.13it/s]

 87%|████████▋ | 1200/1387 [07:18<01:11,  2.60it/s]

 87%|████████▋ | 1201/1387 [07:18<01:22,  2.25it/s]

 87%|████████▋ | 1202/1387 [07:19<01:07,  2.74it/s]

 87%|████████▋ | 1204/1387 [07:19<01:02,  2.92it/s]

 87%|████████▋ | 1205/1387 [07:19<00:58,  3.14it/s]

 87%|████████▋ | 1206/1387 [07:20<00:56,  3.20it/s]

 87%|████████▋ | 1207/1387 [07:20<01:12,  2.47it/s]

 87%|████████▋ | 1208/1387 [07:21<01:08,  2.60it/s]

 87%|████████▋ | 1209/1387 [07:21<01:18,  2.26it/s]

 87%|████████▋ | 1210/1387 [07:22<01:07,  2.64it/s]

 87%|████████▋ | 1211/1387 [07:22<00:59,  2.94it/s]

 87%|████████▋ | 1212/1387 [07:22<00:51,  3.41it/s]

 87%|████████▋ | 1213/1387 [07:23<01:14,  2.32it/s]

 88%|████████▊ | 1214/1387 [07:23<01:06,  2.61it/s]

 88%|████████▊ | 1215/1387 [07:23<01:11,  2.39it/s]

 88%|████████▊ | 1216/1387 [07:24<00:56,  3.03it/s]

 88%|████████▊ | 1217/1387 [07:24<01:00,  2.81it/s]

 88%|████████▊ | 1218/1387 [07:25<01:13,  2.29it/s]

 88%|████████▊ | 1219/1387 [07:25<00:58,  2.89it/s]

 88%|████████▊ | 1220/1387 [07:25<00:45,  3.66it/s]

 88%|████████▊ | 1221/1387 [07:26<01:08,  2.41it/s]

 88%|████████▊ | 1222/1387 [07:26<01:15,  2.17it/s]

 88%|████████▊ | 1223/1387 [07:27<01:09,  2.35it/s]

 88%|████████▊ | 1224/1387 [07:27<00:55,  2.95it/s]

 88%|████████▊ | 1225/1387 [07:27<00:43,  3.74it/s]

 88%|████████▊ | 1226/1387 [07:28<01:07,  2.39it/s]

 88%|████████▊ | 1227/1387 [07:28<00:52,  3.02it/s]

 89%|████████▊ | 1228/1387 [07:28<00:51,  3.07it/s]

 89%|████████▊ | 1229/1387 [07:29<01:08,  2.29it/s]

 89%|████████▊ | 1230/1387 [07:29<01:12,  2.18it/s]

 89%|████████▉ | 1231/1387 [07:29<01:00,  2.59it/s]

 89%|████████▉ | 1232/1387 [07:30<00:47,  3.27it/s]

 89%|████████▉ | 1233/1387 [07:30<00:37,  4.10it/s]

 89%|████████▉ | 1234/1387 [07:30<00:57,  2.67it/s]

 89%|████████▉ | 1235/1387 [07:31<00:51,  2.94it/s]

 89%|████████▉ | 1236/1387 [07:31<00:45,  3.33it/s]

 89%|████████▉ | 1237/1387 [07:32<01:04,  2.34it/s]

 89%|████████▉ | 1238/1387 [07:32<01:12,  2.05it/s]

 89%|████████▉ | 1240/1387 [07:32<00:47,  3.08it/s]

 90%|████████▉ | 1242/1387 [07:33<00:47,  3.08it/s]

 90%|████████▉ | 1243/1387 [07:33<00:48,  2.96it/s]

 90%|████████▉ | 1244/1387 [07:34<00:43,  3.32it/s]

 90%|████████▉ | 1245/1387 [07:34<00:59,  2.39it/s]

 90%|████████▉ | 1246/1387 [07:35<01:05,  2.16it/s]

 90%|████████▉ | 1247/1387 [07:35<00:52,  2.66it/s]

 90%|█████████ | 1249/1387 [07:35<00:36,  3.78it/s]

 90%|█████████ | 1250/1387 [07:36<00:46,  2.96it/s]

 90%|█████████ | 1251/1387 [07:36<00:46,  2.93it/s]

 90%|█████████ | 1252/1387 [07:37<00:44,  3.06it/s]

 90%|█████████ | 1253/1387 [07:37<01:02,  2.14it/s]

 90%|█████████ | 1254/1387 [07:38<01:00,  2.20it/s]

 90%|█████████ | 1255/1387 [07:38<00:52,  2.51it/s]

 91%|█████████ | 1257/1387 [07:38<00:33,  3.92it/s]

 91%|█████████ | 1258/1387 [07:39<00:44,  2.93it/s]

 91%|█████████ | 1259/1387 [07:39<00:46,  2.74it/s]

 91%|█████████ | 1260/1387 [07:40<00:41,  3.03it/s]

 91%|█████████ | 1261/1387 [07:40<00:58,  2.15it/s]

 91%|█████████ | 1262/1387 [07:41<00:57,  2.16it/s]

 91%|█████████ | 1263/1387 [07:41<00:46,  2.64it/s]

 91%|█████████ | 1264/1387 [07:41<00:41,  3.00it/s]

 91%|█████████▏| 1266/1387 [07:42<00:39,  3.03it/s]

 91%|█████████▏| 1267/1387 [07:42<00:46,  2.56it/s]

 91%|█████████▏| 1268/1387 [07:43<00:40,  2.91it/s]

 91%|█████████▏| 1269/1387 [07:43<00:46,  2.53it/s]

 92%|█████████▏| 1270/1387 [07:44<00:49,  2.35it/s]

 92%|█████████▏| 1271/1387 [07:44<00:45,  2.54it/s]

 92%|█████████▏| 1272/1387 [07:44<00:37,  3.07it/s]

 92%|█████████▏| 1274/1387 [07:45<00:32,  3.44it/s]

 92%|█████████▏| 1275/1387 [07:45<00:46,  2.39it/s]

 92%|█████████▏| 1276/1387 [07:46<00:39,  2.84it/s]

 92%|█████████▏| 1277/1387 [07:46<00:40,  2.74it/s]

 92%|█████████▏| 1278/1387 [07:47<00:44,  2.47it/s]

 92%|█████████▏| 1279/1387 [07:47<00:39,  2.76it/s]

 92%|█████████▏| 1280/1387 [07:47<00:36,  2.97it/s]

 92%|█████████▏| 1281/1387 [07:47<00:29,  3.55it/s]

 92%|█████████▏| 1282/1387 [07:47<00:28,  3.62it/s]

 93%|█████████▎| 1283/1387 [07:48<00:44,  2.31it/s]

 93%|█████████▎| 1284/1387 [07:48<00:35,  2.90it/s]

 93%|█████████▎| 1285/1387 [07:49<00:39,  2.59it/s]

 93%|█████████▎| 1286/1387 [07:50<00:50,  1.98it/s]

 93%|█████████▎| 1287/1387 [07:50<00:38,  2.61it/s]

 93%|█████████▎| 1289/1387 [07:50<00:28,  3.38it/s]

 93%|█████████▎| 1291/1387 [07:51<00:35,  2.72it/s]

 93%|█████████▎| 1292/1387 [07:51<00:31,  3.03it/s]

 93%|█████████▎| 1293/1387 [07:52<00:39,  2.36it/s]

 93%|█████████▎| 1294/1387 [07:53<00:41,  2.27it/s]

 93%|█████████▎| 1296/1387 [07:53<00:28,  3.16it/s]

 94%|█████████▎| 1297/1387 [07:53<00:27,  3.33it/s]

 94%|█████████▎| 1298/1387 [07:53<00:28,  3.09it/s]

 94%|█████████▎| 1299/1387 [07:54<00:37,  2.36it/s]

 94%|█████████▎| 1300/1387 [07:55<00:38,  2.25it/s]

 94%|█████████▍| 1301/1387 [07:55<00:32,  2.66it/s]

 94%|█████████▍| 1302/1387 [07:55<00:37,  2.29it/s]

 94%|█████████▍| 1303/1387 [07:56<00:36,  2.28it/s]

 94%|█████████▍| 1306/1387 [07:56<00:23,  3.45it/s]

 94%|█████████▍| 1307/1387 [07:57<00:34,  2.34it/s]

 94%|█████████▍| 1308/1387 [07:58<00:28,  2.73it/s]

 94%|█████████▍| 1309/1387 [07:58<00:30,  2.52it/s]

 94%|█████████▍| 1310/1387 [07:58<00:28,  2.74it/s]

 95%|█████████▍| 1311/1387 [07:59<00:27,  2.81it/s]

 95%|█████████▍| 1312/1387 [07:59<00:24,  3.03it/s]

 95%|█████████▍| 1313/1387 [07:59<00:21,  3.51it/s]

 95%|█████████▍| 1314/1387 [07:59<00:21,  3.40it/s]

 95%|█████████▍| 1315/1387 [08:00<00:35,  2.03it/s]

 95%|█████████▍| 1316/1387 [08:00<00:27,  2.63it/s]

 95%|█████████▍| 1317/1387 [08:01<00:27,  2.57it/s]

 95%|█████████▌| 1318/1387 [08:01<00:27,  2.54it/s]

 95%|█████████▌| 1319/1387 [08:01<00:21,  3.18it/s]

 95%|█████████▌| 1320/1387 [08:02<00:23,  2.90it/s]

 95%|█████████▌| 1322/1387 [08:02<00:18,  3.61it/s]

 95%|█████████▌| 1323/1387 [08:03<00:31,  2.04it/s]

 96%|█████████▌| 1325/1387 [08:04<00:24,  2.58it/s]

 96%|█████████▌| 1326/1387 [08:04<00:23,  2.61it/s]

 96%|█████████▌| 1327/1387 [08:04<00:20,  3.00it/s]

 96%|█████████▌| 1328/1387 [08:05<00:20,  2.93it/s]

 96%|█████████▌| 1330/1387 [08:05<00:14,  3.88it/s]

 96%|█████████▌| 1331/1387 [08:06<00:26,  2.14it/s]

 96%|█████████▌| 1332/1387 [08:06<00:22,  2.45it/s]

 96%|█████████▌| 1333/1387 [08:07<00:19,  2.77it/s]

 96%|█████████▌| 1334/1387 [08:07<00:18,  2.84it/s]

 96%|█████████▋| 1335/1387 [08:07<00:20,  2.57it/s]

 96%|█████████▋| 1336/1387 [08:08<00:16,  3.08it/s]

 96%|█████████▋| 1337/1387 [08:08<00:13,  3.75it/s]

 96%|█████████▋| 1338/1387 [08:08<00:14,  3.39it/s]

 97%|█████████▋| 1339/1387 [08:09<00:22,  2.12it/s]

 97%|█████████▋| 1340/1387 [08:09<00:19,  2.43it/s]

 97%|█████████▋| 1341/1387 [08:10<00:20,  2.30it/s]

 97%|█████████▋| 1342/1387 [08:10<00:17,  2.53it/s]

 97%|█████████▋| 1343/1387 [08:11<00:19,  2.29it/s]

 97%|█████████▋| 1345/1387 [08:11<00:12,  3.43it/s]

 97%|█████████▋| 1347/1387 [08:12<00:17,  2.33it/s]

 97%|█████████▋| 1348/1387 [08:12<00:15,  2.55it/s]

 97%|█████████▋| 1349/1387 [08:13<00:16,  2.25it/s]

 97%|█████████▋| 1350/1387 [08:13<00:15,  2.37it/s]

 97%|█████████▋| 1352/1387 [08:14<00:09,  3.58it/s]

 98%|█████████▊| 1353/1387 [08:14<00:09,  3.63it/s]

 98%|█████████▊| 1354/1387 [08:14<00:08,  3.67it/s]

 98%|█████████▊| 1355/1387 [08:15<00:13,  2.35it/s]

 98%|█████████▊| 1356/1387 [08:15<00:13,  2.32it/s]

 98%|█████████▊| 1357/1387 [08:16<00:12,  2.32it/s]

 98%|█████████▊| 1358/1387 [08:16<00:12,  2.41it/s]

 98%|█████████▊| 1359/1387 [08:17<00:11,  2.49it/s]

 98%|█████████▊| 1361/1387 [08:17<00:06,  3.94it/s]

 98%|█████████▊| 1362/1387 [08:17<00:06,  3.59it/s]

 98%|█████████▊| 1363/1387 [08:18<00:10,  2.36it/s]

 98%|█████████▊| 1364/1387 [08:18<00:09,  2.49it/s]

 98%|█████████▊| 1365/1387 [08:19<00:09,  2.35it/s]

 98%|█████████▊| 1366/1387 [08:19<00:07,  2.64it/s]

 99%|█████████▊| 1367/1387 [08:19<00:07,  2.55it/s]

 99%|█████████▊| 1368/1387 [08:20<00:06,  3.15it/s]

 99%|█████████▉| 1370/1387 [08:20<00:04,  4.00it/s]

 99%|█████████▉| 1371/1387 [08:21<00:06,  2.58it/s]

 99%|█████████▉| 1372/1387 [08:21<00:05,  2.63it/s]

 99%|█████████▉| 1373/1387 [08:21<00:05,  2.46it/s]

 99%|█████████▉| 1374/1387 [08:22<00:04,  2.71it/s]

 99%|█████████▉| 1375/1387 [08:22<00:04,  2.43it/s]

 99%|█████████▉| 1378/1387 [08:23<00:02,  3.82it/s]

 99%|█████████▉| 1379/1387 [08:23<00:02,  2.74it/s]

 99%|█████████▉| 1380/1387 [08:24<00:02,  2.61it/s]

100%|█████████▉| 1381/1387 [08:24<00:02,  2.36it/s]

100%|█████████▉| 1382/1387 [08:25<00:02,  2.47it/s]

100%|█████████▉| 1383/1387 [08:25<00:01,  2.68it/s]

100%|█████████▉| 1384/1387 [08:25<00:00,  3.11it/s]

100%|█████████▉| 1385/1387 [08:25<00:00,  3.59it/s]

100%|██████████| 1387/1387 [08:26<00:00,  2.74it/s]
Multiplets | family 4:   0%|          | 0/1387 [08:26<?, ?it/s]

Multiplets | family 5:   0%|          | 0/1600 [00:00<?, ?it/s]

  0%|          | 0/1600 [00:00<?, ?it/s]

  0%|          | 1/1600 [00:03<1:38:35,  3.70s/it]

  0%|          | 7/1600 [00:03<10:42,  2.48it/s]

  1%|          | 11/1600 [00:07<16:41,  1.59it/s]

  1%|          | 15/1600 [00:07<10:21,  2.55it/s]

  1%|          | 18/1600 [00:11<16:27,  1.60it/s]

  1%|▏         | 22/1600 [00:11<10:46,  2.44it/s]

  2%|▏         | 25/1600 [00:14<16:24,  1.60it/s]

  2%|▏         | 28/1600 [00:14<12:04,  2.17it/s]

  2%|▏         | 31/1600 [00:15<09:33,  2.73it/s]

  2%|▏         | 33/1600 [00:18<16:40,  1.57it/s]

  2%|▏         | 37/1600 [00:18<11:00,  2.37it/s]

  2%|▏         | 39/1600 [00:19<10:14,  2.54it/s]

  3%|▎         | 41/1600 [00:22<16:12,  1.60it/s]

  3%|▎         | 43/1600 [00:22<12:29,  2.08it/s]

  3%|▎         | 44/1600 [00:22<11:33,  2.24it/s]

  3%|▎         | 46/1600 [00:22<09:58,  2.60it/s]

  3%|▎         | 47/1600 [00:23<10:04,  2.57it/s]

  3%|▎         | 49/1600 [00:25<17:39,  1.46it/s]

  3%|▎         | 50/1600 [00:26<14:56,  1.73it/s]

  3%|▎         | 51/1600 [00:26<12:22,  2.09it/s]

  3%|▎         | 52/1600 [00:26<10:05,  2.56it/s]

  3%|▎         | 53/1600 [00:26<08:44,  2.95it/s]

  3%|▎         | 54/1600 [00:26<08:00,  3.22it/s]

  3%|▎         | 55/1600 [00:27<08:47,  2.93it/s]

  4%|▎         | 56/1600 [00:27<08:07,  3.17it/s]

  4%|▎         | 57/1600 [00:29<22:28,  1.14it/s]

  4%|▎         | 58/1600 [00:29<16:46,  1.53it/s]

  4%|▎         | 59/1600 [00:29<13:08,  1.95it/s]

  4%|▍         | 60/1600 [00:30<10:28,  2.45it/s]

  4%|▍         | 61/1600 [00:30<08:16,  3.10it/s]

  4%|▍         | 62/1600 [00:30<09:07,  2.81it/s]

  4%|▍         | 63/1600 [00:31<10:57,  2.34it/s]

  4%|▍         | 64/1600 [00:31<12:09,  2.10it/s]

  4%|▍         | 65/1600 [00:33<20:15,  1.26it/s]

  4%|▍         | 67/1600 [00:33<14:16,  1.79it/s]

  4%|▍         | 68/1600 [00:34<11:30,  2.22it/s]

  4%|▍         | 69/1600 [00:34<10:49,  2.36it/s]

  4%|▍         | 71/1600 [00:35<10:12,  2.50it/s]

  4%|▍         | 72/1600 [00:35<11:12,  2.27it/s]

  5%|▍         | 73/1600 [00:37<18:27,  1.38it/s]

  5%|▍         | 74/1600 [00:37<16:33,  1.54it/s]

  5%|▍         | 75/1600 [00:37<13:58,  1.82it/s]

  5%|▍         | 77/1600 [00:38<09:18,  2.73it/s]

  5%|▍         | 78/1600 [00:38<08:04,  3.14it/s]

  5%|▍         | 79/1600 [00:39<10:56,  2.32it/s]

  5%|▌         | 80/1600 [00:39<12:08,  2.09it/s]

  5%|▌         | 81/1600 [00:41<17:23,  1.46it/s]

  5%|▌         | 82/1600 [00:41<14:26,  1.75it/s]

  5%|▌         | 83/1600 [00:41<12:46,  1.98it/s]

  5%|▌         | 85/1600 [00:41<08:03,  3.13it/s]

  5%|▌         | 86/1600 [00:42<07:46,  3.25it/s]

  5%|▌         | 87/1600 [00:42<11:22,  2.22it/s]

  6%|▌         | 88/1600 [00:43<11:22,  2.21it/s]

  6%|▌         | 89/1600 [00:44<16:36,  1.52it/s]

  6%|▌         | 90/1600 [00:44<14:25,  1.74it/s]

  6%|▌         | 91/1600 [00:45<12:40,  1.98it/s]

  6%|▌         | 93/1600 [00:45<08:01,  3.13it/s]

  6%|▌         | 94/1600 [00:45<08:24,  2.99it/s]

  6%|▌         | 95/1600 [00:46<12:52,  1.95it/s]

  6%|▌         | 96/1600 [00:47<10:42,  2.34it/s]

  6%|▌         | 97/1600 [00:48<15:48,  1.58it/s]

  6%|▌         | 98/1600 [00:48<13:35,  1.84it/s]

  6%|▌         | 99/1600 [00:49<13:03,  1.92it/s]

  6%|▋         | 101/1600 [00:49<07:56,  3.14it/s]

  6%|▋         | 102/1600 [00:49<09:05,  2.75it/s]

  6%|▋         | 103/1600 [00:50<14:24,  1.73it/s]

  6%|▋         | 104/1600 [00:51<11:42,  2.13it/s]

  7%|▋         | 105/1600 [00:52<16:50,  1.48it/s]

  7%|▋         | 106/1600 [00:52<14:00,  1.78it/s]

  7%|▋         | 107/1600 [00:52<13:04,  1.90it/s]

  7%|▋         | 108/1600 [00:53<10:35,  2.35it/s]

  7%|▋         | 110/1600 [00:53<09:36,  2.59it/s]

  7%|▋         | 111/1600 [00:54<13:01,  1.91it/s]

  7%|▋         | 112/1600 [00:55<11:52,  2.09it/s]

  7%|▋         | 113/1600 [00:56<14:58,  1.66it/s]

  7%|▋         | 114/1600 [00:56<13:48,  1.79it/s]

  7%|▋         | 115/1600 [00:56<12:18,  2.01it/s]

  7%|▋         | 116/1600 [00:56<09:36,  2.58it/s]

  7%|▋         | 117/1600 [00:57<07:53,  3.13it/s]

  7%|▋         | 118/1600 [00:57<10:27,  2.36it/s]

  7%|▋         | 119/1600 [00:58<14:10,  1.74it/s]

  8%|▊         | 120/1600 [00:59<13:29,  1.83it/s]

  8%|▊         | 121/1600 [01:00<16:56,  1.45it/s]

  8%|▊         | 122/1600 [01:00<12:38,  1.95it/s]

  8%|▊         | 123/1600 [01:00<11:27,  2.15it/s]

  8%|▊         | 125/1600 [01:00<07:23,  3.32it/s]

  8%|▊         | 126/1600 [01:01<09:21,  2.62it/s]

  8%|▊         | 127/1600 [01:02<14:32,  1.69it/s]

  8%|▊         | 128/1600 [01:03<12:38,  1.94it/s]

  8%|▊         | 129/1600 [01:04<17:15,  1.42it/s]

  8%|▊         | 131/1600 [01:04<12:50,  1.91it/s]

  8%|▊         | 132/1600 [01:05<10:58,  2.23it/s]

  8%|▊         | 133/1600 [01:05<08:56,  2.74it/s]

  8%|▊         | 134/1600 [01:05<07:44,  3.16it/s]

  8%|▊         | 135/1600 [01:06<15:26,  1.58it/s]

  8%|▊         | 136/1600 [01:07<13:10,  1.85it/s]

  9%|▊         | 137/1600 [01:07<14:36,  1.67it/s]

  9%|▊         | 138/1600 [01:08<12:36,  1.93it/s]

  9%|▊         | 139/1600 [01:08<12:02,  2.02it/s]

  9%|▉         | 140/1600 [01:08<10:14,  2.37it/s]

  9%|▉         | 141/1600 [01:09<08:33,  2.84it/s]

  9%|▉         | 142/1600 [01:09<07:45,  3.14it/s]

  9%|▉         | 143/1600 [01:10<16:18,  1.49it/s]

  9%|▉         | 145/1600 [01:11<14:13,  1.70it/s]

  9%|▉         | 146/1600 [01:11<11:25,  2.12it/s]

  9%|▉         | 147/1600 [01:12<12:43,  1.90it/s]

  9%|▉         | 148/1600 [01:12<10:31,  2.30it/s]

  9%|▉         | 150/1600 [01:13<08:08,  2.97it/s]

  9%|▉         | 151/1600 [01:14<13:28,  1.79it/s]

 10%|▉         | 153/1600 [01:15<12:39,  1.90it/s]

 10%|▉         | 154/1600 [01:15<10:32,  2.28it/s]

 10%|▉         | 155/1600 [01:16<11:33,  2.09it/s]

 10%|▉         | 156/1600 [01:16<10:05,  2.38it/s]

 10%|▉         | 158/1600 [01:16<07:34,  3.17it/s]

 10%|▉         | 159/1600 [01:18<13:46,  1.74it/s]

 10%|█         | 160/1600 [01:18<12:04,  1.99it/s]

 10%|█         | 161/1600 [01:19<13:37,  1.76it/s]

 10%|█         | 163/1600 [01:19<10:35,  2.26it/s]

 10%|█         | 164/1600 [01:20<09:51,  2.43it/s]

 10%|█         | 165/1600 [01:20<10:12,  2.34it/s]

 10%|█         | 167/1600 [01:21<13:07,  1.82it/s]

 10%|█         | 168/1600 [01:22<10:55,  2.19it/s]

 11%|█         | 169/1600 [01:22<12:48,  1.86it/s]

 11%|█         | 170/1600 [01:23<12:42,  1.87it/s]

 11%|█         | 171/1600 [01:23<11:23,  2.09it/s]

 11%|█         | 173/1600 [01:24<09:52,  2.41it/s]

 11%|█         | 175/1600 [01:25<12:17,  1.93it/s]

 11%|█         | 176/1600 [01:26<11:16,  2.10it/s]

 11%|█         | 177/1600 [01:26<11:31,  2.06it/s]

 11%|█         | 178/1600 [01:27<12:47,  1.85it/s]

 11%|█         | 179/1600 [01:27<10:38,  2.23it/s]

 11%|█▏        | 181/1600 [01:28<08:45,  2.70it/s]

 11%|█▏        | 182/1600 [01:28<07:27,  3.17it/s]

 11%|█▏        | 183/1600 [01:29<13:05,  1.80it/s]

 12%|█▏        | 184/1600 [01:29<11:48,  2.00it/s]

 12%|█▏        | 185/1600 [01:30<11:52,  1.98it/s]

 12%|█▏        | 186/1600 [01:30<12:21,  1.91it/s]

 12%|█▏        | 187/1600 [01:31<10:10,  2.32it/s]

 12%|█▏        | 189/1600 [01:31<08:49,  2.67it/s]

 12%|█▏        | 190/1600 [01:31<07:21,  3.19it/s]

 12%|█▏        | 191/1600 [01:33<13:21,  1.76it/s]

 12%|█▏        | 192/1600 [01:33<13:23,  1.75it/s]

 12%|█▏        | 193/1600 [01:33<10:56,  2.14it/s]

 12%|█▏        | 194/1600 [01:34<12:48,  1.83it/s]

 12%|█▏        | 195/1600 [01:34<09:50,  2.38it/s]

 12%|█▏        | 197/1600 [01:35<10:41,  2.19it/s]

 12%|█▏        | 199/1600 [01:37<13:46,  1.70it/s]

 12%|█▎        | 200/1600 [01:37<12:19,  1.89it/s]

 13%|█▎        | 201/1600 [01:37<10:05,  2.31it/s]

 13%|█▎        | 202/1600 [01:38<11:41,  1.99it/s]

 13%|█▎        | 203/1600 [01:38<09:21,  2.49it/s]

 13%|█▎        | 204/1600 [01:39<09:23,  2.48it/s]

 13%|█▎        | 205/1600 [01:39<11:36,  2.00it/s]

 13%|█▎        | 206/1600 [01:40<10:12,  2.28it/s]

 13%|█▎        | 207/1600 [01:40<13:12,  1.76it/s]

 13%|█▎        | 208/1600 [01:41<12:24,  1.87it/s]

 13%|█▎        | 209/1600 [01:41<11:17,  2.05it/s]

 13%|█▎        | 210/1600 [01:42<12:00,  1.93it/s]

 13%|█▎        | 212/1600 [01:42<09:34,  2.42it/s]

 13%|█▎        | 213/1600 [01:43<11:09,  2.07it/s]

 13%|█▎        | 214/1600 [01:43<09:04,  2.54it/s]

 13%|█▎        | 215/1600 [01:44<13:33,  1.70it/s]

 14%|█▎        | 216/1600 [01:45<11:07,  2.07it/s]

 14%|█▎        | 217/1600 [01:45<10:00,  2.30it/s]

 14%|█▎        | 218/1600 [01:46<11:16,  2.04it/s]

 14%|█▍        | 220/1600 [01:46<08:18,  2.77it/s]

 14%|█▍        | 221/1600 [01:47<10:42,  2.15it/s]

 14%|█▍        | 222/1600 [01:47<08:37,  2.66it/s]

 14%|█▍        | 223/1600 [01:48<14:12,  1.62it/s]

 14%|█▍        | 225/1600 [01:49<10:15,  2.23it/s]

 14%|█▍        | 226/1600 [01:49<11:04,  2.07it/s]

 14%|█▍        | 227/1600 [01:49<09:32,  2.40it/s]

 14%|█▍        | 228/1600 [01:50<08:24,  2.72it/s]

 14%|█▍        | 229/1600 [01:50<10:25,  2.19it/s]

 14%|█▍        | 230/1600 [01:51<09:35,  2.38it/s]

 14%|█▍        | 231/1600 [01:52<14:59,  1.52it/s]

 14%|█▍        | 232/1600 [01:52<11:19,  2.01it/s]

 15%|█▍        | 233/1600 [01:53<12:14,  1.86it/s]

 15%|█▍        | 234/1600 [01:53<09:59,  2.28it/s]

 15%|█▍        | 235/1600 [01:53<11:06,  2.05it/s]

 15%|█▍        | 237/1600 [01:54<08:34,  2.65it/s]

 15%|█▍        | 238/1600 [01:55<09:35,  2.37it/s]

 15%|█▍        | 239/1600 [01:56<13:45,  1.65it/s]

 15%|█▌        | 240/1600 [01:56<12:32,  1.81it/s]

 15%|█▌        | 241/1600 [01:57<12:35,  1.80it/s]

 15%|█▌        | 242/1600 [01:57<10:52,  2.08it/s]

 15%|█▌        | 243/1600 [01:57<09:42,  2.33it/s]

 15%|█▌        | 245/1600 [01:58<08:40,  2.60it/s]

 15%|█▌        | 246/1600 [01:58<09:13,  2.45it/s]

 15%|█▌        | 247/1600 [01:59<12:12,  1.85it/s]

 16%|█▌        | 248/1600 [02:00<13:03,  1.73it/s]

 16%|█▌        | 249/1600 [02:00<11:57,  1.88it/s]

 16%|█▌        | 250/1600 [02:01<10:29,  2.14it/s]

 16%|█▌        | 251/1600 [02:01<08:52,  2.53it/s]

 16%|█▌        | 253/1600 [02:02<08:22,  2.68it/s]

 16%|█▌        | 254/1600 [02:02<09:03,  2.48it/s]

 16%|█▌        | 255/1600 [02:03<11:43,  1.91it/s]

 16%|█▌        | 256/1600 [02:04<14:13,  1.57it/s]

 16%|█▌        | 257/1600 [02:04<11:56,  1.88it/s]

 16%|█▌        | 258/1600 [02:04<10:20,  2.16it/s]

 16%|█▌        | 259/1600 [02:05<08:22,  2.67it/s]

 16%|█▋        | 260/1600 [02:05<07:18,  3.06it/s]

 16%|█▋        | 261/1600 [02:05<08:46,  2.55it/s]

 16%|█▋        | 262/1600 [02:06<09:51,  2.26it/s]

 16%|█▋        | 263/1600 [02:07<14:07,  1.58it/s]

 16%|█▋        | 264/1600 [02:08<14:21,  1.55it/s]

 17%|█▋        | 265/1600 [02:08<11:14,  1.98it/s]

 17%|█▋        | 266/1600 [02:08<10:52,  2.04it/s]

 17%|█▋        | 268/1600 [02:08<06:26,  3.45it/s]

 17%|█▋        | 269/1600 [02:09<09:02,  2.45it/s]

 17%|█▋        | 270/1600 [02:10<09:59,  2.22it/s]

 17%|█▋        | 271/1600 [02:11<13:15,  1.67it/s]

 17%|█▋        | 272/1600 [02:11<13:26,  1.65it/s]

 17%|█▋        | 273/1600 [02:12<11:42,  1.89it/s]

 17%|█▋        | 274/1600 [02:12<11:11,  1.97it/s]

 17%|█▋        | 275/1600 [02:12<08:55,  2.47it/s]

 17%|█▋        | 277/1600 [02:13<08:49,  2.50it/s]

 17%|█▋        | 278/1600 [02:14<09:14,  2.38it/s]

 17%|█▋        | 279/1600 [02:14<11:44,  1.88it/s]

 18%|█▊        | 280/1600 [02:15<12:18,  1.79it/s]

 18%|█▊        | 281/1600 [02:16<11:23,  1.93it/s]

 18%|█▊        | 282/1600 [02:16<10:38,  2.06it/s]

 18%|█▊        | 283/1600 [02:16<08:29,  2.59it/s]

 18%|█▊        | 284/1600 [02:16<06:44,  3.26it/s]

 18%|█▊        | 285/1600 [02:17<10:13,  2.14it/s]

 18%|█▊        | 286/1600 [02:18<10:57,  2.00it/s]

 18%|█▊        | 287/1600 [02:18<12:11,  1.80it/s]

 18%|█▊        | 288/1600 [02:19<15:13,  1.44it/s]

 18%|█▊        | 289/1600 [02:20<13:01,  1.68it/s]

 18%|█▊        | 290/1600 [02:20<10:40,  2.05it/s]

 18%|█▊        | 292/1600 [02:20<07:19,  2.98it/s]

 18%|█▊        | 293/1600 [02:21<09:01,  2.41it/s]

 18%|█▊        | 294/1600 [02:22<11:17,  1.93it/s]

 18%|█▊        | 295/1600 [02:22<11:30,  1.89it/s]

 18%|█▊        | 296/1600 [02:24<16:21,  1.33it/s]

 19%|█▉        | 300/1600 [02:24<09:06,  2.38it/s]

 19%|█▉        | 301/1600 [02:25<08:07,  2.66it/s]

 19%|█▉        | 302/1600 [02:26<11:16,  1.92it/s]

 19%|█▉        | 303/1600 [02:26<11:19,  1.91it/s]

 19%|█▉        | 304/1600 [02:27<14:07,  1.53it/s]

 19%|█▉        | 305/1600 [02:27<11:24,  1.89it/s]

 19%|█▉        | 306/1600 [02:28<09:40,  2.23it/s]

 19%|█▉        | 308/1600 [02:28<07:52,  2.73it/s]

 19%|█▉        | 309/1600 [02:28<06:54,  3.11it/s]

 19%|█▉        | 310/1600 [02:30<11:51,  1.81it/s]

 19%|█▉        | 311/1600 [02:30<11:05,  1.94it/s]

 20%|█▉        | 312/1600 [02:31<14:00,  1.53it/s]

 20%|█▉        | 313/1600 [02:31<11:05,  1.93it/s]

 20%|█▉        | 314/1600 [02:32<10:11,  2.10it/s]

 20%|█▉        | 315/1600 [02:32<08:11,  2.61it/s]

 20%|█▉        | 316/1600 [02:32<08:19,  2.57it/s]

 20%|█▉        | 318/1600 [02:33<11:06,  1.92it/s]

 20%|█▉        | 319/1600 [02:34<10:02,  2.13it/s]

 20%|██        | 320/1600 [02:35<12:17,  1.74it/s]

 20%|██        | 321/1600 [02:35<10:56,  1.95it/s]

 20%|██        | 322/1600 [02:35<10:42,  1.99it/s]

 20%|██        | 324/1600 [02:36<08:07,  2.62it/s]

 20%|██        | 326/1600 [02:37<10:35,  2.00it/s]

 20%|██        | 327/1600 [02:38<10:35,  2.00it/s]

 20%|██        | 328/1600 [02:38<11:01,  1.92it/s]

 21%|██        | 329/1600 [02:39<12:23,  1.71it/s]

 21%|██        | 330/1600 [02:40<11:23,  1.86it/s]

 21%|██        | 332/1600 [02:40<07:37,  2.77it/s]

 21%|██        | 334/1600 [02:41<10:29,  2.01it/s]

 21%|██        | 335/1600 [02:42<11:36,  1.82it/s]

 21%|██        | 336/1600 [02:42<09:51,  2.14it/s]

 21%|██        | 337/1600 [02:43<11:11,  1.88it/s]

 21%|██        | 338/1600 [02:43<10:25,  2.02it/s]

 21%|██        | 339/1600 [02:44<10:31,  2.00it/s]

 21%|██▏       | 340/1600 [02:44<08:11,  2.56it/s]

 21%|██▏       | 341/1600 [02:44<06:58,  3.01it/s]

 21%|██▏       | 342/1600 [02:46<13:12,  1.59it/s]

 21%|██▏       | 343/1600 [02:46<11:52,  1.76it/s]

 22%|██▏       | 344/1600 [02:46<10:07,  2.07it/s]

 22%|██▏       | 345/1600 [02:47<10:25,  2.01it/s]

 22%|██▏       | 346/1600 [02:47<10:16,  2.03it/s]

 22%|██▏       | 347/1600 [02:48<09:34,  2.18it/s]

 22%|██▏       | 348/1600 [02:48<09:08,  2.28it/s]

 22%|██▏       | 350/1600 [02:49<11:01,  1.89it/s]

 22%|██▏       | 351/1600 [02:50<09:52,  2.11it/s]

 22%|██▏       | 352/1600 [02:50<09:13,  2.26it/s]

 22%|██▏       | 353/1600 [02:51<11:06,  1.87it/s]

 22%|██▏       | 354/1600 [02:51<11:29,  1.81it/s]

 22%|██▏       | 355/1600 [02:51<08:54,  2.33it/s]

 22%|██▏       | 356/1600 [02:52<08:11,  2.53it/s]

 22%|██▏       | 358/1600 [02:53<10:52,  1.90it/s]

 22%|██▏       | 359/1600 [02:54<10:42,  1.93it/s]

 22%|██▎       | 360/1600 [02:54<08:28,  2.44it/s]

 23%|██▎       | 361/1600 [02:55<12:02,  1.71it/s]

 23%|██▎       | 362/1600 [02:55<10:34,  1.95it/s]

 23%|██▎       | 363/1600 [02:55<09:40,  2.13it/s]

 23%|██▎       | 364/1600 [02:56<08:24,  2.45it/s]

 23%|██▎       | 366/1600 [02:57<11:19,  1.82it/s]

 23%|██▎       | 367/1600 [02:58<10:53,  1.89it/s]

 23%|██▎       | 368/1600 [02:58<09:05,  2.26it/s]

 23%|██▎       | 369/1600 [02:59<13:16,  1.55it/s]

 23%|██▎       | 371/1600 [02:59<08:59,  2.28it/s]

 23%|██▎       | 372/1600 [03:00<09:23,  2.18it/s]

 23%|██▎       | 374/1600 [03:01<10:30,  1.95it/s]

 23%|██▎       | 375/1600 [03:02<10:14,  1.99it/s]

 24%|██▎       | 376/1600 [03:02<08:33,  2.38it/s]

 24%|██▎       | 377/1600 [03:03<12:19,  1.65it/s]

 24%|██▎       | 378/1600 [03:03<09:41,  2.10it/s]

 24%|██▎       | 379/1600 [03:03<08:19,  2.44it/s]

 24%|██▍       | 380/1600 [03:04<08:21,  2.43it/s]

 24%|██▍       | 381/1600 [03:04<06:39,  3.05it/s]

 24%|██▍       | 382/1600 [03:05<10:22,  1.96it/s]

 24%|██▍       | 383/1600 [03:05<10:41,  1.90it/s]

 24%|██▍       | 385/1600 [03:07<11:42,  1.73it/s]

 24%|██▍       | 386/1600 [03:07<09:50,  2.06it/s]

 24%|██▍       | 388/1600 [03:07<08:23,  2.41it/s]

 24%|██▍       | 390/1600 [03:08<08:51,  2.28it/s]

 24%|██▍       | 391/1600 [03:09<09:32,  2.11it/s]

 24%|██▍       | 392/1600 [03:09<08:12,  2.45it/s]

 25%|██▍       | 393/1600 [03:10<11:48,  1.70it/s]

 25%|██▍       | 394/1600 [03:11<10:13,  1.96it/s]

 25%|██▍       | 395/1600 [03:11<09:12,  2.18it/s]

 25%|██▍       | 396/1600 [03:11<08:28,  2.37it/s]

 25%|██▍       | 398/1600 [03:12<08:43,  2.29it/s]

 25%|██▍       | 399/1600 [03:13<09:30,  2.11it/s]

 25%|██▌       | 400/1600 [03:13<10:00,  2.00it/s]

 25%|██▌       | 401/1600 [03:14<12:03,  1.66it/s]

 25%|██▌       | 402/1600 [03:14<10:14,  1.95it/s]

 25%|██▌       | 403/1600 [03:15<10:03,  1.98it/s]

 25%|██▌       | 404/1600 [03:15<07:55,  2.51it/s]

 25%|██▌       | 406/1600 [03:16<09:14,  2.15it/s]

 25%|██▌       | 407/1600 [03:17<08:58,  2.21it/s]

 26%|██▌       | 408/1600 [03:17<09:12,  2.16it/s]

 26%|██▌       | 409/1600 [03:18<13:15,  1.50it/s]

 26%|██▌       | 411/1600 [03:19<08:33,  2.32it/s]

 26%|██▌       | 412/1600 [03:19<09:02,  2.19it/s]

 26%|██▌       | 414/1600 [03:20<08:41,  2.27it/s]

 26%|██▌       | 415/1600 [03:20<08:06,  2.44it/s]

 26%|██▌       | 416/1600 [03:21<09:13,  2.14it/s]

 26%|██▌       | 417/1600 [03:22<12:51,  1.53it/s]

 26%|██▌       | 419/1600 [03:22<08:46,  2.24it/s]

 26%|██▋       | 420/1600 [03:23<08:47,  2.24it/s]

 26%|██▋       | 421/1600 [03:23<07:26,  2.64it/s]

 26%|██▋       | 422/1600 [03:24<08:33,  2.29it/s]

 26%|██▋       | 423/1600 [03:24<07:57,  2.46it/s]

 26%|██▋       | 424/1600 [03:24<08:47,  2.23it/s]

 27%|██▋       | 425/1600 [03:26<13:16,  1.48it/s]

 27%|██▋       | 426/1600 [03:26<12:00,  1.63it/s]

 27%|██▋       | 427/1600 [03:26<10:03,  1.94it/s]

 27%|██▋       | 429/1600 [03:27<08:13,  2.38it/s]

 27%|██▋       | 430/1600 [03:27<06:49,  2.86it/s]

 27%|██▋       | 431/1600 [03:28<09:06,  2.14it/s]

 27%|██▋       | 433/1600 [03:29<11:24,  1.71it/s]

 27%|██▋       | 434/1600 [03:30<12:09,  1.60it/s]

 27%|██▋       | 435/1600 [03:30<09:50,  1.97it/s]

 27%|██▋       | 436/1600 [03:31<08:18,  2.34it/s]

 27%|██▋       | 437/1600 [03:31<07:14,  2.68it/s]

 27%|██▋       | 438/1600 [03:31<08:08,  2.38it/s]

 27%|██▋       | 439/1600 [03:32<08:12,  2.36it/s]

 28%|██▊       | 440/1600 [03:32<06:35,  2.93it/s]

 28%|██▊       | 441/1600 [03:33<12:40,  1.52it/s]

 28%|██▊       | 442/1600 [03:34<12:47,  1.51it/s]

 28%|██▊       | 444/1600 [03:34<08:04,  2.39it/s]

 28%|██▊       | 445/1600 [03:35<08:01,  2.40it/s]

 28%|██▊       | 446/1600 [03:35<08:10,  2.35it/s]

 28%|██▊       | 447/1600 [03:36<08:07,  2.37it/s]

 28%|██▊       | 449/1600 [03:37<12:16,  1.56it/s]

 28%|██▊       | 450/1600 [03:38<10:55,  1.75it/s]

 28%|██▊       | 452/1600 [03:38<08:34,  2.23it/s]

 28%|██▊       | 453/1600 [03:39<08:11,  2.33it/s]

 28%|██▊       | 454/1600 [03:39<08:26,  2.26it/s]

 28%|██▊       | 456/1600 [03:39<06:20,  3.00it/s]

 29%|██▊       | 457/1600 [03:41<12:27,  1.53it/s]

 29%|██▊       | 458/1600 [03:41<10:15,  1.86it/s]

 29%|██▊       | 459/1600 [03:42<08:06,  2.34it/s]

 29%|██▉       | 460/1600 [03:42<07:56,  2.39it/s]

 29%|██▉       | 461/1600 [03:43<09:30,  2.00it/s]

 29%|██▉       | 462/1600 [03:43<07:21,  2.58it/s]

 29%|██▉       | 463/1600 [03:43<06:53,  2.75it/s]

 29%|██▉       | 464/1600 [03:43<06:04,  3.11it/s]

 29%|██▉       | 465/1600 [03:45<14:07,  1.34it/s]

 29%|██▉       | 467/1600 [03:45<09:09,  2.06it/s]

 29%|██▉       | 468/1600 [03:46<09:38,  1.96it/s]

 29%|██▉       | 469/1600 [03:46<08:51,  2.13it/s]

 29%|██▉       | 470/1600 [03:47<08:00,  2.35it/s]

 29%|██▉       | 471/1600 [03:47<08:30,  2.21it/s]

 30%|██▉       | 473/1600 [03:49<11:56,  1.57it/s]

 30%|██▉       | 474/1600 [03:49<09:52,  1.90it/s]

 30%|██▉       | 475/1600 [03:49<08:17,  2.26it/s]

 30%|██▉       | 476/1600 [03:50<09:14,  2.03it/s]

 30%|██▉       | 477/1600 [03:50<08:48,  2.13it/s]

 30%|██▉       | 479/1600 [03:51<07:50,  2.38it/s]

 30%|███       | 481/1600 [03:53<11:13,  1.66it/s]

 30%|███       | 483/1600 [03:53<08:58,  2.08it/s]

 30%|███       | 484/1600 [03:54<07:58,  2.33it/s]

 30%|███       | 485/1600 [03:54<08:39,  2.15it/s]

 30%|███       | 487/1600 [03:55<07:29,  2.47it/s]

 31%|███       | 489/1600 [03:56<10:25,  1.78it/s]

 31%|███       | 490/1600 [03:57<09:41,  1.91it/s]

 31%|███       | 491/1600 [03:57<08:40,  2.13it/s]

 31%|███       | 493/1600 [03:58<07:37,  2.42it/s]

 31%|███       | 494/1600 [03:58<08:01,  2.30it/s]

 31%|███       | 495/1600 [03:59<07:49,  2.35it/s]

 31%|███       | 496/1600 [03:59<07:38,  2.41it/s]

 31%|███       | 497/1600 [04:00<10:42,  1.72it/s]

 31%|███       | 498/1600 [04:01<09:57,  1.85it/s]

 31%|███       | 499/1600 [04:01<10:17,  1.78it/s]

 31%|███▏      | 500/1600 [04:01<08:04,  2.27it/s]

 31%|███▏      | 502/1600 [04:03<10:10,  1.80it/s]

 32%|███▏      | 504/1600 [04:03<07:32,  2.42it/s]

 32%|███▏      | 505/1600 [04:04<08:45,  2.08it/s]

 32%|███▏      | 506/1600 [04:05<09:58,  1.83it/s]

 32%|███▏      | 507/1600 [04:05<09:07,  2.00it/s]

 32%|███▏      | 508/1600 [04:05<08:21,  2.18it/s]

 32%|███▏      | 510/1600 [04:06<09:25,  1.93it/s]

 32%|███▏      | 511/1600 [04:07<08:06,  2.24it/s]

 32%|███▏      | 512/1600 [04:07<07:23,  2.45it/s]

 32%|███▏      | 513/1600 [04:07<07:54,  2.29it/s]

 32%|███▏      | 514/1600 [04:08<09:24,  1.92it/s]

 32%|███▏      | 515/1600 [04:09<09:21,  1.93it/s]

 32%|███▏      | 516/1600 [04:09<07:52,  2.29it/s]

 32%|███▏      | 518/1600 [04:10<08:58,  2.01it/s]

 32%|███▏      | 519/1600 [04:10<08:05,  2.23it/s]

 32%|███▎      | 520/1600 [04:11<07:23,  2.43it/s]

 33%|███▎      | 521/1600 [04:11<07:06,  2.53it/s]

 33%|███▎      | 522/1600 [04:12<09:01,  1.99it/s]

 33%|███▎      | 523/1600 [04:12<09:26,  1.90it/s]

 33%|███▎      | 524/1600 [04:13<07:41,  2.33it/s]

 33%|███▎      | 526/1600 [04:14<09:54,  1.81it/s]

 33%|███▎      | 527/1600 [04:14<09:10,  1.95it/s]

 33%|███▎      | 528/1600 [04:15<08:07,  2.20it/s]

 33%|███▎      | 529/1600 [04:15<07:12,  2.47it/s]

 33%|███▎      | 530/1600 [04:16<11:27,  1.56it/s]

 33%|███▎      | 532/1600 [04:16<07:28,  2.38it/s]

 33%|███▎      | 534/1600 [04:18<10:09,  1.75it/s]

 33%|███▎      | 535/1600 [04:18<08:29,  2.09it/s]

 34%|███▎      | 536/1600 [04:19<09:01,  1.96it/s]

 34%|███▎      | 537/1600 [04:19<07:38,  2.32it/s]

 34%|███▎      | 538/1600 [04:20<10:14,  1.73it/s]

 34%|███▎      | 539/1600 [04:20<08:17,  2.13it/s]

 34%|███▍      | 540/1600 [04:20<06:47,  2.60it/s]

 34%|███▍      | 541/1600 [04:21<06:02,  2.92it/s]

 34%|███▍      | 542/1600 [04:22<10:42,  1.65it/s]

 34%|███▍      | 543/1600 [04:22<08:49,  2.00it/s]

 34%|███▍      | 544/1600 [04:23<09:00,  1.96it/s]

 34%|███▍      | 545/1600 [04:23<07:34,  2.32it/s]

 34%|███▍      | 546/1600 [04:24<10:33,  1.66it/s]

 34%|███▍      | 549/1600 [04:24<05:46,  3.04it/s]

 34%|███▍      | 550/1600 [04:25<09:07,  1.92it/s]

 34%|███▍      | 551/1600 [04:26<07:56,  2.20it/s]

 34%|███▍      | 552/1600 [04:26<08:41,  2.01it/s]

 35%|███▍      | 553/1600 [04:27<07:34,  2.30it/s]

 35%|███▍      | 554/1600 [04:28<10:10,  1.71it/s]

 35%|███▍      | 556/1600 [04:28<06:12,  2.80it/s]

 35%|███▍      | 557/1600 [04:28<06:01,  2.88it/s]

 35%|███▍      | 558/1600 [04:29<10:06,  1.72it/s]

 35%|███▍      | 559/1600 [04:29<07:53,  2.20it/s]

 35%|███▌      | 560/1600 [04:30<10:26,  1.66it/s]

 35%|███▌      | 562/1600 [04:31<08:58,  1.93it/s]

 35%|███▌      | 563/1600 [04:32<08:27,  2.04it/s]

 35%|███▌      | 565/1600 [04:32<05:53,  2.92it/s]

 35%|███▌      | 566/1600 [04:33<08:46,  1.96it/s]

 35%|███▌      | 567/1600 [04:33<08:41,  1.98it/s]

 36%|███▌      | 568/1600 [04:34<09:26,  1.82it/s]

 36%|███▌      | 570/1600 [04:35<08:09,  2.10it/s]

 36%|███▌      | 571/1600 [04:36<09:07,  1.88it/s]

 36%|███▌      | 572/1600 [04:36<07:22,  2.33it/s]

 36%|███▌      | 573/1600 [04:36<06:33,  2.61it/s]

 36%|███▌      | 574/1600 [04:37<10:06,  1.69it/s]

 36%|███▌      | 576/1600 [04:38<08:40,  1.97it/s]

 36%|███▌      | 577/1600 [04:38<07:22,  2.31it/s]

 36%|███▌      | 578/1600 [04:39<07:40,  2.22it/s]

 36%|███▌      | 579/1600 [04:40<09:51,  1.73it/s]

 36%|███▋      | 580/1600 [04:40<08:07,  2.09it/s]

 36%|███▋      | 582/1600 [04:41<08:49,  1.92it/s]

 36%|███▋      | 584/1600 [04:42<07:45,  2.18it/s]

 37%|███▋      | 585/1600 [04:42<06:58,  2.42it/s]

 37%|███▋      | 586/1600 [04:42<06:42,  2.52it/s]

 37%|███▋      | 587/1600 [04:43<09:16,  1.82it/s]

 37%|███▋      | 588/1600 [04:44<08:09,  2.07it/s]

 37%|███▋      | 590/1600 [04:45<08:43,  1.93it/s]

 37%|███▋      | 592/1600 [04:46<08:06,  2.07it/s]

 37%|███▋      | 593/1600 [04:46<07:11,  2.34it/s]

 37%|███▋      | 594/1600 [04:46<06:17,  2.67it/s]

 37%|███▋      | 595/1600 [04:47<09:05,  1.84it/s]

 37%|███▋      | 596/1600 [04:47<08:09,  2.05it/s]

 37%|███▋      | 597/1600 [04:47<06:29,  2.58it/s]

 37%|███▋      | 598/1600 [04:49<09:46,  1.71it/s]

 38%|███▊      | 600/1600 [04:49<08:02,  2.07it/s]

 38%|███▊      | 601/1600 [04:50<07:24,  2.25it/s]

 38%|███▊      | 602/1600 [04:50<06:11,  2.69it/s]

 38%|███▊      | 603/1600 [04:51<10:37,  1.56it/s]

 38%|███▊      | 605/1600 [04:51<06:25,  2.58it/s]

 38%|███▊      | 606/1600 [04:52<09:08,  1.81it/s]

 38%|███▊      | 607/1600 [04:53<08:28,  1.95it/s]

 38%|███▊      | 608/1600 [04:53<08:30,  1.94it/s]

 38%|███▊      | 610/1600 [04:54<07:11,  2.29it/s]

 38%|███▊      | 611/1600 [04:55<09:17,  1.77it/s]

 38%|███▊      | 612/1600 [04:55<07:29,  2.20it/s]

 38%|███▊      | 613/1600 [04:55<06:39,  2.47it/s]

 38%|███▊      | 614/1600 [04:56<08:53,  1.85it/s]

 38%|███▊      | 615/1600 [04:57<08:43,  1.88it/s]

 38%|███▊      | 616/1600 [04:57<07:33,  2.17it/s]

 39%|███▊      | 617/1600 [04:57<06:15,  2.62it/s]

 39%|███▊      | 618/1600 [04:58<07:15,  2.25it/s]

 39%|███▊      | 619/1600 [04:59<09:49,  1.66it/s]

 39%|███▉      | 621/1600 [04:59<06:28,  2.52it/s]

 39%|███▉      | 622/1600 [05:00<08:15,  1.97it/s]

 39%|███▉      | 623/1600 [05:00<08:34,  1.90it/s]

 39%|███▉      | 624/1600 [05:01<07:22,  2.21it/s]

 39%|███▉      | 625/1600 [05:01<07:23,  2.20it/s]

 39%|███▉      | 626/1600 [05:01<06:23,  2.54it/s]

 39%|███▉      | 627/1600 [05:02<09:27,  1.71it/s]

 39%|███▉      | 628/1600 [05:03<09:39,  1.68it/s]

 39%|███▉      | 630/1600 [05:04<07:16,  2.22it/s]

 39%|███▉      | 631/1600 [05:04<08:31,  1.90it/s]

 40%|███▉      | 632/1600 [05:05<08:29,  1.90it/s]

 40%|███▉      | 634/1600 [05:06<07:00,  2.30it/s]

 40%|███▉      | 635/1600 [05:07<10:00,  1.61it/s]

 40%|███▉      | 638/1600 [05:08<07:43,  2.07it/s]

 40%|███▉      | 639/1600 [05:08<07:31,  2.13it/s]

 40%|████      | 640/1600 [05:09<07:22,  2.17it/s]

 40%|████      | 641/1600 [05:09<06:46,  2.36it/s]

 40%|████      | 642/1600 [05:09<07:03,  2.26it/s]

 40%|████      | 643/1600 [05:11<09:50,  1.62it/s]

 40%|████      | 644/1600 [05:11<08:06,  1.97it/s]

 40%|████      | 646/1600 [05:12<07:22,  2.16it/s]

 40%|████      | 647/1600 [05:12<06:56,  2.29it/s]

 40%|████      | 648/1600 [05:13<07:51,  2.02it/s]

 41%|████      | 649/1600 [05:13<06:11,  2.56it/s]

 41%|████      | 650/1600 [05:13<06:10,  2.57it/s]

 41%|████      | 651/1600 [05:14<09:59,  1.58it/s]

 41%|████      | 652/1600 [05:15<07:58,  1.98it/s]

 41%|████      | 653/1600 [05:15<06:11,  2.55it/s]

 41%|████      | 654/1600 [05:15<07:07,  2.21it/s]

 41%|████      | 655/1600 [05:16<06:50,  2.30it/s]

 41%|████      | 656/1600 [05:16<08:32,  1.84it/s]

 41%|████      | 657/1600 [05:17<07:02,  2.23it/s]

 41%|████      | 658/1600 [05:17<05:37,  2.79it/s]

 41%|████      | 659/1600 [05:18<11:23,  1.38it/s]

 41%|████▏     | 661/1600 [05:19<06:40,  2.35it/s]

 41%|████▏     | 662/1600 [05:19<06:40,  2.34it/s]

 41%|████▏     | 663/1600 [05:19<06:41,  2.33it/s]

 42%|████▏     | 664/1600 [05:20<09:04,  1.72it/s]

 42%|████▏     | 665/1600 [05:21<09:12,  1.69it/s]

 42%|████▏     | 666/1600 [05:21<07:03,  2.21it/s]

 42%|████▏     | 667/1600 [05:22<09:41,  1.60it/s]

 42%|████▏     | 669/1600 [05:22<05:46,  2.68it/s]

 42%|████▏     | 670/1600 [05:23<07:48,  1.98it/s]

 42%|████▏     | 672/1600 [05:24<08:18,  1.86it/s]

 42%|████▏     | 673/1600 [05:25<08:27,  1.83it/s]

 42%|████▏     | 675/1600 [05:26<08:09,  1.89it/s]

 42%|████▏     | 676/1600 [05:26<06:50,  2.25it/s]

 42%|████▏     | 678/1600 [05:27<07:05,  2.17it/s]

 42%|████▎     | 680/1600 [05:28<07:25,  2.07it/s]

 43%|████▎     | 681/1600 [05:29<07:26,  2.06it/s]

 43%|████▎     | 682/1600 [05:29<06:20,  2.41it/s]

 43%|████▎     | 683/1600 [05:30<08:32,  1.79it/s]

 43%|████▎     | 685/1600 [05:30<05:31,  2.76it/s]

 43%|████▎     | 686/1600 [05:31<06:58,  2.18it/s]

 43%|████▎     | 688/1600 [05:32<07:48,  1.95it/s]

 43%|████▎     | 689/1600 [05:32<07:05,  2.14it/s]

 43%|████▎     | 690/1600 [05:33<06:29,  2.33it/s]

 43%|████▎     | 691/1600 [05:34<08:39,  1.75it/s]

 43%|████▎     | 692/1600 [05:34<07:22,  2.05it/s]

 43%|████▎     | 693/1600 [05:34<06:04,  2.49it/s]

 43%|████▎     | 694/1600 [05:34<06:25,  2.35it/s]

 43%|████▎     | 695/1600 [05:35<06:13,  2.42it/s]

 44%|████▎     | 696/1600 [05:36<08:15,  1.82it/s]

 44%|████▎     | 697/1600 [05:36<07:31,  2.00it/s]

 44%|████▎     | 698/1600 [05:36<06:43,  2.23it/s]

 44%|████▎     | 699/1600 [05:37<09:27,  1.59it/s]

 44%|████▍     | 700/1600 [05:38<07:07,  2.11it/s]

 44%|████▍     | 701/1600 [05:38<08:06,  1.85it/s]

 44%|████▍     | 703/1600 [05:39<06:28,  2.31it/s]

 44%|████▍     | 704/1600 [05:40<08:26,  1.77it/s]

 44%|████▍     | 705/1600 [05:40<07:24,  2.01it/s]

 44%|████▍     | 706/1600 [05:41<07:02,  2.11it/s]

 44%|████▍     | 707/1600 [05:41<07:52,  1.89it/s]

 44%|████▍     | 708/1600 [05:41<06:20,  2.35it/s]

 44%|████▍     | 709/1600 [05:42<07:13,  2.06it/s]

 44%|████▍     | 710/1600 [05:42<05:45,  2.58it/s]

 44%|████▍     | 711/1600 [05:43<06:35,  2.25it/s]

 44%|████▍     | 712/1600 [05:44<08:49,  1.68it/s]

 45%|████▍     | 713/1600 [05:44<06:51,  2.15it/s]

 45%|████▍     | 714/1600 [05:44<07:14,  2.04it/s]

 45%|████▍     | 715/1600 [05:45<07:20,  2.01it/s]

 45%|████▍     | 716/1600 [05:45<07:01,  2.09it/s]

 45%|████▍     | 717/1600 [05:46<07:05,  2.07it/s]

 45%|████▍     | 718/1600 [05:46<05:33,  2.64it/s]

 45%|████▍     | 719/1600 [05:47<06:13,  2.36it/s]

 45%|████▌     | 720/1600 [05:48<09:19,  1.57it/s]

 45%|████▌     | 722/1600 [05:48<07:35,  1.93it/s]

 45%|████▌     | 723/1600 [05:49<06:34,  2.22it/s]

 45%|████▌     | 724/1600 [05:49<07:21,  1.98it/s]

 45%|████▌     | 725/1600 [05:50<06:42,  2.17it/s]

 45%|████▌     | 727/1600 [05:51<06:19,  2.30it/s]

 46%|████▌     | 728/1600 [05:51<07:53,  1.84it/s]

 46%|████▌     | 729/1600 [05:52<06:45,  2.15it/s]

 46%|████▌     | 730/1600 [05:52<07:22,  1.97it/s]

 46%|████▌     | 731/1600 [05:53<07:15,  2.00it/s]

 46%|████▌     | 732/1600 [05:53<07:51,  1.84it/s]

 46%|████▌     | 733/1600 [05:54<06:04,  2.38it/s]

 46%|████▌     | 734/1600 [05:54<06:39,  2.17it/s]

 46%|████▌     | 735/1600 [05:54<05:42,  2.52it/s]

 46%|████▌     | 736/1600 [05:55<07:03,  2.04it/s]

 46%|████▌     | 737/1600 [05:56<07:22,  1.95it/s]

 46%|████▌     | 738/1600 [05:56<08:33,  1.68it/s]

 46%|████▋     | 740/1600 [05:57<07:50,  1.83it/s]

 46%|████▋     | 742/1600 [05:58<06:31,  2.19it/s]

 46%|████▋     | 744/1600 [05:59<06:03,  2.36it/s]

 47%|████▋     | 745/1600 [05:59<06:34,  2.17it/s]

 47%|████▋     | 746/1600 [06:00<07:50,  1.81it/s]

 47%|████▋     | 747/1600 [06:00<06:17,  2.26it/s]

 47%|████▋     | 748/1600 [06:01<07:57,  1.79it/s]

 47%|████▋     | 750/1600 [06:02<06:01,  2.35it/s]

 47%|████▋     | 752/1600 [06:02<05:49,  2.42it/s]

 47%|████▋     | 753/1600 [06:03<06:53,  2.05it/s]

 47%|████▋     | 754/1600 [06:04<08:14,  1.71it/s]

 47%|████▋     | 755/1600 [06:04<06:57,  2.03it/s]

 47%|████▋     | 756/1600 [06:05<07:26,  1.89it/s]

 47%|████▋     | 758/1600 [06:05<05:39,  2.48it/s]

 47%|████▋     | 759/1600 [06:06<05:37,  2.49it/s]

 48%|████▊     | 760/1600 [06:06<05:31,  2.53it/s]

 48%|████▊     | 761/1600 [06:07<07:09,  1.95it/s]

 48%|████▊     | 762/1600 [06:08<08:22,  1.67it/s]

 48%|████▊     | 763/1600 [06:08<07:11,  1.94it/s]

 48%|████▊     | 764/1600 [06:09<06:47,  2.05it/s]

 48%|████▊     | 765/1600 [06:09<06:22,  2.18it/s]

 48%|████▊     | 766/1600 [06:10<07:01,  1.98it/s]

 48%|████▊     | 768/1600 [06:10<05:31,  2.51it/s]

 48%|████▊     | 769/1600 [06:11<07:22,  1.88it/s]

 48%|████▊     | 770/1600 [06:12<09:29,  1.46it/s]

 48%|████▊     | 772/1600 [06:12<05:45,  2.40it/s]

 48%|████▊     | 773/1600 [06:13<05:54,  2.33it/s]

 48%|████▊     | 774/1600 [06:14<07:14,  1.90it/s]

 48%|████▊     | 776/1600 [06:14<04:57,  2.77it/s]

 49%|████▊     | 777/1600 [06:15<07:28,  1.84it/s]

 49%|████▊     | 778/1600 [06:16<08:29,  1.61it/s]

 49%|████▊     | 779/1600 [06:16<07:07,  1.92it/s]

 49%|████▉     | 781/1600 [06:17<05:38,  2.42it/s]

 49%|████▉     | 782/1600 [06:17<06:23,  2.13it/s]

 49%|████▉     | 783/1600 [06:17<05:10,  2.63it/s]

 49%|████▉     | 784/1600 [06:18<04:11,  3.24it/s]

 49%|████▉     | 785/1600 [06:19<07:09,  1.90it/s]

 49%|████▉     | 786/1600 [06:20<08:32,  1.59it/s]

 49%|████▉     | 787/1600 [06:20<07:26,  1.82it/s]

 49%|████▉     | 789/1600 [06:20<05:29,  2.46it/s]

 49%|████▉     | 790/1600 [06:21<06:04,  2.22it/s]

 49%|████▉     | 791/1600 [06:21<05:17,  2.55it/s]

 50%|████▉     | 792/1600 [06:21<04:37,  2.91it/s]

 50%|████▉     | 793/1600 [06:22<07:14,  1.86it/s]

 50%|████▉     | 794/1600 [06:23<08:17,  1.62it/s]

 50%|████▉     | 795/1600 [06:24<08:00,  1.68it/s]

 50%|████▉     | 796/1600 [06:25<08:36,  1.56it/s]

 50%|████▉     | 797/1600 [06:25<06:42,  1.99it/s]

 50%|████▉     | 798/1600 [06:25<05:12,  2.56it/s]

 50%|████▉     | 799/1600 [06:25<04:10,  3.19it/s]

 50%|█████     | 800/1600 [06:25<04:38,  2.88it/s]

 50%|█████     | 801/1600 [06:26<06:46,  1.97it/s]

 50%|█████     | 802/1600 [06:27<08:16,  1.61it/s]

 50%|█████     | 803/1600 [06:28<07:43,  1.72it/s]

 50%|█████     | 804/1600 [06:29<09:15,  1.43it/s]

 50%|█████     | 806/1600 [06:29<05:38,  2.34it/s]

 50%|█████     | 808/1600 [06:29<04:13,  3.12it/s]

 51%|█████     | 809/1600 [06:30<06:27,  2.04it/s]

 51%|█████     | 810/1600 [06:31<07:30,  1.75it/s]

 51%|█████     | 811/1600 [06:31<06:23,  2.06it/s]

 51%|█████     | 812/1600 [06:32<08:18,  1.58it/s]

 51%|█████     | 815/1600 [06:33<04:32,  2.88it/s]

 51%|█████     | 816/1600 [06:33<04:15,  3.07it/s]

 51%|█████     | 817/1600 [06:34<06:30,  2.00it/s]

 51%|█████     | 818/1600 [06:35<07:18,  1.78it/s]

 51%|█████     | 819/1600 [06:35<06:07,  2.13it/s]

 51%|█████▏    | 820/1600 [06:36<08:36,  1.51it/s]

 51%|█████▏    | 822/1600 [06:36<05:29,  2.36it/s]

 52%|█████▏    | 824/1600 [06:37<05:09,  2.51it/s]

 52%|█████▏    | 825/1600 [06:38<05:48,  2.22it/s]

 52%|█████▏    | 826/1600 [06:39<07:43,  1.67it/s]

 52%|█████▏    | 828/1600 [06:40<07:38,  1.68it/s]

 52%|█████▏    | 829/1600 [06:40<06:47,  1.89it/s]

 52%|█████▏    | 830/1600 [06:41<06:34,  1.95it/s]

 52%|█████▏    | 833/1600 [06:42<06:00,  2.12it/s]

 52%|█████▏    | 834/1600 [06:42<05:52,  2.18it/s]

 52%|█████▏    | 835/1600 [06:43<05:23,  2.36it/s]

 52%|█████▏    | 836/1600 [06:44<07:18,  1.74it/s]

 52%|█████▏    | 837/1600 [06:44<06:33,  1.94it/s]

 52%|█████▏    | 838/1600 [06:45<06:41,  1.90it/s]

 52%|█████▏    | 839/1600 [06:45<05:24,  2.34it/s]

 53%|█████▎    | 841/1600 [06:46<06:24,  1.98it/s]

 53%|█████▎    | 843/1600 [06:47<05:04,  2.48it/s]

 53%|█████▎    | 844/1600 [06:48<07:19,  1.72it/s]

 53%|█████▎    | 845/1600 [06:48<05:57,  2.11it/s]

 53%|█████▎    | 846/1600 [06:49<06:37,  1.90it/s]

 53%|█████▎    | 848/1600 [06:49<04:30,  2.78it/s]

 53%|█████▎    | 849/1600 [06:50<06:12,  2.02it/s]

 53%|█████▎    | 851/1600 [06:50<04:43,  2.65it/s]

 53%|█████▎    | 852/1600 [06:52<07:17,  1.71it/s]

 53%|█████▎    | 853/1600 [06:52<05:57,  2.09it/s]

 53%|█████▎    | 854/1600 [06:52<06:44,  1.84it/s]

 53%|█████▎    | 855/1600 [06:53<05:25,  2.29it/s]

 54%|█████▎    | 856/1600 [06:53<04:17,  2.89it/s]

 54%|█████▎    | 857/1600 [06:53<05:50,  2.12it/s]

 54%|█████▎    | 859/1600 [06:54<05:53,  2.10it/s]

 54%|█████▍    | 860/1600 [06:55<07:16,  1.70it/s]

 54%|█████▍    | 861/1600 [06:56<06:10,  2.00it/s]

 54%|█████▍    | 862/1600 [06:56<06:06,  2.01it/s]

 54%|█████▍    | 863/1600 [06:56<05:27,  2.25it/s]

 54%|█████▍    | 864/1600 [06:57<05:47,  2.12it/s]

 54%|█████▍    | 865/1600 [06:57<05:53,  2.08it/s]

 54%|█████▍    | 867/1600 [06:58<05:43,  2.13it/s]

 54%|█████▍    | 868/1600 [06:59<06:42,  1.82it/s]

 54%|█████▍    | 869/1600 [07:00<06:19,  1.93it/s]

 54%|█████▍    | 870/1600 [07:00<06:46,  1.79it/s]

 54%|█████▍    | 871/1600 [07:00<05:31,  2.20it/s]

 55%|█████▍    | 872/1600 [07:01<05:35,  2.17it/s]

 55%|█████▍    | 873/1600 [07:01<05:07,  2.36it/s]

 55%|█████▍    | 874/1600 [07:01<04:20,  2.78it/s]

 55%|█████▍    | 875/1600 [07:02<06:15,  1.93it/s]

 55%|█████▍    | 876/1600 [07:03<06:21,  1.90it/s]

 55%|█████▍    | 877/1600 [07:03<06:27,  1.87it/s]

 55%|█████▍    | 878/1600 [07:04<06:47,  1.77it/s]

 55%|█████▌    | 880/1600 [07:05<04:55,  2.44it/s]

 55%|█████▌    | 881/1600 [07:05<04:57,  2.42it/s]

 55%|█████▌    | 882/1600 [07:05<04:29,  2.66it/s]

 55%|█████▌    | 883/1600 [07:06<05:55,  2.02it/s]

 55%|█████▌    | 884/1600 [07:06<05:42,  2.09it/s]

 55%|█████▌    | 885/1600 [07:07<06:31,  1.83it/s]

 55%|█████▌    | 886/1600 [07:08<06:43,  1.77it/s]

 55%|█████▌    | 887/1600 [07:08<05:24,  2.20it/s]

 56%|█████▌    | 888/1600 [07:08<04:27,  2.66it/s]

 56%|█████▌    | 889/1600 [07:09<05:30,  2.15it/s]

 56%|█████▌    | 890/1600 [07:09<04:38,  2.55it/s]

 56%|█████▌    | 891/1600 [07:10<05:40,  2.08it/s]

 56%|█████▌    | 892/1600 [07:10<05:20,  2.21it/s]

 56%|█████▌    | 893/1600 [07:11<06:34,  1.79it/s]

 56%|█████▌    | 894/1600 [07:12<07:39,  1.54it/s]

 56%|█████▌    | 895/1600 [07:12<06:09,  1.91it/s]

 56%|█████▌    | 897/1600 [07:13<05:35,  2.10it/s]

 56%|█████▌    | 898/1600 [07:13<04:41,  2.49it/s]

 56%|█████▌    | 899/1600 [07:14<06:17,  1.86it/s]

 56%|█████▋    | 901/1600 [07:15<06:02,  1.93it/s]

 56%|█████▋    | 902/1600 [07:16<06:33,  1.77it/s]

 56%|█████▋    | 903/1600 [07:16<05:31,  2.10it/s]

 56%|█████▋    | 904/1600 [07:16<04:31,  2.56it/s]

 57%|█████▋    | 905/1600 [07:17<05:39,  2.05it/s]

 57%|█████▋    | 907/1600 [07:18<05:27,  2.12it/s]

 57%|█████▋    | 908/1600 [07:18<04:52,  2.36it/s]

 57%|█████▋    | 909/1600 [07:19<06:26,  1.79it/s]

 57%|█████▋    | 910/1600 [07:19<06:10,  1.86it/s]

 57%|█████▋    | 911/1600 [07:20<05:27,  2.11it/s]

 57%|█████▋    | 912/1600 [07:20<04:21,  2.63it/s]

 57%|█████▋    | 913/1600 [07:20<05:10,  2.21it/s]

 57%|█████▋    | 914/1600 [07:21<04:29,  2.54it/s]

 57%|█████▋    | 915/1600 [07:21<05:27,  2.09it/s]

 57%|█████▋    | 916/1600 [07:22<05:21,  2.13it/s]

 57%|█████▋    | 917/1600 [07:23<06:32,  1.74it/s]

 57%|█████▋    | 918/1600 [07:23<05:59,  1.90it/s]

 57%|█████▋    | 919/1600 [07:24<06:04,  1.87it/s]

 58%|█████▊    | 921/1600 [07:24<04:36,  2.45it/s]

 58%|█████▊    | 922/1600 [07:24<04:17,  2.63it/s]

 58%|█████▊    | 923/1600 [07:25<05:29,  2.05it/s]

 58%|█████▊    | 924/1600 [07:26<05:28,  2.06it/s]

 58%|█████▊    | 925/1600 [07:26<06:09,  1.82it/s]

 58%|█████▊    | 926/1600 [07:27<06:32,  1.72it/s]

 58%|█████▊    | 927/1600 [07:27<05:28,  2.05it/s]

 58%|█████▊    | 928/1600 [07:28<04:45,  2.35it/s]

 58%|█████▊    | 929/1600 [07:28<04:01,  2.78it/s]

 58%|█████▊    | 930/1600 [07:28<04:11,  2.67it/s]

 58%|█████▊    | 931/1600 [07:29<06:31,  1.71it/s]

 58%|█████▊    | 932/1600 [07:30<05:28,  2.04it/s]

 58%|█████▊    | 933/1600 [07:30<05:44,  1.94it/s]

 58%|█████▊    | 934/1600 [07:31<07:03,  1.57it/s]

 58%|█████▊    | 935/1600 [07:31<05:23,  2.05it/s]

 58%|█████▊    | 936/1600 [07:32<04:53,  2.26it/s]

 59%|█████▊    | 937/1600 [07:32<03:50,  2.87it/s]

 59%|█████▊    | 938/1600 [07:32<04:23,  2.51it/s]

 59%|█████▊    | 939/1600 [07:33<06:42,  1.64it/s]

 59%|█████▉    | 941/1600 [07:34<05:17,  2.07it/s]

 59%|█████▉    | 942/1600 [07:35<06:12,  1.77it/s]

 59%|█████▉    | 943/1600 [07:35<05:54,  1.85it/s]

 59%|█████▉    | 944/1600 [07:35<04:43,  2.31it/s]

 59%|█████▉    | 946/1600 [07:36<04:35,  2.37it/s]

 59%|█████▉    | 947/1600 [07:37<05:43,  1.90it/s]

 59%|█████▉    | 948/1600 [07:37<04:37,  2.35it/s]

 59%|█████▉    | 949/1600 [07:38<06:06,  1.78it/s]

 59%|█████▉    | 950/1600 [07:39<05:34,  1.95it/s]

 59%|█████▉    | 951/1600 [07:39<06:04,  1.78it/s]

 60%|█████▉    | 952/1600 [07:39<04:46,  2.26it/s]

 60%|█████▉    | 954/1600 [07:40<03:55,  2.74it/s]

 60%|█████▉    | 955/1600 [07:41<05:11,  2.07it/s]

 60%|█████▉    | 957/1600 [07:42<05:25,  1.98it/s]

 60%|█████▉    | 958/1600 [07:42<05:39,  1.89it/s]

 60%|█████▉    | 959/1600 [07:43<06:28,  1.65it/s]

 60%|██████    | 960/1600 [07:43<05:08,  2.07it/s]

 60%|██████    | 961/1600 [07:44<04:06,  2.59it/s]

 60%|██████    | 962/1600 [07:44<03:49,  2.78it/s]

 60%|██████    | 963/1600 [07:45<05:02,  2.10it/s]

 60%|██████    | 964/1600 [07:45<04:25,  2.40it/s]

 60%|██████    | 965/1600 [07:46<06:07,  1.73it/s]

 60%|██████    | 966/1600 [07:46<06:18,  1.68it/s]

 60%|██████    | 967/1600 [07:47<06:47,  1.55it/s]

 60%|██████    | 968/1600 [07:47<05:22,  1.96it/s]

 61%|██████    | 970/1600 [07:48<03:17,  3.19it/s]

 61%|██████    | 971/1600 [07:48<04:16,  2.45it/s]

 61%|██████    | 972/1600 [07:49<04:17,  2.44it/s]

 61%|██████    | 973/1600 [07:50<06:33,  1.59it/s]

 61%|██████    | 974/1600 [07:50<05:58,  1.75it/s]

 61%|██████    | 975/1600 [07:51<06:20,  1.64it/s]

 61%|██████    | 977/1600 [07:51<04:17,  2.42it/s]

 61%|██████    | 979/1600 [07:52<03:43,  2.78it/s]

 61%|██████▏   | 980/1600 [07:52<03:42,  2.79it/s]

 61%|██████▏   | 981/1600 [07:54<06:14,  1.65it/s]

 61%|██████▏   | 982/1600 [07:54<05:30,  1.87it/s]

 61%|██████▏   | 983/1600 [07:55<05:51,  1.75it/s]

 62%|██████▏   | 985/1600 [07:55<04:16,  2.39it/s]

 62%|██████▏   | 987/1600 [07:56<03:52,  2.64it/s]

 62%|██████▏   | 988/1600 [07:56<03:28,  2.93it/s]

 62%|██████▏   | 989/1600 [07:58<06:26,  1.58it/s]

 62%|██████▏   | 990/1600 [07:58<05:25,  1.88it/s]

 62%|██████▏   | 991/1600 [07:58<05:32,  1.83it/s]

 62%|██████▏   | 992/1600 [07:59<04:25,  2.29it/s]

 62%|██████▏   | 993/1600 [07:59<04:53,  2.07it/s]

 62%|██████▏   | 994/1600 [07:59<04:28,  2.25it/s]

 62%|██████▏   | 995/1600 [08:00<04:13,  2.38it/s]

 62%|██████▏   | 997/1600 [08:01<05:57,  1.69it/s]

 62%|██████▏   | 998/1600 [08:02<06:09,  1.63it/s]

 62%|██████▏   | 999/1600 [08:02<05:04,  1.97it/s]

 62%|██████▎   | 1000/1600 [08:03<04:18,  2.32it/s]

 63%|██████▎   | 1001/1600 [08:03<04:50,  2.06it/s]

 63%|██████▎   | 1003/1600 [08:03<03:19,  2.99it/s]

 63%|██████▎   | 1004/1600 [08:04<03:02,  3.26it/s]

 63%|██████▎   | 1005/1600 [08:05<06:26,  1.54it/s]

 63%|██████▎   | 1006/1600 [08:06<06:43,  1.47it/s]

 63%|██████▎   | 1008/1600 [08:06<04:10,  2.36it/s]

 63%|██████▎   | 1009/1600 [08:07<04:29,  2.19it/s]

 63%|██████▎   | 1010/1600 [08:07<04:08,  2.37it/s]

 63%|██████▎   | 1011/1600 [08:07<03:37,  2.70it/s]

 63%|██████▎   | 1013/1600 [08:09<06:07,  1.60it/s]

 63%|██████▎   | 1014/1600 [08:10<05:52,  1.66it/s]

 64%|██████▎   | 1016/1600 [08:10<03:56,  2.47it/s]

 64%|██████▎   | 1017/1600 [08:10<03:52,  2.51it/s]

 64%|██████▎   | 1018/1600 [08:11<03:57,  2.45it/s]

 64%|██████▎   | 1019/1600 [08:11<03:21,  2.89it/s]

 64%|██████▍   | 1021/1600 [08:13<06:04,  1.59it/s]

 64%|██████▍   | 1022/1600 [08:13<05:38,  1.71it/s]

 64%|██████▍   | 1023/1600 [08:14<04:37,  2.08it/s]

 64%|██████▍   | 1024/1600 [08:14<03:53,  2.46it/s]

 64%|██████▍   | 1025/1600 [08:14<03:44,  2.56it/s]

 64%|██████▍   | 1026/1600 [08:15<03:43,  2.57it/s]

 64%|██████▍   | 1027/1600 [08:15<03:18,  2.89it/s]

 64%|██████▍   | 1029/1600 [08:17<06:14,  1.52it/s]

 64%|██████▍   | 1030/1600 [08:17<05:51,  1.62it/s]

 64%|██████▍   | 1031/1600 [08:18<05:04,  1.87it/s]

 64%|██████▍   | 1032/1600 [08:18<04:23,  2.15it/s]

 65%|██████▍   | 1033/1600 [08:18<03:57,  2.38it/s]

 65%|██████▍   | 1035/1600 [08:18<02:38,  3.56it/s]

 65%|██████▍   | 1036/1600 [08:19<02:44,  3.42it/s]

 65%|██████▍   | 1037/1600 [08:21<06:59,  1.34it/s]

 65%|██████▍   | 1038/1600 [08:21<05:49,  1.61it/s]

 65%|██████▍   | 1039/1600 [08:22<05:11,  1.80it/s]

 65%|██████▌   | 1040/1600 [08:22<04:05,  2.28it/s]

 65%|██████▌   | 1041/1600 [08:22<04:05,  2.28it/s]

 65%|██████▌   | 1043/1600 [08:22<02:41,  3.44it/s]

 65%|██████▌   | 1044/1600 [08:23<02:44,  3.37it/s]

 65%|██████▌   | 1045/1600 [08:25<06:43,  1.38it/s]

 65%|██████▌   | 1046/1600 [08:25<05:54,  1.56it/s]

 65%|██████▌   | 1047/1600 [08:25<04:55,  1.87it/s]

 66%|██████▌   | 1049/1600 [08:26<03:51,  2.38it/s]

 66%|██████▌   | 1050/1600 [08:26<03:24,  2.69it/s]

 66%|██████▌   | 1052/1600 [08:26<02:34,  3.54it/s]

 66%|██████▌   | 1053/1600 [08:28<06:17,  1.45it/s]

 66%|██████▌   | 1054/1600 [08:29<05:43,  1.59it/s]

 66%|██████▌   | 1055/1600 [08:29<04:33,  1.99it/s]

 66%|██████▌   | 1056/1600 [08:29<03:47,  2.39it/s]

 66%|██████▌   | 1057/1600 [08:30<03:38,  2.48it/s]

 66%|██████▌   | 1058/1600 [08:30<03:18,  2.73it/s]

 66%|██████▌   | 1059/1600 [08:30<02:53,  3.11it/s]

 66%|██████▋   | 1060/1600 [08:30<02:32,  3.54it/s]

 66%|██████▋   | 1061/1600 [08:32<07:05,  1.27it/s]

 66%|██████▋   | 1062/1600 [08:33<06:16,  1.43it/s]

 66%|██████▋   | 1063/1600 [08:33<04:50,  1.85it/s]

 67%|██████▋   | 1065/1600 [08:34<03:51,  2.31it/s]

 67%|██████▋   | 1066/1600 [08:34<03:22,  2.64it/s]

 67%|██████▋   | 1067/1600 [08:34<03:13,  2.75it/s]

 67%|██████▋   | 1068/1600 [08:34<03:19,  2.67it/s]

 67%|██████▋   | 1069/1600 [08:36<06:15,  1.41it/s]

 67%|██████▋   | 1070/1600 [08:36<05:34,  1.59it/s]

 67%|██████▋   | 1071/1600 [08:37<04:44,  1.86it/s]

 67%|██████▋   | 1072/1600 [08:37<04:13,  2.08it/s]

 67%|██████▋   | 1073/1600 [08:37<03:26,  2.55it/s]

 67%|██████▋   | 1074/1600 [08:38<03:29,  2.51it/s]

 67%|██████▋   | 1075/1600 [08:38<03:47,  2.31it/s]

 67%|██████▋   | 1076/1600 [08:39<03:41,  2.36it/s]

 67%|██████▋   | 1077/1600 [08:40<05:29,  1.59it/s]

 67%|██████▋   | 1078/1600 [08:40<05:48,  1.50it/s]

 68%|██████▊   | 1080/1600 [08:41<03:53,  2.23it/s]

 68%|██████▊   | 1081/1600 [08:41<03:16,  2.64it/s]

 68%|██████▊   | 1082/1600 [08:42<03:34,  2.42it/s]

 68%|██████▊   | 1083/1600 [08:42<03:52,  2.23it/s]

 68%|██████▊   | 1084/1600 [08:42<03:27,  2.48it/s]

 68%|██████▊   | 1085/1600 [08:44<05:30,  1.56it/s]

 68%|██████▊   | 1086/1600 [08:44<05:12,  1.64it/s]

 68%|██████▊   | 1087/1600 [08:44<04:26,  1.92it/s]

 68%|██████▊   | 1089/1600 [08:45<02:59,  2.85it/s]

 68%|██████▊   | 1090/1600 [08:46<04:05,  2.08it/s]

 68%|██████▊   | 1091/1600 [08:46<03:18,  2.57it/s]

 68%|██████▊   | 1092/1600 [08:46<03:46,  2.24it/s]

 68%|██████▊   | 1093/1600 [08:48<06:08,  1.38it/s]

 68%|██████▊   | 1094/1600 [08:48<05:12,  1.62it/s]

 68%|██████▊   | 1095/1600 [08:48<04:07,  2.04it/s]

 68%|██████▊   | 1096/1600 [08:48<03:17,  2.56it/s]

 69%|██████▊   | 1097/1600 [08:49<03:11,  2.63it/s]

 69%|██████▊   | 1098/1600 [08:49<03:48,  2.20it/s]

 69%|██████▊   | 1099/1600 [08:50<03:48,  2.19it/s]

 69%|██████▉   | 1100/1600 [08:50<03:42,  2.24it/s]

 69%|██████▉   | 1101/1600 [08:52<05:41,  1.46it/s]

 69%|██████▉   | 1102/1600 [08:52<05:41,  1.46it/s]

 69%|██████▉   | 1104/1600 [08:52<03:26,  2.40it/s]

 69%|██████▉   | 1105/1600 [08:53<03:28,  2.37it/s]

 69%|██████▉   | 1106/1600 [08:53<02:56,  2.80it/s]

 69%|██████▉   | 1107/1600 [08:54<03:29,  2.35it/s]

 69%|██████▉   | 1108/1600 [08:54<03:41,  2.22it/s]

 69%|██████▉   | 1109/1600 [08:55<05:18,  1.54it/s]

 69%|██████▉   | 1110/1600 [08:56<05:13,  1.56it/s]

 69%|██████▉   | 1111/1600 [08:56<03:58,  2.05it/s]

 70%|██████▉   | 1112/1600 [08:56<03:10,  2.56it/s]

 70%|██████▉   | 1113/1600 [08:57<03:06,  2.61it/s]

 70%|██████▉   | 1115/1600 [08:57<03:10,  2.55it/s]

 70%|██████▉   | 1116/1600 [08:58<03:16,  2.47it/s]

 70%|██████▉   | 1117/1600 [08:59<05:02,  1.60it/s]

 70%|██████▉   | 1118/1600 [09:00<05:04,  1.58it/s]

 70%|███████   | 1120/1600 [09:00<03:26,  2.33it/s]

 70%|███████   | 1121/1600 [09:00<02:54,  2.75it/s]

 70%|███████   | 1123/1600 [09:01<03:05,  2.57it/s]

 70%|███████   | 1124/1600 [09:02<04:00,  1.98it/s]

 70%|███████   | 1125/1600 [09:03<04:36,  1.72it/s]

 70%|███████   | 1126/1600 [09:04<05:06,  1.55it/s]

 70%|███████   | 1127/1600 [09:04<04:12,  1.87it/s]

 71%|███████   | 1129/1600 [09:04<03:16,  2.39it/s]

 71%|███████   | 1130/1600 [09:05<02:43,  2.88it/s]

 71%|███████   | 1131/1600 [09:05<02:29,  3.14it/s]

 71%|███████   | 1132/1600 [09:06<05:02,  1.55it/s]

 71%|███████   | 1133/1600 [09:07<04:19,  1.80it/s]

 71%|███████   | 1134/1600 [09:07<04:50,  1.60it/s]

 71%|███████   | 1135/1600 [09:08<04:00,  1.94it/s]

 71%|███████   | 1136/1600 [09:08<03:28,  2.23it/s]

 71%|███████   | 1137/1600 [09:08<02:45,  2.81it/s]

 71%|███████   | 1138/1600 [09:08<02:41,  2.86it/s]

 71%|███████   | 1139/1600 [09:09<02:27,  3.14it/s]

 71%|███████▏  | 1140/1600 [09:10<05:12,  1.47it/s]

 71%|███████▏  | 1141/1600 [09:11<04:26,  1.72it/s]

 71%|███████▏  | 1142/1600 [09:11<04:59,  1.53it/s]

 72%|███████▏  | 1144/1600 [09:12<03:17,  2.31it/s]

 72%|███████▏  | 1145/1600 [09:12<02:54,  2.61it/s]

 72%|███████▏  | 1146/1600 [09:12<02:27,  3.08it/s]

 72%|███████▏  | 1147/1600 [09:12<02:25,  3.12it/s]

 72%|███████▏  | 1148/1600 [09:14<04:37,  1.63it/s]

 72%|███████▏  | 1149/1600 [09:14<04:33,  1.65it/s]

 72%|███████▏  | 1150/1600 [09:15<04:39,  1.61it/s]

 72%|███████▏  | 1151/1600 [09:15<03:52,  1.93it/s]

 72%|███████▏  | 1152/1600 [09:16<03:03,  2.44it/s]

 72%|███████▏  | 1153/1600 [09:16<02:32,  2.93it/s]

 72%|███████▏  | 1154/1600 [09:16<02:07,  3.49it/s]

 72%|███████▏  | 1155/1600 [09:16<02:15,  3.29it/s]

 72%|███████▏  | 1156/1600 [09:18<04:53,  1.51it/s]

 72%|███████▏  | 1157/1600 [09:19<05:59,  1.23it/s]

 72%|███████▏  | 1159/1600 [09:19<03:42,  1.98it/s]

 72%|███████▎  | 1160/1600 [09:19<03:07,  2.35it/s]

 73%|███████▎  | 1161/1600 [09:20<03:31,  2.08it/s]

 73%|███████▎  | 1162/1600 [09:20<02:56,  2.49it/s]

 73%|███████▎  | 1163/1600 [09:20<02:48,  2.59it/s]

 73%|███████▎  | 1164/1600 [09:22<04:11,  1.73it/s]

 73%|███████▎  | 1165/1600 [09:23<05:21,  1.35it/s]

 73%|███████▎  | 1167/1600 [09:23<03:33,  2.03it/s]

 73%|███████▎  | 1168/1600 [09:23<03:19,  2.16it/s]

 73%|███████▎  | 1169/1600 [09:24<03:14,  2.21it/s]

 73%|███████▎  | 1170/1600 [09:24<03:11,  2.25it/s]

 73%|███████▎  | 1171/1600 [09:25<02:42,  2.64it/s]

 73%|███████▎  | 1172/1600 [09:25<03:23,  2.10it/s]

 73%|███████▎  | 1173/1600 [09:26<04:57,  1.44it/s]

 73%|███████▎  | 1175/1600 [09:27<03:27,  2.05it/s]

 74%|███████▎  | 1176/1600 [09:27<03:12,  2.21it/s]

 74%|███████▎  | 1177/1600 [09:28<03:18,  2.14it/s]

 74%|███████▎  | 1178/1600 [09:28<03:00,  2.34it/s]

 74%|███████▎  | 1179/1600 [09:28<02:28,  2.83it/s]

 74%|███████▍  | 1180/1600 [09:29<03:17,  2.13it/s]

 74%|███████▍  | 1181/1600 [09:30<04:41,  1.49it/s]

 74%|███████▍  | 1183/1600 [09:31<03:12,  2.16it/s]

 74%|███████▍  | 1184/1600 [09:31<03:17,  2.11it/s]

 74%|███████▍  | 1185/1600 [09:32<03:09,  2.19it/s]

 74%|███████▍  | 1186/1600 [09:32<02:46,  2.49it/s]

 74%|███████▍  | 1187/1600 [09:32<02:48,  2.46it/s]

 74%|███████▍  | 1188/1600 [09:33<02:51,  2.41it/s]

 74%|███████▍  | 1189/1600 [09:34<04:35,  1.49it/s]

 74%|███████▍  | 1190/1600 [09:34<03:49,  1.79it/s]

 74%|███████▍  | 1192/1600 [09:35<03:06,  2.19it/s]

 75%|███████▍  | 1193/1600 [09:35<03:20,  2.03it/s]

 75%|███████▍  | 1194/1600 [09:36<03:04,  2.21it/s]

 75%|███████▍  | 1195/1600 [09:36<03:02,  2.22it/s]

 75%|███████▍  | 1196/1600 [09:37<03:02,  2.21it/s]

 75%|███████▍  | 1197/1600 [09:38<04:36,  1.46it/s]

 75%|███████▍  | 1199/1600 [09:38<02:51,  2.34it/s]

 75%|███████▌  | 1200/1600 [09:39<03:36,  1.85it/s]

 75%|███████▌  | 1201/1600 [09:40<03:26,  1.93it/s]

 75%|███████▌  | 1203/1600 [09:40<02:57,  2.24it/s]

 75%|███████▌  | 1204/1600 [09:41<02:57,  2.23it/s]

 75%|███████▌  | 1205/1600 [09:42<03:37,  1.82it/s]

 75%|███████▌  | 1206/1600 [09:42<03:30,  1.87it/s]

 76%|███████▌  | 1208/1600 [09:43<03:09,  2.07it/s]

 76%|███████▌  | 1209/1600 [09:43<03:04,  2.12it/s]

 76%|███████▌  | 1211/1600 [09:44<02:44,  2.37it/s]

 76%|███████▌  | 1212/1600 [09:45<02:49,  2.29it/s]

 76%|███████▌  | 1213/1600 [09:45<03:09,  2.04it/s]

 76%|███████▌  | 1214/1600 [09:46<03:18,  1.95it/s]

 76%|███████▌  | 1215/1600 [09:46<02:38,  2.42it/s]

 76%|███████▌  | 1216/1600 [09:47<03:18,  1.93it/s]

 76%|███████▌  | 1217/1600 [09:47<02:59,  2.14it/s]

 76%|███████▌  | 1219/1600 [09:48<02:42,  2.34it/s]

 76%|███████▋  | 1220/1600 [09:48<02:43,  2.32it/s]

 76%|███████▋  | 1221/1600 [09:49<02:59,  2.11it/s]

 76%|███████▋  | 1222/1600 [09:50<03:42,  1.70it/s]

 76%|███████▋  | 1224/1600 [09:50<03:05,  2.02it/s]

 77%|███████▋  | 1225/1600 [09:51<02:39,  2.35it/s]

 77%|███████▋  | 1226/1600 [09:51<02:15,  2.76it/s]

 77%|███████▋  | 1227/1600 [09:52<03:40,  1.69it/s]

 77%|███████▋  | 1228/1600 [09:52<02:53,  2.14it/s]

 77%|███████▋  | 1229/1600 [09:53<03:02,  2.03it/s]

 77%|███████▋  | 1230/1600 [09:53<03:18,  1.87it/s]

 77%|███████▋  | 1231/1600 [09:54<02:44,  2.24it/s]

 77%|███████▋  | 1232/1600 [09:55<03:34,  1.71it/s]

 77%|███████▋  | 1233/1600 [09:55<03:12,  1.91it/s]

 77%|███████▋  | 1235/1600 [09:56<03:00,  2.02it/s]

 77%|███████▋  | 1236/1600 [09:56<02:34,  2.36it/s]

 77%|███████▋  | 1237/1600 [09:57<03:05,  1.95it/s]

 77%|███████▋  | 1238/1600 [09:57<02:51,  2.11it/s]

 77%|███████▋  | 1239/1600 [09:58<02:40,  2.25it/s]

 78%|███████▊  | 1240/1600 [09:58<03:16,  1.83it/s]

 78%|███████▊  | 1241/1600 [09:59<03:00,  1.99it/s]

 78%|███████▊  | 1243/1600 [10:00<02:45,  2.15it/s]

 78%|███████▊  | 1244/1600 [10:00<02:30,  2.36it/s]

 78%|███████▊  | 1245/1600 [10:01<02:47,  2.12it/s]

 78%|███████▊  | 1246/1600 [10:01<02:34,  2.30it/s]

 78%|███████▊  | 1247/1600 [10:01<02:35,  2.26it/s]

 78%|███████▊  | 1248/1600 [10:02<03:15,  1.80it/s]

 78%|███████▊  | 1249/1600 [10:02<02:51,  2.05it/s]

 78%|███████▊  | 1251/1600 [10:03<02:41,  2.16it/s]

 78%|███████▊  | 1252/1600 [10:04<02:29,  2.32it/s]

 78%|███████▊  | 1253/1600 [10:04<02:27,  2.35it/s]

 78%|███████▊  | 1254/1600 [10:05<02:26,  2.37it/s]

 78%|███████▊  | 1255/1600 [10:05<02:39,  2.17it/s]

 78%|███████▊  | 1256/1600 [10:06<03:37,  1.58it/s]

 79%|███████▊  | 1257/1600 [10:06<02:57,  1.93it/s]

 79%|███████▊  | 1258/1600 [10:07<02:20,  2.44it/s]

 79%|███████▊  | 1259/1600 [10:07<02:29,  2.28it/s]

 79%|███████▉  | 1260/1600 [10:08<03:16,  1.73it/s]

 79%|███████▉  | 1261/1600 [10:08<02:48,  2.01it/s]

 79%|███████▉  | 1262/1600 [10:08<02:08,  2.64it/s]

 79%|███████▉  | 1263/1600 [10:09<02:25,  2.31it/s]

 79%|███████▉  | 1264/1600 [10:10<03:22,  1.66it/s]

 79%|███████▉  | 1265/1600 [10:10<02:48,  1.99it/s]

 79%|███████▉  | 1266/1600 [10:10<02:27,  2.27it/s]

 79%|███████▉  | 1267/1600 [10:11<02:50,  1.96it/s]

 79%|███████▉  | 1268/1600 [10:12<02:58,  1.86it/s]

 79%|███████▉  | 1269/1600 [10:12<02:49,  1.96it/s]

 79%|███████▉  | 1271/1600 [10:13<02:32,  2.15it/s]

 80%|███████▉  | 1272/1600 [10:14<02:50,  1.92it/s]

 80%|███████▉  | 1273/1600 [10:14<02:35,  2.10it/s]

 80%|███████▉  | 1274/1600 [10:14<02:27,  2.22it/s]

 80%|███████▉  | 1275/1600 [10:15<02:51,  1.90it/s]

 80%|███████▉  | 1276/1600 [10:15<02:28,  2.18it/s]

 80%|███████▉  | 1277/1600 [10:16<02:37,  2.04it/s]

 80%|███████▉  | 1279/1600 [10:17<02:25,  2.20it/s]

 80%|████████  | 1280/1600 [10:17<02:37,  2.03it/s]

 80%|████████  | 1281/1600 [10:18<02:15,  2.35it/s]

 80%|████████  | 1282/1600 [10:18<02:16,  2.33it/s]

 80%|████████  | 1283/1600 [10:19<02:40,  1.98it/s]

 80%|████████  | 1284/1600 [10:19<02:23,  2.21it/s]

 80%|████████  | 1285/1600 [10:20<02:22,  2.21it/s]

 80%|████████  | 1286/1600 [10:20<01:49,  2.86it/s]

 80%|████████  | 1287/1600 [10:21<02:41,  1.94it/s]

 80%|████████  | 1288/1600 [10:21<03:12,  1.62it/s]

 81%|████████  | 1289/1600 [10:22<02:27,  2.11it/s]

 81%|████████  | 1290/1600 [10:22<02:12,  2.33it/s]

 81%|████████  | 1291/1600 [10:22<02:26,  2.12it/s]

 81%|████████  | 1292/1600 [10:23<02:35,  1.98it/s]

 81%|████████  | 1294/1600 [10:24<02:31,  2.02it/s]

 81%|████████  | 1295/1600 [10:25<03:16,  1.55it/s]

 81%|████████  | 1296/1600 [10:25<02:35,  1.95it/s]

 81%|████████  | 1297/1600 [10:26<02:17,  2.20it/s]

 81%|████████  | 1298/1600 [10:26<02:20,  2.14it/s]

 81%|████████  | 1299/1600 [10:26<01:58,  2.53it/s]

 81%|████████▏ | 1300/1600 [10:27<01:59,  2.51it/s]

 81%|████████▏ | 1301/1600 [10:27<01:53,  2.63it/s]

 81%|████████▏ | 1302/1600 [10:28<02:54,  1.71it/s]

 81%|████████▏ | 1303/1600 [10:29<03:18,  1.50it/s]

 82%|████████▏ | 1304/1600 [10:29<02:32,  1.94it/s]

 82%|████████▏ | 1305/1600 [10:29<02:05,  2.36it/s]

 82%|████████▏ | 1306/1600 [10:30<02:31,  1.94it/s]

 82%|████████▏ | 1307/1600 [10:30<01:56,  2.52it/s]

 82%|████████▏ | 1308/1600 [10:31<01:53,  2.57it/s]

 82%|████████▏ | 1309/1600 [10:31<01:47,  2.70it/s]

 82%|████████▏ | 1310/1600 [10:32<02:30,  1.93it/s]

 82%|████████▏ | 1311/1600 [10:33<03:04,  1.57it/s]

 82%|████████▏ | 1312/1600 [10:33<02:25,  1.97it/s]

 82%|████████▏ | 1313/1600 [10:33<01:55,  2.49it/s]

 82%|████████▏ | 1314/1600 [10:34<02:27,  1.94it/s]

 82%|████████▏ | 1316/1600 [10:34<01:49,  2.59it/s]

 82%|████████▏ | 1317/1600 [10:34<01:37,  2.91it/s]

 82%|████████▏ | 1318/1600 [10:35<02:21,  1.99it/s]

 82%|████████▏ | 1319/1600 [10:37<03:19,  1.41it/s]

 83%|████████▎ | 1321/1600 [10:37<02:02,  2.28it/s]

 83%|████████▎ | 1322/1600 [10:38<02:19,  1.99it/s]

 83%|████████▎ | 1323/1600 [10:38<02:13,  2.08it/s]

 83%|████████▎ | 1324/1600 [10:38<01:49,  2.52it/s]

 83%|████████▎ | 1325/1600 [10:38<01:30,  3.05it/s]

 83%|████████▎ | 1326/1600 [10:39<02:21,  1.94it/s]

 83%|████████▎ | 1327/1600 [10:41<03:21,  1.36it/s]

 83%|████████▎ | 1328/1600 [10:41<02:56,  1.54it/s]

 83%|████████▎ | 1329/1600 [10:41<02:13,  2.03it/s]

 83%|████████▎ | 1330/1600 [10:41<01:48,  2.48it/s]

 83%|████████▎ | 1331/1600 [10:42<01:48,  2.48it/s]

 83%|████████▎ | 1332/1600 [10:42<01:42,  2.61it/s]

 83%|████████▎ | 1333/1600 [10:42<01:27,  3.06it/s]

 83%|████████▎ | 1334/1600 [10:43<02:27,  1.80it/s]

 83%|████████▎ | 1335/1600 [10:45<03:31,  1.25it/s]

 84%|████████▎ | 1336/1600 [10:45<02:54,  1.51it/s]

 84%|████████▎ | 1338/1600 [10:45<01:40,  2.60it/s]

 84%|████████▎ | 1339/1600 [10:46<01:36,  2.70it/s]

 84%|████████▍ | 1340/1600 [10:46<01:44,  2.49it/s]

 84%|████████▍ | 1342/1600 [10:47<02:03,  2.10it/s]

 84%|████████▍ | 1343/1600 [10:48<02:48,  1.53it/s]

 84%|████████▍ | 1344/1600 [10:49<02:26,  1.75it/s]

 84%|████████▍ | 1345/1600 [10:49<01:56,  2.19it/s]

 84%|████████▍ | 1347/1600 [10:49<01:29,  2.81it/s]

 84%|████████▍ | 1348/1600 [10:50<01:29,  2.80it/s]

 84%|████████▍ | 1350/1600 [10:51<01:54,  2.18it/s]

 84%|████████▍ | 1351/1600 [10:52<02:32,  1.63it/s]

 84%|████████▍ | 1352/1600 [10:53<02:26,  1.69it/s]

 85%|████████▍ | 1354/1600 [10:53<01:43,  2.38it/s]

 85%|████████▍ | 1355/1600 [10:53<01:25,  2.87it/s]

 85%|████████▍ | 1356/1600 [10:53<01:18,  3.10it/s]

 85%|████████▍ | 1357/1600 [10:54<01:24,  2.88it/s]

 85%|████████▍ | 1358/1600 [10:55<02:05,  1.92it/s]

 85%|████████▍ | 1359/1600 [10:56<02:40,  1.50it/s]

 85%|████████▌ | 1360/1600 [10:56<02:39,  1.51it/s]

 85%|████████▌ | 1361/1600 [10:57<02:24,  1.66it/s]

 85%|████████▌ | 1363/1600 [10:57<01:33,  2.53it/s]

 85%|████████▌ | 1365/1600 [10:58<01:30,  2.61it/s]

 85%|████████▌ | 1366/1600 [10:58<01:37,  2.40it/s]

 85%|████████▌ | 1367/1600 [11:00<02:30,  1.55it/s]

 86%|████████▌ | 1368/1600 [11:00<02:15,  1.71it/s]

 86%|████████▌ | 1369/1600 [11:01<02:05,  1.85it/s]

 86%|████████▌ | 1370/1600 [11:01<01:48,  2.12it/s]

 86%|████████▌ | 1373/1600 [11:02<01:27,  2.59it/s]

 86%|████████▌ | 1374/1600 [11:02<01:28,  2.56it/s]

 86%|████████▌ | 1375/1600 [11:04<02:17,  1.64it/s]

 86%|████████▌ | 1376/1600 [11:04<01:55,  1.94it/s]

 86%|████████▌ | 1377/1600 [11:04<01:53,  1.96it/s]

 86%|████████▌ | 1378/1600 [11:05<01:38,  2.26it/s]

 86%|████████▌ | 1379/1600 [11:05<01:17,  2.86it/s]

 86%|████████▋ | 1381/1600 [11:06<01:26,  2.52it/s]

 86%|████████▋ | 1382/1600 [11:06<01:21,  2.68it/s]

 86%|████████▋ | 1383/1600 [11:07<02:12,  1.63it/s]

 86%|████████▋ | 1384/1600 [11:08<01:56,  1.85it/s]

 87%|████████▋ | 1385/1600 [11:08<01:52,  1.91it/s]

 87%|████████▋ | 1386/1600 [11:08<01:41,  2.10it/s]

 87%|████████▋ | 1388/1600 [11:09<01:10,  2.99it/s]

 87%|████████▋ | 1389/1600 [11:09<01:25,  2.46it/s]

 87%|████████▋ | 1390/1600 [11:10<01:14,  2.82it/s]

 87%|████████▋ | 1391/1600 [11:11<02:16,  1.53it/s]

 87%|████████▋ | 1392/1600 [11:11<01:51,  1.86it/s]

 87%|████████▋ | 1393/1600 [11:12<02:23,  1.44it/s]

 87%|████████▋ | 1394/1600 [11:12<01:48,  1.90it/s]

 87%|████████▋ | 1396/1600 [11:13<01:11,  2.85it/s]

 87%|████████▋ | 1397/1600 [11:13<01:23,  2.42it/s]

 87%|████████▋ | 1398/1600 [11:14<01:26,  2.33it/s]

 87%|████████▋ | 1399/1600 [11:15<01:50,  1.81it/s]

 88%|████████▊ | 1400/1600 [11:15<02:02,  1.63it/s]

 88%|████████▊ | 1401/1600 [11:16<02:03,  1.62it/s]

 88%|████████▊ | 1403/1600 [11:16<01:18,  2.51it/s]

 88%|████████▊ | 1404/1600 [11:17<01:23,  2.36it/s]

 88%|████████▊ | 1405/1600 [11:17<01:17,  2.53it/s]

 88%|████████▊ | 1406/1600 [11:18<01:21,  2.38it/s]

 88%|████████▊ | 1407/1600 [11:18<01:44,  1.84it/s]

 88%|████████▊ | 1408/1600 [11:19<01:53,  1.69it/s]

 88%|████████▊ | 1409/1600 [11:20<01:57,  1.62it/s]

 88%|████████▊ | 1411/1600 [11:20<01:15,  2.50it/s]

 88%|████████▊ | 1412/1600 [11:21<01:14,  2.51it/s]

 88%|████████▊ | 1413/1600 [11:21<01:08,  2.75it/s]

 88%|████████▊ | 1414/1600 [11:21<01:12,  2.56it/s]

 88%|████████▊ | 1415/1600 [11:22<01:42,  1.81it/s]

 88%|████████▊ | 1416/1600 [11:23<01:48,  1.69it/s]

 89%|████████▊ | 1417/1600 [11:24<01:54,  1.60it/s]

 89%|████████▊ | 1418/1600 [11:24<01:35,  1.91it/s]

 89%|████████▉ | 1420/1600 [11:24<01:12,  2.48it/s]

 89%|████████▉ | 1421/1600 [11:25<01:07,  2.66it/s]

 89%|████████▉ | 1422/1600 [11:25<01:04,  2.74it/s]

 89%|████████▉ | 1423/1600 [11:26<01:38,  1.80it/s]

 89%|████████▉ | 1424/1600 [11:27<01:40,  1.75it/s]

 89%|████████▉ | 1425/1600 [11:28<02:02,  1.42it/s]

 89%|████████▉ | 1427/1600 [11:28<01:31,  1.90it/s]

 89%|████████▉ | 1429/1600 [11:29<01:05,  2.60it/s]

 89%|████████▉ | 1430/1600 [11:29<01:13,  2.31it/s]

 89%|████████▉ | 1431/1600 [11:30<01:17,  2.19it/s]

 90%|████████▉ | 1432/1600 [11:31<01:29,  1.87it/s]

 90%|████████▉ | 1433/1600 [11:32<01:45,  1.58it/s]

 90%|████████▉ | 1434/1600 [11:32<01:24,  1.96it/s]

 90%|████████▉ | 1435/1600 [11:32<01:27,  1.88it/s]

 90%|████████▉ | 1436/1600 [11:33<01:13,  2.23it/s]

 90%|████████▉ | 1437/1600 [11:33<01:01,  2.64it/s]

 90%|████████▉ | 1438/1600 [11:33<01:18,  2.06it/s]

 90%|█████████ | 1440/1600 [11:34<01:15,  2.12it/s]

 90%|█████████ | 1441/1600 [11:36<01:39,  1.60it/s]

 90%|█████████ | 1442/1600 [11:36<01:18,  2.01it/s]

 90%|█████████ | 1443/1600 [11:36<01:13,  2.13it/s]

 90%|█████████ | 1444/1600 [11:36<01:07,  2.32it/s]

 90%|█████████ | 1446/1600 [11:37<01:15,  2.03it/s]

 90%|█████████ | 1448/1600 [11:38<01:10,  2.16it/s]

 91%|█████████ | 1449/1600 [11:39<01:24,  1.78it/s]

 91%|█████████ | 1450/1600 [11:39<01:09,  2.14it/s]

 91%|█████████ | 1451/1600 [11:40<01:04,  2.31it/s]

 91%|█████████ | 1452/1600 [11:40<01:01,  2.42it/s]

 91%|█████████ | 1454/1600 [11:41<01:06,  2.18it/s]

 91%|█████████ | 1455/1600 [11:42<01:05,  2.21it/s]

 91%|█████████ | 1456/1600 [11:42<01:09,  2.07it/s]

 91%|█████████ | 1457/1600 [11:43<01:26,  1.65it/s]

 91%|█████████ | 1458/1600 [11:43<01:16,  1.86it/s]

 91%|█████████ | 1459/1600 [11:44<01:00,  2.35it/s]

 91%|█████████▏| 1460/1600 [11:44<01:03,  2.19it/s]

 91%|█████████▏| 1461/1600 [11:44<00:52,  2.63it/s]

 91%|█████████▏| 1462/1600 [11:45<01:00,  2.28it/s]

 91%|█████████▏| 1463/1600 [11:46<01:24,  1.62it/s]

 92%|█████████▏| 1464/1600 [11:46<01:12,  1.87it/s]

 92%|█████████▏| 1465/1600 [11:47<01:18,  1.72it/s]

 92%|█████████▏| 1466/1600 [11:47<01:01,  2.19it/s]

 92%|█████████▏| 1467/1600 [11:48<01:00,  2.19it/s]

 92%|█████████▏| 1468/1600 [11:48<01:06,  1.98it/s]

 92%|█████████▏| 1470/1600 [11:49<00:53,  2.42it/s]

 92%|█████████▏| 1471/1600 [11:50<01:09,  1.86it/s]

 92%|█████████▏| 1472/1600 [11:50<01:02,  2.06it/s]

 92%|█████████▏| 1473/1600 [11:51<01:05,  1.93it/s]

 92%|█████████▏| 1474/1600 [11:51<00:58,  2.14it/s]

 92%|█████████▏| 1475/1600 [11:51<00:58,  2.14it/s]

 92%|█████████▏| 1476/1600 [11:52<01:00,  2.06it/s]

 92%|█████████▏| 1478/1600 [11:53<00:47,  2.57it/s]

 92%|█████████▏| 1479/1600 [11:53<01:02,  1.95it/s]

 92%|█████████▎| 1480/1600 [11:54<00:53,  2.24it/s]

 93%|█████████▎| 1481/1600 [11:54<00:58,  2.04it/s]

 93%|█████████▎| 1482/1600 [11:55<00:54,  2.15it/s]

 93%|█████████▎| 1483/1600 [11:55<00:55,  2.12it/s]

 93%|█████████▎| 1484/1600 [11:56<00:55,  2.10it/s]

 93%|█████████▎| 1485/1600 [11:56<00:42,  2.70it/s]

 93%|█████████▎| 1486/1600 [11:56<00:50,  2.27it/s]

 93%|█████████▎| 1487/1600 [11:57<01:00,  1.88it/s]

 93%|█████████▎| 1488/1600 [11:57<00:51,  2.19it/s]

 93%|█████████▎| 1489/1600 [11:58<01:04,  1.71it/s]

 93%|█████████▎| 1490/1600 [11:58<00:49,  2.22it/s]

 93%|█████████▎| 1491/1600 [11:59<01:03,  1.72it/s]

 93%|█████████▎| 1492/1600 [12:00<00:51,  2.10it/s]

 93%|█████████▎| 1493/1600 [12:00<00:54,  1.96it/s]

 93%|█████████▎| 1495/1600 [12:01<00:54,  1.94it/s]

 94%|█████████▎| 1496/1600 [12:01<00:43,  2.41it/s]

 94%|█████████▎| 1497/1600 [12:02<00:51,  1.99it/s]

 94%|█████████▎| 1498/1600 [12:03<00:51,  1.97it/s]

 94%|█████████▎| 1499/1600 [12:03<00:54,  1.85it/s]

 94%|█████████▍| 1500/1600 [12:03<00:45,  2.18it/s]

 94%|█████████▍| 1501/1600 [12:04<00:51,  1.91it/s]

 94%|█████████▍| 1503/1600 [12:05<00:50,  1.93it/s]

 94%|█████████▍| 1504/1600 [12:05<00:41,  2.31it/s]

 94%|█████████▍| 1505/1600 [12:06<00:46,  2.05it/s]

 94%|█████████▍| 1506/1600 [12:06<00:40,  2.30it/s]

 94%|█████████▍| 1507/1600 [12:07<00:46,  2.01it/s]

 94%|█████████▍| 1508/1600 [12:07<00:39,  2.31it/s]

 94%|█████████▍| 1509/1600 [12:08<00:44,  2.04it/s]

 94%|█████████▍| 1510/1600 [12:08<00:34,  2.57it/s]

 94%|█████████▍| 1511/1600 [12:09<00:48,  1.84it/s]

 94%|█████████▍| 1512/1600 [12:09<00:37,  2.37it/s]

 95%|█████████▍| 1513/1600 [12:10<00:42,  2.04it/s]

 95%|█████████▍| 1514/1600 [12:10<00:38,  2.22it/s]

 95%|█████████▍| 1515/1600 [12:11<00:40,  2.08it/s]

 95%|█████████▍| 1516/1600 [12:11<00:38,  2.21it/s]

 95%|█████████▍| 1517/1600 [12:12<00:40,  2.03it/s]

 95%|█████████▍| 1518/1600 [12:12<00:31,  2.63it/s]

 95%|█████████▍| 1519/1600 [12:13<00:50,  1.62it/s]

 95%|█████████▌| 1520/1600 [12:13<00:38,  2.09it/s]

 95%|█████████▌| 1521/1600 [12:13<00:35,  2.23it/s]

 95%|█████████▌| 1522/1600 [12:14<00:31,  2.50it/s]

 95%|█████████▌| 1523/1600 [12:14<00:33,  2.27it/s]

 95%|█████████▌| 1524/1600 [12:15<00:36,  2.07it/s]

 95%|█████████▌| 1525/1600 [12:16<00:46,  1.61it/s]

 95%|█████████▌| 1526/1600 [12:16<00:34,  2.13it/s]

 95%|█████████▌| 1527/1600 [12:17<00:41,  1.77it/s]

 96%|█████████▌| 1528/1600 [12:17<00:38,  1.87it/s]

 96%|█████████▌| 1529/1600 [12:17<00:30,  2.31it/s]

 96%|█████████▌| 1531/1600 [12:19<00:35,  1.94it/s]

 96%|█████████▌| 1532/1600 [12:19<00:35,  1.91it/s]

 96%|█████████▌| 1533/1600 [12:20<00:35,  1.89it/s]

 96%|█████████▌| 1534/1600 [12:20<00:31,  2.09it/s]

 96%|█████████▌| 1535/1600 [12:20<00:29,  2.17it/s]

 96%|█████████▌| 1536/1600 [12:21<00:29,  2.20it/s]

 96%|█████████▌| 1537/1600 [12:21<00:23,  2.73it/s]

 96%|█████████▌| 1538/1600 [12:21<00:24,  2.56it/s]

 96%|█████████▌| 1539/1600 [12:22<00:33,  1.80it/s]

 96%|█████████▋| 1540/1600 [12:23<00:33,  1.77it/s]

 96%|█████████▋| 1541/1600 [12:23<00:31,  1.88it/s]

 96%|█████████▋| 1542/1600 [12:24<00:28,  2.02it/s]

 96%|█████████▋| 1543/1600 [12:24<00:25,  2.26it/s]

 96%|█████████▋| 1544/1600 [12:25<00:25,  2.21it/s]

 97%|█████████▋| 1545/1600 [12:25<00:20,  2.72it/s]

 97%|█████████▋| 1546/1600 [12:25<00:18,  2.89it/s]

 97%|█████████▋| 1547/1600 [12:26<00:27,  1.92it/s]

 97%|█████████▋| 1548/1600 [12:27<00:30,  1.71it/s]

 97%|█████████▋| 1549/1600 [12:27<00:27,  1.84it/s]

 97%|█████████▋| 1550/1600 [12:27<00:23,  2.13it/s]

 97%|█████████▋| 1551/1600 [12:28<00:21,  2.23it/s]

 97%|█████████▋| 1552/1600 [12:28<00:20,  2.31it/s]

 97%|█████████▋| 1553/1600 [12:29<00:18,  2.54it/s]

 97%|█████████▋| 1554/1600 [12:29<00:15,  3.03it/s]

 97%|█████████▋| 1555/1600 [12:30<00:22,  1.97it/s]

 97%|█████████▋| 1556/1600 [12:31<00:30,  1.44it/s]

 97%|█████████▋| 1557/1600 [12:31<00:25,  1.68it/s]

 97%|█████████▋| 1558/1600 [12:31<00:19,  2.16it/s]

 97%|█████████▋| 1559/1600 [12:32<00:15,  2.59it/s]

 98%|█████████▊| 1560/1600 [12:32<00:16,  2.45it/s]

 98%|█████████▊| 1561/1600 [12:32<00:15,  2.58it/s]

 98%|█████████▊| 1562/1600 [12:33<00:12,  2.96it/s]

 98%|█████████▊| 1563/1600 [12:33<00:18,  1.98it/s]

 98%|█████████▊| 1564/1600 [12:35<00:25,  1.41it/s]

 98%|█████████▊| 1565/1600 [12:35<00:25,  1.40it/s]

 98%|█████████▊| 1567/1600 [12:36<00:14,  2.21it/s]

 98%|█████████▊| 1569/1600 [12:36<00:10,  2.82it/s]

 98%|█████████▊| 1570/1600 [12:37<00:13,  2.20it/s]

 98%|█████████▊| 1571/1600 [12:37<00:11,  2.51it/s]

 98%|█████████▊| 1572/1600 [12:39<00:18,  1.53it/s]

 98%|█████████▊| 1573/1600 [12:39<00:19,  1.42it/s]

 98%|█████████▊| 1575/1600 [12:40<00:11,  2.23it/s]

 98%|█████████▊| 1576/1600 [12:40<00:08,  2.68it/s]

 99%|█████████▊| 1577/1600 [12:40<00:07,  3.01it/s]

 99%|█████████▊| 1578/1600 [12:41<00:09,  2.38it/s]

 99%|█████████▊| 1579/1600 [12:41<00:08,  2.53it/s]

 99%|█████████▉| 1580/1600 [12:42<00:13,  1.46it/s]

 99%|█████████▉| 1581/1600 [12:43<00:13,  1.39it/s]

 99%|█████████▉| 1583/1600 [12:43<00:07,  2.21it/s]

 99%|█████████▉| 1584/1600 [12:44<00:06,  2.50it/s]

 99%|█████████▉| 1585/1600 [12:44<00:05,  2.74it/s]

 99%|█████████▉| 1586/1600 [12:45<00:07,  1.86it/s]

 99%|█████████▉| 1587/1600 [12:45<00:06,  2.15it/s]

 99%|█████████▉| 1588/1600 [12:47<00:08,  1.41it/s]

 99%|█████████▉| 1589/1600 [12:47<00:07,  1.40it/s]

 99%|█████████▉| 1590/1600 [12:48<00:05,  1.67it/s]

100%|█████████▉| 1592/1600 [12:48<00:03,  2.29it/s]

100%|█████████▉| 1593/1600 [12:48<00:02,  2.79it/s]

100%|█████████▉| 1594/1600 [12:49<00:02,  2.43it/s]

100%|█████████▉| 1595/1600 [12:49<00:01,  2.65it/s]

100%|█████████▉| 1596/1600 [12:50<00:02,  1.50it/s]

100%|█████████▉| 1597/1600 [12:51<00:01,  1.73it/s]

100%|█████████▉| 1598/1600 [12:51<00:00,  2.23it/s]

100%|██████████| 1600/1600 [12:51<00:00,  2.07it/s]
Families: 100%|██████████| 3/3 [22:02<00:00, 440.75s/it]

Runtime: 1322.249312 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

Multiplets | family 3:   0%|          | 0/46 [00:00<?, ?it/s]


  0%|          | 0/46 [00:00<?, ?it/s]


  2%|▏         | 1/46 [00:02<01:39,  2.21s/it]


 17%|█▋        | 8/46 [00:02<00:08,  4.65it/s]


 26%|██▌       | 12/46 [00:04<00:11,  2.85it/s]


 35%|███▍      | 16/46 [00:04<00:06,  4.36it/s]


 41%|████▏     | 19/46 [00:06<00:09,  2.74it/s]


 48%|████▊     | 22/46 [00:06<00:06,  3.65it/s]


 54%|█████▍    | 25/46 [00:08<00:08,  2.60it/s]


 61%|██████    | 28/46 [00:09<00:05,  3.35it/s]


 67%|██████▋   | 31/46 [00:09<00:03,  4.43it/s]


 72%|███████▏  | 33/46 [00:11<00:04,  2.61it/s]


 78%|███████▊  | 36/46 [00:11<00:02,  3.53it/s]


 83%|████████▎ | 38/46 [00:11<00:02,  3.65it/s]


 87%|████████▋ | 40/46 [00:11<00:01,  4.40it/s]


 89%|████████▉ | 41/46 [00:13<00:01,  2.61it/s]


 93%|█████████▎| 43/46 [00:13<00:00,  3.50it/s]


 96%|█████████▌| 44/46 [00:13<00:00,  3.93it/s]


 98%|█████████▊| 45/46 [00:13<00:00,  4.24it/s]


100%|██████████| 46/46 [00:13<00:00,  3.34it/s]
Multiplets | family 3:   0%|          | 0/46 [00:13<?, ?it/s]


Multiplets | family 4:   0%|          | 0/1185 [00:00<?, ?it/s]


  0%|          | 0/1185 [00:00<?, ?it/s]


  0%|          | 1/1185 [00:03<1:04:06,  3.25s/it]


  1%|          | 7/1185 [00:03<07:00,  2.80it/s]


  1%|          | 11/1185 [00:06<11:01,  1.78it/s]


  1%|          | 14/1185 [00:06<07:43,  2.53it/s]


  1%|▏         | 17/1185 [00:09<11:30,  1.69it/s]


  2%|▏         | 20/1185 [00:09<08:06,  2.40it/s]


  2%|▏         | 22/1185 [00:10<06:29,  2.98it/s]


  2%|▏         | 24/1185 [00:10<05:21,  3.61it/s]


  2%|▏         | 26/1185 [00:13<11:13,  1.72it/s]


  2%|▏         | 28/1185 [00:13<08:51,  2.18it/s]


  2%|▏         | 29/1185 [00:13<07:52,  2.44it/s]


  3%|▎         | 30/1185 [00:13<07:01,  2.74it/s]


  3%|▎         | 32/1185 [00:13<05:10,  3.71it/s]


  3%|▎         | 33/1185 [00:16<13:40,  1.40it/s]


  3%|▎         | 35/1185 [00:16<10:20,  1.85it/s]


  3%|▎         | 37/1185 [00:16<07:19,  2.61it/s]


  3%|▎         | 38/1185 [00:17<06:31,  2.93it/s]


  3%|▎         | 39/1185 [00:17<06:11,  3.08it/s]


  3%|▎         | 41/1185 [00:19<11:55,  1.60it/s]


  4%|▎         | 42/1185 [00:19<10:22,  1.84it/s]


  4%|▎         | 43/1185 [00:20<08:39,  2.20it/s]


  4%|▎         | 44/1185 [00:20<08:01,  2.37it/s]


  4%|▍         | 47/1185 [00:20<05:31,  3.43it/s]


  4%|▍         | 49/1185 [00:22<10:03,  1.88it/s]


  4%|▍         | 50/1185 [00:23<08:38,  2.19it/s]


  4%|▍         | 51/1185 [00:23<07:57,  2.38it/s]


  4%|▍         | 52/1185 [00:23<07:31,  2.51it/s]


  5%|▍         | 54/1185 [00:23<04:56,  3.82it/s]


  5%|▍         | 55/1185 [00:24<05:36,  3.35it/s]


  5%|▍         | 57/1185 [00:26<10:39,  1.76it/s]


  5%|▍         | 58/1185 [00:26<09:06,  2.06it/s]


  5%|▍         | 59/1185 [00:26<08:32,  2.20it/s]


  5%|▌         | 60/1185 [00:27<07:42,  2.43it/s]


  5%|▌         | 62/1185 [00:27<05:14,  3.57it/s]


  5%|▌         | 63/1185 [00:27<05:22,  3.48it/s]


  5%|▌         | 65/1185 [00:29<10:55,  1.71it/s]


  6%|▌         | 67/1185 [00:30<08:17,  2.25it/s]


  6%|▌         | 68/1185 [00:30<08:15,  2.26it/s]


  6%|▌         | 69/1185 [00:30<07:08,  2.60it/s]


  6%|▌         | 70/1185 [00:30<06:35,  2.82it/s]


  6%|▌         | 71/1185 [00:31<06:08,  3.02it/s]


  6%|▌         | 72/1185 [00:31<07:07,  2.60it/s]


  6%|▌         | 73/1185 [00:32<11:49,  1.57it/s]


  6%|▌         | 74/1185 [00:33<09:18,  1.99it/s]


  6%|▋         | 75/1185 [00:33<08:35,  2.15it/s]


  6%|▋         | 76/1185 [00:34<09:08,  2.02it/s]


  6%|▋         | 77/1185 [00:34<07:39,  2.41it/s]


  7%|▋         | 79/1185 [00:34<05:25,  3.39it/s]


  7%|▋         | 80/1185 [00:35<06:55,  2.66it/s]


  7%|▋         | 81/1185 [00:36<10:55,  1.69it/s]


  7%|▋         | 83/1185 [00:37<08:46,  2.09it/s]


  7%|▋         | 84/1185 [00:37<08:34,  2.14it/s]


  7%|▋         | 87/1185 [00:38<06:03,  3.02it/s]


  7%|▋         | 88/1185 [00:38<06:25,  2.84it/s]


  8%|▊         | 89/1185 [00:39<09:36,  1.90it/s]


  8%|▊         | 90/1185 [00:39<07:51,  2.32it/s]


  8%|▊         | 91/1185 [00:40<08:14,  2.21it/s]


  8%|▊         | 92/1185 [00:40<08:20,  2.18it/s]


  8%|▊         | 95/1185 [00:41<06:09,  2.95it/s]


  8%|▊         | 96/1185 [00:41<06:09,  2.95it/s]


  8%|▊         | 97/1185 [00:42<09:12,  1.97it/s]


  8%|▊         | 98/1185 [00:43<07:56,  2.28it/s]


  8%|▊         | 99/1185 [00:43<07:49,  2.31it/s]


  8%|▊         | 100/1185 [00:44<08:20,  2.17it/s]


  9%|▊         | 102/1185 [00:44<05:42,  3.17it/s]


  9%|▊         | 103/1185 [00:44<06:25,  2.81it/s]


  9%|▉         | 104/1185 [00:45<08:07,  2.22it/s]


  9%|▉         | 105/1185 [00:46<08:38,  2.08it/s]


  9%|▉         | 106/1185 [00:46<08:25,  2.13it/s]


  9%|▉         | 107/1185 [00:46<07:14,  2.48it/s]


  9%|▉         | 108/1185 [00:47<08:03,  2.23it/s]


  9%|▉         | 109/1185 [00:48<08:58,  2.00it/s]


  9%|▉         | 110/1185 [00:48<07:01,  2.55it/s]


  9%|▉         | 111/1185 [00:48<07:08,  2.51it/s]


  9%|▉         | 112/1185 [00:48<07:15,  2.46it/s]


 10%|▉         | 113/1185 [00:49<09:47,  1.83it/s]


 10%|▉         | 115/1185 [00:50<07:53,  2.26it/s]


 10%|▉         | 116/1185 [00:50<08:01,  2.22it/s]


 10%|▉         | 117/1185 [00:51<07:25,  2.40it/s]


 10%|▉         | 118/1185 [00:51<06:29,  2.74it/s]


 10%|█         | 119/1185 [00:51<06:23,  2.78it/s]


 10%|█         | 120/1185 [00:52<07:49,  2.27it/s]


 10%|█         | 121/1185 [00:53<08:21,  2.12it/s]


 10%|█         | 122/1185 [00:53<08:33,  2.07it/s]


 10%|█         | 123/1185 [00:53<07:19,  2.41it/s]


 10%|█         | 124/1185 [00:54<07:47,  2.27it/s]


 11%|█         | 125/1185 [00:54<07:56,  2.22it/s]


 11%|█         | 126/1185 [00:54<06:22,  2.77it/s]


 11%|█         | 127/1185 [00:55<06:32,  2.69it/s]


 11%|█         | 128/1185 [00:55<06:56,  2.54it/s]


 11%|█         | 129/1185 [00:56<07:15,  2.43it/s]


 11%|█         | 130/1185 [00:56<08:36,  2.04it/s]


 11%|█         | 131/1185 [00:57<07:11,  2.44it/s]


 11%|█         | 132/1185 [00:57<07:26,  2.36it/s]


 11%|█         | 133/1185 [00:58<08:11,  2.14it/s]


 11%|█▏        | 134/1185 [00:58<06:43,  2.60it/s]


 11%|█▏        | 135/1185 [00:58<06:54,  2.53it/s]


 11%|█▏        | 136/1185 [00:59<06:41,  2.61it/s]


 12%|█▏        | 137/1185 [00:59<07:33,  2.31it/s]


 12%|█▏        | 138/1185 [01:00<08:09,  2.14it/s]


 12%|█▏        | 139/1185 [01:00<07:15,  2.40it/s]


 12%|█▏        | 140/1185 [01:01<08:30,  2.05it/s]


 12%|█▏        | 141/1185 [01:01<08:06,  2.14it/s]


 12%|█▏        | 142/1185 [01:02<08:16,  2.10it/s]


 12%|█▏        | 143/1185 [01:02<07:17,  2.38it/s]


 12%|█▏        | 144/1185 [01:02<06:37,  2.62it/s]


 12%|█▏        | 145/1185 [01:03<06:40,  2.59it/s]


 12%|█▏        | 146/1185 [01:03<09:15,  1.87it/s]


 12%|█▏        | 147/1185 [01:04<07:30,  2.30it/s]


 12%|█▏        | 148/1185 [01:04<08:38,  2.00it/s]

 13%|█▎        | 149/1185 [01:04<06:59,  2.47it/s]


 13%|█▎        | 150/1185 [01:05<07:14,  2.38it/s]


 13%|█▎        | 151/1185 [01:06<08:18,  2.07it/s]


 13%|█▎        | 153/1185 [01:06<05:46,  2.98it/s]


 13%|█▎        | 154/1185 [01:07<07:59,  2.15it/s]


 13%|█▎        | 155/1185 [01:07<08:04,  2.12it/s]


 13%|█▎        | 156/1185 [01:08<08:06,  2.12it/s]


 13%|█▎        | 157/1185 [01:08<07:23,  2.32it/s]


 13%|█▎        | 158/1185 [01:08<06:52,  2.49it/s]


 13%|█▎        | 159/1185 [01:09<07:50,  2.18it/s]


 14%|█▎        | 161/1185 [01:09<05:26,  3.14it/s]


 14%|█▎        | 162/1185 [01:10<07:24,  2.30it/s]


 14%|█▍        | 163/1185 [01:11<07:25,  2.30it/s]


 14%|█▍        | 164/1185 [01:11<07:51,  2.17it/s]


 14%|█▍        | 165/1185 [01:11<06:53,  2.47it/s]


 14%|█▍        | 166/1185 [01:12<07:15,  2.34it/s]


 14%|█▍        | 167/1185 [01:12<07:25,  2.29it/s]


 14%|█▍        | 169/1185 [01:13<05:11,  3.26it/s]


 14%|█▍        | 170/1185 [01:13<06:58,  2.42it/s]


 14%|█▍        | 171/1185 [01:14<07:35,  2.23it/s]


 15%|█▍        | 172/1185 [01:14<07:52,  2.15it/s]


 15%|█▍        | 173/1185 [01:15<06:40,  2.53it/s]


 15%|█▍        | 174/1185 [01:15<08:20,  2.02it/s]


 15%|█▍        | 175/1185 [01:16<07:02,  2.39it/s]


 15%|█▍        | 176/1185 [01:16<05:49,  2.89it/s]


 15%|█▌        | 178/1185 [01:17<07:36,  2.21it/s]


 15%|█▌        | 179/1185 [01:17<06:37,  2.53it/s]


 15%|█▌        | 180/1185 [01:18<06:55,  2.42it/s]


 15%|█▌        | 181/1185 [01:18<06:50,  2.44it/s]


 15%|█▌        | 182/1185 [01:19<08:04,  2.07it/s]


 15%|█▌        | 183/1185 [01:19<09:21,  1.78it/s]


 16%|█▌        | 185/1185 [01:20<06:00,  2.78it/s]


 16%|█▌        | 186/1185 [01:20<06:35,  2.53it/s]


 16%|█▌        | 187/1185 [01:20<05:55,  2.80it/s]


 16%|█▌        | 188/1185 [01:21<06:45,  2.46it/s]


 16%|█▌        | 189/1185 [01:22<07:55,  2.09it/s]


 16%|█▌        | 190/1185 [01:22<09:13,  1.80it/s]


 16%|█▌        | 191/1185 [01:23<07:42,  2.15it/s]


 16%|█▌        | 192/1185 [01:23<07:09,  2.31it/s]


 16%|█▋        | 193/1185 [01:23<06:14,  2.65it/s]


 16%|█▋        | 194/1185 [01:24<06:43,  2.45it/s]


 16%|█▋        | 195/1185 [01:24<05:59,  2.76it/s]


 17%|█▋        | 196/1185 [01:24<06:05,  2.71it/s]


 17%|█▋        | 197/1185 [01:25<08:13,  2.00it/s]


 17%|█▋        | 198/1185 [01:26<10:12,  1.61it/s]


 17%|█▋        | 199/1185 [01:26<07:45,  2.12it/s]


 17%|█▋        | 200/1185 [01:26<07:19,  2.24it/s]


 17%|█▋        | 201/1185 [01:27<06:19,  2.59it/s]


 17%|█▋        | 202/1185 [01:27<05:52,  2.79it/s]


 17%|█▋        | 203/1185 [01:27<05:17,  3.09it/s]


 17%|█▋        | 204/1185 [01:28<05:27,  2.99it/s]


 17%|█▋        | 205/1185 [01:28<07:15,  2.25it/s]


 17%|█▋        | 206/1185 [01:29<10:07,  1.61it/s]


 18%|█▊        | 208/1185 [01:30<07:06,  2.29it/s]


 18%|█▊        | 209/1185 [01:30<06:35,  2.47it/s]


 18%|█▊        | 210/1185 [01:30<06:01,  2.70it/s]


 18%|█▊        | 211/1185 [01:31<05:43,  2.84it/s]


 18%|█▊        | 212/1185 [01:31<06:56,  2.34it/s]


 18%|█▊        | 213/1185 [01:32<08:11,  1.98it/s]


 18%|█▊        | 214/1185 [01:33<08:51,  1.83it/s]


 18%|█▊        | 215/1185 [01:33<09:23,  1.72it/s]


 18%|█▊        | 216/1185 [01:33<07:17,  2.22it/s]


 18%|█▊        | 217/1185 [01:34<06:55,  2.33it/s]


 18%|█▊        | 219/1185 [01:34<04:36,  3.49it/s]


 19%|█▊        | 220/1185 [01:35<07:00,  2.29it/s]


 19%|█▊        | 221/1185 [01:36<08:13,  1.95it/s]


 19%|█▊        | 222/1185 [01:36<08:06,  1.98it/s]


 19%|█▉        | 223/1185 [01:37<08:29,  1.89it/s]


 19%|█▉        | 225/1185 [01:37<05:59,  2.67it/s]


 19%|█▉        | 226/1185 [01:37<05:47,  2.76it/s]


 19%|█▉        | 227/1185 [01:38<05:27,  2.92it/s]


 19%|█▉        | 228/1185 [01:38<07:10,  2.22it/s]


 19%|█▉        | 229/1185 [01:39<09:13,  1.73it/s]


 19%|█▉        | 230/1185 [01:40<07:28,  2.13it/s]


 19%|█▉        | 231/1185 [01:40<07:39,  2.08it/s]


 20%|█▉        | 232/1185 [01:40<06:43,  2.36it/s]


 20%|█▉        | 233/1185 [01:41<05:19,  2.98it/s]


 20%|█▉        | 234/1185 [01:41<06:38,  2.39it/s]


 20%|█▉        | 235/1185 [01:41<05:33,  2.85it/s]


 20%|█▉        | 236/1185 [01:42<06:30,  2.43it/s]


 20%|██        | 237/1185 [01:43<09:01,  1.75it/s]


 20%|██        | 239/1185 [01:44<07:28,  2.11it/s]


 20%|██        | 240/1185 [01:44<06:23,  2.47it/s]


 20%|██        | 241/1185 [01:44<05:20,  2.94it/s]


 20%|██        | 242/1185 [01:45<06:42,  2.34it/s]


 21%|██        | 244/1185 [01:45<06:13,  2.52it/s]


 21%|██        | 245/1185 [01:46<07:52,  1.99it/s]


 21%|██        | 246/1185 [01:46<06:21,  2.46it/s]


 21%|██        | 247/1185 [01:47<07:19,  2.13it/s]


 21%|██        | 248/1185 [01:47<06:35,  2.37it/s]


 21%|██        | 250/1185 [01:48<06:08,  2.54it/s]


 21%|██        | 251/1185 [01:48<05:35,  2.78it/s]


 21%|██▏       | 252/1185 [01:49<06:53,  2.26it/s]


 21%|██▏       | 253/1185 [01:49<07:30,  2.07it/s]


 21%|██▏       | 254/1185 [01:50<06:14,  2.48it/s]


 22%|██▏       | 255/1185 [01:51<08:47,  1.76it/s]


 22%|██▏       | 257/1185 [01:51<06:43,  2.30it/s]


 22%|██▏       | 258/1185 [01:52<06:33,  2.36it/s]


 22%|██▏       | 259/1185 [01:52<06:04,  2.54it/s]


 22%|██▏       | 260/1185 [01:52<06:19,  2.44it/s]


 22%|██▏       | 261/1185 [01:53<08:19,  1.85it/s]


 22%|██▏       | 262/1185 [01:53<07:01,  2.19it/s]


 22%|██▏       | 263/1185 [01:54<08:30,  1.81it/s]


 22%|██▏       | 264/1185 [01:54<06:33,  2.34it/s]


 22%|██▏       | 265/1185 [01:55<07:11,  2.13it/s]


 22%|██▏       | 266/1185 [01:55<05:44,  2.67it/s]


 23%|██▎       | 267/1185 [01:55<05:04,  3.02it/s]


 23%|██▎       | 268/1185 [01:56<06:32,  2.34it/s]


 23%|██▎       | 269/1185 [01:57<08:01,  1.90it/s]


 23%|██▎       | 271/1185 [01:58<07:34,  2.01it/s]


 23%|██▎       | 273/1185 [01:58<06:30,  2.34it/s]


 23%|██▎       | 274/1185 [01:58<05:27,  2.78it/s]


 23%|██▎       | 275/1185 [01:59<05:32,  2.74it/s]


 23%|██▎       | 276/1185 [01:59<06:29,  2.33it/s]


 23%|██▎       | 277/1185 [02:00<07:09,  2.12it/s]


 24%|██▎       | 279/1185 [02:01<07:27,  2.03it/s]


 24%|██▎       | 281/1185 [02:02<06:00,  2.51it/s]


 24%|██▍       | 282/1185 [02:02<05:31,  2.73it/s]


 24%|██▍       | 283/1185 [02:02<05:47,  2.60it/s]


 24%|██▍       | 284/1185 [02:03<07:13,  2.08it/s]


 24%|██▍       | 285/1185 [02:03<06:38,  2.26it/s]


 24%|██▍       | 286/1185 [02:04<06:18,  2.37it/s]


 24%|██▍       | 287/1185 [02:04<07:33,  1.98it/s]


 24%|██▍       | 289/1185 [02:05<06:17,  2.37it/s]


 24%|██▍       | 290/1185 [02:06<07:04,  2.11it/s]


 25%|██▍       | 291/1185 [02:06<06:32,  2.28it/s]


 25%|██▍       | 292/1185 [02:07<07:02,  2.12it/s]


 25%|██▍       | 293/1185 [02:07<08:25,  1.76it/s]


 25%|██▍       | 294/1185 [02:08<06:43,  2.21it/s]


 25%|██▍       | 295/1185 [02:08<05:54,  2.51it/s]


 25%|██▍       | 296/1185 [02:08<04:57,  2.98it/s]


 25%|██▌       | 297/1185 [02:09<07:30,  1.97it/s]

 25%|██▌       | 298/1185 [02:09<06:15,  2.36it/s]


 25%|██▌       | 299/1185 [02:09<05:51,  2.52it/s]


 25%|██▌       | 300/1185 [02:10<07:13,  2.04it/s]


 25%|██▌       | 301/1185 [02:11<07:46,  1.89it/s]


 25%|██▌       | 302/1185 [02:11<06:50,  2.15it/s]


 26%|██▌       | 303/1185 [02:11<05:31,  2.66it/s]


 26%|██▌       | 304/1185 [02:12<05:40,  2.58it/s]


 26%|██▌       | 305/1185 [02:12<07:16,  2.02it/s]


 26%|██▌       | 306/1185 [02:13<05:32,  2.65it/s]


 26%|██▌       | 307/1185 [02:13<05:22,  2.72it/s]


 26%|██▌       | 308/1185 [02:14<06:48,  2.15it/s]


 26%|██▌       | 309/1185 [02:14<07:35,  1.92it/s]


 26%|██▌       | 310/1185 [02:15<06:38,  2.20it/s]


 26%|██▌       | 311/1185 [02:15<05:05,  2.86it/s]


 26%|██▋       | 312/1185 [02:15<05:22,  2.71it/s]


 26%|██▋       | 313/1185 [02:16<06:38,  2.19it/s]


 26%|██▋       | 314/1185 [02:16<05:41,  2.55it/s]


 27%|██▋       | 315/1185 [02:16<05:03,  2.87it/s]


 27%|██▋       | 316/1185 [02:17<06:26,  2.25it/s]


 27%|██▋       | 317/1185 [02:17<07:09,  2.02it/s]


 27%|██▋       | 318/1185 [02:18<06:41,  2.16it/s]


 27%|██▋       | 319/1185 [02:18<05:15,  2.74it/s]


 27%|██▋       | 320/1185 [02:19<05:54,  2.44it/s]


 27%|██▋       | 321/1185 [02:19<06:11,  2.33it/s]


 27%|██▋       | 322/1185 [02:19<06:02,  2.38it/s]


 27%|██▋       | 323/1185 [02:20<05:05,  2.83it/s]


 27%|██▋       | 324/1185 [02:20<06:04,  2.36it/s]


 27%|██▋       | 325/1185 [02:21<09:43,  1.47it/s]


 28%|██▊       | 327/1185 [02:22<05:59,  2.39it/s]


 28%|██▊       | 328/1185 [02:22<05:02,  2.84it/s]


 28%|██▊       | 329/1185 [02:22<05:25,  2.63it/s]


 28%|██▊       | 330/1185 [02:23<07:39,  1.86it/s]


 28%|██▊       | 331/1185 [02:23<06:16,  2.27it/s]


 28%|██▊       | 332/1185 [02:24<04:54,  2.90it/s]


 28%|██▊       | 333/1185 [02:25<08:41,  1.63it/s]


 28%|██▊       | 334/1185 [02:25<06:49,  2.08it/s]


 28%|██▊       | 335/1185 [02:25<05:21,  2.65it/s]


 28%|██▊       | 337/1185 [02:26<04:39,  3.03it/s]


 29%|██▊       | 338/1185 [02:27<07:54,  1.79it/s]


 29%|██▊       | 339/1185 [02:27<06:13,  2.27it/s]


 29%|██▊       | 340/1185 [02:27<05:40,  2.48it/s]


 29%|██▉       | 341/1185 [02:28<07:35,  1.85it/s]


 29%|██▉       | 342/1185 [02:28<06:23,  2.20it/s]


 29%|██▉       | 343/1185 [02:29<05:11,  2.70it/s]


 29%|██▉       | 344/1185 [02:29<04:59,  2.81it/s]


 29%|██▉       | 345/1185 [02:29<05:29,  2.55it/s]


 29%|██▉       | 346/1185 [02:30<08:05,  1.73it/s]


 29%|██▉       | 348/1185 [02:31<05:24,  2.58it/s]


 29%|██▉       | 349/1185 [02:32<06:34,  2.12it/s]


 30%|██▉       | 350/1185 [02:32<06:47,  2.05it/s]


 30%|██▉       | 351/1185 [02:32<05:26,  2.55it/s]


 30%|██▉       | 352/1185 [02:32<04:56,  2.81it/s]


 30%|██▉       | 353/1185 [02:33<05:23,  2.57it/s]


 30%|██▉       | 354/1185 [02:34<07:35,  1.83it/s]


 30%|██▉       | 355/1185 [02:34<05:54,  2.34it/s]


 30%|███       | 356/1185 [02:34<05:03,  2.73it/s]


 30%|███       | 357/1185 [02:35<06:06,  2.26it/s]


 30%|███       | 358/1185 [02:35<06:10,  2.23it/s]


 30%|███       | 359/1185 [02:36<05:58,  2.30it/s]


 30%|███       | 360/1185 [02:36<04:50,  2.84it/s]


 30%|███       | 361/1185 [02:36<04:48,  2.85it/s]


 31%|███       | 362/1185 [02:37<07:53,  1.74it/s]


 31%|███       | 363/1185 [02:37<06:18,  2.17it/s]


 31%|███       | 364/1185 [02:38<07:01,  1.95it/s]


 31%|███       | 366/1185 [02:39<05:56,  2.30it/s]


 31%|███       | 367/1185 [02:39<05:56,  2.30it/s]


 31%|███       | 368/1185 [02:39<04:54,  2.77it/s]


 31%|███       | 369/1185 [02:40<06:03,  2.24it/s]


 31%|███       | 370/1185 [02:41<06:44,  2.02it/s]


 31%|███▏      | 371/1185 [02:41<07:26,  1.82it/s]


 31%|███▏      | 372/1185 [02:42<06:19,  2.14it/s]


 31%|███▏      | 373/1185 [02:42<05:15,  2.58it/s]


 32%|███▏      | 374/1185 [02:42<04:40,  2.89it/s]


 32%|███▏      | 375/1185 [02:43<05:08,  2.62it/s]


 32%|███▏      | 376/1185 [02:43<06:12,  2.17it/s]


 32%|███▏      | 377/1185 [02:44<05:54,  2.28it/s]


 32%|███▏      | 378/1185 [02:44<07:16,  1.85it/s]


 32%|███▏      | 379/1185 [02:45<07:01,  1.91it/s]


 32%|███▏      | 380/1185 [02:45<06:06,  2.20it/s]


 32%|███▏      | 382/1185 [02:46<04:33,  2.93it/s]


 32%|███▏      | 383/1185 [02:46<04:51,  2.76it/s]


 32%|███▏      | 384/1185 [02:47<05:21,  2.49it/s]


 32%|███▏      | 385/1185 [02:47<05:29,  2.43it/s]


 33%|███▎      | 386/1185 [02:48<07:00,  1.90it/s]


 33%|███▎      | 387/1185 [02:48<06:39,  2.00it/s]


 33%|███▎      | 388/1185 [02:49<05:56,  2.23it/s]


 33%|███▎      | 390/1185 [02:49<04:24,  3.00it/s]


 33%|███▎      | 391/1185 [02:49<04:32,  2.91it/s]


 33%|███▎      | 392/1185 [02:50<05:11,  2.54it/s]


 33%|███▎      | 393/1185 [02:50<06:02,  2.19it/s]


 33%|███▎      | 394/1185 [02:51<06:43,  1.96it/s]


 33%|███▎      | 395/1185 [02:51<06:12,  2.12it/s]


 33%|███▎      | 396/1185 [02:52<06:06,  2.15it/s]


 34%|███▎      | 397/1185 [02:52<05:08,  2.56it/s]


 34%|███▎      | 398/1185 [02:52<04:14,  3.09it/s]


 34%|███▎      | 399/1185 [02:53<04:59,  2.62it/s]


 34%|███▍      | 400/1185 [02:54<07:20,  1.78it/s]


 34%|███▍      | 402/1185 [02:55<07:03,  1.85it/s]


 34%|███▍      | 403/1185 [02:55<06:04,  2.14it/s]


 34%|███▍      | 404/1185 [02:55<05:33,  2.34it/s]


 34%|███▍      | 405/1185 [02:56<04:31,  2.88it/s]


 34%|███▍      | 406/1185 [02:56<06:04,  2.13it/s]


 34%|███▍      | 408/1185 [02:57<06:46,  1.91it/s]


 35%|███▍      | 410/1185 [02:58<05:56,  2.18it/s]


 35%|███▍      | 411/1185 [02:59<05:32,  2.33it/s]


 35%|███▍      | 412/1185 [02:59<05:00,  2.57it/s]


 35%|███▍      | 413/1185 [02:59<04:41,  2.74it/s]


 35%|███▍      | 414/1185 [03:00<05:45,  2.23it/s]


 35%|███▌      | 415/1185 [03:00<04:50,  2.65it/s]


 35%|███▌      | 416/1185 [03:01<07:10,  1.78it/s]


 35%|███▌      | 418/1185 [03:02<06:12,  2.06it/s]


 35%|███▌      | 419/1185 [03:02<05:36,  2.28it/s]


 35%|███▌      | 420/1185 [03:02<04:39,  2.74it/s]


 36%|███▌      | 421/1185 [03:02<03:59,  3.19it/s]


 36%|███▌      | 422/1185 [03:03<05:41,  2.24it/s]


 36%|███▌      | 423/1185 [03:03<04:29,  2.83it/s]


 36%|███▌      | 424/1185 [03:04<06:57,  1.82it/s]


 36%|███▌      | 426/1185 [03:05<06:09,  2.05it/s]


 36%|███▌      | 427/1185 [03:06<05:47,  2.18it/s]


 36%|███▌      | 428/1185 [03:06<04:44,  2.67it/s]


 36%|███▋      | 430/1185 [03:07<05:07,  2.46it/s]


 36%|███▋      | 432/1185 [03:08<05:56,  2.11it/s]


 37%|███▋      | 433/1185 [03:08<05:04,  2.47it/s]


 37%|███▋      | 434/1185 [03:09<05:55,  2.11it/s]


 37%|███▋      | 435/1185 [03:09<05:23,  2.31it/s]


 37%|███▋      | 436/1185 [03:09<05:15,  2.37it/s]


 37%|███▋      | 437/1185 [03:10<04:46,  2.61it/s]


 37%|███▋      | 438/1185 [03:10<04:28,  2.79it/s]


 37%|███▋      | 439/1185 [03:10<03:38,  3.41it/s]


 37%|███▋      | 440/1185 [03:11<06:41,  1.85it/s]


 37%|███▋      | 441/1185 [03:11<05:33,  2.23it/s]


 37%|███▋      | 442/1185 [03:12<07:32,  1.64it/s]

 37%|███▋      | 443/1185 [03:13<06:24,  1.93it/s]


 37%|███▋      | 444/1185 [03:13<04:56,  2.50it/s]


 38%|███▊      | 445/1185 [03:13<05:03,  2.44it/s]


 38%|███▊      | 446/1185 [03:13<04:35,  2.69it/s]


 38%|███▊      | 448/1185 [03:14<05:05,  2.41it/s]


 38%|███▊      | 449/1185 [03:15<06:13,  1.97it/s]


 38%|███▊      | 450/1185 [03:16<06:12,  1.98it/s]


 38%|███▊      | 451/1185 [03:16<05:15,  2.33it/s]


 38%|███▊      | 452/1185 [03:16<05:34,  2.19it/s]


 38%|███▊      | 453/1185 [03:17<04:24,  2.77it/s]


 38%|███▊      | 454/1185 [03:17<04:29,  2.71it/s]


 38%|███▊      | 456/1185 [03:18<05:02,  2.41it/s]


 39%|███▊      | 457/1185 [03:19<05:59,  2.03it/s]


 39%|███▊      | 458/1185 [03:19<05:38,  2.15it/s]


 39%|███▊      | 459/1185 [03:19<04:41,  2.57it/s]


 39%|███▉      | 460/1185 [03:20<05:29,  2.20it/s]


 39%|███▉      | 462/1185 [03:20<04:27,  2.70it/s]


 39%|███▉      | 464/1185 [03:21<04:51,  2.48it/s]


 39%|███▉      | 465/1185 [03:22<05:31,  2.17it/s]


 39%|███▉      | 466/1185 [03:22<05:42,  2.10it/s]


 39%|███▉      | 468/1185 [03:23<05:02,  2.37it/s]


 40%|███▉      | 469/1185 [03:23<04:13,  2.83it/s]


 40%|███▉      | 470/1185 [03:24<04:33,  2.61it/s]


 40%|███▉      | 471/1185 [03:24<03:54,  3.04it/s]


 40%|███▉      | 472/1185 [03:25<06:20,  1.87it/s]


 40%|███▉      | 473/1185 [03:25<05:23,  2.20it/s]


 40%|████      | 474/1185 [03:26<05:43,  2.07it/s]


 40%|████      | 476/1185 [03:27<05:20,  2.21it/s]


 40%|████      | 477/1185 [03:27<04:57,  2.38it/s]


 40%|████      | 478/1185 [03:27<04:42,  2.50it/s]


 40%|████      | 479/1185 [03:28<04:16,  2.76it/s]


 41%|████      | 480/1185 [03:29<06:40,  1.76it/s]


 41%|████      | 481/1185 [03:29<06:08,  1.91it/s]


 41%|████      | 483/1185 [03:30<04:57,  2.36it/s]


 41%|████      | 484/1185 [03:30<05:14,  2.23it/s]


 41%|████      | 485/1185 [03:30<04:23,  2.66it/s]


 41%|████      | 486/1185 [03:31<05:27,  2.13it/s]


 41%|████      | 487/1185 [03:31<04:48,  2.42it/s]


 41%|████      | 488/1185 [03:32<05:32,  2.10it/s]


 41%|████▏     | 489/1185 [03:33<06:36,  1.76it/s]


 41%|████▏     | 490/1185 [03:33<05:08,  2.25it/s]


 41%|████▏     | 491/1185 [03:33<04:41,  2.46it/s]


 42%|████▏     | 492/1185 [03:34<05:03,  2.28it/s]


 42%|████▏     | 493/1185 [03:34<03:53,  2.96it/s]


 42%|████▏     | 494/1185 [03:35<05:02,  2.28it/s]


 42%|████▏     | 495/1185 [03:35<04:18,  2.66it/s]


 42%|████▏     | 496/1185 [03:35<05:06,  2.24it/s]


 42%|████▏     | 497/1185 [03:36<06:04,  1.89it/s]


 42%|████▏     | 498/1185 [03:36<05:03,  2.27it/s]


 42%|████▏     | 499/1185 [03:37<04:52,  2.35it/s]


 42%|████▏     | 500/1185 [03:37<05:07,  2.23it/s]


 42%|████▏     | 502/1185 [03:38<04:32,  2.51it/s]


 42%|████▏     | 503/1185 [03:38<04:32,  2.50it/s]


 43%|████▎     | 504/1185 [03:39<05:20,  2.12it/s]


 43%|████▎     | 505/1185 [03:40<05:48,  1.95it/s]


 43%|████▎     | 507/1185 [03:40<04:25,  2.55it/s]


 43%|████▎     | 508/1185 [03:41<04:51,  2.32it/s]


 43%|████▎     | 510/1185 [03:41<04:40,  2.41it/s]


 43%|████▎     | 511/1185 [03:42<04:43,  2.37it/s]


 43%|████▎     | 512/1185 [03:43<05:21,  2.09it/s]


 43%|████▎     | 513/1185 [03:43<06:07,  1.83it/s]


 43%|████▎     | 514/1185 [03:43<04:53,  2.29it/s]


 43%|████▎     | 515/1185 [03:44<04:26,  2.52it/s]


 44%|████▎     | 516/1185 [03:44<04:23,  2.54it/s]


 44%|████▎     | 517/1185 [03:45<05:00,  2.23it/s]


 44%|████▎     | 518/1185 [03:45<04:20,  2.56it/s]


 44%|████▍     | 519/1185 [03:46<05:20,  2.08it/s]


 44%|████▍     | 520/1185 [03:46<04:57,  2.23it/s]


 44%|████▍     | 521/1185 [03:47<05:28,  2.02it/s]


 44%|████▍     | 522/1185 [03:47<05:26,  2.03it/s]


 44%|████▍     | 523/1185 [03:47<04:41,  2.35it/s]


 44%|████▍     | 524/1185 [03:48<04:24,  2.50it/s]


 44%|████▍     | 525/1185 [03:48<04:37,  2.37it/s]


 44%|████▍     | 526/1185 [03:48<04:00,  2.73it/s]


 44%|████▍     | 527/1185 [03:49<05:26,  2.02it/s]


 45%|████▍     | 528/1185 [03:50<05:03,  2.17it/s]


 45%|████▍     | 529/1185 [03:50<04:31,  2.42it/s]


 45%|████▍     | 530/1185 [03:50<05:00,  2.18it/s]


 45%|████▍     | 531/1185 [03:51<04:46,  2.29it/s]


 45%|████▍     | 532/1185 [03:51<04:30,  2.41it/s]


 45%|████▍     | 533/1185 [03:52<04:15,  2.56it/s]


 45%|████▌     | 534/1185 [03:52<03:42,  2.93it/s]


 45%|████▌     | 535/1185 [03:53<05:41,  1.90it/s]


 45%|████▌     | 536/1185 [03:53<04:36,  2.35it/s]


 45%|████▌     | 537/1185 [03:53<04:12,  2.57it/s]


 45%|████▌     | 538/1185 [03:54<04:49,  2.23it/s]


 45%|████▌     | 539/1185 [03:54<05:03,  2.13it/s]


 46%|████▌     | 540/1185 [03:55<04:24,  2.44it/s]


 46%|████▌     | 541/1185 [03:55<04:42,  2.28it/s]


 46%|████▌     | 543/1185 [03:56<05:02,  2.12it/s]


 46%|████▌     | 544/1185 [03:56<04:42,  2.27it/s]


 46%|████▌     | 546/1185 [03:57<05:00,  2.13it/s]


 46%|████▌     | 548/1185 [03:58<04:06,  2.58it/s]


 46%|████▋     | 549/1185 [03:58<04:15,  2.49it/s]


 46%|████▋     | 550/1185 [03:59<03:50,  2.75it/s]


 46%|████▋     | 551/1185 [04:00<05:16,  2.01it/s]


 47%|████▋     | 552/1185 [04:00<04:51,  2.17it/s]


 47%|████▋     | 553/1185 [04:00<04:38,  2.27it/s]


 47%|████▋     | 554/1185 [04:01<05:14,  2.01it/s]


 47%|████▋     | 556/1185 [04:02<04:40,  2.25it/s]


 47%|████▋     | 557/1185 [04:02<04:28,  2.34it/s]


 47%|████▋     | 558/1185 [04:02<03:38,  2.87it/s]


 47%|████▋     | 559/1185 [04:03<04:49,  2.16it/s]


 47%|████▋     | 560/1185 [04:03<04:46,  2.18it/s]


 47%|████▋     | 561/1185 [04:04<04:32,  2.29it/s]


 47%|████▋     | 562/1185 [04:04<05:12,  2.00it/s]


 48%|████▊     | 564/1185 [04:05<05:16,  1.96it/s]


 48%|████▊     | 565/1185 [04:06<04:34,  2.26it/s]


 48%|████▊     | 567/1185 [04:07<04:31,  2.28it/s]


 48%|████▊     | 568/1185 [04:07<04:24,  2.33it/s]


 48%|████▊     | 569/1185 [04:07<04:06,  2.49it/s]


 48%|████▊     | 570/1185 [04:08<04:24,  2.32it/s]


 48%|████▊     | 572/1185 [04:09<04:52,  2.09it/s]


 48%|████▊     | 573/1185 [04:09<04:34,  2.23it/s]


 49%|████▊     | 575/1185 [04:10<04:21,  2.33it/s]


 49%|████▊     | 576/1185 [04:10<03:58,  2.55it/s]


 49%|████▊     | 577/1185 [04:11<04:40,  2.17it/s]


 49%|████▉     | 578/1185 [04:11<04:13,  2.39it/s]


 49%|████▉     | 580/1185 [04:12<04:32,  2.22it/s]


 49%|████▉     | 581/1185 [04:13<04:40,  2.15it/s]


 49%|████▉     | 582/1185 [04:13<04:03,  2.47it/s]


 49%|████▉     | 583/1185 [04:14<04:46,  2.10it/s]


 49%|████▉     | 584/1185 [04:14<04:41,  2.14it/s]


 49%|████▉     | 585/1185 [04:14<04:19,  2.31it/s]


 49%|████▉     | 586/1185 [04:15<04:03,  2.46it/s]


 50%|████▉     | 587/1185 [04:15<04:14,  2.35it/s]


 50%|████▉     | 588/1185 [04:16<05:42,  1.74it/s]


 50%|████▉     | 589/1185 [04:16<04:47,  2.08it/s]


 50%|████▉     | 591/1185 [04:17<04:07,  2.40it/s]


 50%|████▉     | 592/1185 [04:18<04:42,  2.10it/s]


 50%|█████     | 594/1185 [04:18<04:01,  2.44it/s]


 50%|█████     | 595/1185 [04:19<04:25,  2.22it/s]

 50%|█████     | 596/1185 [04:20<05:13,  1.88it/s]


 50%|█████     | 597/1185 [04:20<04:15,  2.30it/s]


 51%|█████     | 599/1185 [04:21<03:48,  2.56it/s]


 51%|█████     | 600/1185 [04:21<04:21,  2.24it/s]


 51%|█████     | 602/1185 [04:22<03:47,  2.56it/s]


 51%|█████     | 603/1185 [04:22<03:55,  2.48it/s]


 51%|█████     | 604/1185 [04:23<04:52,  1.98it/s]


 51%|█████     | 605/1185 [04:23<04:08,  2.33it/s]


 51%|█████     | 606/1185 [04:24<03:35,  2.68it/s]


 51%|█████     | 607/1185 [04:24<04:01,  2.40it/s]


 51%|█████▏    | 608/1185 [04:25<04:11,  2.30it/s]


 51%|█████▏    | 610/1185 [04:25<03:46,  2.54it/s]


 52%|█████▏    | 611/1185 [04:26<04:01,  2.37it/s]


 52%|█████▏    | 612/1185 [04:27<04:45,  2.01it/s]


 52%|█████▏    | 613/1185 [04:27<04:13,  2.26it/s]


 52%|█████▏    | 614/1185 [04:27<03:42,  2.56it/s]


 52%|█████▏    | 615/1185 [04:28<04:22,  2.17it/s]


 52%|█████▏    | 616/1185 [04:28<03:39,  2.59it/s]


 52%|█████▏    | 617/1185 [04:28<03:10,  2.98it/s]


 52%|█████▏    | 618/1185 [04:29<04:07,  2.29it/s]


 52%|█████▏    | 619/1185 [04:29<04:32,  2.08it/s]


 52%|█████▏    | 620/1185 [04:30<05:27,  1.72it/s]


 52%|█████▏    | 622/1185 [04:31<03:50,  2.44it/s]


 53%|█████▎    | 623/1185 [04:31<04:41,  2.00it/s]


 53%|█████▎    | 624/1185 [04:32<04:38,  2.01it/s]


 53%|█████▎    | 626/1185 [04:33<04:03,  2.29it/s]


 53%|█████▎    | 627/1185 [04:33<03:48,  2.44it/s]


 53%|█████▎    | 628/1185 [04:34<04:57,  1.87it/s]


 53%|█████▎    | 629/1185 [04:34<04:33,  2.03it/s]


 53%|█████▎    | 630/1185 [04:34<03:41,  2.50it/s]


 53%|█████▎    | 631/1185 [04:35<04:02,  2.28it/s]


 53%|█████▎    | 632/1185 [04:35<03:53,  2.37it/s]


 54%|█████▎    | 634/1185 [04:36<03:50,  2.40it/s]


 54%|█████▎    | 635/1185 [04:37<03:49,  2.39it/s]


 54%|█████▎    | 636/1185 [04:37<04:55,  1.86it/s]


 54%|█████▍    | 637/1185 [04:38<04:41,  1.95it/s]


 54%|█████▍    | 639/1185 [04:38<03:25,  2.65it/s]


 54%|█████▍    | 640/1185 [04:39<03:34,  2.54it/s]


 54%|█████▍    | 641/1185 [04:39<03:08,  2.88it/s]


 54%|█████▍    | 642/1185 [04:40<03:58,  2.27it/s]


 54%|█████▍    | 643/1185 [04:40<03:54,  2.31it/s]


 54%|█████▍    | 644/1185 [04:41<04:43,  1.91it/s]


 54%|█████▍    | 645/1185 [04:41<04:35,  1.96it/s]


 55%|█████▍    | 646/1185 [04:41<03:34,  2.51it/s]


 55%|█████▍    | 647/1185 [04:42<03:00,  2.99it/s]


 55%|█████▍    | 648/1185 [04:42<03:34,  2.51it/s]


 55%|█████▍    | 649/1185 [04:42<03:16,  2.73it/s]


 55%|█████▍    | 650/1185 [04:43<04:24,  2.02it/s]


 55%|█████▍    | 651/1185 [04:43<03:38,  2.44it/s]


 55%|█████▌    | 652/1185 [04:44<04:27,  1.99it/s]


 55%|█████▌    | 653/1185 [04:45<05:02,  1.76it/s]


 55%|█████▌    | 655/1185 [04:45<02:54,  3.03it/s]


 55%|█████▌    | 656/1185 [04:45<03:22,  2.61it/s]


 55%|█████▌    | 657/1185 [04:46<03:54,  2.25it/s]


 56%|█████▌    | 658/1185 [04:47<04:49,  1.82it/s]


 56%|█████▌    | 659/1185 [04:47<03:51,  2.27it/s]


 56%|█████▌    | 660/1185 [04:48<03:58,  2.20it/s]


 56%|█████▌    | 661/1185 [04:48<04:57,  1.76it/s]


 56%|█████▌    | 663/1185 [04:49<03:17,  2.65it/s]


 56%|█████▌    | 664/1185 [04:49<03:04,  2.82it/s]


 56%|█████▌    | 665/1185 [04:50<03:31,  2.46it/s]


 56%|█████▌    | 666/1185 [04:51<04:55,  1.75it/s]


 56%|█████▋    | 668/1185 [04:51<04:06,  2.10it/s]


 56%|█████▋    | 669/1185 [04:52<04:30,  1.91it/s]


 57%|█████▋    | 671/1185 [04:52<03:29,  2.46it/s]


 57%|█████▋    | 672/1185 [04:53<03:10,  2.69it/s]


 57%|█████▋    | 673/1185 [04:53<03:25,  2.49it/s]


 57%|█████▋    | 674/1185 [04:54<04:23,  1.94it/s]


 57%|█████▋    | 675/1185 [04:54<03:28,  2.45it/s]


 57%|█████▋    | 676/1185 [04:55<03:56,  2.15it/s]


 57%|█████▋    | 677/1185 [04:55<04:29,  1.88it/s]


 57%|█████▋    | 679/1185 [04:56<03:15,  2.59it/s]


 57%|█████▋    | 680/1185 [04:56<02:50,  2.97it/s]


 57%|█████▋    | 681/1185 [04:57<03:19,  2.53it/s]


 58%|█████▊    | 682/1185 [04:57<04:17,  1.95it/s]


 58%|█████▊    | 684/1185 [04:58<03:52,  2.16it/s]


 58%|█████▊    | 685/1185 [04:59<04:04,  2.04it/s]


 58%|█████▊    | 686/1185 [04:59<03:50,  2.17it/s]


 58%|█████▊    | 687/1185 [04:59<03:20,  2.48it/s]


 58%|█████▊    | 689/1185 [05:00<03:22,  2.45it/s]


 58%|█████▊    | 690/1185 [05:01<03:38,  2.27it/s]


 58%|█████▊    | 692/1185 [05:02<03:51,  2.13it/s]


 58%|█████▊    | 693/1185 [05:02<03:26,  2.39it/s]


 59%|█████▊    | 694/1185 [05:03<04:02,  2.03it/s]


 59%|█████▊    | 696/1185 [05:03<03:20,  2.44it/s]


 59%|█████▉    | 697/1185 [05:04<03:38,  2.24it/s]


 59%|█████▉    | 698/1185 [05:05<04:08,  1.96it/s]


 59%|█████▉    | 700/1185 [05:05<03:14,  2.50it/s]


 59%|█████▉    | 701/1185 [05:06<03:18,  2.43it/s]


 59%|█████▉    | 702/1185 [05:06<03:38,  2.22it/s]


 59%|█████▉    | 703/1185 [05:06<02:57,  2.71it/s]


 59%|█████▉    | 704/1185 [05:07<03:47,  2.11it/s]


 59%|█████▉    | 705/1185 [05:08<03:51,  2.07it/s]


 60%|█████▉    | 706/1185 [05:08<04:00,  1.99it/s]


 60%|█████▉    | 707/1185 [05:08<03:04,  2.59it/s]


 60%|█████▉    | 708/1185 [05:09<03:29,  2.28it/s]


 60%|█████▉    | 709/1185 [05:09<02:50,  2.80it/s]


 60%|█████▉    | 710/1185 [05:10<03:55,  2.02it/s]


 60%|██████    | 712/1185 [05:10<03:18,  2.38it/s]


 60%|██████    | 713/1185 [05:11<03:25,  2.29it/s]


 60%|██████    | 714/1185 [05:11<03:30,  2.24it/s]


 60%|██████    | 715/1185 [05:12<02:51,  2.73it/s]


 60%|██████    | 716/1185 [05:12<03:26,  2.28it/s]


 61%|██████    | 717/1185 [05:12<02:41,  2.90it/s]


 61%|██████    | 718/1185 [05:13<03:49,  2.03it/s]


 61%|██████    | 720/1185 [05:14<03:12,  2.41it/s]


 61%|██████    | 721/1185 [05:14<03:26,  2.24it/s]


 61%|██████    | 722/1185 [05:15<03:42,  2.09it/s]


 61%|██████    | 723/1185 [05:15<03:11,  2.41it/s]


 61%|██████    | 724/1185 [05:16<03:08,  2.44it/s]


 61%|██████    | 725/1185 [05:16<02:43,  2.82it/s]


 61%|██████▏   | 726/1185 [05:16<03:28,  2.21it/s]


 61%|██████▏   | 727/1185 [05:17<02:41,  2.83it/s]


 61%|██████▏   | 728/1185 [05:18<04:05,  1.86it/s]


 62%|██████▏   | 729/1185 [05:18<03:40,  2.07it/s]


 62%|██████▏   | 730/1185 [05:19<04:21,  1.74it/s]


 62%|██████▏   | 731/1185 [05:19<03:30,  2.16it/s]


 62%|██████▏   | 733/1185 [05:19<02:58,  2.54it/s]


 62%|██████▏   | 734/1185 [05:20<03:12,  2.34it/s]


 62%|██████▏   | 735/1185 [05:20<03:16,  2.29it/s]


 62%|██████▏   | 736/1185 [05:21<03:07,  2.39it/s]


 62%|██████▏   | 737/1185 [05:21<03:15,  2.29it/s]


 62%|██████▏   | 738/1185 [05:22<03:58,  1.87it/s]


 62%|██████▏   | 739/1185 [05:22<03:23,  2.20it/s]


 62%|██████▏   | 740/1185 [05:23<02:52,  2.58it/s]


 63%|██████▎   | 741/1185 [05:23<03:10,  2.33it/s]


 63%|██████▎   | 742/1185 [05:23<02:41,  2.74it/s]


 63%|██████▎   | 743/1185 [05:24<03:22,  2.18it/s]


 63%|██████▎   | 744/1185 [05:25<03:25,  2.15it/s]


 63%|██████▎   | 745/1185 [05:25<02:59,  2.45it/s]


 63%|██████▎   | 746/1185 [05:26<04:11,  1.75it/s]


 63%|██████▎   | 748/1185 [05:26<02:55,  2.49it/s]

 63%|██████▎   | 749/1185 [05:27<03:01,  2.41it/s]


 63%|██████▎   | 750/1185 [05:27<02:25,  2.99it/s]


 63%|██████▎   | 751/1185 [05:27<03:09,  2.29it/s]


 63%|██████▎   | 752/1185 [05:28<03:06,  2.32it/s]


 64%|██████▎   | 753/1185 [05:28<03:00,  2.39it/s]


 64%|██████▎   | 754/1185 [05:29<04:10,  1.72it/s]


 64%|██████▍   | 756/1185 [05:29<02:44,  2.61it/s]


 64%|██████▍   | 757/1185 [05:30<02:50,  2.52it/s]


 64%|██████▍   | 758/1185 [05:30<02:33,  2.77it/s]


 64%|██████▍   | 759/1185 [05:31<03:06,  2.29it/s]


 64%|██████▍   | 760/1185 [05:31<02:59,  2.36it/s]


 64%|██████▍   | 761/1185 [05:32<03:45,  1.88it/s]


 64%|██████▍   | 762/1185 [05:33<03:48,  1.85it/s]


 64%|██████▍   | 763/1185 [05:33<03:17,  2.14it/s]


 64%|██████▍   | 764/1185 [05:33<03:11,  2.20it/s]


 65%|██████▍   | 765/1185 [05:33<02:27,  2.85it/s]


 65%|██████▍   | 766/1185 [05:34<02:45,  2.54it/s]


 65%|██████▍   | 767/1185 [05:35<03:41,  1.89it/s]


 65%|██████▍   | 769/1185 [05:35<03:01,  2.29it/s]


 65%|██████▍   | 770/1185 [05:36<03:10,  2.18it/s]


 65%|██████▌   | 771/1185 [05:37<03:29,  1.98it/s]


 65%|██████▌   | 772/1185 [05:37<03:23,  2.03it/s]


 65%|██████▌   | 774/1185 [05:37<02:14,  3.05it/s]


 65%|██████▌   | 775/1185 [05:38<03:15,  2.10it/s]


 65%|██████▌   | 776/1185 [05:38<02:35,  2.62it/s]


 66%|██████▌   | 777/1185 [05:39<03:28,  1.96it/s]


 66%|██████▌   | 778/1185 [05:40<03:33,  1.91it/s]


 66%|██████▌   | 779/1185 [05:40<02:57,  2.29it/s]


 66%|██████▌   | 780/1185 [05:40<02:59,  2.26it/s]


 66%|██████▌   | 781/1185 [05:41<02:39,  2.53it/s]


 66%|██████▌   | 783/1185 [05:42<02:52,  2.33it/s]


 66%|██████▌   | 784/1185 [05:42<02:28,  2.69it/s]


 66%|██████▌   | 785/1185 [05:43<03:26,  1.94it/s]


 66%|██████▋   | 786/1185 [05:43<03:06,  2.14it/s]


 66%|██████▋   | 787/1185 [05:43<02:50,  2.34it/s]


 66%|██████▋   | 788/1185 [05:44<03:00,  2.20it/s]


 67%|██████▋   | 790/1185 [05:44<01:48,  3.64it/s]


 67%|██████▋   | 791/1185 [05:45<03:10,  2.07it/s]


 67%|██████▋   | 793/1185 [05:46<03:10,  2.06it/s]


 67%|██████▋   | 794/1185 [05:46<02:55,  2.23it/s]


 67%|██████▋   | 795/1185 [05:47<02:44,  2.37it/s]


 67%|██████▋   | 796/1185 [05:47<02:49,  2.29it/s]


 67%|██████▋   | 798/1185 [05:47<01:53,  3.40it/s]


 67%|██████▋   | 799/1185 [05:49<03:17,  1.95it/s]


 68%|██████▊   | 800/1185 [05:49<02:54,  2.21it/s]


 68%|██████▊   | 801/1185 [05:50<03:20,  1.92it/s]


 68%|██████▊   | 803/1185 [05:50<02:26,  2.61it/s]


 68%|██████▊   | 804/1185 [05:51<03:14,  1.96it/s]


 68%|██████▊   | 806/1185 [05:51<02:20,  2.69it/s]


 68%|██████▊   | 807/1185 [05:52<02:45,  2.29it/s]


 68%|██████▊   | 808/1185 [05:53<03:25,  1.84it/s]


 68%|██████▊   | 809/1185 [05:53<02:57,  2.12it/s]


 68%|██████▊   | 811/1185 [05:54<02:31,  2.47it/s]


 69%|██████▊   | 812/1185 [05:54<02:41,  2.31it/s]


 69%|██████▊   | 813/1185 [05:55<02:18,  2.69it/s]


 69%|██████▊   | 814/1185 [05:55<02:26,  2.54it/s]


 69%|██████▉   | 815/1185 [05:56<02:40,  2.31it/s]


 69%|██████▉   | 816/1185 [05:56<03:25,  1.79it/s]


 69%|██████▉   | 817/1185 [05:57<03:14,  1.89it/s]


 69%|██████▉   | 819/1185 [05:57<02:17,  2.66it/s]


 69%|██████▉   | 820/1185 [05:58<02:22,  2.56it/s]


 69%|██████▉   | 821/1185 [05:58<02:12,  2.75it/s]


 69%|██████▉   | 822/1185 [05:58<02:25,  2.49it/s]


 69%|██████▉   | 823/1185 [05:59<02:44,  2.20it/s]


 70%|██████▉   | 824/1185 [06:00<03:12,  1.87it/s]


 70%|██████▉   | 825/1185 [06:00<03:08,  1.91it/s]


 70%|██████▉   | 827/1185 [06:01<02:04,  2.88it/s]


 70%|██████▉   | 828/1185 [06:01<02:18,  2.57it/s]


 70%|██████▉   | 829/1185 [06:01<02:04,  2.86it/s]


 70%|███████   | 830/1185 [06:02<02:16,  2.60it/s]


 70%|███████   | 831/1185 [06:02<02:35,  2.28it/s]


 70%|███████   | 832/1185 [06:03<03:20,  1.76it/s]


 70%|███████   | 833/1185 [06:04<03:09,  1.86it/s]


 70%|███████   | 834/1185 [06:04<02:39,  2.20it/s]


 70%|███████   | 835/1185 [06:04<02:27,  2.37it/s]


 71%|███████   | 836/1185 [06:05<02:14,  2.60it/s]


 71%|███████   | 837/1185 [06:05<02:03,  2.82it/s]


 71%|███████   | 838/1185 [06:05<01:54,  3.02it/s]


 71%|███████   | 839/1185 [06:06<02:56,  1.96it/s]


 71%|███████   | 840/1185 [06:07<03:23,  1.69it/s]


 71%|███████   | 841/1185 [06:07<02:51,  2.01it/s]


 71%|███████   | 842/1185 [06:08<03:01,  1.89it/s]


 71%|███████   | 843/1185 [06:08<02:56,  1.94it/s]


 71%|███████   | 844/1185 [06:09<02:29,  2.29it/s]


 71%|███████▏  | 847/1185 [06:10<02:31,  2.23it/s]


 72%|███████▏  | 848/1185 [06:10<02:29,  2.25it/s]


 72%|███████▏  | 849/1185 [06:11<02:33,  2.19it/s]


 72%|███████▏  | 850/1185 [06:11<02:25,  2.30it/s]


 72%|███████▏  | 851/1185 [06:12<02:43,  2.04it/s]


 72%|███████▏  | 853/1185 [06:12<01:45,  3.15it/s]


 72%|███████▏  | 854/1185 [06:12<01:35,  3.47it/s]


 72%|███████▏  | 855/1185 [06:13<02:48,  1.96it/s]


 72%|███████▏  | 856/1185 [06:14<02:46,  1.98it/s]


 72%|███████▏  | 857/1185 [06:14<02:38,  2.07it/s]


 72%|███████▏  | 858/1185 [06:15<02:22,  2.30it/s]


 72%|███████▏  | 859/1185 [06:15<02:36,  2.09it/s]


 73%|███████▎  | 861/1185 [06:15<01:39,  3.26it/s]


 73%|███████▎  | 862/1185 [06:16<01:33,  3.46it/s]


 73%|███████▎  | 863/1185 [06:17<02:38,  2.03it/s]


 73%|███████▎  | 864/1185 [06:17<02:48,  1.91it/s]


 73%|███████▎  | 865/1185 [06:18<02:37,  2.04it/s]


 73%|███████▎  | 866/1185 [06:18<02:16,  2.34it/s]


 73%|███████▎  | 867/1185 [06:19<02:27,  2.16it/s]


 73%|███████▎  | 869/1185 [06:19<01:46,  2.96it/s]


 73%|███████▎  | 870/1185 [06:19<01:30,  3.47it/s]


 74%|███████▎  | 871/1185 [06:20<02:47,  1.87it/s]


 74%|███████▎  | 872/1185 [06:21<02:44,  1.90it/s]


 74%|███████▎  | 873/1185 [06:21<02:31,  2.05it/s]


 74%|███████▍  | 874/1185 [06:21<02:08,  2.43it/s]


 74%|███████▍  | 875/1185 [06:22<02:33,  2.02it/s]


 74%|███████▍  | 876/1185 [06:22<02:08,  2.41it/s]


 74%|███████▍  | 877/1185 [06:23<02:08,  2.39it/s]


 74%|███████▍  | 878/1185 [06:23<01:54,  2.69it/s]


 74%|███████▍  | 879/1185 [06:24<02:13,  2.30it/s]


 74%|███████▍  | 880/1185 [06:24<02:54,  1.75it/s]


 74%|███████▍  | 882/1185 [06:25<01:51,  2.71it/s]


 75%|███████▍  | 883/1185 [06:26<02:44,  1.83it/s]


 75%|███████▍  | 884/1185 [06:26<02:12,  2.27it/s]


 75%|███████▍  | 885/1185 [06:26<02:05,  2.39it/s]


 75%|███████▍  | 886/1185 [06:26<01:47,  2.79it/s]


 75%|███████▍  | 887/1185 [06:27<02:17,  2.17it/s]


 75%|███████▍  | 888/1185 [06:28<02:26,  2.03it/s]


 75%|███████▌  | 889/1185 [06:28<01:53,  2.60it/s]


 75%|███████▌  | 890/1185 [06:28<01:53,  2.61it/s]


 75%|███████▌  | 891/1185 [06:29<02:39,  1.84it/s]


 75%|███████▌  | 892/1185 [06:30<02:20,  2.08it/s]


 75%|███████▌  | 893/1185 [06:30<02:03,  2.37it/s]


 75%|███████▌  | 894/1185 [06:30<01:34,  3.07it/s]


 76%|███████▌  | 895/1185 [06:31<02:00,  2.41it/s]


 76%|███████▌  | 896/1185 [06:31<02:31,  1.91it/s]


 76%|███████▌  | 897/1185 [06:32<02:10,  2.21it/s]


 76%|███████▌  | 898/1185 [06:32<01:57,  2.44it/s]

 76%|███████▌  | 899/1185 [06:33<02:14,  2.12it/s]


 76%|███████▌  | 900/1185 [06:33<02:21,  2.01it/s]


 76%|███████▌  | 902/1185 [06:33<01:33,  3.02it/s]


 76%|███████▌  | 903/1185 [06:34<01:56,  2.42it/s]


 76%|███████▋  | 904/1185 [06:35<02:12,  2.12it/s]


 76%|███████▋  | 905/1185 [06:35<02:13,  2.10it/s]


 77%|███████▋  | 907/1185 [06:36<01:57,  2.37it/s]


 77%|███████▋  | 908/1185 [06:37<02:16,  2.03it/s]


 77%|███████▋  | 910/1185 [06:37<01:28,  3.11it/s]


 77%|███████▋  | 911/1185 [06:38<02:08,  2.13it/s]


 77%|███████▋  | 912/1185 [06:38<02:08,  2.12it/s]


 77%|███████▋  | 913/1185 [06:39<02:04,  2.19it/s]


 77%|███████▋  | 914/1185 [06:39<02:10,  2.08it/s]


 77%|███████▋  | 915/1185 [06:40<02:29,  1.80it/s]


 77%|███████▋  | 917/1185 [06:40<01:47,  2.49it/s]


 77%|███████▋  | 918/1185 [06:41<01:34,  2.83it/s]


 78%|███████▊  | 919/1185 [06:41<01:47,  2.49it/s]


 78%|███████▊  | 920/1185 [06:42<01:58,  2.24it/s]


 78%|███████▊  | 921/1185 [06:42<02:15,  1.94it/s]


 78%|███████▊  | 922/1185 [06:43<02:02,  2.15it/s]


 78%|███████▊  | 923/1185 [06:43<02:28,  1.76it/s]


 78%|███████▊  | 924/1185 [06:44<01:57,  2.22it/s]


 78%|███████▊  | 925/1185 [06:44<01:30,  2.88it/s]


 78%|███████▊  | 926/1185 [06:44<01:21,  3.19it/s]


 78%|███████▊  | 927/1185 [06:45<01:54,  2.25it/s]


 78%|███████▊  | 928/1185 [06:45<02:01,  2.12it/s]


 78%|███████▊  | 929/1185 [06:46<02:04,  2.06it/s]


 78%|███████▊  | 930/1185 [06:46<01:58,  2.14it/s]


 79%|███████▊  | 931/1185 [06:47<02:11,  1.93it/s]


 79%|███████▊  | 932/1185 [06:47<01:46,  2.38it/s]


 79%|███████▊  | 933/1185 [06:47<01:24,  3.00it/s]


 79%|███████▉  | 934/1185 [06:47<01:07,  3.74it/s]


 79%|███████▉  | 935/1185 [06:48<01:47,  2.33it/s]


 79%|███████▉  | 936/1185 [06:49<01:58,  2.10it/s]


 79%|███████▉  | 937/1185 [06:49<01:58,  2.09it/s]


 79%|███████▉  | 938/1185 [06:50<02:04,  1.98it/s]


 79%|███████▉  | 939/1185 [06:50<02:15,  1.82it/s]


 79%|███████▉  | 941/1185 [06:51<01:25,  2.87it/s]


 79%|███████▉  | 942/1185 [06:51<01:09,  3.48it/s]


 80%|███████▉  | 943/1185 [06:51<01:38,  2.45it/s]


 80%|███████▉  | 944/1185 [06:52<02:03,  1.95it/s]


 80%|███████▉  | 945/1185 [06:53<01:46,  2.25it/s]


 80%|███████▉  | 946/1185 [06:54<02:24,  1.66it/s]


 80%|███████▉  | 947/1185 [06:54<01:59,  1.99it/s]


 80%|████████  | 948/1185 [06:54<01:31,  2.58it/s]


 80%|████████  | 949/1185 [06:54<01:25,  2.75it/s]


 80%|████████  | 950/1185 [06:55<01:26,  2.71it/s]


 80%|████████  | 951/1185 [06:55<01:40,  2.32it/s]


 80%|████████  | 952/1185 [06:56<02:02,  1.90it/s]


 80%|████████  | 953/1185 [06:56<01:51,  2.08it/s]


 81%|████████  | 954/1185 [06:57<02:11,  1.76it/s]


 81%|████████  | 955/1185 [06:57<01:42,  2.23it/s]


 81%|████████  | 956/1185 [06:58<01:41,  2.25it/s]


 81%|████████  | 957/1185 [06:58<01:23,  2.71it/s]


 81%|████████  | 958/1185 [06:58<01:20,  2.82it/s]


 81%|████████  | 959/1185 [06:59<01:20,  2.82it/s]


 81%|████████  | 960/1185 [06:59<01:46,  2.12it/s]


 81%|████████  | 961/1185 [07:00<02:12,  1.69it/s]


 81%|████████  | 962/1185 [07:01<01:59,  1.86it/s]


 81%|████████▏ | 963/1185 [07:01<01:41,  2.20it/s]


 81%|████████▏ | 964/1185 [07:01<01:30,  2.44it/s]


 82%|████████▏ | 966/1185 [07:02<01:21,  2.68it/s]


 82%|████████▏ | 967/1185 [07:02<01:13,  2.98it/s]


 82%|████████▏ | 968/1185 [07:03<01:40,  2.15it/s]


 82%|████████▏ | 969/1185 [07:04<01:55,  1.88it/s]


 82%|████████▏ | 970/1185 [07:04<01:47,  1.99it/s]


 82%|████████▏ | 971/1185 [07:04<01:28,  2.41it/s]


 82%|████████▏ | 972/1185 [07:04<01:18,  2.70it/s]


 82%|████████▏ | 974/1185 [07:05<01:16,  2.74it/s]


 82%|████████▏ | 975/1185 [07:05<01:12,  2.92it/s]


 82%|████████▏ | 976/1185 [07:06<01:40,  2.09it/s]


 82%|████████▏ | 977/1185 [07:07<01:46,  1.95it/s]


 83%|████████▎ | 978/1185 [07:07<01:44,  1.98it/s]


 83%|████████▎ | 979/1185 [07:08<01:50,  1.87it/s]


 83%|████████▎ | 980/1185 [07:08<01:34,  2.16it/s]


 83%|████████▎ | 981/1185 [07:08<01:13,  2.77it/s]


 83%|████████▎ | 982/1185 [07:09<01:01,  3.30it/s]


 83%|████████▎ | 983/1185 [07:09<01:18,  2.58it/s]


 83%|████████▎ | 984/1185 [07:10<01:25,  2.35it/s]


 83%|████████▎ | 985/1185 [07:11<02:07,  1.57it/s]


 83%|████████▎ | 987/1185 [07:11<01:35,  2.08it/s]


 83%|████████▎ | 988/1185 [07:12<01:25,  2.31it/s]


 83%|████████▎ | 989/1185 [07:12<01:12,  2.72it/s]


 84%|████████▎ | 990/1185 [07:12<01:17,  2.53it/s]


 84%|████████▎ | 991/1185 [07:13<01:15,  2.57it/s]


 84%|████████▎ | 992/1185 [07:13<01:24,  2.27it/s]


 84%|████████▍ | 993/1185 [07:14<01:54,  1.68it/s]


 84%|████████▍ | 994/1185 [07:14<01:34,  2.02it/s]


 84%|████████▍ | 995/1185 [07:15<01:42,  1.86it/s]


 84%|████████▍ | 997/1185 [07:15<01:09,  2.70it/s]


 84%|████████▍ | 998/1185 [07:16<01:10,  2.64it/s]


 84%|████████▍ | 999/1185 [07:16<01:02,  2.96it/s]


 84%|████████▍ | 1000/1185 [07:17<01:20,  2.29it/s]


 84%|████████▍ | 1001/1185 [07:18<01:47,  1.72it/s]


 85%|████████▍ | 1003/1185 [07:19<01:31,  1.98it/s]


 85%|████████▍ | 1005/1185 [07:19<01:05,  2.76it/s]


 85%|████████▍ | 1006/1185 [07:19<01:03,  2.83it/s]


 85%|████████▍ | 1007/1185 [07:19<01:00,  2.93it/s]


 85%|████████▌ | 1008/1185 [07:20<01:16,  2.32it/s]


 85%|████████▌ | 1009/1185 [07:21<01:42,  1.73it/s]


 85%|████████▌ | 1011/1185 [07:22<01:27,  1.99it/s]


 85%|████████▌ | 1013/1185 [07:22<01:00,  2.85it/s]


 86%|████████▌ | 1014/1185 [07:23<01:04,  2.63it/s]


 86%|████████▌ | 1015/1185 [07:23<00:55,  3.07it/s]


 86%|████████▌ | 1016/1185 [07:24<01:12,  2.34it/s]


 86%|████████▌ | 1017/1185 [07:25<01:40,  1.67it/s]


 86%|████████▌ | 1019/1185 [07:25<01:21,  2.05it/s]


 86%|████████▌ | 1020/1185 [07:26<01:18,  2.09it/s]


 86%|████████▌ | 1021/1185 [07:26<01:07,  2.44it/s]


 86%|████████▌ | 1022/1185 [07:26<00:59,  2.73it/s]


 86%|████████▋ | 1024/1185 [07:27<01:16,  2.11it/s]


 86%|████████▋ | 1025/1185 [07:28<01:25,  1.88it/s]


 87%|████████▋ | 1026/1185 [07:28<01:10,  2.25it/s]


 87%|████████▋ | 1027/1185 [07:29<01:04,  2.45it/s]


 87%|████████▋ | 1028/1185 [07:29<01:06,  2.38it/s]


 87%|████████▋ | 1029/1185 [07:30<01:07,  2.31it/s]


 87%|████████▋ | 1030/1185 [07:30<00:57,  2.70it/s]


 87%|████████▋ | 1031/1185 [07:30<00:57,  2.67it/s]


 87%|████████▋ | 1032/1185 [07:31<01:22,  1.86it/s]


 87%|████████▋ | 1033/1185 [07:32<01:41,  1.49it/s]


 87%|████████▋ | 1035/1185 [07:32<01:00,  2.46it/s]


 87%|████████▋ | 1036/1185 [07:33<00:54,  2.73it/s]


 88%|████████▊ | 1037/1185 [07:33<00:59,  2.48it/s]


 88%|████████▊ | 1038/1185 [07:33<00:57,  2.57it/s]


 88%|████████▊ | 1039/1185 [07:34<00:53,  2.72it/s]


 88%|████████▊ | 1040/1185 [07:35<01:15,  1.91it/s]


 88%|████████▊ | 1041/1185 [07:35<01:26,  1.66it/s]


 88%|████████▊ | 1042/1185 [07:36<01:06,  2.15it/s]


 88%|████████▊ | 1043/1185 [07:36<00:57,  2.48it/s]


 88%|████████▊ | 1045/1185 [07:36<00:48,  2.89it/s]


 88%|████████▊ | 1046/1185 [07:37<00:50,  2.76it/s]

 88%|████████▊ | 1047/1185 [07:37<00:48,  2.84it/s]


 88%|████████▊ | 1048/1185 [07:38<01:11,  1.92it/s]


 89%|████████▊ | 1049/1185 [07:39<01:16,  1.77it/s]


 89%|████████▊ | 1050/1185 [07:39<01:07,  2.01it/s]


 89%|████████▉ | 1052/1185 [07:39<00:45,  2.95it/s]


 89%|████████▉ | 1053/1185 [07:40<00:44,  2.99it/s]


 89%|████████▉ | 1054/1185 [07:40<00:47,  2.75it/s]


 89%|████████▉ | 1055/1185 [07:41<00:52,  2.48it/s]


 89%|████████▉ | 1056/1185 [07:42<01:23,  1.55it/s]


 89%|████████▉ | 1057/1185 [07:42<01:04,  1.99it/s]


 89%|████████▉ | 1058/1185 [07:42<00:55,  2.29it/s]


 89%|████████▉ | 1059/1185 [07:43<00:52,  2.42it/s]


 89%|████████▉ | 1060/1185 [07:43<00:49,  2.52it/s]


 90%|████████▉ | 1061/1185 [07:43<00:40,  3.03it/s]


 90%|████████▉ | 1062/1185 [07:44<00:51,  2.37it/s]


 90%|████████▉ | 1063/1185 [07:45<01:01,  1.98it/s]


 90%|████████▉ | 1064/1185 [07:45<01:14,  1.63it/s]


 90%|████████▉ | 1065/1185 [07:46<00:58,  2.06it/s]


 90%|████████▉ | 1066/1185 [07:46<00:57,  2.09it/s]


 90%|█████████ | 1068/1185 [07:47<00:47,  2.46it/s]


 90%|█████████ | 1070/1185 [07:47<00:43,  2.64it/s]


 90%|█████████ | 1071/1185 [07:48<00:45,  2.48it/s]


 90%|█████████ | 1072/1185 [07:49<01:08,  1.65it/s]


 91%|█████████ | 1074/1185 [07:49<00:45,  2.44it/s]


 91%|█████████ | 1076/1185 [07:50<00:44,  2.44it/s]


 91%|█████████ | 1078/1185 [07:51<00:39,  2.69it/s]


 91%|█████████ | 1079/1185 [07:51<00:40,  2.63it/s]


 91%|█████████ | 1080/1185 [07:53<01:01,  1.70it/s]


 91%|█████████▏| 1082/1185 [07:53<00:40,  2.52it/s]


 91%|█████████▏| 1083/1185 [07:53<00:34,  2.96it/s]


 91%|█████████▏| 1084/1185 [07:54<00:43,  2.35it/s]


 92%|█████████▏| 1086/1185 [07:54<00:38,  2.55it/s]


 92%|█████████▏| 1087/1185 [07:55<00:36,  2.65it/s]


 92%|█████████▏| 1088/1185 [07:56<00:58,  1.66it/s]


 92%|█████████▏| 1090/1185 [07:56<00:35,  2.65it/s]


 92%|█████████▏| 1091/1185 [07:57<00:39,  2.39it/s]


 92%|█████████▏| 1092/1185 [07:57<00:43,  2.13it/s]


 92%|█████████▏| 1093/1185 [07:57<00:34,  2.65it/s]


 92%|█████████▏| 1094/1185 [07:58<00:39,  2.28it/s]


 92%|█████████▏| 1095/1185 [07:58<00:31,  2.83it/s]


 92%|█████████▏| 1096/1185 [07:59<00:51,  1.72it/s]


 93%|█████████▎| 1097/1185 [08:00<00:48,  1.81it/s]


 93%|█████████▎| 1098/1185 [08:00<00:40,  2.17it/s]


 93%|█████████▎| 1099/1185 [08:00<00:30,  2.82it/s]


 93%|█████████▎| 1100/1185 [08:01<00:37,  2.27it/s]


 93%|█████████▎| 1101/1185 [08:01<00:40,  2.07it/s]


 93%|█████████▎| 1102/1185 [08:01<00:35,  2.36it/s]


 93%|█████████▎| 1104/1185 [08:03<00:40,  2.02it/s]


 93%|█████████▎| 1105/1185 [08:03<00:45,  1.74it/s]


 93%|█████████▎| 1107/1185 [08:04<00:28,  2.78it/s]


 94%|█████████▎| 1108/1185 [08:04<00:28,  2.67it/s]


 94%|█████████▎| 1109/1185 [08:05<00:34,  2.22it/s]


 94%|█████████▎| 1110/1185 [08:05<00:28,  2.65it/s]


 94%|█████████▍| 1111/1185 [08:05<00:24,  3.03it/s]


 94%|█████████▍| 1112/1185 [08:06<00:40,  1.80it/s]


 94%|█████████▍| 1113/1185 [08:07<00:42,  1.70it/s]


 94%|█████████▍| 1115/1185 [08:07<00:24,  2.81it/s]


 94%|█████████▍| 1116/1185 [08:07<00:23,  2.89it/s]


 94%|█████████▍| 1117/1185 [08:08<00:30,  2.21it/s]


 94%|█████████▍| 1118/1185 [08:08<00:25,  2.65it/s]


 94%|█████████▍| 1119/1185 [08:08<00:21,  3.04it/s]


 95%|█████████▍| 1120/1185 [08:10<00:36,  1.78it/s]


 95%|█████████▍| 1121/1185 [08:10<00:36,  1.77it/s]


 95%|█████████▍| 1122/1185 [08:10<00:27,  2.29it/s]


 95%|█████████▍| 1123/1185 [08:10<00:21,  2.88it/s]


 95%|█████████▍| 1124/1185 [08:11<00:22,  2.74it/s]


 95%|█████████▍| 1125/1185 [08:11<00:26,  2.29it/s]


 95%|█████████▌| 1126/1185 [08:12<00:24,  2.39it/s]


 95%|█████████▌| 1128/1185 [08:13<00:27,  2.04it/s]


 95%|█████████▌| 1129/1185 [08:13<00:26,  2.08it/s]


 95%|█████████▌| 1130/1185 [08:14<00:25,  2.13it/s]


 95%|█████████▌| 1131/1185 [08:14<00:23,  2.31it/s]


 96%|█████████▌| 1132/1185 [08:14<00:20,  2.60it/s]


 96%|█████████▌| 1133/1185 [08:15<00:23,  2.17it/s]


 96%|█████████▌| 1134/1185 [08:15<00:19,  2.65it/s]


 96%|█████████▌| 1135/1185 [08:16<00:17,  2.86it/s]


 96%|█████████▌| 1136/1185 [08:17<00:30,  1.62it/s]


 96%|█████████▌| 1137/1185 [08:17<00:26,  1.79it/s]


 96%|█████████▌| 1139/1185 [08:18<00:17,  2.62it/s]


 96%|█████████▌| 1140/1185 [08:18<00:15,  2.94it/s]


 96%|█████████▋| 1141/1185 [08:18<00:18,  2.39it/s]


 96%|█████████▋| 1142/1185 [08:19<00:20,  2.07it/s]


 97%|█████████▋| 1144/1185 [08:20<00:21,  1.95it/s]


 97%|█████████▋| 1145/1185 [08:21<00:19,  2.00it/s]


 97%|█████████▋| 1146/1185 [08:21<00:17,  2.22it/s]


 97%|█████████▋| 1147/1185 [08:21<00:14,  2.62it/s]


 97%|█████████▋| 1148/1185 [08:21<00:13,  2.80it/s]


 97%|█████████▋| 1149/1185 [08:22<00:13,  2.63it/s]


 97%|█████████▋| 1150/1185 [08:23<00:16,  2.08it/s]


 97%|█████████▋| 1151/1185 [08:23<00:13,  2.59it/s]


 97%|█████████▋| 1152/1185 [08:24<00:17,  1.89it/s]


 97%|█████████▋| 1153/1185 [08:24<00:16,  1.95it/s]


 97%|█████████▋| 1154/1185 [08:24<00:12,  2.45it/s]


 97%|█████████▋| 1155/1185 [08:25<00:12,  2.42it/s]


 98%|█████████▊| 1157/1185 [08:25<00:09,  2.83it/s]


 98%|█████████▊| 1158/1185 [08:26<00:12,  2.14it/s]


 98%|█████████▊| 1159/1185 [08:26<00:10,  2.57it/s]


 98%|█████████▊| 1160/1185 [08:27<00:12,  2.01it/s]


 98%|█████████▊| 1161/1185 [08:27<00:11,  2.14it/s]


 98%|█████████▊| 1162/1185 [08:28<00:09,  2.39it/s]


 98%|█████████▊| 1163/1185 [08:28<00:09,  2.35it/s]


 98%|█████████▊| 1164/1185 [08:28<00:07,  2.73it/s]


 98%|█████████▊| 1165/1185 [08:29<00:09,  2.10it/s]


 98%|█████████▊| 1166/1185 [08:30<00:09,  1.99it/s]


 98%|█████████▊| 1167/1185 [08:30<00:06,  2.57it/s]


 99%|█████████▊| 1168/1185 [08:31<00:08,  2.07it/s]


 99%|█████████▊| 1169/1185 [08:31<00:07,  2.04it/s]


 99%|█████████▊| 1170/1185 [08:32<00:09,  1.63it/s]


 99%|█████████▉| 1171/1185 [08:32<00:06,  2.05it/s]


 99%|█████████▉| 1172/1185 [08:33<00:06,  2.08it/s]


 99%|█████████▉| 1174/1185 [08:33<00:04,  2.63it/s]


 99%|█████████▉| 1176/1185 [08:34<00:03,  2.44it/s]


 99%|█████████▉| 1177/1185 [08:35<00:03,  2.27it/s]


 99%|█████████▉| 1178/1185 [08:35<00:03,  1.78it/s]


 99%|█████████▉| 1179/1185 [08:36<00:02,  2.10it/s]


100%|█████████▉| 1180/1185 [08:36<00:02,  2.09it/s]


100%|█████████▉| 1181/1185 [08:36<00:01,  2.61it/s]


100%|█████████▉| 1182/1185 [08:36<00:00,  3.30it/s]


100%|█████████▉| 1183/1185 [08:37<00:00,  3.65it/s]


100%|█████████▉| 1184/1185 [08:37<00:00,  3.68it/s]


100%|██████████| 1185/1185 [08:37<00:00,  2.29it/s]
Multiplets | family 4:   0%|          | 0/1185 [08:37<?, ?it/s]


Multiplets | family 5:   0%|          | 0/1559 [00:00<?, ?it/s]


  0%|          | 0/1559 [00:00<?, ?it/s]


  0%|          | 1/1559 [00:04<1:52:39,  4.34s/it]


  1%|          | 8/1559 [00:04<10:53,  2.37it/s]


  1%|          | 11/1559 [00:08<19:59,  1.29it/s]


  1%|          | 13/1559 [00:09<16:37,  1.55it/s]


  1%|          | 15/1559 [00:09<12:40,  2.03it/s]


  1%|          | 17/1559 [00:12<21:37,  1.19it/s]

  1%|          | 18/1559 [00:13<18:56,  1.36it/s]


  1%|▏         | 20/1559 [00:13<13:47,  1.86it/s]


  1%|▏         | 21/1559 [00:14<14:57,  1.71it/s]


  1%|▏         | 22/1559 [00:14<13:03,  1.96it/s]


  1%|▏         | 23/1559 [00:14<11:20,  2.26it/s]


  2%|▏         | 25/1559 [00:17<21:02,  1.22it/s]


  2%|▏         | 26/1559 [00:17<18:19,  1.39it/s]


  2%|▏         | 28/1559 [00:17<11:51,  2.15it/s]


  2%|▏         | 29/1559 [00:18<13:41,  1.86it/s]


  2%|▏         | 30/1559 [00:19<12:53,  1.98it/s]


  2%|▏         | 31/1559 [00:19<10:36,  2.40it/s]


  2%|▏         | 33/1559 [00:21<20:38,  1.23it/s]


  2%|▏         | 34/1559 [00:22<16:51,  1.51it/s]


  2%|▏         | 36/1559 [00:22<12:09,  2.09it/s]


  2%|▏         | 37/1559 [00:23<12:04,  2.10it/s]


  2%|▏         | 38/1559 [00:23<14:19,  1.77it/s]


  3%|▎         | 40/1559 [00:24<09:35,  2.64it/s]


  3%|▎         | 41/1559 [00:26<19:36,  1.29it/s]


  3%|▎         | 42/1559 [00:26<17:37,  1.43it/s]


  3%|▎         | 43/1559 [00:26<15:06,  1.67it/s]


  3%|▎         | 44/1559 [00:27<11:45,  2.15it/s]


  3%|▎         | 45/1559 [00:27<09:52,  2.56it/s]


  3%|▎         | 46/1559 [00:28<17:29,  1.44it/s]


  3%|▎         | 48/1559 [00:28<10:36,  2.37it/s]


  3%|▎         | 49/1559 [00:30<17:54,  1.41it/s]


  3%|▎         | 50/1559 [00:31<16:30,  1.52it/s]


  3%|▎         | 51/1559 [00:31<15:46,  1.59it/s]


  3%|▎         | 52/1559 [00:31<12:28,  2.01it/s]


  3%|▎         | 53/1559 [00:32<11:23,  2.20it/s]


  3%|▎         | 54/1559 [00:33<16:48,  1.49it/s]


  4%|▎         | 55/1559 [00:33<13:04,  1.92it/s]


  4%|▎         | 56/1559 [00:33<10:22,  2.41it/s]


  4%|▎         | 57/1559 [00:34<17:04,  1.47it/s]


  4%|▎         | 58/1559 [00:35<16:39,  1.50it/s]


  4%|▍         | 59/1559 [00:35<14:23,  1.74it/s]


  4%|▍         | 60/1559 [00:36<10:59,  2.27it/s]


  4%|▍         | 61/1559 [00:36<10:37,  2.35it/s]


  4%|▍         | 62/1559 [00:37<17:37,  1.42it/s]


  4%|▍         | 63/1559 [00:37<13:05,  1.91it/s]


  4%|▍         | 64/1559 [00:38<11:08,  2.24it/s]


  4%|▍         | 65/1559 [00:39<15:30,  1.61it/s]


  4%|▍         | 66/1559 [00:40<18:51,  1.32it/s]


  4%|▍         | 67/1559 [00:40<15:13,  1.63it/s]


  4%|▍         | 68/1559 [00:40<11:24,  2.18it/s]


  4%|▍         | 69/1559 [00:41<12:34,  1.97it/s]


  4%|▍         | 70/1559 [00:42<16:28,  1.51it/s]


  5%|▍         | 71/1559 [00:42<12:47,  1.94it/s]


  5%|▍         | 72/1559 [00:43<14:21,  1.73it/s]


  5%|▍         | 73/1559 [00:43<14:24,  1.72it/s]


  5%|▍         | 74/1559 [00:44<16:01,  1.54it/s]


  5%|▍         | 75/1559 [00:45<16:41,  1.48it/s]


  5%|▍         | 76/1559 [00:45<12:56,  1.91it/s]


  5%|▍         | 77/1559 [00:45<10:11,  2.42it/s]


  5%|▌         | 78/1559 [00:46<15:15,  1.62it/s]


  5%|▌         | 79/1559 [00:47<13:04,  1.89it/s]


  5%|▌         | 80/1559 [00:47<13:15,  1.86it/s]


  5%|▌         | 81/1559 [00:48<14:52,  1.66it/s]


  5%|▌         | 82/1559 [00:49<16:58,  1.45it/s]


  5%|▌         | 83/1559 [00:49<16:38,  1.48it/s]


  5%|▌         | 85/1559 [00:50<09:45,  2.52it/s]


  6%|▌         | 86/1559 [00:51<13:50,  1.77it/s]


  6%|▌         | 87/1559 [00:51<13:16,  1.85it/s]


  6%|▌         | 88/1559 [00:52<13:01,  1.88it/s]


  6%|▌         | 89/1559 [00:52<13:51,  1.77it/s]


  6%|▌         | 90/1559 [00:53<16:16,  1.50it/s]


  6%|▌         | 91/1559 [00:54<16:33,  1.48it/s]


  6%|▌         | 92/1559 [00:54<14:32,  1.68it/s]


  6%|▌         | 93/1559 [00:54<11:20,  2.16it/s]


  6%|▌         | 94/1559 [00:55<12:43,  1.92it/s]


  6%|▌         | 95/1559 [00:56<12:23,  1.97it/s]


  6%|▌         | 96/1559 [00:57<16:02,  1.52it/s]


  6%|▌         | 97/1559 [00:57<15:42,  1.55it/s]


  6%|▋         | 98/1559 [00:58<14:02,  1.73it/s]


  6%|▋         | 99/1559 [00:59<17:42,  1.37it/s]


  6%|▋         | 100/1559 [00:59<13:52,  1.75it/s]


  6%|▋         | 101/1559 [00:59<13:54,  1.75it/s]


  7%|▋         | 102/1559 [01:00<13:34,  1.79it/s]


  7%|▋         | 103/1559 [01:01<14:42,  1.65it/s]


  7%|▋         | 104/1559 [01:01<14:31,  1.67it/s]


  7%|▋         | 105/1559 [01:01<11:30,  2.11it/s]


  7%|▋         | 106/1559 [01:02<12:43,  1.90it/s]


  7%|▋         | 107/1559 [01:03<17:00,  1.42it/s]


  7%|▋         | 108/1559 [01:03<12:55,  1.87it/s]


  7%|▋         | 109/1559 [01:04<13:04,  1.85it/s]


  7%|▋         | 110/1559 [01:04<13:10,  1.83it/s]


  7%|▋         | 111/1559 [01:05<14:46,  1.63it/s]


  7%|▋         | 112/1559 [01:06<14:16,  1.69it/s]


  7%|▋         | 114/1559 [01:07<11:43,  2.05it/s]


  7%|▋         | 115/1559 [01:08<14:55,  1.61it/s]


  7%|▋         | 116/1559 [01:08<12:28,  1.93it/s]


  8%|▊         | 117/1559 [01:08<12:27,  1.93it/s]


  8%|▊         | 118/1559 [01:09<13:43,  1.75it/s]


  8%|▊         | 119/1559 [01:10<14:43,  1.63it/s]


  8%|▊         | 120/1559 [01:10<13:52,  1.73it/s]


  8%|▊         | 122/1559 [01:11<11:07,  2.15it/s]


  8%|▊         | 123/1559 [01:12<15:55,  1.50it/s]


  8%|▊         | 124/1559 [01:12<13:02,  1.83it/s]


  8%|▊         | 125/1559 [01:13<13:09,  1.82it/s]


  8%|▊         | 126/1559 [01:13<13:11,  1.81it/s]


  8%|▊         | 127/1559 [01:15<17:40,  1.35it/s]


  8%|▊         | 128/1559 [01:15<13:21,  1.78it/s]


  8%|▊         | 129/1559 [01:15<11:36,  2.05it/s]


  8%|▊         | 130/1559 [01:16<12:43,  1.87it/s]


  8%|▊         | 131/1559 [01:17<14:51,  1.60it/s]


  8%|▊         | 132/1559 [01:17<13:47,  1.72it/s]


  9%|▊         | 133/1559 [01:18<13:35,  1.75it/s]


  9%|▊         | 134/1559 [01:18<11:15,  2.11it/s]


  9%|▊         | 135/1559 [01:19<16:33,  1.43it/s]


  9%|▊         | 136/1559 [01:20<15:14,  1.56it/s]


  9%|▉         | 137/1559 [01:20<11:47,  2.01it/s]


  9%|▉         | 138/1559 [01:20<13:09,  1.80it/s]


  9%|▉         | 139/1559 [01:21<13:17,  1.78it/s]


  9%|▉         | 140/1559 [01:21<12:18,  1.92it/s]


  9%|▉         | 141/1559 [01:22<12:55,  1.83it/s]


  9%|▉         | 142/1559 [01:22<10:37,  2.22it/s]


  9%|▉         | 143/1559 [01:23<15:44,  1.50it/s]


  9%|▉         | 144/1559 [01:24<16:06,  1.46it/s]


  9%|▉         | 146/1559 [01:25<13:17,  1.77it/s]


  9%|▉         | 147/1559 [01:25<11:54,  1.98it/s]


  9%|▉         | 148/1559 [01:26<13:37,  1.73it/s]


 10%|▉         | 149/1559 [01:26<11:35,  2.03it/s]


 10%|▉         | 150/1559 [01:27<11:09,  2.11it/s]


 10%|▉         | 151/1559 [01:28<14:15,  1.65it/s]


 10%|▉         | 152/1559 [01:29<18:39,  1.26it/s]


 10%|▉         | 154/1559 [01:30<13:50,  1.69it/s]


 10%|▉         | 155/1559 [01:30<12:32,  1.87it/s]


 10%|█         | 156/1559 [01:31<17:04,  1.37it/s]


 10%|█         | 157/1559 [01:31<13:09,  1.78it/s]


 10%|█         | 158/1559 [01:32<10:24,  2.24it/s]


 10%|█         | 159/1559 [01:33<16:54,  1.38it/s]


 10%|█         | 160/1559 [01:34<15:50,  1.47it/s]


 10%|█         | 162/1559 [01:34<11:41,  1.99it/s]


 10%|█         | 163/1559 [01:35<12:22,  1.88it/s]

 11%|█         | 164/1559 [01:36<14:44,  1.58it/s]


 11%|█         | 165/1559 [01:36<13:14,  1.75it/s]


 11%|█         | 166/1559 [01:36<10:35,  2.19it/s]


 11%|█         | 167/1559 [01:38<16:32,  1.40it/s]


 11%|█         | 168/1559 [01:38<13:58,  1.66it/s]


 11%|█         | 169/1559 [01:38<10:50,  2.14it/s]


 11%|█         | 170/1559 [01:39<11:54,  1.94it/s]


 11%|█         | 171/1559 [01:39<12:06,  1.91it/s]


 11%|█         | 172/1559 [01:40<13:21,  1.73it/s]


 11%|█         | 173/1559 [01:41<13:29,  1.71it/s]


 11%|█         | 175/1559 [01:42<16:40,  1.38it/s]


 11%|█▏        | 177/1559 [01:43<10:55,  2.11it/s]


 11%|█▏        | 178/1559 [01:43<11:48,  1.95it/s]


 11%|█▏        | 179/1559 [01:44<11:30,  2.00it/s]


 12%|█▏        | 180/1559 [01:45<14:30,  1.58it/s]


 12%|█▏        | 181/1559 [01:45<13:32,  1.70it/s]


 12%|█▏        | 182/1559 [01:46<13:17,  1.73it/s]


 12%|█▏        | 183/1559 [01:47<17:23,  1.32it/s]


 12%|█▏        | 184/1559 [01:47<14:41,  1.56it/s]


 12%|█▏        | 185/1559 [01:48<12:42,  1.80it/s]


 12%|█▏        | 186/1559 [01:48<10:24,  2.20it/s]


 12%|█▏        | 187/1559 [01:48<10:31,  2.17it/s]


 12%|█▏        | 188/1559 [01:49<13:02,  1.75it/s]


 12%|█▏        | 189/1559 [01:50<12:22,  1.84it/s]


 12%|█▏        | 190/1559 [01:51<14:34,  1.57it/s]


 12%|█▏        | 191/1559 [01:51<14:54,  1.53it/s]


 12%|█▏        | 192/1559 [01:52<15:32,  1.47it/s]


 12%|█▏        | 193/1559 [01:52<12:30,  1.82it/s]


 12%|█▏        | 194/1559 [01:52<09:32,  2.38it/s]


 13%|█▎        | 195/1559 [01:53<09:49,  2.32it/s]


 13%|█▎        | 196/1559 [01:54<13:03,  1.74it/s]


 13%|█▎        | 197/1559 [01:54<13:13,  1.72it/s]


 13%|█▎        | 198/1559 [01:55<13:40,  1.66it/s]


 13%|█▎        | 199/1559 [01:55<13:09,  1.72it/s]


 13%|█▎        | 200/1559 [01:57<16:49,  1.35it/s]


 13%|█▎        | 201/1559 [01:57<12:52,  1.76it/s]


 13%|█▎        | 203/1559 [01:57<09:30,  2.38it/s]


 13%|█▎        | 204/1559 [01:58<12:37,  1.79it/s]


 13%|█▎        | 205/1559 [01:59<13:36,  1.66it/s]


 13%|█▎        | 206/1559 [01:59<12:37,  1.79it/s]


 13%|█▎        | 207/1559 [02:00<15:55,  1.42it/s]


 13%|█▎        | 208/1559 [02:01<15:11,  1.48it/s]


 13%|█▎        | 209/1559 [02:01<11:42,  1.92it/s]


 13%|█▎        | 210/1559 [02:02<11:20,  1.98it/s]


 14%|█▎        | 211/1559 [02:02<09:06,  2.46it/s]


 14%|█▎        | 212/1559 [02:03<15:30,  1.45it/s]


 14%|█▎        | 213/1559 [02:04<16:16,  1.38it/s]


 14%|█▎        | 214/1559 [02:04<14:24,  1.56it/s]


 14%|█▍        | 215/1559 [02:05<12:16,  1.82it/s]


 14%|█▍        | 216/1559 [02:06<13:59,  1.60it/s]


 14%|█▍        | 217/1559 [02:06<13:03,  1.71it/s]


 14%|█▍        | 219/1559 [02:06<07:56,  2.81it/s]


 14%|█▍        | 220/1559 [02:08<14:14,  1.57it/s]


 14%|█▍        | 221/1559 [02:09<15:04,  1.48it/s]


 14%|█▍        | 222/1559 [02:09<13:19,  1.67it/s]


 14%|█▍        | 223/1559 [02:09<10:35,  2.10it/s]


 14%|█▍        | 224/1559 [02:10<13:57,  1.59it/s]


 14%|█▍        | 225/1559 [02:10<12:05,  1.84it/s]


 14%|█▍        | 226/1559 [02:11<09:43,  2.29it/s]


 15%|█▍        | 227/1559 [02:11<07:47,  2.85it/s]


 15%|█▍        | 228/1559 [02:12<14:26,  1.54it/s]


 15%|█▍        | 229/1559 [02:13<15:09,  1.46it/s]


 15%|█▍        | 230/1559 [02:13<13:42,  1.62it/s]


 15%|█▍        | 231/1559 [02:13<10:24,  2.13it/s]


 15%|█▍        | 232/1559 [02:15<14:46,  1.50it/s]


 15%|█▍        | 233/1559 [02:15<14:21,  1.54it/s]


 15%|█▌        | 234/1559 [02:15<10:43,  2.06it/s]


 15%|█▌        | 235/1559 [02:16<08:53,  2.48it/s]


 15%|█▌        | 236/1559 [02:17<13:38,  1.62it/s]


 15%|█▌        | 237/1559 [02:17<13:16,  1.66it/s]


 15%|█▌        | 238/1559 [02:18<14:58,  1.47it/s]


 15%|█▌        | 239/1559 [02:18<11:44,  1.87it/s]


 15%|█▌        | 240/1559 [02:19<14:23,  1.53it/s]


 15%|█▌        | 241/1559 [02:20<13:20,  1.65it/s]


 16%|█▌        | 242/1559 [02:21<14:47,  1.48it/s]


 16%|█▌        | 243/1559 [02:21<11:58,  1.83it/s]


 16%|█▌        | 244/1559 [02:21<10:54,  2.01it/s]


 16%|█▌        | 245/1559 [02:22<11:26,  1.91it/s]


 16%|█▌        | 246/1559 [02:23<13:39,  1.60it/s]


 16%|█▌        | 247/1559 [02:23<12:11,  1.79it/s]


 16%|█▌        | 248/1559 [02:24<12:54,  1.69it/s]


 16%|█▌        | 249/1559 [02:24<12:44,  1.71it/s]


 16%|█▌        | 250/1559 [02:25<14:21,  1.52it/s]


 16%|█▌        | 251/1559 [02:25<11:36,  1.88it/s]


 16%|█▌        | 252/1559 [02:26<10:05,  2.16it/s]


 16%|█▌        | 253/1559 [02:26<10:28,  2.08it/s]


 16%|█▋        | 254/1559 [02:27<13:01,  1.67it/s]


 16%|█▋        | 255/1559 [02:27<11:23,  1.91it/s]


 16%|█▋        | 256/1559 [02:28<11:59,  1.81it/s]


 16%|█▋        | 257/1559 [02:29<12:03,  1.80it/s]


 17%|█▋        | 258/1559 [02:30<16:33,  1.31it/s]


 17%|█▋        | 260/1559 [02:30<10:03,  2.15it/s]


 17%|█▋        | 261/1559 [02:31<10:52,  1.99it/s]


 17%|█▋        | 262/1559 [02:32<14:45,  1.46it/s]


 17%|█▋        | 264/1559 [02:32<11:09,  1.93it/s]


 17%|█▋        | 265/1559 [02:33<11:47,  1.83it/s]


 17%|█▋        | 266/1559 [02:34<15:54,  1.35it/s]


 17%|█▋        | 267/1559 [02:35<13:31,  1.59it/s]


 17%|█▋        | 269/1559 [02:36<12:22,  1.74it/s]


 17%|█▋        | 270/1559 [02:36<12:13,  1.76it/s]


 17%|█▋        | 271/1559 [02:37<13:32,  1.59it/s]


 17%|█▋        | 272/1559 [02:37<10:45,  1.99it/s]


 18%|█▊        | 273/1559 [02:38<12:17,  1.74it/s]


 18%|█▊        | 274/1559 [02:39<14:20,  1.49it/s]


 18%|█▊        | 275/1559 [02:39<11:42,  1.83it/s]


 18%|█▊        | 276/1559 [02:39<09:56,  2.15it/s]


 18%|█▊        | 277/1559 [02:40<12:35,  1.70it/s]


 18%|█▊        | 278/1559 [02:41<11:40,  1.83it/s]


 18%|█▊        | 279/1559 [02:41<12:55,  1.65it/s]


 18%|█▊        | 280/1559 [02:42<11:19,  1.88it/s]


 18%|█▊        | 281/1559 [02:43<12:45,  1.67it/s]


 18%|█▊        | 282/1559 [02:43<13:49,  1.54it/s]


 18%|█▊        | 283/1559 [02:44<11:51,  1.79it/s]


 18%|█▊        | 284/1559 [02:44<09:47,  2.17it/s]


 18%|█▊        | 285/1559 [02:45<12:38,  1.68it/s]


 18%|█▊        | 286/1559 [02:45<12:11,  1.74it/s]


 18%|█▊        | 287/1559 [02:46<12:22,  1.71it/s]


 18%|█▊        | 288/1559 [02:46<11:52,  1.78it/s]


 19%|█▊        | 289/1559 [02:47<13:26,  1.57it/s]


 19%|█▊        | 290/1559 [02:48<14:10,  1.49it/s]


 19%|█▊        | 291/1559 [02:48<10:45,  1.96it/s]


 19%|█▊        | 292/1559 [02:48<09:15,  2.28it/s]


 19%|█▉        | 293/1559 [02:49<12:44,  1.66it/s]


 19%|█▉        | 294/1559 [02:50<13:08,  1.60it/s]


 19%|█▉        | 295/1559 [02:51<14:26,  1.46it/s]


 19%|█▉        | 296/1559 [02:51<12:27,  1.69it/s]


 19%|█▉        | 297/1559 [02:52<15:02,  1.40it/s]


 19%|█▉        | 298/1559 [02:53<12:49,  1.64it/s]


 19%|█▉        | 299/1559 [02:53<09:57,  2.11it/s]


 19%|█▉        | 300/1559 [02:53<10:13,  2.05it/s]


 19%|█▉        | 301/1559 [02:54<11:18,  1.85it/s]


 19%|█▉        | 302/1559 [02:55<15:30,  1.35it/s]

 19%|█▉        | 303/1559 [02:56<14:09,  1.48it/s]


 19%|█▉        | 304/1559 [02:56<13:40,  1.53it/s]


 20%|█▉        | 305/1559 [02:57<14:01,  1.49it/s]


 20%|█▉        | 306/1559 [02:57<11:35,  1.80it/s]


 20%|█▉        | 307/1559 [02:58<11:33,  1.80it/s]


 20%|█▉        | 309/1559 [02:59<09:45,  2.13it/s]


 20%|█▉        | 310/1559 [03:00<13:29,  1.54it/s]


 20%|█▉        | 311/1559 [03:00<12:43,  1.64it/s]


 20%|██        | 312/1559 [03:01<13:43,  1.52it/s]


 20%|██        | 313/1559 [03:02<13:17,  1.56it/s]


 20%|██        | 314/1559 [03:02<10:34,  1.96it/s]


 20%|██        | 315/1559 [03:03<11:27,  1.81it/s]


 20%|██        | 316/1559 [03:03<09:41,  2.14it/s]


 20%|██        | 317/1559 [03:03<09:33,  2.17it/s]


 20%|██        | 318/1559 [03:05<16:17,  1.27it/s]


 20%|██        | 319/1559 [03:05<12:45,  1.62it/s]


 21%|██        | 320/1559 [03:06<13:52,  1.49it/s]


 21%|██        | 321/1559 [03:06<12:35,  1.64it/s]


 21%|██        | 322/1559 [03:07<13:27,  1.53it/s]


 21%|██        | 324/1559 [03:08<11:44,  1.75it/s]


 21%|██        | 325/1559 [03:08<10:19,  1.99it/s]


 21%|██        | 326/1559 [03:09<12:45,  1.61it/s]


 21%|██        | 327/1559 [03:10<11:43,  1.75it/s]


 21%|██        | 328/1559 [03:11<13:18,  1.54it/s]


 21%|██        | 329/1559 [03:11<12:31,  1.64it/s]


 21%|██        | 330/1559 [03:12<11:56,  1.71it/s]


 21%|██▏       | 332/1559 [03:13<12:12,  1.67it/s]


 21%|██▏       | 334/1559 [03:14<10:41,  1.91it/s]


 21%|██▏       | 335/1559 [03:14<11:11,  1.82it/s]


 22%|██▏       | 336/1559 [03:15<13:05,  1.56it/s]


 22%|██▏       | 337/1559 [03:16<12:03,  1.69it/s]


 22%|██▏       | 338/1559 [03:16<11:48,  1.72it/s]


 22%|██▏       | 340/1559 [03:17<12:14,  1.66it/s]


 22%|██▏       | 342/1559 [03:18<09:51,  2.06it/s]


 22%|██▏       | 343/1559 [03:19<11:07,  1.82it/s]


 22%|██▏       | 344/1559 [03:20<13:21,  1.52it/s]


 22%|██▏       | 345/1559 [03:20<11:34,  1.75it/s]


 22%|██▏       | 346/1559 [03:21<12:31,  1.61it/s]


 22%|██▏       | 348/1559 [03:22<12:06,  1.67it/s]


 22%|██▏       | 349/1559 [03:22<10:11,  1.98it/s]


 22%|██▏       | 350/1559 [03:23<09:18,  2.16it/s]


 23%|██▎       | 351/1559 [03:23<10:44,  1.87it/s]


 23%|██▎       | 352/1559 [03:24<14:11,  1.42it/s]


 23%|██▎       | 353/1559 [03:25<11:49,  1.70it/s]


 23%|██▎       | 354/1559 [03:26<12:41,  1.58it/s]


 23%|██▎       | 355/1559 [03:26<11:13,  1.79it/s]


 23%|██▎       | 356/1559 [03:27<13:42,  1.46it/s]


 23%|██▎       | 357/1559 [03:27<11:55,  1.68it/s]


 23%|██▎       | 358/1559 [03:27<09:06,  2.20it/s]


 23%|██▎       | 359/1559 [03:28<11:55,  1.68it/s]


 23%|██▎       | 360/1559 [03:29<13:17,  1.50it/s]


 23%|██▎       | 361/1559 [03:29<10:18,  1.94it/s]


 23%|██▎       | 362/1559 [03:31<14:20,  1.39it/s]


 23%|██▎       | 363/1559 [03:31<12:44,  1.56it/s]


 23%|██▎       | 364/1559 [03:31<11:40,  1.70it/s]


 23%|██▎       | 365/1559 [03:32<09:45,  2.04it/s]


 23%|██▎       | 366/1559 [03:32<09:57,  2.00it/s]


 24%|██▎       | 367/1559 [03:33<11:36,  1.71it/s]


 24%|██▎       | 368/1559 [03:34<12:31,  1.59it/s]


 24%|██▎       | 369/1559 [03:34<09:36,  2.07it/s]


 24%|██▎       | 370/1559 [03:35<13:26,  1.47it/s]


 24%|██▍       | 371/1559 [03:35<12:18,  1.61it/s]


 24%|██▍       | 372/1559 [03:36<11:04,  1.79it/s]


 24%|██▍       | 373/1559 [03:36<09:50,  2.01it/s]


 24%|██▍       | 374/1559 [03:37<10:10,  1.94it/s]


 24%|██▍       | 375/1559 [03:37<10:55,  1.81it/s]


 24%|██▍       | 376/1559 [03:39<13:49,  1.43it/s]


 24%|██▍       | 377/1559 [03:39<11:05,  1.78it/s]


 24%|██▍       | 378/1559 [03:39<11:46,  1.67it/s]


 24%|██▍       | 379/1559 [03:40<13:58,  1.41it/s]


 24%|██▍       | 381/1559 [03:41<08:22,  2.34it/s]


 25%|██▍       | 382/1559 [03:41<09:47,  2.00it/s]


 25%|██▍       | 383/1559 [03:42<12:39,  1.55it/s]


 25%|██▍       | 384/1559 [03:43<14:10,  1.38it/s]


 25%|██▍       | 386/1559 [03:44<11:12,  1.74it/s]


 25%|██▍       | 387/1559 [03:45<12:15,  1.59it/s]


 25%|██▍       | 389/1559 [03:45<08:31,  2.29it/s]


 25%|██▌       | 390/1559 [03:46<09:45,  2.00it/s]


 25%|██▌       | 391/1559 [03:47<12:10,  1.60it/s]


 25%|██▌       | 392/1559 [03:48<13:41,  1.42it/s]


 25%|██▌       | 394/1559 [03:49<10:59,  1.77it/s]


 25%|██▌       | 395/1559 [03:49<12:10,  1.59it/s]


 25%|██▌       | 397/1559 [03:50<07:41,  2.52it/s]


 26%|██▌       | 398/1559 [03:51<10:51,  1.78it/s]


 26%|██▌       | 399/1559 [03:51<11:14,  1.72it/s]


 26%|██▌       | 400/1559 [03:52<14:09,  1.36it/s]


 26%|██▌       | 401/1559 [03:53<10:53,  1.77it/s]


 26%|██▌       | 402/1559 [03:54<13:16,  1.45it/s]


 26%|██▌       | 403/1559 [03:54<12:02,  1.60it/s]


 26%|██▌       | 405/1559 [03:55<09:21,  2.05it/s]


 26%|██▌       | 406/1559 [03:56<12:00,  1.60it/s]


 26%|██▌       | 407/1559 [03:56<09:31,  2.02it/s]


 26%|██▌       | 408/1559 [03:57<13:38,  1.41it/s]


 26%|██▌       | 409/1559 [03:58<12:59,  1.48it/s]


 26%|██▋       | 410/1559 [03:59<13:28,  1.42it/s]


 26%|██▋       | 412/1559 [03:59<08:15,  2.31it/s]


 26%|██▋       | 413/1559 [04:00<10:09,  1.88it/s]


 27%|██▋       | 414/1559 [04:00<11:16,  1.69it/s]


 27%|██▋       | 415/1559 [04:01<10:31,  1.81it/s]


 27%|██▋       | 416/1559 [04:02<13:09,  1.45it/s]


 27%|██▋       | 417/1559 [04:02<12:04,  1.58it/s]


 27%|██▋       | 418/1559 [04:03<12:38,  1.50it/s]


 27%|██▋       | 419/1559 [04:03<09:33,  1.99it/s]


 27%|██▋       | 420/1559 [04:03<07:29,  2.53it/s]


 27%|██▋       | 421/1559 [04:04<09:45,  1.94it/s]


 27%|██▋       | 422/1559 [04:05<10:54,  1.74it/s]


 27%|██▋       | 423/1559 [04:05<10:27,  1.81it/s]


 27%|██▋       | 424/1559 [04:07<14:11,  1.33it/s]


 27%|██▋       | 425/1559 [04:07<14:58,  1.26it/s]


 27%|██▋       | 427/1559 [04:08<10:13,  1.85it/s]


 27%|██▋       | 428/1559 [04:08<09:37,  1.96it/s]


 28%|██▊       | 429/1559 [04:09<08:52,  2.12it/s]


 28%|██▊       | 430/1559 [04:09<09:13,  2.04it/s]


 28%|██▊       | 431/1559 [04:11<13:34,  1.38it/s]


 28%|██▊       | 432/1559 [04:11<13:19,  1.41it/s]


 28%|██▊       | 433/1559 [04:12<13:00,  1.44it/s]


 28%|██▊       | 434/1559 [04:12<11:25,  1.64it/s]


 28%|██▊       | 435/1559 [04:13<10:22,  1.81it/s]


 28%|██▊       | 436/1559 [04:13<08:11,  2.28it/s]


 28%|██▊       | 437/1559 [04:14<10:10,  1.84it/s]


 28%|██▊       | 438/1559 [04:14<08:59,  2.08it/s]


 28%|██▊       | 439/1559 [04:15<13:40,  1.36it/s]


 28%|██▊       | 440/1559 [04:16<11:57,  1.56it/s]


 28%|██▊       | 441/1559 [04:17<13:28,  1.38it/s]


 28%|██▊       | 442/1559 [04:17<10:05,  1.85it/s]


 28%|██▊       | 443/1559 [04:17<09:11,  2.02it/s]


 28%|██▊       | 444/1559 [04:17<08:05,  2.30it/s]


 29%|██▊       | 445/1559 [04:18<09:26,  1.97it/s]


 29%|██▊       | 446/1559 [04:19<08:56,  2.07it/s]


 29%|██▊       | 447/1559 [04:20<13:32,  1.37it/s]


 29%|██▊       | 448/1559 [04:20<11:19,  1.64it/s]


 29%|██▉       | 449/1559 [04:21<12:54,  1.43it/s]

 29%|██▉       | 450/1559 [04:21<10:59,  1.68it/s]


 29%|██▉       | 451/1559 [04:22<10:16,  1.80it/s]


 29%|██▉       | 453/1559 [04:23<10:00,  1.84it/s]


 29%|██▉       | 455/1559 [04:24<11:08,  1.65it/s]


 29%|██▉       | 456/1559 [04:25<12:52,  1.43it/s]


 29%|██▉       | 458/1559 [04:26<09:59,  1.84it/s]


 29%|██▉       | 459/1559 [04:26<09:35,  1.91it/s]


 30%|██▉       | 460/1559 [04:27<08:09,  2.25it/s]


 30%|██▉       | 461/1559 [04:28<11:31,  1.59it/s]


 30%|██▉       | 462/1559 [04:28<09:52,  1.85it/s]


 30%|██▉       | 463/1559 [04:29<12:41,  1.44it/s]


 30%|██▉       | 464/1559 [04:30<11:35,  1.57it/s]


 30%|██▉       | 465/1559 [04:30<09:36,  1.90it/s]


 30%|██▉       | 466/1559 [04:31<11:28,  1.59it/s]


 30%|███       | 468/1559 [04:31<08:18,  2.19it/s]


 30%|███       | 469/1559 [04:33<11:25,  1.59it/s]


 30%|███       | 470/1559 [04:33<09:16,  1.96it/s]


 30%|███       | 471/1559 [04:34<12:33,  1.44it/s]


 30%|███       | 472/1559 [04:34<10:19,  1.75it/s]


 30%|███       | 473/1559 [04:35<09:15,  1.96it/s]


 30%|███       | 474/1559 [04:35<11:01,  1.64it/s]


 30%|███       | 475/1559 [04:35<08:19,  2.17it/s]


 31%|███       | 476/1559 [04:36<07:46,  2.32it/s]


 31%|███       | 477/1559 [04:37<11:43,  1.54it/s]


 31%|███       | 479/1559 [04:39<12:38,  1.42it/s]


 31%|███       | 480/1559 [04:39<10:29,  1.71it/s]


 31%|███       | 481/1559 [04:39<08:37,  2.08it/s]


 31%|███       | 482/1559 [04:40<10:46,  1.66it/s]


 31%|███       | 483/1559 [04:40<10:27,  1.72it/s]


 31%|███       | 485/1559 [04:41<09:48,  1.82it/s]


 31%|███       | 486/1559 [04:42<09:25,  1.90it/s]


 31%|███       | 487/1559 [04:43<13:20,  1.34it/s]


 31%|███▏      | 489/1559 [04:44<10:26,  1.71it/s]


 31%|███▏      | 490/1559 [04:45<11:17,  1.58it/s]


 32%|███▏      | 492/1559 [04:45<08:27,  2.10it/s]


 32%|███▏      | 493/1559 [04:46<10:18,  1.72it/s]


 32%|███▏      | 494/1559 [04:47<10:25,  1.70it/s]


 32%|███▏      | 495/1559 [04:48<12:03,  1.47it/s]


 32%|███▏      | 496/1559 [04:48<10:06,  1.75it/s]


 32%|███▏      | 497/1559 [04:49<10:41,  1.66it/s]


 32%|███▏      | 498/1559 [04:49<10:38,  1.66it/s]


 32%|███▏      | 500/1559 [04:50<08:27,  2.09it/s]


 32%|███▏      | 501/1559 [04:51<09:40,  1.82it/s]


 32%|███▏      | 502/1559 [04:51<09:50,  1.79it/s]


 32%|███▏      | 503/1559 [04:52<11:25,  1.54it/s]


 32%|███▏      | 504/1559 [04:53<12:02,  1.46it/s]


 32%|███▏      | 505/1559 [04:53<09:59,  1.76it/s]


 32%|███▏      | 506/1559 [04:54<10:05,  1.74it/s]


 33%|███▎      | 507/1559 [04:54<09:49,  1.78it/s]


 33%|███▎      | 508/1559 [04:55<10:17,  1.70it/s]


 33%|███▎      | 509/1559 [04:56<11:21,  1.54it/s]


 33%|███▎      | 510/1559 [04:56<10:20,  1.69it/s]


 33%|███▎      | 511/1559 [04:57<09:25,  1.85it/s]


 33%|███▎      | 512/1559 [04:58<11:23,  1.53it/s]


 33%|███▎      | 513/1559 [04:58<11:12,  1.56it/s]


 33%|███▎      | 514/1559 [04:59<12:26,  1.40it/s]


 33%|███▎      | 515/1559 [04:59<10:39,  1.63it/s]


 33%|███▎      | 516/1559 [05:00<08:56,  1.95it/s]


 33%|███▎      | 517/1559 [05:01<10:38,  1.63it/s]


 33%|███▎      | 518/1559 [05:01<11:34,  1.50it/s]


 33%|███▎      | 520/1559 [05:02<09:44,  1.78it/s]


 33%|███▎      | 521/1559 [05:03<09:57,  1.74it/s]


 33%|███▎      | 522/1559 [05:04<11:01,  1.57it/s]


 34%|███▎      | 523/1559 [05:04<10:54,  1.58it/s]


 34%|███▎      | 524/1559 [05:05<08:49,  1.95it/s]


 34%|███▎      | 525/1559 [05:05<09:59,  1.73it/s]


 34%|███▎      | 526/1559 [05:06<10:25,  1.65it/s]


 34%|███▍      | 528/1559 [05:07<09:45,  1.76it/s]


 34%|███▍      | 529/1559 [05:07<09:04,  1.89it/s]


 34%|███▍      | 530/1559 [05:09<12:20,  1.39it/s]


 34%|███▍      | 531/1559 [05:09<10:08,  1.69it/s]


 34%|███▍      | 532/1559 [05:10<11:42,  1.46it/s]


 34%|███▍      | 533/1559 [05:10<09:24,  1.82it/s]


 34%|███▍      | 534/1559 [05:11<12:58,  1.32it/s]


 34%|███▍      | 535/1559 [05:12<10:09,  1.68it/s]


 34%|███▍      | 536/1559 [05:12<10:18,  1.65it/s]


 34%|███▍      | 537/1559 [05:12<08:18,  2.05it/s]


 35%|███▍      | 538/1559 [05:14<12:02,  1.41it/s]


 35%|███▍      | 540/1559 [05:15<10:31,  1.61it/s]


 35%|███▍      | 542/1559 [05:16<10:08,  1.67it/s]


 35%|███▍      | 543/1559 [05:16<10:32,  1.61it/s]


 35%|███▍      | 544/1559 [05:17<09:54,  1.71it/s]


 35%|███▍      | 545/1559 [05:17<08:21,  2.02it/s]


 35%|███▌      | 546/1559 [05:18<10:54,  1.55it/s]


 35%|███▌      | 547/1559 [05:18<08:58,  1.88it/s]


 35%|███▌      | 548/1559 [05:19<10:34,  1.59it/s]


 35%|███▌      | 549/1559 [05:20<08:23,  2.01it/s]


 35%|███▌      | 550/1559 [05:20<10:01,  1.68it/s]


 35%|███▌      | 551/1559 [05:21<11:04,  1.52it/s]


 35%|███▌      | 552/1559 [05:22<10:53,  1.54it/s]


 35%|███▌      | 553/1559 [05:22<08:21,  2.00it/s]


 36%|███▌      | 554/1559 [05:23<10:44,  1.56it/s]


 36%|███▌      | 555/1559 [05:23<08:35,  1.95it/s]


 36%|███▌      | 556/1559 [05:24<10:34,  1.58it/s]


 36%|███▌      | 557/1559 [05:24<08:01,  2.08it/s]


 36%|███▌      | 558/1559 [05:25<09:43,  1.72it/s]


 36%|███▌      | 559/1559 [05:26<12:19,  1.35it/s]


 36%|███▌      | 560/1559 [05:27<11:39,  1.43it/s]


 36%|███▌      | 561/1559 [05:27<08:48,  1.89it/s]


 36%|███▌      | 562/1559 [05:27<09:20,  1.78it/s]


 36%|███▌      | 563/1559 [05:29<12:46,  1.30it/s]


 36%|███▌      | 564/1559 [05:29<12:27,  1.33it/s]


 36%|███▌      | 565/1559 [05:30<09:28,  1.75it/s]


 36%|███▋      | 566/1559 [05:30<07:47,  2.13it/s]


 36%|███▋      | 567/1559 [05:31<09:00,  1.83it/s]


 36%|███▋      | 568/1559 [05:31<10:12,  1.62it/s]


 36%|███▋      | 569/1559 [05:32<10:30,  1.57it/s]


 37%|███▋      | 570/1559 [05:32<07:59,  2.06it/s]


 37%|███▋      | 571/1559 [05:34<13:11,  1.25it/s]


 37%|███▋      | 572/1559 [05:34<10:55,  1.51it/s]


 37%|███▋      | 573/1559 [05:34<09:14,  1.78it/s]


 37%|███▋      | 574/1559 [05:35<07:26,  2.21it/s]


 37%|███▋      | 575/1559 [05:35<09:20,  1.76it/s]


 37%|███▋      | 576/1559 [05:36<10:05,  1.62it/s]


 37%|███▋      | 577/1559 [05:37<09:34,  1.71it/s]


 37%|███▋      | 578/1559 [05:37<08:05,  2.02it/s]


 37%|███▋      | 579/1559 [05:38<12:44,  1.28it/s]


 37%|███▋      | 580/1559 [05:39<10:11,  1.60it/s]


 37%|███▋      | 581/1559 [05:39<08:15,  1.97it/s]


 37%|███▋      | 582/1559 [05:39<07:03,  2.31it/s]


 37%|███▋      | 583/1559 [05:40<08:18,  1.96it/s]


 37%|███▋      | 584/1559 [05:41<10:03,  1.62it/s]


 38%|███▊      | 585/1559 [05:41<09:20,  1.74it/s]


 38%|███▊      | 586/1559 [05:41<07:16,  2.23it/s]


 38%|███▊      | 587/1559 [05:43<13:24,  1.21it/s]


 38%|███▊      | 588/1559 [05:43<10:33,  1.53it/s]


 38%|███▊      | 589/1559 [05:43<08:36,  1.88it/s]


 38%|███▊      | 590/1559 [05:44<06:50,  2.36it/s]


 38%|███▊      | 591/1559 [05:44<08:49,  1.83it/s]


 38%|███▊      | 592/1559 [05:46<12:48,  1.26it/s]


 38%|███▊      | 593/1559 [05:46<09:44,  1.65it/s]


 38%|███▊      | 594/1559 [05:47<09:33,  1.68it/s]

 38%|███▊      | 595/1559 [05:48<11:35,  1.39it/s]


 38%|███▊      | 596/1559 [05:48<09:46,  1.64it/s]


 38%|███▊      | 597/1559 [05:48<07:34,  2.12it/s]


 38%|███▊      | 598/1559 [05:49<08:26,  1.90it/s]


 38%|███▊      | 599/1559 [05:49<07:43,  2.07it/s]


 38%|███▊      | 600/1559 [05:51<12:58,  1.23it/s]


 39%|███▊      | 601/1559 [05:51<10:37,  1.50it/s]


 39%|███▊      | 602/1559 [05:51<08:59,  1.77it/s]


 39%|███▊      | 603/1559 [05:52<10:47,  1.48it/s]


 39%|███▊      | 604/1559 [05:53<08:47,  1.81it/s]


 39%|███▉      | 605/1559 [05:53<07:01,  2.26it/s]


 39%|███▉      | 606/1559 [05:53<08:02,  1.98it/s]


 39%|███▉      | 607/1559 [05:54<07:00,  2.26it/s]


 39%|███▉      | 608/1559 [05:56<13:50,  1.14it/s]


 39%|███▉      | 609/1559 [05:56<11:24,  1.39it/s]


 39%|███▉      | 611/1559 [05:57<10:09,  1.55it/s]


 39%|███▉      | 612/1559 [05:57<08:39,  1.82it/s]


 39%|███▉      | 613/1559 [05:58<07:08,  2.21it/s]


 39%|███▉      | 614/1559 [05:58<07:16,  2.16it/s]


 39%|███▉      | 615/1559 [05:58<06:01,  2.61it/s]


 40%|███▉      | 616/1559 [06:01<15:13,  1.03it/s]


 40%|███▉      | 618/1559 [06:01<10:12,  1.54it/s]


 40%|███▉      | 619/1559 [06:02<09:40,  1.62it/s]


 40%|███▉      | 620/1559 [06:02<08:22,  1.87it/s]


 40%|███▉      | 621/1559 [06:02<07:05,  2.20it/s]


 40%|███▉      | 622/1559 [06:03<08:39,  1.80it/s]


 40%|███▉      | 623/1559 [06:03<06:46,  2.30it/s]


 40%|████      | 624/1559 [06:05<15:23,  1.01it/s]


 40%|████      | 625/1559 [06:06<11:55,  1.31it/s]


 40%|████      | 627/1559 [06:07<09:32,  1.63it/s]


 40%|████      | 628/1559 [06:07<07:41,  2.02it/s]


 40%|████      | 629/1559 [06:07<07:29,  2.07it/s]


 40%|████      | 630/1559 [06:08<07:14,  2.14it/s]


 40%|████      | 631/1559 [06:08<05:51,  2.64it/s]


 41%|████      | 632/1559 [06:10<14:49,  1.04it/s]


 41%|████      | 633/1559 [06:10<11:03,  1.39it/s]


 41%|████      | 634/1559 [06:10<08:27,  1.82it/s]


 41%|████      | 635/1559 [06:11<09:28,  1.62it/s]


 41%|████      | 637/1559 [06:12<07:10,  2.14it/s]


 41%|████      | 638/1559 [06:12<06:25,  2.39it/s]


 41%|████      | 639/1559 [06:12<05:31,  2.77it/s]


 41%|████      | 640/1559 [06:15<14:14,  1.08it/s]


 41%|████      | 641/1559 [06:15<11:35,  1.32it/s]


 41%|████      | 643/1559 [06:16<09:00,  1.70it/s]


 41%|████▏     | 645/1559 [06:16<07:40,  1.98it/s]


 41%|████▏     | 646/1559 [06:17<07:32,  2.02it/s]


 42%|████▏     | 647/1559 [06:17<06:20,  2.40it/s]


 42%|████▏     | 648/1559 [06:19<13:14,  1.15it/s]


 42%|████▏     | 649/1559 [06:20<10:27,  1.45it/s]


 42%|████▏     | 650/1559 [06:20<08:42,  1.74it/s]


 42%|████▏     | 651/1559 [06:20<08:37,  1.75it/s]


 42%|████▏     | 652/1559 [06:21<08:33,  1.77it/s]


 42%|████▏     | 653/1559 [06:22<09:39,  1.56it/s]


 42%|████▏     | 654/1559 [06:22<07:24,  2.04it/s]


 42%|████▏     | 655/1559 [06:22<06:12,  2.43it/s]


 42%|████▏     | 656/1559 [06:24<12:56,  1.16it/s]


 42%|████▏     | 658/1559 [06:25<08:52,  1.69it/s]


 42%|████▏     | 659/1559 [06:25<08:41,  1.72it/s]


 42%|████▏     | 660/1559 [06:26<08:21,  1.79it/s]


 42%|████▏     | 661/1559 [06:26<09:09,  1.63it/s]


 42%|████▏     | 662/1559 [06:27<07:40,  1.95it/s]


 43%|████▎     | 664/1559 [06:29<10:34,  1.41it/s]


 43%|████▎     | 665/1559 [06:29<08:29,  1.76it/s]


 43%|████▎     | 666/1559 [06:29<08:21,  1.78it/s]


 43%|████▎     | 667/1559 [06:30<08:10,  1.82it/s]


 43%|████▎     | 668/1559 [06:30<08:17,  1.79it/s]


 43%|████▎     | 669/1559 [06:31<09:22,  1.58it/s]


 43%|████▎     | 670/1559 [06:31<07:26,  1.99it/s]


 43%|████▎     | 672/1559 [06:33<10:06,  1.46it/s]


 43%|████▎     | 673/1559 [06:34<09:05,  1.62it/s]


 43%|████▎     | 674/1559 [06:34<08:14,  1.79it/s]


 43%|████▎     | 675/1559 [06:35<10:26,  1.41it/s]


 43%|████▎     | 676/1559 [06:36<10:06,  1.46it/s]


 43%|████▎     | 677/1559 [06:36<08:01,  1.83it/s]


 43%|████▎     | 678/1559 [06:36<07:18,  2.01it/s]


 44%|████▎     | 679/1559 [06:36<05:40,  2.59it/s]


 44%|████▎     | 680/1559 [06:38<09:35,  1.53it/s]


 44%|████▎     | 681/1559 [06:38<08:20,  1.75it/s]


 44%|████▎     | 682/1559 [06:39<09:13,  1.58it/s]


 44%|████▍     | 683/1559 [06:40<11:27,  1.27it/s]


 44%|████▍     | 684/1559 [06:40<09:57,  1.47it/s]


 44%|████▍     | 685/1559 [06:40<07:31,  1.94it/s]


 44%|████▍     | 686/1559 [06:41<06:54,  2.11it/s]


 44%|████▍     | 687/1559 [06:41<05:16,  2.75it/s]


 44%|████▍     | 688/1559 [06:42<09:15,  1.57it/s]


 44%|████▍     | 689/1559 [06:43<07:56,  1.82it/s]


 44%|████▍     | 690/1559 [06:43<09:12,  1.57it/s]


 44%|████▍     | 691/1559 [06:45<11:21,  1.27it/s]


 44%|████▍     | 692/1559 [06:45<10:58,  1.32it/s]


 45%|████▍     | 694/1559 [06:45<06:33,  2.20it/s]


 45%|████▍     | 696/1559 [06:47<09:42,  1.48it/s]


 45%|████▍     | 697/1559 [06:48<08:36,  1.67it/s]


 45%|████▍     | 698/1559 [06:48<07:53,  1.82it/s]


 45%|████▍     | 699/1559 [06:49<09:27,  1.52it/s]


 45%|████▍     | 700/1559 [06:50<08:54,  1.61it/s]


 45%|████▍     | 701/1559 [06:50<07:26,  1.92it/s]


 45%|████▌     | 702/1559 [06:50<07:24,  1.93it/s]


 45%|████▌     | 703/1559 [06:51<06:00,  2.37it/s]


 45%|████▌     | 704/1559 [06:52<11:22,  1.25it/s]


 45%|████▌     | 706/1559 [06:53<08:13,  1.73it/s]


 45%|████▌     | 707/1559 [06:54<10:49,  1.31it/s]


 45%|████▌     | 708/1559 [06:55<09:06,  1.56it/s]


 45%|████▌     | 709/1559 [06:55<07:51,  1.80it/s]


 46%|████▌     | 710/1559 [06:55<06:34,  2.15it/s]


 46%|████▌     | 711/1559 [06:55<05:34,  2.54it/s]


 46%|████▌     | 712/1559 [06:57<09:55,  1.42it/s]


 46%|████▌     | 713/1559 [06:57<08:33,  1.65it/s]


 46%|████▌     | 714/1559 [06:58<08:38,  1.63it/s]


 46%|████▌     | 715/1559 [06:59<10:56,  1.28it/s]


 46%|████▌     | 716/1559 [06:59<08:41,  1.62it/s]


 46%|████▌     | 717/1559 [06:59<06:46,  2.07it/s]


 46%|████▌     | 718/1559 [07:00<06:59,  2.00it/s]


 46%|████▌     | 720/1559 [07:02<08:43,  1.60it/s]


 46%|████▌     | 721/1559 [07:02<07:57,  1.76it/s]


 46%|████▋     | 722/1559 [07:03<08:09,  1.71it/s]


 46%|████▋     | 723/1559 [07:04<10:48,  1.29it/s]


 47%|████▋     | 725/1559 [07:04<06:44,  2.06it/s]


 47%|████▋     | 726/1559 [07:04<06:26,  2.16it/s]


 47%|████▋     | 727/1559 [07:05<06:11,  2.24it/s]


 47%|████▋     | 728/1559 [07:06<10:29,  1.32it/s]


 47%|████▋     | 729/1559 [07:07<08:49,  1.57it/s]


 47%|████▋     | 730/1559 [07:07<08:41,  1.59it/s]


 47%|████▋     | 731/1559 [07:08<09:56,  1.39it/s]


 47%|████▋     | 732/1559 [07:09<10:10,  1.35it/s]


 47%|████▋     | 734/1559 [07:09<06:06,  2.25it/s]


 47%|████▋     | 735/1559 [07:10<05:32,  2.48it/s]


 47%|████▋     | 736/1559 [07:11<09:14,  1.48it/s]


 47%|████▋     | 737/1559 [07:12<08:31,  1.61it/s]


 47%|████▋     | 738/1559 [07:12<09:56,  1.38it/s]


 47%|████▋     | 739/1559 [07:13<09:36,  1.42it/s]


 47%|████▋     | 740/1559 [07:14<08:52,  1.54it/s]


 48%|████▊     | 741/1559 [07:14<07:40,  1.78it/s]

 48%|████▊     | 743/1559 [07:14<04:54,  2.77it/s]


 48%|████▊     | 744/1559 [07:15<07:33,  1.80it/s]


 48%|████▊     | 745/1559 [07:16<08:14,  1.65it/s]


 48%|████▊     | 746/1559 [07:17<09:47,  1.38it/s]


 48%|████▊     | 747/1559 [07:18<09:10,  1.48it/s]


 48%|████▊     | 748/1559 [07:18<07:55,  1.71it/s]


 48%|████▊     | 749/1559 [07:19<08:30,  1.59it/s]


 48%|████▊     | 752/1559 [07:21<08:01,  1.68it/s]


 48%|████▊     | 753/1559 [07:21<06:52,  1.95it/s]


 48%|████▊     | 754/1559 [07:22<08:26,  1.59it/s]


 48%|████▊     | 755/1559 [07:23<09:03,  1.48it/s]


 48%|████▊     | 756/1559 [07:23<07:06,  1.88it/s]


 49%|████▊     | 757/1559 [07:23<07:40,  1.74it/s]


 49%|████▊     | 758/1559 [07:24<07:15,  1.84it/s]


 49%|████▊     | 759/1559 [07:24<05:59,  2.22it/s]


 49%|████▊     | 760/1559 [07:25<09:18,  1.43it/s]


 49%|████▉     | 761/1559 [07:26<07:40,  1.73it/s]


 49%|████▉     | 762/1559 [07:26<08:25,  1.58it/s]


 49%|████▉     | 763/1559 [07:27<08:39,  1.53it/s]


 49%|████▉     | 764/1559 [07:28<07:36,  1.74it/s]


 49%|████▉     | 765/1559 [07:28<06:54,  1.92it/s]


 49%|████▉     | 766/1559 [07:28<06:59,  1.89it/s]


 49%|████▉     | 767/1559 [07:29<06:46,  1.95it/s]


 49%|████▉     | 768/1559 [07:30<09:44,  1.35it/s]


 49%|████▉     | 769/1559 [07:31<07:58,  1.65it/s]


 49%|████▉     | 770/1559 [07:31<08:19,  1.58it/s]


 49%|████▉     | 771/1559 [07:32<07:43,  1.70it/s]


 50%|████▉     | 772/1559 [07:32<07:00,  1.87it/s]


 50%|████▉     | 773/1559 [07:33<06:35,  1.99it/s]


 50%|████▉     | 774/1559 [07:33<06:59,  1.87it/s]


 50%|████▉     | 775/1559 [07:34<06:38,  1.97it/s]


 50%|████▉     | 776/1559 [07:35<09:38,  1.35it/s]


 50%|████▉     | 777/1559 [07:35<07:42,  1.69it/s]


 50%|████▉     | 778/1559 [07:36<08:59,  1.45it/s]


 50%|████▉     | 779/1559 [07:36<06:49,  1.90it/s]


 50%|█████     | 780/1559 [07:37<06:43,  1.93it/s]


 50%|█████     | 781/1559 [07:37<06:52,  1.88it/s]


 50%|█████     | 782/1559 [07:38<07:47,  1.66it/s]


 50%|█████     | 783/1559 [07:38<06:45,  1.91it/s]


 50%|█████     | 784/1559 [07:39<08:50,  1.46it/s]


 50%|█████     | 785/1559 [07:40<08:14,  1.56it/s]


 50%|█████     | 786/1559 [07:41<08:45,  1.47it/s]


 50%|█████     | 787/1559 [07:41<07:43,  1.66it/s]


 51%|█████     | 789/1559 [07:42<07:16,  1.76it/s]


 51%|█████     | 790/1559 [07:43<07:23,  1.73it/s]


 51%|█████     | 791/1559 [07:43<06:49,  1.88it/s]


 51%|█████     | 792/1559 [07:44<08:19,  1.54it/s]


 51%|█████     | 793/1559 [07:45<07:17,  1.75it/s]


 51%|█████     | 794/1559 [07:45<08:24,  1.52it/s]


 51%|█████     | 795/1559 [07:46<07:36,  1.68it/s]


 51%|█████     | 797/1559 [07:47<07:09,  1.77it/s]


 51%|█████     | 798/1559 [07:47<06:45,  1.88it/s]


 51%|█████▏    | 799/1559 [07:48<07:09,  1.77it/s]


 51%|█████▏    | 800/1559 [07:49<07:54,  1.60it/s]


 51%|█████▏    | 801/1559 [07:49<07:05,  1.78it/s]


 51%|█████▏    | 802/1559 [07:50<07:38,  1.65it/s]


 52%|█████▏    | 803/1559 [07:51<08:19,  1.51it/s]


 52%|█████▏    | 804/1559 [07:51<06:22,  1.97it/s]


 52%|█████▏    | 805/1559 [07:52<07:09,  1.76it/s]


 52%|█████▏    | 806/1559 [07:52<07:57,  1.58it/s]


 52%|█████▏    | 807/1559 [07:53<06:52,  1.82it/s]


 52%|█████▏    | 808/1559 [07:54<10:02,  1.25it/s]


 52%|█████▏    | 809/1559 [07:54<07:57,  1.57it/s]


 52%|█████▏    | 811/1559 [07:56<09:28,  1.32it/s]


 52%|█████▏    | 813/1559 [07:56<06:08,  2.02it/s]


 52%|█████▏    | 814/1559 [07:57<06:53,  1.80it/s]


 52%|█████▏    | 815/1559 [07:58<06:54,  1.79it/s]


 52%|█████▏    | 816/1559 [07:59<09:12,  1.35it/s]


 52%|█████▏    | 818/1559 [07:59<05:48,  2.12it/s]


 53%|█████▎    | 819/1559 [08:01<08:52,  1.39it/s]


 53%|█████▎    | 820/1559 [08:01<07:12,  1.71it/s]


 53%|█████▎    | 821/1559 [08:01<05:50,  2.10it/s]


 53%|█████▎    | 822/1559 [08:02<06:22,  1.92it/s]


 53%|█████▎    | 823/1559 [08:02<06:42,  1.83it/s]


 53%|█████▎    | 824/1559 [08:03<09:01,  1.36it/s]


 53%|█████▎    | 826/1559 [08:04<05:30,  2.22it/s]


 53%|█████▎    | 827/1559 [08:05<08:39,  1.41it/s]


 53%|█████▎    | 828/1559 [08:05<07:06,  1.71it/s]


 53%|█████▎    | 829/1559 [08:06<06:10,  1.97it/s]


 53%|█████▎    | 830/1559 [08:06<05:58,  2.03it/s]


 53%|█████▎    | 831/1559 [08:07<08:15,  1.47it/s]


 53%|█████▎    | 832/1559 [08:08<08:33,  1.42it/s]


 53%|█████▎    | 834/1559 [08:08<05:13,  2.31it/s]


 54%|█████▎    | 835/1559 [08:10<08:14,  1.46it/s]


 54%|█████▎    | 836/1559 [08:11<08:44,  1.38it/s]


 54%|█████▎    | 837/1559 [08:11<07:28,  1.61it/s]


 54%|█████▍    | 838/1559 [08:11<06:40,  1.80it/s]


 54%|█████▍    | 839/1559 [08:12<07:31,  1.60it/s]


 54%|█████▍    | 840/1559 [08:13<07:18,  1.64it/s]


 54%|█████▍    | 842/1559 [08:13<04:36,  2.59it/s]


 54%|█████▍    | 843/1559 [08:15<08:01,  1.49it/s]


 54%|█████▍    | 844/1559 [08:15<08:09,  1.46it/s]


 54%|█████▍    | 845/1559 [08:16<07:17,  1.63it/s]


 54%|█████▍    | 846/1559 [08:16<06:12,  1.91it/s]


 54%|█████▍    | 847/1559 [08:17<07:09,  1.66it/s]


 54%|█████▍    | 848/1559 [08:17<06:52,  1.72it/s]


 55%|█████▍    | 850/1559 [08:18<04:45,  2.48it/s]


 55%|█████▍    | 851/1559 [08:19<07:37,  1.55it/s]


 55%|█████▍    | 852/1559 [08:20<08:02,  1.47it/s]


 55%|█████▍    | 853/1559 [08:20<07:43,  1.52it/s]


 55%|█████▍    | 855/1559 [08:22<07:09,  1.64it/s]


 55%|█████▍    | 856/1559 [08:22<06:01,  1.95it/s]


 55%|█████▍    | 857/1559 [08:22<05:33,  2.10it/s]


 55%|█████▌    | 859/1559 [08:24<06:48,  1.71it/s]


 55%|█████▌    | 860/1559 [08:25<07:57,  1.46it/s]


 55%|█████▌    | 861/1559 [08:25<07:33,  1.54it/s]


 55%|█████▌    | 862/1559 [08:25<05:53,  1.97it/s]


 55%|█████▌    | 863/1559 [08:27<08:38,  1.34it/s]


 55%|█████▌    | 865/1559 [08:27<06:06,  1.89it/s]


 56%|█████▌    | 867/1559 [08:29<06:59,  1.65it/s]


 56%|█████▌    | 868/1559 [08:29<06:54,  1.67it/s]


 56%|█████▌    | 869/1559 [08:30<06:39,  1.73it/s]


 56%|█████▌    | 870/1559 [08:30<06:43,  1.71it/s]


 56%|█████▌    | 871/1559 [08:31<07:20,  1.56it/s]


 56%|█████▌    | 872/1559 [08:31<05:58,  1.92it/s]


 56%|█████▌    | 873/1559 [08:32<05:57,  1.92it/s]


 56%|█████▌    | 874/1559 [08:32<04:45,  2.40it/s]


 56%|█████▌    | 875/1559 [08:33<08:06,  1.41it/s]


 56%|█████▌    | 876/1559 [08:34<06:49,  1.67it/s]


 56%|█████▋    | 877/1559 [08:34<06:32,  1.74it/s]


 56%|█████▋    | 878/1559 [08:35<07:25,  1.53it/s]


 56%|█████▋    | 879/1559 [08:36<06:52,  1.65it/s]


 56%|█████▋    | 880/1559 [08:36<05:56,  1.90it/s]


 57%|█████▋    | 881/1559 [08:36<05:39,  1.99it/s]


 57%|█████▋    | 882/1559 [08:37<04:47,  2.36it/s]


 57%|█████▋    | 883/1559 [08:38<07:54,  1.42it/s]


 57%|█████▋    | 884/1559 [08:38<07:14,  1.55it/s]


 57%|█████▋    | 885/1559 [08:39<05:57,  1.89it/s]


 57%|█████▋    | 886/1559 [08:40<08:34,  1.31it/s]


 57%|█████▋    | 887/1559 [08:40<06:41,  1.67it/s]


 57%|█████▋    | 888/1559 [08:40<05:40,  1.97it/s]


 57%|█████▋    | 889/1559 [08:41<05:27,  2.05it/s]

 57%|█████▋    | 890/1559 [08:42<06:47,  1.64it/s]


 57%|█████▋    | 891/1559 [08:42<06:28,  1.72it/s]


 57%|█████▋    | 892/1559 [08:43<07:55,  1.40it/s]


 57%|█████▋    | 894/1559 [08:45<08:21,  1.33it/s]


 57%|█████▋    | 896/1559 [08:45<05:28,  2.02it/s]


 58%|█████▊    | 897/1559 [08:46<05:13,  2.11it/s]


 58%|█████▊    | 898/1559 [08:47<07:10,  1.53it/s]


 58%|█████▊    | 899/1559 [08:47<06:24,  1.72it/s]


 58%|█████▊    | 900/1559 [08:48<06:47,  1.62it/s]


 58%|█████▊    | 901/1559 [08:48<05:55,  1.85it/s]


 58%|█████▊    | 902/1559 [08:50<08:35,  1.27it/s]


 58%|█████▊    | 903/1559 [08:50<06:26,  1.70it/s]


 58%|█████▊    | 904/1559 [08:50<04:58,  2.20it/s]


 58%|█████▊    | 905/1559 [08:50<04:18,  2.53it/s]


 58%|█████▊    | 906/1559 [08:51<07:02,  1.54it/s]


 58%|█████▊    | 907/1559 [08:52<05:55,  1.83it/s]


 58%|█████▊    | 908/1559 [08:53<07:14,  1.50it/s]


 58%|█████▊    | 909/1559 [08:53<05:37,  1.93it/s]


 58%|█████▊    | 910/1559 [08:54<08:26,  1.28it/s]


 58%|█████▊    | 911/1559 [08:54<06:37,  1.63it/s]


 59%|█████▊    | 913/1559 [08:55<04:27,  2.41it/s]


 59%|█████▊    | 914/1559 [08:56<07:40,  1.40it/s]


 59%|█████▊    | 915/1559 [08:57<07:23,  1.45it/s]


 59%|█████▉    | 916/1559 [08:57<06:24,  1.67it/s]


 59%|█████▉    | 917/1559 [08:58<07:03,  1.52it/s]


 59%|█████▉    | 918/1559 [08:59<06:34,  1.62it/s]


 59%|█████▉    | 919/1559 [08:59<06:04,  1.76it/s]


 59%|█████▉    | 920/1559 [08:59<05:08,  2.07it/s]


 59%|█████▉    | 921/1559 [09:00<04:26,  2.39it/s]


 59%|█████▉    | 922/1559 [09:01<07:48,  1.36it/s]


 59%|█████▉    | 923/1559 [09:02<06:48,  1.56it/s]


 59%|█████▉    | 924/1559 [09:02<07:10,  1.48it/s]


 59%|█████▉    | 925/1559 [09:03<06:26,  1.64it/s]


 59%|█████▉    | 926/1559 [09:03<06:15,  1.69it/s]


 59%|█████▉    | 927/1559 [09:04<06:45,  1.56it/s]


 60%|█████▉    | 928/1559 [09:04<05:13,  2.01it/s]


 60%|█████▉    | 930/1559 [09:06<06:25,  1.63it/s]


 60%|█████▉    | 931/1559 [09:06<05:44,  1.82it/s]


 60%|█████▉    | 932/1559 [09:07<06:21,  1.65it/s]


 60%|█████▉    | 933/1559 [09:07<05:52,  1.78it/s]


 60%|█████▉    | 934/1559 [09:08<05:56,  1.75it/s]


 60%|█████▉    | 935/1559 [09:09<06:47,  1.53it/s]


 60%|██████    | 937/1559 [09:09<04:02,  2.57it/s]


 60%|██████    | 938/1559 [09:11<07:16,  1.42it/s]


 60%|██████    | 940/1559 [09:12<06:34,  1.57it/s]


 60%|██████    | 941/1559 [09:12<05:35,  1.84it/s]


 60%|██████    | 942/1559 [09:13<05:51,  1.75it/s]


 60%|██████    | 943/1559 [09:13<06:20,  1.62it/s]


 61%|██████    | 944/1559 [09:14<06:20,  1.61it/s]


 61%|██████    | 945/1559 [09:14<05:00,  2.05it/s]


 61%|██████    | 946/1559 [09:15<06:50,  1.49it/s]


 61%|██████    | 947/1559 [09:15<05:28,  1.86it/s]


 61%|██████    | 948/1559 [09:16<06:23,  1.59it/s]


 61%|██████    | 949/1559 [09:17<06:00,  1.69it/s]


 61%|██████    | 950/1559 [09:17<05:29,  1.85it/s]


 61%|██████    | 951/1559 [09:18<05:52,  1.73it/s]


 61%|██████    | 952/1559 [09:19<07:00,  1.44it/s]


 61%|██████    | 953/1559 [09:19<05:17,  1.91it/s]


 61%|██████    | 954/1559 [09:20<06:47,  1.48it/s]


 61%|██████▏   | 955/1559 [09:20<05:22,  1.87it/s]


 61%|██████▏   | 956/1559 [09:21<06:34,  1.53it/s]


 61%|██████▏   | 957/1559 [09:21<05:41,  1.76it/s]


 61%|██████▏   | 958/1559 [09:22<05:11,  1.93it/s]


 62%|██████▏   | 959/1559 [09:22<05:18,  1.88it/s]


 62%|██████▏   | 960/1559 [09:24<07:10,  1.39it/s]


 62%|██████▏   | 961/1559 [09:24<05:58,  1.67it/s]


 62%|██████▏   | 962/1559 [09:25<06:12,  1.60it/s]


 62%|██████▏   | 963/1559 [09:25<05:39,  1.75it/s]


 62%|██████▏   | 964/1559 [09:26<06:16,  1.58it/s]


 62%|██████▏   | 965/1559 [09:26<05:15,  1.88it/s]


 62%|██████▏   | 966/1559 [09:26<04:39,  2.12it/s]


 62%|██████▏   | 967/1559 [09:27<05:32,  1.78it/s]


 62%|██████▏   | 968/1559 [09:28<06:54,  1.43it/s]


 62%|██████▏   | 969/1559 [09:29<06:22,  1.54it/s]


 62%|██████▏   | 970/1559 [09:30<07:00,  1.40it/s]


 62%|██████▏   | 971/1559 [09:30<05:56,  1.65it/s]


 62%|██████▏   | 972/1559 [09:30<05:26,  1.80it/s]


 62%|██████▏   | 973/1559 [09:31<04:36,  2.12it/s]


 62%|██████▏   | 974/1559 [09:31<04:17,  2.27it/s]


 63%|██████▎   | 975/1559 [09:32<06:26,  1.51it/s]


 63%|██████▎   | 976/1559 [09:33<06:36,  1.47it/s]


 63%|██████▎   | 977/1559 [09:34<06:45,  1.43it/s]


 63%|██████▎   | 978/1559 [09:34<06:20,  1.53it/s]


 63%|██████▎   | 979/1559 [09:35<06:32,  1.48it/s]


 63%|██████▎   | 981/1559 [09:36<04:36,  2.09it/s]


 63%|██████▎   | 982/1559 [09:36<04:13,  2.27it/s]


 63%|██████▎   | 983/1559 [09:37<05:42,  1.68it/s]


 63%|██████▎   | 984/1559 [09:38<06:16,  1.53it/s]


 63%|██████▎   | 985/1559 [09:38<06:27,  1.48it/s]


 63%|██████▎   | 986/1559 [09:39<06:12,  1.54it/s]


 63%|██████▎   | 987/1559 [09:40<06:04,  1.57it/s]


 63%|██████▎   | 989/1559 [09:40<04:33,  2.09it/s]


 64%|██████▎   | 990/1559 [09:40<03:59,  2.37it/s]


 64%|██████▎   | 991/1559 [09:41<05:23,  1.76it/s]


 64%|██████▎   | 992/1559 [09:43<07:01,  1.35it/s]


 64%|██████▎   | 993/1559 [09:43<06:32,  1.44it/s]


 64%|██████▍   | 994/1559 [09:44<05:45,  1.64it/s]


 64%|██████▍   | 995/1559 [09:44<05:48,  1.62it/s]


 64%|██████▍   | 996/1559 [09:44<04:24,  2.12it/s]


 64%|██████▍   | 997/1559 [09:45<05:09,  1.81it/s]


 64%|██████▍   | 998/1559 [09:46<05:10,  1.81it/s]


 64%|██████▍   | 999/1559 [09:47<06:19,  1.48it/s]


 64%|██████▍   | 1000/1559 [09:48<07:46,  1.20it/s]


 64%|██████▍   | 1002/1559 [09:48<04:57,  1.87it/s]


 64%|██████▍   | 1003/1559 [09:49<05:22,  1.72it/s]


 64%|██████▍   | 1004/1559 [09:49<05:09,  1.79it/s]


 64%|██████▍   | 1005/1559 [09:50<04:29,  2.06it/s]


 65%|██████▍   | 1006/1559 [09:51<05:57,  1.54it/s]


 65%|██████▍   | 1007/1559 [09:51<05:22,  1.71it/s]


 65%|██████▍   | 1008/1559 [09:53<07:34,  1.21it/s]


 65%|██████▍   | 1009/1559 [09:53<06:03,  1.51it/s]


 65%|██████▍   | 1010/1559 [09:53<04:57,  1.84it/s]


 65%|██████▍   | 1011/1559 [09:53<04:30,  2.03it/s]


 65%|██████▍   | 1012/1559 [09:54<04:33,  2.00it/s]


 65%|██████▍   | 1013/1559 [09:55<04:35,  1.98it/s]


 65%|██████▌   | 1014/1559 [09:56<05:51,  1.55it/s]


 65%|██████▌   | 1016/1559 [09:57<06:46,  1.33it/s]


 65%|██████▌   | 1017/1559 [09:58<05:41,  1.59it/s]


 65%|██████▌   | 1018/1559 [09:58<04:39,  1.94it/s]


 65%|██████▌   | 1019/1559 [09:58<04:58,  1.81it/s]


 65%|██████▌   | 1020/1559 [09:59<04:35,  1.95it/s]


 65%|██████▌   | 1021/1559 [09:59<04:14,  2.12it/s]


 66%|██████▌   | 1022/1559 [10:00<05:40,  1.57it/s]


 66%|██████▌   | 1023/1559 [10:01<05:37,  1.59it/s]


 66%|██████▌   | 1024/1559 [10:02<07:13,  1.23it/s]


 66%|██████▌   | 1025/1559 [10:02<06:03,  1.47it/s]


 66%|██████▌   | 1027/1559 [10:04<05:45,  1.54it/s]


 66%|██████▌   | 1029/1559 [10:04<04:51,  1.82it/s]


 66%|██████▌   | 1030/1559 [10:05<04:42,  1.87it/s]


 66%|██████▌   | 1031/1559 [10:06<05:07,  1.72it/s]


 66%|██████▌   | 1032/1559 [10:07<06:10,  1.42it/s]

 66%|██████▋   | 1033/1559 [10:07<05:38,  1.55it/s]


 66%|██████▋   | 1035/1559 [10:08<05:17,  1.65it/s]


 67%|██████▋   | 1037/1559 [10:09<04:35,  1.90it/s]


 67%|██████▋   | 1038/1559 [10:10<04:26,  1.96it/s]


 67%|██████▋   | 1039/1559 [10:10<04:31,  1.91it/s]


 67%|██████▋   | 1040/1559 [10:11<06:08,  1.41it/s]


 67%|██████▋   | 1041/1559 [10:12<05:06,  1.69it/s]


 67%|██████▋   | 1042/1559 [10:12<04:20,  1.98it/s]


 67%|██████▋   | 1043/1559 [10:13<05:20,  1.61it/s]


 67%|██████▋   | 1045/1559 [10:14<04:33,  1.88it/s]


 67%|██████▋   | 1046/1559 [10:14<04:21,  1.96it/s]


 67%|██████▋   | 1047/1559 [10:15<04:12,  2.03it/s]


 67%|██████▋   | 1048/1559 [10:16<06:42,  1.27it/s]


 67%|██████▋   | 1050/1559 [10:17<04:34,  1.85it/s]


 67%|██████▋   | 1051/1559 [10:17<05:10,  1.63it/s]


 67%|██████▋   | 1052/1559 [10:18<04:35,  1.84it/s]


 68%|██████▊   | 1053/1559 [10:19<05:50,  1.44it/s]


 68%|██████▊   | 1054/1559 [10:19<04:36,  1.83it/s]


 68%|██████▊   | 1055/1559 [10:20<04:36,  1.82it/s]


 68%|██████▊   | 1056/1559 [10:21<06:20,  1.32it/s]


 68%|██████▊   | 1057/1559 [10:21<05:18,  1.58it/s]


 68%|██████▊   | 1058/1559 [10:21<04:05,  2.04it/s]


 68%|██████▊   | 1059/1559 [10:22<04:23,  1.90it/s]


 68%|██████▊   | 1060/1559 [10:23<05:07,  1.62it/s]


 68%|██████▊   | 1061/1559 [10:24<05:32,  1.50it/s]


 68%|██████▊   | 1063/1559 [10:24<04:13,  1.96it/s]


 68%|██████▊   | 1064/1559 [10:26<05:55,  1.39it/s]


 68%|██████▊   | 1065/1559 [10:26<04:57,  1.66it/s]


 68%|██████▊   | 1066/1559 [10:26<03:49,  2.15it/s]


 68%|██████▊   | 1067/1559 [10:26<04:01,  2.04it/s]


 69%|██████▊   | 1068/1559 [10:27<04:41,  1.74it/s]


 69%|██████▊   | 1069/1559 [10:28<05:10,  1.58it/s]


 69%|██████▊   | 1071/1559 [10:29<03:51,  2.11it/s]


 69%|██████▉   | 1072/1559 [10:30<06:23,  1.27it/s]


 69%|██████▉   | 1073/1559 [10:31<05:03,  1.60it/s]


 69%|██████▉   | 1074/1559 [10:31<04:30,  1.79it/s]


 69%|██████▉   | 1075/1559 [10:31<03:35,  2.24it/s]


 69%|██████▉   | 1076/1559 [10:32<04:25,  1.82it/s]


 69%|██████▉   | 1077/1559 [10:33<04:39,  1.72it/s]


 69%|██████▉   | 1078/1559 [10:33<04:36,  1.74it/s]


 69%|██████▉   | 1079/1559 [10:33<03:50,  2.08it/s]


 69%|██████▉   | 1080/1559 [10:35<07:04,  1.13it/s]


 69%|██████▉   | 1081/1559 [10:35<05:31,  1.44it/s]


 69%|██████▉   | 1082/1559 [10:36<04:30,  1.76it/s]


 69%|██████▉   | 1083/1559 [10:36<03:34,  2.22it/s]


 70%|██████▉   | 1084/1559 [10:37<04:54,  1.62it/s]


 70%|██████▉   | 1085/1559 [10:37<04:50,  1.63it/s]


 70%|██████▉   | 1086/1559 [10:38<04:23,  1.79it/s]


 70%|██████▉   | 1087/1559 [10:38<03:41,  2.14it/s]


 70%|██████▉   | 1088/1559 [10:40<06:51,  1.15it/s]


 70%|██████▉   | 1089/1559 [10:40<05:10,  1.52it/s]


 70%|██████▉   | 1090/1559 [10:41<04:32,  1.72it/s]


 70%|███████   | 1092/1559 [10:42<04:11,  1.86it/s]


 70%|███████   | 1093/1559 [10:42<04:01,  1.93it/s]


 70%|███████   | 1094/1559 [10:42<03:52,  2.00it/s]


 70%|███████   | 1095/1559 [10:43<03:10,  2.44it/s]


 70%|███████   | 1096/1559 [10:45<06:23,  1.21it/s]


 70%|███████   | 1097/1559 [10:45<05:15,  1.46it/s]


 70%|███████   | 1098/1559 [10:45<04:24,  1.74it/s]


 71%|███████   | 1100/1559 [10:46<04:26,  1.73it/s]


 71%|███████   | 1101/1559 [10:46<03:34,  2.14it/s]


 71%|███████   | 1102/1559 [10:47<03:50,  1.98it/s]


 71%|███████   | 1103/1559 [10:47<03:27,  2.20it/s]


 71%|███████   | 1104/1559 [10:49<06:05,  1.24it/s]


 71%|███████   | 1105/1559 [10:50<05:51,  1.29it/s]


 71%|███████   | 1106/1559 [10:50<04:26,  1.70it/s]


 71%|███████   | 1107/1559 [10:50<03:36,  2.09it/s]


 71%|███████   | 1108/1559 [10:51<04:15,  1.77it/s]


 71%|███████   | 1109/1559 [10:51<03:46,  1.99it/s]


 71%|███████   | 1110/1559 [10:52<03:45,  1.99it/s]


 71%|███████▏  | 1111/1559 [10:52<04:12,  1.78it/s]


 71%|███████▏  | 1112/1559 [10:54<07:08,  1.04it/s]


 71%|███████▏  | 1114/1559 [10:55<04:46,  1.55it/s]


 72%|███████▏  | 1115/1559 [10:55<03:53,  1.90it/s]


 72%|███████▏  | 1116/1559 [10:55<03:28,  2.13it/s]


 72%|███████▏  | 1117/1559 [10:56<03:45,  1.96it/s]


 72%|███████▏  | 1118/1559 [10:57<04:15,  1.73it/s]


 72%|███████▏  | 1119/1559 [10:57<04:07,  1.78it/s]


 72%|███████▏  | 1120/1559 [10:59<06:15,  1.17it/s]


 72%|███████▏  | 1121/1559 [10:59<04:50,  1.51it/s]


 72%|███████▏  | 1122/1559 [11:00<04:36,  1.58it/s]


 72%|███████▏  | 1123/1559 [11:00<03:33,  2.04it/s]


 72%|███████▏  | 1124/1559 [11:00<02:51,  2.54it/s]


 72%|███████▏  | 1125/1559 [11:00<03:14,  2.23it/s]


 72%|███████▏  | 1126/1559 [11:01<03:45,  1.92it/s]


 72%|███████▏  | 1127/1559 [11:02<04:00,  1.80it/s]


 72%|███████▏  | 1128/1559 [11:04<06:38,  1.08it/s]


 72%|███████▏  | 1129/1559 [11:04<05:16,  1.36it/s]


 72%|███████▏  | 1130/1559 [11:04<04:26,  1.61it/s]


 73%|███████▎  | 1131/1559 [11:04<03:26,  2.08it/s]


 73%|███████▎  | 1132/1559 [11:05<03:23,  2.10it/s]


 73%|███████▎  | 1133/1559 [11:05<02:58,  2.39it/s]


 73%|███████▎  | 1134/1559 [11:06<04:05,  1.73it/s]


 73%|███████▎  | 1135/1559 [11:07<04:38,  1.52it/s]


 73%|███████▎  | 1136/1559 [11:08<06:24,  1.10it/s]


 73%|███████▎  | 1137/1559 [11:09<05:10,  1.36it/s]


 73%|███████▎  | 1138/1559 [11:09<04:09,  1.69it/s]


 73%|███████▎  | 1139/1559 [11:09<03:38,  1.92it/s]


 73%|███████▎  | 1141/1559 [11:10<02:50,  2.46it/s]


 73%|███████▎  | 1142/1559 [11:11<03:10,  2.19it/s]


 73%|███████▎  | 1143/1559 [11:12<04:21,  1.59it/s]


 73%|███████▎  | 1144/1559 [11:13<05:41,  1.22it/s]


 73%|███████▎  | 1145/1559 [11:14<05:15,  1.31it/s]


 74%|███████▎  | 1146/1559 [11:14<04:21,  1.58it/s]


 74%|███████▎  | 1147/1559 [11:14<03:17,  2.08it/s]


 74%|███████▎  | 1148/1559 [11:14<02:40,  2.56it/s]


 74%|███████▎  | 1149/1559 [11:15<02:41,  2.54it/s]


 74%|███████▍  | 1150/1559 [11:15<02:54,  2.34it/s]


 74%|███████▍  | 1151/1559 [11:16<04:11,  1.62it/s]


 74%|███████▍  | 1152/1559 [11:18<05:41,  1.19it/s]


 74%|███████▍  | 1153/1559 [11:18<05:10,  1.31it/s]


 74%|███████▍  | 1154/1559 [11:19<04:28,  1.51it/s]


 74%|███████▍  | 1155/1559 [11:19<03:38,  1.85it/s]


 74%|███████▍  | 1156/1559 [11:19<03:14,  2.07it/s]


 74%|███████▍  | 1157/1559 [11:19<02:33,  2.63it/s]


 74%|███████▍  | 1158/1559 [11:20<03:19,  2.01it/s]


 74%|███████▍  | 1159/1559 [11:21<03:38,  1.83it/s]


 74%|███████▍  | 1160/1559 [11:22<05:20,  1.24it/s]


 74%|███████▍  | 1161/1559 [11:23<05:10,  1.28it/s]


 75%|███████▍  | 1162/1559 [11:23<04:39,  1.42it/s]


 75%|███████▍  | 1163/1559 [11:24<04:12,  1.57it/s]


 75%|███████▍  | 1164/1559 [11:24<03:14,  2.04it/s]


 75%|███████▍  | 1165/1559 [11:24<02:56,  2.24it/s]


 75%|███████▍  | 1166/1559 [11:25<02:50,  2.31it/s]


 75%|███████▍  | 1167/1559 [11:26<04:08,  1.58it/s]


 75%|███████▍  | 1168/1559 [11:27<04:36,  1.41it/s]


 75%|███████▍  | 1169/1559 [11:27<04:36,  1.41it/s]


 75%|███████▌  | 1170/1559 [11:28<04:31,  1.43it/s]


 75%|███████▌  | 1171/1559 [11:29<03:55,  1.65it/s]


 75%|███████▌  | 1172/1559 [11:29<03:47,  1.70it/s]

 75%|███████▌  | 1174/1559 [11:29<02:38,  2.42it/s]


 75%|███████▌  | 1175/1559 [11:31<03:36,  1.77it/s]


 75%|███████▌  | 1176/1559 [11:31<03:54,  1.63it/s]


 75%|███████▌  | 1177/1559 [11:32<04:03,  1.57it/s]


 76%|███████▌  | 1178/1559 [11:33<04:23,  1.44it/s]


 76%|███████▌  | 1179/1559 [11:33<03:41,  1.72it/s]


 76%|███████▌  | 1180/1559 [11:34<03:53,  1.62it/s]


 76%|███████▌  | 1182/1559 [11:34<02:17,  2.74it/s]


 76%|███████▌  | 1183/1559 [11:35<03:21,  1.87it/s]


 76%|███████▌  | 1184/1559 [11:36<03:46,  1.66it/s]


 76%|███████▌  | 1185/1559 [11:37<04:07,  1.51it/s]


 76%|███████▌  | 1186/1559 [11:38<04:32,  1.37it/s]


 76%|███████▌  | 1187/1559 [11:38<04:16,  1.45it/s]


 76%|███████▌  | 1188/1559 [11:39<03:48,  1.62it/s]


 76%|███████▋  | 1189/1559 [11:39<03:35,  1.71it/s]


 76%|███████▋  | 1190/1559 [11:39<02:55,  2.11it/s]


 76%|███████▋  | 1191/1559 [11:40<03:25,  1.79it/s]


 76%|███████▋  | 1192/1559 [11:40<02:51,  2.14it/s]


 77%|███████▋  | 1193/1559 [11:41<03:36,  1.69it/s]


 77%|███████▋  | 1194/1559 [11:43<05:02,  1.21it/s]


 77%|███████▋  | 1195/1559 [11:43<03:43,  1.63it/s]


 77%|███████▋  | 1196/1559 [11:43<03:30,  1.72it/s]


 77%|███████▋  | 1197/1559 [11:44<03:17,  1.84it/s]


 77%|███████▋  | 1198/1559 [11:44<03:03,  1.97it/s]


 77%|███████▋  | 1199/1559 [11:45<03:26,  1.75it/s]


 77%|███████▋  | 1200/1559 [11:45<02:44,  2.18it/s]


 77%|███████▋  | 1201/1559 [11:46<03:28,  1.72it/s]


 77%|███████▋  | 1202/1559 [11:47<04:52,  1.22it/s]


 77%|███████▋  | 1204/1559 [11:48<03:08,  1.89it/s]


 77%|███████▋  | 1205/1559 [11:48<03:05,  1.91it/s]


 77%|███████▋  | 1206/1559 [11:49<03:10,  1.85it/s]


 77%|███████▋  | 1207/1559 [11:49<03:31,  1.66it/s]


 77%|███████▋  | 1208/1559 [11:50<02:58,  1.96it/s]


 78%|███████▊  | 1209/1559 [11:50<03:11,  1.83it/s]


 78%|███████▊  | 1210/1559 [11:52<04:41,  1.24it/s]


 78%|███████▊  | 1212/1559 [11:52<03:24,  1.69it/s]


 78%|███████▊  | 1213/1559 [11:53<03:44,  1.54it/s]


 78%|███████▊  | 1215/1559 [11:55<03:53,  1.47it/s]


 78%|███████▊  | 1216/1559 [11:55<03:12,  1.78it/s]


 78%|███████▊  | 1217/1559 [11:55<02:45,  2.07it/s]


 78%|███████▊  | 1218/1559 [11:56<03:43,  1.53it/s]


 78%|███████▊  | 1219/1559 [11:57<03:37,  1.56it/s]


 78%|███████▊  | 1221/1559 [11:58<03:26,  1.64it/s]


 78%|███████▊  | 1222/1559 [11:58<03:01,  1.86it/s]


 78%|███████▊  | 1223/1559 [11:59<03:51,  1.45it/s]


 79%|███████▊  | 1224/1559 [12:00<03:17,  1.69it/s]


 79%|███████▊  | 1225/1559 [12:00<02:40,  2.08it/s]


 79%|███████▊  | 1226/1559 [12:01<03:12,  1.73it/s]


 79%|███████▊  | 1227/1559 [12:02<03:28,  1.59it/s]


 79%|███████▉  | 1229/1559 [12:03<03:12,  1.72it/s]


 79%|███████▉  | 1230/1559 [12:03<03:00,  1.82it/s]


 79%|███████▉  | 1231/1559 [12:04<03:35,  1.52it/s]


 79%|███████▉  | 1232/1559 [12:04<02:55,  1.86it/s]


 79%|███████▉  | 1233/1559 [12:04<02:26,  2.23it/s]


 79%|███████▉  | 1234/1559 [12:05<03:00,  1.80it/s]


 79%|███████▉  | 1235/1559 [12:06<03:22,  1.60it/s]


 79%|███████▉  | 1236/1559 [12:06<03:00,  1.78it/s]


 79%|███████▉  | 1237/1559 [12:07<03:33,  1.51it/s]


 79%|███████▉  | 1238/1559 [12:08<03:03,  1.75it/s]


 79%|███████▉  | 1239/1559 [12:09<03:30,  1.52it/s]


 80%|███████▉  | 1240/1559 [12:09<03:25,  1.55it/s]


 80%|███████▉  | 1242/1559 [12:10<03:22,  1.56it/s]


 80%|███████▉  | 1244/1559 [12:11<03:01,  1.73it/s]


 80%|███████▉  | 1245/1559 [12:12<02:47,  1.87it/s]


 80%|███████▉  | 1246/1559 [12:13<03:00,  1.73it/s]


 80%|███████▉  | 1247/1559 [12:14<03:39,  1.42it/s]


 80%|████████  | 1248/1559 [12:14<03:06,  1.66it/s]


 80%|████████  | 1249/1559 [12:14<02:30,  2.06it/s]


 80%|████████  | 1250/1559 [12:15<03:14,  1.59it/s]


 80%|████████  | 1251/1559 [12:15<02:31,  2.03it/s]


 80%|████████  | 1252/1559 [12:16<02:57,  1.73it/s]


 80%|████████  | 1253/1559 [12:16<02:44,  1.85it/s]


 80%|████████  | 1254/1559 [12:17<03:22,  1.51it/s]


 81%|████████  | 1255/1559 [12:18<03:28,  1.46it/s]


 81%|████████  | 1256/1559 [12:18<02:44,  1.85it/s]


 81%|████████  | 1257/1559 [12:19<02:28,  2.03it/s]


 81%|████████  | 1258/1559 [12:20<03:08,  1.60it/s]


 81%|████████  | 1259/1559 [12:20<02:26,  2.05it/s]


 81%|████████  | 1260/1559 [12:21<02:56,  1.70it/s]


 81%|████████  | 1261/1559 [12:21<02:30,  1.98it/s]


 81%|████████  | 1262/1559 [12:22<03:37,  1.37it/s]


 81%|████████  | 1263/1559 [12:23<03:15,  1.51it/s]


 81%|████████  | 1264/1559 [12:23<02:35,  1.90it/s]


 81%|████████  | 1265/1559 [12:23<02:23,  2.05it/s]


 81%|████████  | 1266/1559 [12:24<02:59,  1.64it/s]


 81%|████████▏ | 1267/1559 [12:25<02:30,  1.94it/s]


 81%|████████▏ | 1268/1559 [12:26<03:14,  1.50it/s]


 81%|████████▏ | 1269/1559 [12:26<02:30,  1.93it/s]


 81%|████████▏ | 1270/1559 [12:27<03:29,  1.38it/s]


 82%|████████▏ | 1271/1559 [12:27<02:58,  1.62it/s]


 82%|████████▏ | 1272/1559 [12:28<02:20,  2.04it/s]


 82%|████████▏ | 1273/1559 [12:28<02:16,  2.09it/s]


 82%|████████▏ | 1274/1559 [12:29<03:25,  1.39it/s]


 82%|████████▏ | 1276/1559 [12:31<03:13,  1.46it/s]


 82%|████████▏ | 1277/1559 [12:31<02:32,  1.85it/s]


 82%|████████▏ | 1278/1559 [12:32<03:14,  1.45it/s]


 82%|████████▏ | 1280/1559 [12:32<02:21,  1.97it/s]


 82%|████████▏ | 1281/1559 [12:32<02:00,  2.30it/s]


 82%|████████▏ | 1282/1559 [12:34<03:13,  1.43it/s]


 82%|████████▏ | 1284/1559 [12:35<02:55,  1.56it/s]


 82%|████████▏ | 1285/1559 [12:35<02:30,  1.82it/s]


 82%|████████▏ | 1286/1559 [12:36<03:08,  1.45it/s]


 83%|████████▎ | 1288/1559 [12:37<02:15,  2.00it/s]


 83%|████████▎ | 1289/1559 [12:37<02:03,  2.18it/s]


 83%|████████▎ | 1290/1559 [12:39<03:02,  1.47it/s]


 83%|████████▎ | 1292/1559 [12:40<02:39,  1.67it/s]


 83%|████████▎ | 1293/1559 [12:40<02:36,  1.70it/s]


 83%|████████▎ | 1294/1559 [12:41<03:19,  1.33it/s]


 83%|████████▎ | 1296/1559 [12:42<02:09,  2.03it/s]


 83%|████████▎ | 1297/1559 [12:42<02:03,  2.13it/s]


 83%|████████▎ | 1298/1559 [12:43<02:43,  1.59it/s]


 83%|████████▎ | 1299/1559 [12:43<02:16,  1.90it/s]


 83%|████████▎ | 1300/1559 [12:44<02:51,  1.51it/s]


 83%|████████▎ | 1301/1559 [12:45<02:32,  1.69it/s]


 84%|████████▎ | 1302/1559 [12:46<03:13,  1.33it/s]


 84%|████████▎ | 1303/1559 [12:46<02:46,  1.53it/s]


 84%|████████▎ | 1304/1559 [12:47<02:19,  1.82it/s]


 84%|████████▎ | 1305/1559 [12:47<01:52,  2.26it/s]


 84%|████████▍ | 1306/1559 [12:48<02:42,  1.55it/s]


 84%|████████▍ | 1307/1559 [12:48<02:05,  2.01it/s]


 84%|████████▍ | 1308/1559 [12:49<02:21,  1.77it/s]


 84%|████████▍ | 1309/1559 [12:50<02:51,  1.46it/s]


 84%|████████▍ | 1310/1559 [12:51<03:02,  1.36it/s]


 84%|████████▍ | 1311/1559 [12:51<02:33,  1.62it/s]


 84%|████████▍ | 1312/1559 [12:51<02:09,  1.90it/s]


 84%|████████▍ | 1313/1559 [12:51<01:40,  2.44it/s]


 84%|████████▍ | 1314/1559 [12:53<02:55,  1.39it/s]


 84%|████████▍ | 1316/1559 [12:53<01:54,  2.12it/s]


 84%|████████▍ | 1317/1559 [12:55<03:10,  1.27it/s]


 85%|████████▍ | 1318/1559 [12:55<02:35,  1.55it/s]

 85%|████████▍ | 1319/1559 [12:55<02:09,  1.86it/s]


 85%|████████▍ | 1320/1559 [12:56<02:03,  1.93it/s]


 85%|████████▍ | 1321/1559 [12:57<02:19,  1.71it/s]


 85%|████████▍ | 1322/1559 [12:57<02:30,  1.58it/s]


 85%|████████▍ | 1323/1559 [12:58<02:07,  1.85it/s]


 85%|████████▍ | 1324/1559 [12:58<02:15,  1.74it/s]


 85%|████████▍ | 1325/1559 [13:00<03:06,  1.25it/s]


 85%|████████▌ | 1326/1559 [13:00<02:29,  1.56it/s]


 85%|████████▌ | 1327/1559 [13:00<01:52,  2.07it/s]


 85%|████████▌ | 1328/1559 [13:01<01:46,  2.18it/s]


 85%|████████▌ | 1329/1559 [13:02<02:29,  1.53it/s]


 85%|████████▌ | 1330/1559 [13:02<02:26,  1.56it/s]


 85%|████████▌ | 1331/1559 [13:03<02:02,  1.87it/s]


 85%|████████▌ | 1332/1559 [13:03<02:04,  1.83it/s]


 86%|████████▌ | 1333/1559 [13:04<02:46,  1.36it/s]


 86%|████████▌ | 1334/1559 [13:05<02:13,  1.68it/s]


 86%|████████▌ | 1335/1559 [13:05<01:51,  2.02it/s]


 86%|████████▌ | 1336/1559 [13:05<01:41,  2.19it/s]


 86%|████████▌ | 1337/1559 [13:06<02:27,  1.51it/s]


 86%|████████▌ | 1338/1559 [13:07<02:10,  1.69it/s]


 86%|████████▌ | 1339/1559 [13:07<01:51,  1.97it/s]


 86%|████████▌ | 1340/1559 [13:08<01:49,  2.00it/s]


 86%|████████▌ | 1341/1559 [13:09<02:43,  1.33it/s]


 86%|████████▌ | 1342/1559 [13:09<02:13,  1.62it/s]


 86%|████████▌ | 1343/1559 [13:09<01:50,  1.95it/s]


 86%|████████▌ | 1344/1559 [13:10<01:39,  2.15it/s]


 86%|████████▋ | 1345/1559 [13:11<02:23,  1.49it/s]


 86%|████████▋ | 1346/1559 [13:11<02:09,  1.65it/s]


 86%|████████▋ | 1347/1559 [13:12<01:37,  2.18it/s]


 86%|████████▋ | 1348/1559 [13:13<02:21,  1.49it/s]


 87%|████████▋ | 1349/1559 [13:14<02:57,  1.18it/s]


 87%|████████▋ | 1350/1559 [13:14<02:16,  1.53it/s]


 87%|████████▋ | 1351/1559 [13:15<01:58,  1.76it/s]


 87%|████████▋ | 1352/1559 [13:15<01:40,  2.07it/s]


 87%|████████▋ | 1353/1559 [13:16<02:41,  1.28it/s]


 87%|████████▋ | 1354/1559 [13:16<02:00,  1.70it/s]


 87%|████████▋ | 1355/1559 [13:17<01:44,  1.95it/s]


 87%|████████▋ | 1356/1559 [13:18<02:06,  1.60it/s]


 87%|████████▋ | 1357/1559 [13:19<02:24,  1.40it/s]


 87%|████████▋ | 1358/1559 [13:19<02:17,  1.46it/s]


 87%|████████▋ | 1360/1559 [13:20<01:42,  1.95it/s]


 87%|████████▋ | 1361/1559 [13:21<02:12,  1.50it/s]


 87%|████████▋ | 1362/1559 [13:21<01:54,  1.72it/s]


 87%|████████▋ | 1363/1559 [13:22<01:35,  2.05it/s]


 87%|████████▋ | 1364/1559 [13:22<01:56,  1.68it/s]


 88%|████████▊ | 1365/1559 [13:23<02:08,  1.51it/s]


 88%|████████▊ | 1366/1559 [13:24<01:55,  1.66it/s]


 88%|████████▊ | 1367/1559 [13:24<01:28,  2.17it/s]


 88%|████████▊ | 1368/1559 [13:24<01:33,  2.04it/s]


 88%|████████▊ | 1369/1559 [13:26<02:25,  1.31it/s]


 88%|████████▊ | 1370/1559 [13:26<01:49,  1.72it/s]


 88%|████████▊ | 1371/1559 [13:26<01:27,  2.14it/s]


 88%|████████▊ | 1372/1559 [13:27<01:48,  1.73it/s]


 88%|████████▊ | 1373/1559 [13:28<01:58,  1.57it/s]


 88%|████████▊ | 1374/1559 [13:29<02:04,  1.48it/s]


 88%|████████▊ | 1375/1559 [13:29<02:02,  1.51it/s]


 88%|████████▊ | 1376/1559 [13:29<01:37,  1.88it/s]


 88%|████████▊ | 1377/1559 [13:30<02:06,  1.44it/s]


 88%|████████▊ | 1378/1559 [13:31<01:40,  1.81it/s]


 88%|████████▊ | 1379/1559 [13:31<01:45,  1.70it/s]


 89%|████████▊ | 1380/1559 [13:32<01:52,  1.59it/s]


 89%|████████▊ | 1381/1559 [13:32<01:40,  1.78it/s]


 89%|████████▊ | 1382/1559 [13:34<02:15,  1.30it/s]


 89%|████████▊ | 1383/1559 [13:34<01:40,  1.75it/s]


 89%|████████▉ | 1384/1559 [13:34<01:32,  1.90it/s]


 89%|████████▉ | 1385/1559 [13:35<01:45,  1.64it/s]


 89%|████████▉ | 1386/1559 [13:36<01:42,  1.69it/s]


 89%|████████▉ | 1387/1559 [13:36<01:39,  1.72it/s]


 89%|████████▉ | 1388/1559 [13:37<01:42,  1.67it/s]


 89%|████████▉ | 1389/1559 [13:37<01:35,  1.78it/s]


 89%|████████▉ | 1390/1559 [13:38<01:59,  1.42it/s]


 89%|████████▉ | 1391/1559 [13:39<01:37,  1.71it/s]


 89%|████████▉ | 1392/1559 [13:39<01:17,  2.16it/s]


 89%|████████▉ | 1393/1559 [13:40<01:36,  1.72it/s]


 89%|████████▉ | 1394/1559 [13:40<01:27,  1.89it/s]


 89%|████████▉ | 1395/1559 [13:41<01:36,  1.70it/s]


 90%|████████▉ | 1396/1559 [13:41<01:27,  1.85it/s]


 90%|████████▉ | 1397/1559 [13:42<01:35,  1.70it/s]


 90%|████████▉ | 1398/1559 [13:43<02:08,  1.26it/s]


 90%|████████▉ | 1401/1559 [13:44<01:33,  1.70it/s]


 90%|████████▉ | 1402/1559 [13:45<01:26,  1.82it/s]


 90%|████████▉ | 1403/1559 [13:45<01:25,  1.82it/s]


 90%|█████████ | 1404/1559 [13:46<01:38,  1.58it/s]


 90%|█████████ | 1405/1559 [13:47<01:24,  1.82it/s]


 90%|█████████ | 1406/1559 [13:48<02:00,  1.27it/s]


 90%|█████████ | 1409/1559 [13:49<01:32,  1.61it/s]


 90%|█████████ | 1410/1559 [13:50<01:24,  1.75it/s]


 91%|█████████ | 1411/1559 [13:50<01:22,  1.80it/s]


 91%|█████████ | 1412/1559 [13:51<01:21,  1.80it/s]


 91%|█████████ | 1413/1559 [13:51<01:09,  2.09it/s]


 91%|█████████ | 1414/1559 [13:53<01:45,  1.37it/s]


 91%|█████████ | 1415/1559 [13:53<01:26,  1.67it/s]


 91%|█████████ | 1417/1559 [13:54<01:28,  1.60it/s]


 91%|█████████ | 1418/1559 [13:55<01:19,  1.78it/s]


 91%|█████████ | 1419/1559 [13:55<01:25,  1.64it/s]


 91%|█████████ | 1420/1559 [13:56<01:10,  1.97it/s]


 91%|█████████ | 1421/1559 [13:56<01:12,  1.91it/s]


 91%|█████████ | 1422/1559 [13:57<01:35,  1.44it/s]


 91%|█████████▏| 1423/1559 [13:57<01:14,  1.83it/s]


 91%|█████████▏| 1424/1559 [13:58<00:57,  2.33it/s]


 91%|█████████▏| 1425/1559 [13:59<01:30,  1.48it/s]


 91%|█████████▏| 1426/1559 [13:59<01:24,  1.58it/s]


 92%|█████████▏| 1427/1559 [14:00<01:21,  1.62it/s]


 92%|█████████▏| 1428/1559 [14:01<01:22,  1.58it/s]


 92%|█████████▏| 1430/1559 [14:02<01:19,  1.62it/s]


 92%|█████████▏| 1431/1559 [14:02<01:12,  1.77it/s]


 92%|█████████▏| 1432/1559 [14:03<01:14,  1.70it/s]


 92%|█████████▏| 1433/1559 [14:04<01:37,  1.30it/s]


 92%|█████████▏| 1435/1559 [14:05<01:05,  1.89it/s]


 92%|█████████▏| 1436/1559 [14:05<01:13,  1.68it/s]


 92%|█████████▏| 1437/1559 [14:06<01:08,  1.77it/s]


 92%|█████████▏| 1438/1559 [14:06<01:09,  1.74it/s]


 92%|█████████▏| 1439/1559 [14:07<01:14,  1.60it/s]


 92%|█████████▏| 1440/1559 [14:08<01:10,  1.70it/s]


 92%|█████████▏| 1441/1559 [14:09<01:30,  1.31it/s]


 92%|█████████▏| 1442/1559 [14:09<01:06,  1.75it/s]


 93%|█████████▎| 1443/1559 [14:09<00:51,  2.25it/s]


 93%|█████████▎| 1444/1559 [14:10<01:00,  1.89it/s]


 93%|█████████▎| 1445/1559 [14:11<01:06,  1.72it/s]


 93%|█████████▎| 1446/1559 [14:11<01:03,  1.79it/s]


 93%|█████████▎| 1447/1559 [14:12<01:08,  1.64it/s]


 93%|█████████▎| 1448/1559 [14:12<01:00,  1.85it/s]


 93%|█████████▎| 1449/1559 [14:13<01:21,  1.36it/s]


 93%|█████████▎| 1450/1559 [14:14<01:03,  1.73it/s]


 93%|█████████▎| 1452/1559 [14:14<00:52,  2.04it/s]


 93%|█████████▎| 1453/1559 [14:15<01:03,  1.66it/s]


 93%|█████████▎| 1454/1559 [14:16<00:55,  1.88it/s]


 93%|█████████▎| 1455/1559 [14:16<01:00,  1.71it/s]


 93%|█████████▎| 1456/1559 [14:17<00:54,  1.88it/s]


 93%|█████████▎| 1457/1559 [14:18<01:10,  1.44it/s]

 94%|█████████▎| 1458/1559 [14:18<00:56,  1.80it/s]


 94%|█████████▎| 1459/1559 [14:18<00:44,  2.27it/s]


 94%|█████████▎| 1460/1559 [14:19<00:59,  1.67it/s]


 94%|█████████▎| 1461/1559 [14:20<01:03,  1.55it/s]


 94%|█████████▍| 1462/1559 [14:20<00:49,  1.95it/s]


 94%|█████████▍| 1463/1559 [14:21<01:00,  1.58it/s]


 94%|█████████▍| 1464/1559 [14:22<01:00,  1.56it/s]


 94%|█████████▍| 1465/1559 [14:22<00:58,  1.62it/s]


 94%|█████████▍| 1466/1559 [14:23<00:53,  1.75it/s]


 94%|█████████▍| 1467/1559 [14:23<00:50,  1.82it/s]


 94%|█████████▍| 1468/1559 [14:24<01:01,  1.47it/s]


 94%|█████████▍| 1469/1559 [14:25<00:58,  1.54it/s]


 94%|█████████▍| 1470/1559 [14:25<00:54,  1.62it/s]


 94%|█████████▍| 1471/1559 [14:26<01:04,  1.37it/s]


 94%|█████████▍| 1472/1559 [14:26<00:48,  1.78it/s]


 94%|█████████▍| 1473/1559 [14:28<01:04,  1.33it/s]


 95%|█████████▍| 1475/1559 [14:28<00:45,  1.86it/s]


 95%|█████████▍| 1476/1559 [14:29<00:55,  1.49it/s]


 95%|█████████▍| 1477/1559 [14:30<00:58,  1.40it/s]


 95%|█████████▍| 1479/1559 [14:32<00:57,  1.40it/s]


 95%|█████████▍| 1480/1559 [14:32<00:45,  1.73it/s]


 95%|█████████▍| 1481/1559 [14:33<00:57,  1.36it/s]


 95%|█████████▌| 1482/1559 [14:33<00:50,  1.53it/s]


 95%|█████████▌| 1483/1559 [14:34<00:43,  1.74it/s]


 95%|█████████▌| 1484/1559 [14:35<01:01,  1.22it/s]


 95%|█████████▌| 1485/1559 [14:36<00:54,  1.35it/s]


 95%|█████████▌| 1487/1559 [14:37<00:45,  1.57it/s]


 95%|█████████▌| 1488/1559 [14:37<00:36,  1.93it/s]


 96%|█████████▌| 1489/1559 [14:38<00:47,  1.46it/s]


 96%|█████████▌| 1490/1559 [14:38<00:37,  1.84it/s]


 96%|█████████▌| 1491/1559 [14:39<00:34,  2.00it/s]


 96%|█████████▌| 1492/1559 [14:40<00:46,  1.43it/s]


 96%|█████████▌| 1493/1559 [14:40<00:43,  1.53it/s]


 96%|█████████▌| 1494/1559 [14:41<00:33,  1.93it/s]


 96%|█████████▌| 1495/1559 [14:41<00:38,  1.68it/s]


 96%|█████████▌| 1496/1559 [14:42<00:33,  1.88it/s]


 96%|█████████▌| 1497/1559 [14:43<00:43,  1.43it/s]


 96%|█████████▌| 1499/1559 [14:43<00:25,  2.32it/s]


 96%|█████████▌| 1500/1559 [14:44<00:37,  1.56it/s]


 96%|█████████▋| 1501/1559 [14:45<00:41,  1.40it/s]


 96%|█████████▋| 1503/1559 [14:46<00:34,  1.63it/s]


 97%|█████████▋| 1505/1559 [14:47<00:32,  1.65it/s]


 97%|█████████▋| 1506/1559 [14:47<00:26,  2.00it/s]


 97%|█████████▋| 1507/1559 [14:48<00:22,  2.30it/s]


 97%|█████████▋| 1508/1559 [14:49<00:34,  1.48it/s]


 97%|█████████▋| 1509/1559 [14:50<00:34,  1.44it/s]


 97%|█████████▋| 1511/1559 [14:51<00:30,  1.57it/s]


 97%|█████████▋| 1512/1559 [14:51<00:24,  1.91it/s]


 97%|█████████▋| 1513/1559 [14:52<00:28,  1.60it/s]


 97%|█████████▋| 1514/1559 [14:52<00:22,  1.98it/s]


 97%|█████████▋| 1516/1559 [14:54<00:32,  1.30it/s]


 97%|█████████▋| 1517/1559 [14:55<00:26,  1.60it/s]


 97%|█████████▋| 1519/1559 [14:56<00:24,  1.65it/s]


 97%|█████████▋| 1520/1559 [14:56<00:23,  1.63it/s]


 98%|█████████▊| 1521/1559 [14:57<00:22,  1.69it/s]


 98%|█████████▊| 1522/1559 [14:57<00:19,  1.90it/s]


 98%|█████████▊| 1523/1559 [14:57<00:14,  2.41it/s]


 98%|█████████▊| 1524/1559 [15:00<00:31,  1.11it/s]


 98%|█████████▊| 1526/1559 [15:00<00:19,  1.71it/s]


 98%|█████████▊| 1527/1559 [15:01<00:22,  1.43it/s]


 98%|█████████▊| 1528/1559 [15:01<00:18,  1.65it/s]


 98%|█████████▊| 1529/1559 [15:02<00:17,  1.74it/s]


 98%|█████████▊| 1530/1559 [15:02<00:15,  1.83it/s]


 98%|█████████▊| 1531/1559 [15:02<00:11,  2.37it/s]


 98%|█████████▊| 1532/1559 [15:05<00:25,  1.07it/s]


 98%|█████████▊| 1533/1559 [15:05<00:21,  1.22it/s]


 98%|█████████▊| 1534/1559 [15:05<00:15,  1.59it/s]


 98%|█████████▊| 1535/1559 [15:06<00:16,  1.50it/s]


 99%|█████████▊| 1536/1559 [15:07<00:14,  1.57it/s]


 99%|█████████▊| 1537/1559 [15:07<00:13,  1.64it/s]


 99%|█████████▊| 1538/1559 [15:07<00:10,  1.95it/s]


 99%|█████████▊| 1539/1559 [15:08<00:08,  2.33it/s]


 99%|█████████▉| 1540/1559 [15:10<00:20,  1.09s/it]


 99%|█████████▉| 1541/1559 [15:11<00:15,  1.15it/s]


 99%|█████████▉| 1543/1559 [15:11<00:08,  1.80it/s]


 99%|█████████▉| 1544/1559 [15:12<00:09,  1.58it/s]


 99%|█████████▉| 1545/1559 [15:12<00:08,  1.73it/s]


 99%|█████████▉| 1546/1559 [15:13<00:07,  1.63it/s]


 99%|█████████▉| 1548/1559 [15:16<00:10,  1.05it/s]


 99%|█████████▉| 1551/1559 [15:16<00:04,  1.84it/s]


100%|█████████▉| 1552/1559 [15:17<00:04,  1.70it/s]


100%|█████████▉| 1553/1559 [15:18<00:03,  1.71it/s]


100%|█████████▉| 1554/1559 [15:18<00:02,  1.69it/s]


100%|█████████▉| 1555/1559 [15:18<00:01,  2.06it/s]


100%|█████████▉| 1556/1559 [15:21<00:03,  1.06s/it]


100%|█████████▉| 1557/1559 [15:21<00:01,  1.19it/s]


100%|█████████▉| 1558/1559 [15:21<00:00,  1.58it/s]


100%|██████████| 1559/1559 [15:21<00:00,  1.69it/s]
Families: 100%|██████████| 3/3 [24:13<00:00, 484.49s/it]

Runtime: 1453.485510 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 3:   0%|          | 0/144 [00:00<?, ?it/s]



  0%|          | 0/144 [00:00<?, ?it/s]



  1%|          | 1/144 [00:02<04:48,  2.02s/it]



  3%|▎         | 5/144 [00:02<00:46,  2.99it/s]



  6%|▋         | 9/144 [00:04<00:55,  2.44it/s]



  8%|▊         | 12/144 [00:04<00:35,  3.69it/s]



 10%|▉         | 14/144 [00:04<00:29,  4.45it/s]



 12%|█▏        | 17/144 [00:05<00:39,  3.19it/s]



 14%|█▍        | 20/144 [00:05<00:28,  4.37it/s]



 15%|█▌        | 22/144 [00:06<00:24,  4.97it/s]



 17%|█▋        | 24/144 [00:06<00:19,  6.07it/s]



 18%|█▊        | 26/144 [00:07<00:37,  3.16it/s]



 20%|██        | 29/144 [00:07<00:25,  4.54it/s]



 22%|██▏       | 31/144 [00:08<00:22,  5.11it/s]



 23%|██▎       | 33/144 [00:09<00:34,  3.21it/s]



 24%|██▎       | 34/144 [00:09<00:32,  3.43it/s]



 25%|██▌       | 36/144 [00:09<00:23,  4.51it/s]



 26%|██▋       | 38/144 [00:10<00:20,  5.16it/s]



 27%|██▋       | 39/144 [00:10<00:18,  5.65it/s]



 28%|██▊       | 41/144 [00:11<00:32,  3.21it/s]



 29%|██▉       | 42/144 [00:11<00:29,  3.40it/s]



 30%|██▉       | 43/144 [00:11<00:29,  3.48it/s]



 32%|███▏      | 46/144 [00:11<00:17,  5.74it/s]



 33%|███▎      | 48/144 [00:12<00:15,  6.33it/s]



 34%|███▍      | 49/144 [00:13<00:28,  3.28it/s]



 35%|███▍      | 50/144 [00:13<00:28,  3.32it/s]



 35%|███▌      | 51/144 [00:13<00:27,  3.37it/s]



 36%|███▌      | 52/144 [00:13<00:24,  3.76it/s]



 39%|███▉      | 56/144 [00:14<00:13,  6.31it/s]



 40%|███▉      | 57/144 [00:14<00:21,  4.02it/s]



 40%|████      | 58/144 [00:15<00:22,  3.89it/s]



 41%|████      | 59/144 [00:15<00:22,  3.85it/s]



 42%|████▏     | 60/144 [00:15<00:21,  3.97it/s]



 44%|████▍     | 63/144 [00:15<00:11,  6.92it/s]



 45%|████▌     | 65/144 [00:16<00:19,  4.07it/s]



 46%|████▌     | 66/144 [00:16<00:18,  4.24it/s]



 47%|████▋     | 67/144 [00:17<00:18,  4.11it/s]



 47%|████▋     | 68/144 [00:17<00:18,  4.19it/s]



 48%|████▊     | 69/144 [00:17<00:16,  4.46it/s]



 50%|█████     | 72/144 [00:17<00:11,  6.09it/s]



 51%|█████     | 73/144 [00:18<00:17,  4.17it/s]



 51%|█████▏    | 74/144 [00:18<00:16,  4.36it/s]



 52%|█████▏    | 75/144 [00:19<00:21,  3.27it/s]



 53%|█████▎    | 76/144 [00:19<00:17,  3.87it/s]



 54%|█████▍    | 78/144 [00:19<00:11,  5.70it/s]



 56%|█████▌    | 80/144 [00:19<00:11,  5.46it/s]



 56%|█████▋    | 81/144 [00:20<00:14,  4.50it/s]



 57%|█████▋    | 82/144 [00:20<00:14,  4.16it/s]



 58%|█████▊    | 83/144 [00:20<00:18,  3.35it/s]



 59%|█████▉    | 85/144 [00:21<00:12,  4.56it/s]



 60%|██████    | 87/144 [00:21<00:10,  5.62it/s]



 61%|██████    | 88/144 [00:21<00:10,  5.53it/s]



 62%|██████▏   | 89/144 [00:21<00:12,  4.35it/s]



 62%|██████▎   | 90/144 [00:22<00:13,  3.90it/s]



 63%|██████▎   | 91/144 [00:22<00:16,  3.19it/s]



 64%|██████▍   | 92/144 [00:23<00:15,  3.42it/s]



 65%|██████▌   | 94/144 [00:23<00:09,  5.36it/s]



 66%|██████▌   | 95/144 [00:23<00:10,  4.66it/s]



 67%|██████▋   | 97/144 [00:23<00:10,  4.69it/s]



 68%|██████▊   | 98/144 [00:24<00:09,  4.62it/s]



 69%|██████▉   | 99/144 [00:24<00:12,  3.60it/s]



 69%|██████▉   | 100/144 [00:24<00:12,  3.45it/s]



 71%|███████   | 102/144 [00:24<00:08,  5.17it/s]



 72%|███████▏  | 103/144 [00:25<00:10,  3.80it/s]



 73%|███████▎  | 105/144 [00:25<00:08,  4.52it/s]



 74%|███████▎  | 106/144 [00:26<00:09,  4.04it/s]



 74%|███████▍  | 107/144 [00:26<00:12,  3.07it/s]



 76%|███████▌  | 109/144 [00:26<00:07,  4.41it/s]



 77%|███████▋  | 111/144 [00:27<00:07,  4.53it/s]



 78%|███████▊  | 112/144 [00:27<00:06,  5.02it/s]



 78%|███████▊  | 113/144 [00:27<00:07,  4.28it/s]



 79%|███████▉  | 114/144 [00:28<00:07,  4.10it/s]



 80%|███████▉  | 115/144 [00:28<00:09,  2.96it/s]



 81%|████████▏ | 117/144 [00:28<00:06,  4.14it/s]



 82%|████████▏ | 118/144 [00:28<00:05,  4.70it/s]



 83%|████████▎ | 119/144 [00:29<00:05,  4.74it/s]



 83%|████████▎ | 120/144 [00:29<00:05,  4.72it/s]



 84%|████████▍ | 121/144 [00:29<00:06,  3.70it/s]



 85%|████████▍ | 122/144 [00:30<00:05,  3.81it/s]



 85%|████████▌ | 123/144 [00:30<00:06,  3.24it/s]



 86%|████████▌ | 124/144 [00:30<00:06,  3.19it/s]



 87%|████████▋ | 125/144 [00:30<00:04,  3.85it/s]



 88%|████████▊ | 127/144 [00:31<00:03,  4.45it/s]



 89%|████████▉ | 128/144 [00:31<00:03,  4.99it/s]



 90%|████████▉ | 129/144 [00:31<00:03,  4.38it/s]



 90%|█████████ | 130/144 [00:32<00:04,  3.32it/s]



 91%|█████████ | 131/144 [00:32<00:05,  2.59it/s]



 92%|█████████▏| 132/144 [00:32<00:03,  3.23it/s]



 93%|█████████▎| 134/144 [00:33<00:02,  4.55it/s]



 94%|█████████▍| 135/144 [00:33<00:01,  5.16it/s]



 94%|█████████▍| 136/144 [00:33<00:01,  4.20it/s]



 95%|█████████▌| 137/144 [00:33<00:01,  4.38it/s]



 96%|█████████▌| 138/144 [00:33<00:01,  4.97it/s]



 97%|█████████▋| 139/144 [00:34<00:01,  3.05it/s]



 97%|█████████▋| 140/144 [00:34<00:01,  3.14it/s]



 99%|█████████▉| 143/144 [00:35<00:00,  5.76it/s]



100%|██████████| 144/144 [00:35<00:00,  4.07it/s]
Families:  33%|███▎      | 1/3 [00:35<01:10, 35.39s/it]



Multiplets | family 4:   0%|          | 0/1251 [00:00<?, ?it/s]




  0%|          | 0/1251 [00:00<?, ?it/s]




  0%|          | 1/1251 [00:02<49:36,  2.38s/it]




  0%|          | 6/1251 [00:02<06:26,  3.22it/s]




  1%|          | 9/1251 [00:04<10:25,  1.98it/s]




  1%|          | 12/1251 [00:04<06:45,  3.06it/s]




  1%|▏         | 17/1251 [00:07<07:56,  2.59it/s]




  2%|▏         | 19/1251 [00:07<06:35,  3.11it/s]




  2%|▏         | 23/1251 [00:07<04:19,  4.74it/s]




  2%|▏         | 25/1251 [00:09<08:19,  2.45it/s]




  2%|▏         | 27/1251 [00:09<06:47,  3.00it/s]




  2%|▏         | 29/1251 [00:10<05:56,  3.43it/s]




  2%|▏         | 31/1251 [00:10<04:43,  4.30it/s]




  3%|▎         | 33/1251 [00:12<08:41,  2.34it/s]




  3%|▎         | 34/1251 [00:12<07:54,  2.57it/s]




  3%|▎         | 35/1251 [00:12<07:27,  2.72it/s]




  3%|▎         | 37/1251 [00:12<05:13,  3.87it/s]




  3%|▎         | 38/1251 [00:12<04:42,  4.29it/s]




  3%|▎         | 39/1251 [00:13<05:16,  3.83it/s]




  3%|▎         | 41/1251 [00:14<08:57,  2.25it/s]




  3%|▎         | 42/1251 [00:15<08:02,  2.51it/s]




  3%|▎         | 43/1251 [00:15<08:05,  2.49it/s]




  4%|▎         | 45/1251 [00:15<05:39,  3.56it/s]




  4%|▍         | 47/1251 [00:15<04:10,  4.80it/s]




  4%|▍         | 48/1251 [00:15<04:06,  4.88it/s]




  4%|▍         | 49/1251 [00:17<08:36,  2.33it/s]

  4%|▍         | 50/1251 [00:17<07:43,  2.59it/s]




  4%|▍         | 51/1251 [00:17<08:21,  2.39it/s]




  4%|▍         | 52/1251 [00:18<07:52,  2.54it/s]




  4%|▍         | 55/1251 [00:18<04:12,  4.73it/s]




  4%|▍         | 56/1251 [00:18<04:44,  4.20it/s]




  5%|▍         | 57/1251 [00:19<09:06,  2.19it/s]




  5%|▍         | 58/1251 [00:20<07:31,  2.64it/s]




  5%|▍         | 59/1251 [00:20<06:52,  2.89it/s]




  5%|▍         | 60/1251 [00:20<06:49,  2.91it/s]




  5%|▍         | 62/1251 [00:20<04:17,  4.62it/s]




  5%|▌         | 63/1251 [00:20<03:59,  4.97it/s]




  5%|▌         | 64/1251 [00:21<04:43,  4.18it/s]




  5%|▌         | 65/1251 [00:22<09:34,  2.06it/s]




  5%|▌         | 67/1251 [00:22<06:51,  2.88it/s]




  5%|▌         | 68/1251 [00:23<07:01,  2.81it/s]




  6%|▌         | 71/1251 [00:23<04:13,  4.66it/s]




  6%|▌         | 72/1251 [00:23<04:49,  4.07it/s]




  6%|▌         | 73/1251 [00:24<08:28,  2.32it/s]




  6%|▌         | 75/1251 [00:25<06:33,  2.99it/s]




  6%|▌         | 76/1251 [00:25<06:43,  2.92it/s]




  6%|▌         | 77/1251 [00:25<05:54,  3.31it/s]




  6%|▋         | 79/1251 [00:25<04:20,  4.51it/s]




  6%|▋         | 80/1251 [00:26<05:53,  3.32it/s]




  6%|▋         | 81/1251 [00:27<08:39,  2.25it/s]




  7%|▋         | 83/1251 [00:28<07:36,  2.56it/s]




  7%|▋         | 84/1251 [00:28<06:37,  2.93it/s]




  7%|▋         | 85/1251 [00:28<06:07,  3.17it/s]




  7%|▋         | 86/1251 [00:28<05:17,  3.68it/s]




  7%|▋         | 87/1251 [00:29<05:49,  3.33it/s]




  7%|▋         | 88/1251 [00:29<07:23,  2.62it/s]




  7%|▋         | 89/1251 [00:30<10:20,  1.87it/s]




  7%|▋         | 90/1251 [00:30<08:40,  2.23it/s]




  7%|▋         | 91/1251 [00:30<06:53,  2.81it/s]




  7%|▋         | 92/1251 [00:31<06:01,  3.21it/s]




  7%|▋         | 93/1251 [00:31<05:11,  3.72it/s]




  8%|▊         | 94/1251 [00:31<06:28,  2.98it/s]




  8%|▊         | 96/1251 [00:32<06:40,  2.88it/s]




  8%|▊         | 97/1251 [00:33<08:57,  2.15it/s]




  8%|▊         | 98/1251 [00:33<07:57,  2.41it/s]




  8%|▊         | 99/1251 [00:33<07:10,  2.68it/s]




  8%|▊         | 101/1251 [00:33<04:27,  4.30it/s]




  8%|▊         | 102/1251 [00:34<05:40,  3.37it/s]




  8%|▊         | 104/1251 [00:35<07:07,  2.68it/s]




  8%|▊         | 105/1251 [00:36<08:00,  2.38it/s]




  8%|▊         | 106/1251 [00:36<08:17,  2.30it/s]




  9%|▊         | 108/1251 [00:36<05:17,  3.60it/s]




  9%|▊         | 109/1251 [00:36<05:34,  3.41it/s]




  9%|▉         | 110/1251 [00:37<05:29,  3.46it/s]




  9%|▉         | 111/1251 [00:37<05:14,  3.62it/s]




  9%|▉         | 112/1251 [00:38<08:06,  2.34it/s]




  9%|▉         | 113/1251 [00:38<09:16,  2.05it/s]




  9%|▉         | 114/1251 [00:39<07:40,  2.47it/s]




  9%|▉         | 116/1251 [00:39<04:42,  4.02it/s]




  9%|▉         | 117/1251 [00:39<06:20,  2.98it/s]




 10%|▉         | 119/1251 [00:40<05:37,  3.36it/s]




 10%|▉         | 120/1251 [00:41<07:35,  2.48it/s]




 10%|▉         | 121/1251 [00:41<07:41,  2.45it/s]




 10%|▉         | 122/1251 [00:41<06:27,  2.92it/s]




 10%|▉         | 124/1251 [00:41<04:55,  3.82it/s]




 10%|▉         | 125/1251 [00:42<05:53,  3.19it/s]




 10%|█         | 126/1251 [00:42<05:15,  3.56it/s]




 10%|█         | 127/1251 [00:43<06:35,  2.84it/s]




 10%|█         | 128/1251 [00:43<07:23,  2.53it/s]




 10%|█         | 129/1251 [00:44<08:06,  2.31it/s]




 11%|█         | 132/1251 [00:44<05:13,  3.57it/s]




 11%|█         | 133/1251 [00:45<07:00,  2.66it/s]




 11%|█         | 134/1251 [00:45<05:57,  3.12it/s]




 11%|█         | 135/1251 [00:45<05:47,  3.22it/s]




 11%|█         | 136/1251 [00:46<05:43,  3.24it/s]




 11%|█         | 137/1251 [00:46<06:20,  2.93it/s]




 11%|█         | 138/1251 [00:46<05:58,  3.11it/s]




 11%|█         | 139/1251 [00:47<05:43,  3.24it/s]




 11%|█         | 140/1251 [00:47<06:56,  2.67it/s]




 11%|█▏        | 141/1251 [00:47<06:13,  2.98it/s]




 11%|█▏        | 142/1251 [00:48<06:41,  2.76it/s]




 11%|█▏        | 143/1251 [00:48<05:35,  3.31it/s]




 12%|█▏        | 144/1251 [00:48<05:25,  3.40it/s]




 12%|█▏        | 145/1251 [00:49<07:59,  2.31it/s]




 12%|█▏        | 148/1251 [00:50<05:41,  3.23it/s]




 12%|█▏        | 149/1251 [00:50<06:22,  2.88it/s]




 12%|█▏        | 150/1251 [00:50<05:32,  3.31it/s]




 12%|█▏        | 151/1251 [00:51<05:31,  3.31it/s]




 12%|█▏        | 152/1251 [00:51<05:57,  3.07it/s]




 12%|█▏        | 153/1251 [00:51<06:27,  2.84it/s]




 12%|█▏        | 154/1251 [00:52<06:24,  2.85it/s]




 12%|█▏        | 155/1251 [00:52<05:11,  3.52it/s]




 12%|█▏        | 156/1251 [00:52<04:33,  4.00it/s]




 13%|█▎        | 157/1251 [00:53<06:20,  2.87it/s]




 13%|█▎        | 158/1251 [00:53<06:03,  3.00it/s]




 13%|█▎        | 159/1251 [00:53<06:40,  2.73it/s]




 13%|█▎        | 160/1251 [00:54<05:47,  3.14it/s]




 13%|█▎        | 161/1251 [00:54<07:11,  2.53it/s]




 13%|█▎        | 162/1251 [00:54<05:47,  3.14it/s]




 13%|█▎        | 163/1251 [00:55<05:56,  3.05it/s]




 13%|█▎        | 165/1251 [00:56<07:31,  2.41it/s]




 13%|█▎        | 166/1251 [00:56<06:09,  2.94it/s]




 13%|█▎        | 167/1251 [00:56<05:21,  3.37it/s]




 13%|█▎        | 168/1251 [00:56<05:03,  3.57it/s]




 14%|█▎        | 169/1251 [00:57<06:33,  2.75it/s]




 14%|█▎        | 170/1251 [00:57<07:57,  2.26it/s]




 14%|█▎        | 172/1251 [00:58<05:06,  3.52it/s]




 14%|█▍        | 173/1251 [00:58<06:32,  2.74it/s]




 14%|█▍        | 174/1251 [00:59<06:51,  2.62it/s]




 14%|█▍        | 177/1251 [00:59<05:34,  3.21it/s]




 14%|█▍        | 178/1251 [01:00<06:07,  2.92it/s]




 14%|█▍        | 179/1251 [01:00<05:17,  3.38it/s]




 14%|█▍        | 180/1251 [01:01<06:28,  2.75it/s]




 15%|█▍        | 182/1251 [01:01<05:58,  2.99it/s]




 15%|█▍        | 183/1251 [01:01<05:37,  3.16it/s]




 15%|█▍        | 185/1251 [01:02<05:41,  3.12it/s]




 15%|█▍        | 186/1251 [01:02<05:43,  3.10it/s]




 15%|█▍        | 187/1251 [01:03<05:46,  3.07it/s]




 15%|█▌        | 188/1251 [01:03<05:27,  3.25it/s]




 15%|█▌        | 189/1251 [01:03<05:14,  3.38it/s]




 15%|█▌        | 190/1251 [01:04<06:30,  2.72it/s]




 15%|█▌        | 192/1251 [01:04<05:02,  3.50it/s]




 15%|█▌        | 193/1251 [01:05<05:59,  2.94it/s]

 16%|█▌        | 194/1251 [01:05<05:27,  3.22it/s]




 16%|█▌        | 195/1251 [01:05<05:20,  3.30it/s]




 16%|█▌        | 196/1251 [01:06<06:20,  2.78it/s]




 16%|█▌        | 197/1251 [01:06<05:10,  3.39it/s]




 16%|█▌        | 198/1251 [01:06<06:40,  2.63it/s]




 16%|█▌        | 199/1251 [01:07<05:51,  2.99it/s]




 16%|█▌        | 200/1251 [01:07<04:39,  3.76it/s]




 16%|█▌        | 201/1251 [01:07<06:41,  2.62it/s]




 16%|█▌        | 202/1251 [01:08<05:51,  2.99it/s]




 16%|█▋        | 204/1251 [01:08<06:01,  2.89it/s]




 16%|█▋        | 206/1251 [01:09<05:23,  3.23it/s]




 17%|█▋        | 207/1251 [01:09<05:49,  2.99it/s]




 17%|█▋        | 209/1251 [01:10<05:55,  2.93it/s]




 17%|█▋        | 210/1251 [01:10<05:15,  3.30it/s]




 17%|█▋        | 212/1251 [01:11<05:41,  3.04it/s]




 17%|█▋        | 213/1251 [01:11<04:55,  3.51it/s]




 17%|█▋        | 214/1251 [01:12<06:09,  2.81it/s]




 17%|█▋        | 215/1251 [01:12<05:31,  3.12it/s]




 17%|█▋        | 217/1251 [01:13<06:16,  2.75it/s]




 18%|█▊        | 219/1251 [01:13<04:29,  3.82it/s]




 18%|█▊        | 220/1251 [01:13<05:51,  2.94it/s]




 18%|█▊        | 222/1251 [01:14<05:57,  2.88it/s]




 18%|█▊        | 224/1251 [01:15<06:14,  2.74it/s]




 18%|█▊        | 225/1251 [01:15<05:53,  2.90it/s]




 18%|█▊        | 227/1251 [01:15<04:05,  4.16it/s]




 18%|█▊        | 228/1251 [01:17<07:12,  2.37it/s]




 18%|█▊        | 229/1251 [01:17<06:21,  2.68it/s]




 18%|█▊        | 230/1251 [01:17<05:25,  3.14it/s]




 18%|█▊        | 231/1251 [01:17<04:55,  3.45it/s]




 19%|█▊        | 232/1251 [01:18<07:07,  2.38it/s]




 19%|█▊        | 233/1251 [01:18<07:11,  2.36it/s]




 19%|█▉        | 235/1251 [01:18<04:31,  3.74it/s]




 19%|█▉        | 236/1251 [01:20<07:52,  2.15it/s]




 19%|█▉        | 237/1251 [01:20<06:22,  2.65it/s]




 19%|█▉        | 239/1251 [01:20<05:18,  3.18it/s]




 19%|█▉        | 240/1251 [01:21<05:53,  2.86it/s]




 19%|█▉        | 241/1251 [01:21<05:54,  2.85it/s]




 19%|█▉        | 242/1251 [01:21<05:18,  3.17it/s]




 19%|█▉        | 243/1251 [01:21<04:43,  3.56it/s]




 20%|█▉        | 244/1251 [01:22<06:18,  2.66it/s]




 20%|█▉        | 245/1251 [01:22<05:02,  3.33it/s]




 20%|█▉        | 246/1251 [01:22<05:09,  3.25it/s]




 20%|█▉        | 247/1251 [01:23<05:23,  3.10it/s]




 20%|█▉        | 248/1251 [01:23<06:14,  2.68it/s]




 20%|█▉        | 249/1251 [01:24<06:26,  2.59it/s]




 20%|██        | 251/1251 [01:24<04:26,  3.76it/s]




 20%|██        | 252/1251 [01:25<06:27,  2.58it/s]




 20%|██        | 254/1251 [01:25<04:57,  3.35it/s]




 20%|██        | 255/1251 [01:25<04:45,  3.49it/s]




 20%|██        | 256/1251 [01:26<05:43,  2.90it/s]




 21%|██        | 257/1251 [01:26<05:18,  3.12it/s]




 21%|██        | 259/1251 [01:26<04:04,  4.05it/s]




 21%|██        | 260/1251 [01:27<06:00,  2.75it/s]




 21%|██        | 261/1251 [01:27<05:09,  3.19it/s]




 21%|██        | 262/1251 [01:27<04:54,  3.36it/s]




 21%|██        | 263/1251 [01:28<04:45,  3.45it/s]




 21%|██        | 264/1251 [01:28<05:47,  2.84it/s]




 21%|██        | 265/1251 [01:28<04:49,  3.41it/s]




 21%|██▏       | 267/1251 [01:29<04:29,  3.65it/s]




 21%|██▏       | 268/1251 [01:30<06:28,  2.53it/s]




 22%|██▏       | 269/1251 [01:30<05:44,  2.85it/s]




 22%|██▏       | 270/1251 [01:30<06:00,  2.72it/s]




 22%|██▏       | 271/1251 [01:30<04:47,  3.41it/s]




 22%|██▏       | 272/1251 [01:31<04:59,  3.26it/s]




 22%|██▏       | 273/1251 [01:31<04:20,  3.76it/s]




 22%|██▏       | 274/1251 [01:31<05:28,  2.98it/s]




 22%|██▏       | 276/1251 [01:32<05:45,  2.82it/s]




 22%|██▏       | 277/1251 [01:33<07:11,  2.26it/s]




 22%|██▏       | 280/1251 [01:33<04:19,  3.74it/s]




 22%|██▏       | 281/1251 [01:34<04:55,  3.28it/s]




 23%|██▎       | 282/1251 [01:34<05:01,  3.21it/s]




 23%|██▎       | 283/1251 [01:34<04:49,  3.34it/s]




 23%|██▎       | 284/1251 [01:35<05:25,  2.97it/s]




 23%|██▎       | 285/1251 [01:35<07:22,  2.18it/s]




 23%|██▎       | 286/1251 [01:36<05:48,  2.77it/s]




 23%|██▎       | 287/1251 [01:36<04:37,  3.47it/s]




 23%|██▎       | 288/1251 [01:36<04:01,  3.99it/s]




 23%|██▎       | 289/1251 [01:36<04:01,  3.98it/s]




 23%|██▎       | 290/1251 [01:37<05:12,  3.07it/s]




 23%|██▎       | 292/1251 [01:37<05:27,  2.93it/s]




 23%|██▎       | 293/1251 [01:38<06:46,  2.36it/s]




 24%|██▎       | 294/1251 [01:38<05:50,  2.73it/s]




 24%|██▎       | 296/1251 [01:38<04:05,  3.89it/s]




 24%|██▎       | 297/1251 [01:39<03:38,  4.36it/s]




 24%|██▍       | 298/1251 [01:39<04:47,  3.32it/s]




 24%|██▍       | 300/1251 [01:40<04:59,  3.17it/s]




 24%|██▍       | 301/1251 [01:40<06:27,  2.45it/s]




 24%|██▍       | 302/1251 [01:41<05:25,  2.92it/s]




 24%|██▍       | 304/1251 [01:41<03:58,  3.98it/s]




 24%|██▍       | 306/1251 [01:42<04:33,  3.45it/s]




 25%|██▍       | 308/1251 [01:42<04:41,  3.35it/s]




 25%|██▍       | 309/1251 [01:43<06:07,  2.56it/s]




 25%|██▍       | 311/1251 [01:43<04:13,  3.71it/s]




 25%|██▍       | 312/1251 [01:43<04:09,  3.77it/s]




 25%|██▌       | 313/1251 [01:43<03:43,  4.20it/s]




 25%|██▌       | 314/1251 [01:44<04:58,  3.14it/s]




 25%|██▌       | 316/1251 [01:45<04:54,  3.17it/s]




 25%|██▌       | 317/1251 [01:45<06:22,  2.44it/s]




 25%|██▌       | 318/1251 [01:46<05:31,  2.82it/s]




 26%|██▌       | 320/1251 [01:46<04:33,  3.40it/s]




 26%|██▌       | 321/1251 [01:46<04:00,  3.86it/s]




 26%|██▌       | 322/1251 [01:46<04:26,  3.49it/s]




 26%|██▌       | 323/1251 [01:47<04:01,  3.85it/s]




 26%|██▌       | 324/1251 [01:48<07:05,  2.18it/s]




 26%|██▌       | 325/1251 [01:48<05:38,  2.74it/s]




 26%|██▌       | 326/1251 [01:48<05:13,  2.95it/s]




 26%|██▌       | 327/1251 [01:48<05:11,  2.97it/s]




 26%|██▌       | 328/1251 [01:49<05:46,  2.66it/s]




 26%|██▋       | 331/1251 [01:49<03:06,  4.93it/s]




 27%|██▋       | 332/1251 [01:50<06:14,  2.46it/s]




 27%|██▋       | 334/1251 [01:51<05:27,  2.80it/s]




 27%|██▋       | 335/1251 [01:51<05:13,  2.93it/s]




 27%|██▋       | 336/1251 [01:51<04:41,  3.25it/s]




 27%|██▋       | 338/1251 [01:51<03:19,  4.59it/s]




 27%|██▋       | 339/1251 [01:52<03:24,  4.47it/s]




 27%|██▋       | 340/1251 [01:53<06:12,  2.45it/s]




 27%|██▋       | 342/1251 [01:53<05:43,  2.64it/s]

 27%|██▋       | 343/1251 [01:53<04:58,  3.04it/s]




 27%|██▋       | 344/1251 [01:54<04:41,  3.22it/s]




 28%|██▊       | 346/1251 [01:54<03:22,  4.46it/s]




 28%|██▊       | 347/1251 [01:54<03:08,  4.79it/s]




 28%|██▊       | 348/1251 [01:55<06:05,  2.47it/s]




 28%|██▊       | 350/1251 [01:56<06:05,  2.47it/s]




 28%|██▊       | 352/1251 [01:56<04:44,  3.16it/s]




 28%|██▊       | 353/1251 [01:56<04:18,  3.48it/s]




 28%|██▊       | 355/1251 [01:57<03:36,  4.14it/s]




 28%|██▊       | 356/1251 [01:58<05:53,  2.53it/s]




 29%|██▊       | 358/1251 [01:58<05:21,  2.78it/s]




 29%|██▊       | 359/1251 [01:59<04:55,  3.02it/s]




 29%|██▉       | 360/1251 [01:59<04:38,  3.20it/s]




 29%|██▉       | 362/1251 [01:59<03:24,  4.36it/s]




 29%|██▉       | 363/1251 [01:59<03:26,  4.30it/s]




 29%|██▉       | 364/1251 [02:00<05:47,  2.56it/s]




 29%|██▉       | 366/1251 [02:01<05:34,  2.65it/s]




 29%|██▉       | 367/1251 [02:01<04:44,  3.11it/s]




 29%|██▉       | 368/1251 [02:01<04:25,  3.33it/s]




 29%|██▉       | 369/1251 [02:01<03:46,  3.90it/s]




 30%|██▉       | 370/1251 [02:02<03:17,  4.45it/s]




 30%|██▉       | 371/1251 [02:02<03:51,  3.80it/s]




 30%|██▉       | 372/1251 [02:03<05:38,  2.59it/s]




 30%|██▉       | 373/1251 [02:03<04:29,  3.26it/s]




 30%|██▉       | 374/1251 [02:03<06:36,  2.21it/s]




 30%|███       | 376/1251 [02:04<04:24,  3.31it/s]




 30%|███       | 378/1251 [02:04<03:23,  4.28it/s]




 30%|███       | 379/1251 [02:04<03:41,  3.94it/s]




 30%|███       | 380/1251 [02:05<05:53,  2.46it/s]




 31%|███       | 382/1251 [02:06<05:45,  2.51it/s]




 31%|███       | 384/1251 [02:06<04:04,  3.55it/s]




 31%|███       | 386/1251 [02:07<04:07,  3.49it/s]




 31%|███       | 387/1251 [02:07<03:59,  3.61it/s]




 31%|███       | 388/1251 [02:08<05:41,  2.53it/s]




 31%|███       | 390/1251 [02:08<05:15,  2.73it/s]




 31%|███▏      | 392/1251 [02:09<03:55,  3.65it/s]




 31%|███▏      | 394/1251 [02:09<04:07,  3.46it/s]




 32%|███▏      | 395/1251 [02:09<03:46,  3.78it/s]




 32%|███▏      | 396/1251 [02:10<05:25,  2.63it/s]




 32%|███▏      | 397/1251 [02:10<04:37,  3.08it/s]




 32%|███▏      | 398/1251 [02:11<05:19,  2.67it/s]




 32%|███▏      | 399/1251 [02:11<04:22,  3.24it/s]




 32%|███▏      | 401/1251 [02:11<03:15,  4.34it/s]




 32%|███▏      | 402/1251 [02:12<04:08,  3.42it/s]




 32%|███▏      | 403/1251 [02:12<03:48,  3.71it/s]




 32%|███▏      | 404/1251 [02:13<05:35,  2.52it/s]




 32%|███▏      | 406/1251 [02:13<04:59,  2.82it/s]




 33%|███▎      | 408/1251 [02:14<03:57,  3.55it/s]




 33%|███▎      | 410/1251 [02:14<04:06,  3.41it/s]




 33%|███▎      | 411/1251 [02:14<03:37,  3.87it/s]




 33%|███▎      | 412/1251 [02:15<05:22,  2.60it/s]




 33%|███▎      | 414/1251 [02:16<04:50,  2.88it/s]




 33%|███▎      | 415/1251 [02:16<04:36,  3.02it/s]




 33%|███▎      | 416/1251 [02:16<03:50,  3.62it/s]




 33%|███▎      | 418/1251 [02:17<04:08,  3.35it/s]




 33%|███▎      | 419/1251 [02:17<03:38,  3.81it/s]




 34%|███▎      | 420/1251 [02:18<05:03,  2.73it/s]




 34%|███▎      | 421/1251 [02:18<05:42,  2.42it/s]




 34%|███▍      | 423/1251 [02:19<04:15,  3.24it/s]




 34%|███▍      | 425/1251 [02:19<03:34,  3.86it/s]




 34%|███▍      | 426/1251 [02:20<04:58,  2.77it/s]




 34%|███▍      | 427/1251 [02:20<04:16,  3.21it/s]




 34%|███▍      | 428/1251 [02:20<04:09,  3.30it/s]




 34%|███▍      | 429/1251 [02:21<06:07,  2.24it/s]




 34%|███▍      | 431/1251 [02:21<03:51,  3.54it/s]




 35%|███▍      | 433/1251 [02:22<04:01,  3.38it/s]




 35%|███▍      | 434/1251 [02:22<04:25,  3.08it/s]




 35%|███▍      | 435/1251 [02:22<04:34,  2.98it/s]




 35%|███▍      | 436/1251 [02:23<04:21,  3.11it/s]




 35%|███▍      | 437/1251 [02:23<05:16,  2.57it/s]




 35%|███▌      | 438/1251 [02:23<04:12,  3.22it/s]




 35%|███▌      | 440/1251 [02:24<03:36,  3.75it/s]




 35%|███▌      | 441/1251 [02:24<04:18,  3.13it/s]




 35%|███▌      | 442/1251 [02:25<04:25,  3.04it/s]




 35%|███▌      | 443/1251 [02:25<04:04,  3.30it/s]




 35%|███▌      | 444/1251 [02:25<04:58,  2.71it/s]




 36%|███▌      | 445/1251 [02:26<04:30,  2.98it/s]




 36%|███▌      | 446/1251 [02:26<03:46,  3.55it/s]




 36%|███▌      | 447/1251 [02:26<03:18,  4.05it/s]




 36%|███▌      | 448/1251 [02:26<03:58,  3.37it/s]




 36%|███▌      | 449/1251 [02:27<04:11,  3.19it/s]




 36%|███▌      | 450/1251 [02:27<04:40,  2.86it/s]




 36%|███▌      | 451/1251 [02:27<03:47,  3.52it/s]




 36%|███▌      | 452/1251 [02:28<04:57,  2.68it/s]




 36%|███▌      | 453/1251 [02:28<04:22,  3.03it/s]




 36%|███▋      | 455/1251 [02:28<03:01,  4.39it/s]




 36%|███▋      | 456/1251 [02:29<04:02,  3.27it/s]




 37%|███▋      | 457/1251 [02:29<03:52,  3.41it/s]




 37%|███▋      | 458/1251 [02:30<04:51,  2.72it/s]




 37%|███▋      | 460/1251 [02:30<04:36,  2.86it/s]




 37%|███▋      | 461/1251 [02:31<04:13,  3.11it/s]




 37%|███▋      | 463/1251 [02:31<02:53,  4.53it/s]




 37%|███▋      | 464/1251 [02:31<04:09,  3.15it/s]




 37%|███▋      | 465/1251 [02:32<04:09,  3.15it/s]




 37%|███▋      | 466/1251 [02:32<04:41,  2.79it/s]




 37%|███▋      | 468/1251 [02:33<04:17,  3.04it/s]




 37%|███▋      | 469/1251 [02:33<04:17,  3.03it/s]




 38%|███▊      | 470/1251 [02:33<03:46,  3.44it/s]




 38%|███▊      | 471/1251 [02:34<03:24,  3.82it/s]




 38%|███▊      | 472/1251 [02:34<05:03,  2.57it/s]




 38%|███▊      | 474/1251 [02:35<04:50,  2.67it/s]




 38%|███▊      | 476/1251 [02:35<03:57,  3.27it/s]




 38%|███▊      | 477/1251 [02:36<03:49,  3.37it/s]




 38%|███▊      | 478/1251 [02:36<04:07,  3.13it/s]




 38%|███▊      | 479/1251 [02:36<03:31,  3.64it/s]




 38%|███▊      | 480/1251 [02:37<05:25,  2.37it/s]




 39%|███▊      | 482/1251 [02:38<05:00,  2.56it/s]




 39%|███▊      | 484/1251 [02:38<03:49,  3.33it/s]




 39%|███▉      | 486/1251 [02:38<03:39,  3.49it/s]




 39%|███▉      | 488/1251 [02:39<04:14,  2.99it/s]




 39%|███▉      | 489/1251 [02:40<04:11,  3.03it/s]




 39%|███▉      | 490/1251 [02:40<04:33,  2.78it/s]




 39%|███▉      | 491/1251 [02:40<04:12,  3.01it/s]




 39%|███▉      | 492/1251 [02:41<03:39,  3.45it/s]




 39%|███▉      | 493/1251 [02:41<03:12,  3.93it/s]




 39%|███▉      | 494/1251 [02:41<03:02,  4.15it/s]




 40%|███▉      | 495/1251 [02:41<02:35,  4.85it/s]

 40%|███▉      | 496/1251 [02:42<04:32,  2.77it/s]




 40%|███▉      | 497/1251 [02:42<04:48,  2.61it/s]




 40%|███▉      | 498/1251 [02:43<05:21,  2.34it/s]




 40%|███▉      | 499/1251 [02:43<04:08,  3.02it/s]




 40%|███▉      | 500/1251 [02:43<03:33,  3.52it/s]




 40%|████      | 501/1251 [02:43<03:10,  3.95it/s]




 40%|████      | 502/1251 [02:43<02:35,  4.81it/s]




 40%|████      | 503/1251 [02:43<02:27,  5.07it/s]




 40%|████      | 504/1251 [02:44<04:25,  2.81it/s]




 40%|████      | 505/1251 [02:45<04:55,  2.52it/s]




 40%|████      | 506/1251 [02:45<05:10,  2.40it/s]




 41%|████      | 508/1251 [02:45<03:33,  3.47it/s]




 41%|████      | 509/1251 [02:46<03:10,  3.89it/s]




 41%|████      | 511/1251 [02:46<02:30,  4.93it/s]




 41%|████      | 512/1251 [02:47<03:58,  3.10it/s]




 41%|████      | 513/1251 [02:47<04:48,  2.56it/s]




 41%|████      | 514/1251 [02:48<05:20,  2.30it/s]




 41%|████      | 516/1251 [02:48<03:20,  3.66it/s]




 41%|████▏     | 517/1251 [02:48<03:03,  4.01it/s]




 41%|████▏     | 518/1251 [02:48<03:01,  4.05it/s]




 42%|████▏     | 520/1251 [02:49<03:48,  3.19it/s]




 42%|████▏     | 521/1251 [02:50<05:28,  2.22it/s]




 42%|████▏     | 522/1251 [02:50<04:38,  2.61it/s]




 42%|████▏     | 524/1251 [02:51<03:37,  3.34it/s]




 42%|████▏     | 525/1251 [02:51<03:04,  3.93it/s]




 42%|████▏     | 526/1251 [02:51<02:49,  4.27it/s]




 42%|████▏     | 527/1251 [02:51<03:13,  3.73it/s]




 42%|████▏     | 528/1251 [02:51<03:28,  3.47it/s]




 42%|████▏     | 529/1251 [02:52<05:33,  2.16it/s]




 42%|████▏     | 530/1251 [02:53<04:31,  2.66it/s]




 42%|████▏     | 531/1251 [02:53<03:44,  3.21it/s]




 43%|████▎     | 532/1251 [02:53<04:33,  2.63it/s]




 43%|████▎     | 534/1251 [02:53<02:48,  4.26it/s]




 43%|████▎     | 535/1251 [02:54<02:47,  4.27it/s]




 43%|████▎     | 536/1251 [02:54<03:26,  3.46it/s]




 43%|████▎     | 537/1251 [02:55<05:51,  2.03it/s]




 43%|████▎     | 538/1251 [02:55<04:39,  2.55it/s]




 43%|████▎     | 540/1251 [02:56<03:54,  3.03it/s]




 43%|████▎     | 541/1251 [02:56<03:24,  3.47it/s]




 43%|████▎     | 542/1251 [02:56<03:11,  3.70it/s]




 43%|████▎     | 543/1251 [02:56<03:16,  3.60it/s]




 44%|████▎     | 545/1251 [02:58<04:40,  2.51it/s]




 44%|████▎     | 546/1251 [02:58<04:24,  2.67it/s]




 44%|████▎     | 547/1251 [02:58<03:38,  3.22it/s]




 44%|████▍     | 548/1251 [02:58<03:38,  3.22it/s]




 44%|████▍     | 549/1251 [02:58<02:57,  3.95it/s]




 44%|████▍     | 550/1251 [02:59<03:30,  3.33it/s]




 44%|████▍     | 551/1251 [02:59<03:06,  3.75it/s]




 44%|████▍     | 553/1251 [03:00<04:19,  2.69it/s]




 44%|████▍     | 554/1251 [03:00<04:10,  2.78it/s]




 44%|████▍     | 555/1251 [03:00<03:25,  3.38it/s]




 44%|████▍     | 556/1251 [03:01<03:21,  3.46it/s]




 45%|████▍     | 557/1251 [03:01<02:50,  4.08it/s]




 45%|████▍     | 558/1251 [03:01<03:19,  3.48it/s]




 45%|████▍     | 559/1251 [03:01<03:05,  3.72it/s]




 45%|████▍     | 561/1251 [03:02<04:11,  2.75it/s]




 45%|████▍     | 562/1251 [03:03<04:10,  2.75it/s]




 45%|████▌     | 563/1251 [03:03<03:26,  3.34it/s]




 45%|████▌     | 564/1251 [03:03<03:10,  3.60it/s]




 45%|████▌     | 565/1251 [03:03<02:44,  4.18it/s]




 45%|████▌     | 566/1251 [03:04<03:16,  3.48it/s]




 45%|████▌     | 567/1251 [03:04<02:57,  3.84it/s]




 45%|████▌     | 569/1251 [03:05<04:51,  2.34it/s]




 46%|████▌     | 570/1251 [03:05<04:00,  2.83it/s]




 46%|████▌     | 571/1251 [03:05<03:19,  3.42it/s]




 46%|████▌     | 572/1251 [03:06<03:04,  3.67it/s]




 46%|████▌     | 573/1251 [03:06<02:38,  4.28it/s]




 46%|████▌     | 574/1251 [03:06<03:48,  2.97it/s]




 46%|████▌     | 575/1251 [03:06<03:26,  3.27it/s]




 46%|████▌     | 577/1251 [03:08<04:37,  2.43it/s]




 46%|████▋     | 579/1251 [03:08<03:27,  3.24it/s]




 46%|████▋     | 580/1251 [03:08<03:02,  3.67it/s]




 46%|████▋     | 581/1251 [03:08<03:24,  3.27it/s]




 47%|████▋     | 582/1251 [03:09<04:01,  2.78it/s]




 47%|████▋     | 583/1251 [03:09<04:20,  2.57it/s]




 47%|████▋     | 585/1251 [03:10<03:43,  2.98it/s]




 47%|████▋     | 586/1251 [03:10<03:15,  3.40it/s]




 47%|████▋     | 587/1251 [03:10<03:32,  3.12it/s]




 47%|████▋     | 588/1251 [03:11<02:59,  3.69it/s]




 47%|████▋     | 589/1251 [03:11<02:41,  4.11it/s]




 47%|████▋     | 590/1251 [03:12<04:12,  2.61it/s]




 47%|████▋     | 591/1251 [03:12<04:11,  2.63it/s]




 47%|████▋     | 593/1251 [03:13<03:47,  2.90it/s]




 48%|████▊     | 595/1251 [03:13<03:32,  3.09it/s]




 48%|████▊     | 597/1251 [03:13<02:41,  4.04it/s]




 48%|████▊     | 598/1251 [03:14<03:38,  2.98it/s]




 48%|████▊     | 599/1251 [03:14<03:44,  2.91it/s]




 48%|████▊     | 600/1251 [03:14<03:08,  3.46it/s]




 48%|████▊     | 601/1251 [03:15<03:30,  3.09it/s]




 48%|████▊     | 602/1251 [03:15<02:57,  3.66it/s]




 48%|████▊     | 603/1251 [03:16<03:39,  2.96it/s]




 48%|████▊     | 605/1251 [03:16<02:30,  4.29it/s]




 48%|████▊     | 606/1251 [03:16<03:47,  2.84it/s]




 49%|████▊     | 607/1251 [03:17<03:38,  2.94it/s]




 49%|████▊     | 609/1251 [03:17<03:11,  3.35it/s]




 49%|████▉     | 610/1251 [03:17<02:49,  3.78it/s]




 49%|████▉     | 611/1251 [03:18<03:32,  3.01it/s]




 49%|████▉     | 612/1251 [03:18<03:02,  3.51it/s]




 49%|████▉     | 613/1251 [03:18<02:33,  4.16it/s]




 49%|████▉     | 614/1251 [03:19<03:53,  2.73it/s]




 49%|████▉     | 615/1251 [03:19<03:43,  2.85it/s]




 49%|████▉     | 617/1251 [03:20<03:12,  3.29it/s]




 49%|████▉     | 618/1251 [03:20<02:51,  3.70it/s]




 49%|████▉     | 619/1251 [03:20<03:39,  2.89it/s]




 50%|████▉     | 620/1251 [03:21<03:05,  3.40it/s]




 50%|████▉     | 621/1251 [03:21<03:22,  3.11it/s]




 50%|████▉     | 622/1251 [03:21<03:47,  2.77it/s]




 50%|████▉     | 623/1251 [03:22<03:33,  2.94it/s]




 50%|████▉     | 624/1251 [03:22<02:56,  3.55it/s]




 50%|████▉     | 625/1251 [03:22<02:57,  3.52it/s]




 50%|█████     | 626/1251 [03:22<02:41,  3.87it/s]




 50%|█████     | 627/1251 [03:23<03:46,  2.76it/s]




 50%|█████     | 628/1251 [03:24<04:33,  2.28it/s]




 50%|█████     | 630/1251 [03:24<03:32,  2.92it/s]




 51%|█████     | 632/1251 [03:25<03:37,  2.85it/s]




 51%|█████     | 633/1251 [03:25<03:04,  3.35it/s]




 51%|█████     | 635/1251 [03:26<03:12,  3.20it/s]

 51%|█████     | 636/1251 [03:26<03:34,  2.87it/s]




 51%|█████     | 637/1251 [03:26<03:29,  2.94it/s]




 51%|█████     | 638/1251 [03:27<03:31,  2.90it/s]




 51%|█████     | 640/1251 [03:27<03:03,  3.34it/s]




 51%|█████     | 641/1251 [03:27<02:38,  3.86it/s]




 51%|█████▏    | 642/1251 [03:27<02:20,  4.35it/s]




 51%|█████▏    | 643/1251 [03:28<03:19,  3.04it/s]




 51%|█████▏    | 644/1251 [03:29<04:05,  2.47it/s]




 52%|█████▏    | 645/1251 [03:29<03:23,  2.98it/s]




 52%|█████▏    | 646/1251 [03:29<03:50,  2.63it/s]




 52%|█████▏    | 647/1251 [03:30<03:18,  3.05it/s]




 52%|█████▏    | 648/1251 [03:30<02:46,  3.61it/s]




 52%|█████▏    | 649/1251 [03:30<03:10,  3.16it/s]




 52%|█████▏    | 651/1251 [03:31<02:37,  3.81it/s]




 52%|█████▏    | 652/1251 [03:31<04:01,  2.48it/s]




 52%|█████▏    | 654/1251 [03:32<03:17,  3.03it/s]




 52%|█████▏    | 655/1251 [03:32<03:10,  3.13it/s]




 53%|█████▎    | 657/1251 [03:33<02:49,  3.51it/s]




 53%|█████▎    | 659/1251 [03:33<02:31,  3.91it/s]




 53%|█████▎    | 660/1251 [03:34<03:34,  2.76it/s]




 53%|█████▎    | 661/1251 [03:34<02:59,  3.29it/s]




 53%|█████▎    | 662/1251 [03:34<03:10,  3.09it/s]




 53%|█████▎    | 663/1251 [03:35<03:13,  3.04it/s]




 53%|█████▎    | 665/1251 [03:35<02:42,  3.61it/s]




 53%|█████▎    | 667/1251 [03:35<02:22,  4.09it/s]




 53%|█████▎    | 668/1251 [03:36<03:33,  2.73it/s]




 53%|█████▎    | 669/1251 [03:36<02:59,  3.24it/s]




 54%|█████▎    | 670/1251 [03:37<03:42,  2.61it/s]




 54%|█████▎    | 671/1251 [03:37<03:06,  3.11it/s]




 54%|█████▎    | 672/1251 [03:37<02:52,  3.36it/s]




 54%|█████▍    | 673/1251 [03:37<02:27,  3.91it/s]




 54%|█████▍    | 674/1251 [03:38<02:21,  4.09it/s]




 54%|█████▍    | 675/1251 [03:38<02:12,  4.36it/s]




 54%|█████▍    | 676/1251 [03:39<04:18,  2.22it/s]




 54%|█████▍    | 677/1251 [03:39<04:20,  2.21it/s]




 54%|█████▍    | 679/1251 [03:40<03:08,  3.03it/s]




 54%|█████▍    | 680/1251 [03:40<03:02,  3.13it/s]




 54%|█████▍    | 681/1251 [03:40<02:34,  3.69it/s]




 55%|█████▍    | 682/1251 [03:40<02:14,  4.22it/s]




 55%|█████▍    | 683/1251 [03:40<02:00,  4.69it/s]




 55%|█████▍    | 684/1251 [03:41<04:20,  2.18it/s]




 55%|█████▍    | 685/1251 [03:42<03:55,  2.40it/s]




 55%|█████▍    | 687/1251 [03:42<03:23,  2.77it/s]




 55%|█████▍    | 688/1251 [03:43<03:01,  3.10it/s]




 55%|█████▌    | 689/1251 [03:43<02:52,  3.26it/s]




 55%|█████▌    | 692/1251 [03:44<03:13,  2.89it/s]




 55%|█████▌    | 693/1251 [03:44<03:13,  2.88it/s]




 55%|█████▌    | 694/1251 [03:44<02:45,  3.36it/s]




 56%|█████▌    | 695/1251 [03:45<02:54,  3.19it/s]




 56%|█████▌    | 696/1251 [03:45<02:42,  3.42it/s]




 56%|█████▌    | 697/1251 [03:45<02:37,  3.52it/s]




 56%|█████▌    | 699/1251 [03:45<01:52,  4.90it/s]




 56%|█████▌    | 700/1251 [03:46<03:21,  2.74it/s]




 56%|█████▌    | 701/1251 [03:47<03:27,  2.65it/s]




 56%|█████▌    | 703/1251 [03:47<02:51,  3.20it/s]




 56%|█████▋    | 704/1251 [03:47<02:42,  3.37it/s]




 56%|█████▋    | 705/1251 [03:48<02:36,  3.50it/s]




 57%|█████▋    | 707/1251 [03:48<02:00,  4.50it/s]




 57%|█████▋    | 708/1251 [03:49<03:29,  2.59it/s]




 57%|█████▋    | 709/1251 [03:49<03:17,  2.74it/s]




 57%|█████▋    | 710/1251 [03:49<02:52,  3.14it/s]




 57%|█████▋    | 711/1251 [03:50<02:44,  3.28it/s]




 57%|█████▋    | 712/1251 [03:50<02:38,  3.40it/s]




 57%|█████▋    | 713/1251 [03:50<02:28,  3.61it/s]




 57%|█████▋    | 715/1251 [03:50<01:47,  4.98it/s]




 57%|█████▋    | 716/1251 [03:51<03:33,  2.51it/s]




 57%|█████▋    | 717/1251 [03:52<03:14,  2.74it/s]




 57%|█████▋    | 718/1251 [03:52<02:46,  3.20it/s]




 57%|█████▋    | 719/1251 [03:52<02:44,  3.22it/s]




 58%|█████▊    | 720/1251 [03:52<02:39,  3.33it/s]




 58%|█████▊    | 721/1251 [03:53<02:37,  3.37it/s]




 58%|█████▊    | 723/1251 [03:53<01:43,  5.10it/s]




 58%|█████▊    | 724/1251 [03:54<03:49,  2.30it/s]




 58%|█████▊    | 725/1251 [03:54<03:06,  2.82it/s]




 58%|█████▊    | 726/1251 [03:54<02:37,  3.32it/s]




 58%|█████▊    | 727/1251 [03:55<02:40,  3.26it/s]




 58%|█████▊    | 728/1251 [03:55<02:41,  3.24it/s]




 58%|█████▊    | 729/1251 [03:55<02:35,  3.36it/s]




 58%|█████▊    | 731/1251 [03:56<02:19,  3.71it/s]




 59%|█████▊    | 732/1251 [03:57<03:30,  2.47it/s]




 59%|█████▊    | 733/1251 [03:57<02:50,  3.03it/s]




 59%|█████▊    | 734/1251 [03:57<02:42,  3.18it/s]




 59%|█████▉    | 735/1251 [03:57<03:19,  2.58it/s]




 59%|█████▉    | 736/1251 [03:58<02:44,  3.12it/s]




 59%|█████▉    | 738/1251 [03:58<02:18,  3.71it/s]




 59%|█████▉    | 739/1251 [03:58<02:20,  3.65it/s]




 59%|█████▉    | 740/1251 [03:59<03:21,  2.54it/s]




 59%|█████▉    | 741/1251 [03:59<03:01,  2.81it/s]




 59%|█████▉    | 742/1251 [03:59<02:34,  3.29it/s]




 59%|█████▉    | 743/1251 [04:00<03:06,  2.72it/s]




 60%|█████▉    | 745/1251 [04:00<02:19,  3.62it/s]




 60%|█████▉    | 746/1251 [04:01<02:22,  3.55it/s]




 60%|█████▉    | 747/1251 [04:01<02:24,  3.50it/s]




 60%|█████▉    | 748/1251 [04:02<03:31,  2.37it/s]




 60%|█████▉    | 749/1251 [04:02<02:51,  2.93it/s]




 60%|█████▉    | 750/1251 [04:02<02:48,  2.97it/s]




 60%|██████    | 751/1251 [04:03<02:50,  2.93it/s]




 60%|██████    | 752/1251 [04:03<02:46,  3.00it/s]




 60%|██████    | 754/1251 [04:03<01:59,  4.15it/s]




 60%|██████    | 755/1251 [04:04<02:21,  3.52it/s]




 60%|██████    | 756/1251 [04:04<03:15,  2.53it/s]




 61%|██████    | 757/1251 [04:04<02:54,  2.83it/s]




 61%|██████    | 758/1251 [04:05<02:33,  3.21it/s]




 61%|██████    | 759/1251 [04:05<02:33,  3.20it/s]




 61%|██████    | 760/1251 [04:05<02:44,  2.98it/s]




 61%|██████    | 761/1251 [04:06<02:10,  3.74it/s]




 61%|██████    | 763/1251 [04:06<02:05,  3.90it/s]




 61%|██████    | 764/1251 [04:07<03:13,  2.52it/s]




 61%|██████    | 765/1251 [04:07<02:40,  3.03it/s]




 61%|██████    | 766/1251 [04:07<02:46,  2.91it/s]




 61%|██████▏   | 767/1251 [04:07<02:15,  3.57it/s]




 61%|██████▏   | 768/1251 [04:08<02:33,  3.14it/s]




 61%|██████▏   | 769/1251 [04:08<02:12,  3.65it/s]




 62%|██████▏   | 770/1251 [04:08<01:59,  4.04it/s]




 62%|██████▏   | 771/1251 [04:09<02:05,  3.84it/s]




 62%|██████▏   | 772/1251 [04:09<03:18,  2.41it/s]




 62%|██████▏   | 773/1251 [04:10<03:30,  2.27it/s]

 62%|██████▏   | 774/1251 [04:10<02:43,  2.92it/s]




 62%|██████▏   | 776/1251 [04:11<02:54,  2.72it/s]




 62%|██████▏   | 778/1251 [04:11<01:57,  4.01it/s]




 62%|██████▏   | 779/1251 [04:11<01:47,  4.39it/s]




 62%|██████▏   | 780/1251 [04:12<02:54,  2.70it/s]




 62%|██████▏   | 781/1251 [04:12<03:28,  2.26it/s]




 63%|██████▎   | 782/1251 [04:13<03:04,  2.55it/s]




 63%|██████▎   | 783/1251 [04:13<02:27,  3.17it/s]




 63%|██████▎   | 784/1251 [04:13<02:21,  3.30it/s]




 63%|██████▎   | 785/1251 [04:13<01:56,  4.01it/s]




 63%|██████▎   | 786/1251 [04:13<01:53,  4.09it/s]




 63%|██████▎   | 787/1251 [04:14<01:56,  3.99it/s]




 63%|██████▎   | 788/1251 [04:14<02:26,  3.15it/s]




 63%|██████▎   | 789/1251 [04:15<03:56,  1.95it/s]




 63%|██████▎   | 791/1251 [04:15<02:20,  3.28it/s]




 63%|██████▎   | 792/1251 [04:16<02:29,  3.07it/s]




 63%|██████▎   | 793/1251 [04:16<02:06,  3.62it/s]




 63%|██████▎   | 794/1251 [04:16<02:11,  3.48it/s]




 64%|██████▎   | 796/1251 [04:17<02:00,  3.77it/s]




 64%|██████▎   | 797/1251 [04:18<03:25,  2.21it/s]




 64%|██████▍   | 799/1251 [04:18<02:20,  3.22it/s]




 64%|██████▍   | 800/1251 [04:18<02:21,  3.19it/s]




 64%|██████▍   | 802/1251 [04:19<02:13,  3.36it/s]




 64%|██████▍   | 804/1251 [04:19<02:03,  3.62it/s]




 64%|██████▍   | 805/1251 [04:20<03:00,  2.46it/s]




 65%|██████▍   | 807/1251 [04:20<02:12,  3.34it/s]




 65%|██████▍   | 808/1251 [04:21<02:08,  3.46it/s]




 65%|██████▍   | 809/1251 [04:21<01:49,  4.04it/s]




 65%|██████▍   | 810/1251 [04:21<02:18,  3.18it/s]




 65%|██████▍   | 812/1251 [04:22<01:53,  3.85it/s]




 65%|██████▍   | 813/1251 [04:23<03:06,  2.34it/s]




 65%|██████▌   | 815/1251 [04:23<02:06,  3.44it/s]




 65%|██████▌   | 816/1251 [04:23<02:01,  3.58it/s]




 65%|██████▌   | 817/1251 [04:23<01:47,  4.02it/s]




 65%|██████▌   | 818/1251 [04:24<02:19,  3.11it/s]




 66%|██████▌   | 820/1251 [04:24<01:53,  3.80it/s]




 66%|██████▌   | 821/1251 [04:25<03:10,  2.26it/s]




 66%|██████▌   | 822/1251 [04:25<02:35,  2.76it/s]




 66%|██████▌   | 823/1251 [04:25<02:07,  3.36it/s]




 66%|██████▌   | 824/1251 [04:26<02:22,  3.01it/s]




 66%|██████▌   | 826/1251 [04:26<01:50,  3.85it/s]




 66%|██████▌   | 828/1251 [04:27<01:49,  3.88it/s]




 66%|██████▋   | 829/1251 [04:28<03:05,  2.28it/s]




 66%|██████▋   | 830/1251 [04:28<02:49,  2.49it/s]




 66%|██████▋   | 831/1251 [04:28<02:29,  2.82it/s]




 67%|██████▋   | 833/1251 [04:29<01:56,  3.58it/s]




 67%|██████▋   | 836/1251 [04:29<01:51,  3.73it/s]




 67%|██████▋   | 837/1251 [04:30<02:31,  2.74it/s]




 67%|██████▋   | 838/1251 [04:31<02:46,  2.48it/s]




 67%|██████▋   | 840/1251 [04:31<01:53,  3.63it/s]




 67%|██████▋   | 841/1251 [04:31<01:47,  3.81it/s]




 67%|██████▋   | 843/1251 [04:31<01:30,  4.51it/s]




 67%|██████▋   | 844/1251 [04:32<01:54,  3.55it/s]




 68%|██████▊   | 845/1251 [04:33<02:43,  2.49it/s]




 68%|██████▊   | 846/1251 [04:33<03:05,  2.19it/s]




 68%|██████▊   | 847/1251 [04:33<02:29,  2.70it/s]




 68%|██████▊   | 849/1251 [04:34<01:44,  3.86it/s]




 68%|██████▊   | 851/1251 [04:34<01:16,  5.21it/s]




 68%|██████▊   | 852/1251 [04:34<01:39,  4.00it/s]




 68%|██████▊   | 853/1251 [04:35<02:32,  2.61it/s]




 68%|██████▊   | 854/1251 [04:36<03:05,  2.14it/s]




 68%|██████▊   | 856/1251 [04:36<02:06,  3.13it/s]




 69%|██████▊   | 859/1251 [04:36<01:16,  5.15it/s]




 69%|██████▊   | 860/1251 [04:37<01:41,  3.84it/s]




 69%|██████▉   | 861/1251 [04:37<02:19,  2.80it/s]




 69%|██████▉   | 862/1251 [04:38<02:59,  2.17it/s]




 69%|██████▉   | 864/1251 [04:38<02:00,  3.22it/s]




 69%|██████▉   | 866/1251 [04:38<01:23,  4.61it/s]




 69%|██████▉   | 868/1251 [04:39<01:34,  4.06it/s]




 69%|██████▉   | 869/1251 [04:40<02:18,  2.76it/s]




 70%|██████▉   | 870/1251 [04:41<02:52,  2.21it/s]




 70%|██████▉   | 872/1251 [04:41<01:53,  3.35it/s]




 70%|██████▉   | 873/1251 [04:41<01:46,  3.54it/s]




 70%|██████▉   | 875/1251 [04:41<01:13,  5.10it/s]




 70%|███████   | 877/1251 [04:42<02:13,  2.80it/s]




 70%|███████   | 878/1251 [04:43<02:39,  2.34it/s]




 70%|███████   | 880/1251 [04:43<01:56,  3.17it/s]




 71%|███████   | 883/1251 [04:44<01:20,  4.57it/s]




 71%|███████   | 884/1251 [04:44<01:43,  3.54it/s]




 71%|███████   | 885/1251 [04:45<02:15,  2.70it/s]




 71%|███████   | 886/1251 [04:46<02:31,  2.41it/s]




 71%|███████   | 887/1251 [04:46<02:06,  2.87it/s]




 71%|███████   | 888/1251 [04:46<01:48,  3.36it/s]




 71%|███████   | 889/1251 [04:46<01:55,  3.12it/s]




 71%|███████▏  | 892/1251 [04:47<01:33,  3.83it/s]




 71%|███████▏  | 893/1251 [04:47<02:00,  2.96it/s]




 71%|███████▏  | 894/1251 [04:48<02:22,  2.50it/s]




 72%|███████▏  | 895/1251 [04:48<01:58,  3.01it/s]




 72%|███████▏  | 896/1251 [04:48<01:41,  3.50it/s]




 72%|███████▏  | 897/1251 [04:49<01:49,  3.22it/s]




 72%|███████▏  | 899/1251 [04:49<01:13,  4.82it/s]




 72%|███████▏  | 900/1251 [04:49<01:31,  3.82it/s]




 72%|███████▏  | 901/1251 [04:50<01:56,  3.02it/s]




 72%|███████▏  | 902/1251 [04:51<02:25,  2.39it/s]




 72%|███████▏  | 903/1251 [04:51<02:05,  2.76it/s]




 72%|███████▏  | 904/1251 [04:51<01:46,  3.27it/s]




 72%|███████▏  | 905/1251 [04:51<01:41,  3.40it/s]




 72%|███████▏  | 906/1251 [04:51<01:36,  3.57it/s]




 73%|███████▎  | 908/1251 [04:52<01:23,  4.09it/s]




 73%|███████▎  | 909/1251 [04:52<01:48,  3.16it/s]




 73%|███████▎  | 910/1251 [04:53<02:18,  2.46it/s]




 73%|███████▎  | 911/1251 [04:53<01:55,  2.94it/s]




 73%|███████▎  | 912/1251 [04:53<01:45,  3.22it/s]




 73%|███████▎  | 913/1251 [04:54<01:30,  3.72it/s]




 73%|███████▎  | 914/1251 [04:54<01:39,  3.37it/s]




 73%|███████▎  | 916/1251 [04:54<01:27,  3.83it/s]




 73%|███████▎  | 917/1251 [04:55<01:40,  3.32it/s]




 73%|███████▎  | 918/1251 [04:55<02:08,  2.59it/s]




 73%|███████▎  | 919/1251 [04:56<01:52,  2.95it/s]




 74%|███████▎  | 920/1251 [04:56<01:48,  3.04it/s]




 74%|███████▎  | 921/1251 [04:56<02:05,  2.62it/s]




 74%|███████▎  | 922/1251 [04:57<01:47,  3.05it/s]




 74%|███████▍  | 923/1251 [04:57<01:38,  3.32it/s]




 74%|███████▍  | 924/1251 [04:57<01:39,  3.29it/s]




 74%|███████▍  | 925/1251 [04:57<01:20,  4.06it/s]




 74%|███████▍  | 926/1251 [04:58<01:56,  2.80it/s]




 74%|███████▍  | 927/1251 [04:58<01:50,  2.92it/s]

 74%|███████▍  | 928/1251 [04:59<02:02,  2.64it/s]




 74%|███████▍  | 929/1251 [04:59<02:03,  2.60it/s]




 74%|███████▍  | 931/1251 [05:00<01:42,  3.13it/s]




 75%|███████▍  | 932/1251 [05:00<01:32,  3.44it/s]




 75%|███████▍  | 933/1251 [05:00<01:23,  3.81it/s]




 75%|███████▍  | 934/1251 [05:00<01:31,  3.48it/s]




 75%|███████▍  | 935/1251 [05:01<01:35,  3.32it/s]




 75%|███████▍  | 936/1251 [05:01<01:56,  2.70it/s]




 75%|███████▍  | 937/1251 [05:02<01:55,  2.72it/s]




 75%|███████▍  | 938/1251 [05:02<01:45,  2.96it/s]




 75%|███████▌  | 939/1251 [05:02<01:39,  3.14it/s]




 75%|███████▌  | 940/1251 [05:02<01:20,  3.85it/s]




 75%|███████▌  | 941/1251 [05:03<01:39,  3.11it/s]




 75%|███████▌  | 942/1251 [05:03<01:45,  2.94it/s]




 75%|███████▌  | 943/1251 [05:03<01:29,  3.45it/s]




 75%|███████▌  | 944/1251 [05:04<01:49,  2.80it/s]




 76%|███████▌  | 945/1251 [05:04<01:36,  3.16it/s]




 76%|███████▌  | 946/1251 [05:04<01:38,  3.11it/s]




 76%|███████▌  | 947/1251 [05:05<01:43,  2.93it/s]




 76%|███████▌  | 949/1251 [05:05<01:28,  3.41it/s]




 76%|███████▌  | 950/1251 [05:06<01:31,  3.30it/s]




 76%|███████▌  | 951/1251 [05:06<01:33,  3.21it/s]




 76%|███████▌  | 952/1251 [05:06<01:39,  3.01it/s]




 76%|███████▌  | 953/1251 [05:07<01:33,  3.20it/s]




 76%|███████▋  | 954/1251 [05:07<01:32,  3.23it/s]




 76%|███████▋  | 955/1251 [05:07<01:40,  2.94it/s]




 76%|███████▋  | 956/1251 [05:07<01:23,  3.54it/s]




 76%|███████▋  | 957/1251 [05:08<01:25,  3.43it/s]




 77%|███████▋  | 958/1251 [05:08<01:25,  3.42it/s]




 77%|███████▋  | 959/1251 [05:08<01:27,  3.35it/s]




 77%|███████▋  | 960/1251 [05:09<01:37,  2.97it/s]




 77%|███████▋  | 961/1251 [05:09<01:27,  3.31it/s]




 77%|███████▋  | 962/1251 [05:09<01:31,  3.15it/s]




 77%|███████▋  | 963/1251 [05:10<01:48,  2.65it/s]




 77%|███████▋  | 964/1251 [05:10<01:28,  3.23it/s]




 77%|███████▋  | 965/1251 [05:10<01:14,  3.82it/s]




 77%|███████▋  | 966/1251 [05:11<01:26,  3.28it/s]




 77%|███████▋  | 967/1251 [05:11<01:23,  3.42it/s]




 77%|███████▋  | 968/1251 [05:11<01:30,  3.13it/s]




 77%|███████▋  | 969/1251 [05:12<01:34,  2.99it/s]




 78%|███████▊  | 970/1251 [05:12<01:21,  3.43it/s]




 78%|███████▊  | 971/1251 [05:12<01:52,  2.50it/s]




 78%|███████▊  | 973/1251 [05:13<01:27,  3.19it/s]




 78%|███████▊  | 974/1251 [05:13<01:17,  3.57it/s]




 78%|███████▊  | 975/1251 [05:13<01:12,  3.79it/s]




 78%|███████▊  | 976/1251 [05:14<01:40,  2.73it/s]




 78%|███████▊  | 977/1251 [05:14<01:45,  2.60it/s]




 78%|███████▊  | 978/1251 [05:14<01:25,  3.20it/s]




 78%|███████▊  | 979/1251 [05:15<01:57,  2.31it/s]




 78%|███████▊  | 980/1251 [05:15<01:31,  2.98it/s]




 78%|███████▊  | 981/1251 [05:15<01:16,  3.54it/s]




 79%|███████▊  | 983/1251 [05:16<01:01,  4.36it/s]




 79%|███████▊  | 984/1251 [05:16<01:26,  3.10it/s]




 79%|███████▊  | 985/1251 [05:17<01:42,  2.61it/s]




 79%|███████▉  | 986/1251 [05:17<01:22,  3.20it/s]




 79%|███████▉  | 987/1251 [05:18<01:47,  2.45it/s]




 79%|███████▉  | 988/1251 [05:18<01:45,  2.50it/s]




 79%|███████▉  | 990/1251 [05:18<01:04,  4.04it/s]




 79%|███████▉  | 991/1251 [05:18<01:01,  4.23it/s]




 79%|███████▉  | 992/1251 [05:19<01:13,  3.54it/s]




 79%|███████▉  | 993/1251 [05:19<01:29,  2.89it/s]




 79%|███████▉  | 994/1251 [05:20<01:27,  2.92it/s]




 80%|███████▉  | 995/1251 [05:20<01:48,  2.36it/s]




 80%|███████▉  | 996/1251 [05:20<01:31,  2.78it/s]




 80%|███████▉  | 997/1251 [05:21<01:12,  3.51it/s]




 80%|███████▉  | 998/1251 [05:21<01:07,  3.76it/s]




 80%|███████▉  | 1000/1251 [05:21<01:11,  3.50it/s]




 80%|████████  | 1001/1251 [05:22<01:18,  3.18it/s]




 80%|████████  | 1002/1251 [05:22<01:21,  3.05it/s]




 80%|████████  | 1003/1251 [05:23<01:40,  2.48it/s]




 80%|████████  | 1004/1251 [05:23<01:25,  2.88it/s]




 80%|████████  | 1006/1251 [05:23<01:08,  3.59it/s]




 81%|████████  | 1008/1251 [05:24<01:09,  3.51it/s]




 81%|████████  | 1009/1251 [05:24<01:12,  3.36it/s]




 81%|████████  | 1010/1251 [05:25<01:10,  3.42it/s]




 81%|████████  | 1011/1251 [05:25<01:37,  2.46it/s]




 81%|████████  | 1012/1251 [05:25<01:22,  2.90it/s]




 81%|████████  | 1014/1251 [05:26<01:06,  3.55it/s]




 81%|████████  | 1016/1251 [05:26<01:05,  3.57it/s]




 81%|████████▏ | 1017/1251 [05:27<01:06,  3.51it/s]




 81%|████████▏ | 1018/1251 [05:27<01:03,  3.67it/s]




 81%|████████▏ | 1019/1251 [05:28<01:41,  2.28it/s]




 82%|████████▏ | 1021/1251 [05:28<01:04,  3.57it/s]




 82%|████████▏ | 1022/1251 [05:28<01:04,  3.53it/s]




 82%|████████▏ | 1024/1251 [05:29<01:04,  3.53it/s]




 82%|████████▏ | 1025/1251 [05:29<01:06,  3.42it/s]




 82%|████████▏ | 1026/1251 [05:30<01:15,  2.97it/s]




 82%|████████▏ | 1027/1251 [05:30<01:34,  2.36it/s]




 82%|████████▏ | 1028/1251 [05:31<01:21,  2.74it/s]




 82%|████████▏ | 1029/1251 [05:31<01:14,  2.98it/s]




 82%|████████▏ | 1031/1251 [05:31<00:52,  4.20it/s]




 82%|████████▏ | 1032/1251 [05:31<00:59,  3.66it/s]




 83%|████████▎ | 1033/1251 [05:32<01:11,  3.05it/s]




 83%|████████▎ | 1034/1251 [05:33<01:25,  2.53it/s]




 83%|████████▎ | 1035/1251 [05:33<01:29,  2.40it/s]




 83%|████████▎ | 1036/1251 [05:33<01:20,  2.67it/s]




 83%|████████▎ | 1038/1251 [05:34<01:06,  3.21it/s]




 83%|████████▎ | 1039/1251 [05:34<00:57,  3.70it/s]




 83%|████████▎ | 1041/1251 [05:34<00:59,  3.52it/s]




 83%|████████▎ | 1042/1251 [05:35<01:07,  3.08it/s]




 83%|████████▎ | 1043/1251 [05:36<01:21,  2.55it/s]




 83%|████████▎ | 1044/1251 [05:36<01:06,  3.10it/s]




 84%|████████▎ | 1045/1251 [05:36<01:06,  3.08it/s]




 84%|████████▎ | 1046/1251 [05:36<01:05,  3.12it/s]




 84%|████████▍ | 1048/1251 [05:37<00:50,  4.04it/s]




 84%|████████▍ | 1049/1251 [05:37<00:52,  3.88it/s]




 84%|████████▍ | 1050/1251 [05:38<01:12,  2.77it/s]




 84%|████████▍ | 1051/1251 [05:38<01:23,  2.38it/s]




 84%|████████▍ | 1053/1251 [05:38<01:00,  3.30it/s]




 84%|████████▍ | 1054/1251 [05:39<01:07,  2.91it/s]




 84%|████████▍ | 1056/1251 [05:39<00:46,  4.16it/s]




 84%|████████▍ | 1057/1251 [05:39<00:52,  3.71it/s]




 85%|████████▍ | 1058/1251 [05:40<01:03,  3.06it/s]




 85%|████████▍ | 1059/1251 [05:41<01:17,  2.46it/s]




 85%|████████▍ | 1061/1251 [05:41<00:56,  3.37it/s]




 85%|████████▍ | 1062/1251 [05:41<01:06,  2.86it/s]

 85%|████████▌ | 1064/1251 [05:42<00:43,  4.30it/s]




 85%|████████▌ | 1065/1251 [05:42<00:49,  3.79it/s]




 85%|████████▌ | 1066/1251 [05:42<01:00,  3.05it/s]




 85%|████████▌ | 1067/1251 [05:43<01:12,  2.54it/s]




 85%|████████▌ | 1069/1251 [05:43<00:52,  3.49it/s]




 86%|████████▌ | 1070/1251 [05:44<01:06,  2.73it/s]




 86%|████████▌ | 1073/1251 [05:44<00:45,  3.95it/s]




 86%|████████▌ | 1074/1251 [05:45<00:53,  3.32it/s]




 86%|████████▌ | 1075/1251 [05:46<01:06,  2.64it/s]




 86%|████████▌ | 1076/1251 [05:46<01:01,  2.87it/s]




 86%|████████▌ | 1078/1251 [05:46<00:57,  3.02it/s]




 86%|████████▋ | 1079/1251 [05:46<00:48,  3.58it/s]




 86%|████████▋ | 1080/1251 [05:47<00:49,  3.45it/s]




 86%|████████▋ | 1081/1251 [05:47<00:42,  4.01it/s]




 86%|████████▋ | 1082/1251 [05:47<00:52,  3.19it/s]




 87%|████████▋ | 1083/1251 [05:48<01:13,  2.28it/s]




 87%|████████▋ | 1084/1251 [05:48<01:00,  2.77it/s]




 87%|████████▋ | 1086/1251 [05:49<01:07,  2.44it/s]




 87%|████████▋ | 1088/1251 [05:49<00:44,  3.64it/s]




 87%|████████▋ | 1089/1251 [05:50<00:46,  3.45it/s]




 87%|████████▋ | 1090/1251 [05:50<00:42,  3.79it/s]




 87%|████████▋ | 1091/1251 [05:51<00:59,  2.68it/s]




 87%|████████▋ | 1092/1251 [05:51<00:55,  2.88it/s]




 87%|████████▋ | 1093/1251 [05:51<00:52,  2.99it/s]




 87%|████████▋ | 1094/1251 [05:52<01:02,  2.50it/s]




 88%|████████▊ | 1095/1251 [05:52<00:49,  3.12it/s]




 88%|████████▊ | 1096/1251 [05:52<00:40,  3.86it/s]




 88%|████████▊ | 1097/1251 [05:52<00:39,  3.93it/s]




 88%|████████▊ | 1098/1251 [05:53<00:38,  3.93it/s]




 88%|████████▊ | 1099/1251 [05:53<01:03,  2.38it/s]




 88%|████████▊ | 1101/1251 [05:54<00:45,  3.27it/s]




 88%|████████▊ | 1102/1251 [05:54<00:57,  2.61it/s]




 88%|████████▊ | 1103/1251 [05:54<00:48,  3.07it/s]




 88%|████████▊ | 1105/1251 [05:55<00:35,  4.12it/s]




 88%|████████▊ | 1106/1251 [05:55<00:35,  4.04it/s]




 88%|████████▊ | 1107/1251 [05:56<00:54,  2.65it/s]




 89%|████████▊ | 1109/1251 [05:56<00:41,  3.38it/s]




 89%|████████▊ | 1110/1251 [05:57<01:00,  2.33it/s]




 89%|████████▉ | 1112/1251 [05:57<00:41,  3.34it/s]




 89%|████████▉ | 1113/1251 [05:57<00:39,  3.45it/s]




 89%|████████▉ | 1114/1251 [05:58<00:33,  4.09it/s]




 89%|████████▉ | 1115/1251 [05:58<00:47,  2.87it/s]




 89%|████████▉ | 1116/1251 [05:58<00:44,  3.03it/s]




 89%|████████▉ | 1118/1251 [06:00<00:57,  2.30it/s]




 89%|████████▉ | 1119/1251 [06:00<00:47,  2.79it/s]




 90%|████████▉ | 1121/1251 [06:00<00:35,  3.63it/s]




 90%|████████▉ | 1123/1251 [06:01<00:40,  3.14it/s]




 90%|████████▉ | 1125/1251 [06:01<00:32,  3.93it/s]




 90%|█████████ | 1126/1251 [06:02<00:48,  2.57it/s]




 90%|█████████ | 1127/1251 [06:02<00:41,  2.96it/s]




 90%|█████████ | 1129/1251 [06:03<00:36,  3.32it/s]




 90%|█████████ | 1130/1251 [06:03<00:31,  3.84it/s]




 90%|█████████ | 1131/1251 [06:03<00:36,  3.27it/s]




 90%|█████████ | 1132/1251 [06:03<00:32,  3.72it/s]




 91%|█████████ | 1133/1251 [06:04<00:31,  3.80it/s]




 91%|█████████ | 1134/1251 [06:05<00:50,  2.31it/s]




 91%|█████████ | 1135/1251 [06:05<00:45,  2.56it/s]




 91%|█████████ | 1136/1251 [06:05<00:39,  2.92it/s]




 91%|█████████ | 1137/1251 [06:05<00:31,  3.68it/s]




 91%|█████████ | 1139/1251 [06:06<00:39,  2.83it/s]




 91%|█████████ | 1140/1251 [06:06<00:34,  3.22it/s]




 91%|█████████ | 1141/1251 [06:06<00:32,  3.38it/s]




 91%|█████████▏| 1142/1251 [06:07<00:36,  2.95it/s]




 91%|█████████▏| 1143/1251 [06:07<00:36,  2.97it/s]




 91%|█████████▏| 1144/1251 [06:08<00:35,  3.02it/s]




 92%|█████████▏| 1145/1251 [06:08<00:30,  3.49it/s]




 92%|█████████▏| 1147/1251 [06:09<00:36,  2.84it/s]




 92%|█████████▏| 1149/1251 [06:09<00:28,  3.53it/s]




 92%|█████████▏| 1150/1251 [06:10<00:35,  2.88it/s]




 92%|█████████▏| 1151/1251 [06:10<00:33,  2.99it/s]




 92%|█████████▏| 1152/1251 [06:10<00:29,  3.41it/s]




 92%|█████████▏| 1153/1251 [06:10<00:26,  3.66it/s]




 92%|█████████▏| 1155/1251 [06:11<00:34,  2.78it/s]




 92%|█████████▏| 1157/1251 [06:12<00:27,  3.38it/s]




 93%|█████████▎| 1158/1251 [06:12<00:31,  2.95it/s]




 93%|█████████▎| 1159/1251 [06:12<00:28,  3.22it/s]




 93%|█████████▎| 1160/1251 [06:12<00:26,  3.44it/s]




 93%|█████████▎| 1161/1251 [06:13<00:24,  3.63it/s]




 93%|█████████▎| 1163/1251 [06:14<00:29,  3.00it/s]




 93%|█████████▎| 1164/1251 [06:14<00:24,  3.54it/s]




 93%|█████████▎| 1165/1251 [06:14<00:24,  3.47it/s]




 93%|█████████▎| 1166/1251 [06:14<00:29,  2.87it/s]




 93%|█████████▎| 1167/1251 [06:15<00:27,  3.10it/s]




 93%|█████████▎| 1168/1251 [06:15<00:22,  3.72it/s]




 93%|█████████▎| 1169/1251 [06:15<00:22,  3.66it/s]




 94%|█████████▎| 1171/1251 [06:16<00:29,  2.71it/s]




 94%|█████████▍| 1173/1251 [06:17<00:23,  3.27it/s]




 94%|█████████▍| 1174/1251 [06:17<00:25,  3.03it/s]




 94%|█████████▍| 1175/1251 [06:17<00:24,  3.04it/s]




 94%|█████████▍| 1176/1251 [06:17<00:21,  3.49it/s]




 94%|█████████▍| 1177/1251 [06:18<00:19,  3.80it/s]




 94%|█████████▍| 1178/1251 [06:18<00:20,  3.53it/s]




 94%|█████████▍| 1179/1251 [06:19<00:25,  2.80it/s]




 94%|█████████▍| 1180/1251 [06:19<00:21,  3.35it/s]




 94%|█████████▍| 1181/1251 [06:19<00:20,  3.37it/s]




 94%|█████████▍| 1182/1251 [06:20<00:30,  2.28it/s]




 95%|█████████▍| 1183/1251 [06:20<00:23,  2.89it/s]




 95%|█████████▍| 1184/1251 [06:20<00:20,  3.27it/s]




 95%|█████████▍| 1185/1251 [06:20<00:17,  3.82it/s]




 95%|█████████▍| 1186/1251 [06:21<00:21,  3.05it/s]




 95%|█████████▍| 1187/1251 [06:21<00:18,  3.51it/s]




 95%|█████████▍| 1188/1251 [06:21<00:23,  2.68it/s]




 95%|█████████▌| 1189/1251 [06:22<00:18,  3.34it/s]




 95%|█████████▌| 1190/1251 [06:22<00:24,  2.49it/s]




 95%|█████████▌| 1191/1251 [06:22<00:19,  3.12it/s]




 95%|█████████▌| 1192/1251 [06:23<00:18,  3.27it/s]




 95%|█████████▌| 1193/1251 [06:23<00:16,  3.49it/s]




 95%|█████████▌| 1194/1251 [06:23<00:17,  3.23it/s]




 96%|█████████▌| 1195/1251 [06:24<00:18,  3.05it/s]




 96%|█████████▌| 1196/1251 [06:24<00:20,  2.70it/s]




 96%|█████████▌| 1197/1251 [06:24<00:16,  3.20it/s]




 96%|█████████▌| 1198/1251 [06:25<00:17,  2.99it/s]




 96%|█████████▌| 1199/1251 [06:25<00:19,  2.65it/s]




 96%|█████████▌| 1201/1251 [06:26<00:16,  3.12it/s]




 96%|█████████▌| 1203/1251 [06:26<00:13,  3.63it/s]

 96%|█████████▌| 1204/1251 [06:27<00:16,  2.81it/s]




 96%|█████████▋| 1205/1251 [06:27<00:13,  3.38it/s]




 96%|█████████▋| 1206/1251 [06:27<00:14,  3.04it/s]




 96%|█████████▋| 1207/1251 [06:28<00:14,  2.96it/s]




 97%|█████████▋| 1209/1251 [06:28<00:13,  3.20it/s]




 97%|█████████▋| 1211/1251 [06:28<00:09,  4.01it/s]




 97%|█████████▋| 1212/1251 [06:29<00:13,  2.94it/s]




 97%|█████████▋| 1214/1251 [06:30<00:11,  3.23it/s]




 97%|█████████▋| 1215/1251 [06:30<00:11,  3.17it/s]




 97%|█████████▋| 1217/1251 [06:31<00:10,  3.32it/s]




 97%|█████████▋| 1219/1251 [06:31<00:08,  3.97it/s]




 98%|█████████▊| 1220/1251 [06:32<00:10,  2.88it/s]




 98%|█████████▊| 1221/1251 [06:32<00:08,  3.36it/s]




 98%|█████████▊| 1222/1251 [06:32<00:08,  3.28it/s]




 98%|█████████▊| 1223/1251 [06:32<00:09,  2.97it/s]




 98%|█████████▊| 1225/1251 [06:33<00:08,  3.10it/s]




 98%|█████████▊| 1226/1251 [06:33<00:07,  3.48it/s]




 98%|█████████▊| 1228/1251 [06:34<00:07,  2.91it/s]




 98%|█████████▊| 1229/1251 [06:34<00:06,  3.17it/s]




 98%|█████████▊| 1230/1251 [06:35<00:07,  2.79it/s]




 98%|█████████▊| 1232/1251 [06:35<00:05,  3.49it/s]




 99%|█████████▊| 1233/1251 [06:36<00:05,  3.39it/s]




 99%|█████████▊| 1234/1251 [06:36<00:05,  3.08it/s]




 99%|█████████▊| 1235/1251 [06:36<00:04,  3.41it/s]




 99%|█████████▉| 1236/1251 [06:37<00:04,  3.09it/s]




 99%|█████████▉| 1237/1251 [06:37<00:04,  2.90it/s]




 99%|█████████▉| 1238/1251 [06:37<00:04,  2.73it/s]




 99%|█████████▉| 1239/1251 [06:38<00:04,  2.81it/s]




 99%|█████████▉| 1240/1251 [06:38<00:03,  2.91it/s]




 99%|█████████▉| 1242/1251 [06:38<00:02,  3.57it/s]




 99%|█████████▉| 1243/1251 [06:39<00:02,  3.16it/s]




 99%|█████████▉| 1244/1251 [06:39<00:01,  3.79it/s]




100%|█████████▉| 1245/1251 [06:39<00:02,  2.94it/s]




100%|█████████▉| 1246/1251 [06:40<00:01,  2.65it/s]




100%|█████████▉| 1247/1251 [06:40<00:01,  2.76it/s]




100%|█████████▉| 1248/1251 [06:41<00:01,  2.96it/s]




100%|█████████▉| 1250/1251 [06:41<00:00,  4.40it/s]




100%|██████████| 1251/1251 [06:41<00:00,  3.12it/s]
Multiplets | family 3:   0%|          | 0/144 [07:16<?, ?it/s]
Multiplets | family 4:   0%|          | 0/1251 [06:41<?, ?it/s]



Multiplets | family 5:   0%|          | 0/1460 [00:00<?, ?it/s]



  0%|          | 0/1460 [00:00<?, ?it/s]



  0%|          | 1/1460 [00:03<1:16:52,  3.16s/it]



  0%|          | 6/1460 [00:03<09:50,  2.46it/s]



  1%|          | 9/1460 [00:06<15:55,  1.52it/s]



  1%|          | 14/1460 [00:06<08:07,  2.96it/s]



  1%|          | 17/1460 [00:09<13:03,  1.84it/s]



  1%|▏         | 19/1460 [00:09<10:36,  2.26it/s]



  1%|▏         | 21/1460 [00:09<08:23,  2.86it/s]



  2%|▏         | 23/1460 [00:09<06:39,  3.60it/s]



  2%|▏         | 25/1460 [00:12<13:47,  1.73it/s]



  2%|▏         | 27/1460 [00:12<10:44,  2.22it/s]



  2%|▏         | 30/1460 [00:13<07:45,  3.07it/s]



  2%|▏         | 31/1460 [00:13<07:25,  3.20it/s]



  2%|▏         | 33/1460 [00:15<13:07,  1.81it/s]



  2%|▏         | 34/1460 [00:16<12:09,  1.96it/s]



  3%|▎         | 37/1460 [00:16<08:32,  2.78it/s]



  3%|▎         | 38/1460 [00:16<08:08,  2.91it/s]



  3%|▎         | 39/1460 [00:16<07:21,  3.22it/s]



  3%|▎         | 41/1460 [00:18<13:14,  1.79it/s]



  3%|▎         | 42/1460 [00:19<12:02,  1.96it/s]



  3%|▎         | 45/1460 [00:19<07:46,  3.03it/s]



  3%|▎         | 46/1460 [00:19<07:45,  3.04it/s]



  3%|▎         | 48/1460 [00:20<05:42,  4.13it/s]



  3%|▎         | 49/1460 [00:22<13:39,  1.72it/s]



  3%|▎         | 50/1460 [00:22<12:07,  1.94it/s]



  4%|▎         | 52/1460 [00:22<08:08,  2.88it/s]



  4%|▎         | 53/1460 [00:22<07:30,  3.12it/s]



  4%|▎         | 54/1460 [00:23<07:54,  2.96it/s]



  4%|▍         | 55/1460 [00:23<06:59,  3.35it/s]



  4%|▍         | 56/1460 [00:23<07:57,  2.94it/s]



  4%|▍         | 57/1460 [00:25<14:59,  1.56it/s]



  4%|▍         | 58/1460 [00:25<14:13,  1.64it/s]



  4%|▍         | 59/1460 [00:25<11:29,  2.03it/s]



  4%|▍         | 60/1460 [00:26<11:01,  2.12it/s]



  4%|▍         | 61/1460 [00:26<09:10,  2.54it/s]



  4%|▍         | 62/1460 [00:26<08:25,  2.77it/s]



  4%|▍         | 63/1460 [00:27<09:49,  2.37it/s]



  4%|▍         | 65/1460 [00:28<13:01,  1.78it/s]



  5%|▍         | 67/1460 [00:29<10:11,  2.28it/s]



  5%|▍         | 69/1460 [00:29<08:49,  2.63it/s]



  5%|▍         | 70/1460 [00:30<08:15,  2.80it/s]



  5%|▍         | 71/1460 [00:30<08:18,  2.79it/s]



  5%|▍         | 72/1460 [00:30<07:00,  3.30it/s]



  5%|▌         | 73/1460 [00:32<13:23,  1.73it/s]



  5%|▌         | 74/1460 [00:32<11:42,  1.97it/s]



  5%|▌         | 75/1460 [00:32<09:09,  2.52it/s]



  5%|▌         | 76/1460 [00:32<07:22,  3.13it/s]



  5%|▌         | 77/1460 [00:33<10:18,  2.24it/s]



  5%|▌         | 79/1460 [00:33<07:53,  2.92it/s]



  5%|▌         | 80/1460 [00:33<06:42,  3.43it/s]



  6%|▌         | 81/1460 [00:35<12:16,  1.87it/s]



  6%|▌         | 82/1460 [00:35<12:07,  1.89it/s]



  6%|▌         | 85/1460 [00:36<09:17,  2.46it/s]



  6%|▌         | 86/1460 [00:36<09:01,  2.54it/s]



  6%|▌         | 87/1460 [00:37<09:02,  2.53it/s]



  6%|▌         | 88/1460 [00:37<08:05,  2.82it/s]



  6%|▌         | 89/1460 [00:38<12:31,  1.82it/s]



  6%|▌         | 90/1460 [00:39<12:56,  1.76it/s]



  6%|▋         | 92/1460 [00:39<07:53,  2.89it/s]



  6%|▋         | 93/1460 [00:39<08:41,  2.62it/s]



  6%|▋         | 94/1460 [00:40<10:26,  2.18it/s]



  7%|▋         | 95/1460 [00:40<09:49,  2.32it/s]



  7%|▋         | 96/1460 [00:41<07:49,  2.91it/s]



  7%|▋         | 97/1460 [00:42<12:45,  1.78it/s]



  7%|▋         | 98/1460 [00:42<12:24,  1.83it/s]



  7%|▋         | 100/1460 [00:43<08:43,  2.60it/s]



  7%|▋         | 101/1460 [00:43<07:59,  2.84it/s]



  7%|▋         | 102/1460 [00:44<10:43,  2.11it/s]



  7%|▋         | 103/1460 [00:44<10:21,  2.18it/s]



  7%|▋         | 104/1460 [00:44<08:56,  2.53it/s]



  7%|▋         | 105/1460 [00:45<10:13,  2.21it/s]



  7%|▋         | 106/1460 [00:45<10:34,  2.13it/s]



  7%|▋         | 108/1460 [00:46<08:09,  2.76it/s]



  7%|▋         | 109/1460 [00:46<09:00,  2.50it/s]



  8%|▊         | 110/1460 [00:47<12:00,  1.87it/s]



  8%|▊         | 112/1460 [00:48<08:48,  2.55it/s]



  8%|▊         | 113/1460 [00:48<09:50,  2.28it/s]



  8%|▊         | 114/1460 [00:49<09:13,  2.43it/s]



  8%|▊         | 115/1460 [00:49<07:56,  2.82it/s]



  8%|▊         | 116/1460 [00:49<08:50,  2.53it/s]



  8%|▊         | 117/1460 [00:50<08:04,  2.77it/s]

  8%|▊         | 118/1460 [00:51<11:51,  1.89it/s]



  8%|▊         | 120/1460 [00:51<08:26,  2.65it/s]



  8%|▊         | 121/1460 [00:52<10:19,  2.16it/s]



  8%|▊         | 122/1460 [00:52<08:32,  2.61it/s]



  8%|▊         | 123/1460 [00:52<08:10,  2.72it/s]



  8%|▊         | 124/1460 [00:52<08:20,  2.67it/s]



  9%|▊         | 125/1460 [00:53<08:04,  2.75it/s]



  9%|▊         | 126/1460 [00:54<11:42,  1.90it/s]



  9%|▉         | 128/1460 [00:54<07:28,  2.97it/s]



  9%|▉         | 129/1460 [00:55<10:44,  2.07it/s]



  9%|▉         | 130/1460 [00:55<08:42,  2.54it/s]



  9%|▉         | 131/1460 [00:55<08:03,  2.75it/s]



  9%|▉         | 132/1460 [00:56<07:32,  2.93it/s]



  9%|▉         | 133/1460 [00:56<08:04,  2.74it/s]



  9%|▉         | 134/1460 [00:57<12:10,  1.81it/s]



  9%|▉         | 136/1460 [00:57<07:56,  2.78it/s]



  9%|▉         | 137/1460 [00:58<10:37,  2.08it/s]



  9%|▉         | 138/1460 [00:58<09:42,  2.27it/s]



 10%|▉         | 140/1460 [00:59<07:08,  3.08it/s]



 10%|▉         | 141/1460 [00:59<07:52,  2.79it/s]



 10%|▉         | 142/1460 [01:01<12:36,  1.74it/s]



 10%|▉         | 143/1460 [01:01<09:59,  2.20it/s]



 10%|▉         | 145/1460 [01:01<08:44,  2.51it/s]



 10%|█         | 146/1460 [01:02<08:14,  2.66it/s]



 10%|█         | 147/1460 [01:02<07:43,  2.84it/s]



 10%|█         | 149/1460 [01:03<08:38,  2.53it/s]



 10%|█         | 150/1460 [01:04<11:37,  1.88it/s]



 10%|█         | 152/1460 [01:04<07:35,  2.87it/s]



 10%|█         | 153/1460 [01:04<08:48,  2.47it/s]



 11%|█         | 154/1460 [01:05<07:32,  2.89it/s]



 11%|█         | 155/1460 [01:05<08:38,  2.52it/s]



 11%|█         | 157/1460 [01:06<09:03,  2.40it/s]



 11%|█         | 158/1460 [01:07<11:01,  1.97it/s]



 11%|█         | 160/1460 [01:07<07:16,  2.98it/s]



 11%|█         | 161/1460 [01:08<08:45,  2.47it/s]



 11%|█         | 163/1460 [01:08<08:11,  2.64it/s]



 11%|█         | 164/1460 [01:08<06:59,  3.09it/s]



 11%|█▏        | 165/1460 [01:09<09:11,  2.35it/s]



 11%|█▏        | 166/1460 [01:10<10:56,  1.97it/s]



 11%|█▏        | 167/1460 [01:10<08:50,  2.44it/s]



 12%|█▏        | 168/1460 [01:10<07:47,  2.76it/s]



 12%|█▏        | 169/1460 [01:11<08:28,  2.54it/s]



 12%|█▏        | 171/1460 [01:12<08:16,  2.60it/s]



 12%|█▏        | 172/1460 [01:12<07:25,  2.89it/s]



 12%|█▏        | 173/1460 [01:13<09:53,  2.17it/s]



 12%|█▏        | 174/1460 [01:13<10:11,  2.10it/s]



 12%|█▏        | 175/1460 [01:13<08:48,  2.43it/s]



 12%|█▏        | 176/1460 [01:14<07:36,  2.81it/s]



 12%|█▏        | 177/1460 [01:14<08:09,  2.62it/s]



 12%|█▏        | 178/1460 [01:14<06:59,  3.06it/s]



 12%|█▏        | 179/1460 [01:15<09:05,  2.35it/s]



 12%|█▏        | 180/1460 [01:15<08:24,  2.54it/s]



 12%|█▏        | 181/1460 [01:16<13:16,  1.61it/s]



 12%|█▏        | 182/1460 [01:17<10:45,  1.98it/s]



 13%|█▎        | 183/1460 [01:17<08:51,  2.40it/s]



 13%|█▎        | 185/1460 [01:18<08:29,  2.50it/s]



 13%|█▎        | 187/1460 [01:18<08:04,  2.63it/s]



 13%|█▎        | 189/1460 [01:20<10:03,  2.11it/s]



 13%|█▎        | 190/1460 [01:20<09:46,  2.17it/s]



 13%|█▎        | 192/1460 [01:20<07:11,  2.94it/s]



 13%|█▎        | 193/1460 [01:21<07:23,  2.86it/s]



 13%|█▎        | 194/1460 [01:21<06:34,  3.21it/s]



 13%|█▎        | 195/1460 [01:21<08:13,  2.56it/s]



 13%|█▎        | 196/1460 [01:22<07:11,  2.93it/s]



 13%|█▎        | 197/1460 [01:23<11:40,  1.80it/s]



 14%|█▎        | 198/1460 [01:23<10:23,  2.03it/s]



 14%|█▎        | 199/1460 [01:23<08:22,  2.51it/s]



 14%|█▎        | 200/1460 [01:23<07:16,  2.89it/s]



 14%|█▍        | 201/1460 [01:24<07:26,  2.82it/s]



 14%|█▍        | 203/1460 [01:25<07:41,  2.73it/s]



 14%|█▍        | 204/1460 [01:25<07:15,  2.88it/s]



 14%|█▍        | 205/1460 [01:26<10:54,  1.92it/s]



 14%|█▍        | 206/1460 [01:26<09:55,  2.11it/s]



 14%|█▍        | 207/1460 [01:27<09:10,  2.28it/s]



 14%|█▍        | 208/1460 [01:27<07:10,  2.91it/s]



 14%|█▍        | 209/1460 [01:27<07:22,  2.83it/s]



 14%|█▍        | 211/1460 [01:28<08:22,  2.49it/s]



 15%|█▍        | 213/1460 [01:29<09:55,  2.09it/s]



 15%|█▍        | 214/1460 [01:30<09:05,  2.28it/s]



 15%|█▍        | 215/1460 [01:30<08:57,  2.32it/s]



 15%|█▍        | 217/1460 [01:30<07:18,  2.84it/s]



 15%|█▍        | 218/1460 [01:31<06:13,  3.32it/s]



 15%|█▌        | 219/1460 [01:31<08:03,  2.57it/s]



 15%|█▌        | 220/1460 [01:31<07:00,  2.95it/s]



 15%|█▌        | 221/1460 [01:32<10:44,  1.92it/s]



 15%|█▌        | 222/1460 [01:33<09:08,  2.26it/s]



 15%|█▌        | 223/1460 [01:33<09:23,  2.20it/s]



 15%|█▌        | 224/1460 [01:34<09:15,  2.22it/s]



 15%|█▌        | 226/1460 [01:34<07:45,  2.65it/s]



 16%|█▌        | 227/1460 [01:34<07:40,  2.68it/s]



 16%|█▌        | 228/1460 [01:35<07:57,  2.58it/s]



 16%|█▌        | 229/1460 [01:36<09:55,  2.07it/s]



 16%|█▌        | 230/1460 [01:36<08:00,  2.56it/s]



 16%|█▌        | 231/1460 [01:36<09:33,  2.14it/s]



 16%|█▌        | 232/1460 [01:37<08:13,  2.49it/s]



 16%|█▌        | 234/1460 [01:38<08:14,  2.48it/s]



 16%|█▌        | 235/1460 [01:38<07:00,  2.92it/s]



 16%|█▌        | 236/1460 [01:38<07:36,  2.68it/s]



 16%|█▌        | 237/1460 [01:39<09:07,  2.23it/s]



 16%|█▋        | 238/1460 [01:39<08:04,  2.52it/s]



 16%|█▋        | 239/1460 [01:40<08:52,  2.29it/s]



 16%|█▋        | 240/1460 [01:40<07:42,  2.64it/s]



 17%|█▋        | 242/1460 [01:41<07:50,  2.59it/s]



 17%|█▋        | 243/1460 [01:41<07:13,  2.80it/s]



 17%|█▋        | 244/1460 [01:41<08:06,  2.50it/s]



 17%|█▋        | 245/1460 [01:42<08:54,  2.27it/s]



 17%|█▋        | 246/1460 [01:42<07:40,  2.64it/s]



 17%|█▋        | 247/1460 [01:43<09:45,  2.07it/s]



 17%|█▋        | 250/1460 [01:44<07:29,  2.69it/s]



 17%|█▋        | 251/1460 [01:44<07:22,  2.73it/s]



 17%|█▋        | 252/1460 [01:45<08:08,  2.47it/s]



 17%|█▋        | 253/1460 [01:45<09:40,  2.08it/s]



 17%|█▋        | 254/1460 [01:45<07:50,  2.56it/s]



 17%|█▋        | 255/1460 [01:46<09:22,  2.14it/s]



 18%|█▊        | 257/1460 [01:46<05:51,  3.42it/s]



 18%|█▊        | 258/1460 [01:47<08:41,  2.30it/s]



 18%|█▊        | 259/1460 [01:47<07:31,  2.66it/s]



 18%|█▊        | 260/1460 [01:48<07:14,  2.76it/s]



 18%|█▊        | 261/1460 [01:49<10:42,  1.87it/s]



 18%|█▊        | 263/1460 [01:49<08:01,  2.49it/s]



 18%|█▊        | 264/1460 [01:49<07:30,  2.66it/s]



 18%|█▊        | 265/1460 [01:50<06:30,  3.06it/s]



 18%|█▊        | 266/1460 [01:51<09:45,  2.04it/s]



 18%|█▊        | 268/1460 [01:51<07:05,  2.80it/s]

 18%|█▊        | 269/1460 [01:52<10:25,  1.90it/s]



 18%|█▊        | 270/1460 [01:52<08:18,  2.39it/s]



 19%|█▊        | 271/1460 [01:53<08:07,  2.44it/s]



 19%|█▊        | 272/1460 [01:53<06:35,  3.00it/s]



 19%|█▊        | 273/1460 [01:53<06:12,  3.19it/s]



 19%|█▉        | 274/1460 [01:54<10:03,  1.97it/s]



 19%|█▉        | 276/1460 [01:54<06:25,  3.07it/s]



 19%|█▉        | 277/1460 [01:55<10:17,  1.92it/s]



 19%|█▉        | 278/1460 [01:56<09:00,  2.19it/s]



 19%|█▉        | 280/1460 [01:56<06:54,  2.85it/s]



 19%|█▉        | 281/1460 [01:56<06:44,  2.92it/s]



 19%|█▉        | 282/1460 [01:57<08:54,  2.20it/s]



 19%|█▉        | 283/1460 [01:57<07:58,  2.46it/s]



 20%|█▉        | 285/1460 [01:59<10:43,  1.83it/s]



 20%|█▉        | 286/1460 [01:59<08:49,  2.22it/s]



 20%|█▉        | 287/1460 [01:59<07:28,  2.61it/s]



 20%|█▉        | 288/1460 [01:59<07:28,  2.61it/s]



 20%|█▉        | 289/1460 [02:00<05:58,  3.27it/s]



 20%|█▉        | 290/1460 [02:00<08:36,  2.26it/s]



 20%|█▉        | 291/1460 [02:01<07:52,  2.47it/s]



 20%|██        | 293/1460 [02:02<11:22,  1.71it/s]



 20%|██        | 295/1460 [02:03<08:18,  2.34it/s]



 20%|██        | 297/1460 [02:03<06:29,  2.99it/s]



 20%|██        | 298/1460 [02:04<08:42,  2.22it/s]



 20%|██        | 299/1460 [02:04<08:19,  2.33it/s]



 21%|██        | 301/1460 [02:06<09:50,  1.96it/s]



 21%|██        | 302/1460 [02:06<09:00,  2.14it/s]



 21%|██        | 303/1460 [02:06<07:22,  2.62it/s]



 21%|██        | 305/1460 [02:06<06:23,  3.01it/s]



 21%|██        | 306/1460 [02:07<07:52,  2.44it/s]



 21%|██        | 307/1460 [02:08<08:27,  2.27it/s]



 21%|██        | 309/1460 [02:09<09:48,  1.96it/s]



 21%|██        | 310/1460 [02:09<08:25,  2.27it/s]



 21%|██▏       | 311/1460 [02:09<07:23,  2.59it/s]



 21%|██▏       | 313/1460 [02:10<06:04,  3.15it/s]



 22%|██▏       | 314/1460 [02:10<07:12,  2.65it/s]



 22%|██▏       | 315/1460 [02:11<08:29,  2.25it/s]



 22%|██▏       | 317/1460 [02:12<09:31,  2.00it/s]



 22%|██▏       | 318/1460 [02:12<07:55,  2.40it/s]



 22%|██▏       | 319/1460 [02:13<07:16,  2.61it/s]



 22%|██▏       | 321/1460 [02:13<06:15,  3.04it/s]



 22%|██▏       | 322/1460 [02:14<07:59,  2.38it/s]



 22%|██▏       | 323/1460 [02:14<08:00,  2.37it/s]



 22%|██▏       | 324/1460 [02:15<08:48,  2.15it/s]



 22%|██▏       | 325/1460 [02:15<09:00,  2.10it/s]



 22%|██▏       | 326/1460 [02:16<08:24,  2.25it/s]



 22%|██▏       | 327/1460 [02:16<06:46,  2.79it/s]



 23%|██▎       | 329/1460 [02:17<07:52,  2.39it/s]



 23%|██▎       | 330/1460 [02:17<08:26,  2.23it/s]



 23%|██▎       | 331/1460 [02:18<07:09,  2.63it/s]



 23%|██▎       | 332/1460 [02:18<09:18,  2.02it/s]



 23%|██▎       | 333/1460 [02:19<07:36,  2.47it/s]



 23%|██▎       | 334/1460 [02:19<08:08,  2.31it/s]



 23%|██▎       | 336/1460 [02:19<05:04,  3.69it/s]



 23%|██▎       | 337/1460 [02:20<08:53,  2.10it/s]



 23%|██▎       | 338/1460 [02:21<08:00,  2.33it/s]



 23%|██▎       | 339/1460 [02:21<06:55,  2.70it/s]



 23%|██▎       | 340/1460 [02:22<09:00,  2.07it/s]



 23%|██▎       | 341/1460 [02:22<09:39,  1.93it/s]



 23%|██▎       | 342/1460 [02:22<07:42,  2.42it/s]



 23%|██▎       | 343/1460 [02:22<06:05,  3.05it/s]



 24%|██▎       | 345/1460 [02:24<08:12,  2.27it/s]



 24%|██▎       | 346/1460 [02:24<07:10,  2.59it/s]



 24%|██▍       | 347/1460 [02:24<06:33,  2.83it/s]



 24%|██▍       | 348/1460 [02:25<08:28,  2.19it/s]



 24%|██▍       | 349/1460 [02:25<09:10,  2.02it/s]



 24%|██▍       | 350/1460 [02:26<07:27,  2.48it/s]



 24%|██▍       | 351/1460 [02:26<06:07,  3.02it/s]



 24%|██▍       | 352/1460 [02:26<05:15,  3.51it/s]



 24%|██▍       | 353/1460 [02:27<09:40,  1.91it/s]



 24%|██▍       | 355/1460 [02:27<06:58,  2.64it/s]



 24%|██▍       | 356/1460 [02:28<07:47,  2.36it/s]



 24%|██▍       | 357/1460 [02:29<09:09,  2.01it/s]



 25%|██▍       | 358/1460 [02:29<07:13,  2.54it/s]



 25%|██▍       | 359/1460 [02:29<06:23,  2.87it/s]



 25%|██▍       | 361/1460 [02:30<08:04,  2.27it/s]



 25%|██▍       | 362/1460 [02:30<06:55,  2.64it/s]



 25%|██▍       | 363/1460 [02:31<06:45,  2.70it/s]



 25%|██▍       | 364/1460 [02:31<07:51,  2.32it/s]



 25%|██▌       | 365/1460 [02:32<08:35,  2.12it/s]



 25%|██▌       | 366/1460 [02:32<06:58,  2.61it/s]



 25%|██▌       | 367/1460 [02:32<07:06,  2.56it/s]



 25%|██▌       | 368/1460 [02:32<05:34,  3.27it/s]



 25%|██▌       | 369/1460 [02:33<08:25,  2.16it/s]



 25%|██▌       | 370/1460 [02:34<07:00,  2.59it/s]



 25%|██▌       | 371/1460 [02:34<07:44,  2.34it/s]



 25%|██▌       | 372/1460 [02:35<07:53,  2.30it/s]



 26%|██▌       | 373/1460 [02:35<10:17,  1.76it/s]



 26%|██▌       | 374/1460 [02:36<07:55,  2.29it/s]



 26%|██▌       | 375/1460 [02:36<06:05,  2.97it/s]



 26%|██▌       | 376/1460 [02:36<04:55,  3.66it/s]



 26%|██▌       | 377/1460 [02:36<07:10,  2.52it/s]



 26%|██▌       | 378/1460 [02:37<08:04,  2.23it/s]



 26%|██▌       | 379/1460 [02:37<06:44,  2.67it/s]



 26%|██▌       | 380/1460 [02:38<09:41,  1.86it/s]



 26%|██▌       | 381/1460 [02:39<10:06,  1.78it/s]



 26%|██▌       | 383/1460 [02:39<06:03,  2.96it/s]



 26%|██▋       | 384/1460 [02:39<05:48,  3.09it/s]



 26%|██▋       | 385/1460 [02:40<05:54,  3.03it/s]



 26%|██▋       | 386/1460 [02:40<07:47,  2.30it/s]



 27%|██▋       | 387/1460 [02:41<07:20,  2.44it/s]



 27%|██▋       | 388/1460 [02:42<11:25,  1.56it/s]



 27%|██▋       | 389/1460 [02:42<08:37,  2.07it/s]



 27%|██▋       | 390/1460 [02:42<06:54,  2.58it/s]



 27%|██▋       | 391/1460 [02:43<07:46,  2.29it/s]



 27%|██▋       | 393/1460 [02:43<06:27,  2.75it/s]



 27%|██▋       | 394/1460 [02:44<06:57,  2.55it/s]



 27%|██▋       | 395/1460 [02:44<06:07,  2.89it/s]



 27%|██▋       | 396/1460 [02:45<09:28,  1.87it/s]



 27%|██▋       | 398/1460 [02:45<06:36,  2.68it/s]



 27%|██▋       | 399/1460 [02:46<07:19,  2.41it/s]



 27%|██▋       | 401/1460 [02:46<06:10,  2.86it/s]



 28%|██▊       | 402/1460 [02:47<07:25,  2.38it/s]



 28%|██▊       | 404/1460 [02:48<08:22,  2.10it/s]



 28%|██▊       | 406/1460 [02:49<07:10,  2.45it/s]



 28%|██▊       | 407/1460 [02:49<06:47,  2.58it/s]



 28%|██▊       | 408/1460 [02:49<07:17,  2.40it/s]



 28%|██▊       | 410/1460 [02:50<07:14,  2.42it/s]



 28%|██▊       | 411/1460 [02:51<06:39,  2.62it/s]



 28%|██▊       | 412/1460 [02:51<07:50,  2.23it/s]



 28%|██▊       | 413/1460 [02:52<07:33,  2.31it/s]



 28%|██▊       | 414/1460 [02:52<07:51,  2.22it/s]



 28%|██▊       | 415/1460 [02:53<07:44,  2.25it/s]



 29%|██▊       | 417/1460 [02:53<05:56,  2.93it/s]

 29%|██▊       | 418/1460 [02:53<06:30,  2.67it/s]



 29%|██▊       | 419/1460 [02:54<05:57,  2.91it/s]



 29%|██▉       | 420/1460 [02:54<07:40,  2.26it/s]



 29%|██▉       | 421/1460 [02:55<07:52,  2.20it/s]



 29%|██▉       | 422/1460 [02:55<07:59,  2.17it/s]



 29%|██▉       | 423/1460 [02:56<07:17,  2.37it/s]



 29%|██▉       | 424/1460 [02:56<06:13,  2.78it/s]



 29%|██▉       | 425/1460 [02:56<05:26,  3.17it/s]



 29%|██▉       | 426/1460 [02:57<06:04,  2.84it/s]



 29%|██▉       | 427/1460 [02:57<07:00,  2.46it/s]



 29%|██▉       | 428/1460 [02:58<07:26,  2.31it/s]



 29%|██▉       | 429/1460 [02:58<07:34,  2.27it/s]



 29%|██▉       | 430/1460 [02:59<08:07,  2.11it/s]



 30%|██▉       | 431/1460 [02:59<08:17,  2.07it/s]



 30%|██▉       | 433/1460 [02:59<05:34,  3.07it/s]



 30%|██▉       | 434/1460 [03:00<05:27,  3.14it/s]



 30%|██▉       | 435/1460 [03:00<07:12,  2.37it/s]



 30%|██▉       | 436/1460 [03:01<07:36,  2.24it/s]



 30%|██▉       | 437/1460 [03:01<07:01,  2.43it/s]



 30%|███       | 438/1460 [03:02<07:10,  2.37it/s]



 30%|███       | 439/1460 [03:02<08:04,  2.11it/s]



 30%|███       | 441/1460 [03:03<05:51,  2.90it/s]



 30%|███       | 442/1460 [03:03<05:15,  3.23it/s]



 30%|███       | 443/1460 [03:04<07:00,  2.42it/s]



 30%|███       | 444/1460 [03:04<07:13,  2.34it/s]



 30%|███       | 445/1460 [03:04<06:41,  2.53it/s]



 31%|███       | 446/1460 [03:05<08:54,  1.90it/s]



 31%|███       | 447/1460 [03:05<07:19,  2.30it/s]



 31%|███       | 448/1460 [03:06<06:04,  2.77it/s]



 31%|███       | 449/1460 [03:06<08:13,  2.05it/s]



 31%|███       | 450/1460 [03:07<06:37,  2.54it/s]



 31%|███       | 451/1460 [03:07<05:27,  3.08it/s]



 31%|███       | 452/1460 [03:07<06:15,  2.68it/s]



 31%|███       | 453/1460 [03:08<07:46,  2.16it/s]



 31%|███       | 454/1460 [03:08<07:56,  2.11it/s]



 31%|███       | 455/1460 [03:09<06:12,  2.69it/s]



 31%|███       | 456/1460 [03:09<07:29,  2.24it/s]



 31%|███▏      | 457/1460 [03:10<07:53,  2.12it/s]



 31%|███▏      | 458/1460 [03:10<06:51,  2.44it/s]



 32%|███▏      | 460/1460 [03:10<05:02,  3.30it/s]



 32%|███▏      | 461/1460 [03:11<06:35,  2.52it/s]



 32%|███▏      | 462/1460 [03:12<07:59,  2.08it/s]



 32%|███▏      | 464/1460 [03:12<06:38,  2.50it/s]



 32%|███▏      | 465/1460 [03:13<07:33,  2.19it/s]



 32%|███▏      | 466/1460 [03:13<06:22,  2.60it/s]



 32%|███▏      | 467/1460 [03:13<05:53,  2.81it/s]



 32%|███▏      | 468/1460 [03:14<05:35,  2.95it/s]



 32%|███▏      | 469/1460 [03:14<06:58,  2.37it/s]



 32%|███▏      | 470/1460 [03:15<07:39,  2.16it/s]



 32%|███▏      | 472/1460 [03:16<06:47,  2.43it/s]



 32%|███▏      | 473/1460 [03:16<08:06,  2.03it/s]



 32%|███▏      | 474/1460 [03:17<06:56,  2.36it/s]



 33%|███▎      | 475/1460 [03:17<06:05,  2.70it/s]



 33%|███▎      | 476/1460 [03:17<05:03,  3.24it/s]



 33%|███▎      | 477/1460 [03:17<05:35,  2.93it/s]



 33%|███▎      | 478/1460 [03:18<06:45,  2.42it/s]



 33%|███▎      | 479/1460 [03:18<05:19,  3.07it/s]



 33%|███▎      | 480/1460 [03:19<06:48,  2.40it/s]



 33%|███▎      | 481/1460 [03:19<08:38,  1.89it/s]



 33%|███▎      | 482/1460 [03:20<07:08,  2.28it/s]



 33%|███▎      | 483/1460 [03:20<06:16,  2.59it/s]



 33%|███▎      | 484/1460 [03:20<06:45,  2.41it/s]



 33%|███▎      | 485/1460 [03:21<06:33,  2.48it/s]



 33%|███▎      | 486/1460 [03:21<06:19,  2.57it/s]



 33%|███▎      | 488/1460 [03:22<07:46,  2.08it/s]



 33%|███▎      | 489/1460 [03:23<06:43,  2.41it/s]



 34%|███▎      | 490/1460 [03:23<06:10,  2.62it/s]



 34%|███▎      | 491/1460 [03:24<07:32,  2.14it/s]



 34%|███▎      | 492/1460 [03:24<06:02,  2.67it/s]



 34%|███▍      | 493/1460 [03:24<06:38,  2.43it/s]



 34%|███▍      | 495/1460 [03:25<05:21,  3.00it/s]



 34%|███▍      | 496/1460 [03:26<08:12,  1.96it/s]



 34%|███▍      | 497/1460 [03:26<07:54,  2.03it/s]



 34%|███▍      | 499/1460 [03:27<07:01,  2.28it/s]



 34%|███▍      | 500/1460 [03:27<06:24,  2.50it/s]



 34%|███▍      | 501/1460 [03:27<05:15,  3.04it/s]



 34%|███▍      | 502/1460 [03:28<04:54,  3.26it/s]



 34%|███▍      | 503/1460 [03:28<05:27,  2.92it/s]



 35%|███▍      | 504/1460 [03:29<09:01,  1.77it/s]



 35%|███▍      | 505/1460 [03:29<07:54,  2.01it/s]



 35%|███▍      | 507/1460 [03:30<06:32,  2.43it/s]



 35%|███▍      | 508/1460 [03:30<06:07,  2.59it/s]



 35%|███▍      | 510/1460 [03:31<04:37,  3.43it/s]



 35%|███▌      | 511/1460 [03:31<05:09,  3.07it/s]



 35%|███▌      | 512/1460 [03:32<08:20,  1.89it/s]



 35%|███▌      | 513/1460 [03:33<07:27,  2.12it/s]



 35%|███▌      | 515/1460 [03:33<06:14,  2.52it/s]



 35%|███▌      | 516/1460 [03:33<05:53,  2.67it/s]



 35%|███▌      | 518/1460 [03:34<04:26,  3.53it/s]



 36%|███▌      | 519/1460 [03:34<05:13,  3.00it/s]



 36%|███▌      | 520/1460 [03:35<08:12,  1.91it/s]



 36%|███▌      | 521/1460 [03:36<07:44,  2.02it/s]



 36%|███▌      | 522/1460 [03:36<06:34,  2.38it/s]



 36%|███▌      | 523/1460 [03:36<05:55,  2.64it/s]



 36%|███▌      | 524/1460 [03:36<05:13,  2.98it/s]



 36%|███▌      | 525/1460 [03:37<05:21,  2.91it/s]



 36%|███▌      | 526/1460 [03:37<06:02,  2.58it/s]



 36%|███▌      | 527/1460 [03:38<05:39,  2.75it/s]



 36%|███▌      | 528/1460 [03:39<08:11,  1.89it/s]



 36%|███▌      | 529/1460 [03:39<07:31,  2.06it/s]



 36%|███▋      | 530/1460 [03:39<06:27,  2.40it/s]



 36%|███▋      | 531/1460 [03:40<07:11,  2.15it/s]



 36%|███▋      | 532/1460 [03:40<06:26,  2.40it/s]



 37%|███▋      | 533/1460 [03:40<05:36,  2.75it/s]



 37%|███▋      | 534/1460 [03:41<05:52,  2.62it/s]



 37%|███▋      | 535/1460 [03:41<05:00,  3.08it/s]



 37%|███▋      | 536/1460 [03:42<08:05,  1.90it/s]



 37%|███▋      | 537/1460 [03:42<06:17,  2.45it/s]



 37%|███▋      | 538/1460 [03:43<06:50,  2.25it/s]



 37%|███▋      | 539/1460 [03:43<07:57,  1.93it/s]



 37%|███▋      | 541/1460 [03:44<05:10,  2.96it/s]



 37%|███▋      | 542/1460 [03:44<05:27,  2.80it/s]



 37%|███▋      | 543/1460 [03:44<05:19,  2.87it/s]



 37%|███▋      | 544/1460 [03:45<07:36,  2.01it/s]



 37%|███▋      | 545/1460 [03:45<06:08,  2.48it/s]



 37%|███▋      | 546/1460 [03:46<07:03,  2.16it/s]



 37%|███▋      | 547/1460 [03:47<07:32,  2.02it/s]



 38%|███▊      | 548/1460 [03:47<06:19,  2.40it/s]



 38%|███▊      | 550/1460 [03:47<05:05,  2.98it/s]



 38%|███▊      | 551/1460 [03:47<04:39,  3.25it/s]



 38%|███▊      | 552/1460 [03:48<06:44,  2.24it/s]



 38%|███▊      | 553/1460 [03:48<05:41,  2.65it/s]



 38%|███▊      | 554/1460 [03:49<06:52,  2.20it/s]



 38%|███▊      | 555/1460 [03:50<07:17,  2.07it/s]

 38%|███▊      | 556/1460 [03:50<05:51,  2.57it/s]



 38%|███▊      | 557/1460 [03:50<04:46,  3.15it/s]



 38%|███▊      | 558/1460 [03:50<04:50,  3.10it/s]



 38%|███▊      | 559/1460 [03:51<05:03,  2.97it/s]



 38%|███▊      | 560/1460 [03:51<06:54,  2.17it/s]



 38%|███▊      | 561/1460 [03:52<05:41,  2.64it/s]



 38%|███▊      | 562/1460 [03:53<08:17,  1.81it/s]



 39%|███▊      | 563/1460 [03:53<07:28,  2.00it/s]



 39%|███▊      | 564/1460 [03:53<06:19,  2.36it/s]



 39%|███▊      | 565/1460 [03:53<05:23,  2.77it/s]



 39%|███▉      | 566/1460 [03:54<04:56,  3.01it/s]



 39%|███▉      | 567/1460 [03:54<04:10,  3.56it/s]



 39%|███▉      | 568/1460 [03:55<08:01,  1.85it/s]



 39%|███▉      | 569/1460 [03:55<06:33,  2.27it/s]



 39%|███▉      | 570/1460 [03:56<07:13,  2.05it/s]



 39%|███▉      | 571/1460 [03:56<07:58,  1.86it/s]



 39%|███▉      | 572/1460 [03:57<06:26,  2.30it/s]



 39%|███▉      | 574/1460 [03:57<04:56,  2.99it/s]



 39%|███▉      | 576/1460 [03:58<06:10,  2.38it/s]



 40%|███▉      | 577/1460 [03:58<05:40,  2.59it/s]



 40%|███▉      | 578/1460 [03:59<07:06,  2.07it/s]



 40%|███▉      | 579/1460 [04:00<07:11,  2.04it/s]



 40%|███▉      | 581/1460 [04:00<05:03,  2.89it/s]



 40%|███▉      | 582/1460 [04:00<04:42,  3.11it/s]



 40%|████      | 584/1460 [04:01<05:49,  2.51it/s]



 40%|████      | 585/1460 [04:02<05:47,  2.51it/s]



 40%|████      | 586/1460 [04:02<06:52,  2.12it/s]



 40%|████      | 587/1460 [04:03<06:43,  2.16it/s]



 40%|████      | 589/1460 [04:03<04:46,  3.04it/s]



 40%|████      | 590/1460 [04:03<04:24,  3.28it/s]



 41%|████      | 592/1460 [04:04<05:47,  2.50it/s]



 41%|████      | 593/1460 [04:05<05:51,  2.46it/s]



 41%|████      | 594/1460 [04:06<06:54,  2.09it/s]



 41%|████      | 595/1460 [04:06<06:28,  2.22it/s]



 41%|████      | 596/1460 [04:06<05:22,  2.68it/s]



 41%|████      | 597/1460 [04:06<04:41,  3.06it/s]



 41%|████      | 598/1460 [04:06<03:54,  3.68it/s]



 41%|████      | 600/1460 [04:08<06:10,  2.32it/s]



 41%|████      | 601/1460 [04:08<05:37,  2.55it/s]



 41%|████      | 602/1460 [04:09<07:00,  2.04it/s]



 41%|████▏     | 603/1460 [04:09<06:07,  2.33it/s]



 41%|████▏     | 604/1460 [04:10<06:37,  2.15it/s]



 41%|████▏     | 605/1460 [04:10<05:25,  2.63it/s]



 42%|████▏     | 606/1460 [04:10<04:34,  3.11it/s]



 42%|████▏     | 607/1460 [04:10<03:46,  3.76it/s]



 42%|████▏     | 608/1460 [04:11<06:03,  2.34it/s]



 42%|████▏     | 609/1460 [04:11<06:00,  2.36it/s]



 42%|████▏     | 610/1460 [04:12<07:17,  1.94it/s]



 42%|████▏     | 611/1460 [04:12<06:40,  2.12it/s]



 42%|████▏     | 612/1460 [04:13<06:34,  2.15it/s]



 42%|████▏     | 613/1460 [04:13<05:29,  2.57it/s]



 42%|████▏     | 614/1460 [04:13<05:03,  2.79it/s]



 42%|████▏     | 615/1460 [04:13<03:57,  3.55it/s]



 42%|████▏     | 616/1460 [04:14<06:17,  2.23it/s]



 42%|████▏     | 617/1460 [04:15<06:03,  2.32it/s]



 42%|████▏     | 618/1460 [04:15<07:01,  2.00it/s]



 42%|████▏     | 619/1460 [04:16<07:15,  1.93it/s]



 42%|████▏     | 620/1460 [04:17<07:45,  1.81it/s]



 43%|████▎     | 622/1460 [04:17<04:30,  3.09it/s]



 43%|████▎     | 624/1460 [04:18<05:29,  2.54it/s]



 43%|████▎     | 625/1460 [04:18<04:52,  2.86it/s]



 43%|████▎     | 626/1460 [04:19<06:25,  2.16it/s]



 43%|████▎     | 627/1460 [04:19<06:15,  2.22it/s]



 43%|████▎     | 628/1460 [04:20<06:42,  2.07it/s]



 43%|████▎     | 630/1460 [04:20<04:16,  3.23it/s]



 43%|████▎     | 632/1460 [04:21<05:19,  2.59it/s]



 43%|████▎     | 633/1460 [04:21<04:43,  2.92it/s]



 43%|████▎     | 634/1460 [04:22<06:23,  2.15it/s]



 43%|████▎     | 635/1460 [04:22<05:39,  2.43it/s]



 44%|████▎     | 636/1460 [04:23<06:30,  2.11it/s]



 44%|████▎     | 637/1460 [04:23<05:07,  2.68it/s]



 44%|████▎     | 638/1460 [04:23<04:19,  3.17it/s]



 44%|████▍     | 639/1460 [04:23<03:41,  3.70it/s]



 44%|████▍     | 640/1460 [04:24<05:29,  2.49it/s]



 44%|████▍     | 641/1460 [04:24<06:06,  2.24it/s]



 44%|████▍     | 642/1460 [04:25<07:01,  1.94it/s]



 44%|████▍     | 644/1460 [04:26<05:51,  2.32it/s]



 44%|████▍     | 645/1460 [04:26<06:13,  2.18it/s]



 44%|████▍     | 646/1460 [04:27<05:16,  2.57it/s]



 44%|████▍     | 648/1460 [04:27<04:55,  2.75it/s]



 44%|████▍     | 649/1460 [04:28<07:05,  1.91it/s]



 45%|████▍     | 651/1460 [04:29<05:36,  2.40it/s]



 45%|████▍     | 652/1460 [04:29<05:01,  2.68it/s]



 45%|████▍     | 653/1460 [04:30<05:56,  2.27it/s]



 45%|████▍     | 654/1460 [04:30<05:08,  2.62it/s]



 45%|████▍     | 656/1460 [04:30<04:11,  3.19it/s]



 45%|████▌     | 657/1460 [04:32<07:10,  1.86it/s]



 45%|████▌     | 658/1460 [04:32<05:43,  2.34it/s]



 45%|████▌     | 659/1460 [04:32<05:47,  2.30it/s]



 45%|████▌     | 660/1460 [04:32<04:55,  2.70it/s]



 45%|████▌     | 661/1460 [04:33<05:23,  2.47it/s]



 45%|████▌     | 662/1460 [04:33<04:23,  3.03it/s]



 45%|████▌     | 663/1460 [04:33<04:14,  3.13it/s]



 45%|████▌     | 664/1460 [04:34<04:07,  3.22it/s]



 46%|████▌     | 665/1460 [04:35<07:34,  1.75it/s]



 46%|████▌     | 666/1460 [04:35<05:52,  2.25it/s]



 46%|████▌     | 667/1460 [04:35<05:07,  2.58it/s]



 46%|████▌     | 668/1460 [04:36<05:05,  2.59it/s]



 46%|████▌     | 669/1460 [04:36<04:57,  2.66it/s]



 46%|████▌     | 670/1460 [04:36<04:13,  3.11it/s]



 46%|████▌     | 671/1460 [04:36<04:33,  2.89it/s]



 46%|████▌     | 672/1460 [04:37<03:51,  3.41it/s]



 46%|████▌     | 673/1460 [04:38<07:42,  1.70it/s]



 46%|████▌     | 674/1460 [04:38<06:32,  2.00it/s]



 46%|████▌     | 675/1460 [04:38<05:07,  2.55it/s]



 46%|████▋     | 676/1460 [04:39<05:39,  2.31it/s]



 46%|████▋     | 677/1460 [04:39<04:39,  2.80it/s]



 46%|████▋     | 678/1460 [04:39<03:58,  3.28it/s]



 47%|████▋     | 679/1460 [04:40<04:21,  2.98it/s]



 47%|████▋     | 680/1460 [04:40<04:09,  3.13it/s]



 47%|████▋     | 681/1460 [04:41<07:31,  1.73it/s]



 47%|████▋     | 682/1460 [04:41<06:34,  1.97it/s]



 47%|████▋     | 683/1460 [04:42<05:38,  2.30it/s]



 47%|████▋     | 684/1460 [04:42<05:26,  2.38it/s]



 47%|████▋     | 685/1460 [04:42<04:44,  2.72it/s]



 47%|████▋     | 686/1460 [04:43<04:15,  3.03it/s]



 47%|████▋     | 687/1460 [04:43<06:03,  2.13it/s]



 47%|████▋     | 689/1460 [04:44<05:59,  2.15it/s]



 47%|████▋     | 690/1460 [04:45<06:29,  1.98it/s]



 47%|████▋     | 691/1460 [04:45<05:11,  2.47it/s]



 47%|████▋     | 692/1460 [04:45<04:43,  2.71it/s]



 47%|████▋     | 693/1460 [04:46<04:57,  2.58it/s]



 48%|████▊     | 695/1460 [04:47<05:52,  2.17it/s]



 48%|████▊     | 697/1460 [04:48<05:30,  2.31it/s]

 48%|████▊     | 698/1460 [04:48<05:21,  2.37it/s]



 48%|████▊     | 699/1460 [04:48<05:07,  2.47it/s]



 48%|████▊     | 700/1460 [04:49<05:17,  2.40it/s]



 48%|████▊     | 701/1460 [04:49<04:34,  2.77it/s]



 48%|████▊     | 702/1460 [04:49<03:54,  3.23it/s]



 48%|████▊     | 703/1460 [04:50<06:04,  2.08it/s]



 48%|████▊     | 704/1460 [04:50<05:19,  2.37it/s]



 48%|████▊     | 705/1460 [04:51<05:20,  2.36it/s]



 48%|████▊     | 706/1460 [04:51<04:53,  2.57it/s]



 48%|████▊     | 707/1460 [04:52<05:14,  2.39it/s]



 48%|████▊     | 708/1460 [04:52<04:57,  2.52it/s]



 49%|████▊     | 709/1460 [04:52<04:23,  2.85it/s]



 49%|████▊     | 710/1460 [04:52<03:46,  3.31it/s]



 49%|████▊     | 711/1460 [04:53<05:50,  2.14it/s]



 49%|████▉     | 712/1460 [04:54<05:23,  2.31it/s]



 49%|████▉     | 713/1460 [04:54<05:19,  2.34it/s]



 49%|████▉     | 714/1460 [04:54<04:38,  2.68it/s]



 49%|████▉     | 715/1460 [04:55<05:23,  2.30it/s]



 49%|████▉     | 716/1460 [04:55<04:35,  2.70it/s]



 49%|████▉     | 717/1460 [04:55<04:09,  2.98it/s]



 49%|████▉     | 718/1460 [04:56<04:06,  3.01it/s]



 49%|████▉     | 719/1460 [04:57<06:06,  2.02it/s]



 49%|████▉     | 720/1460 [04:57<05:17,  2.33it/s]



 49%|████▉     | 721/1460 [04:57<05:47,  2.13it/s]



 49%|████▉     | 722/1460 [04:58<05:14,  2.35it/s]



 50%|████▉     | 723/1460 [04:58<05:24,  2.27it/s]



 50%|████▉     | 724/1460 [04:58<04:39,  2.63it/s]



 50%|████▉     | 725/1460 [04:59<05:44,  2.13it/s]



 50%|████▉     | 727/1460 [05:00<05:52,  2.08it/s]



 50%|████▉     | 729/1460 [05:01<04:38,  2.62it/s]



 50%|█████     | 730/1460 [05:01<04:24,  2.76it/s]



 50%|█████     | 731/1460 [05:02<05:20,  2.27it/s]



 50%|█████     | 733/1460 [05:02<05:21,  2.26it/s]



 50%|█████     | 734/1460 [05:03<04:25,  2.74it/s]



 50%|█████     | 735/1460 [05:03<05:59,  2.02it/s]



 50%|█████     | 736/1460 [05:04<04:57,  2.43it/s]



 50%|█████     | 737/1460 [05:04<04:03,  2.97it/s]



 51%|█████     | 738/1460 [05:04<04:31,  2.66it/s]



 51%|█████     | 739/1460 [05:05<05:13,  2.30it/s]



 51%|█████     | 741/1460 [05:06<04:51,  2.46it/s]



 51%|█████     | 742/1460 [05:06<04:12,  2.85it/s]



 51%|█████     | 743/1460 [05:07<06:10,  1.94it/s]



 51%|█████     | 745/1460 [05:07<03:55,  3.03it/s]



 51%|█████     | 746/1460 [05:07<04:22,  2.72it/s]



 51%|█████     | 747/1460 [05:08<05:00,  2.38it/s]



 51%|█████▏    | 749/1460 [05:09<04:33,  2.60it/s]



 51%|█████▏    | 750/1460 [05:09<04:09,  2.85it/s]



 51%|█████▏    | 751/1460 [05:10<06:10,  1.91it/s]



 52%|█████▏    | 753/1460 [05:10<03:56,  3.00it/s]



 52%|█████▏    | 754/1460 [05:10<04:10,  2.82it/s]



 52%|█████▏    | 755/1460 [05:11<04:49,  2.43it/s]



 52%|█████▏    | 757/1460 [05:12<04:32,  2.58it/s]



 52%|█████▏    | 758/1460 [05:12<04:57,  2.36it/s]



 52%|█████▏    | 759/1460 [05:13<05:54,  1.98it/s]



 52%|█████▏    | 760/1460 [05:13<05:10,  2.25it/s]



 52%|█████▏    | 762/1460 [05:14<04:33,  2.55it/s]



 52%|█████▏    | 763/1460 [05:14<04:28,  2.59it/s]



 52%|█████▏    | 764/1460 [05:15<04:14,  2.74it/s]



 52%|█████▏    | 765/1460 [05:16<05:54,  1.96it/s]



 53%|█████▎    | 767/1460 [05:17<06:07,  1.88it/s]



 53%|█████▎    | 769/1460 [05:17<04:14,  2.72it/s]



 53%|█████▎    | 770/1460 [05:17<03:49,  3.01it/s]



 53%|█████▎    | 771/1460 [05:17<04:07,  2.79it/s]



 53%|█████▎    | 772/1460 [05:18<04:21,  2.63it/s]



 53%|█████▎    | 773/1460 [05:19<05:53,  1.95it/s]



 53%|█████▎    | 775/1460 [05:20<05:51,  1.95it/s]



 53%|█████▎    | 776/1460 [05:20<04:54,  2.32it/s]



 53%|█████▎    | 777/1460 [05:20<04:08,  2.75it/s]



 53%|█████▎    | 778/1460 [05:20<03:35,  3.16it/s]



 53%|█████▎    | 779/1460 [05:21<04:14,  2.68it/s]



 53%|█████▎    | 780/1460 [05:21<04:13,  2.68it/s]



 53%|█████▎    | 781/1460 [05:22<05:35,  2.02it/s]



 54%|█████▎    | 783/1460 [05:23<05:27,  2.07it/s]



 54%|█████▎    | 784/1460 [05:23<04:46,  2.36it/s]



 54%|█████▍    | 785/1460 [05:23<03:57,  2.84it/s]



 54%|█████▍    | 786/1460 [05:24<03:18,  3.40it/s]



 54%|█████▍    | 787/1460 [05:24<04:15,  2.64it/s]



 54%|█████▍    | 788/1460 [05:24<03:55,  2.85it/s]



 54%|█████▍    | 789/1460 [05:25<05:13,  2.14it/s]



 54%|█████▍    | 791/1460 [05:26<05:21,  2.08it/s]



 54%|█████▍    | 792/1460 [05:26<04:53,  2.27it/s]



 54%|█████▍    | 793/1460 [05:27<04:03,  2.74it/s]



 54%|█████▍    | 794/1460 [05:27<03:15,  3.40it/s]



 54%|█████▍    | 795/1460 [05:27<04:13,  2.62it/s]



 55%|█████▍    | 796/1460 [05:28<04:14,  2.61it/s]



 55%|█████▍    | 797/1460 [05:28<04:47,  2.31it/s]



 55%|█████▍    | 798/1460 [05:29<04:30,  2.45it/s]



 55%|█████▍    | 799/1460 [05:29<05:11,  2.12it/s]



 55%|█████▍    | 800/1460 [05:30<04:44,  2.32it/s]



 55%|█████▍    | 801/1460 [05:30<04:00,  2.74it/s]



 55%|█████▍    | 802/1460 [05:31<05:17,  2.07it/s]



 55%|█████▌    | 803/1460 [05:31<04:12,  2.60it/s]



 55%|█████▌    | 804/1460 [05:31<03:56,  2.77it/s]



 55%|█████▌    | 805/1460 [05:32<04:59,  2.19it/s]



 55%|█████▌    | 806/1460 [05:32<04:14,  2.57it/s]



 55%|█████▌    | 807/1460 [05:33<05:27,  1.99it/s]



 55%|█████▌    | 808/1460 [05:33<04:18,  2.52it/s]



 55%|█████▌    | 809/1460 [05:33<03:57,  2.74it/s]



 55%|█████▌    | 810/1460 [05:34<04:53,  2.22it/s]



 56%|█████▌    | 811/1460 [05:34<04:31,  2.39it/s]



 56%|█████▌    | 812/1460 [05:35<04:30,  2.39it/s]



 56%|█████▌    | 813/1460 [05:35<04:51,  2.22it/s]



 56%|█████▌    | 814/1460 [05:35<03:53,  2.77it/s]



 56%|█████▌    | 815/1460 [05:36<04:36,  2.33it/s]



 56%|█████▌    | 816/1460 [05:36<04:35,  2.33it/s]



 56%|█████▌    | 818/1460 [05:37<04:18,  2.49it/s]



 56%|█████▌    | 819/1460 [05:38<04:47,  2.23it/s]



 56%|█████▌    | 820/1460 [05:38<04:16,  2.50it/s]



 56%|█████▌    | 821/1460 [05:38<04:16,  2.49it/s]



 56%|█████▋    | 822/1460 [05:39<03:54,  2.72it/s]



 56%|█████▋    | 823/1460 [05:39<03:59,  2.66it/s]



 56%|█████▋    | 824/1460 [05:39<04:08,  2.56it/s]



 57%|█████▋    | 825/1460 [05:40<03:41,  2.86it/s]



 57%|█████▋    | 826/1460 [05:40<04:37,  2.28it/s]



 57%|█████▋    | 827/1460 [05:41<04:48,  2.19it/s]



 57%|█████▋    | 828/1460 [05:41<04:42,  2.24it/s]



 57%|█████▋    | 829/1460 [05:41<04:11,  2.51it/s]



 57%|█████▋    | 830/1460 [05:42<03:49,  2.75it/s]



 57%|█████▋    | 831/1460 [05:42<03:49,  2.74it/s]



 57%|█████▋    | 832/1460 [05:43<04:17,  2.44it/s]



 57%|█████▋    | 833/1460 [05:43<03:40,  2.84it/s]



 57%|█████▋    | 834/1460 [05:43<04:27,  2.34it/s]



 57%|█████▋    | 835/1460 [05:44<04:55,  2.12it/s]



 57%|█████▋    | 836/1460 [05:45<05:34,  1.86it/s]

 57%|█████▋    | 838/1460 [05:45<04:47,  2.16it/s]



 57%|█████▋    | 839/1460 [05:46<04:08,  2.49it/s]



 58%|█████▊    | 840/1460 [05:46<03:31,  2.93it/s]



 58%|█████▊    | 841/1460 [05:46<03:09,  3.27it/s]



 58%|█████▊    | 842/1460 [05:47<05:15,  1.96it/s]



 58%|█████▊    | 843/1460 [05:47<04:22,  2.35it/s]



 58%|█████▊    | 844/1460 [05:48<05:56,  1.73it/s]



 58%|█████▊    | 846/1460 [05:49<04:33,  2.24it/s]



 58%|█████▊    | 848/1460 [05:49<03:03,  3.33it/s]



 58%|█████▊    | 849/1460 [05:49<03:33,  2.86it/s]



 58%|█████▊    | 850/1460 [05:50<05:00,  2.03it/s]



 58%|█████▊    | 851/1460 [05:51<04:06,  2.48it/s]



 58%|█████▊    | 852/1460 [05:51<05:24,  1.87it/s]



 58%|█████▊    | 853/1460 [05:52<04:23,  2.30it/s]



 58%|█████▊    | 854/1460 [05:52<04:00,  2.52it/s]



 59%|█████▊    | 855/1460 [05:52<03:36,  2.79it/s]



 59%|█████▊    | 856/1460 [05:52<03:04,  3.28it/s]



 59%|█████▊    | 857/1460 [05:53<03:18,  3.04it/s]



 59%|█████▉    | 858/1460 [05:54<05:43,  1.75it/s]



 59%|█████▉    | 859/1460 [05:54<04:19,  2.32it/s]



 59%|█████▉    | 860/1460 [05:55<04:54,  2.04it/s]



 59%|█████▉    | 861/1460 [05:55<04:03,  2.46it/s]



 59%|█████▉    | 862/1460 [05:55<04:01,  2.48it/s]



 59%|█████▉    | 864/1460 [05:56<02:50,  3.49it/s]



 59%|█████▉    | 865/1460 [05:56<02:57,  3.35it/s]



 59%|█████▉    | 866/1460 [05:57<05:19,  1.86it/s]



 59%|█████▉    | 868/1460 [05:58<04:29,  2.20it/s]



 60%|█████▉    | 869/1460 [05:58<03:49,  2.57it/s]



 60%|█████▉    | 870/1460 [05:58<03:58,  2.47it/s]



 60%|█████▉    | 871/1460 [05:59<03:11,  3.08it/s]



 60%|█████▉    | 872/1460 [05:59<02:53,  3.38it/s]



 60%|█████▉    | 873/1460 [05:59<02:56,  3.33it/s]



 60%|█████▉    | 874/1460 [06:00<05:26,  1.80it/s]



 60%|█████▉    | 875/1460 [06:00<04:29,  2.17it/s]



 60%|██████    | 876/1460 [06:01<04:55,  1.98it/s]



 60%|██████    | 877/1460 [06:02<04:41,  2.07it/s]



 60%|██████    | 878/1460 [06:02<04:20,  2.23it/s]



 60%|██████    | 879/1460 [06:02<03:33,  2.73it/s]



 60%|██████    | 880/1460 [06:02<02:51,  3.37it/s]



 60%|██████    | 881/1460 [06:02<02:18,  4.19it/s]



 60%|██████    | 882/1460 [06:03<04:54,  1.96it/s]



 60%|██████    | 883/1460 [06:04<04:00,  2.40it/s]



 61%|██████    | 884/1460 [06:05<05:35,  1.71it/s]



 61%|██████    | 885/1460 [06:05<04:12,  2.28it/s]



 61%|██████    | 886/1460 [06:05<04:29,  2.13it/s]



 61%|██████    | 887/1460 [06:05<03:33,  2.68it/s]



 61%|██████    | 889/1460 [06:06<02:11,  4.33it/s]



 61%|██████    | 890/1460 [06:07<04:33,  2.08it/s]



 61%|██████    | 891/1460 [06:07<03:39,  2.60it/s]



 61%|██████    | 892/1460 [06:08<05:05,  1.86it/s]



 61%|██████    | 893/1460 [06:08<04:24,  2.14it/s]



 61%|██████    | 894/1460 [06:08<03:48,  2.48it/s]



 61%|██████▏   | 895/1460 [06:09<03:43,  2.53it/s]



 61%|██████▏   | 897/1460 [06:09<02:40,  3.51it/s]



 62%|██████▏   | 898/1460 [06:10<04:40,  2.00it/s]



 62%|██████▏   | 900/1460 [06:11<04:09,  2.25it/s]



 62%|██████▏   | 901/1460 [06:11<03:48,  2.45it/s]



 62%|██████▏   | 902/1460 [06:11<03:22,  2.75it/s]



 62%|██████▏   | 903/1460 [06:12<03:32,  2.62it/s]



 62%|██████▏   | 905/1460 [06:12<02:42,  3.42it/s]



 62%|██████▏   | 906/1460 [06:13<04:32,  2.03it/s]



 62%|██████▏   | 908/1460 [06:14<04:34,  2.01it/s]



 62%|██████▏   | 909/1460 [06:14<03:48,  2.41it/s]



 62%|██████▏   | 910/1460 [06:15<03:08,  2.92it/s]



 62%|██████▏   | 911/1460 [06:15<03:11,  2.87it/s]



 63%|██████▎   | 913/1460 [06:16<03:19,  2.74it/s]



 63%|██████▎   | 914/1460 [06:17<04:28,  2.03it/s]



 63%|██████▎   | 916/1460 [06:18<04:27,  2.03it/s]



 63%|██████▎   | 917/1460 [06:18<03:42,  2.44it/s]



 63%|██████▎   | 918/1460 [06:18<03:29,  2.59it/s]



 63%|██████▎   | 919/1460 [06:18<03:14,  2.78it/s]



 63%|██████▎   | 920/1460 [06:19<02:45,  3.26it/s]



 63%|██████▎   | 921/1460 [06:19<03:57,  2.27it/s]



 63%|██████▎   | 922/1460 [06:20<04:11,  2.14it/s]



 63%|██████▎   | 923/1460 [06:20<03:48,  2.35it/s]



 63%|██████▎   | 924/1460 [06:21<04:24,  2.03it/s]



 63%|██████▎   | 926/1460 [06:21<03:37,  2.46it/s]



 64%|██████▎   | 928/1460 [06:22<03:00,  2.94it/s]



 64%|██████▎   | 929/1460 [06:23<04:16,  2.07it/s]



 64%|██████▎   | 930/1460 [06:23<04:07,  2.14it/s]



 64%|██████▍   | 931/1460 [06:23<03:23,  2.60it/s]



 64%|██████▍   | 932/1460 [06:24<03:28,  2.53it/s]



 64%|██████▍   | 933/1460 [06:24<02:50,  3.10it/s]



 64%|██████▍   | 934/1460 [06:25<03:36,  2.43it/s]



 64%|██████▍   | 935/1460 [06:25<03:01,  2.89it/s]



 64%|██████▍   | 936/1460 [06:25<03:11,  2.74it/s]



 64%|██████▍   | 937/1460 [06:26<04:33,  1.91it/s]



 64%|██████▍   | 938/1460 [06:27<04:25,  1.97it/s]



 64%|██████▍   | 940/1460 [06:27<03:01,  2.86it/s]



 64%|██████▍   | 941/1460 [06:27<02:42,  3.19it/s]



 65%|██████▍   | 942/1460 [06:28<03:30,  2.47it/s]



 65%|██████▍   | 943/1460 [06:28<02:49,  3.05it/s]



 65%|██████▍   | 944/1460 [06:28<03:07,  2.76it/s]



 65%|██████▍   | 945/1460 [06:29<04:24,  1.95it/s]



 65%|██████▍   | 946/1460 [06:30<04:19,  1.98it/s]



 65%|██████▍   | 947/1460 [06:30<03:24,  2.51it/s]



 65%|██████▍   | 948/1460 [06:30<02:45,  3.09it/s]



 65%|██████▌   | 949/1460 [06:30<02:25,  3.51it/s]



 65%|██████▌   | 950/1460 [06:31<03:33,  2.38it/s]



 65%|██████▌   | 951/1460 [06:31<03:17,  2.58it/s]



 65%|██████▌   | 952/1460 [06:32<02:59,  2.83it/s]



 65%|██████▌   | 953/1460 [06:32<04:12,  2.01it/s]



 65%|██████▌   | 954/1460 [06:33<04:50,  1.74it/s]



 65%|██████▌   | 955/1460 [06:33<03:45,  2.24it/s]



 65%|██████▌   | 956/1460 [06:33<03:03,  2.74it/s]



 66%|██████▌   | 958/1460 [06:34<02:48,  2.97it/s]



 66%|██████▌   | 959/1460 [06:35<03:29,  2.39it/s]



 66%|██████▌   | 960/1460 [06:35<02:50,  2.93it/s]



 66%|██████▌   | 961/1460 [06:36<03:38,  2.28it/s]



 66%|██████▌   | 962/1460 [06:36<04:20,  1.91it/s]



 66%|██████▌   | 963/1460 [06:37<04:47,  1.73it/s]



 66%|██████▌   | 965/1460 [06:37<02:57,  2.78it/s]



 66%|██████▌   | 966/1460 [06:37<02:29,  3.31it/s]



 66%|██████▌   | 967/1460 [06:38<03:16,  2.51it/s]



 66%|██████▋   | 969/1460 [06:39<03:40,  2.22it/s]



 66%|██████▋   | 970/1460 [06:40<03:46,  2.16it/s]



 67%|██████▋   | 971/1460 [06:40<03:58,  2.05it/s]



 67%|██████▋   | 972/1460 [06:40<03:22,  2.41it/s]



 67%|██████▋   | 973/1460 [06:40<02:47,  2.91it/s]



 67%|██████▋   | 975/1460 [06:41<03:00,  2.68it/s]



 67%|██████▋   | 977/1460 [06:42<03:18,  2.43it/s]



 67%|██████▋   | 978/1460 [06:43<03:40,  2.18it/s]



 67%|██████▋   | 979/1460 [06:43<03:45,  2.13it/s]



 67%|██████▋   | 980/1460 [06:44<03:07,  2.55it/s]

 67%|██████▋   | 982/1460 [06:44<02:00,  3.95it/s]



 67%|██████▋   | 983/1460 [06:44<02:53,  2.74it/s]



 67%|██████▋   | 984/1460 [06:45<02:29,  3.17it/s]



 67%|██████▋   | 985/1460 [06:45<03:33,  2.23it/s]



 68%|██████▊   | 986/1460 [06:46<03:50,  2.06it/s]



 68%|██████▊   | 987/1460 [06:47<03:55,  2.01it/s]



 68%|██████▊   | 988/1460 [06:47<03:20,  2.35it/s]



 68%|██████▊   | 990/1460 [06:47<02:05,  3.76it/s]



 68%|██████▊   | 991/1460 [06:48<03:15,  2.41it/s]



 68%|██████▊   | 993/1460 [06:49<03:04,  2.53it/s]



 68%|██████▊   | 994/1460 [06:49<03:49,  2.03it/s]



 68%|██████▊   | 995/1460 [06:50<03:25,  2.26it/s]



 68%|██████▊   | 996/1460 [06:50<03:08,  2.46it/s]



 68%|██████▊   | 997/1460 [06:50<02:55,  2.64it/s]



 68%|██████▊   | 998/1460 [06:50<02:25,  3.17it/s]



 68%|██████▊   | 999/1460 [06:51<02:59,  2.57it/s]



 68%|██████▊   | 1000/1460 [06:51<02:35,  2.95it/s]



 69%|██████▊   | 1001/1460 [06:52<03:09,  2.42it/s]



 69%|██████▊   | 1002/1460 [06:52<03:50,  1.99it/s]



 69%|██████▊   | 1003/1460 [06:53<04:10,  1.82it/s]



 69%|██████▉   | 1004/1460 [06:53<03:31,  2.15it/s]



 69%|██████▉   | 1006/1460 [06:54<02:28,  3.05it/s]



 69%|██████▉   | 1007/1460 [06:54<02:33,  2.95it/s]



 69%|██████▉   | 1008/1460 [06:54<02:32,  2.97it/s]



 69%|██████▉   | 1009/1460 [06:55<02:56,  2.55it/s]



 69%|██████▉   | 1010/1460 [06:56<03:41,  2.03it/s]



 69%|██████▉   | 1011/1460 [06:56<03:53,  1.92it/s]



 69%|██████▉   | 1012/1460 [06:57<03:27,  2.16it/s]



 69%|██████▉   | 1013/1460 [06:57<03:00,  2.47it/s]



 69%|██████▉   | 1014/1460 [06:57<02:32,  2.92it/s]



 70%|██████▉   | 1015/1460 [06:57<02:35,  2.87it/s]



 70%|██████▉   | 1016/1460 [06:58<02:09,  3.42it/s]



 70%|██████▉   | 1017/1460 [06:58<02:43,  2.71it/s]



 70%|██████▉   | 1018/1460 [06:59<03:27,  2.13it/s]



 70%|██████▉   | 1019/1460 [07:00<03:49,  1.92it/s]



 70%|██████▉   | 1020/1460 [07:00<03:39,  2.01it/s]



 70%|██████▉   | 1021/1460 [07:00<02:51,  2.56it/s]



 70%|███████   | 1022/1460 [07:00<02:17,  3.19it/s]



 70%|███████   | 1023/1460 [07:01<02:36,  2.78it/s]



 70%|███████   | 1025/1460 [07:01<02:34,  2.82it/s]



 70%|███████   | 1026/1460 [07:02<02:59,  2.42it/s]



 70%|███████   | 1027/1460 [07:03<03:43,  1.94it/s]



 70%|███████   | 1028/1460 [07:03<03:24,  2.11it/s]



 70%|███████   | 1029/1460 [07:03<02:48,  2.56it/s]



 71%|███████   | 1031/1460 [07:04<02:44,  2.60it/s]



 71%|███████   | 1033/1460 [07:05<02:37,  2.72it/s]



 71%|███████   | 1034/1460 [07:05<02:41,  2.64it/s]



 71%|███████   | 1035/1460 [07:07<04:16,  1.66it/s]



 71%|███████   | 1036/1460 [07:07<03:22,  2.10it/s]



 71%|███████   | 1038/1460 [07:07<02:40,  2.63it/s]



 71%|███████   | 1039/1460 [07:07<02:25,  2.89it/s]



 71%|███████   | 1040/1460 [07:08<02:18,  3.04it/s]



 71%|███████▏  | 1041/1460 [07:08<02:12,  3.16it/s]



 71%|███████▏  | 1042/1460 [07:09<02:54,  2.39it/s]



 71%|███████▏  | 1043/1460 [07:10<04:29,  1.55it/s]



 72%|███████▏  | 1045/1460 [07:10<02:54,  2.38it/s]



 72%|███████▏  | 1046/1460 [07:10<02:33,  2.70it/s]



 72%|███████▏  | 1047/1460 [07:11<02:21,  2.92it/s]



 72%|███████▏  | 1048/1460 [07:11<02:26,  2.81it/s]



 72%|███████▏  | 1049/1460 [07:11<02:00,  3.40it/s]



 72%|███████▏  | 1050/1460 [07:12<02:39,  2.56it/s]



 72%|███████▏  | 1051/1460 [07:13<04:18,  1.58it/s]



 72%|███████▏  | 1052/1460 [07:13<03:26,  1.97it/s]



 72%|███████▏  | 1053/1460 [07:14<03:27,  1.96it/s]



 72%|███████▏  | 1054/1460 [07:14<02:40,  2.53it/s]



 72%|███████▏  | 1055/1460 [07:14<02:14,  3.01it/s]



 72%|███████▏  | 1056/1460 [07:14<01:54,  3.53it/s]



 72%|███████▏  | 1057/1460 [07:14<01:44,  3.85it/s]



 72%|███████▏  | 1058/1460 [07:15<02:51,  2.34it/s]



 73%|███████▎  | 1059/1460 [07:16<03:50,  1.74it/s]



 73%|███████▎  | 1060/1460 [07:17<03:36,  1.85it/s]



 73%|███████▎  | 1061/1460 [07:17<03:00,  2.22it/s]



 73%|███████▎  | 1062/1460 [07:17<02:29,  2.67it/s]



 73%|███████▎  | 1063/1460 [07:17<02:05,  3.15it/s]



 73%|███████▎  | 1064/1460 [07:17<01:44,  3.80it/s]



 73%|███████▎  | 1065/1460 [07:18<01:42,  3.87it/s]



 73%|███████▎  | 1066/1460 [07:18<02:41,  2.44it/s]



 73%|███████▎  | 1067/1460 [07:19<03:40,  1.78it/s]



 73%|███████▎  | 1068/1460 [07:20<03:50,  1.70it/s]



 73%|███████▎  | 1069/1460 [07:20<02:52,  2.26it/s]



 73%|███████▎  | 1070/1460 [07:20<02:37,  2.48it/s]



 73%|███████▎  | 1071/1460 [07:20<02:06,  3.08it/s]



 73%|███████▎  | 1072/1460 [07:21<02:00,  3.23it/s]



 73%|███████▎  | 1073/1460 [07:21<02:15,  2.86it/s]



 74%|███████▎  | 1074/1460 [07:22<02:30,  2.56it/s]



 74%|███████▎  | 1075/1460 [07:23<03:31,  1.82it/s]



 74%|███████▎  | 1076/1460 [07:23<03:24,  1.88it/s]



 74%|███████▍  | 1077/1460 [07:24<03:34,  1.78it/s]



 74%|███████▍  | 1078/1460 [07:24<02:42,  2.36it/s]



 74%|███████▍  | 1080/1460 [07:24<01:57,  3.24it/s]



 74%|███████▍  | 1081/1460 [07:25<02:12,  2.87it/s]



 74%|███████▍  | 1082/1460 [07:25<02:18,  2.73it/s]



 74%|███████▍  | 1083/1460 [07:26<02:47,  2.25it/s]



 74%|███████▍  | 1084/1460 [07:26<03:08,  1.99it/s]



 74%|███████▍  | 1085/1460 [07:27<03:35,  1.74it/s]



 74%|███████▍  | 1086/1460 [07:27<02:48,  2.22it/s]



 75%|███████▍  | 1088/1460 [07:27<01:46,  3.50it/s]



 75%|███████▍  | 1089/1460 [07:28<01:48,  3.42it/s]



 75%|███████▍  | 1090/1460 [07:28<02:16,  2.71it/s]



 75%|███████▍  | 1091/1460 [07:29<02:34,  2.39it/s]



 75%|███████▍  | 1092/1460 [07:30<03:10,  1.94it/s]



 75%|███████▍  | 1093/1460 [07:30<03:29,  1.75it/s]



 75%|███████▌  | 1095/1460 [07:30<02:04,  2.94it/s]



 75%|███████▌  | 1096/1460 [07:31<02:04,  2.91it/s]



 75%|███████▌  | 1097/1460 [07:31<01:49,  3.31it/s]



 75%|███████▌  | 1098/1460 [07:31<02:07,  2.85it/s]



 75%|███████▌  | 1099/1460 [07:32<02:41,  2.23it/s]



 75%|███████▌  | 1100/1460 [07:33<03:08,  1.91it/s]



 75%|███████▌  | 1101/1460 [07:34<03:16,  1.83it/s]



 76%|███████▌  | 1104/1460 [07:34<02:03,  2.88it/s]



 76%|███████▌  | 1105/1460 [07:34<01:45,  3.35it/s]



 76%|███████▌  | 1106/1460 [07:35<01:54,  3.08it/s]



 76%|███████▌  | 1107/1460 [07:35<02:35,  2.27it/s]



 76%|███████▌  | 1108/1460 [07:36<02:58,  1.97it/s]



 76%|███████▌  | 1109/1460 [07:37<03:01,  1.94it/s]



 76%|███████▌  | 1111/1460 [07:37<02:05,  2.79it/s]



 76%|███████▌  | 1112/1460 [07:38<02:28,  2.34it/s]



 76%|███████▋  | 1114/1460 [07:38<01:57,  2.93it/s]



 76%|███████▋  | 1115/1460 [07:39<02:51,  2.01it/s]



 76%|███████▋  | 1116/1460 [07:39<02:31,  2.27it/s]



 77%|███████▋  | 1117/1460 [07:40<02:41,  2.12it/s]



 77%|███████▋  | 1118/1460 [07:40<02:28,  2.31it/s]

 77%|███████▋  | 1120/1460 [07:41<02:12,  2.57it/s]



 77%|███████▋  | 1121/1460 [07:41<01:51,  3.03it/s]



 77%|███████▋  | 1122/1460 [07:42<02:13,  2.53it/s]



 77%|███████▋  | 1123/1460 [07:42<02:54,  1.93it/s]



 77%|███████▋  | 1124/1460 [07:43<02:20,  2.39it/s]



 77%|███████▋  | 1125/1460 [07:43<02:21,  2.37it/s]



 77%|███████▋  | 1126/1460 [07:43<02:14,  2.48it/s]



 77%|███████▋  | 1127/1460 [07:44<02:04,  2.68it/s]



 77%|███████▋  | 1128/1460 [07:44<02:04,  2.67it/s]



 77%|███████▋  | 1129/1460 [07:44<01:51,  2.96it/s]



 77%|███████▋  | 1130/1460 [07:45<02:18,  2.38it/s]



 77%|███████▋  | 1131/1460 [07:46<02:54,  1.89it/s]



 78%|███████▊  | 1132/1460 [07:46<02:22,  2.30it/s]



 78%|███████▊  | 1133/1460 [07:46<02:10,  2.51it/s]



 78%|███████▊  | 1134/1460 [07:46<01:53,  2.87it/s]



 78%|███████▊  | 1135/1460 [07:47<01:59,  2.72it/s]



 78%|███████▊  | 1136/1460 [07:47<02:00,  2.68it/s]



 78%|███████▊  | 1137/1460 [07:47<01:39,  3.23it/s]



 78%|███████▊  | 1138/1460 [07:48<02:20,  2.30it/s]



 78%|███████▊  | 1139/1460 [07:49<02:49,  1.90it/s]



 78%|███████▊  | 1140/1460 [07:49<02:11,  2.43it/s]



 78%|███████▊  | 1141/1460 [07:49<01:59,  2.68it/s]



 78%|███████▊  | 1142/1460 [07:50<01:52,  2.82it/s]



 78%|███████▊  | 1143/1460 [07:50<01:56,  2.73it/s]



 78%|███████▊  | 1144/1460 [07:50<02:01,  2.61it/s]



 78%|███████▊  | 1145/1460 [07:51<01:39,  3.16it/s]



 78%|███████▊  | 1146/1460 [07:51<02:20,  2.23it/s]



 79%|███████▊  | 1147/1460 [07:52<02:46,  1.88it/s]



 79%|███████▊  | 1148/1460 [07:53<02:36,  2.00it/s]



 79%|███████▊  | 1149/1460 [07:53<02:02,  2.55it/s]



 79%|███████▉  | 1151/1460 [07:53<01:40,  3.09it/s]



 79%|███████▉  | 1152/1460 [07:54<02:06,  2.43it/s]



 79%|███████▉  | 1153/1460 [07:54<01:51,  2.76it/s]



 79%|███████▉  | 1154/1460 [07:55<02:12,  2.30it/s]



 79%|███████▉  | 1155/1460 [07:56<03:01,  1.68it/s]



 79%|███████▉  | 1157/1460 [07:56<01:58,  2.56it/s]



 79%|███████▉  | 1158/1460 [07:56<01:49,  2.75it/s]



 79%|███████▉  | 1159/1460 [07:57<01:47,  2.80it/s]



 79%|███████▉  | 1160/1460 [07:57<01:57,  2.55it/s]



 80%|███████▉  | 1161/1460 [07:57<01:49,  2.74it/s]



 80%|███████▉  | 1162/1460 [07:58<02:03,  2.40it/s]



 80%|███████▉  | 1163/1460 [07:59<03:12,  1.54it/s]



 80%|███████▉  | 1165/1460 [07:59<01:57,  2.50it/s]



 80%|███████▉  | 1166/1460 [08:00<01:51,  2.63it/s]



 80%|████████  | 1168/1460 [08:00<01:41,  2.87it/s]



 80%|████████  | 1169/1460 [08:01<01:56,  2.50it/s]



 80%|████████  | 1170/1460 [08:01<01:55,  2.51it/s]



 80%|████████  | 1171/1460 [08:02<02:47,  1.72it/s]



 80%|████████  | 1173/1460 [08:02<01:42,  2.80it/s]



 80%|████████  | 1174/1460 [08:03<01:49,  2.61it/s]



 81%|████████  | 1176/1460 [08:03<01:37,  2.90it/s]



 81%|████████  | 1177/1460 [08:04<01:45,  2.67it/s]



 81%|████████  | 1178/1460 [08:04<01:44,  2.69it/s]



 81%|████████  | 1179/1460 [08:05<02:40,  1.75it/s]



 81%|████████  | 1181/1460 [08:06<01:38,  2.83it/s]



 81%|████████  | 1182/1460 [08:06<01:44,  2.65it/s]



 81%|████████  | 1184/1460 [08:07<01:36,  2.86it/s]



 81%|████████  | 1185/1460 [08:07<01:47,  2.55it/s]



 81%|████████  | 1186/1460 [08:07<01:38,  2.78it/s]



 81%|████████▏ | 1187/1460 [08:09<02:33,  1.78it/s]



 81%|████████▏ | 1188/1460 [08:09<02:09,  2.10it/s]



 81%|████████▏ | 1189/1460 [08:09<01:42,  2.66it/s]



 82%|████████▏ | 1190/1460 [08:09<01:27,  3.08it/s]



 82%|████████▏ | 1191/1460 [08:09<01:27,  3.08it/s]



 82%|████████▏ | 1192/1460 [08:10<01:30,  2.97it/s]



 82%|████████▏ | 1193/1460 [08:11<01:59,  2.23it/s]



 82%|████████▏ | 1194/1460 [08:11<01:42,  2.58it/s]



 82%|████████▏ | 1195/1460 [08:12<02:22,  1.86it/s]



 82%|████████▏ | 1196/1460 [08:12<02:28,  1.78it/s]



 82%|████████▏ | 1197/1460 [08:13<01:59,  2.20it/s]



 82%|████████▏ | 1199/1460 [08:13<01:18,  3.32it/s]



 82%|████████▏ | 1200/1460 [08:13<01:30,  2.88it/s]



 82%|████████▏ | 1201/1460 [08:14<01:50,  2.35it/s]



 82%|████████▏ | 1203/1460 [08:15<02:13,  1.92it/s]



 82%|████████▏ | 1204/1460 [08:16<02:18,  1.85it/s]



 83%|████████▎ | 1206/1460 [08:16<01:36,  2.64it/s]



 83%|████████▎ | 1208/1460 [08:17<01:32,  2.71it/s]



 83%|████████▎ | 1209/1460 [08:17<01:28,  2.83it/s]



 83%|████████▎ | 1210/1460 [08:17<01:21,  3.05it/s]



 83%|████████▎ | 1211/1460 [08:19<02:15,  1.83it/s]



 83%|████████▎ | 1212/1460 [08:19<02:13,  1.86it/s]



 83%|████████▎ | 1214/1460 [08:19<01:29,  2.74it/s]



 83%|████████▎ | 1216/1460 [08:20<01:26,  2.82it/s]



 83%|████████▎ | 1217/1460 [08:20<01:18,  3.08it/s]



 83%|████████▎ | 1218/1460 [08:20<01:13,  3.30it/s]



 83%|████████▎ | 1219/1460 [08:22<02:11,  1.84it/s]



 84%|████████▎ | 1220/1460 [08:22<02:07,  1.88it/s]



 84%|████████▎ | 1221/1460 [08:22<01:39,  2.41it/s]



 84%|████████▎ | 1222/1460 [08:22<01:20,  2.95it/s]



 84%|████████▍ | 1224/1460 [08:23<01:25,  2.75it/s]



 84%|████████▍ | 1225/1460 [08:23<01:14,  3.17it/s]



 84%|████████▍ | 1226/1460 [08:24<01:19,  2.96it/s]



 84%|████████▍ | 1227/1460 [08:25<02:19,  1.67it/s]



 84%|████████▍ | 1228/1460 [08:25<02:01,  1.92it/s]



 84%|████████▍ | 1230/1460 [08:26<01:20,  2.86it/s]



 84%|████████▍ | 1231/1460 [08:26<01:14,  3.07it/s]



 84%|████████▍ | 1232/1460 [08:27<01:31,  2.49it/s]



 85%|████████▍ | 1234/1460 [08:27<01:14,  3.05it/s]



 85%|████████▍ | 1235/1460 [08:29<02:18,  1.62it/s]



 85%|████████▍ | 1237/1460 [08:29<01:38,  2.26it/s]



 85%|████████▍ | 1238/1460 [08:29<01:25,  2.60it/s]



 85%|████████▍ | 1240/1460 [08:30<01:22,  2.68it/s]



 85%|████████▌ | 1241/1460 [08:30<01:18,  2.79it/s]



 85%|████████▌ | 1242/1460 [08:31<01:20,  2.69it/s]



 85%|████████▌ | 1243/1460 [08:32<02:04,  1.75it/s]



 85%|████████▌ | 1245/1460 [08:32<01:36,  2.24it/s]



 85%|████████▌ | 1247/1460 [08:32<01:05,  3.26it/s]



 85%|████████▌ | 1248/1460 [08:33<01:22,  2.57it/s]



 86%|████████▌ | 1249/1460 [08:34<01:23,  2.53it/s]



 86%|████████▌ | 1250/1460 [08:34<01:22,  2.55it/s]



 86%|████████▌ | 1251/1460 [08:35<01:54,  1.83it/s]



 86%|████████▌ | 1253/1460 [08:35<01:25,  2.41it/s]



 86%|████████▌ | 1255/1460 [08:36<00:59,  3.45it/s]



 86%|████████▌ | 1256/1460 [08:36<01:17,  2.64it/s]



 86%|████████▌ | 1257/1460 [08:37<01:21,  2.49it/s]



 86%|████████▌ | 1258/1460 [08:37<01:18,  2.58it/s]



 86%|████████▌ | 1259/1460 [08:38<01:45,  1.91it/s]



 86%|████████▋ | 1260/1460 [08:38<01:24,  2.37it/s]



 86%|████████▋ | 1261/1460 [08:39<01:24,  2.36it/s]



 87%|████████▋ | 1263/1460 [08:39<00:54,  3.63it/s]



 87%|████████▋ | 1264/1460 [08:39<01:11,  2.75it/s]



 87%|████████▋ | 1265/1460 [08:40<01:20,  2.44it/s]

 87%|████████▋ | 1266/1460 [08:41<01:33,  2.09it/s]



 87%|████████▋ | 1267/1460 [08:41<01:43,  1.87it/s]



 87%|████████▋ | 1269/1460 [08:42<01:18,  2.42it/s]



 87%|████████▋ | 1270/1460 [08:42<01:10,  2.68it/s]



 87%|████████▋ | 1271/1460 [08:43<01:15,  2.51it/s]



 87%|████████▋ | 1272/1460 [08:43<01:07,  2.79it/s]



 87%|████████▋ | 1273/1460 [08:43<01:07,  2.78it/s]



 87%|████████▋ | 1274/1460 [08:44<01:35,  1.95it/s]



 87%|████████▋ | 1275/1460 [08:44<01:24,  2.19it/s]



 87%|████████▋ | 1276/1460 [08:45<01:15,  2.44it/s]



 87%|████████▋ | 1277/1460 [08:45<01:31,  1.99it/s]



 88%|████████▊ | 1279/1460 [08:46<01:04,  2.80it/s]



 88%|████████▊ | 1280/1460 [08:46<01:05,  2.74it/s]



 88%|████████▊ | 1281/1460 [08:46<01:04,  2.79it/s]



 88%|████████▊ | 1282/1460 [08:48<01:38,  1.80it/s]



 88%|████████▊ | 1283/1460 [08:48<01:20,  2.19it/s]



 88%|████████▊ | 1284/1460 [08:48<01:07,  2.61it/s]



 88%|████████▊ | 1285/1460 [08:49<01:16,  2.28it/s]



 88%|████████▊ | 1286/1460 [08:49<01:07,  2.60it/s]



 88%|████████▊ | 1287/1460 [08:49<00:56,  3.05it/s]



 88%|████████▊ | 1288/1460 [08:49<01:03,  2.69it/s]



 88%|████████▊ | 1289/1460 [08:50<01:03,  2.69it/s]



 88%|████████▊ | 1290/1460 [08:51<01:29,  1.90it/s]



 88%|████████▊ | 1291/1460 [08:51<01:13,  2.29it/s]



 88%|████████▊ | 1292/1460 [08:51<00:59,  2.84it/s]



 89%|████████▊ | 1293/1460 [08:52<01:12,  2.29it/s]



 89%|████████▊ | 1294/1460 [08:52<01:00,  2.75it/s]



 89%|████████▊ | 1295/1460 [08:52<00:54,  3.02it/s]



 89%|████████▉ | 1296/1460 [08:53<00:54,  2.99it/s]



 89%|████████▉ | 1297/1460 [08:53<01:01,  2.65it/s]



 89%|████████▉ | 1298/1460 [08:54<01:25,  1.89it/s]



 89%|████████▉ | 1299/1460 [08:54<01:13,  2.19it/s]



 89%|████████▉ | 1300/1460 [08:54<00:56,  2.83it/s]



 89%|████████▉ | 1301/1460 [08:55<01:05,  2.43it/s]



 89%|████████▉ | 1302/1460 [08:55<00:56,  2.82it/s]



 89%|████████▉ | 1303/1460 [08:55<00:55,  2.83it/s]



 89%|████████▉ | 1304/1460 [08:56<00:57,  2.71it/s]



 89%|████████▉ | 1305/1460 [08:56<01:08,  2.26it/s]



 89%|████████▉ | 1306/1460 [08:57<01:20,  1.91it/s]



 90%|████████▉ | 1307/1460 [08:57<01:04,  2.37it/s]



 90%|████████▉ | 1308/1460 [08:58<00:54,  2.80it/s]



 90%|████████▉ | 1309/1460 [08:58<00:58,  2.59it/s]



 90%|████████▉ | 1310/1460 [08:58<01:04,  2.33it/s]



 90%|████████▉ | 1311/1460 [08:59<01:05,  2.27it/s]



 90%|████████▉ | 1313/1460 [09:00<01:11,  2.05it/s]



 90%|█████████ | 1314/1460 [09:00<01:01,  2.36it/s]



 90%|█████████ | 1315/1460 [09:00<00:49,  2.93it/s]



 90%|█████████ | 1316/1460 [09:01<00:59,  2.43it/s]



 90%|█████████ | 1317/1460 [09:01<00:48,  2.93it/s]



 90%|█████████ | 1318/1460 [09:02<01:05,  2.18it/s]



 90%|█████████ | 1319/1460 [09:02<01:01,  2.30it/s]



 90%|█████████ | 1321/1460 [09:03<01:10,  1.97it/s]



 91%|█████████ | 1322/1460 [09:04<00:57,  2.40it/s]



 91%|█████████ | 1324/1460 [09:04<00:51,  2.64it/s]



 91%|█████████ | 1325/1460 [09:05<00:47,  2.84it/s]



 91%|█████████ | 1326/1460 [09:05<00:52,  2.54it/s]



 91%|█████████ | 1327/1460 [09:06<00:59,  2.25it/s]



 91%|█████████ | 1328/1460 [09:06<00:48,  2.72it/s]



 91%|█████████ | 1329/1460 [09:07<01:04,  2.04it/s]



 91%|█████████ | 1330/1460 [09:07<00:51,  2.53it/s]



 91%|█████████ | 1331/1460 [09:07<00:43,  3.00it/s]



 91%|█████████ | 1332/1460 [09:07<00:50,  2.55it/s]



 91%|█████████▏| 1333/1460 [09:08<00:45,  2.77it/s]



 91%|█████████▏| 1334/1460 [09:08<00:49,  2.54it/s]



 91%|█████████▏| 1335/1460 [09:09<00:52,  2.37it/s]



 92%|█████████▏| 1336/1460 [09:09<00:47,  2.59it/s]



 92%|█████████▏| 1337/1460 [09:10<01:00,  2.05it/s]



 92%|█████████▏| 1338/1460 [09:10<00:46,  2.60it/s]



 92%|█████████▏| 1339/1460 [09:10<00:41,  2.90it/s]



 92%|█████████▏| 1340/1460 [09:11<00:47,  2.50it/s]



 92%|█████████▏| 1341/1460 [09:11<00:41,  2.88it/s]



 92%|█████████▏| 1342/1460 [09:11<00:46,  2.55it/s]



 92%|█████████▏| 1343/1460 [09:12<00:47,  2.46it/s]



 92%|█████████▏| 1344/1460 [09:12<00:52,  2.23it/s]



 92%|█████████▏| 1345/1460 [09:13<00:57,  2.01it/s]



 92%|█████████▏| 1346/1460 [09:13<00:56,  2.02it/s]



 92%|█████████▏| 1348/1460 [09:14<00:39,  2.81it/s]



 92%|█████████▏| 1349/1460 [09:15<00:49,  2.25it/s]



 92%|█████████▏| 1350/1460 [09:15<00:50,  2.16it/s]



 93%|█████████▎| 1352/1460 [09:16<00:44,  2.41it/s]



 93%|█████████▎| 1353/1460 [09:16<00:43,  2.44it/s]



 93%|█████████▎| 1354/1460 [09:17<00:53,  1.99it/s]



 93%|█████████▎| 1355/1460 [09:17<00:46,  2.27it/s]



 93%|█████████▎| 1357/1460 [09:18<00:43,  2.38it/s]



 93%|█████████▎| 1358/1460 [09:18<00:35,  2.83it/s]



 93%|█████████▎| 1359/1460 [09:18<00:33,  3.02it/s]



 93%|█████████▎| 1360/1460 [09:19<00:37,  2.65it/s]



 93%|█████████▎| 1361/1460 [09:19<00:37,  2.66it/s]



 93%|█████████▎| 1362/1460 [09:20<00:52,  1.88it/s]



 93%|█████████▎| 1363/1460 [09:21<00:45,  2.14it/s]



 93%|█████████▎| 1364/1460 [09:21<00:35,  2.72it/s]



 93%|█████████▎| 1365/1460 [09:21<00:41,  2.30it/s]



 94%|█████████▎| 1366/1460 [09:21<00:35,  2.63it/s]



 94%|█████████▎| 1367/1460 [09:22<00:27,  3.33it/s]



 94%|█████████▎| 1368/1460 [09:22<00:35,  2.61it/s]



 94%|█████████▍| 1369/1460 [09:23<00:35,  2.59it/s]



 94%|█████████▍| 1370/1460 [09:23<00:48,  1.84it/s]



 94%|█████████▍| 1371/1460 [09:24<00:42,  2.10it/s]



 94%|█████████▍| 1372/1460 [09:24<00:32,  2.69it/s]



 94%|█████████▍| 1373/1460 [09:24<00:35,  2.43it/s]



 94%|█████████▍| 1374/1460 [09:25<00:28,  3.05it/s]



 94%|█████████▍| 1375/1460 [09:25<00:25,  3.38it/s]



 94%|█████████▍| 1376/1460 [09:25<00:31,  2.63it/s]



 94%|█████████▍| 1377/1460 [09:26<00:31,  2.62it/s]



 94%|█████████▍| 1378/1460 [09:27<00:43,  1.88it/s]



 94%|█████████▍| 1379/1460 [09:27<00:38,  2.09it/s]



 95%|█████████▍| 1380/1460 [09:27<00:29,  2.69it/s]



 95%|█████████▍| 1381/1460 [09:28<00:34,  2.32it/s]



 95%|█████████▍| 1382/1460 [09:28<00:32,  2.42it/s]



 95%|█████████▍| 1383/1460 [09:28<00:30,  2.51it/s]



 95%|█████████▍| 1384/1460 [09:29<00:32,  2.32it/s]



 95%|█████████▍| 1385/1460 [09:29<00:28,  2.62it/s]



 95%|█████████▍| 1386/1460 [09:30<00:34,  2.16it/s]



 95%|█████████▌| 1387/1460 [09:30<00:35,  2.08it/s]



 95%|█████████▌| 1389/1460 [09:31<00:28,  2.48it/s]



 95%|█████████▌| 1390/1460 [09:31<00:29,  2.38it/s]



 95%|█████████▌| 1392/1460 [09:32<00:25,  2.68it/s]



 95%|█████████▌| 1393/1460 [09:33<00:26,  2.54it/s]



 95%|█████████▌| 1394/1460 [09:33<00:32,  2.03it/s]



 96%|█████████▌| 1395/1460 [09:34<00:26,  2.45it/s]



 96%|█████████▌| 1396/1460 [09:34<00:25,  2.50it/s]



 96%|█████████▌| 1397/1460 [09:34<00:28,  2.24it/s]

 96%|█████████▌| 1398/1460 [09:35<00:22,  2.79it/s]



 96%|█████████▌| 1399/1460 [09:35<00:22,  2.76it/s]



 96%|█████████▌| 1400/1460 [09:35<00:22,  2.72it/s]



 96%|█████████▌| 1401/1460 [09:36<00:23,  2.53it/s]



 96%|█████████▌| 1402/1460 [09:37<00:32,  1.81it/s]



 96%|█████████▌| 1404/1460 [09:37<00:22,  2.45it/s]



 96%|█████████▌| 1405/1460 [09:38<00:21,  2.53it/s]



 96%|█████████▋| 1406/1460 [09:38<00:20,  2.69it/s]



 96%|█████████▋| 1407/1460 [09:38<00:17,  3.01it/s]



 96%|█████████▋| 1408/1460 [09:39<00:21,  2.42it/s]



 97%|█████████▋| 1409/1460 [09:39<00:20,  2.55it/s]



 97%|█████████▋| 1410/1460 [09:40<00:26,  1.92it/s]



 97%|█████████▋| 1412/1460 [09:40<00:19,  2.44it/s]



 97%|█████████▋| 1413/1460 [09:41<00:18,  2.51it/s]



 97%|█████████▋| 1414/1460 [09:41<00:16,  2.77it/s]



 97%|█████████▋| 1415/1460 [09:41<00:14,  3.15it/s]



 97%|█████████▋| 1416/1460 [09:42<00:18,  2.33it/s]



 97%|█████████▋| 1417/1460 [09:42<00:17,  2.45it/s]



 97%|█████████▋| 1418/1460 [09:43<00:22,  1.87it/s]



 97%|█████████▋| 1419/1460 [09:43<00:17,  2.41it/s]



 97%|█████████▋| 1420/1460 [09:44<00:15,  2.51it/s]



 97%|█████████▋| 1421/1460 [09:44<00:14,  2.60it/s]



 97%|█████████▋| 1422/1460 [09:45<00:15,  2.40it/s]



 98%|█████████▊| 1424/1460 [09:45<00:15,  2.27it/s]



 98%|█████████▊| 1425/1460 [09:46<00:13,  2.68it/s]



 98%|█████████▊| 1426/1460 [09:46<00:17,  2.00it/s]



 98%|█████████▊| 1427/1460 [09:47<00:16,  1.97it/s]



 98%|█████████▊| 1429/1460 [09:47<00:10,  2.85it/s]



 98%|█████████▊| 1430/1460 [09:48<00:09,  3.03it/s]



 98%|█████████▊| 1431/1460 [09:48<00:11,  2.46it/s]



 98%|█████████▊| 1432/1460 [09:49<00:13,  2.06it/s]



 98%|█████████▊| 1433/1460 [09:49<00:10,  2.61it/s]



 98%|█████████▊| 1434/1460 [09:50<00:11,  2.30it/s]



 98%|█████████▊| 1435/1460 [09:50<00:13,  1.83it/s]



 98%|█████████▊| 1436/1460 [09:51<00:10,  2.38it/s]



 98%|█████████▊| 1438/1460 [09:51<00:07,  2.97it/s]



 99%|█████████▊| 1439/1460 [09:51<00:07,  2.78it/s]



 99%|█████████▊| 1440/1460 [09:52<00:10,  1.98it/s]



 99%|█████████▉| 1442/1460 [09:53<00:06,  2.63it/s]



 99%|█████████▉| 1443/1460 [09:54<00:08,  1.99it/s]



 99%|█████████▉| 1445/1460 [09:54<00:04,  3.02it/s]



 99%|█████████▉| 1446/1460 [09:54<00:04,  3.08it/s]



 99%|█████████▉| 1447/1460 [09:55<00:04,  2.90it/s]



 99%|█████████▉| 1448/1460 [09:55<00:05,  2.02it/s]



 99%|█████████▉| 1450/1460 [09:56<00:03,  2.66it/s]



 99%|█████████▉| 1451/1460 [09:57<00:04,  2.04it/s]



 99%|█████████▉| 1452/1460 [09:57<00:03,  2.46it/s]



100%|█████████▉| 1454/1460 [09:57<00:01,  3.32it/s]



100%|█████████▉| 1455/1460 [09:58<00:01,  3.01it/s]



100%|█████████▉| 1456/1460 [09:59<00:01,  2.11it/s]



100%|█████████▉| 1458/1460 [09:59<00:00,  2.82it/s]



100%|█████████▉| 1459/1460 [09:59<00:00,  2.60it/s]



100%|██████████| 1460/1460 [10:00<00:00,  2.43it/s]
Families: 100%|██████████| 3/3 [17:17<00:00, 345.69s/it]

Runtime: 1037.076381 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]



Multiplets | family 3:   0%|          | 0/22 [00:00<?, ?it/s]




  0%|          | 0/22 [00:00<?, ?it/s]




  5%|▍         | 1/22 [00:02<00:51,  2.44s/it]




 18%|█▊        | 4/22 [00:02<00:08,  2.04it/s]




 27%|██▋       | 6/22 [00:02<00:05,  3.04it/s]




 41%|████      | 9/22 [00:04<00:06,  1.94it/s]




 45%|████▌     | 10/22 [00:05<00:05,  2.19it/s]




 59%|█████▉    | 13/22 [00:05<00:02,  3.55it/s]




 68%|██████▊   | 15/22 [00:05<00:01,  4.27it/s]




 73%|███████▎  | 16/22 [00:05<00:01,  4.66it/s]




 77%|███████▋  | 17/22 [00:07<00:02,  2.19it/s]




 82%|████████▏ | 18/22 [00:07<00:01,  2.62it/s]




100%|██████████| 22/22 [00:07<00:00,  2.95it/s]
Multiplets | family 3:   0%|          | 0/22 [00:07<?, ?it/s]




Multiplets | family 4:   0%|          | 0/1305 [00:00<?, ?it/s]




  0%|          | 0/1305 [00:00<?, ?it/s]




  0%|          | 1/1305 [00:03<1:19:54,  3.68s/it]




  0%|          | 3/1305 [00:03<21:29,  1.01it/s]




  1%|          | 8/1305 [00:03<06:14,  3.47it/s]




  1%|          | 11/1305 [00:07<14:05,  1.53it/s]




  1%|          | 13/1305 [00:07<10:58,  1.96it/s]




  1%|          | 15/1305 [00:07<08:14,  2.61it/s]




  1%|▏         | 17/1305 [00:11<15:35,  1.38it/s]




  1%|▏         | 19/1305 [00:11<12:10,  1.76it/s]




  2%|▏         | 20/1305 [00:11<10:38,  2.01it/s]




  2%|▏         | 21/1305 [00:11<09:46,  2.19it/s]




  2%|▏         | 22/1305 [00:12<09:14,  2.32it/s]




  2%|▏         | 24/1305 [00:12<06:27,  3.30it/s]




  2%|▏         | 25/1305 [00:14<16:19,  1.31it/s]




  2%|▏         | 26/1305 [00:15<14:02,  1.52it/s]




  2%|▏         | 28/1305 [00:15<11:00,  1.93it/s]




  2%|▏         | 29/1305 [00:16<10:04,  2.11it/s]




  2%|▏         | 31/1305 [00:16<07:29,  2.84it/s]




  2%|▏         | 32/1305 [00:16<07:23,  2.87it/s]




  3%|▎         | 33/1305 [00:18<14:44,  1.44it/s]




  3%|▎         | 34/1305 [00:19<13:26,  1.58it/s]




  3%|▎         | 35/1305 [00:19<10:26,  2.03it/s]




  3%|▎         | 36/1305 [00:19<10:51,  1.95it/s]




  3%|▎         | 37/1305 [00:20<09:14,  2.29it/s]




  3%|▎         | 39/1305 [00:20<06:20,  3.32it/s]




  3%|▎         | 40/1305 [00:20<06:42,  3.14it/s]




  3%|▎         | 41/1305 [00:22<14:32,  1.45it/s]




  3%|▎         | 42/1305 [00:22<12:45,  1.65it/s]




  3%|▎         | 43/1305 [00:22<10:20,  2.04it/s]




  3%|▎         | 44/1305 [00:23<10:46,  1.95it/s]




  3%|▎         | 45/1305 [00:23<09:23,  2.24it/s]




  4%|▎         | 46/1305 [00:24<08:04,  2.60it/s]




  4%|▎         | 48/1305 [00:24<06:37,  3.16it/s]




  4%|▍         | 49/1305 [00:26<12:43,  1.65it/s]




  4%|▍         | 50/1305 [00:26<12:43,  1.64it/s]




  4%|▍         | 52/1305 [00:27<12:22,  1.69it/s]




  4%|▍         | 54/1305 [00:27<08:18,  2.51it/s]




  4%|▍         | 55/1305 [00:28<07:15,  2.87it/s]




  4%|▍         | 56/1305 [00:28<07:50,  2.66it/s]




  4%|▍         | 57/1305 [00:30<13:16,  1.57it/s]




  4%|▍         | 58/1305 [00:30<14:39,  1.42it/s]




  5%|▍         | 59/1305 [00:31<11:16,  1.84it/s]




  5%|▍         | 60/1305 [00:31<10:56,  1.90it/s]




  5%|▍         | 61/1305 [00:31<08:27,  2.45it/s]




  5%|▍         | 62/1305 [00:31<06:40,  3.10it/s]




  5%|▍         | 63/1305 [00:32<08:07,  2.55it/s]




  5%|▍         | 64/1305 [00:32<07:26,  2.78it/s]




  5%|▍         | 65/1305 [00:33<12:59,  1.59it/s]




  5%|▌         | 66/1305 [00:34<15:49,  1.31it/s]




  5%|▌         | 67/1305 [00:35<12:10,  1.69it/s]




  5%|▌         | 68/1305 [00:35<10:01,  2.06it/s]




  5%|▌         | 70/1305 [00:35<06:53,  2.99it/s]




  5%|▌         | 71/1305 [00:36<07:35,  2.71it/s]




  6%|▌         | 72/1305 [00:36<07:09,  2.87it/s]




  6%|▌         | 73/1305 [00:37<11:09,  1.84it/s]




  6%|▌         | 74/1305 [00:38<14:46,  1.39it/s]




  6%|▌         | 75/1305 [00:38<12:13,  1.68it/s]




  6%|▌         | 76/1305 [00:39<09:48,  2.09it/s]




  6%|▌         | 78/1305 [00:39<07:31,  2.72it/s]




  6%|▌         | 79/1305 [00:39<07:17,  2.80it/s]




  6%|▌         | 80/1305 [00:40<07:48,  2.62it/s]




  6%|▌         | 81/1305 [00:41<10:05,  2.02it/s]




  6%|▋         | 82/1305 [00:42<14:15,  1.43it/s]




  6%|▋         | 83/1305 [00:43<14:42,  1.38it/s]




  6%|▋         | 84/1305 [00:43<11:31,  1.77it/s]




  7%|▋         | 86/1305 [00:43<06:52,  2.96it/s]




  7%|▋         | 87/1305 [00:43<06:48,  2.98it/s]




  7%|▋         | 88/1305 [00:44<09:10,  2.21it/s]




  7%|▋         | 89/1305 [00:45<10:27,  1.94it/s]




  7%|▋         | 90/1305 [00:46<14:49,  1.37it/s]




  7%|▋         | 91/1305 [00:46<12:51,  1.57it/s]




  7%|▋         | 92/1305 [00:47<10:14,  1.97it/s]




  7%|▋         | 93/1305 [00:47<08:52,  2.28it/s]




  7%|▋         | 94/1305 [00:47<06:57,  2.90it/s]




  7%|▋         | 95/1305 [00:47<06:27,  3.12it/s]




  7%|▋         | 96/1305 [00:48<11:08,  1.81it/s]




  7%|▋         | 97/1305 [00:49<09:35,  2.10it/s]




  8%|▊         | 98/1305 [00:50<13:27,  1.49it/s]




  8%|▊         | 99/1305 [00:50<12:03,  1.67it/s]




  8%|▊         | 100/1305 [00:50<09:33,  2.10it/s]




  8%|▊         | 101/1305 [00:51<09:27,  2.12it/s]




  8%|▊         | 103/1305 [00:51<07:17,  2.74it/s]




  8%|▊         | 104/1305 [00:52<10:13,  1.96it/s]




  8%|▊         | 106/1305 [00:54<10:54,  1.83it/s]




  8%|▊         | 107/1305 [00:54<10:32,  1.89it/s]




  8%|▊         | 108/1305 [00:54<09:02,  2.21it/s]




  8%|▊         | 109/1305 [00:55<09:05,  2.19it/s]




  9%|▊         | 111/1305 [00:55<07:34,  2.63it/s]




  9%|▊         | 112/1305 [00:56<09:16,  2.14it/s]




  9%|▊         | 113/1305 [00:56<09:03,  2.19it/s]




  9%|▊         | 114/1305 [00:57<11:00,  1.80it/s]




  9%|▉         | 115/1305 [00:58<11:40,  1.70it/s]




  9%|▉         | 116/1305 [00:58<10:50,  1.83it/s]




  9%|▉         | 117/1305 [00:59<09:43,  2.03it/s]




  9%|▉         | 118/1305 [00:59<08:19,  2.38it/s]




  9%|▉         | 119/1305 [00:59<06:32,  3.02it/s]




  9%|▉         | 120/1305 [01:00<07:37,  2.59it/s]




  9%|▉         | 121/1305 [01:01<11:22,  1.73it/s]




  9%|▉         | 122/1305 [01:01<12:09,  1.62it/s]




  9%|▉         | 123/1305 [01:02<10:46,  1.83it/s]




 10%|▉         | 124/1305 [01:02<11:39,  1.69it/s]




 10%|▉         | 125/1305 [01:03<10:39,  1.84it/s]




 10%|▉         | 127/1305 [01:03<06:38,  2.96it/s]

 10%|▉         | 128/1305 [01:04<08:44,  2.24it/s]




 10%|▉         | 129/1305 [01:05<10:38,  1.84it/s]




 10%|▉         | 130/1305 [01:05<11:26,  1.71it/s]




 10%|█         | 131/1305 [01:05<08:52,  2.21it/s]




 10%|█         | 132/1305 [01:06<10:35,  1.84it/s]




 10%|█         | 133/1305 [01:07<10:03,  1.94it/s]




 10%|█         | 134/1305 [01:07<08:09,  2.39it/s]




 10%|█         | 135/1305 [01:07<08:37,  2.26it/s]




 10%|█         | 136/1305 [01:08<07:38,  2.55it/s]




 10%|█         | 137/1305 [01:09<12:44,  1.53it/s]




 11%|█         | 138/1305 [01:10<12:38,  1.54it/s]




 11%|█         | 140/1305 [01:10<09:36,  2.02it/s]




 11%|█         | 141/1305 [01:11<09:02,  2.15it/s]




 11%|█         | 143/1305 [01:11<07:22,  2.62it/s]




 11%|█         | 144/1305 [01:11<07:03,  2.74it/s]




 11%|█         | 145/1305 [01:13<11:26,  1.69it/s]




 11%|█         | 146/1305 [01:13<11:28,  1.68it/s]




 11%|█▏        | 147/1305 [01:13<09:15,  2.08it/s]




 11%|█▏        | 148/1305 [01:14<10:53,  1.77it/s]




 11%|█▏        | 149/1305 [01:14<08:56,  2.15it/s]




 12%|█▏        | 151/1305 [01:15<07:51,  2.45it/s]




 12%|█▏        | 152/1305 [01:16<07:58,  2.41it/s]




 12%|█▏        | 153/1305 [01:17<11:18,  1.70it/s]




 12%|█▏        | 154/1305 [01:17<12:07,  1.58it/s]




 12%|█▏        | 155/1305 [01:18<09:34,  2.00it/s]




 12%|█▏        | 156/1305 [01:18<09:02,  2.12it/s]




 12%|█▏        | 157/1305 [01:18<08:03,  2.37it/s]




 12%|█▏        | 158/1305 [01:19<08:31,  2.24it/s]




 12%|█▏        | 159/1305 [01:19<07:44,  2.47it/s]




 12%|█▏        | 160/1305 [01:19<07:24,  2.58it/s]




 12%|█▏        | 161/1305 [01:21<12:25,  1.53it/s]




 12%|█▏        | 162/1305 [01:21<12:28,  1.53it/s]




 13%|█▎        | 164/1305 [01:22<08:46,  2.17it/s]




 13%|█▎        | 165/1305 [01:22<07:50,  2.42it/s]




 13%|█▎        | 166/1305 [01:23<08:30,  2.23it/s]




 13%|█▎        | 167/1305 [01:23<07:47,  2.44it/s]




 13%|█▎        | 168/1305 [01:23<06:56,  2.73it/s]




 13%|█▎        | 169/1305 [01:24<11:42,  1.62it/s]




 13%|█▎        | 170/1305 [01:25<11:26,  1.65it/s]




 13%|█▎        | 172/1305 [01:25<08:14,  2.29it/s]




 13%|█▎        | 173/1305 [01:26<08:09,  2.31it/s]




 13%|█▎        | 174/1305 [01:26<08:38,  2.18it/s]




 13%|█▎        | 175/1305 [01:27<07:44,  2.43it/s]




 13%|█▎        | 176/1305 [01:27<06:32,  2.88it/s]




 14%|█▎        | 177/1305 [01:28<11:56,  1.58it/s]




 14%|█▎        | 178/1305 [01:29<12:02,  1.56it/s]




 14%|█▍        | 180/1305 [01:29<08:03,  2.33it/s]




 14%|█▍        | 181/1305 [01:30<07:21,  2.55it/s]




 14%|█▍        | 182/1305 [01:31<11:15,  1.66it/s]




 14%|█▍        | 183/1305 [01:31<09:28,  1.98it/s]




 14%|█▍        | 184/1305 [01:31<07:36,  2.46it/s]




 14%|█▍        | 185/1305 [01:32<10:05,  1.85it/s]




 14%|█▍        | 186/1305 [01:33<11:05,  1.68it/s]




 14%|█▍        | 188/1305 [01:33<09:04,  2.05it/s]




 14%|█▍        | 189/1305 [01:34<07:31,  2.47it/s]




 15%|█▍        | 190/1305 [01:34<09:38,  1.93it/s]




 15%|█▍        | 191/1305 [01:35<10:24,  1.78it/s]




 15%|█▍        | 193/1305 [01:36<09:03,  2.05it/s]




 15%|█▍        | 194/1305 [01:37<10:14,  1.81it/s]




 15%|█▍        | 195/1305 [01:37<08:21,  2.21it/s]




 15%|█▌        | 196/1305 [01:37<08:56,  2.07it/s]




 15%|█▌        | 198/1305 [01:38<08:34,  2.15it/s]




 15%|█▌        | 199/1305 [01:39<09:11,  2.00it/s]




 15%|█▌        | 201/1305 [01:40<08:45,  2.10it/s]




 15%|█▌        | 202/1305 [01:40<09:23,  1.96it/s]




 16%|█▌        | 203/1305 [01:41<07:33,  2.43it/s]




 16%|█▌        | 204/1305 [01:41<08:46,  2.09it/s]




 16%|█▌        | 206/1305 [01:42<08:33,  2.14it/s]




 16%|█▌        | 207/1305 [01:43<08:40,  2.11it/s]




 16%|█▌        | 208/1305 [01:43<07:12,  2.54it/s]




 16%|█▌        | 209/1305 [01:44<08:55,  2.05it/s]




 16%|█▌        | 210/1305 [01:44<10:19,  1.77it/s]




 16%|█▌        | 212/1305 [01:45<09:40,  1.88it/s]




 16%|█▋        | 213/1305 [01:45<07:49,  2.32it/s]




 16%|█▋        | 214/1305 [01:46<08:06,  2.24it/s]




 16%|█▋        | 215/1305 [01:46<07:35,  2.40it/s]




 17%|█▋        | 216/1305 [01:47<10:42,  1.69it/s]




 17%|█▋        | 218/1305 [01:48<08:55,  2.03it/s]




 17%|█▋        | 219/1305 [01:49<09:58,  1.81it/s]




 17%|█▋        | 220/1305 [01:49<08:52,  2.04it/s]




 17%|█▋        | 221/1305 [01:49<07:32,  2.40it/s]




 17%|█▋        | 222/1305 [01:50<07:57,  2.27it/s]




 17%|█▋        | 223/1305 [01:50<07:40,  2.35it/s]




 17%|█▋        | 224/1305 [01:51<10:17,  1.75it/s]




 17%|█▋        | 225/1305 [01:51<08:14,  2.19it/s]




 17%|█▋        | 226/1305 [01:52<09:26,  1.90it/s]




 17%|█▋        | 227/1305 [01:53<09:49,  1.83it/s]




 17%|█▋        | 228/1305 [01:53<09:55,  1.81it/s]




 18%|█▊        | 229/1305 [01:53<07:42,  2.32it/s]




 18%|█▊        | 230/1305 [01:54<07:24,  2.42it/s]




 18%|█▊        | 231/1305 [01:54<07:11,  2.49it/s]




 18%|█▊        | 232/1305 [01:55<09:17,  1.92it/s]




 18%|█▊        | 233/1305 [01:55<08:14,  2.17it/s]




 18%|█▊        | 234/1305 [01:56<08:24,  2.12it/s]




 18%|█▊        | 235/1305 [01:56<09:43,  1.83it/s]




 18%|█▊        | 236/1305 [01:57<09:01,  1.97it/s]




 18%|█▊        | 237/1305 [01:57<07:38,  2.33it/s]




 18%|█▊        | 238/1305 [01:57<06:58,  2.55it/s]




 18%|█▊        | 239/1305 [01:58<06:06,  2.91it/s]




 18%|█▊        | 240/1305 [01:59<09:33,  1.86it/s]




 18%|█▊        | 241/1305 [01:59<09:30,  1.86it/s]




 19%|█▊        | 242/1305 [01:59<07:43,  2.29it/s]




 19%|█▊        | 243/1305 [02:00<10:23,  1.70it/s]




 19%|█▊        | 244/1305 [02:00<08:40,  2.04it/s]




 19%|█▉        | 245/1305 [02:01<07:04,  2.50it/s]




 19%|█▉        | 246/1305 [02:01<08:25,  2.09it/s]




 19%|█▉        | 247/1305 [02:02<07:07,  2.47it/s]




 19%|█▉        | 248/1305 [02:02<08:52,  1.98it/s]




 19%|█▉        | 249/1305 [02:03<09:06,  1.93it/s]




 19%|█▉        | 250/1305 [02:03<07:06,  2.47it/s]




 19%|█▉        | 251/1305 [02:04<12:24,  1.42it/s]




 19%|█▉        | 253/1305 [02:05<07:43,  2.27it/s]




 19%|█▉        | 254/1305 [02:05<08:14,  2.13it/s]




 20%|█▉        | 255/1305 [02:06<08:11,  2.14it/s]




 20%|█▉        | 256/1305 [02:06<07:38,  2.29it/s]




 20%|█▉        | 257/1305 [02:07<10:50,  1.61it/s]




 20%|█▉        | 258/1305 [02:07<09:16,  1.88it/s]

 20%|█▉        | 259/1305 [02:08<10:13,  1.70it/s]




 20%|██        | 261/1305 [02:09<09:36,  1.81it/s]




 20%|██        | 262/1305 [02:10<09:07,  1.90it/s]




 20%|██        | 264/1305 [02:10<07:51,  2.21it/s]




 20%|██        | 265/1305 [02:11<09:52,  1.76it/s]




 20%|██        | 266/1305 [02:11<08:10,  2.12it/s]




 20%|██        | 267/1305 [02:12<09:05,  1.90it/s]




 21%|██        | 269/1305 [02:13<08:37,  2.00it/s]




 21%|██        | 270/1305 [02:13<08:02,  2.14it/s]




 21%|██        | 271/1305 [02:14<07:03,  2.44it/s]




 21%|██        | 272/1305 [02:14<07:40,  2.24it/s]




 21%|██        | 273/1305 [02:15<10:07,  1.70it/s]




 21%|██        | 274/1305 [02:15<08:08,  2.11it/s]




 21%|██        | 275/1305 [02:16<08:44,  1.96it/s]




 21%|██        | 276/1305 [02:16<06:53,  2.49it/s]




 21%|██        | 277/1305 [02:17<08:44,  1.96it/s]




 21%|██▏       | 278/1305 [02:17<07:31,  2.27it/s]




 21%|██▏       | 279/1305 [02:18<07:20,  2.33it/s]




 21%|██▏       | 280/1305 [02:18<08:59,  1.90it/s]




 22%|██▏       | 281/1305 [02:19<10:22,  1.64it/s]




 22%|██▏       | 282/1305 [02:19<08:43,  1.95it/s]




 22%|██▏       | 283/1305 [02:20<08:24,  2.02it/s]




 22%|██▏       | 284/1305 [02:20<07:05,  2.40it/s]




 22%|██▏       | 285/1305 [02:21<07:56,  2.14it/s]




 22%|██▏       | 286/1305 [02:21<08:27,  2.01it/s]




 22%|██▏       | 287/1305 [02:22<09:18,  1.82it/s]




 22%|██▏       | 288/1305 [02:22<08:18,  2.04it/s]




 22%|██▏       | 289/1305 [02:23<09:05,  1.86it/s]




 22%|██▏       | 290/1305 [02:23<08:09,  2.07it/s]




 22%|██▏       | 291/1305 [02:24<09:23,  1.80it/s]




 22%|██▏       | 292/1305 [02:24<07:24,  2.28it/s]




 22%|██▏       | 293/1305 [02:25<07:15,  2.32it/s]




 23%|██▎       | 294/1305 [02:25<07:53,  2.14it/s]




 23%|██▎       | 295/1305 [02:26<10:58,  1.53it/s]




 23%|██▎       | 296/1305 [02:26<08:18,  2.03it/s]




 23%|██▎       | 297/1305 [02:27<08:19,  2.02it/s]




 23%|██▎       | 298/1305 [02:28<09:39,  1.74it/s]




 23%|██▎       | 299/1305 [02:28<09:12,  1.82it/s]




 23%|██▎       | 300/1305 [02:28<07:57,  2.10it/s]




 23%|██▎       | 301/1305 [02:29<06:31,  2.56it/s]




 23%|██▎       | 302/1305 [02:29<07:06,  2.35it/s]




 23%|██▎       | 303/1305 [02:30<10:11,  1.64it/s]




 23%|██▎       | 304/1305 [02:30<08:11,  2.04it/s]




 23%|██▎       | 305/1305 [02:31<07:29,  2.22it/s]




 23%|██▎       | 306/1305 [02:32<09:51,  1.69it/s]




 24%|██▎       | 307/1305 [02:32<09:08,  1.82it/s]




 24%|██▎       | 308/1305 [02:32<08:16,  2.01it/s]




 24%|██▍       | 310/1305 [02:33<06:14,  2.66it/s]




 24%|██▍       | 311/1305 [02:34<10:39,  1.55it/s]




 24%|██▍       | 313/1305 [02:35<07:34,  2.18it/s]




 24%|██▍       | 314/1305 [02:36<10:02,  1.64it/s]




 24%|██▍       | 316/1305 [02:36<07:50,  2.10it/s]




 24%|██▍       | 317/1305 [02:37<07:29,  2.20it/s]




 24%|██▍       | 318/1305 [02:37<06:11,  2.66it/s]




 24%|██▍       | 319/1305 [02:38<10:57,  1.50it/s]




 25%|██▍       | 321/1305 [02:39<07:43,  2.12it/s]




 25%|██▍       | 322/1305 [02:40<09:51,  1.66it/s]




 25%|██▍       | 324/1305 [02:41<08:29,  1.93it/s]




 25%|██▍       | 326/1305 [02:41<05:47,  2.82it/s]




 25%|██▌       | 327/1305 [02:42<09:54,  1.64it/s]




 25%|██▌       | 328/1305 [02:43<08:21,  1.95it/s]




 25%|██▌       | 329/1305 [02:43<07:21,  2.21it/s]




 25%|██▌       | 330/1305 [02:44<09:09,  1.77it/s]




 25%|██▌       | 331/1305 [02:44<07:37,  2.13it/s]




 25%|██▌       | 332/1305 [02:45<08:16,  1.96it/s]




 26%|██▌       | 335/1305 [02:46<09:19,  1.73it/s]




 26%|██▌       | 336/1305 [02:47<08:12,  1.97it/s]




 26%|██▌       | 338/1305 [02:48<08:19,  1.94it/s]




 26%|██▌       | 339/1305 [02:48<07:03,  2.28it/s]




 26%|██▌       | 340/1305 [02:48<07:28,  2.15it/s]




 26%|██▌       | 341/1305 [02:49<06:04,  2.64it/s]




 26%|██▋       | 343/1305 [02:51<10:51,  1.48it/s]




 26%|██▋       | 344/1305 [02:51<08:48,  1.82it/s]




 27%|██▋       | 346/1305 [02:52<07:34,  2.11it/s]




 27%|██▋       | 347/1305 [02:52<06:24,  2.49it/s]




 27%|██▋       | 348/1305 [02:52<06:16,  2.54it/s]




 27%|██▋       | 349/1305 [02:53<07:24,  2.15it/s]




 27%|██▋       | 350/1305 [02:53<06:17,  2.53it/s]




 27%|██▋       | 351/1305 [02:54<11:19,  1.40it/s]




 27%|██▋       | 352/1305 [02:55<09:34,  1.66it/s]




 27%|██▋       | 353/1305 [02:55<08:09,  1.95it/s]




 27%|██▋       | 354/1305 [02:56<08:22,  1.89it/s]




 27%|██▋       | 355/1305 [02:56<06:25,  2.46it/s]




 27%|██▋       | 357/1305 [02:57<07:37,  2.07it/s]




 27%|██▋       | 358/1305 [02:57<06:13,  2.54it/s]




 28%|██▊       | 359/1305 [02:58<09:46,  1.61it/s]




 28%|██▊       | 360/1305 [02:59<09:08,  1.72it/s]




 28%|██▊       | 361/1305 [02:59<07:36,  2.07it/s]




 28%|██▊       | 362/1305 [03:00<08:36,  1.83it/s]




 28%|██▊       | 364/1305 [03:00<06:01,  2.60it/s]




 28%|██▊       | 365/1305 [03:01<08:37,  1.81it/s]




 28%|██▊       | 366/1305 [03:02<08:16,  1.89it/s]




 28%|██▊       | 367/1305 [03:03<12:05,  1.29it/s]




 28%|██▊       | 368/1305 [03:03<10:12,  1.53it/s]




 28%|██▊       | 369/1305 [03:04<08:44,  1.78it/s]




 28%|██▊       | 370/1305 [03:04<07:37,  2.04it/s]




 29%|██▊       | 372/1305 [03:05<06:57,  2.24it/s]




 29%|██▊       | 373/1305 [03:06<08:20,  1.86it/s]




 29%|██▊       | 374/1305 [03:06<09:14,  1.68it/s]




 29%|██▊       | 375/1305 [03:07<09:50,  1.58it/s]




 29%|██▉       | 376/1305 [03:08<09:03,  1.71it/s]




 29%|██▉       | 377/1305 [03:08<09:11,  1.68it/s]




 29%|██▉       | 378/1305 [03:09<08:28,  1.82it/s]




 29%|██▉       | 379/1305 [03:09<06:51,  2.25it/s]




 29%|██▉       | 380/1305 [03:10<08:29,  1.81it/s]




 29%|██▉       | 382/1305 [03:10<06:20,  2.42it/s]




 29%|██▉       | 383/1305 [03:11<07:52,  1.95it/s]




 29%|██▉       | 384/1305 [03:12<08:49,  1.74it/s]




 30%|██▉       | 385/1305 [03:12<08:51,  1.73it/s]




 30%|██▉       | 386/1305 [03:13<07:42,  1.99it/s]




 30%|██▉       | 387/1305 [03:13<07:09,  2.14it/s]




 30%|██▉       | 388/1305 [03:14<07:21,  2.08it/s]




 30%|██▉       | 389/1305 [03:14<06:43,  2.27it/s]




 30%|██▉       | 390/1305 [03:14<06:08,  2.48it/s]




 30%|██▉       | 391/1305 [03:15<06:44,  2.26it/s]




 30%|███       | 392/1305 [03:16<08:29,  1.79it/s]




 30%|███       | 393/1305 [03:16<09:06,  1.67it/s]

 30%|███       | 394/1305 [03:17<08:40,  1.75it/s]




 30%|███       | 395/1305 [03:17<07:24,  2.05it/s]




 30%|███       | 396/1305 [03:17<06:44,  2.25it/s]




 30%|███       | 397/1305 [03:18<06:30,  2.33it/s]




 30%|███       | 398/1305 [03:18<06:31,  2.32it/s]




 31%|███       | 399/1305 [03:19<06:40,  2.26it/s]




 31%|███       | 400/1305 [03:19<07:30,  2.01it/s]




 31%|███       | 401/1305 [03:20<08:51,  1.70it/s]




 31%|███       | 402/1305 [03:21<09:37,  1.56it/s]




 31%|███       | 404/1305 [03:21<06:27,  2.32it/s]




 31%|███       | 405/1305 [03:22<07:09,  2.10it/s]




 31%|███       | 406/1305 [03:22<05:42,  2.62it/s]




 31%|███       | 407/1305 [03:23<06:38,  2.26it/s]




 31%|███▏      | 408/1305 [03:24<09:03,  1.65it/s]




 31%|███▏      | 409/1305 [03:25<10:33,  1.41it/s]




 31%|███▏      | 411/1305 [03:25<07:00,  2.12it/s]




 32%|███▏      | 412/1305 [03:25<05:49,  2.56it/s]




 32%|███▏      | 413/1305 [03:26<06:50,  2.17it/s]




 32%|███▏      | 414/1305 [03:26<06:29,  2.29it/s]




 32%|███▏      | 415/1305 [03:27<06:45,  2.19it/s]




 32%|███▏      | 416/1305 [03:28<09:13,  1.61it/s]




 32%|███▏      | 417/1305 [03:28<10:03,  1.47it/s]




 32%|███▏      | 418/1305 [03:29<07:41,  1.92it/s]




 32%|███▏      | 419/1305 [03:29<07:23,  2.00it/s]




 32%|███▏      | 420/1305 [03:29<06:31,  2.26it/s]




 32%|███▏      | 421/1305 [03:30<06:23,  2.31it/s]




 32%|███▏      | 422/1305 [03:30<05:49,  2.53it/s]




 32%|███▏      | 423/1305 [03:31<06:04,  2.42it/s]




 32%|███▏      | 424/1305 [03:32<09:01,  1.63it/s]




 33%|███▎      | 425/1305 [03:32<09:01,  1.62it/s]




 33%|███▎      | 426/1305 [03:32<07:15,  2.02it/s]




 33%|███▎      | 427/1305 [03:33<07:01,  2.08it/s]




 33%|███▎      | 428/1305 [03:33<06:19,  2.31it/s]




 33%|███▎      | 429/1305 [03:34<05:45,  2.53it/s]




 33%|███▎      | 430/1305 [03:34<06:52,  2.12it/s]




 33%|███▎      | 431/1305 [03:34<05:52,  2.48it/s]




 33%|███▎      | 432/1305 [03:36<10:59,  1.32it/s]




 33%|███▎      | 433/1305 [03:37<10:01,  1.45it/s]




 33%|███▎      | 434/1305 [03:37<07:37,  1.91it/s]




 33%|███▎      | 436/1305 [03:38<07:08,  2.03it/s]




 34%|███▎      | 438/1305 [03:38<05:43,  2.53it/s]




 34%|███▎      | 439/1305 [03:39<06:17,  2.30it/s]




 34%|███▎      | 440/1305 [03:40<09:03,  1.59it/s]




 34%|███▍      | 441/1305 [03:40<08:27,  1.70it/s]




 34%|███▍      | 442/1305 [03:41<07:04,  2.03it/s]




 34%|███▍      | 444/1305 [03:41<06:43,  2.14it/s]




 34%|███▍      | 446/1305 [03:42<05:53,  2.43it/s]




 34%|███▍      | 447/1305 [03:43<06:03,  2.36it/s]




 34%|███▍      | 448/1305 [03:44<09:51,  1.45it/s]




 34%|███▍      | 449/1305 [03:44<08:27,  1.69it/s]




 34%|███▍      | 450/1305 [03:45<06:36,  2.16it/s]




 35%|███▍      | 451/1305 [03:45<06:19,  2.25it/s]




 35%|███▍      | 452/1305 [03:46<06:50,  2.08it/s]




 35%|███▍      | 454/1305 [03:46<05:47,  2.45it/s]




 35%|███▍      | 455/1305 [03:46<05:03,  2.80it/s]




 35%|███▍      | 456/1305 [03:48<10:21,  1.37it/s]




 35%|███▌      | 457/1305 [03:48<08:47,  1.61it/s]




 35%|███▌      | 459/1305 [03:49<06:06,  2.31it/s]




 35%|███▌      | 460/1305 [03:49<06:25,  2.19it/s]




 35%|███▌      | 462/1305 [03:50<05:39,  2.48it/s]




 35%|███▌      | 463/1305 [03:50<05:24,  2.60it/s]




 36%|███▌      | 464/1305 [03:52<09:32,  1.47it/s]




 36%|███▌      | 465/1305 [03:52<08:50,  1.58it/s]




 36%|███▌      | 467/1305 [03:53<05:41,  2.46it/s]




 36%|███▌      | 468/1305 [03:53<06:39,  2.10it/s]




 36%|███▌      | 469/1305 [03:54<05:39,  2.47it/s]




 36%|███▌      | 470/1305 [03:54<06:47,  2.05it/s]




 36%|███▌      | 471/1305 [03:54<05:30,  2.52it/s]




 36%|███▌      | 472/1305 [03:56<09:42,  1.43it/s]




 36%|███▌      | 473/1305 [03:56<09:03,  1.53it/s]




 36%|███▋      | 475/1305 [03:57<06:08,  2.25it/s]




 36%|███▋      | 476/1305 [03:57<06:13,  2.22it/s]




 37%|███▋      | 477/1305 [03:57<05:07,  2.70it/s]




 37%|███▋      | 478/1305 [03:58<07:29,  1.84it/s]




 37%|███▋      | 479/1305 [03:59<05:54,  2.33it/s]




 37%|███▋      | 480/1305 [04:00<09:10,  1.50it/s]




 37%|███▋      | 481/1305 [04:00<08:11,  1.68it/s]




 37%|███▋      | 482/1305 [04:01<07:17,  1.88it/s]




 37%|███▋      | 483/1305 [04:01<06:09,  2.23it/s]




 37%|███▋      | 484/1305 [04:01<06:14,  2.19it/s]




 37%|███▋      | 486/1305 [04:02<06:36,  2.07it/s]




 37%|███▋      | 488/1305 [04:04<07:27,  1.83it/s]




 37%|███▋      | 489/1305 [04:04<07:15,  1.87it/s]




 38%|███▊      | 490/1305 [04:05<06:45,  2.01it/s]




 38%|███▊      | 491/1305 [04:05<06:01,  2.25it/s]




 38%|███▊      | 492/1305 [04:05<06:22,  2.13it/s]




 38%|███▊      | 494/1305 [04:06<06:00,  2.25it/s]




 38%|███▊      | 495/1305 [04:07<06:17,  2.15it/s]




 38%|███▊      | 496/1305 [04:08<07:34,  1.78it/s]




 38%|███▊      | 497/1305 [04:08<07:29,  1.80it/s]




 38%|███▊      | 498/1305 [04:09<07:13,  1.86it/s]




 38%|███▊      | 499/1305 [04:09<06:08,  2.19it/s]




 38%|███▊      | 500/1305 [04:10<07:26,  1.80it/s]




 38%|███▊      | 502/1305 [04:10<05:21,  2.50it/s]




 39%|███▊      | 503/1305 [04:11<06:27,  2.07it/s]




 39%|███▊      | 504/1305 [04:12<07:07,  1.88it/s]




 39%|███▊      | 505/1305 [04:12<07:03,  1.89it/s]




 39%|███▉      | 506/1305 [04:12<06:37,  2.01it/s]




 39%|███▉      | 507/1305 [04:13<06:13,  2.13it/s]




 39%|███▉      | 508/1305 [04:14<07:59,  1.66it/s]




 39%|███▉      | 510/1305 [04:14<06:07,  2.16it/s]




 39%|███▉      | 511/1305 [04:15<06:54,  1.91it/s]




 39%|███▉      | 512/1305 [04:15<06:07,  2.16it/s]




 39%|███▉      | 513/1305 [04:16<06:08,  2.15it/s]




 39%|███▉      | 514/1305 [04:16<06:51,  1.92it/s]




 39%|███▉      | 515/1305 [04:17<07:50,  1.68it/s]




 40%|███▉      | 516/1305 [04:18<07:01,  1.87it/s]




 40%|███▉      | 517/1305 [04:18<05:37,  2.33it/s]




 40%|███▉      | 518/1305 [04:18<05:26,  2.41it/s]




 40%|███▉      | 519/1305 [04:19<06:32,  2.00it/s]




 40%|███▉      | 520/1305 [04:19<05:34,  2.34it/s]




 40%|███▉      | 521/1305 [04:20<06:07,  2.14it/s]




 40%|████      | 522/1305 [04:20<06:41,  1.95it/s]




 40%|████      | 523/1305 [04:21<08:58,  1.45it/s]




 40%|████      | 524/1305 [04:22<06:43,  1.93it/s]




 40%|████      | 525/1305 [04:22<06:40,  1.95it/s]




 40%|████      | 526/1305 [04:22<06:10,  2.10it/s]

 40%|████      | 527/1305 [04:23<06:01,  2.15it/s]




 40%|████      | 528/1305 [04:23<04:39,  2.78it/s]




 41%|████      | 529/1305 [04:24<05:59,  2.16it/s]




 41%|████      | 530/1305 [04:24<05:38,  2.29it/s]




 41%|████      | 531/1305 [04:25<08:28,  1.52it/s]




 41%|████      | 532/1305 [04:26<08:23,  1.53it/s]




 41%|████      | 533/1305 [04:26<07:29,  1.72it/s]




 41%|████      | 534/1305 [04:27<06:05,  2.11it/s]




 41%|████      | 536/1305 [04:27<04:13,  3.03it/s]




 41%|████      | 537/1305 [04:28<06:06,  2.10it/s]




 41%|████      | 538/1305 [04:28<05:12,  2.45it/s]




 41%|████▏     | 539/1305 [04:29<07:46,  1.64it/s]




 41%|████▏     | 540/1305 [04:30<07:48,  1.63it/s]




 41%|████▏     | 541/1305 [04:30<08:02,  1.58it/s]




 42%|████▏     | 542/1305 [04:31<06:05,  2.09it/s]




 42%|████▏     | 543/1305 [04:31<05:02,  2.52it/s]




 42%|████▏     | 545/1305 [04:32<05:47,  2.19it/s]




 42%|████▏     | 546/1305 [04:32<04:57,  2.55it/s]




 42%|████▏     | 547/1305 [04:33<06:46,  1.86it/s]




 42%|████▏     | 548/1305 [04:34<08:04,  1.56it/s]




 42%|████▏     | 549/1305 [04:34<07:46,  1.62it/s]




 42%|████▏     | 551/1305 [04:35<04:56,  2.55it/s]




 42%|████▏     | 552/1305 [04:35<04:17,  2.92it/s]




 42%|████▏     | 553/1305 [04:36<05:31,  2.27it/s]




 42%|████▏     | 554/1305 [04:36<05:17,  2.37it/s]




 43%|████▎     | 555/1305 [04:37<06:24,  1.95it/s]




 43%|████▎     | 556/1305 [04:38<08:30,  1.47it/s]




 43%|████▎     | 557/1305 [04:38<07:49,  1.59it/s]




 43%|████▎     | 558/1305 [04:39<06:32,  1.91it/s]




 43%|████▎     | 560/1305 [04:39<04:29,  2.76it/s]




 43%|████▎     | 561/1305 [04:39<04:57,  2.50it/s]




 43%|████▎     | 562/1305 [04:40<04:44,  2.61it/s]




 43%|████▎     | 563/1305 [04:41<07:18,  1.69it/s]




 43%|████▎     | 564/1305 [04:42<08:11,  1.51it/s]




 43%|████▎     | 565/1305 [04:43<08:31,  1.45it/s]




 44%|████▎     | 568/1305 [04:43<04:41,  2.62it/s]




 44%|████▎     | 569/1305 [04:43<05:08,  2.38it/s]




 44%|████▎     | 570/1305 [04:44<04:21,  2.81it/s]




 44%|████▍     | 571/1305 [04:45<06:58,  1.75it/s]




 44%|████▍     | 572/1305 [04:46<08:03,  1.51it/s]




 44%|████▍     | 573/1305 [04:46<07:54,  1.54it/s]




 44%|████▍     | 575/1305 [04:47<05:28,  2.22it/s]




 44%|████▍     | 576/1305 [04:47<05:02,  2.41it/s]




 44%|████▍     | 577/1305 [04:47<04:21,  2.79it/s]




 44%|████▍     | 578/1305 [04:48<04:36,  2.63it/s]




 44%|████▍     | 579/1305 [04:49<07:15,  1.67it/s]




 44%|████▍     | 580/1305 [04:50<07:47,  1.55it/s]




 45%|████▍     | 581/1305 [04:50<07:53,  1.53it/s]




 45%|████▍     | 583/1305 [04:51<05:16,  2.28it/s]




 45%|████▍     | 584/1305 [04:51<04:42,  2.55it/s]




 45%|████▍     | 585/1305 [04:51<04:31,  2.65it/s]




 45%|████▍     | 586/1305 [04:51<04:06,  2.91it/s]




 45%|████▍     | 587/1305 [04:53<07:19,  1.63it/s]




 45%|████▌     | 588/1305 [04:54<07:39,  1.56it/s]




 45%|████▌     | 589/1305 [04:54<07:50,  1.52it/s]




 45%|████▌     | 590/1305 [04:54<05:57,  2.00it/s]




 45%|████▌     | 591/1305 [04:54<04:39,  2.55it/s]




 45%|████▌     | 592/1305 [04:55<04:20,  2.74it/s]




 45%|████▌     | 593/1305 [04:55<04:15,  2.78it/s]




 46%|████▌     | 594/1305 [04:55<03:20,  3.54it/s]




 46%|████▌     | 595/1305 [04:57<07:27,  1.59it/s]




 46%|████▌     | 596/1305 [04:58<09:49,  1.20it/s]




 46%|████▌     | 597/1305 [04:58<07:16,  1.62it/s]




 46%|████▌     | 598/1305 [04:58<06:12,  1.90it/s]




 46%|████▌     | 599/1305 [04:59<05:01,  2.34it/s]




 46%|████▌     | 601/1305 [04:59<03:36,  3.24it/s]




 46%|████▌     | 602/1305 [04:59<04:10,  2.81it/s]




 46%|████▌     | 603/1305 [05:01<06:59,  1.67it/s]




 46%|████▋     | 604/1305 [05:02<09:27,  1.24it/s]




 46%|████▋     | 605/1305 [05:02<07:13,  1.61it/s]




 46%|████▋     | 606/1305 [05:02<05:49,  2.00it/s]




 47%|████▋     | 608/1305 [05:03<04:42,  2.47it/s]




 47%|████▋     | 609/1305 [05:03<04:11,  2.77it/s]




 47%|████▋     | 610/1305 [05:03<03:24,  3.40it/s]




 47%|████▋     | 611/1305 [05:05<07:05,  1.63it/s]




 47%|████▋     | 612/1305 [05:06<09:03,  1.27it/s]




 47%|████▋     | 614/1305 [05:06<05:36,  2.05it/s]




 47%|████▋     | 615/1305 [05:07<05:43,  2.01it/s]




 47%|████▋     | 616/1305 [05:07<05:02,  2.28it/s]




 47%|████▋     | 618/1305 [05:08<04:00,  2.86it/s]




 47%|████▋     | 619/1305 [05:09<06:37,  1.73it/s]




 48%|████▊     | 620/1305 [05:10<07:46,  1.47it/s]




 48%|████▊     | 621/1305 [05:10<06:17,  1.81it/s]




 48%|████▊     | 623/1305 [05:11<04:56,  2.30it/s]




 48%|████▊     | 624/1305 [05:11<04:40,  2.43it/s]




 48%|████▊     | 626/1305 [05:11<03:54,  2.90it/s]




 48%|████▊     | 627/1305 [05:13<06:56,  1.63it/s]




 48%|████▊     | 628/1305 [05:14<07:17,  1.55it/s]




 48%|████▊     | 629/1305 [05:14<06:01,  1.87it/s]




 48%|████▊     | 630/1305 [05:14<05:27,  2.06it/s]




 48%|████▊     | 631/1305 [05:14<04:16,  2.63it/s]




 48%|████▊     | 632/1305 [05:15<03:51,  2.91it/s]




 49%|████▊     | 633/1305 [05:15<04:14,  2.64it/s]




 49%|████▊     | 634/1305 [05:16<05:16,  2.12it/s]




 49%|████▊     | 635/1305 [05:17<09:05,  1.23it/s]




 49%|████▊     | 636/1305 [05:18<07:20,  1.52it/s]




 49%|████▉     | 637/1305 [05:18<06:03,  1.84it/s]




 49%|████▉     | 638/1305 [05:18<04:44,  2.34it/s]




 49%|████▉     | 640/1305 [05:19<04:00,  2.77it/s]




 49%|████▉     | 641/1305 [05:19<04:33,  2.42it/s]




 49%|████▉     | 642/1305 [05:20<05:24,  2.05it/s]




 49%|████▉     | 643/1305 [05:21<08:02,  1.37it/s]




 49%|████▉     | 644/1305 [05:22<06:51,  1.61it/s]




 49%|████▉     | 645/1305 [05:22<05:44,  1.92it/s]




 50%|████▉     | 646/1305 [05:22<04:28,  2.46it/s]




 50%|████▉     | 647/1305 [05:22<04:03,  2.70it/s]




 50%|████▉     | 648/1305 [05:23<03:44,  2.92it/s]




 50%|████▉     | 649/1305 [05:23<04:59,  2.19it/s]




 50%|████▉     | 650/1305 [05:24<05:25,  2.01it/s]




 50%|████▉     | 651/1305 [05:25<07:44,  1.41it/s]




 50%|████▉     | 652/1305 [05:26<06:46,  1.61it/s]




 50%|█████     | 653/1305 [05:26<05:28,  1.99it/s]




 50%|█████     | 655/1305 [05:26<04:00,  2.70it/s]




 50%|█████     | 656/1305 [05:27<03:40,  2.94it/s]




 50%|█████     | 657/1305 [05:27<04:52,  2.22it/s]




 50%|█████     | 658/1305 [05:28<05:26,  1.98it/s]




 50%|█████     | 659/1305 [05:29<07:08,  1.51it/s]

 51%|█████     | 660/1305 [05:29<06:39,  1.62it/s]




 51%|█████     | 661/1305 [05:30<06:17,  1.71it/s]




 51%|█████     | 663/1305 [05:30<04:05,  2.61it/s]




 51%|█████     | 664/1305 [05:31<03:54,  2.74it/s]




 51%|█████     | 665/1305 [05:31<04:10,  2.56it/s]




 51%|█████     | 666/1305 [05:32<05:29,  1.94it/s]




 51%|█████     | 667/1305 [05:33<07:07,  1.49it/s]




 51%|█████     | 668/1305 [05:33<06:26,  1.65it/s]




 51%|█████▏    | 669/1305 [05:34<06:20,  1.67it/s]




 51%|█████▏    | 671/1305 [05:35<04:41,  2.25it/s]




 51%|█████▏    | 672/1305 [05:35<03:58,  2.65it/s]




 52%|█████▏    | 673/1305 [05:35<04:12,  2.50it/s]




 52%|█████▏    | 674/1305 [05:36<05:35,  1.88it/s]




 52%|█████▏    | 675/1305 [05:37<06:43,  1.56it/s]




 52%|█████▏    | 676/1305 [05:37<06:05,  1.72it/s]




 52%|█████▏    | 677/1305 [05:38<05:45,  1.82it/s]




 52%|█████▏    | 678/1305 [05:38<04:45,  2.20it/s]




 52%|█████▏    | 679/1305 [05:38<04:16,  2.44it/s]




 52%|█████▏    | 680/1305 [05:39<04:16,  2.44it/s]




 52%|█████▏    | 681/1305 [05:39<03:37,  2.87it/s]




 52%|█████▏    | 682/1305 [05:40<05:45,  1.80it/s]




 52%|█████▏    | 683/1305 [05:41<06:26,  1.61it/s]




 52%|█████▏    | 684/1305 [05:41<05:58,  1.73it/s]




 52%|█████▏    | 685/1305 [05:42<06:29,  1.59it/s]




 53%|█████▎    | 687/1305 [05:43<04:35,  2.24it/s]




 53%|█████▎    | 688/1305 [05:43<04:05,  2.52it/s]




 53%|█████▎    | 689/1305 [05:43<03:27,  2.97it/s]




 53%|█████▎    | 690/1305 [05:44<05:46,  1.77it/s]




 53%|█████▎    | 691/1305 [05:45<05:44,  1.78it/s]




 53%|█████▎    | 692/1305 [05:45<06:10,  1.66it/s]




 53%|█████▎    | 693/1305 [05:46<05:51,  1.74it/s]




 53%|█████▎    | 694/1305 [05:46<05:19,  1.91it/s]




 53%|█████▎    | 695/1305 [05:46<04:25,  2.30it/s]




 53%|█████▎    | 696/1305 [05:47<03:29,  2.90it/s]




 53%|█████▎    | 697/1305 [05:47<04:22,  2.32it/s]




 53%|█████▎    | 698/1305 [05:49<06:56,  1.46it/s]




 54%|█████▎    | 699/1305 [05:49<06:21,  1.59it/s]




 54%|█████▎    | 700/1305 [05:49<05:32,  1.82it/s]




 54%|█████▎    | 701/1305 [05:50<04:41,  2.15it/s]




 54%|█████▍    | 702/1305 [05:50<04:44,  2.12it/s]




 54%|█████▍    | 703/1305 [05:51<04:34,  2.19it/s]




 54%|█████▍    | 704/1305 [05:51<03:59,  2.51it/s]




 54%|█████▍    | 705/1305 [05:51<03:31,  2.84it/s]




 54%|█████▍    | 706/1305 [05:53<06:54,  1.44it/s]




 54%|█████▍    | 707/1305 [05:53<06:23,  1.56it/s]




 54%|█████▍    | 708/1305 [05:53<05:07,  1.94it/s]




 54%|█████▍    | 709/1305 [05:54<04:39,  2.13it/s]




 54%|█████▍    | 710/1305 [05:54<04:05,  2.42it/s]




 54%|█████▍    | 711/1305 [05:54<04:13,  2.35it/s]




 55%|█████▍    | 712/1305 [05:55<03:55,  2.52it/s]




 55%|█████▍    | 713/1305 [05:55<03:58,  2.49it/s]




 55%|█████▍    | 714/1305 [05:57<07:07,  1.38it/s]




 55%|█████▍    | 715/1305 [05:57<05:53,  1.67it/s]




 55%|█████▍    | 716/1305 [05:57<05:25,  1.81it/s]




 55%|█████▍    | 717/1305 [05:58<04:22,  2.24it/s]




 55%|█████▌    | 718/1305 [05:58<03:37,  2.69it/s]




 55%|█████▌    | 719/1305 [05:58<04:13,  2.31it/s]




 55%|█████▌    | 720/1305 [05:59<04:06,  2.37it/s]




 55%|█████▌    | 721/1305 [05:59<04:11,  2.32it/s]




 55%|█████▌    | 722/1305 [06:01<07:10,  1.35it/s]




 55%|█████▌    | 724/1305 [06:01<05:19,  1.82it/s]




 56%|█████▌    | 725/1305 [06:02<04:38,  2.09it/s]




 56%|█████▌    | 727/1305 [06:02<04:24,  2.19it/s]




 56%|█████▌    | 728/1305 [06:03<03:58,  2.42it/s]




 56%|█████▌    | 729/1305 [06:03<04:26,  2.17it/s]




 56%|█████▌    | 730/1305 [06:05<06:21,  1.51it/s]




 56%|█████▌    | 732/1305 [06:05<05:19,  1.79it/s]




 56%|█████▌    | 733/1305 [06:06<04:39,  2.05it/s]




 56%|█████▋    | 735/1305 [06:06<03:53,  2.44it/s]




 56%|█████▋    | 736/1305 [06:07<03:57,  2.40it/s]




 56%|█████▋    | 737/1305 [06:08<05:18,  1.78it/s]




 57%|█████▋    | 738/1305 [06:09<06:20,  1.49it/s]




 57%|█████▋    | 739/1305 [06:09<04:53,  1.93it/s]




 57%|█████▋    | 740/1305 [06:10<06:00,  1.57it/s]




 57%|█████▋    | 741/1305 [06:10<04:54,  1.91it/s]




 57%|█████▋    | 742/1305 [06:10<03:45,  2.49it/s]




 57%|█████▋    | 744/1305 [06:11<03:10,  2.95it/s]




 57%|█████▋    | 745/1305 [06:12<04:58,  1.88it/s]




 57%|█████▋    | 746/1305 [06:13<05:50,  1.59it/s]




 57%|█████▋    | 747/1305 [06:13<04:48,  1.94it/s]




 57%|█████▋    | 748/1305 [06:14<05:29,  1.69it/s]




 57%|█████▋    | 749/1305 [06:14<04:35,  2.02it/s]




 58%|█████▊    | 751/1305 [06:14<02:55,  3.16it/s]




 58%|█████▊    | 752/1305 [06:15<03:23,  2.72it/s]




 58%|█████▊    | 753/1305 [06:16<04:52,  1.89it/s]




 58%|█████▊    | 754/1305 [06:17<06:28,  1.42it/s]




 58%|█████▊    | 755/1305 [06:17<05:32,  1.65it/s]




 58%|█████▊    | 756/1305 [06:17<04:56,  1.85it/s]




 58%|█████▊    | 757/1305 [06:18<04:32,  2.01it/s]




 58%|█████▊    | 758/1305 [06:18<03:41,  2.46it/s]




 58%|█████▊    | 759/1305 [06:18<03:21,  2.70it/s]




 58%|█████▊    | 760/1305 [06:19<03:28,  2.61it/s]




 58%|█████▊    | 761/1305 [06:20<04:56,  1.83it/s]




 58%|█████▊    | 762/1305 [06:21<06:23,  1.42it/s]




 58%|█████▊    | 763/1305 [06:21<06:21,  1.42it/s]




 59%|█████▊    | 765/1305 [06:22<04:07,  2.18it/s]




 59%|█████▊    | 766/1305 [06:22<04:33,  1.97it/s]




 59%|█████▉    | 768/1305 [06:23<03:12,  2.79it/s]




 59%|█████▉    | 769/1305 [06:24<04:41,  1.91it/s]




 59%|█████▉    | 770/1305 [06:25<05:21,  1.67it/s]




 59%|█████▉    | 771/1305 [06:25<05:28,  1.62it/s]




 59%|█████▉    | 772/1305 [06:26<04:32,  1.96it/s]




 59%|█████▉    | 774/1305 [06:27<04:25,  2.00it/s]




 59%|█████▉    | 776/1305 [06:27<03:14,  2.73it/s]




 60%|█████▉    | 777/1305 [06:28<04:28,  1.97it/s]




 60%|█████▉    | 778/1305 [06:29<05:00,  1.75it/s]




 60%|█████▉    | 779/1305 [06:29<04:52,  1.80it/s]




 60%|█████▉    | 780/1305 [06:29<04:12,  2.08it/s]




 60%|█████▉    | 781/1305 [06:30<03:21,  2.60it/s]




 60%|█████▉    | 782/1305 [06:30<04:24,  1.98it/s]




 60%|██████    | 784/1305 [06:31<02:58,  2.93it/s]




 60%|██████    | 785/1305 [06:32<04:30,  1.93it/s]




 60%|██████    | 786/1305 [06:33<05:11,  1.67it/s]




 60%|██████    | 787/1305 [06:33<04:56,  1.75it/s]




 60%|██████    | 788/1305 [06:33<04:34,  1.88it/s]




 60%|██████    | 789/1305 [06:34<03:39,  2.35it/s]




 61%|██████    | 790/1305 [06:34<04:29,  1.91it/s]

 61%|██████    | 791/1305 [06:35<03:38,  2.36it/s]




 61%|██████    | 792/1305 [06:35<02:53,  2.96it/s]




 61%|██████    | 793/1305 [06:36<06:19,  1.35it/s]




 61%|██████    | 795/1305 [06:37<04:38,  1.83it/s]




 61%|██████    | 796/1305 [06:38<04:49,  1.76it/s]




 61%|██████    | 797/1305 [06:38<04:00,  2.11it/s]




 61%|██████    | 798/1305 [06:38<03:52,  2.18it/s]




 61%|██████    | 799/1305 [06:39<03:40,  2.29it/s]




 61%|██████▏   | 800/1305 [06:39<03:20,  2.52it/s]




 61%|██████▏   | 801/1305 [06:40<05:26,  1.54it/s]




 61%|██████▏   | 802/1305 [06:41<04:36,  1.82it/s]




 62%|██████▏   | 803/1305 [06:41<04:29,  1.86it/s]




 62%|██████▏   | 804/1305 [06:42<04:37,  1.80it/s]




 62%|██████▏   | 806/1305 [06:43<04:07,  2.02it/s]




 62%|██████▏   | 808/1305 [06:43<03:36,  2.30it/s]




 62%|██████▏   | 809/1305 [06:44<04:36,  1.79it/s]




 62%|██████▏   | 810/1305 [06:45<04:21,  1.89it/s]




 62%|██████▏   | 811/1305 [06:45<03:54,  2.11it/s]




 62%|██████▏   | 812/1305 [06:45<03:57,  2.07it/s]




 62%|██████▏   | 813/1305 [06:46<03:10,  2.58it/s]




 62%|██████▏   | 814/1305 [06:46<04:09,  1.97it/s]




 63%|██████▎   | 816/1305 [06:47<03:35,  2.27it/s]




 63%|██████▎   | 817/1305 [06:48<04:36,  1.77it/s]




 63%|██████▎   | 818/1305 [06:49<04:45,  1.71it/s]




 63%|██████▎   | 820/1305 [06:50<04:18,  1.88it/s]




 63%|██████▎   | 822/1305 [06:50<03:28,  2.31it/s]




 63%|██████▎   | 823/1305 [06:50<03:08,  2.56it/s]




 63%|██████▎   | 824/1305 [06:52<04:42,  1.70it/s]




 63%|██████▎   | 825/1305 [06:52<04:50,  1.65it/s]




 63%|██████▎   | 826/1305 [06:52<03:56,  2.03it/s]




 63%|██████▎   | 827/1305 [06:53<03:38,  2.18it/s]




 63%|██████▎   | 828/1305 [06:54<04:07,  1.92it/s]




 64%|██████▎   | 829/1305 [06:54<03:24,  2.33it/s]




 64%|██████▎   | 830/1305 [06:54<03:58,  1.99it/s]




 64%|██████▎   | 831/1305 [06:55<03:13,  2.45it/s]




 64%|██████▍   | 832/1305 [06:56<05:17,  1.49it/s]




 64%|██████▍   | 833/1305 [06:56<04:29,  1.75it/s]




 64%|██████▍   | 834/1305 [06:57<04:10,  1.88it/s]




 64%|██████▍   | 836/1305 [06:57<03:37,  2.15it/s]




 64%|██████▍   | 837/1305 [06:58<03:10,  2.46it/s]




 64%|██████▍   | 838/1305 [06:58<03:39,  2.13it/s]




 64%|██████▍   | 839/1305 [06:58<02:59,  2.59it/s]




 64%|██████▍   | 840/1305 [07:00<04:55,  1.57it/s]




 64%|██████▍   | 841/1305 [07:00<04:11,  1.85it/s]




 65%|██████▍   | 842/1305 [07:00<03:52,  1.99it/s]




 65%|██████▍   | 843/1305 [07:01<02:59,  2.57it/s]




 65%|██████▍   | 844/1305 [07:01<03:55,  1.96it/s]




 65%|██████▍   | 846/1305 [07:02<03:30,  2.18it/s]




 65%|██████▍   | 847/1305 [07:02<02:59,  2.55it/s]




 65%|██████▍   | 848/1305 [07:04<04:39,  1.64it/s]




 65%|██████▌   | 849/1305 [07:04<03:55,  1.94it/s]




 65%|██████▌   | 850/1305 [07:04<03:44,  2.02it/s]




 65%|██████▌   | 851/1305 [07:04<02:53,  2.62it/s]




 65%|██████▌   | 852/1305 [07:05<04:08,  1.82it/s]




 65%|██████▌   | 853/1305 [07:05<03:09,  2.39it/s]




 65%|██████▌   | 854/1305 [07:06<03:33,  2.11it/s]




 66%|██████▌   | 855/1305 [07:07<04:47,  1.56it/s]




 66%|██████▌   | 856/1305 [07:08<04:34,  1.63it/s]




 66%|██████▌   | 857/1305 [07:08<03:36,  2.07it/s]




 66%|██████▌   | 858/1305 [07:08<03:08,  2.38it/s]




 66%|██████▌   | 859/1305 [07:09<04:11,  1.77it/s]




 66%|██████▌   | 860/1305 [07:09<03:47,  1.96it/s]




 66%|██████▌   | 861/1305 [07:10<04:27,  1.66it/s]




 66%|██████▌   | 862/1305 [07:11<03:45,  1.96it/s]




 66%|██████▌   | 863/1305 [07:11<04:09,  1.77it/s]




 66%|██████▌   | 864/1305 [07:11<03:29,  2.10it/s]




 66%|██████▋   | 865/1305 [07:12<02:49,  2.60it/s]




 66%|██████▋   | 866/1305 [07:12<02:55,  2.50it/s]




 66%|██████▋   | 867/1305 [07:13<04:30,  1.62it/s]




 67%|██████▋   | 868/1305 [07:14<03:52,  1.88it/s]




 67%|██████▋   | 869/1305 [07:14<04:22,  1.66it/s]




 67%|██████▋   | 870/1305 [07:14<03:29,  2.08it/s]




 67%|██████▋   | 871/1305 [07:15<03:49,  1.89it/s]




 67%|██████▋   | 872/1305 [07:16<03:31,  2.05it/s]




 67%|██████▋   | 873/1305 [07:16<02:49,  2.54it/s]




 67%|██████▋   | 874/1305 [07:16<02:49,  2.54it/s]




 67%|██████▋   | 875/1305 [07:17<04:00,  1.79it/s]




 67%|██████▋   | 876/1305 [07:17<03:21,  2.13it/s]




 67%|██████▋   | 877/1305 [07:18<04:26,  1.61it/s]




 67%|██████▋   | 878/1305 [07:18<03:25,  2.08it/s]




 67%|██████▋   | 879/1305 [07:19<03:37,  1.95it/s]




 67%|██████▋   | 880/1305 [07:20<03:36,  1.96it/s]




 68%|██████▊   | 882/1305 [07:20<02:51,  2.47it/s]




 68%|██████▊   | 883/1305 [07:21<03:48,  1.85it/s]




 68%|██████▊   | 885/1305 [07:22<03:54,  1.79it/s]




 68%|██████▊   | 886/1305 [07:22<03:10,  2.20it/s]




 68%|██████▊   | 887/1305 [07:23<03:42,  1.88it/s]




 68%|██████▊   | 888/1305 [07:23<03:11,  2.18it/s]




 68%|██████▊   | 889/1305 [07:24<02:57,  2.35it/s]




 68%|██████▊   | 890/1305 [07:24<02:49,  2.45it/s]




 68%|██████▊   | 891/1305 [07:25<03:51,  1.79it/s]




 68%|██████▊   | 893/1305 [07:26<03:59,  1.72it/s]




 69%|██████▊   | 894/1305 [07:27<03:39,  1.87it/s]




 69%|██████▊   | 895/1305 [07:27<03:34,  1.91it/s]




 69%|██████▊   | 896/1305 [07:27<03:05,  2.20it/s]




 69%|██████▊   | 897/1305 [07:28<02:44,  2.48it/s]




 69%|██████▉   | 898/1305 [07:28<02:52,  2.36it/s]




 69%|██████▉   | 899/1305 [07:29<04:10,  1.62it/s]




 69%|██████▉   | 900/1305 [07:29<03:13,  2.10it/s]




 69%|██████▉   | 901/1305 [07:30<03:37,  1.86it/s]




 69%|██████▉   | 902/1305 [07:31<03:41,  1.82it/s]




 69%|██████▉   | 903/1305 [07:31<03:25,  1.96it/s]




 69%|██████▉   | 904/1305 [07:31<03:24,  1.96it/s]




 69%|██████▉   | 905/1305 [07:32<03:00,  2.22it/s]




 69%|██████▉   | 906/1305 [07:32<02:57,  2.25it/s]




 70%|██████▉   | 907/1305 [07:33<04:09,  1.60it/s]




 70%|██████▉   | 909/1305 [07:34<03:19,  1.98it/s]




 70%|██████▉   | 910/1305 [07:34<03:17,  2.00it/s]




 70%|██████▉   | 911/1305 [07:35<03:30,  1.87it/s]




 70%|██████▉   | 912/1305 [07:35<02:55,  2.24it/s]




 70%|██████▉   | 913/1305 [07:36<03:06,  2.11it/s]




 70%|███████   | 914/1305 [07:36<02:35,  2.52it/s]




 70%|███████   | 915/1305 [07:37<03:31,  1.84it/s]




 70%|███████   | 916/1305 [07:37<02:52,  2.26it/s]




 70%|███████   | 917/1305 [07:38<03:11,  2.02it/s]




 70%|███████   | 918/1305 [07:39<03:47,  1.70it/s]




 70%|███████   | 919/1305 [07:39<04:09,  1.55it/s]

 70%|███████   | 920/1305 [07:40<03:48,  1.68it/s]




 71%|███████   | 921/1305 [07:40<02:59,  2.14it/s]




 71%|███████   | 923/1305 [07:41<02:44,  2.32it/s]




 71%|███████   | 924/1305 [07:42<03:13,  1.97it/s]




 71%|███████   | 925/1305 [07:42<03:30,  1.81it/s]




 71%|███████   | 926/1305 [07:43<03:20,  1.89it/s]




 71%|███████   | 927/1305 [07:43<03:14,  1.95it/s]




 71%|███████   | 928/1305 [07:44<03:27,  1.82it/s]




 71%|███████   | 929/1305 [07:44<02:47,  2.24it/s]




 71%|███████▏  | 930/1305 [07:44<02:16,  2.75it/s]




 71%|███████▏  | 931/1305 [07:45<02:52,  2.17it/s]




 71%|███████▏  | 932/1305 [07:46<03:11,  1.95it/s]




 71%|███████▏  | 933/1305 [07:46<03:23,  1.83it/s]




 72%|███████▏  | 934/1305 [07:47<03:32,  1.75it/s]




 72%|███████▏  | 935/1305 [07:47<03:14,  1.90it/s]




 72%|███████▏  | 936/1305 [07:48<03:19,  1.85it/s]




 72%|███████▏  | 938/1305 [07:48<02:15,  2.71it/s]




 72%|███████▏  | 939/1305 [07:49<02:30,  2.44it/s]




 72%|███████▏  | 940/1305 [07:49<02:58,  2.05it/s]




 72%|███████▏  | 941/1305 [07:50<03:08,  1.93it/s]




 72%|███████▏  | 942/1305 [07:51<03:28,  1.74it/s]




 72%|███████▏  | 943/1305 [07:51<03:06,  1.94it/s]




 72%|███████▏  | 944/1305 [07:52<03:03,  1.96it/s]




 72%|███████▏  | 945/1305 [07:52<02:41,  2.23it/s]




 72%|███████▏  | 946/1305 [07:52<02:09,  2.78it/s]




 73%|███████▎  | 947/1305 [07:52<02:14,  2.66it/s]




 73%|███████▎  | 948/1305 [07:53<03:02,  1.96it/s]




 73%|███████▎  | 949/1305 [07:54<03:17,  1.80it/s]




 73%|███████▎  | 950/1305 [07:55<04:38,  1.28it/s]




 73%|███████▎  | 951/1305 [07:55<03:33,  1.66it/s]




 73%|███████▎  | 953/1305 [07:56<02:34,  2.28it/s]




 73%|███████▎  | 954/1305 [07:56<02:15,  2.58it/s]




 73%|███████▎  | 955/1305 [07:56<02:13,  2.62it/s]




 73%|███████▎  | 956/1305 [07:57<02:33,  2.27it/s]




 73%|███████▎  | 957/1305 [07:58<03:13,  1.80it/s]




 73%|███████▎  | 958/1305 [07:59<04:40,  1.24it/s]




 74%|███████▎  | 960/1305 [08:00<02:45,  2.09it/s]




 74%|███████▎  | 961/1305 [08:00<02:21,  2.43it/s]




 74%|███████▎  | 962/1305 [08:00<02:33,  2.23it/s]




 74%|███████▍  | 963/1305 [08:00<02:13,  2.56it/s]




 74%|███████▍  | 964/1305 [08:01<02:40,  2.12it/s]




 74%|███████▍  | 965/1305 [08:02<03:20,  1.70it/s]




 74%|███████▍  | 966/1305 [08:03<04:09,  1.36it/s]




 74%|███████▍  | 967/1305 [08:03<03:16,  1.72it/s]




 74%|███████▍  | 968/1305 [08:03<02:29,  2.25it/s]




 74%|███████▍  | 969/1305 [08:04<02:02,  2.73it/s]




 74%|███████▍  | 970/1305 [08:04<01:54,  2.92it/s]




 74%|███████▍  | 971/1305 [08:04<01:57,  2.85it/s]




 74%|███████▍  | 972/1305 [08:05<02:36,  2.13it/s]




 75%|███████▍  | 973/1305 [08:06<03:30,  1.58it/s]




 75%|███████▍  | 974/1305 [08:07<04:03,  1.36it/s]




 75%|███████▍  | 975/1305 [08:07<03:29,  1.57it/s]




 75%|███████▍  | 977/1305 [08:08<02:05,  2.61it/s]




 75%|███████▍  | 978/1305 [08:08<01:49,  2.99it/s]




 75%|███████▌  | 979/1305 [08:08<02:10,  2.50it/s]




 75%|███████▌  | 980/1305 [08:09<02:36,  2.08it/s]




 75%|███████▌  | 981/1305 [08:10<03:15,  1.66it/s]




 75%|███████▌  | 982/1305 [08:11<03:57,  1.36it/s]




 75%|███████▌  | 983/1305 [08:11<03:07,  1.72it/s]




 75%|███████▌  | 984/1305 [08:11<02:30,  2.13it/s]




 75%|███████▌  | 985/1305 [08:12<01:57,  2.72it/s]




 76%|███████▌  | 986/1305 [08:12<01:33,  3.40it/s]




 76%|███████▌  | 987/1305 [08:13<02:18,  2.29it/s]




 76%|███████▌  | 988/1305 [08:13<02:38,  2.00it/s]




 76%|███████▌  | 989/1305 [08:14<03:20,  1.58it/s]




 76%|███████▌  | 990/1305 [08:15<03:58,  1.32it/s]




 76%|███████▌  | 991/1305 [08:15<03:04,  1.70it/s]




 76%|███████▌  | 993/1305 [08:16<02:07,  2.44it/s]




 76%|███████▌  | 995/1305 [08:17<02:20,  2.21it/s]




 76%|███████▋  | 996/1305 [08:17<02:27,  2.10it/s]




 76%|███████▋  | 997/1305 [08:18<02:44,  1.88it/s]




 76%|███████▋  | 998/1305 [08:19<03:26,  1.49it/s]




 77%|███████▋  | 999/1305 [08:19<02:42,  1.89it/s]




 77%|███████▋  | 1000/1305 [08:19<02:07,  2.39it/s]




 77%|███████▋  | 1001/1305 [08:20<01:57,  2.58it/s]




 77%|███████▋  | 1002/1305 [08:20<01:39,  3.04it/s]




 77%|███████▋  | 1003/1305 [08:21<02:32,  1.97it/s]




 77%|███████▋  | 1004/1305 [08:21<02:18,  2.17it/s]




 77%|███████▋  | 1005/1305 [08:22<02:53,  1.73it/s]




 77%|███████▋  | 1006/1305 [08:23<03:25,  1.46it/s]




 77%|███████▋  | 1007/1305 [08:23<02:38,  1.88it/s]




 77%|███████▋  | 1008/1305 [08:24<02:25,  2.05it/s]




 77%|███████▋  | 1010/1305 [08:24<01:59,  2.48it/s]




 77%|███████▋  | 1011/1305 [08:25<02:15,  2.18it/s]




 78%|███████▊  | 1012/1305 [08:25<02:00,  2.44it/s]




 78%|███████▊  | 1013/1305 [08:26<02:36,  1.87it/s]




 78%|███████▊  | 1014/1305 [08:27<03:47,  1.28it/s]




 78%|███████▊  | 1016/1305 [08:28<02:20,  2.06it/s]




 78%|███████▊  | 1018/1305 [08:29<02:27,  1.95it/s]




 78%|███████▊  | 1019/1305 [08:29<02:05,  2.29it/s]




 78%|███████▊  | 1020/1305 [08:29<02:11,  2.17it/s]




 78%|███████▊  | 1021/1305 [08:30<02:51,  1.65it/s]




 78%|███████▊  | 1022/1305 [08:31<02:59,  1.58it/s]




 78%|███████▊  | 1023/1305 [08:31<02:25,  1.93it/s]




 78%|███████▊  | 1024/1305 [08:31<01:54,  2.46it/s]




 79%|███████▊  | 1026/1305 [08:33<02:15,  2.06it/s]




 79%|███████▊  | 1027/1305 [08:33<02:10,  2.13it/s]




 79%|███████▉  | 1028/1305 [08:33<02:05,  2.20it/s]




 79%|███████▉  | 1029/1305 [08:34<02:33,  1.80it/s]




 79%|███████▉  | 1030/1305 [08:35<03:00,  1.52it/s]




 79%|███████▉  | 1032/1305 [08:35<01:51,  2.44it/s]




 79%|███████▉  | 1033/1305 [08:36<01:32,  2.93it/s]




 79%|███████▉  | 1034/1305 [08:37<02:26,  1.85it/s]




 79%|███████▉  | 1035/1305 [08:37<02:11,  2.06it/s]




 79%|███████▉  | 1036/1305 [08:37<02:04,  2.16it/s]




 79%|███████▉  | 1037/1305 [08:38<02:20,  1.91it/s]




 80%|███████▉  | 1038/1305 [08:39<02:52,  1.55it/s]




 80%|███████▉  | 1040/1305 [08:39<01:51,  2.39it/s]




 80%|███████▉  | 1042/1305 [08:41<02:15,  1.94it/s]




 80%|███████▉  | 1043/1305 [08:41<02:02,  2.14it/s]




 80%|████████  | 1044/1305 [08:41<01:51,  2.35it/s]




 80%|████████  | 1045/1305 [08:42<02:10,  1.99it/s]




 80%|████████  | 1046/1305 [08:43<02:53,  1.49it/s]




 80%|████████  | 1047/1305 [08:43<02:18,  1.86it/s]




 80%|████████  | 1049/1305 [08:44<01:32,  2.77it/s]




 80%|████████  | 1050/1305 [08:45<02:55,  1.46it/s]

 81%|████████  | 1052/1305 [08:46<01:56,  2.18it/s]




 81%|████████  | 1053/1305 [08:46<01:57,  2.15it/s]




 81%|████████  | 1054/1305 [08:47<02:36,  1.60it/s]




 81%|████████  | 1056/1305 [08:47<01:51,  2.24it/s]




 81%|████████  | 1057/1305 [08:48<01:44,  2.37it/s]




 81%|████████  | 1058/1305 [08:49<02:40,  1.54it/s]




 81%|████████  | 1059/1305 [08:50<02:21,  1.74it/s]




 81%|████████▏ | 1061/1305 [08:50<01:45,  2.31it/s]




 81%|████████▏ | 1062/1305 [08:51<02:09,  1.87it/s]




 81%|████████▏ | 1063/1305 [08:51<01:53,  2.14it/s]




 82%|████████▏ | 1064/1305 [08:52<01:45,  2.28it/s]




 82%|████████▏ | 1065/1305 [08:52<01:33,  2.56it/s]




 82%|████████▏ | 1066/1305 [08:53<02:36,  1.53it/s]




 82%|████████▏ | 1067/1305 [08:53<02:11,  1.81it/s]




 82%|████████▏ | 1069/1305 [08:54<01:36,  2.44it/s]




 82%|████████▏ | 1070/1305 [08:55<01:58,  1.98it/s]




 82%|████████▏ | 1071/1305 [08:55<01:45,  2.21it/s]




 82%|████████▏ | 1072/1305 [08:55<01:38,  2.38it/s]




 82%|████████▏ | 1073/1305 [08:56<01:29,  2.59it/s]




 82%|████████▏ | 1074/1305 [08:57<02:40,  1.44it/s]




 82%|████████▏ | 1075/1305 [08:57<02:17,  1.67it/s]




 83%|████████▎ | 1077/1305 [08:58<01:29,  2.54it/s]




 83%|████████▎ | 1078/1305 [08:58<01:45,  2.16it/s]




 83%|████████▎ | 1079/1305 [08:59<01:56,  1.94it/s]




 83%|████████▎ | 1080/1305 [08:59<01:46,  2.10it/s]




 83%|████████▎ | 1081/1305 [09:00<01:23,  2.69it/s]




 83%|████████▎ | 1082/1305 [09:01<02:31,  1.48it/s]




 83%|████████▎ | 1083/1305 [09:01<02:05,  1.77it/s]




 83%|████████▎ | 1084/1305 [09:01<01:36,  2.29it/s]




 83%|████████▎ | 1085/1305 [09:02<01:40,  2.18it/s]




 83%|████████▎ | 1086/1305 [09:03<01:53,  1.93it/s]




 83%|████████▎ | 1087/1305 [09:03<02:04,  1.76it/s]




 83%|████████▎ | 1089/1305 [09:03<01:17,  2.78it/s]




 84%|████████▎ | 1090/1305 [09:05<02:22,  1.51it/s]




 84%|████████▎ | 1092/1305 [09:05<01:38,  2.17it/s]




 84%|████████▍ | 1093/1305 [09:06<01:49,  1.94it/s]




 84%|████████▍ | 1094/1305 [09:06<01:40,  2.09it/s]




 84%|████████▍ | 1095/1305 [09:07<01:45,  2.00it/s]




 84%|████████▍ | 1096/1305 [09:07<01:30,  2.31it/s]




 84%|████████▍ | 1097/1305 [09:08<01:31,  2.26it/s]




 84%|████████▍ | 1098/1305 [09:09<02:15,  1.52it/s]




 84%|████████▍ | 1099/1305 [09:09<02:00,  1.70it/s]




 84%|████████▍ | 1100/1305 [09:10<01:41,  2.03it/s]




 84%|████████▍ | 1101/1305 [09:10<01:45,  1.93it/s]




 85%|████████▍ | 1103/1305 [09:11<01:26,  2.34it/s]




 85%|████████▍ | 1104/1305 [09:11<01:17,  2.60it/s]




 85%|████████▍ | 1105/1305 [09:12<01:33,  2.14it/s]




 85%|████████▍ | 1106/1305 [09:13<02:26,  1.36it/s]




 85%|████████▍ | 1107/1305 [09:13<01:51,  1.77it/s]




 85%|████████▍ | 1108/1305 [09:14<01:27,  2.25it/s]




 85%|████████▍ | 1109/1305 [09:14<01:32,  2.11it/s]




 85%|████████▌ | 1110/1305 [09:14<01:22,  2.36it/s]




 85%|████████▌ | 1111/1305 [09:15<01:14,  2.60it/s]




 85%|████████▌ | 1112/1305 [09:15<01:25,  2.26it/s]




 85%|████████▌ | 1113/1305 [09:16<01:29,  2.14it/s]




 85%|████████▌ | 1114/1305 [09:17<02:39,  1.20it/s]




 85%|████████▌ | 1115/1305 [09:18<01:59,  1.59it/s]




 86%|████████▌ | 1117/1305 [09:18<01:18,  2.38it/s]




 86%|████████▌ | 1118/1305 [09:18<01:10,  2.66it/s]




 86%|████████▌ | 1119/1305 [09:19<01:04,  2.89it/s]




 86%|████████▌ | 1120/1305 [09:19<01:35,  1.94it/s]




 86%|████████▌ | 1121/1305 [09:20<01:29,  2.05it/s]




 86%|████████▌ | 1122/1305 [09:21<02:26,  1.25it/s]




 86%|████████▌ | 1123/1305 [09:22<01:49,  1.67it/s]




 86%|████████▌ | 1124/1305 [09:22<01:27,  2.08it/s]




 86%|████████▌ | 1125/1305 [09:22<01:09,  2.60it/s]




 86%|████████▋ | 1127/1305 [09:22<00:57,  3.09it/s]




 86%|████████▋ | 1128/1305 [09:23<01:26,  2.03it/s]




 87%|████████▋ | 1129/1305 [09:24<01:25,  2.06it/s]




 87%|████████▋ | 1130/1305 [09:25<02:16,  1.29it/s]




 87%|████████▋ | 1131/1305 [09:26<01:42,  1.70it/s]




 87%|████████▋ | 1132/1305 [09:26<01:23,  2.08it/s]




 87%|████████▋ | 1133/1305 [09:26<01:05,  2.63it/s]




 87%|████████▋ | 1134/1305 [09:26<00:59,  2.88it/s]




 87%|████████▋ | 1135/1305 [09:27<00:58,  2.89it/s]




 87%|████████▋ | 1136/1305 [09:27<01:27,  1.94it/s]




 87%|████████▋ | 1137/1305 [09:28<01:24,  1.99it/s]




 87%|████████▋ | 1138/1305 [09:29<02:17,  1.21it/s]




 87%|████████▋ | 1139/1305 [09:30<01:42,  1.61it/s]




 87%|████████▋ | 1140/1305 [09:30<01:23,  1.97it/s]




 87%|████████▋ | 1141/1305 [09:30<01:05,  2.51it/s]




 88%|████████▊ | 1142/1305 [09:30<01:01,  2.66it/s]




 88%|████████▊ | 1143/1305 [09:31<01:12,  2.24it/s]




 88%|████████▊ | 1144/1305 [09:31<01:04,  2.51it/s]




 88%|████████▊ | 1145/1305 [09:32<01:19,  2.02it/s]




 88%|████████▊ | 1146/1305 [09:33<02:04,  1.28it/s]




 88%|████████▊ | 1147/1305 [09:34<01:42,  1.55it/s]




 88%|████████▊ | 1148/1305 [09:34<01:26,  1.82it/s]




 88%|████████▊ | 1149/1305 [09:34<01:07,  2.32it/s]




 88%|████████▊ | 1150/1305 [09:34<00:56,  2.76it/s]




 88%|████████▊ | 1151/1305 [09:35<01:10,  2.18it/s]




 88%|████████▊ | 1152/1305 [09:36<01:10,  2.17it/s]




 88%|████████▊ | 1153/1305 [09:36<00:56,  2.67it/s]




 88%|████████▊ | 1154/1305 [09:37<01:53,  1.33it/s]




 89%|████████▊ | 1155/1305 [09:38<01:35,  1.57it/s]




 89%|████████▊ | 1156/1305 [09:38<01:23,  1.78it/s]




 89%|████████▊ | 1158/1305 [09:39<00:58,  2.52it/s]




 89%|████████▉ | 1159/1305 [09:39<01:02,  2.33it/s]




 89%|████████▉ | 1160/1305 [09:39<00:58,  2.48it/s]




 89%|████████▉ | 1161/1305 [09:40<00:52,  2.73it/s]




 89%|████████▉ | 1162/1305 [09:41<01:41,  1.41it/s]




 89%|████████▉ | 1163/1305 [09:42<01:32,  1.53it/s]




 89%|████████▉ | 1164/1305 [09:42<01:11,  1.97it/s]




 89%|████████▉ | 1165/1305 [09:42<01:01,  2.26it/s]




 89%|████████▉ | 1166/1305 [09:43<00:55,  2.51it/s]




 89%|████████▉ | 1167/1305 [09:43<00:55,  2.51it/s]




 90%|████████▉ | 1168/1305 [09:44<01:03,  2.16it/s]




 90%|████████▉ | 1169/1305 [09:44<00:59,  2.29it/s]




 90%|████████▉ | 1170/1305 [09:45<01:36,  1.39it/s]




 90%|████████▉ | 1171/1305 [09:46<01:22,  1.62it/s]




 90%|████████▉ | 1172/1305 [09:46<01:12,  1.83it/s]




 90%|████████▉ | 1173/1305 [09:46<00:54,  2.42it/s]




 90%|████████▉ | 1174/1305 [09:47<00:56,  2.32it/s]




 90%|█████████ | 1175/1305 [09:47<00:59,  2.19it/s]




 90%|█████████ | 1176/1305 [09:48<01:05,  1.97it/s]

 90%|█████████ | 1177/1305 [09:48<01:06,  1.93it/s]




 90%|█████████ | 1178/1305 [09:49<01:20,  1.59it/s]




 90%|█████████ | 1179/1305 [09:50<01:08,  1.85it/s]




 90%|█████████ | 1180/1305 [09:50<01:21,  1.54it/s]




 91%|█████████ | 1182/1305 [09:51<00:47,  2.57it/s]




 91%|█████████ | 1183/1305 [09:51<00:47,  2.57it/s]




 91%|█████████ | 1184/1305 [09:52<00:57,  2.09it/s]




 91%|█████████ | 1185/1305 [09:53<01:12,  1.66it/s]




 91%|█████████ | 1186/1305 [09:53<01:11,  1.66it/s]




 91%|█████████ | 1187/1305 [09:53<00:54,  2.16it/s]




 91%|█████████ | 1188/1305 [09:54<01:10,  1.67it/s]




 91%|█████████ | 1189/1305 [09:55<00:58,  1.98it/s]




 91%|█████████▏| 1191/1305 [09:55<00:38,  2.95it/s]




 91%|█████████▏| 1192/1305 [09:56<00:50,  2.22it/s]




 91%|█████████▏| 1193/1305 [09:56<01:01,  1.81it/s]




 91%|█████████▏| 1194/1305 [09:57<01:04,  1.73it/s]




 92%|█████████▏| 1196/1305 [09:58<00:59,  1.84it/s]




 92%|█████████▏| 1197/1305 [09:58<00:51,  2.11it/s]




 92%|█████████▏| 1199/1305 [09:59<00:35,  3.01it/s]




 92%|█████████▏| 1200/1305 [09:59<00:46,  2.26it/s]




 92%|█████████▏| 1201/1305 [10:00<00:57,  1.82it/s]




 92%|█████████▏| 1202/1305 [10:01<01:01,  1.68it/s]




 92%|█████████▏| 1203/1305 [10:01<00:48,  2.08it/s]




 92%|█████████▏| 1204/1305 [10:02<00:58,  1.74it/s]




 92%|█████████▏| 1205/1305 [10:02<00:48,  2.05it/s]




 92%|█████████▏| 1206/1305 [10:02<00:38,  2.58it/s]




 92%|█████████▏| 1207/1305 [10:03<00:42,  2.29it/s]




 93%|█████████▎| 1208/1305 [10:03<00:42,  2.27it/s]




 93%|█████████▎| 1209/1305 [10:04<00:58,  1.65it/s]




 93%|█████████▎| 1210/1305 [10:05<01:09,  1.37it/s]




 93%|█████████▎| 1211/1305 [10:06<00:52,  1.79it/s]




 93%|█████████▎| 1212/1305 [10:06<00:46,  2.01it/s]




 93%|█████████▎| 1213/1305 [10:06<00:42,  2.16it/s]




 93%|█████████▎| 1215/1305 [10:07<00:43,  2.08it/s]




 93%|█████████▎| 1217/1305 [10:08<00:44,  1.96it/s]




 93%|█████████▎| 1218/1305 [10:10<01:00,  1.44it/s]




 94%|█████████▎| 1221/1305 [10:10<00:36,  2.27it/s]




 94%|█████████▎| 1223/1305 [10:11<00:38,  2.15it/s]




 94%|█████████▍| 1225/1305 [10:12<00:37,  2.15it/s]




 94%|█████████▍| 1226/1305 [10:14<00:49,  1.60it/s]




 94%|█████████▍| 1228/1305 [10:14<00:33,  2.32it/s]




 94%|█████████▍| 1229/1305 [10:14<00:31,  2.39it/s]




 94%|█████████▍| 1230/1305 [10:14<00:27,  2.72it/s]




 94%|█████████▍| 1231/1305 [10:15<00:35,  2.09it/s]




 94%|█████████▍| 1232/1305 [10:15<00:27,  2.61it/s]




 94%|█████████▍| 1233/1305 [10:16<00:37,  1.91it/s]




 95%|█████████▍| 1234/1305 [10:17<00:51,  1.37it/s]




 95%|█████████▍| 1235/1305 [10:18<00:39,  1.76it/s]




 95%|█████████▍| 1236/1305 [10:18<00:38,  1.80it/s]




 95%|█████████▍| 1238/1305 [10:18<00:22,  2.99it/s]




 95%|█████████▍| 1239/1305 [10:19<00:33,  1.96it/s]




 95%|█████████▌| 1240/1305 [10:20<00:29,  2.18it/s]




 95%|█████████▌| 1241/1305 [10:20<00:31,  2.02it/s]




 95%|█████████▌| 1242/1305 [10:21<00:42,  1.48it/s]




 95%|█████████▌| 1243/1305 [10:22<00:32,  1.92it/s]




 95%|█████████▌| 1244/1305 [10:22<00:36,  1.68it/s]




 95%|█████████▌| 1245/1305 [10:23<00:29,  2.01it/s]




 96%|█████████▌| 1247/1305 [10:23<00:26,  2.21it/s]




 96%|█████████▌| 1248/1305 [10:24<00:25,  2.21it/s]




 96%|█████████▌| 1249/1305 [10:24<00:27,  2.06it/s]




 96%|█████████▌| 1250/1305 [10:25<00:30,  1.82it/s]




 96%|█████████▌| 1251/1305 [10:25<00:25,  2.14it/s]




 96%|█████████▌| 1252/1305 [10:26<00:32,  1.65it/s]




 96%|█████████▌| 1253/1305 [10:26<00:24,  2.15it/s]




 96%|█████████▌| 1254/1305 [10:27<00:19,  2.64it/s]




 96%|█████████▌| 1255/1305 [10:27<00:22,  2.22it/s]




 96%|█████████▌| 1256/1305 [10:28<00:23,  2.08it/s]




 96%|█████████▋| 1257/1305 [10:28<00:23,  2.04it/s]




 96%|█████████▋| 1258/1305 [10:29<00:24,  1.88it/s]




 96%|█████████▋| 1259/1305 [10:29<00:24,  1.88it/s]




 97%|█████████▋| 1260/1305 [10:30<00:30,  1.48it/s]




 97%|█████████▋| 1261/1305 [10:31<00:22,  1.93it/s]




 97%|█████████▋| 1263/1305 [10:31<00:15,  2.63it/s]




 97%|█████████▋| 1264/1305 [10:32<00:17,  2.36it/s]




 97%|█████████▋| 1265/1305 [10:32<00:18,  2.21it/s]




 97%|█████████▋| 1266/1305 [10:33<00:18,  2.11it/s]




 97%|█████████▋| 1267/1305 [10:34<00:22,  1.67it/s]




 97%|█████████▋| 1268/1305 [10:34<00:24,  1.51it/s]




 97%|█████████▋| 1269/1305 [10:35<00:19,  1.89it/s]




 97%|█████████▋| 1271/1305 [10:35<00:15,  2.18it/s]




 97%|█████████▋| 1272/1305 [10:36<00:15,  2.14it/s]




 98%|█████████▊| 1273/1305 [10:36<00:15,  2.02it/s]




 98%|█████████▊| 1275/1305 [10:38<00:16,  1.82it/s]




 98%|█████████▊| 1276/1305 [10:39<00:19,  1.49it/s]




 98%|█████████▊| 1277/1305 [10:39<00:14,  1.89it/s]




 98%|█████████▊| 1279/1305 [10:39<00:09,  2.66it/s]




 98%|█████████▊| 1280/1305 [10:40<00:10,  2.32it/s]




 98%|█████████▊| 1281/1305 [10:40<00:11,  2.07it/s]




 98%|█████████▊| 1282/1305 [10:41<00:09,  2.39it/s]




 98%|█████████▊| 1283/1305 [10:42<00:13,  1.65it/s]




 98%|█████████▊| 1284/1305 [10:43<00:15,  1.35it/s]




 99%|█████████▊| 1286/1305 [10:43<00:08,  2.29it/s]




 99%|█████████▊| 1288/1305 [10:44<00:06,  2.46it/s]




 99%|█████████▉| 1289/1305 [10:44<00:07,  2.27it/s]




 99%|█████████▉| 1290/1305 [10:44<00:05,  2.54it/s]




 99%|█████████▉| 1291/1305 [10:46<00:08,  1.66it/s]




 99%|█████████▉| 1292/1305 [10:47<00:09,  1.43it/s]




 99%|█████████▉| 1295/1305 [10:47<00:03,  2.52it/s]




 99%|█████████▉| 1296/1305 [10:47<00:03,  2.47it/s]




 99%|█████████▉| 1297/1305 [10:48<00:03,  2.09it/s]




 99%|█████████▉| 1298/1305 [10:48<00:02,  2.41it/s]




100%|█████████▉| 1299/1305 [10:50<00:03,  1.70it/s]




100%|█████████▉| 1300/1305 [10:50<00:03,  1.48it/s]




100%|█████████▉| 1301/1305 [10:51<00:02,  1.71it/s]




100%|█████████▉| 1303/1305 [10:51<00:00,  2.80it/s]




100%|█████████▉| 1304/1305 [10:51<00:00,  2.80it/s]




100%|██████████| 1305/1305 [10:52<00:00,  2.00it/s]
Multiplets | family 4:   0%|          | 0/1305 [10:52<?, ?it/s]




Multiplets | family 5:   0%|          | 0/1616 [00:00<?, ?it/s]




  0%|          | 0/1616 [00:00<?, ?it/s]




  0%|          | 1/1616 [00:05<2:17:30,  5.11s/it]




  0%|          | 6/1616 [00:05<17:32,  1.53it/s]




  0%|          | 8/1616 [00:05<12:16,  2.18it/s]




  1%|          | 10/1616 [00:10<29:13,  1.09s/it]




  1%|          | 13/1616 [00:10<17:42,  1.51it/s]

  1%|          | 15/1616 [00:10<13:47,  1.93it/s]




  1%|          | 17/1616 [00:15<27:44,  1.04s/it]




  1%|          | 18/1616 [00:15<23:52,  1.12it/s]




  1%|▏         | 21/1616 [00:15<15:24,  1.73it/s]




  1%|▏         | 23/1616 [00:16<11:50,  2.24it/s]




  1%|▏         | 24/1616 [00:16<11:02,  2.40it/s]




  2%|▏         | 25/1616 [00:20<28:19,  1.07s/it]




  2%|▏         | 26/1616 [00:20<24:39,  1.07it/s]




  2%|▏         | 27/1616 [00:20<20:54,  1.27it/s]




  2%|▏         | 29/1616 [00:21<13:34,  1.95it/s]




  2%|▏         | 30/1616 [00:21<11:35,  2.28it/s]




  2%|▏         | 31/1616 [00:21<09:35,  2.75it/s]




  2%|▏         | 32/1616 [00:21<08:54,  2.97it/s]




  2%|▏         | 33/1616 [00:25<33:03,  1.25s/it]




  2%|▏         | 34/1616 [00:25<26:14,  1.00it/s]




  2%|▏         | 35/1616 [00:26<21:02,  1.25it/s]




  2%|▏         | 36/1616 [00:26<16:07,  1.63it/s]




  2%|▏         | 38/1616 [00:26<10:22,  2.53it/s]




  2%|▏         | 40/1616 [00:27<10:04,  2.61it/s]




  3%|▎         | 41/1616 [00:30<26:45,  1.02s/it]




  3%|▎         | 42/1616 [00:31<24:32,  1.07it/s]




  3%|▎         | 43/1616 [00:31<19:27,  1.35it/s]




  3%|▎         | 44/1616 [00:31<15:15,  1.72it/s]




  3%|▎         | 45/1616 [00:31<12:25,  2.11it/s]




  3%|▎         | 46/1616 [00:32<11:14,  2.33it/s]




  3%|▎         | 47/1616 [00:32<11:57,  2.19it/s]




  3%|▎         | 48/1616 [00:33<11:46,  2.22it/s]




  3%|▎         | 49/1616 [00:35<27:45,  1.06s/it]




  3%|▎         | 50/1616 [00:36<25:25,  1.03it/s]




  3%|▎         | 51/1616 [00:36<19:40,  1.33it/s]




  3%|▎         | 52/1616 [00:37<17:32,  1.49it/s]




  3%|▎         | 54/1616 [00:37<12:39,  2.06it/s]




  3%|▎         | 55/1616 [00:38<13:09,  1.98it/s]




  4%|▎         | 57/1616 [00:40<20:29,  1.27it/s]




  4%|▎         | 58/1616 [00:41<20:58,  1.24it/s]




  4%|▎         | 59/1616 [00:41<17:25,  1.49it/s]




  4%|▎         | 60/1616 [00:42<15:43,  1.65it/s]




  4%|▍         | 62/1616 [00:42<12:28,  2.08it/s]




  4%|▍         | 63/1616 [00:43<13:15,  1.95it/s]




  4%|▍         | 65/1616 [00:45<19:07,  1.35it/s]




  4%|▍         | 66/1616 [00:46<21:57,  1.18it/s]




  4%|▍         | 67/1616 [00:47<19:39,  1.31it/s]




  4%|▍         | 69/1616 [00:47<13:26,  1.92it/s]




  4%|▍         | 70/1616 [00:47<12:03,  2.14it/s]




  4%|▍         | 71/1616 [00:48<14:32,  1.77it/s]




  4%|▍         | 72/1616 [00:49<13:42,  1.88it/s]




  5%|▍         | 73/1616 [00:51<24:15,  1.06it/s]




  5%|▍         | 74/1616 [00:51<22:04,  1.16it/s]




  5%|▍         | 75/1616 [00:52<20:39,  1.24it/s]




  5%|▍         | 76/1616 [00:52<16:57,  1.51it/s]




  5%|▍         | 78/1616 [00:53<11:39,  2.20it/s]




  5%|▍         | 79/1616 [00:53<13:40,  1.87it/s]




  5%|▍         | 80/1616 [00:54<13:36,  1.88it/s]




  5%|▌         | 81/1616 [00:56<22:33,  1.13it/s]




  5%|▌         | 82/1616 [00:56<20:25,  1.25it/s]




  5%|▌         | 83/1616 [00:57<19:12,  1.33it/s]




  5%|▌         | 84/1616 [00:57<15:54,  1.60it/s]




  5%|▌         | 85/1616 [00:58<12:27,  2.05it/s]




  5%|▌         | 86/1616 [00:58<10:19,  2.47it/s]




  5%|▌         | 87/1616 [00:59<14:44,  1.73it/s]




  5%|▌         | 88/1616 [00:59<15:41,  1.62it/s]




  6%|▌         | 89/1616 [01:01<21:27,  1.19it/s]




  6%|▌         | 90/1616 [01:02<21:24,  1.19it/s]




  6%|▌         | 91/1616 [01:02<18:40,  1.36it/s]




  6%|▌         | 92/1616 [01:03<17:01,  1.49it/s]




  6%|▌         | 93/1616 [01:03<12:55,  1.96it/s]




  6%|▌         | 94/1616 [01:03<13:39,  1.86it/s]




  6%|▌         | 95/1616 [01:04<17:14,  1.47it/s]




  6%|▌         | 96/1616 [01:05<18:45,  1.35it/s]




  6%|▌         | 97/1616 [01:06<16:26,  1.54it/s]




  6%|▌         | 98/1616 [01:07<20:39,  1.22it/s]




  6%|▌         | 99/1616 [01:07<18:16,  1.38it/s]




  6%|▌         | 100/1616 [01:08<15:00,  1.68it/s]




  6%|▋         | 101/1616 [01:08<13:39,  1.85it/s]




  6%|▋         | 102/1616 [01:09<16:28,  1.53it/s]




  6%|▋         | 103/1616 [01:10<17:14,  1.46it/s]




  6%|▋         | 104/1616 [01:11<18:43,  1.35it/s]




  6%|▋         | 105/1616 [01:11<15:05,  1.67it/s]




  7%|▋         | 106/1616 [01:12<18:46,  1.34it/s]




  7%|▋         | 107/1616 [01:13<18:01,  1.40it/s]




  7%|▋         | 108/1616 [01:13<13:37,  1.84it/s]




  7%|▋         | 109/1616 [01:13<12:53,  1.95it/s]




  7%|▋         | 110/1616 [01:14<15:36,  1.61it/s]




  7%|▋         | 111/1616 [01:15<17:37,  1.42it/s]




  7%|▋         | 112/1616 [01:16<20:29,  1.22it/s]




  7%|▋         | 113/1616 [01:16<16:57,  1.48it/s]




  7%|▋         | 114/1616 [01:17<15:55,  1.57it/s]




  7%|▋         | 115/1616 [01:18<21:17,  1.17it/s]




  7%|▋         | 116/1616 [01:18<15:48,  1.58it/s]




  7%|▋         | 118/1616 [01:20<14:47,  1.69it/s]




  7%|▋         | 119/1616 [01:21<18:15,  1.37it/s]




  7%|▋         | 120/1616 [01:21<17:16,  1.44it/s]




  7%|▋         | 121/1616 [01:22<16:08,  1.54it/s]




  8%|▊         | 122/1616 [01:23<17:07,  1.45it/s]




  8%|▊         | 123/1616 [01:24<20:25,  1.22it/s]




  8%|▊         | 124/1616 [01:24<16:10,  1.54it/s]




  8%|▊         | 125/1616 [01:24<12:32,  1.98it/s]




  8%|▊         | 126/1616 [01:25<14:36,  1.70it/s]




  8%|▊         | 127/1616 [01:26<18:53,  1.31it/s]




  8%|▊         | 128/1616 [01:27<16:29,  1.50it/s]




  8%|▊         | 129/1616 [01:27<16:03,  1.54it/s]




  8%|▊         | 130/1616 [01:28<16:21,  1.51it/s]




  8%|▊         | 131/1616 [01:29<19:44,  1.25it/s]




  8%|▊         | 132/1616 [01:29<16:08,  1.53it/s]




  8%|▊         | 134/1616 [01:30<15:27,  1.60it/s]




  8%|▊         | 135/1616 [01:32<18:42,  1.32it/s]




  8%|▊         | 136/1616 [01:32<16:10,  1.52it/s]




  9%|▊         | 138/1616 [01:33<16:38,  1.48it/s]




  9%|▊         | 139/1616 [01:34<16:18,  1.51it/s]




  9%|▊         | 140/1616 [01:35<15:26,  1.59it/s]




  9%|▊         | 141/1616 [01:35<14:38,  1.68it/s]




  9%|▉         | 142/1616 [01:36<18:07,  1.36it/s]




  9%|▉         | 143/1616 [01:37<18:13,  1.35it/s]




  9%|▉         | 144/1616 [01:37<15:47,  1.55it/s]




  9%|▉         | 145/1616 [01:38<14:53,  1.65it/s]




  9%|▉         | 146/1616 [01:39<17:42,  1.38it/s]




  9%|▉         | 147/1616 [01:39<14:35,  1.68it/s]




  9%|▉         | 148/1616 [01:40<17:38,  1.39it/s]

  9%|▉         | 150/1616 [01:41<16:40,  1.46it/s]




  9%|▉         | 151/1616 [01:43<19:18,  1.26it/s]




  9%|▉         | 152/1616 [01:43<15:47,  1.54it/s]




  9%|▉         | 153/1616 [01:43<12:27,  1.96it/s]




 10%|▉         | 154/1616 [01:44<16:44,  1.46it/s]




 10%|▉         | 155/1616 [01:44<14:16,  1.71it/s]




 10%|▉         | 156/1616 [01:45<15:19,  1.59it/s]




 10%|▉         | 157/1616 [01:45<11:46,  2.07it/s]




 10%|▉         | 158/1616 [01:46<16:37,  1.46it/s]




 10%|▉         | 159/1616 [01:48<22:19,  1.09it/s]




 10%|▉         | 160/1616 [01:48<16:51,  1.44it/s]




 10%|▉         | 161/1616 [01:48<13:03,  1.86it/s]




 10%|█         | 162/1616 [01:49<15:36,  1.55it/s]




 10%|█         | 163/1616 [01:50<14:00,  1.73it/s]




 10%|█         | 164/1616 [01:50<13:59,  1.73it/s]




 10%|█         | 165/1616 [01:51<14:29,  1.67it/s]




 10%|█         | 166/1616 [01:52<20:55,  1.15it/s]




 10%|█         | 167/1616 [01:53<21:27,  1.13it/s]




 10%|█         | 168/1616 [01:53<15:47,  1.53it/s]




 10%|█         | 169/1616 [01:54<15:45,  1.53it/s]




 11%|█         | 170/1616 [01:54<13:22,  1.80it/s]




 11%|█         | 171/1616 [01:55<15:38,  1.54it/s]




 11%|█         | 172/1616 [01:56<14:13,  1.69it/s]




 11%|█         | 173/1616 [01:56<10:50,  2.22it/s]




 11%|█         | 174/1616 [01:58<20:50,  1.15it/s]




 11%|█         | 175/1616 [01:59<21:34,  1.11it/s]




 11%|█         | 176/1616 [01:59<16:10,  1.48it/s]




 11%|█         | 177/1616 [01:59<15:44,  1.52it/s]




 11%|█         | 179/1616 [02:00<14:17,  1.68it/s]




 11%|█         | 180/1616 [02:01<12:10,  1.97it/s]




 11%|█         | 181/1616 [02:01<10:30,  2.28it/s]




 11%|█▏        | 182/1616 [02:03<19:28,  1.23it/s]




 11%|█▏        | 183/1616 [02:03<19:17,  1.24it/s]




 11%|█▏        | 184/1616 [02:04<17:34,  1.36it/s]




 11%|█▏        | 185/1616 [02:05<16:31,  1.44it/s]




 12%|█▏        | 186/1616 [02:05<12:48,  1.86it/s]




 12%|█▏        | 187/1616 [02:06<15:16,  1.56it/s]




 12%|█▏        | 189/1616 [02:06<12:19,  1.93it/s]




 12%|█▏        | 190/1616 [02:08<17:02,  1.40it/s]




 12%|█▏        | 191/1616 [02:09<18:35,  1.28it/s]




 12%|█▏        | 192/1616 [02:09<17:15,  1.38it/s]




 12%|█▏        | 193/1616 [02:10<15:50,  1.50it/s]




 12%|█▏        | 194/1616 [02:10<15:12,  1.56it/s]




 12%|█▏        | 195/1616 [02:11<17:56,  1.32it/s]




 12%|█▏        | 197/1616 [02:12<11:41,  2.02it/s]




 12%|█▏        | 198/1616 [02:14<19:46,  1.20it/s]




 12%|█▏        | 199/1616 [02:14<18:32,  1.27it/s]




 12%|█▏        | 200/1616 [02:15<18:45,  1.26it/s]




 12%|█▏        | 201/1616 [02:15<15:46,  1.49it/s]




 12%|█▎        | 202/1616 [02:16<15:16,  1.54it/s]




 13%|█▎        | 203/1616 [02:17<15:41,  1.50it/s]




 13%|█▎        | 204/1616 [02:17<14:13,  1.65it/s]




 13%|█▎        | 205/1616 [02:17<11:38,  2.02it/s]




 13%|█▎        | 206/1616 [02:20<22:32,  1.04it/s]




 13%|█▎        | 208/1616 [02:21<18:47,  1.25it/s]




 13%|█▎        | 209/1616 [02:21<15:22,  1.53it/s]




 13%|█▎        | 210/1616 [02:21<14:08,  1.66it/s]




 13%|█▎        | 211/1616 [02:22<14:19,  1.63it/s]




 13%|█▎        | 212/1616 [02:23<14:51,  1.58it/s]




 13%|█▎        | 213/1616 [02:23<13:43,  1.70it/s]




 13%|█▎        | 214/1616 [02:25<22:05,  1.06it/s]




 13%|█▎        | 215/1616 [02:26<18:40,  1.25it/s]




 13%|█▎        | 216/1616 [02:26<16:04,  1.45it/s]




 13%|█▎        | 217/1616 [02:26<13:03,  1.79it/s]




 13%|█▎        | 218/1616 [02:27<17:24,  1.34it/s]




 14%|█▎        | 219/1616 [02:27<13:00,  1.79it/s]




 14%|█▎        | 220/1616 [02:28<13:50,  1.68it/s]




 14%|█▎        | 221/1616 [02:29<12:39,  1.84it/s]




 14%|█▎        | 222/1616 [02:30<19:49,  1.17it/s]




 14%|█▍        | 223/1616 [02:31<18:00,  1.29it/s]




 14%|█▍        | 224/1616 [02:31<16:10,  1.43it/s]




 14%|█▍        | 225/1616 [02:31<12:07,  1.91it/s]




 14%|█▍        | 226/1616 [02:32<16:07,  1.44it/s]




 14%|█▍        | 227/1616 [02:33<13:02,  1.78it/s]




 14%|█▍        | 228/1616 [02:33<12:42,  1.82it/s]




 14%|█▍        | 229/1616 [02:34<11:12,  2.06it/s]




 14%|█▍        | 230/1616 [02:35<18:27,  1.25it/s]




 14%|█▍        | 231/1616 [02:36<17:27,  1.32it/s]




 14%|█▍        | 232/1616 [02:37<17:24,  1.33it/s]




 14%|█▍        | 233/1616 [02:37<13:05,  1.76it/s]




 14%|█▍        | 234/1616 [02:38<18:59,  1.21it/s]




 15%|█▍        | 235/1616 [02:38<15:16,  1.51it/s]




 15%|█▍        | 236/1616 [02:39<14:31,  1.58it/s]




 15%|█▍        | 237/1616 [02:40<14:42,  1.56it/s]




 15%|█▍        | 238/1616 [02:40<16:18,  1.41it/s]




 15%|█▍        | 239/1616 [02:41<15:03,  1.52it/s]




 15%|█▍        | 240/1616 [02:42<16:49,  1.36it/s]




 15%|█▍        | 241/1616 [02:42<14:10,  1.62it/s]




 15%|█▍        | 242/1616 [02:44<20:10,  1.13it/s]




 15%|█▌        | 243/1616 [02:44<17:11,  1.33it/s]




 15%|█▌        | 244/1616 [02:45<15:05,  1.51it/s]




 15%|█▌        | 245/1616 [02:45<12:46,  1.79it/s]




 15%|█▌        | 246/1616 [02:46<12:34,  1.82it/s]




 15%|█▌        | 247/1616 [02:46<12:23,  1.84it/s]




 15%|█▌        | 248/1616 [02:47<17:04,  1.33it/s]




 15%|█▌        | 249/1616 [02:48<14:56,  1.52it/s]




 15%|█▌        | 250/1616 [02:49<18:36,  1.22it/s]




 16%|█▌        | 251/1616 [02:49<15:58,  1.42it/s]




 16%|█▌        | 252/1616 [02:50<13:37,  1.67it/s]




 16%|█▌        | 253/1616 [02:50<12:52,  1.76it/s]




 16%|█▌        | 254/1616 [02:50<10:50,  2.09it/s]




 16%|█▌        | 255/1616 [02:51<12:06,  1.87it/s]




 16%|█▌        | 256/1616 [02:52<17:31,  1.29it/s]




 16%|█▌        | 257/1616 [02:53<15:42,  1.44it/s]




 16%|█▌        | 258/1616 [02:55<21:34,  1.05it/s]




 16%|█▌        | 260/1616 [02:55<12:42,  1.78it/s]




 16%|█▌        | 261/1616 [02:56<15:50,  1.43it/s]




 16%|█▌        | 262/1616 [02:56<12:42,  1.78it/s]




 16%|█▋        | 263/1616 [02:56<11:20,  1.99it/s]




 16%|█▋        | 264/1616 [02:58<15:45,  1.43it/s]




 16%|█▋        | 265/1616 [02:58<15:08,  1.49it/s]




 16%|█▋        | 266/1616 [03:00<20:23,  1.10it/s]




 17%|█▋        | 267/1616 [03:00<15:40,  1.43it/s]




 17%|█▋        | 268/1616 [03:01<15:50,  1.42it/s]




 17%|█▋        | 269/1616 [03:01<17:09,  1.31it/s]




 17%|█▋        | 270/1616 [03:02<14:14,  1.58it/s]




 17%|█▋        | 271/1616 [03:02<11:24,  1.96it/s]

 17%|█▋        | 272/1616 [03:03<12:07,  1.85it/s]




 17%|█▋        | 273/1616 [03:03<14:09,  1.58it/s]




 17%|█▋        | 274/1616 [03:05<19:41,  1.14it/s]




 17%|█▋        | 275/1616 [03:05<15:09,  1.47it/s]




 17%|█▋        | 276/1616 [03:06<15:06,  1.48it/s]




 17%|█▋        | 277/1616 [03:07<15:43,  1.42it/s]




 17%|█▋        | 278/1616 [03:07<12:44,  1.75it/s]




 17%|█▋        | 279/1616 [03:07<11:49,  1.88it/s]




 17%|█▋        | 280/1616 [03:08<11:39,  1.91it/s]




 17%|█▋        | 281/1616 [03:09<13:30,  1.65it/s]




 17%|█▋        | 282/1616 [03:10<17:19,  1.28it/s]




 18%|█▊        | 283/1616 [03:11<18:20,  1.21it/s]




 18%|█▊        | 284/1616 [03:11<14:03,  1.58it/s]




 18%|█▊        | 285/1616 [03:12<14:43,  1.51it/s]




 18%|█▊        | 286/1616 [03:12<12:31,  1.77it/s]




 18%|█▊        | 287/1616 [03:13<15:59,  1.38it/s]




 18%|█▊        | 288/1616 [03:14<14:17,  1.55it/s]




 18%|█▊        | 289/1616 [03:14<14:49,  1.49it/s]




 18%|█▊        | 290/1616 [03:16<19:13,  1.15it/s]




 18%|█▊        | 291/1616 [03:16<16:51,  1.31it/s]




 18%|█▊        | 293/1616 [03:17<13:00,  1.69it/s]




 18%|█▊        | 294/1616 [03:17<11:42,  1.88it/s]




 18%|█▊        | 295/1616 [03:18<15:17,  1.44it/s]




 18%|█▊        | 296/1616 [03:19<13:42,  1.60it/s]




 18%|█▊        | 297/1616 [03:19<13:29,  1.63it/s]




 18%|█▊        | 298/1616 [03:21<17:05,  1.29it/s]




 19%|█▊        | 299/1616 [03:21<16:07,  1.36it/s]




 19%|█▊        | 301/1616 [03:22<12:50,  1.71it/s]




 19%|█▊        | 302/1616 [03:22<11:00,  1.99it/s]




 19%|█▉        | 303/1616 [03:23<14:35,  1.50it/s]




 19%|█▉        | 304/1616 [03:24<13:14,  1.65it/s]




 19%|█▉        | 305/1616 [03:25<14:31,  1.50it/s]




 19%|█▉        | 306/1616 [03:26<18:18,  1.19it/s]




 19%|█▉        | 307/1616 [03:27<16:49,  1.30it/s]




 19%|█▉        | 308/1616 [03:27<14:05,  1.55it/s]




 19%|█▉        | 309/1616 [03:27<10:54,  2.00it/s]




 19%|█▉        | 310/1616 [03:28<13:32,  1.61it/s]




 19%|█▉        | 311/1616 [03:29<13:18,  1.63it/s]




 19%|█▉        | 312/1616 [03:30<15:33,  1.40it/s]




 19%|█▉        | 313/1616 [03:30<13:28,  1.61it/s]




 19%|█▉        | 314/1616 [03:31<16:43,  1.30it/s]




 19%|█▉        | 315/1616 [03:32<16:32,  1.31it/s]




 20%|█▉        | 316/1616 [03:32<14:25,  1.50it/s]




 20%|█▉        | 317/1616 [03:33<12:08,  1.78it/s]




 20%|█▉        | 318/1616 [03:33<13:46,  1.57it/s]




 20%|█▉        | 319/1616 [03:34<12:41,  1.70it/s]




 20%|█▉        | 320/1616 [03:35<15:28,  1.40it/s]




 20%|█▉        | 321/1616 [03:35<12:46,  1.69it/s]




 20%|█▉        | 322/1616 [03:36<15:11,  1.42it/s]




 20%|█▉        | 323/1616 [03:37<18:23,  1.17it/s]




 20%|██        | 324/1616 [03:37<13:46,  1.56it/s]




 20%|██        | 325/1616 [03:38<11:47,  1.82it/s]




 20%|██        | 326/1616 [03:38<12:45,  1.69it/s]




 20%|██        | 327/1616 [03:39<12:30,  1.72it/s]




 20%|██        | 328/1616 [03:40<16:03,  1.34it/s]




 20%|██        | 329/1616 [03:40<12:24,  1.73it/s]




 20%|██        | 330/1616 [03:41<14:02,  1.53it/s]




 20%|██        | 331/1616 [03:43<18:31,  1.16it/s]




 21%|██        | 332/1616 [03:43<15:30,  1.38it/s]




 21%|██        | 334/1616 [03:44<12:15,  1.74it/s]




 21%|██        | 335/1616 [03:45<15:28,  1.38it/s]




 21%|██        | 336/1616 [03:45<13:21,  1.60it/s]




 21%|██        | 337/1616 [03:46<14:39,  1.45it/s]




 21%|██        | 338/1616 [03:47<13:15,  1.61it/s]




 21%|██        | 339/1616 [03:48<16:03,  1.33it/s]




 21%|██        | 340/1616 [03:48<15:21,  1.39it/s]




 21%|██        | 341/1616 [03:49<14:42,  1.44it/s]




 21%|██        | 342/1616 [03:49<11:29,  1.85it/s]




 21%|██        | 343/1616 [03:51<17:32,  1.21it/s]




 21%|██▏       | 345/1616 [03:52<15:40,  1.35it/s]




 21%|██▏       | 347/1616 [03:53<13:58,  1.51it/s]




 22%|██▏       | 348/1616 [03:54<13:34,  1.56it/s]




 22%|██▏       | 349/1616 [03:54<12:40,  1.67it/s]




 22%|██▏       | 350/1616 [03:54<12:02,  1.75it/s]




 22%|██▏       | 351/1616 [03:56<16:05,  1.31it/s]




 22%|██▏       | 352/1616 [03:56<13:36,  1.55it/s]




 22%|██▏       | 353/1616 [03:57<15:48,  1.33it/s]




 22%|██▏       | 354/1616 [03:58<13:45,  1.53it/s]




 22%|██▏       | 355/1616 [03:58<12:49,  1.64it/s]




 22%|██▏       | 356/1616 [03:59<12:44,  1.65it/s]




 22%|██▏       | 357/1616 [04:00<15:44,  1.33it/s]




 22%|██▏       | 358/1616 [04:00<15:42,  1.33it/s]




 22%|██▏       | 359/1616 [04:01<13:40,  1.53it/s]




 22%|██▏       | 360/1616 [04:02<13:56,  1.50it/s]




 22%|██▏       | 361/1616 [04:02<15:13,  1.37it/s]




 22%|██▏       | 362/1616 [04:03<16:00,  1.31it/s]




 22%|██▏       | 363/1616 [04:03<12:12,  1.71it/s]




 23%|██▎       | 364/1616 [04:04<12:13,  1.71it/s]




 23%|██▎       | 365/1616 [04:05<15:14,  1.37it/s]




 23%|██▎       | 366/1616 [04:06<16:59,  1.23it/s]




 23%|██▎       | 367/1616 [04:06<13:04,  1.59it/s]




 23%|██▎       | 368/1616 [04:07<11:17,  1.84it/s]




 23%|██▎       | 369/1616 [04:08<15:08,  1.37it/s]




 23%|██▎       | 370/1616 [04:08<14:29,  1.43it/s]




 23%|██▎       | 371/1616 [04:09<11:08,  1.86it/s]




 23%|██▎       | 372/1616 [04:09<11:56,  1.74it/s]




 23%|██▎       | 373/1616 [04:10<13:44,  1.51it/s]




 23%|██▎       | 374/1616 [04:11<17:25,  1.19it/s]




 23%|██▎       | 375/1616 [04:12<14:00,  1.48it/s]




 23%|██▎       | 376/1616 [04:12<10:48,  1.91it/s]




 23%|██▎       | 377/1616 [04:13<15:04,  1.37it/s]




 23%|██▎       | 378/1616 [04:14<13:18,  1.55it/s]




 23%|██▎       | 379/1616 [04:14<11:15,  1.83it/s]




 24%|██▎       | 380/1616 [04:15<13:15,  1.55it/s]




 24%|██▎       | 381/1616 [04:15<13:41,  1.50it/s]




 24%|██▎       | 382/1616 [04:17<19:08,  1.07it/s]




 24%|██▎       | 383/1616 [04:17<16:22,  1.26it/s]




 24%|██▍       | 384/1616 [04:18<13:03,  1.57it/s]




 24%|██▍       | 385/1616 [04:19<14:40,  1.40it/s]




 24%|██▍       | 387/1616 [04:19<11:14,  1.82it/s]




 24%|██▍       | 388/1616 [04:20<11:39,  1.75it/s]




 24%|██▍       | 389/1616 [04:21<12:32,  1.63it/s]




 24%|██▍       | 390/1616 [04:22<18:14,  1.12it/s]




 24%|██▍       | 391/1616 [04:23<16:20,  1.25it/s]




 24%|██▍       | 392/1616 [04:23<12:23,  1.65it/s]




 24%|██▍       | 393/1616 [04:24<13:50,  1.47it/s]




 24%|██▍       | 394/1616 [04:24<11:15,  1.81it/s]

 24%|██▍       | 395/1616 [04:25<11:05,  1.84it/s]




 25%|██▍       | 396/1616 [04:25<10:32,  1.93it/s]




 25%|██▍       | 397/1616 [04:26<11:42,  1.74it/s]




 25%|██▍       | 398/1616 [04:28<19:53,  1.02it/s]




 25%|██▍       | 399/1616 [04:28<16:27,  1.23it/s]




 25%|██▍       | 400/1616 [04:29<14:24,  1.41it/s]




 25%|██▍       | 401/1616 [04:29<12:54,  1.57it/s]




 25%|██▍       | 402/1616 [04:30<11:59,  1.69it/s]




 25%|██▍       | 403/1616 [04:30<09:25,  2.14it/s]




 25%|██▌       | 404/1616 [04:31<12:21,  1.64it/s]




 25%|██▌       | 405/1616 [04:32<14:35,  1.38it/s]




 25%|██▌       | 406/1616 [04:33<18:49,  1.07it/s]




 25%|██▌       | 407/1616 [04:33<13:58,  1.44it/s]




 25%|██▌       | 408/1616 [04:34<14:44,  1.37it/s]




 25%|██▌       | 409/1616 [04:35<14:35,  1.38it/s]




 25%|██▌       | 411/1616 [04:35<10:42,  1.88it/s]




 25%|██▌       | 412/1616 [04:36<12:35,  1.59it/s]




 26%|██▌       | 413/1616 [04:37<12:50,  1.56it/s]




 26%|██▌       | 414/1616 [04:38<16:33,  1.21it/s]




 26%|██▌       | 415/1616 [04:39<12:49,  1.56it/s]




 26%|██▌       | 416/1616 [04:40<14:45,  1.36it/s]




 26%|██▌       | 417/1616 [04:40<12:38,  1.58it/s]




 26%|██▌       | 418/1616 [04:40<11:38,  1.71it/s]




 26%|██▌       | 419/1616 [04:41<09:59,  2.00it/s]




 26%|██▌       | 420/1616 [04:42<12:20,  1.62it/s]




 26%|██▌       | 421/1616 [04:42<11:04,  1.80it/s]




 26%|██▌       | 422/1616 [04:44<17:35,  1.13it/s]




 26%|██▌       | 424/1616 [04:45<13:46,  1.44it/s]




 26%|██▋       | 425/1616 [04:45<12:00,  1.65it/s]




 26%|██▋       | 426/1616 [04:46<14:59,  1.32it/s]




 26%|██▋       | 427/1616 [04:46<11:56,  1.66it/s]




 26%|██▋       | 428/1616 [04:47<11:03,  1.79it/s]




 27%|██▋       | 429/1616 [04:47<09:46,  2.02it/s]




 27%|██▋       | 430/1616 [04:49<18:00,  1.10it/s]




 27%|██▋       | 431/1616 [04:49<14:11,  1.39it/s]




 27%|██▋       | 432/1616 [04:50<16:27,  1.20it/s]




 27%|██▋       | 433/1616 [04:51<13:07,  1.50it/s]




 27%|██▋       | 434/1616 [04:51<12:24,  1.59it/s]




 27%|██▋       | 435/1616 [04:52<12:51,  1.53it/s]




 27%|██▋       | 436/1616 [04:52<10:19,  1.91it/s]




 27%|██▋       | 438/1616 [04:54<15:38,  1.26it/s]




 27%|██▋       | 439/1616 [04:55<12:45,  1.54it/s]




 27%|██▋       | 440/1616 [04:56<15:02,  1.30it/s]




 27%|██▋       | 441/1616 [04:56<11:53,  1.65it/s]




 27%|██▋       | 442/1616 [04:56<11:09,  1.75it/s]




 27%|██▋       | 443/1616 [04:57<11:14,  1.74it/s]




 27%|██▋       | 444/1616 [04:57<10:00,  1.95it/s]




 28%|██▊       | 446/1616 [05:00<16:11,  1.20it/s]




 28%|██▊       | 448/1616 [05:01<14:39,  1.33it/s]




 28%|██▊       | 450/1616 [05:01<11:06,  1.75it/s]




 28%|██▊       | 451/1616 [05:02<11:33,  1.68it/s]




 28%|██▊       | 452/1616 [05:02<10:06,  1.92it/s]




 28%|██▊       | 453/1616 [05:03<10:00,  1.94it/s]




 28%|██▊       | 454/1616 [05:05<19:20,  1.00it/s]




 28%|██▊       | 455/1616 [05:06<16:26,  1.18it/s]




 28%|██▊       | 456/1616 [05:06<14:20,  1.35it/s]




 28%|██▊       | 457/1616 [05:06<11:00,  1.76it/s]




 28%|██▊       | 458/1616 [05:07<09:26,  2.04it/s]




 28%|██▊       | 459/1616 [05:08<13:03,  1.48it/s]




 29%|██▊       | 461/1616 [05:09<11:01,  1.75it/s]




 29%|██▊       | 462/1616 [05:11<17:31,  1.10it/s]




 29%|██▊       | 463/1616 [05:11<14:37,  1.31it/s]




 29%|██▊       | 464/1616 [05:11<12:43,  1.51it/s]




 29%|██▉       | 465/1616 [05:12<10:20,  1.85it/s]




 29%|██▉       | 466/1616 [05:12<08:57,  2.14it/s]




 29%|██▉       | 467/1616 [05:13<11:26,  1.67it/s]




 29%|██▉       | 468/1616 [05:13<08:45,  2.19it/s]




 29%|██▉       | 469/1616 [05:14<12:20,  1.55it/s]




 29%|██▉       | 470/1616 [05:16<19:55,  1.04s/it]




 29%|██▉       | 471/1616 [05:16<16:10,  1.18it/s]




 29%|██▉       | 472/1616 [05:17<12:44,  1.50it/s]




 29%|██▉       | 473/1616 [05:17<10:39,  1.79it/s]




 29%|██▉       | 474/1616 [05:17<08:48,  2.16it/s]




 29%|██▉       | 475/1616 [05:18<10:23,  1.83it/s]




 29%|██▉       | 476/1616 [05:18<08:36,  2.21it/s]




 30%|██▉       | 477/1616 [05:19<13:00,  1.46it/s]




 30%|██▉       | 478/1616 [05:21<21:16,  1.12s/it]




 30%|██▉       | 479/1616 [05:22<17:00,  1.11it/s]




 30%|██▉       | 480/1616 [05:22<13:45,  1.38it/s]




 30%|██▉       | 481/1616 [05:22<11:06,  1.70it/s]




 30%|██▉       | 482/1616 [05:23<08:23,  2.25it/s]




 30%|██▉       | 483/1616 [05:23<09:26,  2.00it/s]




 30%|██▉       | 484/1616 [05:23<08:09,  2.31it/s]




 30%|███       | 485/1616 [05:25<14:20,  1.31it/s]




 30%|███       | 486/1616 [05:27<19:25,  1.03s/it]




 30%|███       | 487/1616 [05:27<17:35,  1.07it/s]




 30%|███       | 488/1616 [05:27<12:58,  1.45it/s]




 30%|███       | 489/1616 [05:28<10:09,  1.85it/s]




 30%|███       | 491/1616 [05:28<07:42,  2.43it/s]




 30%|███       | 492/1616 [05:29<08:10,  2.29it/s]




 31%|███       | 493/1616 [05:30<13:27,  1.39it/s]




 31%|███       | 494/1616 [05:32<17:52,  1.05it/s]




 31%|███       | 495/1616 [05:33<16:55,  1.10it/s]




 31%|███       | 496/1616 [05:33<13:14,  1.41it/s]




 31%|███       | 497/1616 [05:33<10:41,  1.74it/s]




 31%|███       | 499/1616 [05:33<06:35,  2.82it/s]




 31%|███       | 500/1616 [05:34<09:07,  2.04it/s]




 31%|███       | 501/1616 [05:35<12:56,  1.44it/s]




 31%|███       | 502/1616 [05:37<16:23,  1.13it/s]




 31%|███       | 503/1616 [05:38<18:01,  1.03it/s]




 31%|███▏      | 505/1616 [05:38<10:43,  1.73it/s]




 31%|███▏      | 506/1616 [05:39<10:10,  1.82it/s]




 31%|███▏      | 507/1616 [05:39<08:23,  2.20it/s]




 31%|███▏      | 508/1616 [05:40<10:58,  1.68it/s]




 31%|███▏      | 509/1616 [05:41<12:23,  1.49it/s]




 32%|███▏      | 510/1616 [05:42<15:55,  1.16it/s]




 32%|███▏      | 511/1616 [05:43<17:10,  1.07it/s]




 32%|███▏      | 512/1616 [05:43<13:53,  1.33it/s]




 32%|███▏      | 513/1616 [05:44<11:10,  1.65it/s]




 32%|███▏      | 515/1616 [05:44<07:06,  2.58it/s]




 32%|███▏      | 516/1616 [05:45<10:02,  1.82it/s]




 32%|███▏      | 517/1616 [05:46<12:05,  1.52it/s]




 32%|███▏      | 518/1616 [05:47<14:46,  1.24it/s]




 32%|███▏      | 519/1616 [05:48<16:25,  1.11it/s]




 32%|███▏      | 520/1616 [05:49<13:15,  1.38it/s]




 32%|███▏      | 521/1616 [05:49<11:22,  1.60it/s]




 32%|███▏      | 522/1616 [05:49<09:11,  1.98it/s]

 32%|███▏      | 523/1616 [05:49<08:11,  2.22it/s]




 32%|███▏      | 524/1616 [05:51<12:49,  1.42it/s]




 32%|███▏      | 525/1616 [05:52<15:46,  1.15it/s]




 33%|███▎      | 526/1616 [05:52<12:16,  1.48it/s]




 33%|███▎      | 527/1616 [05:53<14:25,  1.26it/s]




 33%|███▎      | 528/1616 [05:54<12:24,  1.46it/s]




 33%|███▎      | 529/1616 [05:54<11:55,  1.52it/s]




 33%|███▎      | 531/1616 [05:55<11:09,  1.62it/s]




 33%|███▎      | 532/1616 [05:57<14:03,  1.28it/s]




 33%|███▎      | 533/1616 [05:58<15:29,  1.16it/s]




 33%|███▎      | 534/1616 [05:58<12:58,  1.39it/s]




 33%|███▎      | 535/1616 [05:59<11:34,  1.56it/s]




 33%|███▎      | 536/1616 [06:00<12:48,  1.41it/s]




 33%|███▎      | 537/1616 [06:00<10:46,  1.67it/s]




 33%|███▎      | 538/1616 [06:00<08:09,  2.20it/s]




 33%|███▎      | 539/1616 [06:01<10:55,  1.64it/s]




 33%|███▎      | 540/1616 [06:02<14:05,  1.27it/s]




 33%|███▎      | 541/1616 [06:03<15:20,  1.17it/s]




 34%|███▎      | 542/1616 [06:04<13:14,  1.35it/s]




 34%|███▎      | 543/1616 [06:04<10:26,  1.71it/s]




 34%|███▎      | 544/1616 [06:05<12:16,  1.45it/s]




 34%|███▎      | 545/1616 [06:05<10:52,  1.64it/s]




 34%|███▍      | 546/1616 [06:05<08:12,  2.17it/s]




 34%|███▍      | 547/1616 [06:07<12:19,  1.45it/s]




 34%|███▍      | 548/1616 [06:07<13:21,  1.33it/s]




 34%|███▍      | 549/1616 [06:08<14:21,  1.24it/s]




 34%|███▍      | 550/1616 [06:09<12:49,  1.38it/s]




 34%|███▍      | 551/1616 [06:09<11:49,  1.50it/s]




 34%|███▍      | 552/1616 [06:10<11:20,  1.56it/s]




 34%|███▍      | 553/1616 [06:11<11:58,  1.48it/s]




 34%|███▍      | 554/1616 [06:11<09:33,  1.85it/s]




 34%|███▍      | 555/1616 [06:12<11:36,  1.52it/s]




 34%|███▍      | 556/1616 [06:13<12:11,  1.45it/s]




 34%|███▍      | 557/1616 [06:14<12:58,  1.36it/s]




 35%|███▍      | 558/1616 [06:15<15:04,  1.17it/s]




 35%|███▍      | 559/1616 [06:15<11:11,  1.57it/s]




 35%|███▍      | 560/1616 [06:15<09:48,  1.80it/s]




 35%|███▍      | 561/1616 [06:16<10:57,  1.61it/s]




 35%|███▍      | 562/1616 [06:16<10:29,  1.67it/s]




 35%|███▍      | 563/1616 [06:17<12:35,  1.39it/s]




 35%|███▍      | 564/1616 [06:18<12:18,  1.42it/s]




 35%|███▍      | 565/1616 [06:19<12:45,  1.37it/s]




 35%|███▌      | 566/1616 [06:20<14:20,  1.22it/s]




 35%|███▌      | 568/1616 [06:20<09:20,  1.87it/s]




 35%|███▌      | 569/1616 [06:21<09:43,  1.80it/s]




 35%|███▌      | 570/1616 [06:22<12:48,  1.36it/s]




 35%|███▌      | 571/1616 [06:23<15:01,  1.16it/s]




 35%|███▌      | 572/1616 [06:24<12:00,  1.45it/s]




 35%|███▌      | 573/1616 [06:24<10:41,  1.63it/s]




 36%|███▌      | 574/1616 [06:25<12:52,  1.35it/s]




 36%|███▌      | 575/1616 [06:25<10:50,  1.60it/s]




 36%|███▌      | 576/1616 [06:26<10:44,  1.61it/s]




 36%|███▌      | 577/1616 [06:27<09:47,  1.77it/s]




 36%|███▌      | 578/1616 [06:28<12:11,  1.42it/s]




 36%|███▌      | 579/1616 [06:29<14:38,  1.18it/s]




 36%|███▌      | 580/1616 [06:29<12:53,  1.34it/s]




 36%|███▌      | 581/1616 [06:30<10:52,  1.59it/s]




 36%|███▌      | 582/1616 [06:30<11:00,  1.57it/s]




 36%|███▌      | 583/1616 [06:31<09:12,  1.87it/s]




 36%|███▌      | 584/1616 [06:31<10:58,  1.57it/s]




 36%|███▌      | 585/1616 [06:32<09:42,  1.77it/s]




 36%|███▋      | 586/1616 [06:33<11:22,  1.51it/s]




 36%|███▋      | 587/1616 [06:34<15:10,  1.13it/s]




 36%|███▋      | 588/1616 [06:34<12:08,  1.41it/s]




 36%|███▋      | 589/1616 [06:35<09:43,  1.76it/s]




 37%|███▋      | 590/1616 [06:35<10:19,  1.66it/s]




 37%|███▋      | 591/1616 [06:36<10:21,  1.65it/s]




 37%|███▋      | 592/1616 [06:37<11:59,  1.42it/s]




 37%|███▋      | 594/1616 [06:38<10:16,  1.66it/s]




 37%|███▋      | 595/1616 [06:39<14:22,  1.18it/s]




 37%|███▋      | 596/1616 [06:40<11:46,  1.44it/s]




 37%|███▋      | 597/1616 [06:40<10:05,  1.68it/s]




 37%|███▋      | 598/1616 [06:41<10:36,  1.60it/s]




 37%|███▋      | 599/1616 [06:41<10:06,  1.68it/s]




 37%|███▋      | 600/1616 [06:42<11:13,  1.51it/s]




 37%|███▋      | 602/1616 [06:44<11:36,  1.46it/s]




 37%|███▋      | 603/1616 [06:45<13:31,  1.25it/s]




 37%|███▋      | 604/1616 [06:45<12:34,  1.34it/s]




 37%|███▋      | 605/1616 [06:45<10:00,  1.68it/s]




 38%|███▊      | 606/1616 [06:46<09:36,  1.75it/s]




 38%|███▊      | 607/1616 [06:47<10:54,  1.54it/s]




 38%|███▊      | 608/1616 [06:47<10:53,  1.54it/s]




 38%|███▊      | 610/1616 [06:49<11:24,  1.47it/s]




 38%|███▊      | 611/1616 [06:50<12:53,  1.30it/s]




 38%|███▊      | 612/1616 [06:50<11:29,  1.46it/s]




 38%|███▊      | 613/1616 [06:51<09:20,  1.79it/s]




 38%|███▊      | 614/1616 [06:51<09:42,  1.72it/s]




 38%|███▊      | 615/1616 [06:52<10:12,  1.63it/s]




 38%|███▊      | 616/1616 [06:53<11:14,  1.48it/s]




 38%|███▊      | 617/1616 [06:53<08:28,  1.96it/s]




 38%|███▊      | 618/1616 [06:55<14:25,  1.15it/s]




 38%|███▊      | 619/1616 [06:55<13:07,  1.27it/s]




 38%|███▊      | 620/1616 [06:56<11:12,  1.48it/s]




 38%|███▊      | 621/1616 [06:56<09:28,  1.75it/s]




 38%|███▊      | 622/1616 [06:57<11:27,  1.45it/s]




 39%|███▊      | 623/1616 [06:57<08:49,  1.87it/s]




 39%|███▊      | 624/1616 [06:58<11:31,  1.43it/s]




 39%|███▊      | 625/1616 [06:59<11:12,  1.47it/s]




 39%|███▊      | 626/1616 [07:00<14:52,  1.11it/s]




 39%|███▉      | 627/1616 [07:01<12:58,  1.27it/s]




 39%|███▉      | 628/1616 [07:01<10:56,  1.51it/s]




 39%|███▉      | 629/1616 [07:01<08:18,  1.98it/s]




 39%|███▉      | 630/1616 [07:02<09:24,  1.75it/s]




 39%|███▉      | 631/1616 [07:03<09:25,  1.74it/s]




 39%|███▉      | 632/1616 [07:03<10:58,  1.49it/s]




 39%|███▉      | 633/1616 [07:05<13:54,  1.18it/s]




 39%|███▉      | 634/1616 [07:06<16:24,  1.00s/it]




 39%|███▉      | 635/1616 [07:06<13:07,  1.25it/s]




 39%|███▉      | 636/1616 [07:07<11:24,  1.43it/s]




 39%|███▉      | 637/1616 [07:07<08:28,  1.93it/s]




 39%|███▉      | 638/1616 [07:08<10:02,  1.62it/s]




 40%|███▉      | 639/1616 [07:08<08:57,  1.82it/s]




 40%|███▉      | 640/1616 [07:09<10:54,  1.49it/s]




 40%|███▉      | 641/1616 [07:10<13:41,  1.19it/s]




 40%|███▉      | 642/1616 [07:11<13:24,  1.21it/s]




 40%|███▉      | 643/1616 [07:12<12:34,  1.29it/s]




 40%|███▉      | 644/1616 [07:12<11:50,  1.37it/s]

 40%|███▉      | 645/1616 [07:13<10:00,  1.62it/s]




 40%|███▉      | 646/1616 [07:13<08:12,  1.97it/s]




 40%|████      | 647/1616 [07:14<09:48,  1.65it/s]




 40%|████      | 648/1616 [07:15<10:28,  1.54it/s]




 40%|████      | 649/1616 [07:16<14:39,  1.10it/s]




 40%|████      | 650/1616 [07:17<13:37,  1.18it/s]




 40%|████      | 651/1616 [07:17<12:03,  1.33it/s]




 40%|████      | 652/1616 [07:18<12:22,  1.30it/s]




 40%|████      | 653/1616 [07:19<10:47,  1.49it/s]




 41%|████      | 655/1616 [07:19<07:29,  2.14it/s]




 41%|████      | 656/1616 [07:20<08:39,  1.85it/s]




 41%|████      | 657/1616 [07:22<13:13,  1.21it/s]




 41%|████      | 658/1616 [07:22<11:51,  1.35it/s]




 41%|████      | 659/1616 [07:23<11:07,  1.43it/s]




 41%|████      | 660/1616 [07:23<11:12,  1.42it/s]




 41%|████      | 661/1616 [07:24<09:46,  1.63it/s]




 41%|████      | 662/1616 [07:24<08:43,  1.82it/s]




 41%|████      | 663/1616 [07:24<07:09,  2.22it/s]




 41%|████      | 664/1616 [07:25<09:16,  1.71it/s]




 41%|████      | 665/1616 [07:27<14:29,  1.09it/s]




 41%|████      | 666/1616 [07:27<11:42,  1.35it/s]




 41%|████▏     | 667/1616 [07:28<10:41,  1.48it/s]




 41%|████▏     | 668/1616 [07:29<12:12,  1.29it/s]




 41%|████▏     | 669/1616 [07:29<10:44,  1.47it/s]




 41%|████▏     | 670/1616 [07:29<08:42,  1.81it/s]




 42%|████▏     | 671/1616 [07:30<08:52,  1.78it/s]




 42%|████▏     | 672/1616 [07:31<08:35,  1.83it/s]




 42%|████▏     | 673/1616 [07:32<14:21,  1.09it/s]




 42%|████▏     | 674/1616 [07:33<11:08,  1.41it/s]




 42%|████▏     | 675/1616 [07:33<11:29,  1.36it/s]




 42%|████▏     | 676/1616 [07:34<12:18,  1.27it/s]




 42%|████▏     | 677/1616 [07:34<09:15,  1.69it/s]




 42%|████▏     | 678/1616 [07:35<08:19,  1.88it/s]




 42%|████▏     | 679/1616 [07:35<08:21,  1.87it/s]




 42%|████▏     | 680/1616 [07:36<07:46,  2.01it/s]




 42%|████▏     | 681/1616 [07:38<13:30,  1.15it/s]




 42%|████▏     | 682/1616 [07:38<11:22,  1.37it/s]




 42%|████▏     | 683/1616 [07:39<11:14,  1.38it/s]




 42%|████▏     | 684/1616 [07:40<11:57,  1.30it/s]




 42%|████▏     | 686/1616 [07:40<09:19,  1.66it/s]




 43%|████▎     | 687/1616 [07:41<07:46,  1.99it/s]




 43%|████▎     | 688/1616 [07:41<08:07,  1.90it/s]




 43%|████▎     | 689/1616 [07:43<12:37,  1.22it/s]




 43%|████▎     | 690/1616 [07:44<14:14,  1.08it/s]




 43%|████▎     | 692/1616 [07:45<10:23,  1.48it/s]




 43%|████▎     | 693/1616 [07:45<08:46,  1.75it/s]




 43%|████▎     | 694/1616 [07:46<10:57,  1.40it/s]




 43%|████▎     | 695/1616 [07:46<09:09,  1.67it/s]




 43%|████▎     | 696/1616 [07:47<09:22,  1.64it/s]




 43%|████▎     | 697/1616 [07:48<11:25,  1.34it/s]




 43%|████▎     | 698/1616 [07:49<13:33,  1.13it/s]




 43%|████▎     | 699/1616 [07:50<12:00,  1.27it/s]




 43%|████▎     | 700/1616 [07:50<10:34,  1.44it/s]




 43%|████▎     | 702/1616 [07:51<09:15,  1.65it/s]




 44%|████▎     | 703/1616 [07:52<08:01,  1.90it/s]




 44%|████▎     | 704/1616 [07:52<08:29,  1.79it/s]




 44%|████▎     | 705/1616 [07:53<10:24,  1.46it/s]




 44%|████▎     | 706/1616 [07:54<12:10,  1.25it/s]




 44%|████▍     | 707/1616 [07:55<13:11,  1.15it/s]




 44%|████▍     | 708/1616 [07:55<09:52,  1.53it/s]




 44%|████▍     | 710/1616 [07:57<09:47,  1.54it/s]




 44%|████▍     | 711/1616 [07:57<09:25,  1.60it/s]




 44%|████▍     | 713/1616 [07:59<11:59,  1.25it/s]




 44%|████▍     | 714/1616 [08:00<10:09,  1.48it/s]




 44%|████▍     | 715/1616 [08:01<11:44,  1.28it/s]




 44%|████▍     | 717/1616 [08:01<07:34,  1.98it/s]




 44%|████▍     | 718/1616 [08:03<12:08,  1.23it/s]




 45%|████▍     | 720/1616 [08:03<07:45,  1.92it/s]




 45%|████▍     | 721/1616 [08:05<11:38,  1.28it/s]




 45%|████▍     | 722/1616 [08:05<10:01,  1.49it/s]




 45%|████▍     | 723/1616 [08:06<11:39,  1.28it/s]




 45%|████▍     | 725/1616 [08:07<08:00,  1.85it/s]




 45%|████▍     | 726/1616 [08:08<11:40,  1.27it/s]




 45%|████▌     | 729/1616 [08:10<10:06,  1.46it/s]




 45%|████▌     | 730/1616 [08:10<09:10,  1.61it/s]




 45%|████▌     | 731/1616 [08:11<10:22,  1.42it/s]




 45%|████▌     | 732/1616 [08:11<08:35,  1.72it/s]




 45%|████▌     | 733/1616 [08:12<07:43,  1.90it/s]




 45%|████▌     | 734/1616 [08:13<11:17,  1.30it/s]




 45%|████▌     | 735/1616 [08:14<10:38,  1.38it/s]




 46%|████▌     | 736/1616 [08:14<08:14,  1.78it/s]




 46%|████▌     | 737/1616 [08:15<10:29,  1.40it/s]




 46%|████▌     | 738/1616 [08:16<10:01,  1.46it/s]




 46%|████▌     | 739/1616 [08:16<10:13,  1.43it/s]




 46%|████▌     | 740/1616 [08:17<11:14,  1.30it/s]




 46%|████▌     | 741/1616 [08:18<08:49,  1.65it/s]




 46%|████▌     | 742/1616 [08:19<12:14,  1.19it/s]




 46%|████▌     | 744/1616 [08:20<09:05,  1.60it/s]




 46%|████▌     | 745/1616 [08:20<08:56,  1.62it/s]




 46%|████▌     | 746/1616 [08:21<09:23,  1.54it/s]




 46%|████▌     | 747/1616 [08:22<09:40,  1.50it/s]




 46%|████▋     | 748/1616 [08:23<10:20,  1.40it/s]




 46%|████▋     | 749/1616 [08:23<08:56,  1.62it/s]




 46%|████▋     | 750/1616 [08:24<10:37,  1.36it/s]




 46%|████▋     | 751/1616 [08:24<08:26,  1.71it/s]




 47%|████▋     | 752/1616 [08:25<09:17,  1.55it/s]




 47%|████▋     | 753/1616 [08:25<08:18,  1.73it/s]




 47%|████▋     | 754/1616 [08:26<09:04,  1.58it/s]




 47%|████▋     | 755/1616 [08:27<09:38,  1.49it/s]




 47%|████▋     | 756/1616 [08:28<11:01,  1.30it/s]




 47%|████▋     | 757/1616 [08:28<09:42,  1.47it/s]




 47%|████▋     | 758/1616 [08:29<09:23,  1.52it/s]




 47%|████▋     | 759/1616 [08:29<07:52,  1.81it/s]




 47%|████▋     | 760/1616 [08:30<09:21,  1.52it/s]




 47%|████▋     | 761/1616 [08:31<08:50,  1.61it/s]




 47%|████▋     | 762/1616 [08:32<10:58,  1.30it/s]




 47%|████▋     | 763/1616 [08:32<09:02,  1.57it/s]




 47%|████▋     | 764/1616 [08:34<13:30,  1.05it/s]




 47%|████▋     | 765/1616 [08:34<10:05,  1.40it/s]




 47%|████▋     | 767/1616 [08:35<09:17,  1.52it/s]




 48%|████▊     | 768/1616 [08:35<07:29,  1.89it/s]




 48%|████▊     | 769/1616 [08:36<08:46,  1.61it/s]




 48%|████▊     | 770/1616 [08:37<10:13,  1.38it/s]




 48%|████▊     | 771/1616 [08:38<08:55,  1.58it/s]




 48%|████▊     | 772/1616 [08:39<12:41,  1.11it/s]




 48%|████▊     | 774/1616 [08:39<07:17,  1.92it/s]




 48%|████▊     | 775/1616 [08:41<09:49,  1.43it/s]

 48%|████▊     | 776/1616 [08:41<08:12,  1.71it/s]




 48%|████▊     | 777/1616 [08:41<07:57,  1.76it/s]




 48%|████▊     | 778/1616 [08:42<09:33,  1.46it/s]




 48%|████▊     | 779/1616 [08:43<08:50,  1.58it/s]




 48%|████▊     | 780/1616 [08:44<12:06,  1.15it/s]




 48%|████▊     | 781/1616 [08:45<09:27,  1.47it/s]




 48%|████▊     | 783/1616 [08:46<10:59,  1.26it/s]




 49%|████▊     | 786/1616 [08:48<08:39,  1.60it/s]




 49%|████▊     | 787/1616 [08:48<08:29,  1.63it/s]




 49%|████▉     | 788/1616 [08:50<11:08,  1.24it/s]




 49%|████▉     | 789/1616 [08:50<09:37,  1.43it/s]




 49%|████▉     | 791/1616 [08:52<09:33,  1.44it/s]




 49%|████▉     | 792/1616 [08:52<08:25,  1.63it/s]




 49%|████▉     | 794/1616 [08:53<07:58,  1.72it/s]




 49%|████▉     | 795/1616 [08:54<08:50,  1.55it/s]




 49%|████▉     | 796/1616 [08:55<10:58,  1.24it/s]




 49%|████▉     | 797/1616 [08:55<09:08,  1.49it/s]




 49%|████▉     | 798/1616 [08:56<07:14,  1.88it/s]




 49%|████▉     | 799/1616 [08:57<09:40,  1.41it/s]




 50%|████▉     | 800/1616 [08:57<08:06,  1.68it/s]




 50%|████▉     | 801/1616 [08:57<07:12,  1.88it/s]




 50%|████▉     | 802/1616 [08:58<07:53,  1.72it/s]




 50%|████▉     | 803/1616 [08:59<08:52,  1.53it/s]




 50%|████▉     | 804/1616 [09:00<11:51,  1.14it/s]




 50%|████▉     | 805/1616 [09:01<08:46,  1.54it/s]




 50%|████▉     | 806/1616 [09:01<08:06,  1.66it/s]




 50%|████▉     | 807/1616 [09:02<09:34,  1.41it/s]




 50%|█████     | 808/1616 [09:02<08:52,  1.52it/s]




 50%|█████     | 809/1616 [09:03<08:24,  1.60it/s]




 50%|█████     | 810/1616 [09:04<09:15,  1.45it/s]




 50%|█████     | 811/1616 [09:04<07:27,  1.80it/s]




 50%|█████     | 812/1616 [09:06<12:01,  1.11it/s]




 50%|█████     | 813/1616 [09:06<09:47,  1.37it/s]




 50%|█████     | 815/1616 [09:08<09:27,  1.41it/s]




 50%|█████     | 816/1616 [09:08<07:32,  1.77it/s]




 51%|█████     | 817/1616 [09:08<08:28,  1.57it/s]




 51%|█████     | 818/1616 [09:09<09:36,  1.39it/s]




 51%|█████     | 819/1616 [09:10<07:48,  1.70it/s]




 51%|█████     | 820/1616 [09:11<10:44,  1.23it/s]




 51%|█████     | 821/1616 [09:11<09:06,  1.46it/s]




 51%|█████     | 822/1616 [09:12<07:03,  1.88it/s]




 51%|█████     | 823/1616 [09:13<09:20,  1.41it/s]




 51%|█████     | 824/1616 [09:13<07:01,  1.88it/s]




 51%|█████     | 825/1616 [09:14<08:57,  1.47it/s]




 51%|█████     | 826/1616 [09:15<09:17,  1.42it/s]




 51%|█████     | 827/1616 [09:15<07:52,  1.67it/s]




 51%|█████     | 828/1616 [09:16<10:39,  1.23it/s]




 51%|█████▏    | 829/1616 [09:17<08:43,  1.50it/s]




 51%|█████▏    | 830/1616 [09:17<07:38,  1.71it/s]




 51%|█████▏    | 831/1616 [09:18<09:20,  1.40it/s]




 51%|█████▏    | 832/1616 [09:19<08:25,  1.55it/s]




 52%|█████▏    | 833/1616 [09:19<09:22,  1.39it/s]




 52%|█████▏    | 834/1616 [09:20<09:59,  1.30it/s]




 52%|█████▏    | 836/1616 [09:21<08:35,  1.51it/s]




 52%|█████▏    | 837/1616 [09:22<09:30,  1.37it/s]




 52%|█████▏    | 838/1616 [09:23<08:18,  1.56it/s]




 52%|█████▏    | 839/1616 [09:23<07:32,  1.72it/s]




 52%|█████▏    | 840/1616 [09:24<08:19,  1.55it/s]




 52%|█████▏    | 841/1616 [09:25<08:48,  1.47it/s]




 52%|█████▏    | 842/1616 [09:26<10:06,  1.28it/s]




 52%|█████▏    | 843/1616 [09:26<08:05,  1.59it/s]




 52%|█████▏    | 844/1616 [09:27<08:09,  1.58it/s]




 52%|█████▏    | 845/1616 [09:28<09:51,  1.30it/s]




 52%|█████▏    | 846/1616 [09:28<08:08,  1.58it/s]




 52%|█████▏    | 847/1616 [09:28<06:52,  1.86it/s]




 52%|█████▏    | 848/1616 [09:29<07:38,  1.67it/s]




 53%|█████▎    | 849/1616 [09:30<08:41,  1.47it/s]




 53%|█████▎    | 850/1616 [09:31<09:42,  1.32it/s]




 53%|█████▎    | 851/1616 [09:31<07:38,  1.67it/s]




 53%|█████▎    | 852/1616 [09:32<08:09,  1.56it/s]




 53%|█████▎    | 853/1616 [09:33<09:29,  1.34it/s]




 53%|█████▎    | 854/1616 [09:33<08:20,  1.52it/s]




 53%|█████▎    | 855/1616 [09:34<07:33,  1.68it/s]




 53%|█████▎    | 856/1616 [09:34<06:54,  1.83it/s]




 53%|█████▎    | 857/1616 [09:36<11:19,  1.12it/s]




 53%|█████▎    | 858/1616 [09:36<09:40,  1.31it/s]




 53%|█████▎    | 860/1616 [09:37<07:48,  1.61it/s]




 53%|█████▎    | 861/1616 [09:38<09:14,  1.36it/s]




 53%|█████▎    | 862/1616 [09:39<09:10,  1.37it/s]




 53%|█████▎    | 863/1616 [09:39<07:09,  1.75it/s]




 53%|█████▎    | 864/1616 [09:40<06:44,  1.86it/s]




 54%|█████▎    | 865/1616 [09:41<10:27,  1.20it/s]




 54%|█████▎    | 866/1616 [09:42<09:02,  1.38it/s]




 54%|█████▎    | 868/1616 [09:42<06:58,  1.79it/s]




 54%|█████▍    | 869/1616 [09:43<08:22,  1.49it/s]




 54%|█████▍    | 870/1616 [09:44<09:06,  1.37it/s]




 54%|█████▍    | 871/1616 [09:44<07:04,  1.75it/s]




 54%|█████▍    | 872/1616 [09:45<07:14,  1.71it/s]




 54%|█████▍    | 873/1616 [09:47<10:47,  1.15it/s]




 54%|█████▍    | 874/1616 [09:47<08:14,  1.50it/s]




 54%|█████▍    | 875/1616 [09:47<06:55,  1.78it/s]




 54%|█████▍    | 876/1616 [09:48<07:21,  1.68it/s]




 54%|█████▍    | 877/1616 [09:49<08:17,  1.48it/s]




 54%|█████▍    | 878/1616 [09:50<09:25,  1.31it/s]




 54%|█████▍    | 880/1616 [09:51<07:52,  1.56it/s]




 55%|█████▍    | 881/1616 [09:52<10:06,  1.21it/s]




 55%|█████▍    | 883/1616 [09:52<06:41,  1.82it/s]




 55%|█████▍    | 884/1616 [09:53<07:01,  1.74it/s]




 55%|█████▍    | 885/1616 [09:54<08:08,  1.50it/s]




 55%|█████▍    | 886/1616 [09:55<09:56,  1.22it/s]




 55%|█████▍    | 887/1616 [09:55<07:51,  1.55it/s]




 55%|█████▍    | 888/1616 [09:56<08:55,  1.36it/s]




 55%|█████▌    | 889/1616 [09:57<09:28,  1.28it/s]




 55%|█████▌    | 890/1616 [09:58<08:46,  1.38it/s]




 55%|█████▌    | 891/1616 [09:58<06:54,  1.75it/s]




 55%|█████▌    | 892/1616 [09:58<05:57,  2.03it/s]




 55%|█████▌    | 893/1616 [09:59<07:23,  1.63it/s]




 55%|█████▌    | 894/1616 [10:00<09:35,  1.25it/s]




 55%|█████▌    | 895/1616 [10:01<07:39,  1.57it/s]




 55%|█████▌    | 896/1616 [10:02<08:31,  1.41it/s]




 56%|█████▌    | 897/1616 [10:02<08:45,  1.37it/s]




 56%|█████▌    | 898/1616 [10:03<09:14,  1.29it/s]




 56%|█████▌    | 900/1616 [10:04<06:11,  1.93it/s]




 56%|█████▌    | 901/1616 [10:05<07:27,  1.60it/s]




 56%|█████▌    | 902/1616 [10:06<09:17,  1.28it/s]




 56%|█████▌    | 904/1616 [10:07<07:27,  1.59it/s]




 56%|█████▌    | 905/1616 [10:08<07:55,  1.50it/s]

 56%|█████▌    | 906/1616 [10:09<09:53,  1.20it/s]




 56%|█████▌    | 907/1616 [10:09<08:03,  1.47it/s]




 56%|█████▌    | 908/1616 [10:10<07:56,  1.49it/s]




 56%|█████▋    | 909/1616 [10:10<06:58,  1.69it/s]




 56%|█████▋    | 910/1616 [10:11<07:50,  1.50it/s]




 56%|█████▋    | 911/1616 [10:12<08:16,  1.42it/s]




 56%|█████▋    | 912/1616 [10:12<06:56,  1.69it/s]




 56%|█████▋    | 913/1616 [10:13<07:07,  1.64it/s]




 57%|█████▋    | 914/1616 [10:15<11:07,  1.05it/s]




 57%|█████▋    | 915/1616 [10:15<08:48,  1.33it/s]




 57%|█████▋    | 916/1616 [10:15<07:17,  1.60it/s]




 57%|█████▋    | 918/1616 [10:16<06:50,  1.70it/s]




 57%|█████▋    | 919/1616 [10:17<07:30,  1.55it/s]




 57%|█████▋    | 920/1616 [10:17<06:40,  1.74it/s]




 57%|█████▋    | 921/1616 [10:18<06:47,  1.71it/s]




 57%|█████▋    | 922/1616 [10:20<10:38,  1.09it/s]




 57%|█████▋    | 923/1616 [10:20<08:43,  1.32it/s]




 57%|█████▋    | 924/1616 [10:20<06:35,  1.75it/s]




 57%|█████▋    | 925/1616 [10:20<05:06,  2.26it/s]




 57%|█████▋    | 926/1616 [10:21<06:50,  1.68it/s]




 57%|█████▋    | 927/1616 [10:22<08:31,  1.35it/s]




 57%|█████▋    | 929/1616 [10:23<06:40,  1.72it/s]




 58%|█████▊    | 930/1616 [10:25<10:53,  1.05it/s]




 58%|█████▊    | 931/1616 [10:26<08:47,  1.30it/s]




 58%|█████▊    | 932/1616 [10:26<07:01,  1.62it/s]




 58%|█████▊    | 933/1616 [10:26<06:05,  1.87it/s]




 58%|█████▊    | 934/1616 [10:27<06:58,  1.63it/s]




 58%|█████▊    | 935/1616 [10:28<08:07,  1.40it/s]




 58%|█████▊    | 936/1616 [10:28<06:26,  1.76it/s]




 58%|█████▊    | 937/1616 [10:29<05:51,  1.93it/s]




 58%|█████▊    | 938/1616 [10:31<10:47,  1.05it/s]




 58%|█████▊    | 939/1616 [10:31<08:56,  1.26it/s]




 58%|█████▊    | 940/1616 [10:31<07:05,  1.59it/s]




 58%|█████▊    | 941/1616 [10:32<06:27,  1.74it/s]




 58%|█████▊    | 942/1616 [10:32<06:39,  1.69it/s]




 58%|█████▊    | 943/1616 [10:33<07:31,  1.49it/s]




 58%|█████▊    | 944/1616 [10:33<06:00,  1.86it/s]




 58%|█████▊    | 945/1616 [10:34<05:30,  2.03it/s]




 59%|█████▊    | 946/1616 [10:36<10:13,  1.09it/s]




 59%|█████▊    | 947/1616 [10:36<09:03,  1.23it/s]




 59%|█████▊    | 949/1616 [10:37<06:32,  1.70it/s]




 59%|█████▉    | 950/1616 [10:37<06:17,  1.76it/s]




 59%|█████▉    | 951/1616 [10:39<07:59,  1.39it/s]




 59%|█████▉    | 952/1616 [10:39<07:16,  1.52it/s]




 59%|█████▉    | 953/1616 [10:40<06:53,  1.60it/s]




 59%|█████▉    | 954/1616 [10:41<08:56,  1.23it/s]




 59%|█████▉    | 955/1616 [10:41<07:50,  1.40it/s]




 59%|█████▉    | 956/1616 [10:42<07:22,  1.49it/s]




 59%|█████▉    | 957/1616 [10:42<07:11,  1.53it/s]




 59%|█████▉    | 958/1616 [10:43<05:34,  1.97it/s]




 59%|█████▉    | 959/1616 [10:44<08:42,  1.26it/s]




 59%|█████▉    | 960/1616 [10:45<07:27,  1.47it/s]




 59%|█████▉    | 961/1616 [10:45<06:42,  1.63it/s]




 60%|█████▉    | 962/1616 [10:46<07:44,  1.41it/s]




 60%|█████▉    | 963/1616 [10:46<07:04,  1.54it/s]




 60%|█████▉    | 964/1616 [10:47<07:04,  1.54it/s]




 60%|█████▉    | 965/1616 [10:48<07:38,  1.42it/s]




 60%|█████▉    | 967/1616 [10:50<08:17,  1.30it/s]




 60%|█████▉    | 968/1616 [10:50<06:31,  1.66it/s]




 60%|█████▉    | 969/1616 [10:50<06:10,  1.75it/s]




 60%|██████    | 970/1616 [10:51<07:01,  1.53it/s]




 60%|██████    | 971/1616 [10:52<07:22,  1.46it/s]




 60%|██████    | 972/1616 [10:52<07:03,  1.52it/s]




 60%|██████    | 973/1616 [10:53<06:54,  1.55it/s]




 60%|██████    | 974/1616 [10:54<06:41,  1.60it/s]




 60%|██████    | 975/1616 [10:55<08:40,  1.23it/s]




 60%|██████    | 976/1616 [10:55<06:29,  1.65it/s]




 60%|██████    | 977/1616 [10:55<05:32,  1.92it/s]




 61%|██████    | 978/1616 [10:57<09:28,  1.12it/s]




 61%|██████    | 979/1616 [10:57<07:58,  1.33it/s]




 61%|██████    | 980/1616 [10:58<07:06,  1.49it/s]




 61%|██████    | 981/1616 [10:58<06:25,  1.65it/s]




 61%|██████    | 982/1616 [10:59<06:01,  1.75it/s]




 61%|██████    | 983/1616 [11:00<09:10,  1.15it/s]




 61%|██████    | 985/1616 [11:01<05:51,  1.79it/s]




 61%|██████    | 986/1616 [11:02<08:27,  1.24it/s]




 61%|██████    | 987/1616 [11:03<07:05,  1.48it/s]




 61%|██████    | 988/1616 [11:03<06:32,  1.60it/s]




 61%|██████    | 989/1616 [11:04<06:02,  1.73it/s]




 61%|██████▏   | 990/1616 [11:04<06:17,  1.66it/s]




 61%|██████▏   | 991/1616 [11:06<08:20,  1.25it/s]




 61%|██████▏   | 992/1616 [11:06<06:19,  1.65it/s]




 61%|██████▏   | 993/1616 [11:06<05:28,  1.90it/s]




 62%|██████▏   | 994/1616 [11:08<08:13,  1.26it/s]




 62%|██████▏   | 995/1616 [11:08<06:43,  1.54it/s]




 62%|██████▏   | 996/1616 [11:08<05:50,  1.77it/s]




 62%|██████▏   | 997/1616 [11:09<06:46,  1.52it/s]




 62%|██████▏   | 998/1616 [11:10<06:31,  1.58it/s]




 62%|██████▏   | 999/1616 [11:11<09:03,  1.14it/s]




 62%|██████▏   | 1000/1616 [11:11<07:12,  1.42it/s]




 62%|██████▏   | 1001/1616 [11:12<05:41,  1.80it/s]




 62%|██████▏   | 1002/1616 [11:13<08:26,  1.21it/s]




 62%|██████▏   | 1004/1616 [11:14<06:07,  1.66it/s]




 62%|██████▏   | 1005/1616 [11:15<08:00,  1.27it/s]




 62%|██████▏   | 1006/1616 [11:15<06:13,  1.63it/s]




 62%|██████▏   | 1007/1616 [11:17<08:38,  1.17it/s]




 62%|██████▏   | 1008/1616 [11:17<06:46,  1.50it/s]




 62%|██████▏   | 1009/1616 [11:17<06:14,  1.62it/s]




 62%|██████▎   | 1010/1616 [11:18<06:56,  1.46it/s]




 63%|██████▎   | 1011/1616 [11:18<05:24,  1.86it/s]




 63%|██████▎   | 1012/1616 [11:19<05:51,  1.72it/s]




 63%|██████▎   | 1013/1616 [11:20<08:07,  1.24it/s]




 63%|██████▎   | 1014/1616 [11:21<06:39,  1.51it/s]




 63%|██████▎   | 1015/1616 [11:22<08:01,  1.25it/s]




 63%|██████▎   | 1016/1616 [11:22<07:19,  1.37it/s]




 63%|██████▎   | 1017/1616 [11:23<05:37,  1.78it/s]




 63%|██████▎   | 1018/1616 [11:24<06:33,  1.52it/s]




 63%|██████▎   | 1019/1616 [11:24<05:04,  1.96it/s]




 63%|██████▎   | 1020/1616 [11:25<06:06,  1.63it/s]




 63%|██████▎   | 1021/1616 [11:26<07:56,  1.25it/s]




 63%|██████▎   | 1022/1616 [11:26<06:34,  1.50it/s]




 63%|██████▎   | 1023/1616 [11:27<08:13,  1.20it/s]




 63%|██████▎   | 1024/1616 [11:28<07:06,  1.39it/s]




 63%|██████▎   | 1025/1616 [11:28<05:50,  1.69it/s]




 63%|██████▎   | 1026/1616 [11:29<05:55,  1.66it/s]




 64%|██████▎   | 1027/1616 [11:29<04:44,  2.07it/s]

 64%|██████▎   | 1028/1616 [11:30<06:08,  1.60it/s]




 64%|██████▎   | 1029/1616 [11:31<08:34,  1.14it/s]




 64%|██████▍   | 1031/1616 [11:33<07:14,  1.35it/s]




 64%|██████▍   | 1032/1616 [11:33<07:42,  1.26it/s]




 64%|██████▍   | 1033/1616 [11:34<06:31,  1.49it/s]




 64%|██████▍   | 1034/1616 [11:34<05:21,  1.81it/s]




 64%|██████▍   | 1036/1616 [11:35<05:21,  1.80it/s]




 64%|██████▍   | 1037/1616 [11:37<08:08,  1.18it/s]




 64%|██████▍   | 1039/1616 [11:38<06:30,  1.48it/s]




 64%|██████▍   | 1040/1616 [11:39<07:47,  1.23it/s]




 64%|██████▍   | 1041/1616 [11:39<06:13,  1.54it/s]




 65%|██████▍   | 1043/1616 [11:39<04:08,  2.30it/s]




 65%|██████▍   | 1044/1616 [11:40<04:52,  1.96it/s]




 65%|██████▍   | 1045/1616 [11:42<08:12,  1.16it/s]




 65%|██████▍   | 1047/1616 [11:43<06:25,  1.48it/s]




 65%|██████▍   | 1048/1616 [11:44<07:48,  1.21it/s]




 65%|██████▍   | 1049/1616 [11:45<06:50,  1.38it/s]




 65%|██████▍   | 1050/1616 [11:45<06:19,  1.49it/s]




 65%|██████▌   | 1052/1616 [11:46<04:30,  2.08it/s]




 65%|██████▌   | 1053/1616 [11:47<07:14,  1.30it/s]




 65%|██████▌   | 1054/1616 [11:48<05:39,  1.66it/s]




 65%|██████▌   | 1055/1616 [11:48<05:28,  1.71it/s]




 65%|██████▌   | 1056/1616 [11:50<09:11,  1.02it/s]




 65%|██████▌   | 1057/1616 [11:50<06:56,  1.34it/s]




 65%|██████▌   | 1058/1616 [11:50<05:25,  1.71it/s]




 66%|██████▌   | 1059/1616 [11:51<05:04,  1.83it/s]




 66%|██████▌   | 1060/1616 [11:51<03:54,  2.37it/s]




 66%|██████▌   | 1061/1616 [11:53<07:36,  1.22it/s]




 66%|██████▌   | 1062/1616 [11:53<05:37,  1.64it/s]




 66%|██████▌   | 1063/1616 [11:53<04:51,  1.90it/s]




 66%|██████▌   | 1064/1616 [11:55<08:57,  1.03it/s]




 66%|██████▌   | 1065/1616 [11:55<07:00,  1.31it/s]




 66%|██████▌   | 1066/1616 [11:56<05:22,  1.71it/s]




 66%|██████▌   | 1067/1616 [11:56<04:51,  1.88it/s]




 66%|██████▌   | 1068/1616 [11:56<03:56,  2.32it/s]




 66%|██████▌   | 1069/1616 [11:58<07:45,  1.18it/s]




 66%|██████▌   | 1070/1616 [11:58<05:56,  1.53it/s]




 66%|██████▋   | 1072/1616 [12:01<07:56,  1.14it/s]




 66%|██████▋   | 1073/1616 [12:01<06:35,  1.37it/s]




 66%|██████▋   | 1074/1616 [12:01<05:41,  1.59it/s]




 67%|██████▋   | 1075/1616 [12:01<04:34,  1.97it/s]




 67%|██████▋   | 1077/1616 [12:03<06:30,  1.38it/s]




 67%|██████▋   | 1078/1616 [12:04<05:45,  1.56it/s]




 67%|██████▋   | 1080/1616 [12:06<07:07,  1.25it/s]




 67%|██████▋   | 1081/1616 [12:06<06:23,  1.39it/s]




 67%|██████▋   | 1082/1616 [12:07<05:25,  1.64it/s]




 67%|██████▋   | 1083/1616 [12:07<04:25,  2.01it/s]




 67%|██████▋   | 1085/1616 [12:09<06:24,  1.38it/s]




 67%|██████▋   | 1086/1616 [12:09<05:32,  1.59it/s]




 67%|██████▋   | 1088/1616 [12:11<06:40,  1.32it/s]




 67%|██████▋   | 1089/1616 [12:11<06:07,  1.43it/s]




 67%|██████▋   | 1090/1616 [12:12<05:32,  1.58it/s]




 68%|██████▊   | 1091/1616 [12:12<04:24,  1.99it/s]




 68%|██████▊   | 1092/1616 [12:12<03:56,  2.21it/s]




 68%|██████▊   | 1093/1616 [12:14<07:19,  1.19it/s]




 68%|██████▊   | 1095/1616 [12:15<04:42,  1.85it/s]




 68%|██████▊   | 1096/1616 [12:16<07:08,  1.21it/s]




 68%|██████▊   | 1097/1616 [12:17<07:31,  1.15it/s]




 68%|██████▊   | 1098/1616 [12:18<07:09,  1.21it/s]




 68%|██████▊   | 1099/1616 [12:18<05:28,  1.57it/s]




 68%|██████▊   | 1101/1616 [12:20<05:49,  1.47it/s]




 68%|██████▊   | 1102/1616 [12:20<04:51,  1.76it/s]




 68%|██████▊   | 1103/1616 [12:20<03:56,  2.17it/s]




 68%|██████▊   | 1104/1616 [12:22<07:17,  1.17it/s]




 68%|██████▊   | 1105/1616 [12:23<06:53,  1.23it/s]




 68%|██████▊   | 1106/1616 [12:23<06:16,  1.35it/s]




 69%|██████▊   | 1107/1616 [12:23<05:08,  1.65it/s]




 69%|██████▊   | 1109/1616 [12:25<05:29,  1.54it/s]




 69%|██████▊   | 1110/1616 [12:25<04:25,  1.90it/s]




 69%|██████▉   | 1111/1616 [12:25<03:57,  2.12it/s]




 69%|██████▉   | 1112/1616 [12:27<07:09,  1.17it/s]




 69%|██████▉   | 1113/1616 [12:28<06:21,  1.32it/s]




 69%|██████▉   | 1114/1616 [12:28<05:46,  1.45it/s]




 69%|██████▉   | 1115/1616 [12:29<05:33,  1.50it/s]




 69%|██████▉   | 1116/1616 [12:29<04:17,  1.94it/s]




 69%|██████▉   | 1117/1616 [12:30<05:30,  1.51it/s]




 69%|██████▉   | 1118/1616 [12:30<04:07,  2.01it/s]




 69%|██████▉   | 1119/1616 [12:31<04:25,  1.87it/s]




 69%|██████▉   | 1120/1616 [12:32<07:07,  1.16it/s]




 69%|██████▉   | 1121/1616 [12:33<06:49,  1.21it/s]




 69%|██████▉   | 1122/1616 [12:33<05:37,  1.46it/s]




 69%|██████▉   | 1123/1616 [12:34<06:05,  1.35it/s]




 70%|██████▉   | 1124/1616 [12:34<04:41,  1.75it/s]




 70%|██████▉   | 1125/1616 [12:36<06:28,  1.27it/s]




 70%|██████▉   | 1126/1616 [12:36<04:47,  1.70it/s]




 70%|██████▉   | 1127/1616 [12:36<04:01,  2.03it/s]




 70%|██████▉   | 1128/1616 [12:38<07:05,  1.15it/s]




 70%|██████▉   | 1129/1616 [12:38<06:13,  1.30it/s]




 70%|██████▉   | 1131/1616 [12:40<05:38,  1.43it/s]




 70%|███████   | 1132/1616 [12:40<04:43,  1.71it/s]




 70%|███████   | 1133/1616 [12:41<06:06,  1.32it/s]




 70%|███████   | 1135/1616 [12:42<04:27,  1.80it/s]




 70%|███████   | 1136/1616 [12:43<06:34,  1.22it/s]




 70%|███████   | 1137/1616 [12:44<05:19,  1.50it/s]




 70%|███████   | 1139/1616 [12:45<05:54,  1.34it/s]




 71%|███████   | 1141/1616 [12:46<04:57,  1.60it/s]




 71%|███████   | 1142/1616 [12:46<04:13,  1.87it/s]




 71%|███████   | 1143/1616 [12:47<04:22,  1.80it/s]




 71%|███████   | 1144/1616 [12:49<06:22,  1.23it/s]




 71%|███████   | 1145/1616 [12:49<05:44,  1.37it/s]




 71%|███████   | 1146/1616 [12:50<05:10,  1.52it/s]




 71%|███████   | 1147/1616 [12:51<06:09,  1.27it/s]




 71%|███████   | 1149/1616 [12:52<05:24,  1.44it/s]




 71%|███████   | 1151/1616 [12:52<04:14,  1.83it/s]




 71%|███████▏  | 1152/1616 [12:54<05:22,  1.44it/s]




 71%|███████▏  | 1153/1616 [12:54<05:10,  1.49it/s]




 71%|███████▏  | 1154/1616 [12:55<04:51,  1.58it/s]




 71%|███████▏  | 1155/1616 [12:56<06:06,  1.26it/s]




 72%|███████▏  | 1156/1616 [12:56<04:38,  1.65it/s]




 72%|███████▏  | 1157/1616 [12:57<05:01,  1.52it/s]




 72%|███████▏  | 1158/1616 [12:57<04:16,  1.78it/s]




 72%|███████▏  | 1159/1616 [12:58<04:03,  1.88it/s]




 72%|███████▏  | 1160/1616 [12:59<05:15,  1.45it/s]




 72%|███████▏  | 1161/1616 [12:59<05:13,  1.45it/s]




 72%|███████▏  | 1162/1616 [13:00<05:08,  1.47it/s]

 72%|███████▏  | 1163/1616 [13:01<06:36,  1.14it/s]




 72%|███████▏  | 1165/1616 [13:02<04:58,  1.51it/s]




 72%|███████▏  | 1166/1616 [13:03<04:17,  1.75it/s]




 72%|███████▏  | 1167/1616 [13:03<04:07,  1.82it/s]




 72%|███████▏  | 1168/1616 [13:04<04:31,  1.65it/s]




 72%|███████▏  | 1169/1616 [13:05<05:14,  1.42it/s]




 72%|███████▏  | 1170/1616 [13:06<05:57,  1.25it/s]




 72%|███████▏  | 1171/1616 [13:07<06:18,  1.18it/s]




 73%|███████▎  | 1173/1616 [13:07<04:32,  1.63it/s]




 73%|███████▎  | 1174/1616 [13:08<04:41,  1.57it/s]




 73%|███████▎  | 1175/1616 [13:08<03:58,  1.85it/s]




 73%|███████▎  | 1176/1616 [13:09<04:40,  1.57it/s]




 73%|███████▎  | 1177/1616 [13:10<05:20,  1.37it/s]




 73%|███████▎  | 1178/1616 [13:11<05:16,  1.39it/s]




 73%|███████▎  | 1179/1616 [13:12<05:58,  1.22it/s]




 73%|███████▎  | 1180/1616 [13:12<04:45,  1.53it/s]




 73%|███████▎  | 1181/1616 [13:13<04:38,  1.56it/s]




 73%|███████▎  | 1182/1616 [13:13<03:49,  1.89it/s]




 73%|███████▎  | 1183/1616 [13:14<05:13,  1.38it/s]




 73%|███████▎  | 1184/1616 [13:15<04:25,  1.63it/s]




 73%|███████▎  | 1185/1616 [13:16<06:15,  1.15it/s]




 73%|███████▎  | 1187/1616 [13:17<05:00,  1.43it/s]




 74%|███████▎  | 1188/1616 [13:18<04:35,  1.55it/s]




 74%|███████▎  | 1189/1616 [13:19<04:59,  1.42it/s]




 74%|███████▎  | 1190/1616 [13:19<04:07,  1.72it/s]




 74%|███████▎  | 1191/1616 [13:20<05:04,  1.39it/s]




 74%|███████▍  | 1192/1616 [13:20<04:26,  1.59it/s]




 74%|███████▍  | 1193/1616 [13:21<05:37,  1.25it/s]




 74%|███████▍  | 1195/1616 [13:23<05:34,  1.26it/s]




 74%|███████▍  | 1196/1616 [13:23<04:29,  1.56it/s]




 74%|███████▍  | 1197/1616 [13:24<04:09,  1.68it/s]




 74%|███████▍  | 1198/1616 [13:24<04:04,  1.71it/s]




 74%|███████▍  | 1199/1616 [13:25<04:41,  1.48it/s]




 74%|███████▍  | 1200/1616 [13:26<04:18,  1.61it/s]




 74%|███████▍  | 1201/1616 [13:27<05:27,  1.27it/s]




 74%|███████▍  | 1203/1616 [13:28<05:11,  1.32it/s]




 75%|███████▍  | 1204/1616 [13:29<04:22,  1.57it/s]




 75%|███████▍  | 1205/1616 [13:29<03:51,  1.77it/s]




 75%|███████▍  | 1206/1616 [13:30<03:56,  1.73it/s]




 75%|███████▍  | 1207/1616 [13:30<04:14,  1.61it/s]




 75%|███████▍  | 1208/1616 [13:31<04:18,  1.58it/s]




 75%|███████▍  | 1209/1616 [13:32<05:15,  1.29it/s]




 75%|███████▍  | 1211/1616 [13:33<05:02,  1.34it/s]




 75%|███████▌  | 1212/1616 [13:34<05:05,  1.32it/s]




 75%|███████▌  | 1214/1616 [13:35<03:32,  1.89it/s]




 75%|███████▌  | 1215/1616 [13:36<04:31,  1.48it/s]




 75%|███████▌  | 1216/1616 [13:36<04:28,  1.49it/s]




 75%|███████▌  | 1217/1616 [13:37<04:26,  1.50it/s]




 75%|███████▌  | 1218/1616 [13:38<04:23,  1.51it/s]




 75%|███████▌  | 1219/1616 [13:39<05:06,  1.30it/s]




 75%|███████▌  | 1220/1616 [13:40<05:08,  1.28it/s]




 76%|███████▌  | 1221/1616 [13:40<04:14,  1.55it/s]




 76%|███████▌  | 1222/1616 [13:40<03:50,  1.71it/s]




 76%|███████▌  | 1223/1616 [13:41<04:35,  1.42it/s]




 76%|███████▌  | 1224/1616 [13:42<03:54,  1.67it/s]




 76%|███████▌  | 1225/1616 [13:42<04:04,  1.60it/s]




 76%|███████▌  | 1226/1616 [13:43<04:13,  1.54it/s]




 76%|███████▌  | 1227/1616 [13:44<04:39,  1.39it/s]




 76%|███████▌  | 1228/1616 [13:45<04:45,  1.36it/s]




 76%|███████▌  | 1229/1616 [13:45<04:38,  1.39it/s]




 76%|███████▌  | 1230/1616 [13:46<03:43,  1.73it/s]




 76%|███████▌  | 1231/1616 [13:46<03:53,  1.65it/s]




 76%|███████▌  | 1232/1616 [13:47<03:46,  1.70it/s]




 76%|███████▋  | 1233/1616 [13:48<03:59,  1.60it/s]




 76%|███████▋  | 1234/1616 [13:48<04:12,  1.51it/s]




 76%|███████▋  | 1235/1616 [13:49<04:46,  1.33it/s]




 76%|███████▋  | 1236/1616 [13:51<05:46,  1.10it/s]




 77%|███████▋  | 1237/1616 [13:51<04:48,  1.31it/s]




 77%|███████▋  | 1238/1616 [13:52<04:19,  1.46it/s]




 77%|███████▋  | 1239/1616 [13:52<04:32,  1.38it/s]




 77%|███████▋  | 1240/1616 [13:53<03:26,  1.82it/s]




 77%|███████▋  | 1241/1616 [13:54<04:42,  1.33it/s]




 77%|███████▋  | 1243/1616 [13:55<04:02,  1.54it/s]




 77%|███████▋  | 1244/1616 [13:56<05:22,  1.16it/s]




 77%|███████▋  | 1245/1616 [13:57<04:22,  1.41it/s]




 77%|███████▋  | 1246/1616 [13:57<03:47,  1.62it/s]




 77%|███████▋  | 1247/1616 [13:58<03:45,  1.64it/s]




 77%|███████▋  | 1248/1616 [13:58<03:20,  1.84it/s]




 77%|███████▋  | 1249/1616 [13:59<04:25,  1.38it/s]




 77%|███████▋  | 1250/1616 [13:59<03:33,  1.71it/s]




 77%|███████▋  | 1251/1616 [14:00<03:58,  1.53it/s]




 77%|███████▋  | 1252/1616 [14:02<05:27,  1.11it/s]




 78%|███████▊  | 1253/1616 [14:02<04:43,  1.28it/s]




 78%|███████▊  | 1255/1616 [14:03<03:12,  1.87it/s]




 78%|███████▊  | 1256/1616 [14:04<03:43,  1.61it/s]




 78%|███████▊  | 1257/1616 [14:04<03:55,  1.53it/s]




 78%|███████▊  | 1258/1616 [14:05<03:55,  1.52it/s]




 78%|███████▊  | 1259/1616 [14:05<03:41,  1.61it/s]




 78%|███████▊  | 1260/1616 [14:07<04:59,  1.19it/s]




 78%|███████▊  | 1261/1616 [14:07<04:33,  1.30it/s]




 78%|███████▊  | 1262/1616 [14:08<03:26,  1.71it/s]




 78%|███████▊  | 1263/1616 [14:08<03:15,  1.80it/s]




 78%|███████▊  | 1264/1616 [14:09<03:40,  1.60it/s]




 78%|███████▊  | 1265/1616 [14:10<04:35,  1.28it/s]




 78%|███████▊  | 1266/1616 [14:10<03:25,  1.70it/s]




 78%|███████▊  | 1267/1616 [14:11<03:28,  1.67it/s]




 78%|███████▊  | 1268/1616 [14:12<05:19,  1.09it/s]




 79%|███████▊  | 1269/1616 [14:13<04:02,  1.43it/s]




 79%|███████▊  | 1270/1616 [14:13<03:22,  1.71it/s]




 79%|███████▊  | 1271/1616 [14:14<03:27,  1.66it/s]




 79%|███████▊  | 1272/1616 [14:14<03:56,  1.46it/s]




 79%|███████▉  | 1273/1616 [14:15<04:19,  1.32it/s]




 79%|███████▉  | 1275/1616 [14:16<03:29,  1.63it/s]




 79%|███████▉  | 1276/1616 [14:18<04:52,  1.16it/s]




 79%|███████▉  | 1277/1616 [14:18<03:59,  1.41it/s]




 79%|███████▉  | 1278/1616 [14:18<03:05,  1.82it/s]




 79%|███████▉  | 1279/1616 [14:19<03:13,  1.74it/s]




 79%|███████▉  | 1280/1616 [14:20<03:38,  1.54it/s]




 79%|███████▉  | 1281/1616 [14:21<04:02,  1.38it/s]




 79%|███████▉  | 1283/1616 [14:22<03:35,  1.55it/s]




 79%|███████▉  | 1284/1616 [14:23<04:16,  1.29it/s]




 80%|███████▉  | 1285/1616 [14:24<04:32,  1.22it/s]




 80%|███████▉  | 1286/1616 [14:24<03:47,  1.45it/s]




 80%|███████▉  | 1287/1616 [14:24<02:58,  1.84it/s]




 80%|███████▉  | 1288/1616 [14:25<03:18,  1.66it/s]

 80%|███████▉  | 1289/1616 [14:26<03:38,  1.50it/s]




 80%|███████▉  | 1290/1616 [14:26<03:14,  1.67it/s]




 80%|███████▉  | 1291/1616 [14:27<03:45,  1.44it/s]




 80%|███████▉  | 1292/1616 [14:29<05:00,  1.08it/s]




 80%|████████  | 1293/1616 [14:29<04:03,  1.33it/s]




 80%|████████  | 1294/1616 [14:29<03:22,  1.59it/s]




 80%|████████  | 1295/1616 [14:30<02:59,  1.79it/s]




 80%|████████  | 1296/1616 [14:31<03:12,  1.66it/s]




 80%|████████  | 1297/1616 [14:31<02:56,  1.80it/s]




 80%|████████  | 1298/1616 [14:32<03:09,  1.67it/s]




 80%|████████  | 1299/1616 [14:33<03:25,  1.54it/s]




 80%|████████  | 1300/1616 [14:34<04:38,  1.14it/s]




 81%|████████  | 1301/1616 [14:34<03:47,  1.38it/s]




 81%|████████  | 1302/1616 [14:35<03:04,  1.70it/s]




 81%|████████  | 1303/1616 [14:35<03:08,  1.66it/s]




 81%|████████  | 1304/1616 [14:36<03:33,  1.46it/s]




 81%|████████  | 1305/1616 [14:36<02:42,  1.91it/s]




 81%|████████  | 1306/1616 [14:37<02:51,  1.81it/s]




 81%|████████  | 1307/1616 [14:38<03:13,  1.59it/s]




 81%|████████  | 1308/1616 [14:39<04:19,  1.19it/s]




 81%|████████  | 1309/1616 [14:40<04:03,  1.26it/s]




 81%|████████  | 1311/1616 [14:41<03:17,  1.55it/s]




 81%|████████  | 1312/1616 [14:42<03:56,  1.29it/s]




 81%|████████▏ | 1313/1616 [14:42<03:17,  1.54it/s]




 81%|████████▏ | 1315/1616 [14:43<02:56,  1.70it/s]




 81%|████████▏ | 1316/1616 [14:44<03:53,  1.28it/s]




 81%|████████▏ | 1317/1616 [14:45<03:19,  1.50it/s]




 82%|████████▏ | 1318/1616 [14:45<02:59,  1.66it/s]




 82%|████████▏ | 1319/1616 [14:46<03:10,  1.56it/s]




 82%|████████▏ | 1320/1616 [14:47<03:58,  1.24it/s]




 82%|████████▏ | 1321/1616 [14:47<02:59,  1.64it/s]




 82%|████████▏ | 1322/1616 [14:48<02:28,  1.98it/s]




 82%|████████▏ | 1323/1616 [14:49<03:04,  1.58it/s]




 82%|████████▏ | 1324/1616 [14:50<03:38,  1.34it/s]




 82%|████████▏ | 1325/1616 [14:50<03:12,  1.51it/s]




 82%|████████▏ | 1326/1616 [14:50<02:44,  1.76it/s]




 82%|████████▏ | 1327/1616 [14:51<03:09,  1.53it/s]




 82%|████████▏ | 1328/1616 [14:53<04:19,  1.11it/s]




 82%|████████▏ | 1330/1616 [14:53<02:50,  1.68it/s]




 82%|████████▏ | 1331/1616 [14:54<03:16,  1.45it/s]




 82%|████████▏ | 1332/1616 [14:55<03:42,  1.27it/s]




 82%|████████▏ | 1333/1616 [14:55<02:51,  1.65it/s]




 83%|████████▎ | 1334/1616 [14:56<02:36,  1.81it/s]




 83%|████████▎ | 1335/1616 [14:57<03:13,  1.45it/s]




 83%|████████▎ | 1336/1616 [14:58<04:22,  1.07it/s]




 83%|████████▎ | 1337/1616 [14:59<03:23,  1.37it/s]




 83%|████████▎ | 1338/1616 [14:59<02:44,  1.69it/s]




 83%|████████▎ | 1339/1616 [15:00<03:34,  1.29it/s]




 83%|████████▎ | 1340/1616 [15:01<03:25,  1.34it/s]




 83%|████████▎ | 1342/1616 [15:01<02:22,  1.93it/s]




 83%|████████▎ | 1343/1616 [15:02<02:55,  1.56it/s]




 83%|████████▎ | 1344/1616 [15:04<03:53,  1.17it/s]




 83%|████████▎ | 1346/1616 [15:04<02:51,  1.57it/s]




 83%|████████▎ | 1347/1616 [15:05<03:05,  1.45it/s]




 83%|████████▎ | 1348/1616 [15:06<02:56,  1.52it/s]




 83%|████████▎ | 1349/1616 [15:06<02:30,  1.77it/s]




 84%|████████▎ | 1350/1616 [15:06<02:09,  2.05it/s]




 84%|████████▎ | 1351/1616 [15:07<02:54,  1.51it/s]




 84%|████████▎ | 1352/1616 [15:09<03:57,  1.11it/s]




 84%|████████▍ | 1354/1616 [15:10<02:49,  1.55it/s]




 84%|████████▍ | 1355/1616 [15:11<03:14,  1.34it/s]




 84%|████████▍ | 1356/1616 [15:11<02:35,  1.67it/s]




 84%|████████▍ | 1357/1616 [15:12<02:45,  1.57it/s]




 84%|████████▍ | 1358/1616 [15:12<02:19,  1.85it/s]




 84%|████████▍ | 1359/1616 [15:13<02:56,  1.46it/s]




 84%|████████▍ | 1360/1616 [15:14<03:53,  1.09it/s]




 84%|████████▍ | 1362/1616 [15:16<03:12,  1.32it/s]




 84%|████████▍ | 1363/1616 [15:16<02:55,  1.44it/s]




 84%|████████▍ | 1364/1616 [15:16<02:25,  1.74it/s]




 84%|████████▍ | 1365/1616 [15:17<02:42,  1.54it/s]




 85%|████████▍ | 1366/1616 [15:18<02:28,  1.69it/s]




 85%|████████▍ | 1367/1616 [15:18<02:45,  1.50it/s]




 85%|████████▍ | 1368/1616 [15:20<03:20,  1.24it/s]




 85%|████████▍ | 1369/1616 [15:20<02:39,  1.54it/s]




 85%|████████▍ | 1370/1616 [15:21<03:20,  1.22it/s]




 85%|████████▍ | 1371/1616 [15:21<02:41,  1.52it/s]




 85%|████████▍ | 1372/1616 [15:22<02:12,  1.84it/s]




 85%|████████▍ | 1373/1616 [15:22<02:33,  1.58it/s]




 85%|████████▌ | 1374/1616 [15:23<02:09,  1.87it/s]




 85%|████████▌ | 1375/1616 [15:24<02:40,  1.50it/s]




 85%|████████▌ | 1376/1616 [15:25<03:07,  1.28it/s]




 85%|████████▌ | 1377/1616 [15:25<02:25,  1.64it/s]




 85%|████████▌ | 1378/1616 [15:26<03:12,  1.24it/s]




 85%|████████▌ | 1379/1616 [15:27<03:20,  1.18it/s]




 85%|████████▌ | 1381/1616 [15:28<02:10,  1.81it/s]




 86%|████████▌ | 1382/1616 [15:29<02:32,  1.53it/s]




 86%|████████▌ | 1383/1616 [15:29<02:26,  1.59it/s]




 86%|████████▌ | 1384/1616 [15:30<02:32,  1.52it/s]




 86%|████████▌ | 1385/1616 [15:31<02:45,  1.40it/s]




 86%|████████▌ | 1386/1616 [15:31<02:45,  1.39it/s]




 86%|████████▌ | 1387/1616 [15:32<02:53,  1.32it/s]




 86%|████████▌ | 1388/1616 [15:33<02:47,  1.36it/s]




 86%|████████▌ | 1389/1616 [15:33<02:13,  1.70it/s]




 86%|████████▌ | 1390/1616 [15:34<02:04,  1.82it/s]




 86%|████████▌ | 1391/1616 [15:35<02:24,  1.55it/s]




 86%|████████▌ | 1392/1616 [15:35<02:35,  1.44it/s]




 86%|████████▌ | 1393/1616 [15:36<02:28,  1.51it/s]




 86%|████████▋ | 1394/1616 [15:37<02:53,  1.28it/s]




 86%|████████▋ | 1395/1616 [15:38<02:39,  1.38it/s]




 86%|████████▋ | 1396/1616 [15:38<02:34,  1.42it/s]




 86%|████████▋ | 1397/1616 [15:39<02:02,  1.78it/s]




 87%|████████▋ | 1398/1616 [15:39<01:43,  2.11it/s]




 87%|████████▋ | 1399/1616 [15:40<02:27,  1.47it/s]




 87%|████████▋ | 1400/1616 [15:41<02:56,  1.22it/s]




 87%|████████▋ | 1402/1616 [15:42<02:33,  1.39it/s]




 87%|████████▋ | 1403/1616 [15:43<02:56,  1.20it/s]




 87%|████████▋ | 1404/1616 [15:44<02:29,  1.42it/s]




 87%|████████▋ | 1405/1616 [15:44<02:01,  1.74it/s]




 87%|████████▋ | 1406/1616 [15:45<02:31,  1.39it/s]




 87%|████████▋ | 1408/1616 [15:46<02:24,  1.44it/s]




 87%|████████▋ | 1409/1616 [15:47<02:08,  1.62it/s]




 87%|████████▋ | 1410/1616 [15:48<02:43,  1.26it/s]




 87%|████████▋ | 1411/1616 [15:49<02:26,  1.40it/s]




 87%|████████▋ | 1412/1616 [15:49<02:17,  1.49it/s]




 87%|████████▋ | 1413/1616 [15:49<01:54,  1.77it/s]

 88%|████████▊ | 1414/1616 [15:51<02:26,  1.38it/s]




 88%|████████▊ | 1416/1616 [15:52<02:24,  1.39it/s]




 88%|████████▊ | 1418/1616 [15:54<02:32,  1.29it/s]




 88%|████████▊ | 1419/1616 [15:54<02:05,  1.56it/s]




 88%|████████▊ | 1420/1616 [15:54<01:56,  1.69it/s]




 88%|████████▊ | 1421/1616 [15:55<01:43,  1.89it/s]




 88%|████████▊ | 1422/1616 [15:56<02:26,  1.33it/s]




 88%|████████▊ | 1424/1616 [15:57<02:12,  1.45it/s]




 88%|████████▊ | 1426/1616 [15:59<02:38,  1.20it/s]




 88%|████████▊ | 1428/1616 [16:00<01:45,  1.78it/s]




 88%|████████▊ | 1429/1616 [16:00<01:34,  1.97it/s]




 88%|████████▊ | 1430/1616 [16:01<02:18,  1.34it/s]




 89%|████████▊ | 1431/1616 [16:02<01:52,  1.65it/s]




 89%|████████▊ | 1432/1616 [16:02<02:03,  1.49it/s]




 89%|████████▊ | 1433/1616 [16:03<02:05,  1.46it/s]




 89%|████████▊ | 1434/1616 [16:05<02:46,  1.10it/s]




 89%|████████▉ | 1436/1616 [16:05<01:51,  1.62it/s]




 89%|████████▉ | 1438/1616 [16:07<02:04,  1.43it/s]




 89%|████████▉ | 1439/1616 [16:07<01:48,  1.64it/s]




 89%|████████▉ | 1440/1616 [16:08<01:46,  1.66it/s]




 89%|████████▉ | 1441/1616 [16:08<01:51,  1.57it/s]




 89%|████████▉ | 1442/1616 [16:10<02:32,  1.14it/s]




 89%|████████▉ | 1444/1616 [16:10<01:41,  1.70it/s]




 89%|████████▉ | 1446/1616 [16:12<02:00,  1.41it/s]




 90%|████████▉ | 1447/1616 [16:12<01:42,  1.65it/s]




 90%|████████▉ | 1448/1616 [16:13<01:36,  1.75it/s]




 90%|████████▉ | 1449/1616 [16:14<01:43,  1.61it/s]




 90%|████████▉ | 1450/1616 [16:16<02:37,  1.05it/s]




 90%|████████▉ | 1451/1616 [16:16<02:10,  1.27it/s]




 90%|████████▉ | 1453/1616 [16:16<01:23,  1.94it/s]




 90%|████████▉ | 1454/1616 [16:18<01:55,  1.40it/s]




 90%|█████████ | 1455/1616 [16:18<01:46,  1.52it/s]




 90%|█████████ | 1456/1616 [16:19<01:46,  1.50it/s]




 90%|█████████ | 1457/1616 [16:20<01:54,  1.38it/s]




 90%|█████████ | 1458/1616 [16:21<02:16,  1.16it/s]




 90%|█████████ | 1459/1616 [16:21<01:46,  1.47it/s]




 90%|█████████ | 1460/1616 [16:21<01:27,  1.77it/s]




 90%|█████████ | 1461/1616 [16:22<01:18,  1.97it/s]




 90%|█████████ | 1462/1616 [16:23<02:01,  1.27it/s]




 91%|█████████ | 1463/1616 [16:23<01:37,  1.57it/s]




 91%|█████████ | 1464/1616 [16:24<01:32,  1.64it/s]




 91%|█████████ | 1465/1616 [16:25<01:42,  1.47it/s]




 91%|█████████ | 1466/1616 [16:26<02:03,  1.21it/s]




 91%|█████████ | 1467/1616 [16:26<01:43,  1.43it/s]




 91%|█████████ | 1469/1616 [16:27<01:15,  1.95it/s]




 91%|█████████ | 1470/1616 [16:28<01:46,  1.37it/s]




 91%|█████████ | 1471/1616 [16:29<01:27,  1.66it/s]




 91%|█████████ | 1472/1616 [16:30<01:38,  1.46it/s]




 91%|█████████ | 1473/1616 [16:30<01:29,  1.60it/s]




 91%|█████████ | 1474/1616 [16:32<02:11,  1.08it/s]




 91%|█████████▏| 1475/1616 [16:32<01:37,  1.44it/s]




 91%|█████████▏| 1477/1616 [16:33<01:22,  1.68it/s]




 91%|█████████▏| 1478/1616 [16:34<01:46,  1.29it/s]




 92%|█████████▏| 1479/1616 [16:34<01:24,  1.62it/s]




 92%|█████████▏| 1480/1616 [16:35<01:21,  1.67it/s]




 92%|█████████▏| 1481/1616 [16:36<01:27,  1.54it/s]




 92%|█████████▏| 1482/1616 [16:37<02:00,  1.12it/s]




 92%|█████████▏| 1483/1616 [16:37<01:33,  1.42it/s]




 92%|█████████▏| 1484/1616 [16:38<01:13,  1.79it/s]




 92%|█████████▏| 1485/1616 [16:38<01:20,  1.63it/s]




 92%|█████████▏| 1486/1616 [16:39<01:35,  1.37it/s]




 92%|█████████▏| 1487/1616 [16:39<01:13,  1.76it/s]




 92%|█████████▏| 1488/1616 [16:40<01:21,  1.56it/s]




 92%|█████████▏| 1489/1616 [16:41<01:20,  1.59it/s]




 92%|█████████▏| 1490/1616 [16:42<01:44,  1.21it/s]




 92%|█████████▏| 1491/1616 [16:42<01:21,  1.54it/s]




 92%|█████████▏| 1492/1616 [16:43<01:05,  1.88it/s]




 92%|█████████▏| 1493/1616 [16:44<01:26,  1.43it/s]




 92%|█████████▏| 1494/1616 [16:44<01:24,  1.45it/s]




 93%|█████████▎| 1495/1616 [16:45<01:15,  1.61it/s]




 93%|█████████▎| 1496/1616 [16:45<01:14,  1.62it/s]




 93%|█████████▎| 1497/1616 [16:46<01:19,  1.49it/s]




 93%|█████████▎| 1498/1616 [16:47<01:28,  1.34it/s]




 93%|█████████▎| 1499/1616 [16:47<01:10,  1.66it/s]




 93%|█████████▎| 1500/1616 [16:48<01:04,  1.80it/s]




 93%|█████████▎| 1501/1616 [16:50<01:42,  1.12it/s]




 93%|█████████▎| 1502/1616 [16:50<01:32,  1.24it/s]




 93%|█████████▎| 1503/1616 [16:51<01:26,  1.30it/s]




 93%|█████████▎| 1504/1616 [16:51<01:16,  1.46it/s]




 93%|█████████▎| 1505/1616 [16:52<00:59,  1.87it/s]




 93%|█████████▎| 1506/1616 [16:52<01:04,  1.71it/s]




 93%|█████████▎| 1507/1616 [16:53<01:20,  1.35it/s]




 93%|█████████▎| 1508/1616 [16:53<00:59,  1.82it/s]




 93%|█████████▎| 1509/1616 [16:55<01:44,  1.02it/s]




 93%|█████████▎| 1510/1616 [16:56<01:17,  1.38it/s]




 94%|█████████▎| 1511/1616 [16:56<01:10,  1.49it/s]




 94%|█████████▎| 1512/1616 [16:57<01:07,  1.53it/s]




 94%|█████████▎| 1514/1616 [16:57<00:52,  1.95it/s]




 94%|█████████▍| 1515/1616 [16:58<01:03,  1.58it/s]




 94%|█████████▍| 1516/1616 [16:59<00:55,  1.80it/s]




 94%|█████████▍| 1517/1616 [17:01<01:40,  1.02s/it]




 94%|█████████▍| 1518/1616 [17:01<01:14,  1.31it/s]




 94%|█████████▍| 1519/1616 [17:01<00:58,  1.65it/s]




 94%|█████████▍| 1520/1616 [17:02<00:54,  1.76it/s]




 94%|█████████▍| 1521/1616 [17:02<00:55,  1.71it/s]




 94%|█████████▍| 1523/1616 [17:04<00:53,  1.74it/s]




 94%|█████████▍| 1524/1616 [17:05<01:04,  1.43it/s]




 94%|█████████▍| 1525/1616 [17:07<01:30,  1.00it/s]




 94%|█████████▍| 1526/1616 [17:07<01:08,  1.31it/s]




 94%|█████████▍| 1527/1616 [17:07<00:56,  1.59it/s]




 95%|█████████▍| 1529/1616 [17:08<00:49,  1.77it/s]




 95%|█████████▍| 1530/1616 [17:08<00:42,  2.00it/s]




 95%|█████████▍| 1531/1616 [17:09<00:49,  1.72it/s]




 95%|█████████▍| 1532/1616 [17:10<01:04,  1.29it/s]




 95%|█████████▍| 1533/1616 [17:12<01:22,  1.00it/s]




 95%|█████████▍| 1534/1616 [17:12<01:04,  1.27it/s]




 95%|█████████▌| 1536/1616 [17:12<00:39,  2.05it/s]




 95%|█████████▌| 1537/1616 [17:13<00:43,  1.82it/s]




 95%|█████████▌| 1538/1616 [17:13<00:37,  2.09it/s]




 95%|█████████▌| 1539/1616 [17:14<00:42,  1.82it/s]




 95%|█████████▌| 1540/1616 [17:16<00:59,  1.27it/s]




 95%|█████████▌| 1541/1616 [17:17<01:19,  1.07s/it]




 95%|█████████▌| 1542/1616 [17:18<01:00,  1.22it/s]




 95%|█████████▌| 1543/1616 [17:18<00:45,  1.59it/s]




 96%|█████████▌| 1544/1616 [17:18<00:34,  2.07it/s]

 96%|█████████▌| 1545/1616 [17:19<00:41,  1.70it/s]




 96%|█████████▌| 1546/1616 [17:19<00:44,  1.57it/s]




 96%|█████████▌| 1547/1616 [17:20<00:34,  2.02it/s]




 96%|█████████▌| 1548/1616 [17:21<00:43,  1.55it/s]




 96%|█████████▌| 1549/1616 [17:23<01:14,  1.11s/it]




 96%|█████████▌| 1550/1616 [17:23<00:55,  1.19it/s]




 96%|█████████▌| 1551/1616 [17:23<00:44,  1.47it/s]




 96%|█████████▌| 1552/1616 [17:23<00:34,  1.88it/s]




 96%|█████████▌| 1553/1616 [17:24<00:36,  1.72it/s]




 96%|█████████▌| 1554/1616 [17:25<00:36,  1.72it/s]




 96%|█████████▋| 1556/1616 [17:26<00:38,  1.57it/s]




 96%|█████████▋| 1557/1616 [17:28<00:56,  1.04it/s]




 96%|█████████▋| 1558/1616 [17:28<00:44,  1.31it/s]




 96%|█████████▋| 1559/1616 [17:28<00:33,  1.68it/s]




 97%|█████████▋| 1560/1616 [17:29<00:28,  1.98it/s]




 97%|█████████▋| 1561/1616 [17:29<00:28,  1.90it/s]




 97%|█████████▋| 1562/1616 [17:30<00:29,  1.83it/s]




 97%|█████████▋| 1563/1616 [17:30<00:23,  2.29it/s]




 97%|█████████▋| 1564/1616 [17:31<00:36,  1.43it/s]




 97%|█████████▋| 1565/1616 [17:33<00:54,  1.07s/it]




 97%|█████████▋| 1566/1616 [17:33<00:39,  1.27it/s]




 97%|█████████▋| 1567/1616 [17:34<00:29,  1.68it/s]




 97%|█████████▋| 1568/1616 [17:34<00:24,  1.97it/s]




 97%|█████████▋| 1569/1616 [17:35<00:26,  1.79it/s]




 97%|█████████▋| 1570/1616 [17:35<00:25,  1.83it/s]




 97%|█████████▋| 1571/1616 [17:35<00:20,  2.19it/s]




 97%|█████████▋| 1572/1616 [17:37<00:35,  1.24it/s]




 97%|█████████▋| 1573/1616 [17:39<00:45,  1.06s/it]




 97%|█████████▋| 1575/1616 [17:39<00:28,  1.43it/s]




 98%|█████████▊| 1576/1616 [17:39<00:22,  1.78it/s]




 98%|█████████▊| 1577/1616 [17:40<00:23,  1.69it/s]




 98%|█████████▊| 1578/1616 [17:40<00:18,  2.06it/s]




 98%|█████████▊| 1579/1616 [17:41<00:21,  1.69it/s]




 98%|█████████▊| 1580/1616 [17:43<00:33,  1.07it/s]




 98%|█████████▊| 1581/1616 [17:44<00:34,  1.03it/s]




 98%|█████████▊| 1583/1616 [17:44<00:21,  1.53it/s]




 98%|█████████▊| 1584/1616 [17:45<00:18,  1.72it/s]




 98%|█████████▊| 1585/1616 [17:45<00:15,  2.01it/s]




 98%|█████████▊| 1586/1616 [17:46<00:14,  2.04it/s]




 98%|█████████▊| 1587/1616 [17:47<00:19,  1.52it/s]




 98%|█████████▊| 1588/1616 [17:48<00:23,  1.19it/s]




 98%|█████████▊| 1589/1616 [17:49<00:25,  1.08it/s]




 98%|█████████▊| 1590/1616 [17:50<00:22,  1.15it/s]




 98%|█████████▊| 1591/1616 [17:50<00:18,  1.38it/s]




 99%|█████████▊| 1593/1616 [17:50<00:09,  2.33it/s]




 99%|█████████▊| 1594/1616 [17:51<00:10,  2.15it/s]




 99%|█████████▊| 1595/1616 [17:52<00:13,  1.56it/s]




 99%|█████████▉| 1596/1616 [17:53<00:15,  1.26it/s]




 99%|█████████▉| 1597/1616 [17:54<00:17,  1.09it/s]




 99%|█████████▉| 1598/1616 [17:55<00:15,  1.18it/s]




 99%|█████████▉| 1599/1616 [17:55<00:11,  1.47it/s]




 99%|█████████▉| 1600/1616 [17:56<00:10,  1.59it/s]




 99%|█████████▉| 1601/1616 [17:56<00:07,  1.94it/s]




 99%|█████████▉| 1602/1616 [17:57<00:06,  2.01it/s]




 99%|█████████▉| 1603/1616 [17:58<00:08,  1.56it/s]




 99%|█████████▉| 1604/1616 [17:58<00:08,  1.47it/s]




 99%|█████████▉| 1605/1616 [18:00<00:09,  1.14it/s]




 99%|█████████▉| 1606/1616 [18:00<00:08,  1.19it/s]




 99%|█████████▉| 1607/1616 [18:01<00:06,  1.49it/s]




100%|█████████▉| 1608/1616 [18:01<00:04,  1.69it/s]




100%|█████████▉| 1609/1616 [18:01<00:03,  2.10it/s]




100%|█████████▉| 1610/1616 [18:02<00:03,  2.00it/s]




100%|█████████▉| 1611/1616 [18:03<00:03,  1.58it/s]




100%|█████████▉| 1612/1616 [18:04<00:02,  1.42it/s]




100%|█████████▉| 1613/1616 [18:05<00:02,  1.16it/s]




100%|█████████▉| 1614/1616 [18:06<00:01,  1.23it/s]




100%|██████████| 1616/1616 [18:06<00:00,  1.49it/s]
Families: 100%|██████████| 3/3 [29:06<00:00, 582.10s/it]

Runtime: 1746.292645 s

In [95]:
# skip dir creation if it already exist
out_dir = "sampD_diags_SCALES"            
os.makedirs(out_dir, exist_ok=True)

for diagnosis, sampD_scales in bca_sampD_diags_inter.items():
    #fname = f"{diagnosis}_sampD_scales.pkl"
    fname = f"{diagnosis}_sampD_scales.pkl"
    fpath = os.path.join(out_dir, fname)
    with open(fpath, "wb") as f:
        pickle.dump(sampD_scales, f, protocol=pickle.HIGHEST_PROTOCOL)

In [43]:
#bca_sampD_diags_scales['ANR']['DT'][5]
#fdr_neut_filtered_diags_scales['ANR']['DT'][5]

In [97]:
# Load
with open("sampD_diags_SCALES/ANBP_sampD_scales.pkl", "rb") as f:
    ANBP_sampD_scales = pickle.load(f)

with open("sampD_diags_SCALES/ANR_sampD_scales.pkl", "rb") as f:
    ANR_sampD_scales = pickle.load(f)

with open("sampD_diags_SCALES/BED_OSFED_sampD_scales.pkl", "rb") as f:
    BED_OSFED_sampD_scales = pickle.load(f)

with open("sampD_diags_SCALES/BN_sampD_scales.pkl", "rb") as f:
    BN_sampD_scales = pickle.load(f)

# rebuild general dictionary
bca_sampD_diags_scales = {
    'ANBP' : ANBP_sampD_scales,
    'ANR' : ANR_sampD_scales,
    'BED_OSFED' : BED_OSFED_sampD_scales,
    'BN' : BN_sampD_scales
}

#### Assambling information:  
bca_sampD_diags_scales contains the emp distros from the bca sampling for each multiplet.
Assemble info from multiplets and sample distributions just computed, by adding to the dict of the fdr survived multiplets info about the BCa sample_distro

In [98]:
BCa_fdr_diags_scales = {}
for diagnosis in bca_sampD_diags_scales:
    BCa_fdr_diags_scales[diagnosis] = ut.get_BCa_input_dict_from_fdr(bca_sampD_diags_scales[diagnosis],
                                                              fdr_neut_filtered_mults_diags[diagnosis])

In [101]:
#BCa_fdr_diags_scales['ANR'][3][(38, 53, 64)]

In [102]:
bca_mults_diags_scales = {} 
for diagnosis, mults in BCa_fdr_diags_scales.items():
    start = time.perf_counter()
    # structure: order: multiple: samp_distro
    bca_mults_diags_scales[diagnosis] = bca_bootopt.bca_bootstrap_parallel(multiplets_dict=mults, 
                                                                            X=EDI_diags[diagnosis])
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 156 multiplets

Families:  33%|███▎      | 1/3 [00:02<00:04,  2.28s/it]

  [BCa | family 3] 156/156 multiplets (100%)

[BCa | family 4] starting – 1387 multiplets

Families:  67%|██████▋   | 2/3 [00:02<00:01,  1.31s/it]

  [BCa | family 4] 1387/1387 multiplets (100%)

[BCa | family 5] starting – 1600 multiplets
  [BCa | family 5] 400/1600 multiplets (25%)
  [BCa | family 5] 800/1600 multiplets (50%)
  [BCa | family 5] 1200/1600 multiplets (75%)

Families: 100%|██████████| 3/3 [00:03<00:00,  1.21s/it]

  [BCa | family 5] 1600/1600 multiplets (100%)
Runtime: 3.624112 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 46 multiplets
  [BCa | family 3] 46/46 multiplets (100%)

[BCa | family 4] starting – 1185 multiplets

Families:  67%|██████▋   | 2/3 [00:00<00:00,  3.10it/s]

  [BCa | family 4] 1185/1185 multiplets (100%)

[BCa | family 5] starting – 1559 multiplets

Families: 100%|██████████| 3/3 [00:01<00:00,  2.24it/s]

  [BCa | family 5] 1559/1559 multiplets (100%)
Runtime: 1.341224 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 144 multiplets
  [BCa | family 3] 144/144 multiplets (100%)

[BCa | family 4] starting – 1251 multiplets

Families:  67%|██████▋   | 2/3 [00:00<00:00,  3.09it/s]

  [BCa | family 4] 1251/1251 multiplets (100%)

[BCa | family 5] starting – 1460 multiplets

Families: 100%|██████████| 3/3 [00:01<00:00,  2.31it/s]

  [BCa | family 5] 1460/1460 multiplets (100%)
Runtime: 1.307773 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 22 multiplets
  [BCa | family 3] 22/22 multiplets (100%)

[BCa | family 4] starting – 1305 multiplets

Families:  67%|██████▋   | 2/3 [00:00<00:00,  3.04it/s]

  [BCa | family 4] 1305/1305 multiplets (100%)

[BCa | family 5] starting – 1616 multiplets

Families: 100%|██████████| 3/3 [00:01<00:00,  2.02it/s]

  [BCa | family 5] 1616/1616 multiplets (100%)
Runtime: 1.484402 s

When running the BCa_CI_check procedure, the multiplets with not valid pvalue have already been filtered out.

In [103]:
from contextlib import redirect_stdout

BCa_selected_diags = {}
for diagnosis, multiplets in bca_mults_diags_scales.items():
    with open(diagnosis + "_CI_warnings_SCALES.txt", "w") as f:
        with redirect_stdout(f):
            BCa_selected_diags[diagnosis] = bca_bootopt.BCa_CI_mults_selection(multiplets)

In [106]:
BCa_selected_diags['ANR'][3][(38, 53, 64)]

'synergy'

Save results to picke files.

In [107]:
# skip dir creation if it already exist
out_dir_bca = "bca_selected_SCALES"            
os.makedirs(out_dir_bca, exist_ok=True)

for diagnosis, bca_scales in BCa_selected_diags.items():
    fname = f"{diagnosis}_bca_selected_scales.pkl"
    fpath = os.path.join(out_dir_bca, fname)
    with open(fpath, "wb") as f:
        pickle.dump(bca_scales, f, protocol=pickle.HIGHEST_PROTOCOL)

### Stage 2, part 2: BCa_CI: plots and stats

In [162]:
base = 'SCALES_part2_plots/'
n_boot = 1000

for diagnosis in bca_sampD_diags_scales:
    out_dir = f"{base}{diagnosis}_figures"
    
    # bootstrap sampling
    # boot_arrays = bootstrap_multiplets_chunked(multiplets_dict=multiplets, X=X, n_boot=500)
    boot_arrays = bca_sampD_diags_scales[diagnosis]

    # BCa confidence intervals
    # BCa_boot = bca_bootstrap_parallel(multiplets_dict=..., X=X, alpha=0.05)
    BCa_boot = bca_mults_diags_scales[diagnosis]
    
    # selection — keeps only {family: {multiplet: hypothesis}}
    # BCa_selected = BCa_CI_mults_selection(BCa_boot, tol=0.05)
    BCa_selected = BCa_selected_diags[diagnosis]
    
    # re-join with full info for the survivors  
    BCa_boot_sel, boot_arrays_sel = bca_bootopt.retrieve_selected_multiplets_info(
        BCa_selected = BCa_selected,
        BCa_boot_full = BCa_boot,
        boot_arrays_full = boot_arrays,
    )              # {family: {multiplet: (obs, lo, hi, diag)}}

    # pick representative multiplets and plot
    reps = bca_plots.pick_representative_multiplets(BCa_boot_sel, 
                                                    boot_arrays_sel)
    bca_plots.plot_all(
        BCa_boot_all = BCa_boot_sel,
        n_samples = EDI_diags[diagnosis].shape[0],
        n_boot = n_boot,
        representative_multiplets = reps,
        output_dir=out_dir,
    )

  Family 3: 104/156 multiplets retrieved.
  Family 4: 1357/1387 multiplets retrieved.
  Family 5: 219/1600 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(65, 8, 60, 77)  Ω=-1.0906  CI=[-1.2647, -0.8217]  margin from 0=0.8217  method=percentile
  most_borderline     multiplet=(3, 6, 14, 22)  Ω=-0.3075  CI=[-0.4810, -0.0007]  margin from 0=0.0007  method=percentile
  most_extreme        multiplet=(54, 8, 40, 77)  Ω=-1.3667  CI=[-1.5397, -1.1053]  margin from 0=1.1053  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → SCALES_part2_plots/ANBP_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → SCALES_part2_plots/ANBP_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (65, 8, 60, 77) ...
  saved → SCALES_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult65_8_60_77.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (3, 6, 14, 22) ...
  saved → SCALES_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult3_6_14_22.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (54, 8, 40, 77) ...
  saved → SCALES_part2_plots/ANBP_figures\fig3_boot_dist_fam4_mult54_8_40_77.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → SCALES_part2_plots/ANBP_figures\fig4_summary_table.pdf / .png

All figures saved to 'SCALES_part2_plots/ANBP_figures/'.
  Family 3: 26/46 multiplets retrieved.
  Family 4: 1131/1185 multiplets retrieved.
  Family 5: 370/1559 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(11, 25, 33, 40)  Ω=-0.9159  CI=[-1.2136, -0.8303]  margin from 0=0.8303  method=percentile
  most_borderline     multiplet=(9, 45, 47, 55)  Ω=-0.1856  CI=[-0.4151, -0.0005]  margin from 0=0.0005  method=percentile
  most_extreme        multiplet=(10, 41, 43, 63)  Ω=-1.2380  CI=[-1.5094, -1.1739]  margin from 0=1.1739  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → SCALES_part2_plots/ANR_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → SCALES_part2_plots/ANR_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (11, 25, 33, 40) ...
  saved → SCALES_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult11_25_33_40.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (9, 45, 47, 55) ...
  saved → SCALES_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult9_45_47_55.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (10, 41, 43, 63) ...
  saved → SCALES_part2_plots/ANR_figures\fig3_boot_dist_fam4_mult10_41_43_63.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → SCALES_part2_plots/ANR_figures\fig4_summary_table.pdf / .png

All figures saved to 'SCALES_part2_plots/ANR_figures/'.
  Family 3: 129/144 multiplets retrieved.
  Family 4: 1233/1251 multiplets retrieved.
  Family 5: 144/1460 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(65, 33, 44, 77)  Ω=-1.1992  CI=[-1.3108, -0.8182]  margin from 0=0.8182  method=percentile
  most_borderline     multiplet=(2, 9, 45, 55)  Ω=+0.1115  CI=[0.0004, 0.4515]  margin from 0=0.0004  method=percentile
  most_extreme        multiplet=(34, 69, 18, 24)  Ω=-1.5161  CI=[-1.6211, -1.0651]  margin from 0=1.0651  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (65, 33, 44, 77) ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult65_33_44_77.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (2, 9, 45, 55) ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult2_9_45_55.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (34, 69, 18, 24) ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig3_boot_dist_fam4_mult34_69_18_24.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → SCALES_part2_plots/BED_OSFED_figures\fig4_summary_table.pdf / .png

All figures saved to 'SCALES_part2_plots/BED_OSFED_figures/'.
  Family 3: 17/22 multiplets retrieved.
  Family 4: 767/1305 multiplets retrieved.
  Family 5: 468/1616 multiplets retrieved.

Representative multiplets selected from family 4:
  most_typical        multiplet=(67, 70, 72, 85)  Ω=-0.5679  CI=[-0.7805, -0.4900]  margin from 0=0.4900  method=percentile
  most_borderline     multiplet=(12, 47, 55, 62)  Ω=-0.1582  CI=[-0.2704, -0.0006]  margin from 0=0.0006  method=percentile
  most_extreme        multiplet=(67, 83, 54, 65)  Ω=-1.1216  CI=[-1.4275, -1.1101]  margin from 0=1.1101  method=percentile
Generating Figure 1 – Ω dot-and-whisker with BCa CIs ...
  saved → SCALES_part2_plots/BN_figures\fig1_omega_ci.pdf / .png
Generating Figure 2 – Redundancy / synergy breakdown ...
  saved → SCALES_part2_plots/BN_figures\fig2_breakdown.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (67, 70, 72, 85) ...
  saved → SCALES_part2_plots/BN_figures\fig3_boot_dist_fam4_mult67_70_72_85.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (12, 47, 55, 62) ...
  saved → SCALES_part2_plots/BN_figures\fig3_boot_dist_fam4_mult12_47_55_62.pdf / .png
Generating Figure 3 – Bootstrap distribution for multiplet (67, 83, 54, 65) ...
  saved → SCALES_part2_plots/BN_figures\fig3_boot_dist_fam4_mult67_83_54_65.pdf / .png
Generating Figure 4 – Summary statistics table ...
  saved → SCALES_part2_plots/BN_figures\fig4_summary_table.pdf / .png

All figures saved to 'SCALES_part2_plots/BN_figures/'.

### Hyperedges selection's results

- fdr_neut_filtered_diags_scales 

- bca_selected_diag

In [108]:
# Load
with open("bca_selected_SCALES/ANBP_bca_selected_scales.pkl", "rb") as f:
    ANBP_bca_sel_scales = pickle.load(f)

with open("bca_selected_SCALES/ANR_bca_selected_scales.pkl", "rb") as f:
    ANR_bca_sel_scales = pickle.load(f)

with open("bca_selected_SCALES/BED_OSFED_bca_selected_scales.pkl", "rb") as f:
    BED_OSFED_bca_sel_scales = pickle.load(f)

with open("bca_selected_SCALES/BN_bca_selected_scales.pkl", "rb") as f:
    BN_bca_sel_scales = pickle.load(f)

# rebuild general dictionary
BCa_selected_diags_loaded = {
    'ANBP' : ANBP_bca_sel_scales,
    'ANR' : ANR_bca_sel_scales,
    'BED_OSFED' : BED_OSFED_bca_sel_scales,
    'BN' : BN_bca_sel_scales
}

### For selected multiplets, recompute $\Omega$-information and append all the information together.

In [112]:
sel_mult_diags_scales = {}
for diagnosis, sel_mults in BCa_selected_diags_loaded.items():
    sel_mult_diags_scales[diagnosis] = pp_bootopt.compute_omega_for_multiplets(multiplets_dict=sel_mults, 
                                                                                   X=EDI_diags[diagnosis])

In [113]:
sel_mult_diags_scales['ANR'].head(5)

   order       label     omega  node1  node2  node3  node4  node5
0      3  redundancy  0.209966      2     45     32   <NA>   <NA>
1      3     synergy -0.103594      3     22     39   <NA>   <NA>
2      3  redundancy  0.227318      7     16     32   <NA>   <NA>
3      3  redundancy  0.262536      7     16     49   <NA>   <NA>
4      3  redundancy  0.259711      7     32     49   <NA>   <NA>

In [114]:
# skip dir creation if it already exist
out_dir_sm = "selected_df_scales"            
os.makedirs(out_dir_sm, exist_ok=True)

for diagnosis, df in sel_mult_diags_scales.items():
    fname = f"{diagnosis}_selected_df_scales.csv"
    fpath = os.path.join(out_dir_sm, fname)
    df.to_csv(fpath, index=False)

### MULTIPLETS' CIs COMPARISON
I have:

    - BCa_selected_diags_scales_INTRA_loaded
    - BCa_selected_diags_INTER_loaded
    
I want to compare the bootstrap confidence interval of each multiplet with subsets of its components one order below.
Multiplets are discarded if the confidence intervals overlap, as this indicates that they do not display additional synergy or redundancy.

In [115]:
BCa_selected_diags_loaded['ANR'][3] # get all keys

{(38, 53, 64): 'synergy',
 (53, 61, 64): 'synergy',
 (9, 45, 55): 'redundancy',
 (9, 45, 59): 'redundancy',
 (9, 55, 59): 'redundancy',
 (9, 55, 62): 'redundancy',
 (9, 59, 62): 'redundancy',
 (19, 55, 62): 'redundancy',
 (31, 55, 62): 'redundancy',
 (45, 55, 59): 'redundancy',
 (45, 59, 62): 'redundancy',
 (55, 59, 62): 'redundancy',
 (7, 16, 32): 'redundancy',
 (7, 16, 49): 'redundancy',
 (7, 32, 49): 'redundancy',
 (16, 25, 32): 'redundancy',
 (16, 25, 49): 'redundancy',
 (16, 32, 49): 'redundancy',
 (70, 79, 90): 'synergy',
 (21, 26, 51): 'redundancy',
 (21, 26, 60): 'redundancy',
 (3, 22, 39): 'synergy',
 (13, 29, 52): 'synergy',
 (9, 45, 32): 'redundancy',
 (2, 45, 32): 'redundancy',
 (42, 43, 63): 'synergy'}

In [119]:
selected_as_list = ut.get_selected_INTER(BCa_selected_diags_loaded)

#### Get the distributions for CIs computation

In [120]:
selected_boot_stats = {}
for diagnosis, mults in selected_as_list.items():
    start = time.perf_counter()
    selected_boot_stats[diagnosis] = bca_bootopt.get_boot_stats_parallel(multiplets_dict=mults, 
                                                                            X=EDI_diags[diagnosis], 
                                                                            n_boot=n_boot_perm) # 400
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]
Multiplets | family 3:   0%|          | 0/104 [00:00<?, ?it/s]

  0%|          | 0/104 [00:00<?, ?it/s]

  1%|          | 1/104 [00:04<07:14,  4.22s/it]

  3%|▎         | 3/104 [00:04<01:54,  1.13s/it]

  5%|▍         | 5/104 [00:04<00:57,  1.73it/s]

  7%|▋         | 7/104 [00:04<00:34,  2.81it/s]

  9%|▊         | 9/104 [00:06<00:51,  1.85it/s]

 11%|█         | 11/104 [00:06<00:36,  2.54it/s]

 12%|█▎        | 13/104 [00:06<00:28,  3.21it/s]

 15%|█▌        | 16/104 [00:06<00:17,  4.98it/s]

 17%|█▋        | 18/104 [00:08<00:30,  2.80it/s]

 18%|█▊        | 19/104 [00:08<00:31,  2.72it/s]

 21%|██        | 22/104 [00:09<00:19,  4.11it/s]

 22%|██▏       | 23/104 [00:09<00:18,  4.33it/s]

 24%|██▍       | 25/104 [00:10<00:28,  2.80it/s]

 26%|██▌       | 27/104 [00:10<00:24,  3.09it/s]

 27%|██▋       | 28/104 [00:11<00:22,  3.30it/s]

 28%|██▊       | 29/104 [00:11<00:20,  3.73it/s]

 29%|██▉       | 30/104 [00:11<00:18,  4.05it/s]

 30%|██▉       | 31/104 [00:11<00:18,  3.99it/s]

 31%|███       | 32/104 [00:12<00:18,  3.93it/s]

 32%|███▏      | 33/104 [00:12<00:22,  3.18it/s]

 33%|███▎      | 34/104 [00:12<00:17,  3.92it/s]

 34%|███▎      | 35/104 [00:13<00:21,  3.23it/s]

 36%|███▌      | 37/104 [00:13<00:21,  3.08it/s]

 38%|███▊      | 39/104 [00:14<00:20,  3.23it/s]

 38%|███▊      | 40/104 [00:14<00:18,  3.47it/s]

 40%|████      | 42/104 [00:14<00:12,  5.05it/s]

 41%|████▏     | 43/104 [00:15<00:18,  3.37it/s]

 43%|████▎     | 45/104 [00:15<00:15,  3.71it/s]

 44%|████▍     | 46/104 [00:16<00:16,  3.49it/s]

 45%|████▌     | 47/104 [00:16<00:18,  3.05it/s]

 47%|████▋     | 49/104 [00:16<00:15,  3.45it/s]

 49%|████▉     | 51/104 [00:17<00:16,  3.15it/s]

 50%|█████     | 52/104 [00:17<00:14,  3.54it/s]

 52%|█████▏    | 54/104 [00:18<00:14,  3.51it/s]

 53%|█████▎    | 55/104 [00:18<00:15,  3.23it/s]

 55%|█████▍    | 57/104 [00:19<00:11,  4.27it/s]

 56%|█████▌    | 58/104 [00:19<00:11,  4.07it/s]

 57%|█████▋    | 59/104 [00:19<00:12,  3.47it/s]

 58%|█████▊    | 60/104 [00:19<00:11,  3.95it/s]

 60%|█████▉    | 62/104 [00:20<00:11,  3.51it/s]

 61%|██████    | 63/104 [00:20<00:12,  3.22it/s]

 62%|██████▎   | 65/104 [00:21<00:08,  4.73it/s]

 63%|██████▎   | 66/104 [00:21<00:09,  4.00it/s]

 64%|██████▍   | 67/104 [00:21<00:08,  4.25it/s]

 65%|██████▌   | 68/104 [00:21<00:08,  4.34it/s]

 67%|██████▋   | 70/104 [00:22<00:09,  3.58it/s]

 68%|██████▊   | 71/104 [00:23<00:10,  3.10it/s]

 70%|███████   | 73/104 [00:23<00:06,  4.55it/s]

 71%|███████   | 74/104 [00:23<00:07,  3.84it/s]

 72%|███████▏  | 75/104 [00:23<00:07,  3.88it/s]

 74%|███████▍  | 77/104 [00:24<00:05,  5.40it/s]

 75%|███████▌  | 78/104 [00:24<00:06,  3.77it/s]

 76%|███████▌  | 79/104 [00:25<00:08,  2.89it/s]

 78%|███████▊  | 81/104 [00:25<00:06,  3.67it/s]

 79%|███████▉  | 82/104 [00:25<00:06,  3.61it/s]

 80%|███████▉  | 83/104 [00:25<00:04,  4.26it/s]

 81%|████████  | 84/104 [00:26<00:05,  3.91it/s]

 83%|████████▎ | 86/104 [00:26<00:05,  3.14it/s]

 84%|████████▎ | 87/104 [00:27<00:04,  3.52it/s]

 85%|████████▍ | 88/104 [00:27<00:04,  3.95it/s]

 86%|████████▌ | 89/104 [00:27<00:03,  4.15it/s]

 87%|████████▋ | 90/104 [00:27<00:03,  3.73it/s]

 88%|████████▊ | 91/104 [00:28<00:03,  3.86it/s]

 88%|████████▊ | 92/104 [00:28<00:03,  3.74it/s]

 90%|█████████ | 94/104 [00:28<00:02,  3.54it/s]

 91%|█████████▏| 95/104 [00:29<00:02,  3.60it/s]

 93%|█████████▎| 97/104 [00:29<00:01,  3.68it/s]

 94%|█████████▍| 98/104 [00:30<00:01,  3.65it/s]

 96%|█████████▌| 100/104 [00:30<00:00,  4.00it/s]

 98%|█████████▊| 102/104 [00:30<00:00,  4.35it/s]

100%|██████████| 104/104 [00:31<00:00,  3.33it/s]
Families:  33%|███▎      | 1/3 [00:31<01:02, 31.22s/it]

Multiplets | family 4:   0%|          | 0/1357 [00:00<?, ?it/s]


  0%|          | 0/1357 [00:00<?, ?it/s]


  0%|          | 1/1357 [00:02<1:00:38,  2.68s/it]


  0%|          | 5/1357 [00:02<09:42,  2.32it/s]


  1%|          | 7/1357 [00:02<06:31,  3.44it/s]


  1%|          | 9/1357 [00:05<13:25,  1.67it/s]


  1%|          | 11/1357 [00:05<09:18,  2.41it/s]


  1%|          | 13/1357 [00:05<07:04,  3.17it/s]


  1%|          | 15/1357 [00:05<05:14,  4.27it/s]


  1%|▏         | 17/1357 [00:07<11:17,  1.98it/s]


  2%|▏         | 21/1357 [00:08<07:14,  3.07it/s]


  2%|▏         | 23/1357 [00:08<05:47,  3.84it/s]


  2%|▏         | 25/1357 [00:10<10:52,  2.04it/s]


  2%|▏         | 27/1357 [00:11<09:07,  2.43it/s]


  2%|▏         | 29/1357 [00:11<06:58,  3.18it/s]


  2%|▏         | 31/1357 [00:11<06:25,  3.44it/s]


  2%|▏         | 33/1357 [00:13<09:36,  2.30it/s]


  3%|▎         | 35/1357 [00:13<08:12,  2.68it/s]


  3%|▎         | 36/1357 [00:14<07:43,  2.85it/s]


  3%|▎         | 37/1357 [00:14<06:47,  3.24it/s]


  3%|▎         | 38/1357 [00:14<06:23,  3.44it/s]


  3%|▎         | 39/1357 [00:14<06:04,  3.62it/s]


  3%|▎         | 40/1357 [00:15<06:27,  3.40it/s]


  3%|▎         | 41/1357 [00:16<10:53,  2.01it/s]


  3%|▎         | 43/1357 [00:16<07:48,  2.81it/s]


  3%|▎         | 44/1357 [00:16<08:30,  2.57it/s]


  3%|▎         | 45/1357 [00:17<07:16,  3.01it/s]


  3%|▎         | 46/1357 [00:17<07:32,  2.90it/s]


  4%|▎         | 48/1357 [00:17<05:51,  3.73it/s]


  4%|▎         | 49/1357 [00:18<09:53,  2.20it/s]


  4%|▎         | 50/1357 [00:18<08:08,  2.68it/s]


  4%|▍         | 51/1357 [00:19<06:34,  3.31it/s]


  4%|▍         | 52/1357 [00:19<08:13,  2.64it/s]


  4%|▍         | 54/1357 [00:20<06:53,  3.15it/s]


  4%|▍         | 56/1357 [00:20<05:44,  3.77it/s]


  4%|▍         | 57/1357 [00:21<08:46,  2.47it/s]


  4%|▍         | 58/1357 [00:21<07:22,  2.94it/s]


  4%|▍         | 59/1357 [00:21<06:46,  3.19it/s]


  4%|▍         | 60/1357 [00:22<07:59,  2.71it/s]


  5%|▍         | 62/1357 [00:22<06:33,  3.29it/s]


  5%|▍         | 64/1357 [00:23<05:52,  3.66it/s]


  5%|▍         | 65/1357 [00:24<08:51,  2.43it/s]


  5%|▍         | 66/1357 [00:24<09:14,  2.33it/s]


  5%|▍         | 67/1357 [00:24<07:54,  2.72it/s]


  5%|▌         | 68/1357 [00:25<07:55,  2.71it/s]


  5%|▌         | 69/1357 [00:25<06:25,  3.35it/s]


  5%|▌         | 70/1357 [00:25<07:10,  2.99it/s]


  5%|▌         | 71/1357 [00:26<08:06,  2.65it/s]


  5%|▌         | 72/1357 [00:26<09:42,  2.21it/s]


  5%|▌         | 73/1357 [00:26<07:55,  2.70it/s]


  5%|▌         | 74/1357 [00:27<08:24,  2.55it/s]


  6%|▌         | 75/1357 [00:27<08:55,  2.40it/s]


  6%|▌         | 76/1357 [00:28<10:37,  2.01it/s]


  6%|▌         | 78/1357 [00:28<07:33,  2.82it/s]


  6%|▌         | 79/1357 [00:30<11:33,  1.84it/s]


  6%|▌         | 80/1357 [00:30<09:08,  2.33it/s]


  6%|▌         | 82/1357 [00:30<08:04,  2.63it/s]


  6%|▌         | 83/1357 [00:31<08:44,  2.43it/s]


  6%|▌         | 84/1357 [00:32<10:12,  2.08it/s]


  6%|▋         | 85/1357 [00:32<08:32,  2.48it/s]


  6%|▋         | 86/1357 [00:32<08:32,  2.48it/s]


  6%|▋         | 87/1357 [00:33<09:30,  2.23it/s]


  7%|▋         | 89/1357 [00:33<08:33,  2.47it/s]


  7%|▋         | 90/1357 [00:34<07:45,  2.72it/s]


  7%|▋         | 91/1357 [00:34<08:56,  2.36it/s]

  7%|▋         | 92/1357 [00:35<10:30,  2.01it/s]


  7%|▋         | 93/1357 [00:35<10:00,  2.10it/s]


  7%|▋         | 96/1357 [00:36<06:50,  3.08it/s]


  7%|▋         | 97/1357 [00:36<07:34,  2.77it/s]


  7%|▋         | 98/1357 [00:37<07:05,  2.96it/s]


  7%|▋         | 99/1357 [00:37<06:57,  3.01it/s]


  7%|▋         | 100/1357 [00:38<08:42,  2.40it/s]


  7%|▋         | 101/1357 [00:38<07:28,  2.80it/s]


  8%|▊         | 103/1357 [00:38<04:54,  4.27it/s]


  8%|▊         | 104/1357 [00:39<06:37,  3.15it/s]


  8%|▊         | 105/1357 [00:39<07:23,  2.82it/s]


  8%|▊         | 106/1357 [00:40<08:03,  2.59it/s]


  8%|▊         | 107/1357 [00:40<07:10,  2.91it/s]


  8%|▊         | 108/1357 [00:40<07:56,  2.62it/s]


  8%|▊         | 109/1357 [00:40<06:40,  3.11it/s]


  8%|▊         | 110/1357 [00:41<06:28,  3.21it/s]


  8%|▊         | 111/1357 [00:41<05:13,  3.98it/s]


  8%|▊         | 112/1357 [00:41<07:33,  2.74it/s]


  8%|▊         | 113/1357 [00:42<06:56,  2.98it/s]


  8%|▊         | 114/1357 [00:42<08:25,  2.46it/s]


  9%|▊         | 116/1357 [00:43<08:03,  2.57it/s]


  9%|▊         | 117/1357 [00:43<06:34,  3.14it/s]


  9%|▊         | 118/1357 [00:44<07:08,  2.89it/s]


  9%|▉         | 119/1357 [00:44<06:03,  3.41it/s]


  9%|▉         | 120/1357 [00:44<07:50,  2.63it/s]


  9%|▉         | 122/1357 [00:45<08:56,  2.30it/s]


  9%|▉         | 124/1357 [00:46<06:54,  2.97it/s]


  9%|▉         | 125/1357 [00:46<06:02,  3.40it/s]


  9%|▉         | 126/1357 [00:46<06:34,  3.12it/s]


  9%|▉         | 127/1357 [00:47<06:31,  3.14it/s]


  9%|▉         | 128/1357 [00:47<08:05,  2.53it/s]


 10%|▉         | 129/1357 [00:47<07:20,  2.79it/s]


 10%|▉         | 130/1357 [00:48<08:28,  2.41it/s]


 10%|▉         | 131/1357 [00:48<07:23,  2.76it/s]


 10%|▉         | 132/1357 [00:48<06:43,  3.03it/s]


 10%|▉         | 133/1357 [00:49<06:59,  2.92it/s]


 10%|▉         | 134/1357 [00:49<07:40,  2.65it/s]


 10%|▉         | 135/1357 [00:50<07:35,  2.68it/s]


 10%|█         | 136/1357 [00:50<06:44,  3.02it/s]


 10%|█         | 137/1357 [00:50<07:55,  2.56it/s]


 10%|█         | 138/1357 [00:51<07:42,  2.64it/s]


 10%|█         | 139/1357 [00:51<06:15,  3.25it/s]


 10%|█         | 140/1357 [00:51<05:36,  3.62it/s]


 10%|█         | 141/1357 [00:51<06:21,  3.19it/s]


 10%|█         | 142/1357 [00:52<06:55,  2.93it/s]


 11%|█         | 143/1357 [00:52<07:20,  2.76it/s]


 11%|█         | 144/1357 [00:52<05:52,  3.44it/s]


 11%|█         | 145/1357 [00:53<08:24,  2.40it/s]


 11%|█         | 146/1357 [00:53<06:44,  2.99it/s]


 11%|█         | 147/1357 [00:54<06:14,  3.23it/s]


 11%|█         | 149/1357 [00:54<05:57,  3.38it/s]


 11%|█         | 150/1357 [00:54<06:19,  3.18it/s]


 11%|█         | 151/1357 [00:55<07:17,  2.76it/s]


 11%|█▏        | 153/1357 [00:56<07:51,  2.55it/s]


 11%|█▏        | 154/1357 [00:56<07:14,  2.77it/s]


 11%|█▏        | 155/1357 [00:56<06:18,  3.18it/s]


 12%|█▏        | 157/1357 [00:57<05:51,  3.41it/s]


 12%|█▏        | 158/1357 [00:57<05:54,  3.38it/s]


 12%|█▏        | 159/1357 [00:58<09:34,  2.08it/s]


 12%|█▏        | 160/1357 [00:58<07:38,  2.61it/s]


 12%|█▏        | 161/1357 [00:58<06:41,  2.98it/s]


 12%|█▏        | 162/1357 [00:59<06:38,  3.00it/s]


 12%|█▏        | 163/1357 [00:59<06:19,  3.15it/s]


 12%|█▏        | 164/1357 [00:59<05:11,  3.83it/s]


 12%|█▏        | 165/1357 [00:59<04:51,  4.09it/s]


 12%|█▏        | 166/1357 [01:00<07:27,  2.66it/s]


 12%|█▏        | 167/1357 [01:01<09:41,  2.05it/s]


 12%|█▏        | 168/1357 [01:01<08:50,  2.24it/s]


 12%|█▏        | 169/1357 [01:01<07:16,  2.72it/s]


 13%|█▎        | 171/1357 [01:02<05:23,  3.67it/s]


 13%|█▎        | 172/1357 [01:02<04:56,  4.00it/s]


 13%|█▎        | 173/1357 [01:02<05:17,  3.72it/s]


 13%|█▎        | 174/1357 [01:03<07:41,  2.56it/s]


 13%|█▎        | 175/1357 [01:03<08:36,  2.29it/s]


 13%|█▎        | 176/1357 [01:04<08:11,  2.40it/s]


 13%|█▎        | 177/1357 [01:04<08:41,  2.26it/s]


 13%|█▎        | 180/1357 [01:05<04:55,  3.98it/s]


 13%|█▎        | 181/1357 [01:05<04:48,  4.07it/s]


 13%|█▎        | 182/1357 [01:06<07:01,  2.79it/s]


 13%|█▎        | 183/1357 [01:06<08:14,  2.37it/s]


 14%|█▎        | 184/1357 [01:07<08:14,  2.37it/s]


 14%|█▎        | 185/1357 [01:07<07:54,  2.47it/s]


 14%|█▍        | 188/1357 [01:07<04:07,  4.72it/s]


 14%|█▍        | 189/1357 [01:07<04:41,  4.15it/s]


 14%|█▍        | 190/1357 [01:08<06:52,  2.83it/s]


 14%|█▍        | 191/1357 [01:09<08:23,  2.31it/s]


 14%|█▍        | 192/1357 [01:09<07:38,  2.54it/s]


 14%|█▍        | 193/1357 [01:10<07:41,  2.52it/s]


 14%|█▍        | 196/1357 [01:10<04:15,  4.55it/s]


 15%|█▍        | 197/1357 [01:10<04:41,  4.12it/s]


 15%|█▍        | 198/1357 [01:11<07:22,  2.62it/s]


 15%|█▍        | 199/1357 [01:12<08:17,  2.33it/s]


 15%|█▍        | 200/1357 [01:12<08:39,  2.23it/s]


 15%|█▍        | 201/1357 [01:12<07:00,  2.75it/s]


 15%|█▍        | 203/1357 [01:12<04:22,  4.40it/s]


 15%|█▌        | 204/1357 [01:13<05:13,  3.68it/s]


 15%|█▌        | 206/1357 [01:14<07:12,  2.66it/s]


 15%|█▌        | 207/1357 [01:15<09:27,  2.03it/s]


 15%|█▌        | 210/1357 [01:15<05:47,  3.30it/s]


 16%|█▌        | 211/1357 [01:15<05:36,  3.40it/s]


 16%|█▌        | 213/1357 [01:16<05:34,  3.42it/s]


 16%|█▌        | 214/1357 [01:16<07:02,  2.71it/s]


 16%|█▌        | 215/1357 [01:17<08:45,  2.17it/s]


 16%|█▌        | 217/1357 [01:18<06:26,  2.95it/s]


 16%|█▌        | 219/1357 [01:18<05:52,  3.22it/s]


 16%|█▌        | 220/1357 [01:18<05:08,  3.69it/s]


 16%|█▋        | 221/1357 [01:18<04:56,  3.84it/s]


 16%|█▋        | 222/1357 [01:19<07:39,  2.47it/s]


 16%|█▋        | 223/1357 [01:20<08:39,  2.18it/s]


 17%|█▋        | 225/1357 [01:20<06:20,  2.98it/s]


 17%|█▋        | 226/1357 [01:20<06:00,  3.13it/s]


 17%|█▋        | 227/1357 [01:21<06:23,  2.94it/s]


 17%|█▋        | 229/1357 [01:21<04:51,  3.88it/s]


 17%|█▋        | 230/1357 [01:22<06:48,  2.76it/s]


 17%|█▋        | 231/1357 [01:23<08:12,  2.29it/s]


 17%|█▋        | 232/1357 [01:23<07:34,  2.47it/s]


 17%|█▋        | 234/1357 [01:23<05:14,  3.57it/s]


 17%|█▋        | 235/1357 [01:23<05:18,  3.53it/s]


 17%|█▋        | 236/1357 [01:24<06:17,  2.97it/s]


 18%|█▊        | 238/1357 [01:25<06:37,  2.82it/s]


 18%|█▊        | 239/1357 [01:25<07:53,  2.36it/s]


 18%|█▊        | 240/1357 [01:25<06:40,  2.79it/s]


 18%|█▊        | 242/1357 [01:26<04:41,  3.96it/s]


 18%|█▊        | 243/1357 [01:26<05:13,  3.55it/s]


 18%|█▊        | 244/1357 [01:27<06:12,  2.99it/s]


 18%|█▊        | 246/1357 [01:27<07:09,  2.59it/s]


 18%|█▊        | 247/1357 [01:28<07:43,  2.39it/s]


 18%|█▊        | 248/1357 [01:28<06:37,  2.79it/s]


 18%|█▊        | 250/1357 [01:28<04:54,  3.75it/s]


 18%|█▊        | 251/1357 [01:29<04:42,  3.92it/s]


 19%|█▊        | 252/1357 [01:29<06:46,  2.72it/s]


 19%|█▊        | 253/1357 [01:30<05:58,  3.08it/s]

 19%|█▊        | 254/1357 [01:30<07:16,  2.53it/s]


 19%|█▉        | 255/1357 [01:31<07:52,  2.33it/s]


 19%|█▉        | 256/1357 [01:31<06:28,  2.84it/s]


 19%|█▉        | 257/1357 [01:31<05:10,  3.54it/s]


 19%|█▉        | 258/1357 [01:31<06:28,  2.83it/s]


 19%|█▉        | 259/1357 [01:32<05:49,  3.14it/s]


 19%|█▉        | 260/1357 [01:32<07:58,  2.29it/s]


 19%|█▉        | 261/1357 [01:33<06:47,  2.69it/s]


 19%|█▉        | 262/1357 [01:33<05:43,  3.19it/s]


 19%|█▉        | 263/1357 [01:33<06:41,  2.72it/s]


 19%|█▉        | 264/1357 [01:34<08:13,  2.21it/s]


 20%|█▉        | 266/1357 [01:34<05:14,  3.47it/s]


 20%|█▉        | 267/1357 [01:34<05:04,  3.58it/s]


 20%|█▉        | 268/1357 [01:35<07:35,  2.39it/s]


 20%|█▉        | 270/1357 [01:36<06:12,  2.92it/s]


 20%|█▉        | 271/1357 [01:36<06:04,  2.98it/s]


 20%|██        | 272/1357 [01:37<07:38,  2.37it/s]


 20%|██        | 273/1357 [01:37<06:12,  2.91it/s]


 20%|██        | 274/1357 [01:37<05:54,  3.06it/s]


 20%|██        | 275/1357 [01:37<04:45,  3.79it/s]


 20%|██        | 276/1357 [01:38<06:53,  2.62it/s]


 20%|██        | 277/1357 [01:38<05:30,  3.26it/s]


 20%|██        | 278/1357 [01:38<06:11,  2.91it/s]


 21%|██        | 279/1357 [01:39<05:22,  3.34it/s]


 21%|██        | 280/1357 [01:39<07:22,  2.43it/s]


 21%|██        | 281/1357 [01:39<06:12,  2.89it/s]


 21%|██        | 282/1357 [01:40<06:04,  2.95it/s]


 21%|██        | 283/1357 [01:40<05:01,  3.56it/s]


 21%|██        | 284/1357 [01:41<06:39,  2.69it/s]


 21%|██        | 285/1357 [01:41<05:36,  3.18it/s]


 21%|██        | 286/1357 [01:41<05:59,  2.98it/s]


 21%|██        | 287/1357 [01:41<05:03,  3.53it/s]


 21%|██        | 288/1357 [01:42<07:27,  2.39it/s]


 21%|██▏       | 290/1357 [01:43<06:09,  2.89it/s]


 21%|██▏       | 291/1357 [01:43<05:08,  3.45it/s]


 22%|██▏       | 292/1357 [01:43<06:12,  2.86it/s]


 22%|██▏       | 293/1357 [01:43<05:43,  3.10it/s]


 22%|██▏       | 294/1357 [01:44<05:47,  3.06it/s]


 22%|██▏       | 295/1357 [01:44<04:53,  3.61it/s]


 22%|██▏       | 296/1357 [01:45<08:39,  2.04it/s]


 22%|██▏       | 297/1357 [01:45<06:50,  2.58it/s]


 22%|██▏       | 298/1357 [01:45<05:58,  2.95it/s]


 22%|██▏       | 300/1357 [01:46<05:36,  3.14it/s]


 22%|██▏       | 301/1357 [01:46<05:55,  2.97it/s]


 22%|██▏       | 302/1357 [01:47<06:19,  2.78it/s]


 22%|██▏       | 303/1357 [01:47<06:31,  2.69it/s]


 22%|██▏       | 304/1357 [01:48<06:53,  2.55it/s]


 22%|██▏       | 305/1357 [01:48<06:05,  2.88it/s]


 23%|██▎       | 306/1357 [01:48<06:31,  2.69it/s]


 23%|██▎       | 308/1357 [01:49<07:00,  2.49it/s]


 23%|██▎       | 309/1357 [01:49<06:27,  2.70it/s]


 23%|██▎       | 311/1357 [01:50<05:36,  3.11it/s]


 23%|██▎       | 312/1357 [01:50<05:41,  3.06it/s]


 23%|██▎       | 313/1357 [01:50<05:20,  3.26it/s]


 23%|██▎       | 314/1357 [01:51<06:23,  2.72it/s]


 23%|██▎       | 316/1357 [01:52<06:59,  2.48it/s]


 23%|██▎       | 317/1357 [01:52<06:32,  2.65it/s]


 23%|██▎       | 318/1357 [01:52<05:36,  3.09it/s]


 24%|██▎       | 319/1357 [01:53<05:50,  2.96it/s]


 24%|██▎       | 320/1357 [01:53<05:28,  3.16it/s]


 24%|██▎       | 321/1357 [01:53<04:32,  3.80it/s]


 24%|██▎       | 322/1357 [01:54<06:11,  2.78it/s]


 24%|██▍       | 324/1357 [01:55<06:37,  2.60it/s]


 24%|██▍       | 325/1357 [01:55<06:56,  2.48it/s]


 24%|██▍       | 326/1357 [01:55<05:36,  3.06it/s]


 24%|██▍       | 327/1357 [01:55<05:01,  3.41it/s]


 24%|██▍       | 328/1357 [01:56<05:36,  3.06it/s]


 24%|██▍       | 330/1357 [01:56<05:24,  3.16it/s]


 24%|██▍       | 331/1357 [01:56<04:41,  3.65it/s]


 24%|██▍       | 332/1357 [01:57<07:03,  2.42it/s]


 25%|██▍       | 333/1357 [01:58<06:47,  2.52it/s]


 25%|██▍       | 335/1357 [01:58<05:13,  3.26it/s]


 25%|██▍       | 336/1357 [01:58<05:30,  3.09it/s]


 25%|██▍       | 338/1357 [01:59<05:19,  3.19it/s]


 25%|██▍       | 339/1357 [01:59<04:33,  3.72it/s]


 25%|██▌       | 340/1357 [02:00<07:00,  2.42it/s]


 25%|██▌       | 341/1357 [02:01<07:36,  2.22it/s]


 25%|██▌       | 342/1357 [02:01<06:07,  2.76it/s]


 25%|██▌       | 344/1357 [02:01<04:54,  3.44it/s]


 25%|██▌       | 346/1357 [02:02<05:16,  3.20it/s]


 26%|██▌       | 347/1357 [02:02<04:54,  3.43it/s]


 26%|██▌       | 348/1357 [02:03<07:03,  2.38it/s]


 26%|██▌       | 349/1357 [02:03<06:41,  2.51it/s]


 26%|██▌       | 350/1357 [02:03<06:24,  2.62it/s]


 26%|██▌       | 351/1357 [02:04<06:04,  2.76it/s]


 26%|██▌       | 352/1357 [02:04<05:02,  3.33it/s]


 26%|██▌       | 354/1357 [02:05<06:21,  2.63it/s]


 26%|██▌       | 355/1357 [02:05<05:18,  3.14it/s]


 26%|██▌       | 356/1357 [02:06<06:22,  2.62it/s]


 26%|██▋       | 357/1357 [02:06<06:55,  2.40it/s]


 26%|██▋       | 359/1357 [02:06<04:58,  3.34it/s]


 27%|██▋       | 360/1357 [02:07<05:01,  3.30it/s]


 27%|██▋       | 361/1357 [02:07<04:23,  3.78it/s]


 27%|██▋       | 362/1357 [02:08<06:46,  2.45it/s]


 27%|██▋       | 364/1357 [02:08<06:08,  2.70it/s]


 27%|██▋       | 365/1357 [02:09<07:18,  2.26it/s]


 27%|██▋       | 368/1357 [02:10<05:30,  2.99it/s]


 27%|██▋       | 370/1357 [02:10<05:20,  3.08it/s]


 27%|██▋       | 371/1357 [02:10<05:02,  3.26it/s]


 27%|██▋       | 372/1357 [02:11<05:45,  2.85it/s]


 27%|██▋       | 373/1357 [02:12<06:55,  2.37it/s]


 28%|██▊       | 375/1357 [02:12<04:31,  3.62it/s]


 28%|██▊       | 376/1357 [02:12<05:22,  3.04it/s]


 28%|██▊       | 377/1357 [02:12<04:38,  3.52it/s]


 28%|██▊       | 378/1357 [02:13<05:30,  2.96it/s]


 28%|██▊       | 379/1357 [02:13<04:52,  3.35it/s]


 28%|██▊       | 380/1357 [02:14<05:55,  2.74it/s]


 28%|██▊       | 381/1357 [02:14<06:58,  2.33it/s]


 28%|██▊       | 382/1357 [02:14<05:32,  2.94it/s]


 28%|██▊       | 383/1357 [02:14<04:26,  3.65it/s]


 28%|██▊       | 384/1357 [02:15<06:06,  2.65it/s]


 28%|██▊       | 386/1357 [02:16<05:12,  3.11it/s]


 29%|██▊       | 387/1357 [02:16<04:55,  3.29it/s]


 29%|██▊       | 388/1357 [02:17<06:44,  2.40it/s]


 29%|██▊       | 389/1357 [02:17<05:51,  2.75it/s]


 29%|██▊       | 390/1357 [02:17<06:01,  2.68it/s]


 29%|██▉       | 392/1357 [02:18<05:04,  3.17it/s]


 29%|██▉       | 393/1357 [02:18<05:48,  2.77it/s]


 29%|██▉       | 394/1357 [02:18<04:58,  3.22it/s]


 29%|██▉       | 395/1357 [02:19<06:43,  2.38it/s]


 29%|██▉       | 396/1357 [02:19<06:09,  2.60it/s]


 29%|██▉       | 397/1357 [02:19<04:52,  3.29it/s]


 29%|██▉       | 398/1357 [02:20<05:22,  2.98it/s]


 29%|██▉       | 399/1357 [02:20<05:32,  2.88it/s]


 29%|██▉       | 400/1357 [02:21<06:00,  2.66it/s]


 30%|██▉       | 401/1357 [02:21<04:47,  3.32it/s]


 30%|██▉       | 402/1357 [02:21<05:35,  2.85it/s]


 30%|██▉       | 403/1357 [02:22<06:44,  2.36it/s]


 30%|██▉       | 404/1357 [02:22<06:15,  2.54it/s]


 30%|██▉       | 405/1357 [02:23<06:01,  2.63it/s]


 30%|██▉       | 407/1357 [02:23<06:33,  2.41it/s]


 30%|███       | 409/1357 [02:24<04:54,  3.22it/s]

 30%|███       | 410/1357 [02:24<04:35,  3.44it/s]


 30%|███       | 411/1357 [02:25<06:14,  2.52it/s]


 30%|███       | 412/1357 [02:25<07:05,  2.22it/s]


 31%|███       | 414/1357 [02:26<04:49,  3.26it/s]


 31%|███       | 415/1357 [02:26<05:42,  2.75it/s]


 31%|███       | 417/1357 [02:27<04:48,  3.26it/s]


 31%|███       | 418/1357 [02:27<04:36,  3.40it/s]


 31%|███       | 419/1357 [02:27<05:41,  2.75it/s]


 31%|███       | 420/1357 [02:28<06:41,  2.33it/s]


 31%|███       | 422/1357 [02:28<04:38,  3.36it/s]


 31%|███       | 423/1357 [02:29<05:06,  3.04it/s]


 31%|███       | 424/1357 [02:29<04:30,  3.45it/s]


 31%|███▏      | 425/1357 [02:29<04:39,  3.33it/s]


 31%|███▏      | 426/1357 [02:29<04:35,  3.38it/s]


 31%|███▏      | 427/1357 [02:30<05:50,  2.65it/s]


 32%|███▏      | 428/1357 [02:31<06:51,  2.26it/s]


 32%|███▏      | 430/1357 [02:31<04:26,  3.47it/s]


 32%|███▏      | 431/1357 [02:31<05:15,  2.93it/s]


 32%|███▏      | 432/1357 [02:32<04:39,  3.31it/s]


 32%|███▏      | 433/1357 [02:32<04:44,  3.24it/s]


 32%|███▏      | 434/1357 [02:32<04:17,  3.58it/s]


 32%|███▏      | 435/1357 [02:33<07:28,  2.05it/s]


 32%|███▏      | 436/1357 [02:33<07:01,  2.19it/s]


 32%|███▏      | 439/1357 [02:34<05:14,  2.92it/s]


 32%|███▏      | 441/1357 [02:35<04:40,  3.27it/s]


 33%|███▎      | 442/1357 [02:35<04:41,  3.25it/s]


 33%|███▎      | 443/1357 [02:36<06:23,  2.38it/s]


 33%|███▎      | 444/1357 [02:36<06:41,  2.27it/s]


 33%|███▎      | 445/1357 [02:37<06:03,  2.51it/s]


 33%|███▎      | 447/1357 [02:37<04:53,  3.10it/s]


 33%|███▎      | 448/1357 [02:37<04:38,  3.27it/s]


 33%|███▎      | 449/1357 [02:37<03:51,  3.92it/s]


 33%|███▎      | 450/1357 [02:38<04:24,  3.43it/s]


 33%|███▎      | 451/1357 [02:39<06:43,  2.25it/s]


 33%|███▎      | 452/1357 [02:39<06:30,  2.32it/s]


 33%|███▎      | 453/1357 [02:39<05:46,  2.61it/s]


 33%|███▎      | 454/1357 [02:40<05:27,  2.76it/s]


 34%|███▎      | 455/1357 [02:40<05:08,  2.92it/s]


 34%|███▎      | 456/1357 [02:40<05:00,  3.00it/s]


 34%|███▍      | 458/1357 [02:40<03:37,  4.13it/s]


 34%|███▍      | 459/1357 [02:41<05:56,  2.52it/s]


 34%|███▍      | 460/1357 [02:42<06:18,  2.37it/s]


 34%|███▍      | 461/1357 [02:42<05:01,  2.97it/s]


 34%|███▍      | 462/1357 [02:42<04:58,  2.99it/s]


 34%|███▍      | 463/1357 [02:43<04:49,  3.08it/s]


 34%|███▍      | 464/1357 [02:43<04:44,  3.14it/s]


 34%|███▍      | 466/1357 [02:43<03:36,  4.12it/s]


 34%|███▍      | 467/1357 [02:44<05:40,  2.61it/s]


 34%|███▍      | 468/1357 [02:44<05:48,  2.55it/s]


 35%|███▍      | 469/1357 [02:45<05:10,  2.86it/s]


 35%|███▍      | 470/1357 [02:45<05:23,  2.74it/s]


 35%|███▍      | 471/1357 [02:45<04:37,  3.19it/s]


 35%|███▍      | 472/1357 [02:46<04:22,  3.37it/s]


 35%|███▍      | 474/1357 [02:46<03:35,  4.10it/s]


 35%|███▌      | 475/1357 [02:47<05:50,  2.52it/s]


 35%|███▌      | 476/1357 [02:47<05:43,  2.57it/s]


 35%|███▌      | 477/1357 [02:47<05:10,  2.83it/s]


 35%|███▌      | 478/1357 [02:48<05:50,  2.51it/s]


 35%|███▌      | 479/1357 [02:48<04:53,  2.99it/s]


 35%|███▌      | 480/1357 [02:48<05:19,  2.75it/s]


 36%|███▌      | 482/1357 [02:49<03:37,  4.03it/s]


 36%|███▌      | 483/1357 [02:50<06:24,  2.27it/s]


 36%|███▌      | 484/1357 [02:50<05:28,  2.66it/s]


 36%|███▌      | 485/1357 [02:50<05:01,  2.90it/s]


 36%|███▌      | 486/1357 [02:51<05:44,  2.53it/s]


 36%|███▌      | 487/1357 [02:51<06:31,  2.22it/s]


 36%|███▌      | 488/1357 [02:51<05:13,  2.77it/s]


 36%|███▌      | 490/1357 [02:52<03:41,  3.92it/s]


 36%|███▌      | 491/1357 [02:53<05:41,  2.53it/s]


 36%|███▋      | 492/1357 [02:53<05:20,  2.70it/s]


 36%|███▋      | 493/1357 [02:53<05:12,  2.77it/s]


 36%|███▋      | 494/1357 [02:54<06:03,  2.37it/s]


 36%|███▋      | 495/1357 [02:54<06:53,  2.08it/s]


 37%|███▋      | 497/1357 [02:54<04:11,  3.43it/s]


 37%|███▋      | 498/1357 [02:55<04:25,  3.24it/s]


 37%|███▋      | 499/1357 [02:55<05:05,  2.81it/s]


 37%|███▋      | 500/1357 [02:56<05:03,  2.82it/s]


 37%|███▋      | 501/1357 [02:56<05:27,  2.61it/s]


 37%|███▋      | 502/1357 [02:57<06:27,  2.20it/s]


 37%|███▋      | 503/1357 [02:57<06:07,  2.32it/s]


 37%|███▋      | 505/1357 [02:57<04:18,  3.30it/s]


 37%|███▋      | 506/1357 [02:58<04:13,  3.35it/s]


 37%|███▋      | 507/1357 [02:58<04:48,  2.95it/s]


 37%|███▋      | 508/1357 [02:58<04:11,  3.37it/s]


 38%|███▊      | 509/1357 [02:59<05:31,  2.56it/s]


 38%|███▊      | 510/1357 [02:59<05:32,  2.55it/s]


 38%|███▊      | 511/1357 [03:00<05:46,  2.44it/s]


 38%|███▊      | 513/1357 [03:00<04:17,  3.28it/s]


 38%|███▊      | 514/1357 [03:00<03:39,  3.85it/s]


 38%|███▊      | 515/1357 [03:01<04:32,  3.09it/s]


 38%|███▊      | 516/1357 [03:01<03:48,  3.68it/s]


 38%|███▊      | 517/1357 [03:02<05:25,  2.58it/s]


 38%|███▊      | 518/1357 [03:02<05:31,  2.53it/s]


 38%|███▊      | 519/1357 [03:02<05:30,  2.53it/s]


 38%|███▊      | 521/1357 [03:03<04:22,  3.18it/s]


 38%|███▊      | 522/1357 [03:03<03:49,  3.64it/s]


 39%|███▊      | 523/1357 [03:04<04:46,  2.91it/s]


 39%|███▊      | 524/1357 [03:04<04:06,  3.38it/s]


 39%|███▊      | 525/1357 [03:04<04:57,  2.80it/s]


 39%|███▉      | 526/1357 [03:05<05:38,  2.45it/s]


 39%|███▉      | 527/1357 [03:05<05:23,  2.57it/s]


 39%|███▉      | 528/1357 [03:05<04:52,  2.84it/s]


 39%|███▉      | 529/1357 [03:06<04:24,  3.13it/s]


 39%|███▉      | 530/1357 [03:06<05:17,  2.60it/s]


 39%|███▉      | 531/1357 [03:06<04:42,  2.93it/s]


 39%|███▉      | 533/1357 [03:07<05:12,  2.63it/s]


 39%|███▉      | 534/1357 [03:08<05:00,  2.73it/s]


 39%|███▉      | 535/1357 [03:08<05:13,  2.62it/s]


 39%|███▉      | 536/1357 [03:08<05:00,  2.74it/s]


Multiplets | family 3:   0%|          | 0/104 [03:40<?, ?it/s]



 40%|███▉      | 538/1357 [03:09<05:29,  2.48it/s]


 40%|███▉      | 540/1357 [03:10<04:06,  3.32it/s]


 40%|███▉      | 541/1357 [03:10<04:27,  3.05it/s]


 40%|███▉      | 542/1357 [03:10<04:57,  2.74it/s]


 40%|████      | 543/1357 [03:11<05:42,  2.37it/s]


 40%|████      | 545/1357 [03:11<04:39,  2.91it/s]


 40%|████      | 546/1357 [03:12<05:08,  2.63it/s]


 40%|████      | 547/1357 [03:12<04:49,  2.79it/s]


 40%|████      | 549/1357 [03:13<04:29,  3.00it/s]


 41%|████      | 550/1357 [03:13<04:28,  3.00it/s]


 41%|████      | 551/1357 [03:14<05:03,  2.65it/s]


 41%|████      | 552/1357 [03:14<04:24,  3.04it/s]


 41%|████      | 553/1357 [03:14<05:12,  2.58it/s]


 41%|████      | 554/1357 [03:15<04:24,  3.04it/s]


 41%|████      | 555/1357 [03:15<04:20,  3.08it/s]


 41%|████      | 556/1357 [03:15<03:28,  3.84it/s]


 41%|████      | 557/1357 [03:15<04:03,  3.28it/s]


 41%|████      | 558/1357 [03:16<04:24,  3.02it/s]


 41%|████      | 559/1357 [03:16<05:17,  2.51it/s]


 41%|████▏     | 560/1357 [03:17<04:44,  2.80it/s]


 41%|████▏     | 561/1357 [03:17<05:01,  2.64it/s]


 41%|████▏     | 562/1357 [03:17<04:21,  3.04it/s]

 41%|████▏     | 563/1357 [03:18<04:02,  3.27it/s]


 42%|████▏     | 564/1357 [03:18<03:41,  3.59it/s]


 42%|████▏     | 565/1357 [03:18<03:58,  3.32it/s]


 42%|████▏     | 566/1357 [03:19<04:26,  2.97it/s]


 42%|████▏     | 567/1357 [03:19<05:14,  2.51it/s]


 42%|████▏     | 568/1357 [03:19<05:03,  2.60it/s]


 42%|████▏     | 569/1357 [03:20<05:15,  2.50it/s]


 42%|████▏     | 570/1357 [03:20<04:15,  3.08it/s]


 42%|████▏     | 571/1357 [03:20<03:23,  3.87it/s]


 42%|████▏     | 572/1357 [03:20<03:38,  3.60it/s]


 42%|████▏     | 573/1357 [03:21<03:46,  3.46it/s]


 42%|████▏     | 574/1357 [03:21<04:22,  2.98it/s]


 42%|████▏     | 575/1357 [03:22<04:52,  2.67it/s]


 42%|████▏     | 576/1357 [03:22<05:51,  2.22it/s]


 43%|████▎     | 577/1357 [03:23<05:26,  2.39it/s]


 43%|████▎     | 578/1357 [03:23<04:15,  3.04it/s]


 43%|████▎     | 579/1357 [03:23<04:24,  2.94it/s]


 43%|████▎     | 580/1357 [03:23<03:31,  3.67it/s]


 43%|████▎     | 581/1357 [03:23<03:32,  3.66it/s]


 43%|████▎     | 582/1357 [03:24<04:52,  2.65it/s]


 43%|████▎     | 583/1357 [03:25<05:55,  2.18it/s]


 43%|████▎     | 584/1357 [03:25<05:51,  2.20it/s]


 43%|████▎     | 585/1357 [03:25<04:50,  2.66it/s]


 43%|████▎     | 586/1357 [03:26<04:54,  2.62it/s]


 43%|████▎     | 588/1357 [03:26<03:50,  3.34it/s]


 43%|████▎     | 590/1357 [03:27<03:46,  3.38it/s]


 44%|████▎     | 591/1357 [03:28<05:25,  2.35it/s]


 44%|████▎     | 592/1357 [03:28<04:56,  2.58it/s]


 44%|████▎     | 593/1357 [03:28<04:22,  2.91it/s]


 44%|████▍     | 594/1357 [03:29<04:41,  2.71it/s]


 44%|████▍     | 595/1357 [03:29<03:53,  3.27it/s]


 44%|████▍     | 596/1357 [03:29<04:19,  2.93it/s]


 44%|████▍     | 598/1357 [03:30<03:40,  3.45it/s]


 44%|████▍     | 599/1357 [03:31<05:36,  2.26it/s]


 44%|████▍     | 600/1357 [03:31<04:37,  2.73it/s]


 44%|████▍     | 601/1357 [03:31<04:35,  2.74it/s]


 44%|████▍     | 602/1357 [03:31<04:17,  2.93it/s]


 44%|████▍     | 603/1357 [03:32<04:23,  2.86it/s]


 45%|████▍     | 605/1357 [03:32<03:07,  4.02it/s]


 45%|████▍     | 606/1357 [03:32<03:36,  3.47it/s]


 45%|████▍     | 607/1357 [03:33<05:46,  2.16it/s]


 45%|████▍     | 609/1357 [03:34<04:20,  2.87it/s]


 45%|████▍     | 610/1357 [03:34<04:16,  2.91it/s]


 45%|████▌     | 611/1357 [03:34<04:01,  3.09it/s]


 45%|████▌     | 612/1357 [03:34<03:17,  3.77it/s]


 45%|████▌     | 613/1357 [03:35<03:12,  3.87it/s]


 45%|████▌     | 614/1357 [03:35<04:00,  3.09it/s]


 45%|████▌     | 615/1357 [03:36<05:45,  2.15it/s]


 45%|████▌     | 616/1357 [03:36<04:27,  2.77it/s]


 45%|████▌     | 617/1357 [03:36<04:23,  2.80it/s]


 46%|████▌     | 618/1357 [03:37<04:20,  2.83it/s]


 46%|████▌     | 619/1357 [03:37<04:38,  2.65it/s]


 46%|████▌     | 620/1357 [03:37<04:23,  2.79it/s]


 46%|████▌     | 622/1357 [03:38<04:45,  2.57it/s]


 46%|████▌     | 623/1357 [03:39<04:44,  2.58it/s]


 46%|████▌     | 625/1357 [03:39<03:40,  3.33it/s]


 46%|████▌     | 626/1357 [03:40<04:35,  2.65it/s]


 46%|████▌     | 627/1357 [03:40<04:49,  2.52it/s]


 46%|████▋     | 629/1357 [03:41<03:47,  3.20it/s]


 46%|████▋     | 630/1357 [03:41<05:18,  2.28it/s]


 47%|████▋     | 632/1357 [03:42<03:29,  3.47it/s]


 47%|████▋     | 633/1357 [03:42<03:16,  3.68it/s]


 47%|████▋     | 634/1357 [03:43<04:47,  2.52it/s]


 47%|████▋     | 635/1357 [03:43<05:12,  2.31it/s]


 47%|████▋     | 636/1357 [03:43<04:19,  2.77it/s]


 47%|████▋     | 637/1357 [03:44<04:14,  2.83it/s]


 47%|████▋     | 638/1357 [03:44<04:59,  2.40it/s]


 47%|████▋     | 640/1357 [03:45<03:49,  3.12it/s]


 47%|████▋     | 642/1357 [03:45<04:00,  2.98it/s]


 47%|████▋     | 643/1357 [03:46<04:43,  2.52it/s]


 47%|████▋     | 644/1357 [03:46<04:04,  2.91it/s]


 48%|████▊     | 645/1357 [03:46<03:49,  3.10it/s]


 48%|████▊     | 646/1357 [03:47<04:20,  2.73it/s]


 48%|████▊     | 647/1357 [03:47<03:47,  3.13it/s]


 48%|████▊     | 648/1357 [03:47<03:38,  3.25it/s]


 48%|████▊     | 649/1357 [03:47<02:56,  4.01it/s]


 48%|████▊     | 650/1357 [03:48<04:07,  2.85it/s]


 48%|████▊     | 651/1357 [03:49<05:29,  2.14it/s]


 48%|████▊     | 652/1357 [03:49<04:26,  2.65it/s]


 48%|████▊     | 653/1357 [03:49<03:34,  3.28it/s]


 48%|████▊     | 654/1357 [03:50<04:29,  2.61it/s]


 48%|████▊     | 655/1357 [03:50<03:41,  3.17it/s]


 48%|████▊     | 656/1357 [03:50<03:27,  3.38it/s]


 48%|████▊     | 657/1357 [03:50<02:50,  4.11it/s]


 48%|████▊     | 658/1357 [03:51<04:16,  2.73it/s]


 49%|████▊     | 659/1357 [03:51<04:57,  2.35it/s]


 49%|████▊     | 660/1357 [03:52<04:38,  2.50it/s]


 49%|████▉     | 662/1357 [03:52<04:03,  2.86it/s]


 49%|████▉     | 663/1357 [03:53<04:19,  2.68it/s]


 49%|████▉     | 664/1357 [03:53<04:18,  2.68it/s]


 49%|████▉     | 665/1357 [03:53<03:47,  3.04it/s]


 49%|████▉     | 666/1357 [03:54<04:13,  2.73it/s]


 49%|████▉     | 667/1357 [03:54<03:44,  3.07it/s]


 49%|████▉     | 668/1357 [03:54<04:07,  2.78it/s]


 49%|████▉     | 669/1357 [03:55<03:46,  3.04it/s]


 49%|████▉     | 670/1357 [03:55<05:02,  2.27it/s]


 49%|████▉     | 671/1357 [03:56<03:54,  2.92it/s]


 50%|████▉     | 672/1357 [03:56<04:44,  2.41it/s]


 50%|████▉     | 673/1357 [03:57<04:47,  2.38it/s]


 50%|████▉     | 675/1357 [03:57<03:33,  3.19it/s]


 50%|████▉     | 676/1357 [03:57<04:03,  2.79it/s]


 50%|████▉     | 678/1357 [03:58<04:39,  2.43it/s]


 50%|█████     | 679/1357 [03:59<04:17,  2.63it/s]


 50%|█████     | 680/1357 [03:59<03:47,  2.98it/s]


 50%|█████     | 681/1357 [03:59<04:07,  2.73it/s]


 50%|█████     | 682/1357 [04:00<04:02,  2.79it/s]


 50%|█████     | 683/1357 [04:00<03:53,  2.89it/s]


 50%|█████     | 684/1357 [04:00<03:54,  2.87it/s]


 50%|█████     | 685/1357 [04:00<03:23,  3.31it/s]


 51%|█████     | 686/1357 [04:01<04:34,  2.44it/s]


 51%|█████     | 687/1357 [04:01<04:03,  2.75it/s]


 51%|█████     | 688/1357 [04:02<03:38,  3.06it/s]


 51%|█████     | 689/1357 [04:02<04:10,  2.67it/s]


 51%|█████     | 690/1357 [04:02<03:45,  2.96it/s]


 51%|█████     | 691/1357 [04:03<03:36,  3.08it/s]


 51%|█████     | 692/1357 [04:03<03:49,  2.90it/s]


 51%|█████     | 693/1357 [04:03<03:24,  3.24it/s]


 51%|█████     | 694/1357 [04:04<04:13,  2.61it/s]


 51%|█████     | 695/1357 [04:04<03:59,  2.76it/s]


 51%|█████▏    | 696/1357 [04:04<03:28,  3.17it/s]


 51%|█████▏    | 697/1357 [04:05<03:59,  2.75it/s]


 51%|█████▏    | 698/1357 [04:05<03:42,  2.96it/s]


 52%|█████▏    | 699/1357 [04:05<03:34,  3.06it/s]


 52%|█████▏    | 700/1357 [04:06<03:31,  3.11it/s]


 52%|█████▏    | 701/1357 [04:06<03:21,  3.26it/s]


 52%|█████▏    | 702/1357 [04:07<04:27,  2.44it/s]


 52%|█████▏    | 703/1357 [04:07<04:14,  2.57it/s]


 52%|█████▏    | 705/1357 [04:08<03:37,  3.00it/s]


 52%|█████▏    | 706/1357 [04:08<03:30,  3.09it/s]


 52%|█████▏    | 707/1357 [04:08<04:06,  2.64it/s]


 52%|█████▏    | 708/1357 [04:09<03:54,  2.77it/s]


 52%|█████▏    | 710/1357 [04:09<03:43,  2.90it/s]

 52%|█████▏    | 711/1357 [04:10<04:01,  2.68it/s]


 53%|█████▎    | 713/1357 [04:10<03:36,  2.97it/s]


 53%|█████▎    | 714/1357 [04:11<04:29,  2.38it/s]


 53%|█████▎    | 715/1357 [04:11<03:40,  2.92it/s]


 53%|█████▎    | 716/1357 [04:11<03:34,  2.98it/s]


 53%|█████▎    | 718/1357 [04:12<03:57,  2.69it/s]


 53%|█████▎    | 719/1357 [04:13<03:41,  2.89it/s]


 53%|█████▎    | 720/1357 [04:13<03:05,  3.44it/s]


 53%|█████▎    | 721/1357 [04:13<04:16,  2.48it/s]


 53%|█████▎    | 722/1357 [04:14<04:07,  2.57it/s]


 53%|█████▎    | 723/1357 [04:14<03:18,  3.19it/s]


 53%|█████▎    | 724/1357 [04:14<03:30,  3.01it/s]


 53%|█████▎    | 725/1357 [04:14<02:59,  3.51it/s]


 54%|█████▎    | 726/1357 [04:15<03:43,  2.83it/s]


 54%|█████▎    | 727/1357 [04:15<03:51,  2.72it/s]


 54%|█████▎    | 728/1357 [04:16<03:56,  2.66it/s]


 54%|█████▎    | 729/1357 [04:16<04:03,  2.58it/s]


 54%|█████▍    | 730/1357 [04:17<03:49,  2.73it/s]


 54%|█████▍    | 731/1357 [04:17<03:51,  2.71it/s]


 54%|█████▍    | 732/1357 [04:17<03:33,  2.92it/s]


 54%|█████▍    | 733/1357 [04:17<02:50,  3.65it/s]


 54%|█████▍    | 734/1357 [04:18<03:13,  3.22it/s]


 54%|█████▍    | 735/1357 [04:18<03:54,  2.65it/s]


 54%|█████▍    | 736/1357 [04:19<04:08,  2.50it/s]


 54%|█████▍    | 737/1357 [04:19<04:03,  2.54it/s]


 54%|█████▍    | 738/1357 [04:19<03:19,  3.11it/s]


 54%|█████▍    | 739/1357 [04:20<03:30,  2.93it/s]


 55%|█████▍    | 740/1357 [04:20<03:32,  2.90it/s]


 55%|█████▍    | 742/1357 [04:20<02:46,  3.69it/s]


 55%|█████▍    | 743/1357 [04:21<03:41,  2.77it/s]


 55%|█████▍    | 744/1357 [04:21<04:00,  2.55it/s]


 55%|█████▍    | 745/1357 [04:22<03:43,  2.74it/s]


 55%|█████▍    | 746/1357 [04:22<03:11,  3.20it/s]


 55%|█████▌    | 747/1357 [04:22<03:31,  2.89it/s]


 55%|█████▌    | 748/1357 [04:23<03:41,  2.75it/s]


 55%|█████▌    | 749/1357 [04:23<03:11,  3.18it/s]


 55%|█████▌    | 750/1357 [04:23<02:34,  3.93it/s]


 55%|█████▌    | 751/1357 [04:24<03:41,  2.74it/s]


 55%|█████▌    | 752/1357 [04:24<04:31,  2.23it/s]


 55%|█████▌    | 753/1357 [04:25<04:04,  2.47it/s]


 56%|█████▌    | 754/1357 [04:25<03:51,  2.60it/s]


 56%|█████▌    | 756/1357 [04:25<03:18,  3.02it/s]


 56%|█████▌    | 757/1357 [04:26<03:31,  2.84it/s]


 56%|█████▌    | 759/1357 [04:27<04:00,  2.48it/s]


 56%|█████▌    | 760/1357 [04:27<03:22,  2.95it/s]


 56%|█████▌    | 761/1357 [04:27<03:30,  2.83it/s]


 56%|█████▌    | 762/1357 [04:28<03:42,  2.67it/s]


 56%|█████▌    | 763/1357 [04:28<03:46,  2.62it/s]


 56%|█████▋    | 764/1357 [04:28<03:23,  2.92it/s]


 56%|█████▋    | 765/1357 [04:29<02:53,  3.42it/s]


 56%|█████▋    | 766/1357 [04:29<03:16,  3.01it/s]


 57%|█████▋    | 767/1357 [04:29<03:37,  2.72it/s]


 57%|█████▋    | 768/1357 [04:30<03:03,  3.20it/s]


 57%|█████▋    | 769/1357 [04:30<03:47,  2.59it/s]


 57%|█████▋    | 770/1357 [04:31<04:55,  1.99it/s]


 57%|█████▋    | 772/1357 [04:31<03:37,  2.69it/s]


 57%|█████▋    | 774/1357 [04:32<02:40,  3.64it/s]


 57%|█████▋    | 775/1357 [04:32<03:04,  3.15it/s]


 57%|█████▋    | 776/1357 [04:33<03:23,  2.86it/s]


 57%|█████▋    | 777/1357 [04:33<03:48,  2.54it/s]


 57%|█████▋    | 778/1357 [04:34<04:13,  2.28it/s]


 57%|█████▋    | 780/1357 [04:34<03:30,  2.75it/s]


 58%|█████▊    | 782/1357 [04:34<02:33,  3.74it/s]


 58%|█████▊    | 783/1357 [04:35<02:45,  3.47it/s]


 58%|█████▊    | 784/1357 [04:35<03:23,  2.81it/s]


 58%|█████▊    | 785/1357 [04:36<03:33,  2.68it/s]


 58%|█████▊    | 786/1357 [04:36<03:58,  2.40it/s]


 58%|█████▊    | 788/1357 [04:37<03:28,  2.72it/s]


 58%|█████▊    | 790/1357 [04:37<02:22,  3.97it/s]


 58%|█████▊    | 791/1357 [04:38<02:44,  3.45it/s]


 58%|█████▊    | 792/1357 [04:38<03:23,  2.78it/s]


 58%|█████▊    | 793/1357 [04:39<03:49,  2.46it/s]


 59%|█████▊    | 794/1357 [04:39<03:42,  2.53it/s]


 59%|█████▊    | 796/1357 [04:40<03:17,  2.84it/s]


 59%|█████▊    | 797/1357 [04:40<02:50,  3.28it/s]


 59%|█████▉    | 798/1357 [04:40<02:37,  3.55it/s]


 59%|█████▉    | 799/1357 [04:40<02:42,  3.44it/s]


 59%|█████▉    | 800/1357 [04:41<03:43,  2.49it/s]


 59%|█████▉    | 801/1357 [04:42<04:19,  2.14it/s]


 59%|█████▉    | 803/1357 [04:42<02:51,  3.24it/s]


 59%|█████▉    | 804/1357 [04:43<04:29,  2.05it/s]


 59%|█████▉    | 806/1357 [04:43<02:54,  3.15it/s]


 60%|█████▉    | 808/1357 [04:44<03:05,  2.96it/s]


 60%|█████▉    | 809/1357 [04:44<03:31,  2.60it/s]


 60%|█████▉    | 810/1357 [04:45<03:15,  2.80it/s]


 60%|█████▉    | 812/1357 [04:46<03:46,  2.40it/s]


 60%|█████▉    | 813/1357 [04:46<03:17,  2.76it/s]


 60%|█████▉    | 814/1357 [04:46<02:47,  3.23it/s]


 60%|██████    | 816/1357 [04:47<03:20,  2.70it/s]


 60%|██████    | 817/1357 [04:47<03:07,  2.88it/s]


 60%|██████    | 818/1357 [04:47<02:57,  3.04it/s]


 60%|██████    | 819/1357 [04:48<02:43,  3.29it/s]


 60%|██████    | 820/1357 [04:49<04:14,  2.11it/s]


 61%|██████    | 821/1357 [04:49<03:38,  2.46it/s]


 61%|██████    | 822/1357 [04:49<03:11,  2.80it/s]


 61%|██████    | 823/1357 [04:49<02:56,  3.02it/s]


 61%|██████    | 824/1357 [04:50<03:48,  2.34it/s]


 61%|██████    | 826/1357 [04:50<02:50,  3.11it/s]


 61%|██████    | 827/1357 [04:51<02:38,  3.34it/s]


 61%|██████    | 828/1357 [04:51<03:53,  2.27it/s]


 61%|██████    | 830/1357 [04:52<02:44,  3.21it/s]


 61%|██████    | 831/1357 [04:52<02:36,  3.35it/s]


 61%|██████▏   | 832/1357 [04:53<03:47,  2.31it/s]


 61%|██████▏   | 834/1357 [04:53<02:36,  3.34it/s]


 62%|██████▏   | 835/1357 [04:53<02:34,  3.38it/s]


 62%|██████▏   | 836/1357 [04:54<03:54,  2.22it/s]


 62%|██████▏   | 839/1357 [04:55<02:42,  3.19it/s]


 62%|██████▏   | 840/1357 [04:56<03:35,  2.40it/s]


 62%|██████▏   | 841/1357 [04:56<03:37,  2.37it/s]


 62%|██████▏   | 842/1357 [04:56<02:59,  2.88it/s]


 62%|██████▏   | 844/1357 [04:57<03:14,  2.64it/s]


 62%|██████▏   | 845/1357 [04:57<02:42,  3.16it/s]


 62%|██████▏   | 846/1357 [04:57<02:45,  3.09it/s]


 62%|██████▏   | 847/1357 [04:58<02:48,  3.02it/s]


 62%|██████▏   | 848/1357 [04:58<03:26,  2.46it/s]


 63%|██████▎   | 849/1357 [04:59<03:56,  2.15it/s]


 63%|██████▎   | 851/1357 [04:59<02:38,  3.20it/s]


 63%|██████▎   | 852/1357 [05:00<03:38,  2.31it/s]


 63%|██████▎   | 853/1357 [05:00<03:11,  2.64it/s]


 63%|██████▎   | 854/1357 [05:00<02:43,  3.07it/s]


 63%|██████▎   | 855/1357 [05:01<02:56,  2.84it/s]


 63%|██████▎   | 856/1357 [05:01<02:53,  2.89it/s]


 63%|██████▎   | 857/1357 [05:02<03:58,  2.10it/s]


 63%|██████▎   | 858/1357 [05:02<03:03,  2.72it/s]


 63%|██████▎   | 860/1357 [05:03<03:12,  2.58it/s]


 63%|██████▎   | 861/1357 [05:03<02:49,  2.92it/s]


 64%|██████▎   | 862/1357 [05:03<02:32,  3.25it/s]


 64%|██████▎   | 863/1357 [05:04<03:02,  2.71it/s]


 64%|██████▎   | 864/1357 [05:04<03:04,  2.67it/s]


 64%|██████▎   | 865/1357 [05:05<03:18,  2.48it/s]


 64%|██████▍   | 866/1357 [05:05<02:58,  2.75it/s]


 64%|██████▍   | 867/1357 [05:05<02:27,  3.32it/s]

 64%|██████▍   | 868/1357 [05:06<02:56,  2.77it/s]


 64%|██████▍   | 869/1357 [05:06<03:05,  2.63it/s]


 64%|██████▍   | 871/1357 [05:07<02:41,  3.00it/s]


 64%|██████▍   | 872/1357 [05:07<02:58,  2.72it/s]


 64%|██████▍   | 873/1357 [05:07<02:54,  2.77it/s]


 64%|██████▍   | 874/1357 [05:08<02:47,  2.89it/s]


 64%|██████▍   | 875/1357 [05:08<02:26,  3.29it/s]


 65%|██████▍   | 876/1357 [05:08<02:34,  3.12it/s]


 65%|██████▍   | 877/1357 [05:09<02:59,  2.67it/s]


 65%|██████▍   | 878/1357 [05:09<02:24,  3.32it/s]


 65%|██████▍   | 879/1357 [05:09<02:38,  3.02it/s]


 65%|██████▍   | 880/1357 [05:10<03:12,  2.47it/s]


 65%|██████▍   | 881/1357 [05:10<02:50,  2.79it/s]


 65%|██████▍   | 882/1357 [05:10<02:36,  3.03it/s]


 65%|██████▌   | 883/1357 [05:11<02:18,  3.43it/s]


 65%|██████▌   | 884/1357 [05:11<02:22,  3.32it/s]


 65%|██████▌   | 885/1357 [05:12<03:01,  2.61it/s]


 65%|██████▌   | 886/1357 [05:12<03:10,  2.47it/s]


 65%|██████▌   | 887/1357 [05:12<02:37,  2.98it/s]


 65%|██████▌   | 888/1357 [05:13<03:00,  2.59it/s]


 66%|██████▌   | 889/1357 [05:13<02:48,  2.78it/s]


 66%|██████▌   | 890/1357 [05:14<03:09,  2.46it/s]


 66%|██████▌   | 892/1357 [05:14<01:53,  4.09it/s]


 66%|██████▌   | 893/1357 [05:15<03:06,  2.49it/s]


 66%|██████▌   | 894/1357 [05:15<03:09,  2.44it/s]


 66%|██████▌   | 896/1357 [05:16<04:00,  1.92it/s]


 66%|██████▌   | 899/1357 [05:16<02:16,  3.36it/s]


 66%|██████▋   | 900/1357 [05:17<02:10,  3.50it/s]


 66%|██████▋   | 901/1357 [05:18<03:05,  2.45it/s]


 66%|██████▋   | 902/1357 [05:18<02:55,  2.59it/s]


 67%|██████▋   | 904/1357 [05:19<03:42,  2.04it/s]


 67%|██████▋   | 905/1357 [05:19<03:06,  2.43it/s]


 67%|██████▋   | 908/1357 [05:20<02:06,  3.54it/s]


 67%|██████▋   | 909/1357 [05:20<02:23,  3.12it/s]


 67%|██████▋   | 910/1357 [05:21<02:38,  2.83it/s]


 67%|██████▋   | 911/1357 [05:21<02:17,  3.23it/s]


 67%|██████▋   | 912/1357 [05:22<03:50,  1.93it/s]


 67%|██████▋   | 915/1357 [05:22<02:10,  3.38it/s]


 68%|██████▊   | 916/1357 [05:23<02:09,  3.41it/s]


 68%|██████▊   | 917/1357 [05:23<02:42,  2.71it/s]


 68%|██████▊   | 918/1357 [05:24<02:54,  2.52it/s]


 68%|██████▊   | 920/1357 [05:25<03:15,  2.23it/s]


 68%|██████▊   | 922/1357 [05:25<02:14,  3.24it/s]


 68%|██████▊   | 923/1357 [05:25<02:06,  3.44it/s]


 68%|██████▊   | 924/1357 [05:25<02:04,  3.49it/s]


 68%|██████▊   | 925/1357 [05:26<02:28,  2.92it/s]


 68%|██████▊   | 926/1357 [05:26<02:47,  2.58it/s]


 68%|██████▊   | 928/1357 [05:27<03:12,  2.23it/s]


 68%|██████▊   | 929/1357 [05:28<02:39,  2.68it/s]


 69%|██████▊   | 931/1357 [05:28<01:53,  3.77it/s]


 69%|██████▊   | 932/1357 [05:28<02:20,  3.02it/s]


 69%|██████▉   | 933/1357 [05:29<02:17,  3.09it/s]


 69%|██████▉   | 934/1357 [05:29<02:28,  2.86it/s]


 69%|██████▉   | 935/1357 [05:30<02:37,  2.67it/s]


 69%|██████▉   | 936/1357 [05:30<03:10,  2.21it/s]


 69%|██████▉   | 937/1357 [05:30<02:34,  2.72it/s]


 69%|██████▉   | 938/1357 [05:30<02:02,  3.42it/s]


 69%|██████▉   | 939/1357 [05:31<02:22,  2.94it/s]


 69%|██████▉   | 940/1357 [05:32<02:57,  2.35it/s]


 69%|██████▉   | 942/1357 [05:32<02:16,  3.03it/s]


 69%|██████▉   | 943/1357 [05:33<02:41,  2.57it/s]


 70%|██████▉   | 944/1357 [05:33<02:54,  2.37it/s]


 70%|██████▉   | 945/1357 [05:34<03:15,  2.11it/s]


 70%|██████▉   | 946/1357 [05:34<02:35,  2.64it/s]


 70%|██████▉   | 948/1357 [05:34<02:13,  3.05it/s]


 70%|██████▉   | 949/1357 [05:35<02:26,  2.79it/s]


 70%|███████   | 950/1357 [05:35<02:12,  3.08it/s]


 70%|███████   | 951/1357 [05:35<02:22,  2.85it/s]


 70%|███████   | 952/1357 [05:37<03:47,  1.78it/s]


 70%|███████   | 954/1357 [05:37<02:20,  2.88it/s]


 70%|███████   | 955/1357 [05:37<01:58,  3.38it/s]


 70%|███████   | 956/1357 [05:37<01:58,  3.38it/s]


 71%|███████   | 957/1357 [05:38<02:22,  2.80it/s]


 71%|███████   | 958/1357 [05:38<02:09,  3.07it/s]


 71%|███████   | 959/1357 [05:38<02:15,  2.94it/s]


 71%|███████   | 960/1357 [05:39<03:28,  1.91it/s]


 71%|███████   | 961/1357 [05:39<02:41,  2.46it/s]


 71%|███████   | 962/1357 [05:39<02:06,  3.13it/s]


 71%|███████   | 964/1357 [05:40<01:42,  3.83it/s]


 71%|███████   | 965/1357 [05:40<02:06,  3.09it/s]


 71%|███████   | 966/1357 [05:41<01:51,  3.51it/s]


 71%|███████▏  | 967/1357 [05:41<02:20,  2.77it/s]


 71%|███████▏  | 968/1357 [05:42<03:08,  2.07it/s]


 71%|███████▏  | 969/1357 [05:42<02:32,  2.55it/s]


 71%|███████▏  | 970/1357 [05:42<02:09,  2.99it/s]


 72%|███████▏  | 972/1357 [05:43<01:35,  4.02it/s]


 72%|███████▏  | 973/1357 [05:43<02:06,  3.03it/s]


 72%|███████▏  | 974/1357 [05:43<01:57,  3.26it/s]


 72%|███████▏  | 975/1357 [05:44<02:20,  2.72it/s]


 72%|███████▏  | 976/1357 [05:45<03:15,  1.95it/s]


 72%|███████▏  | 978/1357 [05:45<02:04,  3.06it/s]


 72%|███████▏  | 979/1357 [05:45<01:51,  3.38it/s]


 72%|███████▏  | 981/1357 [05:46<01:57,  3.21it/s]


 72%|███████▏  | 982/1357 [05:46<01:56,  3.21it/s]


 72%|███████▏  | 983/1357 [05:47<02:25,  2.57it/s]


 73%|███████▎  | 984/1357 [05:47<02:54,  2.14it/s]


 73%|███████▎  | 985/1357 [05:48<02:34,  2.41it/s]


 73%|███████▎  | 987/1357 [05:48<01:43,  3.59it/s]


 73%|███████▎  | 988/1357 [05:48<01:30,  4.10it/s]


 73%|███████▎  | 989/1357 [05:49<02:04,  2.95it/s]


 73%|███████▎  | 990/1357 [05:49<02:00,  3.04it/s]


 73%|███████▎  | 991/1357 [05:50<02:33,  2.38it/s]


 73%|███████▎  | 992/1357 [05:50<03:00,  2.02it/s]


 73%|███████▎  | 993/1357 [05:50<02:20,  2.59it/s]


 73%|███████▎  | 994/1357 [05:51<02:26,  2.49it/s]


 73%|███████▎  | 997/1357 [05:52<01:48,  3.33it/s]


 74%|███████▎  | 998/1357 [05:52<01:53,  3.17it/s]


 74%|███████▎  | 999/1357 [05:52<02:11,  2.73it/s]


 74%|███████▎  | 1000/1357 [05:53<02:28,  2.40it/s]


 74%|███████▍  | 1001/1357 [05:53<02:22,  2.50it/s]


 74%|███████▍  | 1002/1357 [05:54<02:09,  2.75it/s]


 74%|███████▍  | 1004/1357 [05:54<01:35,  3.71it/s]


 74%|███████▍  | 1005/1357 [05:54<01:38,  3.57it/s]


 74%|███████▍  | 1006/1357 [05:55<01:49,  3.20it/s]


 74%|███████▍  | 1007/1357 [05:55<02:27,  2.37it/s]


 74%|███████▍  | 1008/1357 [05:56<02:39,  2.19it/s]


 74%|███████▍  | 1009/1357 [05:56<02:21,  2.46it/s]


 74%|███████▍  | 1010/1357 [05:56<01:58,  2.92it/s]


 75%|███████▍  | 1011/1357 [05:57<01:46,  3.25it/s]


 75%|███████▍  | 1013/1357 [05:57<01:29,  3.85it/s]


 75%|███████▍  | 1014/1357 [05:58<01:46,  3.22it/s]


 75%|███████▍  | 1015/1357 [05:58<02:19,  2.45it/s]


 75%|███████▍  | 1016/1357 [05:59<02:29,  2.27it/s]


 75%|███████▍  | 1017/1357 [05:59<02:28,  2.28it/s]


 75%|███████▌  | 1018/1357 [05:59<01:59,  2.83it/s]


 75%|███████▌  | 1020/1357 [06:00<01:37,  3.44it/s]


 75%|███████▌  | 1022/1357 [06:00<01:40,  3.33it/s]


 75%|███████▌  | 1023/1357 [06:01<02:12,  2.52it/s]


 75%|███████▌  | 1024/1357 [06:02<02:18,  2.40it/s]


 76%|███████▌  | 1025/1357 [06:02<02:16,  2.43it/s]


 76%|███████▌  | 1026/1357 [06:02<02:04,  2.66it/s]

 76%|███████▌  | 1027/1357 [06:02<01:42,  3.21it/s]


 76%|███████▌  | 1028/1357 [06:03<01:36,  3.42it/s]


 76%|███████▌  | 1030/1357 [06:03<01:47,  3.05it/s]


 76%|███████▌  | 1031/1357 [06:04<02:33,  2.12it/s]


 76%|███████▌  | 1033/1357 [06:05<02:06,  2.56it/s]


 76%|███████▌  | 1034/1357 [06:05<02:18,  2.34it/s]


 76%|███████▋  | 1036/1357 [06:06<01:29,  3.57it/s]


 76%|███████▋  | 1037/1357 [06:06<01:22,  3.87it/s]


 76%|███████▋  | 1038/1357 [06:07<02:05,  2.54it/s]


 77%|███████▋  | 1039/1357 [06:07<02:31,  2.10it/s]


 77%|███████▋  | 1041/1357 [06:08<02:00,  2.61it/s]


 77%|███████▋  | 1042/1357 [06:08<02:00,  2.62it/s]


 77%|███████▋  | 1043/1357 [06:08<01:37,  3.21it/s]


 77%|███████▋  | 1044/1357 [06:08<01:30,  3.47it/s]


 77%|███████▋  | 1046/1357 [06:10<02:02,  2.54it/s]


 77%|███████▋  | 1047/1357 [06:10<02:18,  2.24it/s]


 77%|███████▋  | 1048/1357 [06:10<01:51,  2.78it/s]


 77%|███████▋  | 1049/1357 [06:11<01:48,  2.83it/s]


 77%|███████▋  | 1050/1357 [06:11<01:39,  3.10it/s]


 77%|███████▋  | 1051/1357 [06:11<01:33,  3.27it/s]


 78%|███████▊  | 1052/1357 [06:11<01:25,  3.57it/s]


 78%|███████▊  | 1053/1357 [06:11<01:13,  4.14it/s]


 78%|███████▊  | 1054/1357 [06:12<02:09,  2.33it/s]


 78%|███████▊  | 1055/1357 [06:13<02:20,  2.14it/s]


 78%|███████▊  | 1057/1357 [06:13<01:55,  2.60it/s]


 78%|███████▊  | 1058/1357 [06:14<01:36,  3.10it/s]


 78%|███████▊  | 1059/1357 [06:14<01:26,  3.43it/s]


 78%|███████▊  | 1060/1357 [06:14<01:26,  3.43it/s]


 78%|███████▊  | 1061/1357 [06:14<01:16,  3.87it/s]


 78%|███████▊  | 1062/1357 [06:15<02:10,  2.27it/s]


 78%|███████▊  | 1063/1357 [06:16<02:10,  2.26it/s]


 78%|███████▊  | 1064/1357 [06:16<02:10,  2.24it/s]


 78%|███████▊  | 1065/1357 [06:16<01:49,  2.66it/s]


 79%|███████▊  | 1066/1357 [06:17<01:42,  2.83it/s]


 79%|███████▊  | 1067/1357 [06:17<01:33,  3.11it/s]


 79%|███████▉  | 1069/1357 [06:17<01:06,  4.32it/s]


 79%|███████▉  | 1070/1357 [06:18<01:50,  2.59it/s]


 79%|███████▉  | 1071/1357 [06:18<02:05,  2.28it/s]


 79%|███████▉  | 1072/1357 [06:19<02:13,  2.14it/s]


 79%|███████▉  | 1074/1357 [06:19<01:37,  2.89it/s]


 79%|███████▉  | 1075/1357 [06:20<01:21,  3.45it/s]


 79%|███████▉  | 1076/1357 [06:20<01:08,  4.13it/s]


 79%|███████▉  | 1077/1357 [06:20<01:00,  4.64it/s]


 79%|███████▉  | 1078/1357 [06:21<01:56,  2.39it/s]


 80%|███████▉  | 1079/1357 [06:21<02:08,  2.16it/s]


 80%|███████▉  | 1080/1357 [06:22<02:10,  2.12it/s]


 80%|███████▉  | 1081/1357 [06:22<01:43,  2.68it/s]


 80%|███████▉  | 1082/1357 [06:22<01:54,  2.39it/s]


 80%|███████▉  | 1084/1357 [06:23<01:10,  3.85it/s]


 80%|███████▉  | 1085/1357 [06:23<01:01,  4.41it/s]


 80%|████████  | 1086/1357 [06:24<02:11,  2.07it/s]


 80%|████████  | 1087/1357 [06:24<01:46,  2.53it/s]


 80%|████████  | 1088/1357 [06:25<02:04,  2.15it/s]


 80%|████████  | 1089/1357 [06:25<01:45,  2.54it/s]


 80%|████████  | 1090/1357 [06:25<01:41,  2.64it/s]


 80%|████████  | 1091/1357 [06:25<01:19,  3.36it/s]


 81%|████████  | 1093/1357 [06:26<00:54,  4.85it/s]


 81%|████████  | 1094/1357 [06:27<01:51,  2.36it/s]


 81%|████████  | 1095/1357 [06:27<01:37,  2.69it/s]


 81%|████████  | 1096/1357 [06:28<01:53,  2.29it/s]


 81%|████████  | 1097/1357 [06:28<01:54,  2.27it/s]


 81%|████████  | 1098/1357 [06:28<01:29,  2.91it/s]


 81%|████████  | 1099/1357 [06:28<01:16,  3.37it/s]


 81%|████████  | 1101/1357 [06:29<00:58,  4.41it/s]


 81%|████████  | 1102/1357 [06:29<01:35,  2.66it/s]


 81%|████████▏ | 1103/1357 [06:30<01:29,  2.84it/s]


 81%|████████▏ | 1104/1357 [06:30<01:53,  2.23it/s]


 81%|████████▏ | 1105/1357 [06:31<01:47,  2.33it/s]


 82%|████████▏ | 1107/1357 [06:31<01:26,  2.89it/s]


 82%|████████▏ | 1109/1357 [06:32<01:21,  3.05it/s]


 82%|████████▏ | 1110/1357 [06:32<01:20,  3.08it/s]


 82%|████████▏ | 1111/1357 [06:33<01:24,  2.91it/s]


 82%|████████▏ | 1112/1357 [06:33<01:51,  2.19it/s]


 82%|████████▏ | 1113/1357 [06:34<01:45,  2.31it/s]


 82%|████████▏ | 1114/1357 [06:34<01:33,  2.59it/s]


 82%|████████▏ | 1115/1357 [06:34<01:26,  2.79it/s]


 82%|████████▏ | 1116/1357 [06:34<01:15,  3.21it/s]


 82%|████████▏ | 1117/1357 [06:35<01:26,  2.77it/s]


 82%|████████▏ | 1118/1357 [06:35<01:17,  3.08it/s]


 82%|████████▏ | 1119/1357 [06:36<01:44,  2.27it/s]


 83%|████████▎ | 1120/1357 [06:36<01:25,  2.77it/s]


 83%|████████▎ | 1121/1357 [06:37<01:34,  2.49it/s]


 83%|████████▎ | 1122/1357 [06:37<01:32,  2.54it/s]


 83%|████████▎ | 1123/1357 [06:37<01:23,  2.80it/s]


 83%|████████▎ | 1124/1357 [06:37<01:07,  3.45it/s]


 83%|████████▎ | 1125/1357 [06:38<01:37,  2.38it/s]


 83%|████████▎ | 1127/1357 [06:39<01:24,  2.72it/s]


 83%|████████▎ | 1128/1357 [06:39<01:22,  2.77it/s]


 83%|████████▎ | 1129/1357 [06:40<01:37,  2.34it/s]


 83%|████████▎ | 1130/1357 [06:40<01:16,  2.95it/s]


 83%|████████▎ | 1131/1357 [06:40<01:15,  2.98it/s]


 83%|████████▎ | 1132/1357 [06:40<01:01,  3.68it/s]


 83%|████████▎ | 1133/1357 [06:41<01:28,  2.52it/s]


 84%|████████▎ | 1135/1357 [06:41<01:17,  2.86it/s]


 84%|████████▎ | 1136/1357 [06:42<01:22,  2.68it/s]


 84%|████████▍ | 1137/1357 [06:42<01:34,  2.33it/s]


 84%|████████▍ | 1139/1357 [06:43<01:11,  3.07it/s]


 84%|████████▍ | 1140/1357 [06:43<01:08,  3.16it/s]


 84%|████████▍ | 1141/1357 [06:44<01:18,  2.75it/s]


 84%|████████▍ | 1143/1357 [06:44<01:06,  3.20it/s]


 84%|████████▍ | 1144/1357 [06:45<01:15,  2.82it/s]


 84%|████████▍ | 1145/1357 [06:45<01:26,  2.46it/s]


 85%|████████▍ | 1147/1357 [06:46<01:11,  2.95it/s]


 85%|████████▍ | 1148/1357 [06:46<01:06,  3.13it/s]


 85%|████████▍ | 1149/1357 [06:46<01:15,  2.74it/s]


 85%|████████▍ | 1150/1357 [06:47<01:06,  3.13it/s]


 85%|████████▍ | 1151/1357 [06:47<00:57,  3.61it/s]


 85%|████████▍ | 1152/1357 [06:47<01:15,  2.73it/s]


 85%|████████▍ | 1153/1357 [06:48<01:27,  2.33it/s]


 85%|████████▌ | 1155/1357 [06:49<01:15,  2.66it/s]


 85%|████████▌ | 1156/1357 [06:49<01:27,  2.28it/s]


 85%|████████▌ | 1157/1357 [06:50<01:20,  2.49it/s]


 85%|████████▌ | 1158/1357 [06:50<01:07,  2.93it/s]


 85%|████████▌ | 1159/1357 [06:50<00:56,  3.51it/s]


 85%|████████▌ | 1160/1357 [06:50<00:59,  3.32it/s]


 86%|████████▌ | 1161/1357 [06:51<01:27,  2.24it/s]


 86%|████████▌ | 1162/1357 [06:51<01:17,  2.51it/s]


 86%|████████▌ | 1164/1357 [06:52<01:29,  2.14it/s]


 86%|████████▌ | 1166/1357 [06:53<01:02,  3.07it/s]


 86%|████████▌ | 1167/1357 [06:53<00:55,  3.44it/s]


 86%|████████▌ | 1168/1357 [06:53<01:15,  2.52it/s]


 86%|████████▌ | 1169/1357 [06:54<01:02,  3.01it/s]


 86%|████████▌ | 1170/1357 [06:54<01:07,  2.78it/s]


 86%|████████▋ | 1171/1357 [06:54<01:02,  2.98it/s]


 86%|████████▋ | 1172/1357 [06:55<01:25,  2.17it/s]


 87%|████████▋ | 1174/1357 [06:56<01:06,  2.74it/s]


 87%|████████▋ | 1175/1357 [06:56<00:54,  3.31it/s]


 87%|████████▋ | 1176/1357 [06:56<01:04,  2.82it/s]


 87%|████████▋ | 1177/1357 [06:56<00:58,  3.06it/s]


 87%|████████▋ | 1178/1357 [06:57<01:08,  2.62it/s]

 87%|████████▋ | 1179/1357 [06:57<00:56,  3.16it/s]


 87%|████████▋ | 1180/1357 [06:58<01:15,  2.34it/s]


 87%|████████▋ | 1181/1357 [06:58<01:04,  2.72it/s]


 87%|████████▋ | 1182/1357 [06:58<01:03,  2.74it/s]


 87%|████████▋ | 1183/1357 [06:59<01:00,  2.87it/s]


 87%|████████▋ | 1184/1357 [06:59<00:53,  3.22it/s]


 87%|████████▋ | 1185/1357 [06:59<00:59,  2.88it/s]


 87%|████████▋ | 1186/1357 [07:00<01:03,  2.68it/s]


 87%|████████▋ | 1187/1357 [07:00<00:54,  3.10it/s]


 88%|████████▊ | 1188/1357 [07:01<01:05,  2.57it/s]


 88%|████████▊ | 1189/1357 [07:01<00:58,  2.90it/s]


 88%|████████▊ | 1190/1357 [07:01<00:57,  2.92it/s]


 88%|████████▊ | 1191/1357 [07:02<01:01,  2.71it/s]


 88%|████████▊ | 1192/1357 [07:02<00:52,  3.13it/s]


 88%|████████▊ | 1193/1357 [07:02<00:56,  2.90it/s]


 88%|████████▊ | 1194/1357 [07:03<00:57,  2.82it/s]


 88%|████████▊ | 1195/1357 [07:03<00:49,  3.30it/s]


 88%|████████▊ | 1196/1357 [07:03<01:06,  2.43it/s]


 88%|████████▊ | 1197/1357 [07:04<01:05,  2.43it/s]


 88%|████████▊ | 1199/1357 [07:04<00:52,  3.02it/s]


 88%|████████▊ | 1200/1357 [07:05<00:48,  3.27it/s]


 89%|████████▊ | 1201/1357 [07:05<00:52,  2.99it/s]


 89%|████████▊ | 1202/1357 [07:05<00:57,  2.70it/s]


 89%|████████▊ | 1203/1357 [07:06<00:49,  3.09it/s]


 89%|████████▊ | 1204/1357 [07:07<01:16,  1.99it/s]


 89%|████████▉ | 1206/1357 [07:07<00:48,  3.08it/s]


 89%|████████▉ | 1207/1357 [07:07<00:55,  2.70it/s]


 89%|████████▉ | 1209/1357 [07:08<00:56,  2.62it/s]


 89%|████████▉ | 1210/1357 [07:09<00:58,  2.52it/s]


 89%|████████▉ | 1211/1357 [07:09<00:48,  3.01it/s]


 89%|████████▉ | 1212/1357 [07:09<01:02,  2.33it/s]


 89%|████████▉ | 1213/1357 [07:10<00:51,  2.80it/s]


 89%|████████▉ | 1214/1357 [07:10<00:43,  3.27it/s]


 90%|████████▉ | 1215/1357 [07:10<00:45,  3.14it/s]


 90%|████████▉ | 1216/1357 [07:10<00:45,  3.12it/s]


 90%|████████▉ | 1217/1357 [07:11<01:02,  2.24it/s]


 90%|████████▉ | 1218/1357 [07:11<00:55,  2.49it/s]


 90%|████████▉ | 1219/1357 [07:12<00:43,  3.14it/s]


 90%|████████▉ | 1220/1357 [07:12<00:56,  2.43it/s]


 90%|████████▉ | 1221/1357 [07:12<00:44,  3.06it/s]


 90%|█████████ | 1222/1357 [07:13<00:39,  3.42it/s]


 90%|█████████ | 1223/1357 [07:13<00:50,  2.65it/s]


 90%|█████████ | 1224/1357 [07:13<00:47,  2.78it/s]


 90%|█████████ | 1225/1357 [07:14<00:55,  2.39it/s]


 90%|█████████ | 1226/1357 [07:14<00:47,  2.75it/s]


 90%|█████████ | 1227/1357 [07:14<00:37,  3.44it/s]


 90%|█████████ | 1228/1357 [07:15<00:50,  2.55it/s]


 91%|█████████ | 1229/1357 [07:15<00:39,  3.25it/s]


 91%|█████████ | 1230/1357 [07:15<00:35,  3.58it/s]


 91%|█████████ | 1231/1357 [07:16<00:47,  2.67it/s]


 91%|█████████ | 1232/1357 [07:16<00:43,  2.91it/s]


 91%|█████████ | 1233/1357 [07:17<00:48,  2.55it/s]


 91%|█████████ | 1234/1357 [07:17<00:44,  2.78it/s]


 91%|█████████ | 1236/1357 [07:18<00:49,  2.45it/s]


 91%|█████████ | 1238/1357 [07:18<00:32,  3.62it/s]


 91%|█████████▏| 1239/1357 [07:19<00:43,  2.71it/s]


 91%|█████████▏| 1240/1357 [07:19<00:38,  3.08it/s]


 91%|█████████▏| 1241/1357 [07:19<00:42,  2.75it/s]


 92%|█████████▏| 1242/1357 [07:20<00:38,  2.95it/s]


 92%|█████████▏| 1244/1357 [07:21<00:47,  2.37it/s]


 92%|█████████▏| 1246/1357 [07:21<00:34,  3.22it/s]


 92%|█████████▏| 1247/1357 [07:22<00:47,  2.33it/s]


 92%|█████████▏| 1249/1357 [07:22<00:33,  3.27it/s]


 92%|█████████▏| 1250/1357 [07:22<00:32,  3.32it/s]


 92%|█████████▏| 1251/1357 [07:22<00:28,  3.76it/s]


 92%|█████████▏| 1252/1357 [07:24<00:50,  2.07it/s]


 92%|█████████▏| 1253/1357 [07:24<00:42,  2.44it/s]


 92%|█████████▏| 1254/1357 [07:24<00:40,  2.54it/s]


 92%|█████████▏| 1255/1357 [07:25<00:47,  2.15it/s]


 93%|█████████▎| 1256/1357 [07:25<00:42,  2.39it/s]


 93%|█████████▎| 1258/1357 [07:25<00:27,  3.57it/s]


 93%|█████████▎| 1259/1357 [07:25<00:24,  4.02it/s]


 93%|█████████▎| 1260/1357 [07:27<00:44,  2.16it/s]


 93%|█████████▎| 1261/1357 [07:27<00:38,  2.46it/s]


 93%|█████████▎| 1262/1357 [07:27<00:33,  2.85it/s]


 93%|█████████▎| 1263/1357 [07:28<00:43,  2.16it/s]


 93%|█████████▎| 1264/1357 [07:28<00:33,  2.78it/s]


 93%|█████████▎| 1266/1357 [07:28<00:27,  3.27it/s]


 93%|█████████▎| 1267/1357 [07:29<00:25,  3.51it/s]


 93%|█████████▎| 1268/1357 [07:29<00:37,  2.37it/s]


 94%|█████████▎| 1269/1357 [07:30<00:33,  2.63it/s]


 94%|█████████▎| 1270/1357 [07:30<00:28,  3.04it/s]


 94%|█████████▎| 1271/1357 [07:31<00:38,  2.26it/s]


 94%|█████████▍| 1273/1357 [07:31<00:23,  3.53it/s]


 94%|█████████▍| 1274/1357 [07:31<00:27,  3.02it/s]


 94%|█████████▍| 1275/1357 [07:31<00:25,  3.20it/s]


 94%|█████████▍| 1276/1357 [07:32<00:34,  2.35it/s]


 94%|█████████▍| 1277/1357 [07:32<00:29,  2.68it/s]


 94%|█████████▍| 1278/1357 [07:33<00:23,  3.32it/s]


 94%|█████████▍| 1279/1357 [07:33<00:32,  2.42it/s]


 94%|█████████▍| 1280/1357 [07:33<00:24,  3.08it/s]


 94%|█████████▍| 1282/1357 [07:34<00:24,  3.08it/s]


 95%|█████████▍| 1283/1357 [07:34<00:22,  3.35it/s]


 95%|█████████▍| 1284/1357 [07:35<00:31,  2.28it/s]


 95%|█████████▍| 1286/1357 [07:35<00:23,  2.98it/s]


 95%|█████████▍| 1287/1357 [07:36<00:27,  2.55it/s]


 95%|█████████▍| 1288/1357 [07:36<00:22,  3.13it/s]


 95%|█████████▌| 1290/1357 [07:37<00:23,  2.91it/s]


 95%|█████████▌| 1291/1357 [07:37<00:19,  3.41it/s]


 95%|█████████▌| 1292/1357 [07:38<00:28,  2.26it/s]


 95%|█████████▌| 1293/1357 [07:38<00:26,  2.44it/s]


 95%|█████████▌| 1294/1357 [07:38<00:20,  3.02it/s]


 95%|█████████▌| 1295/1357 [07:39<00:21,  2.84it/s]


 96%|█████████▌| 1296/1357 [07:39<00:18,  3.33it/s]


 96%|█████████▌| 1297/1357 [07:39<00:15,  3.84it/s]


 96%|█████████▌| 1298/1357 [07:40<00:22,  2.66it/s]


 96%|█████████▌| 1299/1357 [07:40<00:21,  2.64it/s]


 96%|█████████▌| 1300/1357 [07:41<00:30,  1.90it/s]


 96%|█████████▌| 1301/1357 [07:41<00:23,  2.36it/s]


 96%|█████████▌| 1302/1357 [07:41<00:18,  2.94it/s]


 96%|█████████▌| 1303/1357 [07:42<00:18,  2.93it/s]


 96%|█████████▌| 1305/1357 [07:42<00:16,  3.09it/s]


 96%|█████████▌| 1306/1357 [07:43<00:18,  2.80it/s]


 96%|█████████▋| 1307/1357 [07:43<00:16,  3.01it/s]


 96%|█████████▋| 1308/1357 [07:44<00:24,  2.01it/s]


 96%|█████████▋| 1309/1357 [07:44<00:20,  2.33it/s]


 97%|█████████▋| 1311/1357 [07:44<00:12,  3.67it/s]


 97%|█████████▋| 1312/1357 [07:45<00:13,  3.31it/s]


 97%|█████████▋| 1313/1357 [07:45<00:13,  3.22it/s]


 97%|█████████▋| 1314/1357 [07:46<00:15,  2.72it/s]


 97%|█████████▋| 1315/1357 [07:46<00:16,  2.50it/s]


 97%|█████████▋| 1316/1357 [07:47<00:19,  2.09it/s]


 97%|█████████▋| 1317/1357 [07:47<00:15,  2.51it/s]


 97%|█████████▋| 1319/1357 [07:47<00:10,  3.54it/s]


 97%|█████████▋| 1320/1357 [07:48<00:10,  3.54it/s]


 97%|█████████▋| 1321/1357 [07:48<00:11,  3.18it/s]


 97%|█████████▋| 1322/1357 [07:48<00:11,  2.98it/s]


 97%|█████████▋| 1323/1357 [07:49<00:14,  2.35it/s]


 98%|█████████▊| 1324/1357 [07:50<00:14,  2.25it/s]


 98%|█████████▊| 1325/1357 [07:50<00:11,  2.69it/s]

 98%|█████████▊| 1326/1357 [07:50<00:09,  3.28it/s]


 98%|█████████▊| 1327/1357 [07:50<00:08,  3.69it/s]


 98%|█████████▊| 1328/1357 [07:50<00:07,  4.03it/s]


 98%|█████████▊| 1329/1357 [07:51<00:09,  2.84it/s]


 98%|█████████▊| 1330/1357 [07:51<00:09,  2.81it/s]


 98%|█████████▊| 1331/1357 [07:52<00:11,  2.36it/s]


 98%|█████████▊| 1332/1357 [07:52<00:11,  2.20it/s]


 98%|█████████▊| 1334/1357 [07:53<00:07,  3.24it/s]


 98%|█████████▊| 1335/1357 [07:53<00:07,  2.98it/s]


 98%|█████████▊| 1336/1357 [07:53<00:05,  3.61it/s]


 99%|█████████▊| 1337/1357 [07:54<00:07,  2.64it/s]


 99%|█████████▊| 1338/1357 [07:54<00:06,  2.77it/s]


 99%|█████████▊| 1339/1357 [07:55<00:08,  2.22it/s]


 99%|█████████▊| 1340/1357 [07:55<00:07,  2.16it/s]


 99%|█████████▉| 1341/1357 [07:56<00:06,  2.30it/s]


 99%|█████████▉| 1343/1357 [07:56<00:03,  3.55it/s]


 99%|█████████▉| 1344/1357 [07:56<00:04,  3.13it/s]


 99%|█████████▉| 1345/1357 [07:57<00:03,  3.05it/s]


 99%|█████████▉| 1346/1357 [07:57<00:03,  2.86it/s]


 99%|█████████▉| 1347/1357 [07:58<00:04,  2.32it/s]


 99%|█████████▉| 1348/1357 [07:58<00:04,  2.09it/s]


 99%|█████████▉| 1349/1357 [07:58<00:03,  2.46it/s]


100%|█████████▉| 1351/1357 [07:59<00:01,  3.06it/s]


100%|█████████▉| 1352/1357 [07:59<00:01,  2.89it/s]


100%|█████████▉| 1353/1357 [08:00<00:01,  3.29it/s]


100%|█████████▉| 1354/1357 [08:00<00:00,  3.04it/s]


100%|█████████▉| 1355/1357 [08:01<00:00,  2.41it/s]


100%|█████████▉| 1356/1357 [08:01<00:00,  2.32it/s]


100%|██████████| 1357/1357 [08:01<00:00,  2.82it/s]
Families:  67%|██████▋   | 2/3 [08:33<04:56, 296.27s/it]
Multiplets | family 5:   0%|          | 0/219 [00:00<?, ?it/s]


  0%|          | 0/219 [00:00<?, ?it/s]


  0%|          | 1/219 [00:03<12:52,  3.55s/it]


  1%|▏         | 3/219 [00:03<03:32,  1.02it/s]


  3%|▎         | 6/219 [00:03<01:28,  2.40it/s]


  4%|▍         | 9/219 [00:07<02:30,  1.40it/s]


  5%|▌         | 12/219 [00:07<01:33,  2.22it/s]


  6%|▋         | 14/219 [00:07<01:21,  2.51it/s]


  7%|▋         | 16/219 [00:07<01:04,  3.13it/s]


  8%|▊         | 17/219 [00:10<02:20,  1.44it/s]


  9%|▊         | 19/219 [00:10<01:38,  2.02it/s]


  9%|▉         | 20/219 [00:10<01:25,  2.33it/s]


 10%|▉         | 21/219 [00:11<01:47,  1.84it/s]


 10%|█         | 22/219 [00:11<01:27,  2.26it/s]


 11%|█         | 24/219 [00:12<01:00,  3.25it/s]


 11%|█▏        | 25/219 [00:13<02:06,  1.54it/s]


 12%|█▏        | 26/219 [00:14<01:47,  1.79it/s]


 12%|█▏        | 27/219 [00:14<01:29,  2.15it/s]


 13%|█▎        | 29/219 [00:15<01:23,  2.27it/s]


 14%|█▎        | 30/219 [00:15<01:25,  2.22it/s]


 15%|█▍        | 32/219 [00:15<00:58,  3.21it/s]


 15%|█▌        | 33/219 [00:17<01:57,  1.59it/s]


 16%|█▌        | 35/219 [00:18<01:23,  2.21it/s]


 17%|█▋        | 37/219 [00:18<01:22,  2.21it/s]


 17%|█▋        | 38/219 [00:19<01:20,  2.26it/s]


 18%|█▊        | 40/219 [00:19<00:56,  3.15it/s]


 19%|█▊        | 41/219 [00:21<01:50,  1.61it/s]


 19%|█▉        | 42/219 [00:21<01:31,  1.94it/s]


 20%|█▉        | 43/219 [00:21<01:14,  2.37it/s]


 20%|██        | 44/219 [00:21<01:00,  2.88it/s]


 21%|██        | 45/219 [00:22<01:31,  1.89it/s]


 21%|██        | 46/219 [00:23<01:19,  2.16it/s]


 21%|██▏       | 47/219 [00:23<01:02,  2.74it/s]


 22%|██▏       | 49/219 [00:25<01:45,  1.61it/s]


 23%|██▎       | 51/219 [00:25<01:14,  2.26it/s]


 24%|██▎       | 52/219 [00:25<01:08,  2.44it/s]


 24%|██▍       | 53/219 [00:26<01:15,  2.21it/s]


 25%|██▍       | 54/219 [00:26<01:10,  2.34it/s]


 25%|██▌       | 55/219 [00:26<01:02,  2.63it/s]


 26%|██▌       | 57/219 [00:28<01:40,  1.61it/s]


 26%|██▋       | 58/219 [00:29<01:26,  1.85it/s]


 27%|██▋       | 59/219 [00:29<01:12,  2.20it/s]


 27%|██▋       | 60/219 [00:29<01:01,  2.60it/s]


 28%|██▊       | 61/219 [00:30<01:12,  2.17it/s]


 29%|██▉       | 63/219 [00:30<00:50,  3.08it/s]


 29%|██▉       | 64/219 [00:30<01:01,  2.54it/s]


 30%|██▉       | 65/219 [00:32<01:35,  1.61it/s]


 30%|███       | 66/219 [00:32<01:30,  1.70it/s]


 31%|███       | 68/219 [00:32<00:57,  2.64it/s]


 32%|███▏      | 69/219 [00:33<01:05,  2.28it/s]


 32%|███▏      | 70/219 [00:33<00:55,  2.70it/s]


 32%|███▏      | 71/219 [00:34<00:50,  2.91it/s]


 33%|███▎      | 72/219 [00:34<01:00,  2.42it/s]


 33%|███▎      | 73/219 [00:35<01:35,  1.54it/s]


 34%|███▍      | 74/219 [00:36<01:24,  1.72it/s]


 35%|███▍      | 76/219 [00:36<00:51,  2.78it/s]


 35%|███▌      | 77/219 [00:37<01:10,  2.02it/s]


 36%|███▌      | 79/219 [00:37<00:51,  2.73it/s]


 37%|███▋      | 80/219 [00:38<00:53,  2.62it/s]


 37%|███▋      | 81/219 [00:39<01:20,  1.72it/s]


 37%|███▋      | 82/219 [00:39<01:12,  1.88it/s]


 38%|███▊      | 83/219 [00:40<01:05,  2.09it/s]


 39%|███▉      | 85/219 [00:41<01:08,  1.96it/s]


 40%|███▉      | 87/219 [00:41<00:50,  2.64it/s]


 40%|████      | 88/219 [00:41<00:46,  2.84it/s]


 41%|████      | 89/219 [00:43<01:13,  1.77it/s]


 41%|████      | 90/219 [00:43<01:12,  1.79it/s]


 42%|████▏     | 91/219 [00:43<00:57,  2.22it/s]


 42%|████▏     | 92/219 [00:43<00:49,  2.59it/s]


 42%|████▏     | 93/219 [00:44<01:01,  2.04it/s]


 43%|████▎     | 94/219 [00:44<00:49,  2.53it/s]


 43%|████▎     | 95/219 [00:45<00:45,  2.75it/s]


 44%|████▍     | 96/219 [00:45<00:59,  2.07it/s]


 44%|████▍     | 97/219 [00:47<01:19,  1.54it/s]


 45%|████▍     | 98/219 [00:47<01:00,  2.01it/s]


 45%|████▌     | 99/219 [00:47<00:54,  2.20it/s]


 46%|████▌     | 100/219 [00:47<00:48,  2.46it/s]


 46%|████▌     | 101/219 [00:48<00:58,  2.00it/s]


 47%|████▋     | 102/219 [00:48<00:55,  2.09it/s]


 47%|████▋     | 104/219 [00:49<00:51,  2.24it/s]


 48%|████▊     | 105/219 [00:50<01:06,  1.71it/s]


 49%|████▉     | 107/219 [00:51<00:45,  2.47it/s]


 49%|████▉     | 108/219 [00:51<00:42,  2.60it/s]


 50%|████▉     | 109/219 [00:52<00:53,  2.04it/s]


 50%|█████     | 110/219 [00:52<00:48,  2.24it/s]


 51%|█████     | 111/219 [00:52<00:43,  2.49it/s]


 51%|█████     | 112/219 [00:53<00:48,  2.19it/s]


 52%|█████▏    | 113/219 [00:54<01:00,  1.76it/s]


 52%|█████▏    | 114/219 [00:54<00:46,  2.24it/s]


 53%|█████▎    | 115/219 [00:54<00:40,  2.59it/s]


 53%|█████▎    | 116/219 [00:55<00:47,  2.18it/s]


 53%|█████▎    | 117/219 [00:56<01:03,  1.62it/s]


 54%|█████▍    | 118/219 [00:56<00:49,  2.05it/s]


 55%|█████▍    | 120/219 [00:57<00:41,  2.38it/s]


 55%|█████▌    | 121/219 [00:57<00:47,  2.08it/s]


 56%|█████▌    | 122/219 [00:58<00:49,  1.95it/s]


 56%|█████▌    | 123/219 [00:58<00:47,  2.03it/s]


 57%|█████▋    | 124/219 [00:58<00:37,  2.53it/s]


 57%|█████▋    | 125/219 [00:59<00:47,  1.98it/s]


 58%|█████▊    | 126/219 [01:00<00:49,  1.89it/s]


 58%|█████▊    | 127/219 [01:00<00:41,  2.20it/s]


 58%|█████▊    | 128/219 [01:01<00:45,  1.99it/s]


 59%|█████▉    | 129/219 [01:01<00:36,  2.49it/s]


 59%|█████▉    | 130/219 [01:01<00:38,  2.32it/s]

 60%|█████▉    | 131/219 [01:02<00:41,  2.13it/s]


 60%|██████    | 132/219 [01:02<00:41,  2.10it/s]


 61%|██████    | 133/219 [01:03<00:48,  1.76it/s]


 61%|██████    | 134/219 [01:03<00:40,  2.11it/s]


 62%|██████▏   | 135/219 [01:04<00:38,  2.20it/s]


 62%|██████▏   | 136/219 [01:04<00:37,  2.22it/s]


 63%|██████▎   | 137/219 [01:05<00:36,  2.28it/s]


 63%|██████▎   | 138/219 [01:05<00:32,  2.49it/s]


 63%|██████▎   | 139/219 [01:05<00:32,  2.45it/s]


 64%|██████▍   | 140/219 [01:06<00:35,  2.24it/s]


 64%|██████▍   | 141/219 [01:07<00:46,  1.68it/s]


 65%|██████▍   | 142/219 [01:07<00:36,  2.14it/s]


 65%|██████▌   | 143/219 [01:08<00:35,  2.11it/s]


 66%|██████▌   | 144/219 [01:08<00:31,  2.35it/s]


 66%|██████▌   | 145/219 [01:08<00:32,  2.30it/s]


 67%|██████▋   | 146/219 [01:09<00:25,  2.86it/s]


 67%|██████▋   | 147/219 [01:09<00:28,  2.54it/s]


 68%|██████▊   | 148/219 [01:10<00:31,  2.25it/s]


 68%|██████▊   | 149/219 [01:11<00:41,  1.69it/s]


 68%|██████▊   | 150/219 [01:11<00:35,  1.94it/s]


 69%|██████▉   | 151/219 [01:11<00:32,  2.08it/s]


 69%|██████▉   | 152/219 [01:12<00:28,  2.39it/s]


 70%|██████▉   | 153/219 [01:12<00:28,  2.29it/s]


 70%|███████   | 154/219 [01:12<00:22,  2.90it/s]


 71%|███████   | 155/219 [01:13<00:26,  2.41it/s]


 71%|███████   | 156/219 [01:13<00:28,  2.18it/s]


 72%|███████▏  | 157/219 [01:14<00:36,  1.68it/s]


 72%|███████▏  | 158/219 [01:15<00:31,  1.96it/s]


 73%|███████▎  | 159/219 [01:15<00:31,  1.89it/s]


 73%|███████▎  | 160/219 [01:15<00:27,  2.17it/s]


 74%|███████▎  | 161/219 [01:16<00:28,  2.05it/s]


 74%|███████▍  | 163/219 [01:16<00:19,  2.95it/s]


 75%|███████▍  | 164/219 [01:17<00:25,  2.20it/s]


 75%|███████▌  | 165/219 [01:18<00:31,  1.71it/s]


 76%|███████▌  | 166/219 [01:18<00:24,  2.18it/s]


 76%|███████▋  | 167/219 [01:19<00:26,  1.99it/s]


 77%|███████▋  | 168/219 [01:19<00:23,  2.20it/s]


 77%|███████▋  | 169/219 [01:19<00:20,  2.43it/s]


 78%|███████▊  | 170/219 [01:20<00:16,  2.89it/s]


 78%|███████▊  | 171/219 [01:20<00:18,  2.62it/s]


 79%|███████▊  | 172/219 [01:21<00:24,  1.92it/s]


 79%|███████▉  | 173/219 [01:22<00:32,  1.40it/s]


 80%|███████▉  | 175/219 [01:22<00:20,  2.17it/s]


 80%|████████  | 176/219 [01:23<00:22,  1.90it/s]


 81%|████████  | 177/219 [01:23<00:18,  2.23it/s]


 81%|████████▏ | 178/219 [01:24<00:17,  2.35it/s]


 82%|████████▏ | 179/219 [01:24<00:18,  2.19it/s]


 82%|████████▏ | 180/219 [01:25<00:20,  1.91it/s]


 83%|████████▎ | 181/219 [01:26<00:21,  1.80it/s]


 83%|████████▎ | 182/219 [01:26<00:15,  2.33it/s]


 84%|████████▎ | 183/219 [01:26<00:15,  2.38it/s]


 84%|████████▍ | 184/219 [01:27<00:16,  2.13it/s]


 84%|████████▍ | 185/219 [01:27<00:17,  1.98it/s]


 85%|████████▍ | 186/219 [01:28<00:13,  2.40it/s]


 85%|████████▌ | 187/219 [01:28<00:14,  2.15it/s]


 86%|████████▌ | 188/219 [01:29<00:14,  2.18it/s]


 86%|████████▋ | 189/219 [01:29<00:16,  1.83it/s]


 87%|████████▋ | 190/219 [01:30<00:14,  1.95it/s]


 87%|████████▋ | 191/219 [01:30<00:14,  1.92it/s]


 88%|████████▊ | 192/219 [01:31<00:13,  2.02it/s]


 88%|████████▊ | 193/219 [01:31<00:10,  2.38it/s]


 89%|████████▊ | 194/219 [01:32<00:12,  1.97it/s]


 89%|████████▉ | 195/219 [01:32<00:09,  2.49it/s]


 89%|████████▉ | 196/219 [01:33<00:11,  1.99it/s]


 90%|████████▉ | 197/219 [01:33<00:10,  2.01it/s]


 90%|█████████ | 198/219 [01:34<00:10,  2.02it/s]


 91%|█████████ | 199/219 [01:34<00:10,  1.94it/s]


 91%|█████████▏| 200/219 [01:34<00:08,  2.30it/s]


 92%|█████████▏| 201/219 [01:35<00:08,  2.22it/s]


 92%|█████████▏| 202/219 [01:35<00:07,  2.17it/s]


 93%|█████████▎| 204/219 [01:36<00:06,  2.33it/s]


 94%|█████████▎| 205/219 [01:37<00:06,  2.05it/s]


 94%|█████████▍| 206/219 [01:37<00:06,  2.04it/s]


 95%|█████████▍| 207/219 [01:38<00:05,  2.12it/s]


 95%|█████████▍| 208/219 [01:38<00:04,  2.47it/s]


 95%|█████████▌| 209/219 [01:38<00:04,  2.32it/s]


 96%|█████████▌| 210/219 [01:39<00:03,  2.25it/s]


 96%|█████████▋| 211/219 [01:39<00:03,  2.62it/s]


 97%|█████████▋| 212/219 [01:40<00:03,  2.07it/s]


 97%|█████████▋| 213/219 [01:40<00:03,  1.89it/s]


 98%|█████████▊| 214/219 [01:41<00:02,  2.09it/s]


 98%|█████████▊| 215/219 [01:41<00:01,  2.21it/s]


 99%|█████████▊| 216/219 [01:41<00:01,  2.53it/s]


 99%|█████████▉| 217/219 [01:42<00:00,  2.09it/s]


100%|█████████▉| 218/219 [01:43<00:00,  2.15it/s]


100%|██████████| 219/219 [01:43<00:00,  2.12it/s]
Families: 100%|██████████| 3/3 [10:16<00:00, 205.45s/it]

Runtime: 616.359789 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]


Multiplets | family 3:   0%|          | 0/26 [00:00<?, ?it/s]



  0%|          | 0/26 [00:00<?, ?it/s]



  4%|▍         | 1/26 [00:02<00:53,  2.12s/it]



 15%|█▌        | 4/26 [00:02<00:09,  2.23it/s]



 23%|██▎       | 6/26 [00:02<00:06,  3.27it/s]



 35%|███▍      | 9/26 [00:04<00:07,  2.21it/s]



 42%|████▏     | 11/26 [00:04<00:05,  2.96it/s]



 50%|█████     | 13/26 [00:04<00:03,  3.57it/s]



 58%|█████▊    | 15/26 [00:04<00:02,  4.70it/s]



 65%|██████▌   | 17/26 [00:06<00:03,  2.43it/s]



 73%|███████▎  | 19/26 [00:06<00:02,  3.19it/s]



 81%|████████  | 21/26 [00:07<00:01,  3.80it/s]



 85%|████████▍ | 22/26 [00:07<00:01,  3.91it/s]



 92%|█████████▏| 24/26 [00:07<00:00,  4.86it/s]



 96%|█████████▌| 25/26 [00:08<00:00,  3.19it/s]



100%|██████████| 26/26 [00:08<00:00,  3.06it/s]
Multiplets | family 3:   0%|          | 0/26 [00:08<?, ?it/s]



Multiplets | family 4:   0%|          | 0/1131 [00:00<?, ?it/s]



  0%|          | 0/1131 [00:00<?, ?it/s]



  0%|          | 1/1131 [00:03<1:02:12,  3.30s/it]



  0%|          | 5/1131 [00:03<09:44,  1.93it/s]



  1%|          | 9/1131 [00:06<12:08,  1.54it/s]



  1%|          | 11/1131 [00:06<08:59,  2.08it/s]



  1%|          | 13/1131 [00:06<06:45,  2.76it/s]



  1%|▏         | 16/1131 [00:06<04:27,  4.16it/s]



  2%|▏         | 18/1131 [00:09<10:33,  1.76it/s]



  2%|▏         | 20/1131 [00:09<07:59,  2.32it/s]



  2%|▏         | 22/1131 [00:10<06:32,  2.82it/s]



  2%|▏         | 25/1131 [00:12<10:14,  1.80it/s]



  2%|▏         | 26/1131 [00:13<09:02,  2.04it/s]



  2%|▏         | 27/1131 [00:13<07:51,  2.34it/s]



  2%|▏         | 28/1131 [00:13<07:20,  2.51it/s]



  3%|▎         | 30/1131 [00:13<05:52,  3.13it/s]



  3%|▎         | 31/1131 [00:13<05:15,  3.49it/s]



  3%|▎         | 33/1131 [00:16<10:16,  1.78it/s]



  3%|▎         | 34/1131 [00:16<08:48,  2.07it/s]



  3%|▎         | 35/1131 [00:16<07:19,  2.50it/s]



  3%|▎         | 36/1131 [00:16<07:53,  2.31it/s]



  3%|▎         | 38/1131 [00:17<05:08,  3.55it/s]



  3%|▎         | 39/1131 [00:17<05:18,  3.43it/s]



  4%|▎         | 40/1131 [00:17<04:47,  3.80it/s]



  4%|▎         | 41/1131 [00:19<11:30,  1.58it/s]



  4%|▎         | 42/1131 [00:19<08:59,  2.02it/s]



  4%|▍         | 43/1131 [00:19<08:00,  2.26it/s]



  4%|▍         | 44/1131 [00:20<07:44,  2.34it/s]



  4%|▍         | 45/1131 [00:20<07:05,  2.55it/s]



  4%|▍         | 47/1131 [00:20<04:58,  3.63it/s]



  4%|▍         | 48/1131 [00:20<04:11,  4.30it/s]



  4%|▍         | 49/1131 [00:22<11:24,  1.58it/s]



  4%|▍         | 50/1131 [00:22<09:15,  1.95it/s]



  5%|▍         | 51/1131 [00:23<09:15,  1.94it/s]



  5%|▍         | 53/1131 [00:23<06:59,  2.57it/s]



  5%|▍         | 54/1131 [00:23<05:50,  3.08it/s]



  5%|▍         | 55/1131 [00:23<05:07,  3.50it/s]



  5%|▍         | 56/1131 [00:24<04:55,  3.64it/s]



  5%|▌         | 57/1131 [00:25<11:56,  1.50it/s]



  5%|▌         | 59/1131 [00:26<08:45,  2.04it/s]



  5%|▌         | 61/1131 [00:27<08:29,  2.10it/s]



  5%|▌         | 62/1131 [00:27<07:11,  2.48it/s]



  6%|▌         | 63/1131 [00:27<06:24,  2.78it/s]



  6%|▌         | 64/1131 [00:27<05:46,  3.08it/s]



  6%|▌         | 65/1131 [00:28<09:24,  1.89it/s]



  6%|▌         | 66/1131 [00:29<07:40,  2.31it/s]



  6%|▌         | 67/1131 [00:29<08:20,  2.13it/s]



  6%|▌         | 68/1131 [00:30<08:52,  2.00it/s]



  6%|▌         | 69/1131 [00:30<07:38,  2.32it/s]



  6%|▌         | 70/1131 [00:31<08:31,  2.07it/s]



  6%|▋         | 72/1131 [00:31<05:22,  3.28it/s]



  6%|▋         | 73/1131 [00:32<08:14,  2.14it/s]



  7%|▋         | 74/1131 [00:32<07:43,  2.28it/s]



  7%|▋         | 75/1131 [00:33<07:24,  2.38it/s]



  7%|▋         | 76/1131 [00:33<07:43,  2.28it/s]



  7%|▋         | 77/1131 [00:34<07:56,  2.21it/s]



  7%|▋         | 78/1131 [00:34<08:24,  2.09it/s]



  7%|▋         | 80/1131 [00:34<05:07,  3.42it/s]



  7%|▋         | 81/1131 [00:35<08:10,  2.14it/s]



  7%|▋         | 82/1131 [00:35<07:06,  2.46it/s]



  7%|▋         | 83/1131 [00:36<07:08,  2.45it/s]



  7%|▋         | 84/1131 [00:36<06:54,  2.53it/s]



  8%|▊         | 85/1131 [00:37<08:39,  2.01it/s]



  8%|▊         | 86/1131 [00:37<07:38,  2.28it/s]



  8%|▊         | 87/1131 [00:37<06:31,  2.67it/s]



  8%|▊         | 89/1131 [00:38<07:19,  2.37it/s]



  8%|▊         | 90/1131 [00:39<06:56,  2.50it/s]



  8%|▊         | 91/1131 [00:39<07:24,  2.34it/s]



  8%|▊         | 92/1131 [00:39<05:58,  2.90it/s]



  8%|▊         | 93/1131 [00:40<09:28,  1.83it/s]



  8%|▊         | 95/1131 [00:41<06:23,  2.70it/s]



  9%|▊         | 97/1131 [00:42<06:46,  2.54it/s]



  9%|▊         | 98/1131 [00:42<07:13,  2.38it/s]



  9%|▉         | 99/1131 [00:42<06:52,  2.50it/s]



  9%|▉         | 100/1131 [00:43<06:49,  2.52it/s]



  9%|▉         | 101/1131 [00:44<08:56,  1.92it/s]



  9%|▉         | 102/1131 [00:44<07:46,  2.21it/s]



  9%|▉         | 103/1131 [00:44<06:35,  2.60it/s]



  9%|▉         | 105/1131 [00:45<05:47,  2.96it/s]



  9%|▉         | 106/1131 [00:46<08:03,  2.12it/s]



  9%|▉         | 107/1131 [00:46<08:25,  2.03it/s]



 10%|▉         | 109/1131 [00:47<08:53,  1.91it/s]



 10%|▉         | 111/1131 [00:47<05:53,  2.89it/s]



 10%|▉         | 112/1131 [00:48<05:26,  3.12it/s]



 10%|▉         | 113/1131 [00:48<05:36,  3.02it/s]



 10%|█         | 114/1131 [00:49<08:46,  1.93it/s]



 10%|█         | 115/1131 [00:50<08:20,  2.03it/s]



 10%|█         | 116/1131 [00:50<08:25,  2.01it/s]



 10%|█         | 117/1131 [00:51<10:27,  1.62it/s]



 10%|█         | 118/1131 [00:51<08:27,  2.00it/s]



 11%|█         | 119/1131 [00:51<06:43,  2.51it/s]



 11%|█         | 121/1131 [00:52<05:40,  2.97it/s]



 11%|█         | 122/1131 [00:53<07:41,  2.19it/s]



 11%|█         | 123/1131 [00:53<06:55,  2.42it/s]



 11%|█         | 124/1131 [00:53<06:42,  2.50it/s]



 11%|█         | 125/1131 [00:55<11:48,  1.42it/s]



 11%|█         | 126/1131 [00:55<08:56,  1.87it/s]



 11%|█▏        | 129/1131 [00:55<05:05,  3.28it/s]



 11%|█▏        | 130/1131 [00:57<09:12,  1.81it/s]



 12%|█▏        | 131/1131 [00:57<07:47,  2.14it/s]



 12%|█▏        | 132/1131 [00:57<07:45,  2.15it/s]



 12%|█▏        | 133/1131 [00:59<11:44,  1.42it/s]



 12%|█▏        | 135/1131 [00:59<07:06,  2.33it/s]



 12%|█▏        | 136/1131 [00:59<05:57,  2.78it/s]



 12%|█▏        | 138/1131 [01:01<09:34,  1.73it/s]



 12%|█▏        | 139/1131 [01:01<08:31,  1.94it/s]



 12%|█▏        | 141/1131 [01:03<09:32,  1.73it/s]



 13%|█▎        | 142/1131 [01:03<07:49,  2.11it/s]

 13%|█▎        | 143/1131 [01:03<06:48,  2.42it/s]



 13%|█▎        | 145/1131 [01:03<05:29,  2.99it/s]



 13%|█▎        | 146/1131 [01:05<09:07,  1.80it/s]



 13%|█▎        | 147/1131 [01:05<08:22,  1.96it/s]



 13%|█▎        | 148/1131 [01:05<06:54,  2.37it/s]



 13%|█▎        | 149/1131 [01:06<09:38,  1.70it/s]



 13%|█▎        | 150/1131 [01:06<07:41,  2.13it/s]



 13%|█▎        | 151/1131 [01:06<05:58,  2.73it/s]



 14%|█▎        | 153/1131 [01:07<05:02,  3.24it/s]



 14%|█▎        | 154/1131 [01:08<08:20,  1.95it/s]



 14%|█▎        | 155/1131 [01:09<07:59,  2.04it/s]



 14%|█▍        | 156/1131 [01:09<06:33,  2.48it/s]



 14%|█▍        | 157/1131 [01:10<09:19,  1.74it/s]



 14%|█▍        | 159/1131 [01:10<05:57,  2.72it/s]



 14%|█▍        | 160/1131 [01:10<05:16,  3.07it/s]



 14%|█▍        | 161/1131 [01:10<04:38,  3.48it/s]



 14%|█▍        | 162/1131 [01:12<08:54,  1.81it/s]



 14%|█▍        | 163/1131 [01:12<07:54,  2.04it/s]



 15%|█▍        | 164/1131 [01:12<06:52,  2.34it/s]



 15%|█▍        | 165/1131 [01:13<09:14,  1.74it/s]



 15%|█▍        | 166/1131 [01:14<09:46,  1.64it/s]



 15%|█▍        | 168/1131 [01:14<06:01,  2.66it/s]



 15%|█▌        | 170/1131 [01:15<07:48,  2.05it/s]



 15%|█▌        | 171/1131 [01:16<07:10,  2.23it/s]



 15%|█▌        | 172/1131 [01:16<06:33,  2.44it/s]



 15%|█▌        | 173/1131 [01:17<10:02,  1.59it/s]



 15%|█▌        | 174/1131 [01:17<07:50,  2.03it/s]



 16%|█▌        | 176/1131 [01:18<06:06,  2.61it/s]



 16%|█▌        | 177/1131 [01:18<06:05,  2.61it/s]



 16%|█▌        | 178/1131 [01:19<06:38,  2.39it/s]



 16%|█▌        | 179/1131 [01:19<06:53,  2.30it/s]



 16%|█▌        | 180/1131 [01:20<06:42,  2.36it/s]



 16%|█▌        | 181/1131 [01:21<10:38,  1.49it/s]



 16%|█▌        | 183/1131 [01:21<07:00,  2.26it/s]



 16%|█▋        | 184/1131 [01:21<06:20,  2.49it/s]



 16%|█▋        | 185/1131 [01:22<06:04,  2.60it/s]



 16%|█▋        | 186/1131 [01:22<06:07,  2.57it/s]



 17%|█▋        | 187/1131 [01:23<06:31,  2.41it/s]



 17%|█▋        | 188/1131 [01:23<05:29,  2.87it/s]



 17%|█▋        | 189/1131 [01:24<10:00,  1.57it/s]



 17%|█▋        | 190/1131 [01:24<07:37,  2.06it/s]



 17%|█▋        | 191/1131 [01:25<07:27,  2.10it/s]



 17%|█▋        | 193/1131 [01:25<05:59,  2.61it/s]



 17%|█▋        | 194/1131 [01:26<05:58,  2.61it/s]



 17%|█▋        | 195/1131 [01:26<05:37,  2.78it/s]



 17%|█▋        | 196/1131 [01:26<04:54,  3.17it/s]



 17%|█▋        | 197/1131 [01:28<09:37,  1.62it/s]



 18%|█▊        | 198/1131 [01:28<09:14,  1.68it/s]



 18%|█▊        | 200/1131 [01:28<05:47,  2.68it/s]



 18%|█▊        | 201/1131 [01:29<07:17,  2.12it/s]



 18%|█▊        | 203/1131 [01:30<05:37,  2.75it/s]



 18%|█▊        | 204/1131 [01:30<05:06,  3.02it/s]



 18%|█▊        | 205/1131 [01:31<08:13,  1.88it/s]



 18%|█▊        | 206/1131 [01:32<09:29,  1.63it/s]



 18%|█▊        | 207/1131 [01:32<08:39,  1.78it/s]



 18%|█▊        | 208/1131 [01:32<07:13,  2.13it/s]



 18%|█▊        | 209/1131 [01:33<05:49,  2.64it/s]



 19%|█▊        | 210/1131 [01:33<05:13,  2.94it/s]



 19%|█▊        | 211/1131 [01:33<04:16,  3.58it/s]



 19%|█▊        | 212/1131 [01:33<05:23,  2.84it/s]



 19%|█▉        | 213/1131 [01:34<07:39,  2.00it/s]



 19%|█▉        | 214/1131 [01:36<11:28,  1.33it/s]



 19%|█▉        | 216/1131 [01:36<07:04,  2.15it/s]



 19%|█▉        | 218/1131 [01:36<05:40,  2.68it/s]



 19%|█▉        | 219/1131 [01:36<04:45,  3.20it/s]



 19%|█▉        | 220/1131 [01:37<05:07,  2.96it/s]



 20%|█▉        | 221/1131 [01:38<07:16,  2.09it/s]



 20%|█▉        | 222/1131 [01:39<11:05,  1.37it/s]



 20%|█▉        | 225/1131 [01:39<05:55,  2.55it/s]



 20%|█▉        | 226/1131 [01:40<05:39,  2.67it/s]



 20%|██        | 227/1131 [01:40<05:04,  2.97it/s]



 20%|██        | 228/1131 [01:40<05:13,  2.88it/s]



 20%|██        | 229/1131 [01:41<07:37,  1.97it/s]



 20%|██        | 230/1131 [01:43<11:06,  1.35it/s]



 20%|██        | 231/1131 [01:43<08:31,  1.76it/s]



 21%|██        | 233/1131 [01:43<06:12,  2.41it/s]



 21%|██        | 234/1131 [01:43<05:18,  2.82it/s]



 21%|██        | 235/1131 [01:44<05:31,  2.70it/s]



 21%|██        | 236/1131 [01:44<04:55,  3.02it/s]



 21%|██        | 237/1131 [01:45<07:12,  2.07it/s]



 21%|██        | 238/1131 [01:46<10:53,  1.37it/s]



 21%|██        | 239/1131 [01:47<09:45,  1.52it/s]



 21%|██▏       | 241/1131 [01:47<05:52,  2.52it/s]



 21%|██▏       | 242/1131 [01:47<05:04,  2.92it/s]



 21%|██▏       | 243/1131 [01:48<05:38,  2.63it/s]



 22%|██▏       | 244/1131 [01:48<04:41,  3.15it/s]



 22%|██▏       | 245/1131 [01:49<08:27,  1.74it/s]



 22%|██▏       | 246/1131 [01:50<09:21,  1.58it/s]



 22%|██▏       | 247/1131 [01:50<07:53,  1.87it/s]



 22%|██▏       | 249/1131 [01:51<06:21,  2.31it/s]



 22%|██▏       | 250/1131 [01:51<05:45,  2.55it/s]



 22%|██▏       | 251/1131 [01:51<04:55,  2.98it/s]



 22%|██▏       | 253/1131 [01:52<06:19,  2.31it/s]



 22%|██▏       | 254/1131 [01:53<07:57,  1.84it/s]



 23%|██▎       | 255/1131 [01:53<06:57,  2.10it/s]



 23%|██▎       | 257/1131 [01:54<05:46,  2.53it/s]



 23%|██▎       | 258/1131 [01:54<05:07,  2.84it/s]



 23%|██▎       | 259/1131 [01:54<04:19,  3.36it/s]



 23%|██▎       | 260/1131 [01:55<04:15,  3.40it/s]



 23%|██▎       | 261/1131 [01:55<05:57,  2.43it/s]



 23%|██▎       | 262/1131 [01:56<08:43,  1.66it/s]



 23%|██▎       | 263/1131 [01:57<07:02,  2.05it/s]



 23%|██▎       | 265/1131 [01:57<06:21,  2.27it/s]



 24%|██▎       | 267/1131 [01:58<04:27,  3.23it/s]



 24%|██▎       | 268/1131 [01:58<04:33,  3.15it/s]



 24%|██▍       | 269/1131 [01:59<06:25,  2.23it/s]



 24%|██▍       | 270/1131 [02:00<09:01,  1.59it/s]



 24%|██▍       | 271/1131 [02:00<07:28,  1.92it/s]



 24%|██▍       | 273/1131 [02:01<06:17,  2.27it/s]



 24%|██▍       | 274/1131 [02:01<05:42,  2.50it/s]



 24%|██▍       | 276/1131 [02:02<05:15,  2.71it/s]



 24%|██▍       | 277/1131 [02:03<06:22,  2.23it/s]



 25%|██▍       | 278/1131 [02:03<07:46,  1.83it/s]



 25%|██▍       | 279/1131 [02:04<06:30,  2.18it/s]



 25%|██▍       | 280/1131 [02:04<06:46,  2.09it/s]



 25%|██▍       | 281/1131 [02:04<06:20,  2.23it/s]



 25%|██▍       | 282/1131 [02:05<05:01,  2.81it/s]



 25%|██▌       | 284/1131 [02:05<05:16,  2.68it/s]



 25%|██▌       | 285/1131 [02:06<06:37,  2.13it/s]



 25%|██▌       | 286/1131 [02:07<06:23,  2.20it/s]



 25%|██▌       | 287/1131 [02:07<06:00,  2.34it/s]



 25%|██▌       | 288/1131 [02:07<06:27,  2.17it/s]



 26%|██▌       | 289/1131 [02:08<06:06,  2.30it/s]



 26%|██▌       | 290/1131 [02:08<05:21,  2.61it/s]

 26%|██▌       | 292/1131 [02:09<04:58,  2.81it/s]



 26%|██▌       | 293/1131 [02:10<06:30,  2.14it/s]



 26%|██▌       | 294/1131 [02:10<06:21,  2.19it/s]



 26%|██▌       | 295/1131 [02:10<06:02,  2.31it/s]



 26%|██▌       | 296/1131 [02:11<05:46,  2.41it/s]



 26%|██▋       | 297/1131 [02:11<05:28,  2.54it/s]



 26%|██▋       | 298/1131 [02:11<05:28,  2.53it/s]



 27%|██▋       | 300/1131 [02:12<05:12,  2.66it/s]



 27%|██▋       | 301/1131 [02:13<06:15,  2.21it/s]



 27%|██▋       | 302/1131 [02:13<06:01,  2.29it/s]



 27%|██▋       | 303/1131 [02:14<05:33,  2.48it/s]



 27%|██▋       | 304/1131 [02:14<06:04,  2.27it/s]



 27%|██▋       | 305/1131 [02:14<04:48,  2.87it/s]



 27%|██▋       | 306/1131 [02:15<05:17,  2.60it/s]



 27%|██▋       | 308/1131 [02:16<06:01,  2.28it/s]



 27%|██▋       | 309/1131 [02:16<06:30,  2.10it/s]



 27%|██▋       | 310/1131 [02:17<05:40,  2.41it/s]



 27%|██▋       | 311/1131 [02:17<06:49,  2.00it/s]



 28%|██▊       | 313/1131 [02:18<05:11,  2.63it/s]



 28%|██▊       | 314/1131 [02:18<04:40,  2.92it/s]



 28%|██▊       | 315/1131 [02:18<05:11,  2.62it/s]



 28%|██▊       | 316/1131 [02:19<06:15,  2.17it/s]



 28%|██▊       | 317/1131 [02:20<06:54,  1.97it/s]



 28%|██▊       | 318/1131 [02:20<07:09,  1.89it/s]



 28%|██▊       | 319/1131 [02:20<05:36,  2.42it/s]



 28%|██▊       | 320/1131 [02:21<06:30,  2.08it/s]



 28%|██▊       | 322/1131 [02:22<05:07,  2.63it/s]



 29%|██▊       | 323/1131 [02:22<06:11,  2.18it/s]



 29%|██▊       | 325/1131 [02:23<05:13,  2.57it/s]



 29%|██▉       | 326/1131 [02:24<06:37,  2.03it/s]



 29%|██▉       | 328/1131 [02:24<05:51,  2.28it/s]



 29%|██▉       | 329/1131 [02:25<04:59,  2.68it/s]



 29%|██▉       | 330/1131 [02:25<05:13,  2.56it/s]



 29%|██▉       | 331/1131 [02:26<06:20,  2.10it/s]



 29%|██▉       | 332/1131 [02:26<05:29,  2.43it/s]



 29%|██▉       | 333/1131 [02:26<04:53,  2.72it/s]



 30%|██▉       | 334/1131 [02:27<06:25,  2.07it/s]



 30%|██▉       | 335/1131 [02:27<05:04,  2.61it/s]



 30%|██▉       | 336/1131 [02:28<06:02,  2.19it/s]



 30%|██▉       | 338/1131 [02:28<04:50,  2.73it/s]



 30%|██▉       | 339/1131 [02:29<06:57,  1.90it/s]



 30%|███       | 341/1131 [02:30<04:30,  2.93it/s]



 30%|███       | 342/1131 [02:31<06:30,  2.02it/s]



 30%|███       | 343/1131 [02:31<05:46,  2.27it/s]



 30%|███       | 344/1131 [02:31<04:52,  2.69it/s]



 31%|███       | 345/1131 [02:31<05:18,  2.47it/s]



 31%|███       | 346/1131 [02:32<04:34,  2.86it/s]



 31%|███       | 347/1131 [02:33<07:05,  1.84it/s]



 31%|███       | 348/1131 [02:33<05:46,  2.26it/s]



 31%|███       | 349/1131 [02:33<04:46,  2.73it/s]



 31%|███       | 350/1131 [02:34<06:22,  2.04it/s]



 31%|███       | 351/1131 [02:34<06:51,  1.89it/s]



 31%|███       | 352/1131 [02:35<05:15,  2.47it/s]



 31%|███       | 353/1131 [02:35<05:14,  2.47it/s]



 31%|███▏      | 354/1131 [02:35<04:10,  3.10it/s]



 31%|███▏      | 355/1131 [02:36<06:15,  2.07it/s]



 31%|███▏      | 356/1131 [02:37<06:43,  1.92it/s]



 32%|███▏      | 357/1131 [02:37<05:06,  2.53it/s]



 32%|███▏      | 358/1131 [02:37<05:21,  2.41it/s]



 32%|███▏      | 359/1131 [02:38<05:58,  2.15it/s]



 32%|███▏      | 360/1131 [02:38<06:16,  2.05it/s]



 32%|███▏      | 362/1131 [02:39<04:44,  2.70it/s]



 32%|███▏      | 363/1131 [02:40<06:08,  2.09it/s]



 32%|███▏      | 364/1131 [02:40<06:09,  2.08it/s]



 32%|███▏      | 366/1131 [02:41<04:46,  2.67it/s]



 32%|███▏      | 367/1131 [02:41<05:38,  2.26it/s]



 33%|███▎      | 368/1131 [02:42<05:23,  2.36it/s]



 33%|███▎      | 370/1131 [02:42<04:34,  2.77it/s]



 33%|███▎      | 371/1131 [02:43<05:48,  2.18it/s]



 33%|███▎      | 372/1131 [02:43<06:02,  2.10it/s]



 33%|███▎      | 374/1131 [02:44<04:26,  2.84it/s]



 33%|███▎      | 375/1131 [02:44<05:18,  2.38it/s]



 33%|███▎      | 376/1131 [02:45<05:07,  2.45it/s]



 33%|███▎      | 377/1131 [02:45<04:30,  2.79it/s]



 33%|███▎      | 378/1131 [02:45<04:31,  2.77it/s]



 34%|███▎      | 379/1131 [02:46<07:06,  1.76it/s]



 34%|███▎      | 380/1131 [02:47<05:41,  2.20it/s]



 34%|███▎      | 381/1131 [02:47<04:37,  2.70it/s]



 34%|███▍      | 382/1131 [02:47<03:58,  3.14it/s]



 34%|███▍      | 383/1131 [02:48<06:24,  1.95it/s]



 34%|███▍      | 385/1131 [02:49<05:57,  2.09it/s]



 34%|███▍      | 387/1131 [02:50<06:27,  1.92it/s]



 34%|███▍      | 388/1131 [02:50<05:31,  2.24it/s]



 34%|███▍      | 390/1131 [02:50<03:48,  3.24it/s]



 35%|███▍      | 391/1131 [02:52<06:16,  1.97it/s]



 35%|███▍      | 392/1131 [02:52<05:08,  2.39it/s]



 35%|███▍      | 393/1131 [02:52<05:39,  2.18it/s]



 35%|███▍      | 395/1131 [02:53<06:06,  2.01it/s]



 35%|███▌      | 396/1131 [02:54<05:33,  2.21it/s]



 35%|███▌      | 397/1131 [02:54<04:31,  2.70it/s]



 35%|███▌      | 399/1131 [02:55<05:42,  2.14it/s]



 35%|███▌      | 400/1131 [02:55<05:32,  2.20it/s]



 35%|███▌      | 401/1131 [02:56<05:30,  2.21it/s]



 36%|███▌      | 402/1131 [02:56<05:02,  2.41it/s]



 36%|███▌      | 403/1131 [02:57<06:07,  1.98it/s]



 36%|███▌      | 404/1131 [02:57<05:20,  2.27it/s]



 36%|███▌      | 405/1131 [02:57<04:29,  2.70it/s]



 36%|███▌      | 407/1131 [02:58<05:07,  2.36it/s]



 36%|███▌      | 408/1131 [02:59<05:12,  2.31it/s]



 36%|███▌      | 409/1131 [02:59<05:36,  2.14it/s]



 36%|███▋      | 410/1131 [03:00<05:42,  2.11it/s]



 36%|███▋      | 411/1131 [03:01<06:30,  1.85it/s]



 37%|███▋      | 413/1131 [03:01<03:55,  3.05it/s]



 37%|███▋      | 414/1131 [03:01<03:52,  3.08it/s]



 37%|███▋      | 415/1131 [03:02<04:42,  2.53it/s]



 37%|███▋      | 416/1131 [03:02<04:53,  2.44it/s]



 37%|███▋      | 417/1131 [03:03<05:18,  2.24it/s]



 37%|███▋      | 418/1131 [03:03<05:40,  2.09it/s]



 37%|███▋      | 419/1131 [03:04<07:30,  1.58it/s]



 37%|███▋      | 421/1131 [03:05<04:51,  2.43it/s]



 37%|███▋      | 423/1131 [03:05<04:23,  2.68it/s]



 37%|███▋      | 424/1131 [03:05<03:52,  3.04it/s]



 38%|███▊      | 425/1131 [03:07<06:20,  1.85it/s]



 38%|███▊      | 426/1131 [03:07<05:36,  2.10it/s]



 38%|███▊      | 427/1131 [03:08<06:16,  1.87it/s]



 38%|███▊      | 428/1131 [03:08<06:00,  1.95it/s]



 38%|███▊      | 430/1131 [03:08<04:05,  2.85it/s]



 38%|███▊      | 432/1131 [03:09<03:27,  3.38it/s]



 38%|███▊      | 433/1131 [03:10<05:29,  2.12it/s]



 38%|███▊      | 434/1131 [03:10<05:55,  1.96it/s]



 38%|███▊      | 435/1131 [03:11<05:26,  2.13it/s]



 39%|███▊      | 436/1131 [03:12<06:15,  1.85it/s]



 39%|███▉      | 439/1131 [03:12<03:08,  3.67it/s]



 39%|███▉      | 440/1131 [03:12<03:50,  2.99it/s]

 39%|███▉      | 441/1131 [03:13<05:13,  2.20it/s]



 39%|███▉      | 442/1131 [03:14<06:03,  1.90it/s]



 39%|███▉      | 443/1131 [03:14<04:54,  2.34it/s]



 39%|███▉      | 444/1131 [03:15<05:58,  1.92it/s]



 39%|███▉      | 446/1131 [03:15<03:46,  3.03it/s]



 40%|███▉      | 447/1131 [03:15<03:15,  3.50it/s]



 40%|███▉      | 448/1131 [03:15<03:18,  3.45it/s]



 40%|███▉      | 449/1131 [03:16<05:20,  2.13it/s]



 40%|███▉      | 450/1131 [03:17<06:06,  1.86it/s]



 40%|███▉      | 451/1131 [03:17<05:13,  2.17it/s]



 40%|███▉      | 452/1131 [03:18<06:20,  1.78it/s]



 40%|████      | 455/1131 [03:18<03:25,  3.28it/s]



 40%|████      | 456/1131 [03:19<03:04,  3.66it/s]



 40%|████      | 457/1131 [03:20<05:28,  2.05it/s]



 40%|████      | 458/1131 [03:21<06:20,  1.77it/s]



 41%|████      | 459/1131 [03:21<05:35,  2.00it/s]



 41%|████      | 460/1131 [03:21<05:32,  2.02it/s]



 41%|████      | 462/1131 [03:22<03:33,  3.13it/s]



 41%|████      | 463/1131 [03:22<04:44,  2.35it/s]



 41%|████      | 465/1131 [03:24<05:44,  1.93it/s]



 41%|████      | 466/1131 [03:24<04:49,  2.30it/s]



 41%|████▏     | 467/1131 [03:24<04:50,  2.28it/s]



 41%|████▏     | 468/1131 [03:25<05:05,  2.17it/s]



 41%|████▏     | 469/1131 [03:25<04:31,  2.43it/s]



 42%|████▏     | 471/1131 [03:26<04:14,  2.59it/s]



 42%|████▏     | 472/1131 [03:26<04:40,  2.35it/s]



 42%|████▏     | 473/1131 [03:28<06:51,  1.60it/s]



 42%|████▏     | 474/1131 [03:28<05:47,  1.89it/s]



 42%|████▏     | 475/1131 [03:28<04:33,  2.40it/s]



 42%|████▏     | 476/1131 [03:28<04:55,  2.22it/s]



 42%|████▏     | 477/1131 [03:29<03:58,  2.75it/s]



 42%|████▏     | 478/1131 [03:29<03:37,  3.01it/s]



 42%|████▏     | 479/1131 [03:29<04:25,  2.46it/s]



 42%|████▏     | 480/1131 [03:30<04:49,  2.25it/s]



 43%|████▎     | 481/1131 [03:31<06:10,  1.75it/s]



 43%|████▎     | 482/1131 [03:31<04:53,  2.21it/s]



 43%|████▎     | 483/1131 [03:31<04:49,  2.24it/s]



 43%|████▎     | 484/1131 [03:32<04:52,  2.21it/s]



 43%|████▎     | 485/1131 [03:32<03:51,  2.79it/s]



 43%|████▎     | 486/1131 [03:32<03:04,  3.51it/s]



 43%|████▎     | 487/1131 [03:33<04:10,  2.57it/s]



 43%|████▎     | 488/1131 [03:33<04:01,  2.66it/s]



 43%|████▎     | 489/1131 [03:34<06:37,  1.62it/s]



 43%|████▎     | 490/1131 [03:34<05:01,  2.13it/s]



 43%|████▎     | 491/1131 [03:35<05:54,  1.81it/s]



 44%|████▎     | 493/1131 [03:35<03:26,  3.09it/s]



 44%|████▎     | 494/1131 [03:36<03:19,  3.19it/s]



 44%|████▍     | 495/1131 [03:36<04:40,  2.27it/s]



 44%|████▍     | 496/1131 [03:37<04:15,  2.48it/s]



 44%|████▍     | 497/1131 [03:38<07:14,  1.46it/s]



 44%|████▍     | 499/1131 [03:39<05:11,  2.03it/s]



 44%|████▍     | 500/1131 [03:39<04:28,  2.35it/s]



 44%|████▍     | 501/1131 [03:39<04:15,  2.47it/s]



 44%|████▍     | 502/1131 [03:39<03:45,  2.79it/s]



 44%|████▍     | 503/1131 [03:40<03:55,  2.67it/s]



 45%|████▍     | 504/1131 [03:40<04:00,  2.61it/s]



 45%|████▍     | 505/1131 [03:41<06:31,  1.60it/s]



 45%|████▍     | 506/1131 [03:42<05:24,  1.92it/s]



 45%|████▍     | 507/1131 [03:42<04:39,  2.24it/s]



 45%|████▍     | 508/1131 [03:43<05:08,  2.02it/s]



 45%|████▌     | 510/1131 [03:43<03:31,  2.93it/s]



 45%|████▌     | 511/1131 [03:43<03:31,  2.93it/s]



 45%|████▌     | 512/1131 [03:44<03:54,  2.64it/s]



 45%|████▌     | 513/1131 [03:45<05:45,  1.79it/s]



 45%|████▌     | 514/1131 [03:45<05:38,  1.82it/s]



 46%|████▌     | 516/1131 [03:46<04:41,  2.19it/s]



 46%|████▌     | 517/1131 [03:46<03:54,  2.62it/s]



 46%|████▌     | 519/1131 [03:47<03:12,  3.18it/s]



 46%|████▌     | 520/1131 [03:47<03:57,  2.57it/s]



 46%|████▌     | 521/1131 [03:48<04:57,  2.05it/s]



 46%|████▌     | 522/1131 [03:49<05:19,  1.91it/s]



 46%|████▋     | 524/1131 [03:49<04:42,  2.15it/s]



 47%|████▋     | 526/1131 [03:50<03:12,  3.14it/s]



 47%|████▋     | 528/1131 [03:50<03:32,  2.83it/s]



 47%|████▋     | 529/1131 [03:51<04:20,  2.32it/s]



 47%|████▋     | 530/1131 [03:52<05:03,  1.98it/s]



 47%|████▋     | 531/1131 [03:52<04:21,  2.29it/s]



 47%|████▋     | 532/1131 [03:53<04:53,  2.04it/s]



 47%|████▋     | 534/1131 [03:53<03:07,  3.18it/s]



 47%|████▋     | 535/1131 [03:53<02:39,  3.74it/s]



 47%|████▋     | 536/1131 [03:54<04:04,  2.43it/s]



 47%|████▋     | 537/1131 [03:54<04:31,  2.19it/s]



 48%|████▊     | 538/1131 [03:55<05:28,  1.80it/s]



 48%|████▊     | 539/1131 [03:55<04:19,  2.28it/s]



 48%|████▊     | 540/1131 [03:56<05:33,  1.77it/s]



 48%|████▊     | 543/1131 [03:57<03:33,  2.75it/s]



 48%|████▊     | 544/1131 [03:58<04:44,  2.06it/s]



 48%|████▊     | 545/1131 [03:58<04:00,  2.43it/s]



 48%|████▊     | 546/1131 [03:59<04:25,  2.20it/s]



 48%|████▊     | 547/1131 [03:59<03:51,  2.52it/s]



 48%|████▊     | 548/1131 [04:00<04:53,  1.99it/s]



 49%|████▊     | 549/1131 [04:00<04:33,  2.13it/s]



 49%|████▊     | 550/1131 [04:00<04:05,  2.37it/s]



 49%|████▊     | 551/1131 [04:00<03:22,  2.86it/s]



 49%|████▉     | 552/1131 [04:01<05:14,  1.84it/s]



 49%|████▉     | 553/1131 [04:02<04:03,  2.37it/s]



 49%|████▉     | 554/1131 [04:02<03:56,  2.44it/s]



 49%|████▉     | 555/1131 [04:03<04:50,  1.98it/s]



 49%|████▉     | 556/1131 [04:03<04:31,  2.12it/s]



 49%|████▉     | 557/1131 [04:04<04:24,  2.17it/s]



 49%|████▉     | 559/1131 [04:04<03:11,  2.98it/s]



 50%|████▉     | 560/1131 [04:05<04:55,  1.93it/s]



 50%|████▉     | 562/1131 [04:05<03:42,  2.55it/s]



 50%|████▉     | 563/1131 [04:06<04:06,  2.30it/s]



 50%|████▉     | 564/1131 [04:06<04:07,  2.29it/s]



 50%|████▉     | 565/1131 [04:07<04:03,  2.32it/s]



 50%|█████     | 567/1131 [04:07<03:05,  3.04it/s]



 50%|█████     | 568/1131 [04:08<04:44,  1.98it/s]



 50%|█████     | 569/1131 [04:08<03:59,  2.35it/s]



 50%|█████     | 570/1131 [04:09<03:39,  2.56it/s]



 50%|█████     | 571/1131 [04:09<03:59,  2.34it/s]



 51%|█████     | 572/1131 [04:10<04:26,  2.09it/s]



 51%|█████     | 573/1131 [04:10<04:13,  2.20it/s]



 51%|█████     | 574/1131 [04:10<03:17,  2.82it/s]



 51%|█████     | 576/1131 [04:12<04:31,  2.04it/s]



 51%|█████     | 577/1131 [04:12<04:08,  2.23it/s]



 51%|█████     | 579/1131 [04:13<04:41,  1.96it/s]



 51%|█████▏    | 580/1131 [04:13<03:52,  2.37it/s]



 51%|█████▏    | 581/1131 [04:14<04:12,  2.17it/s]



 52%|█████▏    | 583/1131 [04:14<02:43,  3.36it/s]



 52%|█████▏    | 584/1131 [04:16<05:16,  1.73it/s]



 52%|█████▏    | 587/1131 [04:17<04:12,  2.15it/s]



 52%|█████▏    | 589/1131 [04:17<03:55,  2.30it/s]



 52%|█████▏    | 590/1131 [04:18<03:21,  2.68it/s]

 52%|█████▏    | 591/1131 [04:18<03:13,  2.79it/s]



 52%|█████▏    | 592/1131 [04:19<04:47,  1.87it/s]



 52%|█████▏    | 593/1131 [04:19<04:00,  2.23it/s]



 53%|█████▎    | 595/1131 [04:20<04:20,  2.06it/s]



 53%|█████▎    | 596/1131 [04:21<03:59,  2.23it/s]



 53%|█████▎    | 597/1131 [04:21<04:03,  2.19it/s]



 53%|█████▎    | 599/1131 [04:21<03:06,  2.86it/s]



 53%|█████▎    | 600/1131 [04:22<04:01,  2.20it/s]



 53%|█████▎    | 601/1131 [04:23<03:48,  2.31it/s]



 53%|█████▎    | 603/1131 [04:24<03:59,  2.20it/s]



 53%|█████▎    | 604/1131 [04:24<04:25,  1.98it/s]



 53%|█████▎    | 605/1131 [04:24<03:53,  2.25it/s]



 54%|█████▎    | 606/1131 [04:25<03:30,  2.50it/s]



 54%|█████▎    | 607/1131 [04:25<02:59,  2.92it/s]



 54%|█████▍    | 608/1131 [04:26<04:14,  2.05it/s]



 54%|█████▍    | 609/1131 [04:26<03:21,  2.59it/s]



 54%|█████▍    | 610/1131 [04:26<03:46,  2.30it/s]



 54%|█████▍    | 611/1131 [04:27<03:52,  2.24it/s]



 54%|█████▍    | 612/1131 [04:28<04:39,  1.86it/s]



 54%|█████▍    | 613/1131 [04:28<04:08,  2.08it/s]



 54%|█████▍    | 614/1131 [04:28<03:21,  2.57it/s]



 54%|█████▍    | 615/1131 [04:29<03:14,  2.65it/s]



 54%|█████▍    | 616/1131 [04:30<05:12,  1.65it/s]



 55%|█████▍    | 617/1131 [04:30<04:14,  2.02it/s]



 55%|█████▍    | 619/1131 [04:30<03:06,  2.74it/s]



 55%|█████▍    | 620/1131 [04:31<04:05,  2.09it/s]



 55%|█████▍    | 621/1131 [04:32<04:05,  2.08it/s]



 55%|█████▌    | 623/1131 [04:32<03:17,  2.57it/s]



 55%|█████▌    | 624/1131 [04:33<04:10,  2.03it/s]



 55%|█████▌    | 625/1131 [04:33<03:53,  2.16it/s]



 55%|█████▌    | 626/1131 [04:34<03:14,  2.60it/s]



 55%|█████▌    | 627/1131 [04:34<02:42,  3.10it/s]



 56%|█████▌    | 628/1131 [04:35<03:50,  2.18it/s]



 56%|█████▌    | 629/1131 [04:35<03:46,  2.22it/s]



 56%|█████▌    | 631/1131 [04:36<03:20,  2.49it/s]



 56%|█████▌    | 632/1131 [04:36<03:47,  2.19it/s]



 56%|█████▌    | 633/1131 [04:37<04:07,  2.02it/s]



 56%|█████▌    | 635/1131 [04:37<02:40,  3.09it/s]



 56%|█████▌    | 636/1131 [04:38<04:02,  2.04it/s]



 56%|█████▋    | 637/1131 [04:38<03:16,  2.51it/s]



 56%|█████▋    | 638/1131 [04:38<02:41,  3.05it/s]



 56%|█████▋    | 639/1131 [04:39<03:30,  2.34it/s]



 57%|█████▋    | 640/1131 [04:40<03:58,  2.06it/s]



 57%|█████▋    | 641/1131 [04:40<04:16,  1.91it/s]



 57%|█████▋    | 643/1131 [04:41<03:14,  2.51it/s]



 57%|█████▋    | 644/1131 [04:42<04:09,  1.95it/s]



 57%|█████▋    | 645/1131 [04:42<03:59,  2.03it/s]



 57%|█████▋    | 647/1131 [04:42<02:53,  2.78it/s]



 57%|█████▋    | 648/1131 [04:43<03:30,  2.30it/s]



 57%|█████▋    | 649/1131 [04:44<03:41,  2.18it/s]



 57%|█████▋    | 650/1131 [04:44<03:53,  2.06it/s]



 58%|█████▊    | 651/1131 [04:44<03:02,  2.63it/s]



 58%|█████▊    | 652/1131 [04:45<04:22,  1.82it/s]



 58%|█████▊    | 654/1131 [04:46<03:27,  2.30it/s]



 58%|█████▊    | 656/1131 [04:47<03:05,  2.56it/s]



 58%|█████▊    | 657/1131 [04:47<03:49,  2.07it/s]



 58%|█████▊    | 658/1131 [04:48<03:20,  2.36it/s]



 58%|█████▊    | 659/1131 [04:48<03:01,  2.60it/s]



 58%|█████▊    | 660/1131 [04:49<03:55,  2.00it/s]



 59%|█████▊    | 662/1131 [04:49<03:18,  2.37it/s]



 59%|█████▊    | 664/1131 [04:50<02:42,  2.87it/s]



 59%|█████▉    | 665/1131 [04:51<03:58,  1.96it/s]



 59%|█████▉    | 667/1131 [04:51<02:57,  2.62it/s]



 59%|█████▉    | 668/1131 [04:52<03:36,  2.14it/s]



 59%|█████▉    | 670/1131 [04:53<03:02,  2.53it/s]



 59%|█████▉    | 671/1131 [04:53<02:52,  2.66it/s]



 59%|█████▉    | 672/1131 [04:53<02:33,  2.99it/s]



 60%|█████▉    | 673/1131 [04:54<04:05,  1.86it/s]



 60%|█████▉    | 674/1131 [04:54<03:22,  2.26it/s]



 60%|█████▉    | 675/1131 [04:55<03:51,  1.97it/s]



 60%|█████▉    | 676/1131 [04:56<03:48,  1.99it/s]



 60%|█████▉    | 677/1131 [04:56<03:01,  2.50it/s]



 60%|█████▉    | 678/1131 [04:56<03:23,  2.23it/s]



 60%|██████    | 679/1131 [04:57<03:32,  2.13it/s]



 60%|██████    | 680/1131 [04:57<02:59,  2.51it/s]



 60%|██████    | 681/1131 [04:58<04:14,  1.77it/s]



 60%|██████    | 683/1131 [04:59<03:22,  2.21it/s]



 60%|██████    | 684/1131 [04:59<02:53,  2.57it/s]



 61%|██████    | 685/1131 [04:59<03:23,  2.19it/s]



 61%|██████    | 686/1131 [05:00<03:34,  2.07it/s]



 61%|██████    | 687/1131 [05:00<03:17,  2.25it/s]



 61%|██████    | 688/1131 [05:01<03:04,  2.40it/s]



 61%|██████    | 689/1131 [05:01<03:33,  2.07it/s]



 61%|██████    | 690/1131 [05:02<03:04,  2.39it/s]



 61%|██████    | 691/1131 [05:02<02:48,  2.61it/s]



 61%|██████    | 692/1131 [05:02<02:50,  2.58it/s]



 61%|██████▏   | 693/1131 [05:03<03:43,  1.96it/s]



 61%|██████▏   | 694/1131 [05:04<03:53,  1.87it/s]



 61%|██████▏   | 695/1131 [05:04<03:16,  2.22it/s]



 62%|██████▏   | 696/1131 [05:04<02:36,  2.79it/s]



 62%|██████▏   | 697/1131 [05:05<03:46,  1.91it/s]



 62%|██████▏   | 698/1131 [05:05<02:53,  2.50it/s]



 62%|██████▏   | 699/1131 [05:05<02:22,  3.04it/s]



 62%|██████▏   | 700/1131 [05:06<02:25,  2.95it/s]



 62%|██████▏   | 701/1131 [05:07<03:32,  2.02it/s]



 62%|██████▏   | 702/1131 [05:07<03:49,  1.87it/s]



 62%|██████▏   | 703/1131 [05:07<03:00,  2.37it/s]



 62%|██████▏   | 704/1131 [05:07<02:27,  2.89it/s]



 62%|██████▏   | 705/1131 [05:08<03:46,  1.88it/s]



 63%|██████▎   | 707/1131 [05:09<02:17,  3.07it/s]



 63%|██████▎   | 708/1131 [05:09<02:28,  2.86it/s]



 63%|██████▎   | 709/1131 [05:10<03:45,  1.87it/s]



 63%|██████▎   | 710/1131 [05:11<03:31,  1.99it/s]



 63%|██████▎   | 711/1131 [05:11<03:17,  2.13it/s]



 63%|██████▎   | 712/1131 [05:11<02:33,  2.74it/s]



 63%|██████▎   | 713/1131 [05:12<03:20,  2.09it/s]



 63%|██████▎   | 715/1131 [05:12<02:09,  3.22it/s]



 63%|██████▎   | 716/1131 [05:13<02:35,  2.66it/s]



 63%|██████▎   | 717/1131 [05:14<03:59,  1.73it/s]



 63%|██████▎   | 718/1131 [05:14<03:25,  2.01it/s]



 64%|██████▎   | 719/1131 [05:14<03:21,  2.04it/s]



 64%|██████▎   | 721/1131 [05:15<03:23,  2.01it/s]



 64%|██████▍   | 722/1131 [05:16<02:45,  2.48it/s]



 64%|██████▍   | 723/1131 [05:16<02:30,  2.71it/s]



 64%|██████▍   | 724/1131 [05:16<02:24,  2.81it/s]



 64%|██████▍   | 725/1131 [05:17<03:45,  1.80it/s]



 64%|██████▍   | 727/1131 [05:18<03:04,  2.19it/s]



 64%|██████▍   | 728/1131 [05:18<02:43,  2.47it/s]



 64%|██████▍   | 729/1131 [05:19<03:04,  2.18it/s]



 65%|██████▍   | 730/1131 [05:19<03:09,  2.12it/s]



 65%|██████▍   | 731/1131 [05:19<02:30,  2.67it/s]



 65%|██████▍   | 732/1131 [05:20<02:16,  2.91it/s]



 65%|██████▍   | 733/1131 [05:21<03:38,  1.82it/s]



 65%|██████▍   | 734/1131 [05:21<02:48,  2.35it/s]

 65%|██████▍   | 735/1131 [05:21<02:30,  2.63it/s]



 65%|██████▌   | 736/1131 [05:22<03:18,  1.99it/s]



 65%|██████▌   | 737/1131 [05:22<03:22,  1.95it/s]



 65%|██████▌   | 738/1131 [05:23<02:53,  2.27it/s]



 65%|██████▌   | 739/1131 [05:23<02:15,  2.89it/s]



 65%|██████▌   | 740/1131 [05:23<01:58,  3.30it/s]



 66%|██████▌   | 741/1131 [05:24<03:34,  1.82it/s]



 66%|██████▌   | 743/1131 [05:24<02:23,  2.71it/s]



 66%|██████▌   | 744/1131 [05:25<03:00,  2.15it/s]



 66%|██████▌   | 745/1131 [05:26<03:15,  1.97it/s]



 66%|██████▌   | 746/1131 [05:26<02:50,  2.25it/s]



 66%|██████▌   | 747/1131 [05:26<02:15,  2.83it/s]



 66%|██████▌   | 749/1131 [05:27<02:52,  2.21it/s]



 66%|██████▋   | 750/1131 [05:28<02:40,  2.37it/s]



 66%|██████▋   | 751/1131 [05:28<02:29,  2.54it/s]



 66%|██████▋   | 752/1131 [05:29<02:50,  2.22it/s]



 67%|██████▋   | 753/1131 [05:29<03:19,  1.90it/s]



 67%|██████▋   | 755/1131 [05:30<02:25,  2.59it/s]



 67%|██████▋   | 756/1131 [05:30<02:14,  2.78it/s]



 67%|██████▋   | 757/1131 [05:31<03:27,  1.80it/s]



 67%|██████▋   | 758/1131 [05:31<02:42,  2.29it/s]



 67%|██████▋   | 759/1131 [05:32<03:12,  1.93it/s]



 67%|██████▋   | 760/1131 [05:32<03:00,  2.05it/s]



 67%|██████▋   | 761/1131 [05:33<02:36,  2.37it/s]



 67%|██████▋   | 762/1131 [05:33<02:09,  2.86it/s]



 67%|██████▋   | 763/1131 [05:34<02:57,  2.07it/s]



 68%|██████▊   | 764/1131 [05:34<02:24,  2.54it/s]



 68%|██████▊   | 765/1131 [05:35<03:03,  1.99it/s]



 68%|██████▊   | 766/1131 [05:35<02:41,  2.25it/s]



 68%|██████▊   | 767/1131 [05:36<03:32,  1.71it/s]



 68%|██████▊   | 769/1131 [05:36<02:03,  2.93it/s]



 68%|██████▊   | 770/1131 [05:36<01:58,  3.04it/s]



 68%|██████▊   | 771/1131 [05:37<02:52,  2.08it/s]



 68%|██████▊   | 772/1131 [05:37<02:35,  2.31it/s]



 68%|██████▊   | 773/1131 [05:38<02:45,  2.17it/s]



 68%|██████▊   | 774/1131 [05:38<02:31,  2.35it/s]



 69%|██████▊   | 775/1131 [05:39<03:16,  1.81it/s]



 69%|██████▉   | 778/1131 [05:40<01:59,  2.96it/s]



 69%|██████▉   | 779/1131 [05:40<02:28,  2.36it/s]



 69%|██████▉   | 780/1131 [05:41<02:28,  2.36it/s]



 69%|██████▉   | 781/1131 [05:41<02:30,  2.32it/s]



 69%|██████▉   | 782/1131 [05:42<02:33,  2.27it/s]



 69%|██████▉   | 783/1131 [05:42<02:57,  1.96it/s]



 69%|██████▉   | 784/1131 [05:43<02:22,  2.43it/s]



 69%|██████▉   | 785/1131 [05:43<02:04,  2.78it/s]



 69%|██████▉   | 786/1131 [05:43<01:45,  3.28it/s]



 70%|██████▉   | 787/1131 [05:44<02:20,  2.44it/s]



 70%|██████▉   | 788/1131 [05:45<03:15,  1.76it/s]



 70%|██████▉   | 789/1131 [05:45<02:34,  2.21it/s]



 70%|██████▉   | 790/1131 [05:45<02:12,  2.57it/s]



 70%|██████▉   | 791/1131 [05:46<02:52,  1.97it/s]



 70%|███████   | 792/1131 [05:46<02:54,  1.95it/s]



 70%|███████   | 794/1131 [05:47<01:46,  3.16it/s]



 70%|███████   | 795/1131 [05:47<02:36,  2.14it/s]



 70%|███████   | 796/1131 [05:48<03:00,  1.86it/s]



 70%|███████   | 797/1131 [05:49<02:39,  2.10it/s]



 71%|███████   | 799/1131 [05:50<02:41,  2.06it/s]



 71%|███████   | 800/1131 [05:50<02:16,  2.42it/s]



 71%|███████   | 802/1131 [05:50<01:52,  2.94it/s]



 71%|███████   | 803/1131 [05:51<02:20,  2.33it/s]



 71%|███████   | 804/1131 [05:52<03:00,  1.81it/s]



 71%|███████   | 805/1131 [05:52<02:31,  2.15it/s]



 71%|███████▏  | 806/1131 [05:52<02:02,  2.66it/s]



 71%|███████▏  | 807/1131 [05:53<02:22,  2.27it/s]



 71%|███████▏  | 808/1131 [05:53<02:08,  2.52it/s]



 72%|███████▏  | 809/1131 [05:53<01:51,  2.88it/s]



 72%|███████▏  | 810/1131 [05:54<01:56,  2.75it/s]



 72%|███████▏  | 811/1131 [05:54<02:28,  2.16it/s]



 72%|███████▏  | 812/1131 [05:55<03:03,  1.74it/s]



 72%|███████▏  | 814/1131 [05:56<02:03,  2.57it/s]



 72%|███████▏  | 815/1131 [05:56<02:07,  2.47it/s]



 72%|███████▏  | 816/1131 [05:56<02:07,  2.47it/s]



 72%|███████▏  | 817/1131 [05:57<01:57,  2.67it/s]



 72%|███████▏  | 818/1131 [05:57<02:00,  2.59it/s]



 72%|███████▏  | 819/1131 [05:58<02:35,  2.01it/s]



 73%|███████▎  | 820/1131 [05:59<02:41,  1.92it/s]



 73%|███████▎  | 821/1131 [05:59<02:07,  2.42it/s]



 73%|███████▎  | 822/1131 [05:59<01:59,  2.59it/s]



 73%|███████▎  | 823/1131 [05:59<01:48,  2.83it/s]



 73%|███████▎  | 824/1131 [06:00<02:34,  1.99it/s]



 73%|███████▎  | 825/1131 [06:00<02:09,  2.37it/s]



 73%|███████▎  | 826/1131 [06:01<02:30,  2.03it/s]



 73%|███████▎  | 827/1131 [06:01<02:09,  2.34it/s]



 73%|███████▎  | 828/1131 [06:02<02:13,  2.27it/s]



 73%|███████▎  | 829/1131 [06:02<02:32,  1.98it/s]



 73%|███████▎  | 831/1131 [06:03<01:42,  2.94it/s]



 74%|███████▎  | 832/1131 [06:04<02:34,  1.93it/s]



Multiplets | family 5:   0%|          | 0/219 [07:56<?, ?it/s]




 74%|███████▎  | 834/1131 [06:05<02:31,  1.96it/s]



 74%|███████▍  | 835/1131 [06:05<02:14,  2.20it/s]



 74%|███████▍  | 836/1131 [06:05<01:47,  2.75it/s]



 74%|███████▍  | 837/1131 [06:06<02:36,  1.88it/s]



 74%|███████▍  | 838/1131 [06:06<02:09,  2.26it/s]



 74%|███████▍  | 839/1131 [06:06<01:44,  2.80it/s]



 74%|███████▍  | 840/1131 [06:07<02:06,  2.29it/s]



 74%|███████▍  | 841/1131 [06:08<02:19,  2.08it/s]



 74%|███████▍  | 842/1131 [06:08<02:08,  2.24it/s]



 75%|███████▍  | 843/1131 [06:08<02:02,  2.35it/s]



 75%|███████▍  | 845/1131 [06:10<02:26,  1.95it/s]



 75%|███████▍  | 846/1131 [06:10<02:00,  2.36it/s]



 75%|███████▍  | 847/1131 [06:10<01:40,  2.84it/s]



 75%|███████▍  | 848/1131 [06:10<01:49,  2.58it/s]



 75%|███████▌  | 849/1131 [06:11<02:05,  2.24it/s]



 75%|███████▌  | 850/1131 [06:11<01:56,  2.40it/s]



 75%|███████▌  | 851/1131 [06:12<01:52,  2.48it/s]



 75%|███████▌  | 852/1131 [06:12<01:35,  2.91it/s]



 75%|███████▌  | 853/1131 [06:13<02:34,  1.80it/s]



 76%|███████▌  | 854/1131 [06:13<02:07,  2.18it/s]



 76%|███████▌  | 855/1131 [06:13<01:43,  2.67it/s]



 76%|███████▌  | 856/1131 [06:14<01:38,  2.78it/s]



 76%|███████▌  | 857/1131 [06:14<02:02,  2.23it/s]



 76%|███████▌  | 858/1131 [06:15<02:09,  2.10it/s]



 76%|███████▌  | 859/1131 [06:15<01:45,  2.59it/s]



 76%|███████▌  | 860/1131 [06:15<01:35,  2.83it/s]



 76%|███████▌  | 861/1131 [06:17<02:40,  1.68it/s]



 76%|███████▌  | 862/1131 [06:17<02:19,  1.93it/s]



 76%|███████▋  | 864/1131 [06:17<01:49,  2.44it/s]



 76%|███████▋  | 865/1131 [06:18<01:37,  2.74it/s]



 77%|███████▋  | 866/1131 [06:19<02:19,  1.90it/s]



 77%|███████▋  | 868/1131 [06:19<01:32,  2.85it/s]



 77%|███████▋  | 869/1131 [06:20<02:10,  2.00it/s]



 77%|███████▋  | 870/1131 [06:20<02:12,  1.97it/s]



 77%|███████▋  | 871/1131 [06:21<02:01,  2.14it/s]



 77%|███████▋  | 872/1131 [06:21<01:38,  2.64it/s]

 77%|███████▋  | 873/1131 [06:21<01:32,  2.78it/s]



 77%|███████▋  | 874/1131 [06:22<02:15,  1.89it/s]



 77%|███████▋  | 875/1131 [06:22<01:50,  2.32it/s]



 77%|███████▋  | 876/1131 [06:23<01:31,  2.78it/s]



 78%|███████▊  | 877/1131 [06:23<01:50,  2.30it/s]



 78%|███████▊  | 878/1131 [06:24<02:17,  1.84it/s]



 78%|███████▊  | 879/1131 [06:24<01:48,  2.32it/s]



 78%|███████▊  | 880/1131 [06:24<01:28,  2.83it/s]



 78%|███████▊  | 881/1131 [06:25<01:41,  2.47it/s]



 78%|███████▊  | 882/1131 [06:26<02:08,  1.94it/s]



 78%|███████▊  | 883/1131 [06:26<01:48,  2.29it/s]



 78%|███████▊  | 885/1131 [06:26<01:30,  2.70it/s]



 78%|███████▊  | 886/1131 [06:27<02:05,  1.95it/s]



 78%|███████▊  | 887/1131 [06:28<01:41,  2.40it/s]



 79%|███████▊  | 889/1131 [06:28<01:33,  2.60it/s]



 79%|███████▊  | 890/1131 [06:29<01:48,  2.23it/s]



 79%|███████▉  | 891/1131 [06:29<01:46,  2.25it/s]



 79%|███████▉  | 892/1131 [06:29<01:27,  2.72it/s]



 79%|███████▉  | 893/1131 [06:30<01:23,  2.86it/s]



 79%|███████▉  | 894/1131 [06:31<02:06,  1.88it/s]



 79%|███████▉  | 895/1131 [06:31<01:52,  2.09it/s]



 79%|███████▉  | 896/1131 [06:31<01:35,  2.45it/s]



 79%|███████▉  | 897/1131 [06:32<01:39,  2.35it/s]



 79%|███████▉  | 898/1131 [06:32<01:35,  2.45it/s]



 79%|███████▉  | 899/1131 [06:33<01:51,  2.09it/s]



 80%|███████▉  | 900/1131 [06:33<01:28,  2.60it/s]



 80%|███████▉  | 901/1131 [06:34<01:39,  2.31it/s]



 80%|███████▉  | 902/1131 [06:35<02:20,  1.64it/s]



 80%|███████▉  | 903/1131 [06:35<01:48,  2.11it/s]



 80%|███████▉  | 904/1131 [06:35<01:45,  2.16it/s]



 80%|████████  | 906/1131 [06:35<01:14,  3.00it/s]



 80%|████████  | 907/1131 [06:36<01:29,  2.51it/s]



 80%|████████  | 908/1131 [06:37<01:34,  2.36it/s]



 80%|████████  | 909/1131 [06:37<01:28,  2.52it/s]



 80%|████████  | 910/1131 [06:38<02:24,  1.53it/s]



 81%|████████  | 911/1131 [06:39<02:01,  1.81it/s]



 81%|████████  | 914/1131 [06:39<01:18,  2.78it/s]



 81%|████████  | 915/1131 [06:39<01:16,  2.81it/s]



 81%|████████  | 916/1131 [06:40<01:15,  2.87it/s]



 81%|████████  | 917/1131 [06:40<01:24,  2.52it/s]



 81%|████████  | 918/1131 [06:42<02:10,  1.63it/s]



 81%|████████▏ | 919/1131 [06:42<01:57,  1.81it/s]



 81%|████████▏ | 921/1131 [06:42<01:10,  2.99it/s]



 82%|████████▏ | 922/1131 [06:42<01:14,  2.81it/s]



 82%|████████▏ | 923/1131 [06:43<01:23,  2.50it/s]



 82%|████████▏ | 924/1131 [06:43<01:10,  2.95it/s]



 82%|████████▏ | 925/1131 [06:44<01:14,  2.76it/s]



 82%|████████▏ | 926/1131 [06:45<02:09,  1.59it/s]



 82%|████████▏ | 927/1131 [06:45<01:53,  1.80it/s]



 82%|████████▏ | 929/1131 [06:45<01:10,  2.86it/s]



 82%|████████▏ | 930/1131 [06:46<01:03,  3.15it/s]



 82%|████████▏ | 931/1131 [06:46<01:26,  2.31it/s]



 82%|████████▏ | 933/1131 [06:47<01:14,  2.64it/s]



 83%|████████▎ | 934/1131 [06:48<01:54,  1.72it/s]



 83%|████████▎ | 935/1131 [06:49<01:51,  1.76it/s]



 83%|████████▎ | 937/1131 [06:49<01:14,  2.60it/s]



 83%|████████▎ | 938/1131 [06:49<01:07,  2.84it/s]



 83%|████████▎ | 939/1131 [06:50<01:11,  2.70it/s]



 83%|████████▎ | 940/1131 [06:50<01:24,  2.26it/s]



 83%|████████▎ | 941/1131 [06:51<01:32,  2.05it/s]



 83%|████████▎ | 942/1131 [06:52<01:56,  1.62it/s]



 83%|████████▎ | 943/1131 [06:52<01:36,  1.95it/s]



 84%|████████▎ | 945/1131 [06:52<01:02,  2.99it/s]



 84%|████████▎ | 946/1131 [06:53<01:13,  2.52it/s]



 84%|████████▎ | 947/1131 [06:54<01:20,  2.28it/s]



 84%|████████▍ | 948/1131 [06:54<01:19,  2.30it/s]



 84%|████████▍ | 949/1131 [06:55<01:24,  2.14it/s]



 84%|████████▍ | 950/1131 [06:56<01:59,  1.51it/s]



 84%|████████▍ | 951/1131 [06:56<01:31,  1.98it/s]



 84%|████████▍ | 953/1131 [06:56<00:53,  3.33it/s]



 84%|████████▍ | 954/1131 [06:57<01:07,  2.63it/s]



 84%|████████▍ | 955/1131 [06:57<01:09,  2.52it/s]



 85%|████████▍ | 956/1131 [06:58<01:18,  2.23it/s]



 85%|████████▍ | 957/1131 [06:58<01:10,  2.47it/s]



 85%|████████▍ | 958/1131 [06:59<01:51,  1.56it/s]



 85%|████████▍ | 959/1131 [06:59<01:25,  2.02it/s]



 85%|████████▍ | 961/1131 [06:59<00:53,  3.19it/s]



 85%|████████▌ | 962/1131 [07:00<00:59,  2.83it/s]



 85%|████████▌ | 963/1131 [07:00<00:57,  2.91it/s]



 85%|████████▌ | 964/1131 [07:01<01:17,  2.16it/s]



 85%|████████▌ | 965/1131 [07:01<01:00,  2.76it/s]



 85%|████████▌ | 966/1131 [07:03<01:46,  1.55it/s]



 85%|████████▌ | 967/1131 [07:03<01:21,  2.01it/s]



 86%|████████▌ | 969/1131 [07:03<01:02,  2.60it/s]



 86%|████████▌ | 970/1131 [07:04<01:07,  2.37it/s]



 86%|████████▌ | 971/1131 [07:04<01:00,  2.67it/s]



 86%|████████▌ | 972/1131 [07:04<01:00,  2.61it/s]



 86%|████████▌ | 973/1131 [07:05<01:03,  2.48it/s]



 86%|████████▌ | 974/1131 [07:06<01:31,  1.72it/s]



 86%|████████▌ | 975/1131 [07:06<01:15,  2.08it/s]



 86%|████████▋ | 976/1131 [07:07<01:18,  1.97it/s]



 86%|████████▋ | 977/1131 [07:07<01:11,  2.16it/s]



 86%|████████▋ | 978/1131 [07:07<00:59,  2.59it/s]



 87%|████████▋ | 980/1131 [07:08<00:58,  2.60it/s]



 87%|████████▋ | 981/1131 [07:08<01:01,  2.46it/s]



 87%|████████▋ | 982/1131 [07:10<01:28,  1.68it/s]



 87%|████████▋ | 983/1131 [07:10<01:17,  1.90it/s]



 87%|████████▋ | 985/1131 [07:10<00:57,  2.52it/s]



 87%|████████▋ | 986/1131 [07:11<00:53,  2.69it/s]



 87%|████████▋ | 987/1131 [07:11<00:47,  3.04it/s]



 87%|████████▋ | 988/1131 [07:11<00:53,  2.66it/s]



 87%|████████▋ | 989/1131 [07:12<00:58,  2.43it/s]



 88%|████████▊ | 990/1131 [07:13<01:25,  1.66it/s]



 88%|████████▊ | 991/1131 [07:13<01:12,  1.94it/s]



 88%|████████▊ | 992/1131 [07:13<00:58,  2.36it/s]



 88%|████████▊ | 993/1131 [07:14<00:51,  2.69it/s]



 88%|████████▊ | 994/1131 [07:14<00:49,  2.78it/s]



 88%|████████▊ | 995/1131 [07:14<00:39,  3.40it/s]



 88%|████████▊ | 996/1131 [07:15<00:50,  2.66it/s]



 88%|████████▊ | 997/1131 [07:15<00:57,  2.34it/s]



 88%|████████▊ | 998/1131 [07:16<01:23,  1.59it/s]



 88%|████████▊ | 999/1131 [07:16<01:02,  2.11it/s]



 88%|████████▊ | 1000/1131 [07:17<00:55,  2.37it/s]



 89%|████████▊ | 1001/1131 [07:17<00:53,  2.44it/s]



 89%|████████▊ | 1002/1131 [07:17<00:45,  2.84it/s]



 89%|████████▉ | 1004/1131 [07:18<00:45,  2.77it/s]



 89%|████████▉ | 1005/1131 [07:19<00:50,  2.52it/s]



 89%|████████▉ | 1006/1131 [07:20<01:12,  1.72it/s]



 89%|████████▉ | 1007/1131 [07:20<01:07,  1.84it/s]



 89%|████████▉ | 1008/1131 [07:20<00:54,  2.26it/s]



 89%|████████▉ | 1009/1131 [07:21<00:50,  2.41it/s]



 89%|████████▉ | 1011/1131 [07:21<00:34,  3.48it/s]



 89%|████████▉ | 1012/1131 [07:22<00:55,  2.16it/s]



 90%|████████▉ | 1013/1131 [07:22<00:55,  2.11it/s]

 90%|████████▉ | 1014/1131 [07:23<01:01,  1.89it/s]



 90%|████████▉ | 1015/1131 [07:24<01:00,  1.90it/s]



 90%|████████▉ | 1016/1131 [07:24<00:54,  2.09it/s]



 90%|█████████ | 1018/1131 [07:24<00:32,  3.46it/s]



 90%|█████████ | 1019/1131 [07:25<00:37,  2.97it/s]



 90%|█████████ | 1020/1131 [07:26<01:00,  1.85it/s]



 90%|█████████ | 1022/1131 [07:27<00:53,  2.02it/s]



 90%|█████████ | 1023/1131 [07:27<00:58,  1.85it/s]



 91%|█████████ | 1024/1131 [07:27<00:46,  2.29it/s]



 91%|█████████ | 1026/1131 [07:28<00:29,  3.54it/s]



 91%|█████████ | 1027/1131 [07:28<00:35,  2.96it/s]



 91%|█████████ | 1028/1131 [07:29<00:54,  1.88it/s]



 91%|█████████ | 1030/1131 [07:30<00:55,  1.81it/s]



 91%|█████████ | 1031/1131 [07:31<00:48,  2.08it/s]



 91%|█████████ | 1032/1131 [07:31<00:41,  2.37it/s]



 91%|█████████▏| 1033/1131 [07:31<00:37,  2.60it/s]



 91%|█████████▏| 1034/1131 [07:31<00:30,  3.23it/s]



 92%|█████████▏| 1035/1131 [07:32<00:30,  3.13it/s]



 92%|█████████▏| 1036/1131 [07:33<00:47,  1.98it/s]



 92%|█████████▏| 1037/1131 [07:33<00:36,  2.55it/s]



 92%|█████████▏| 1038/1131 [07:34<00:53,  1.74it/s]



 92%|█████████▏| 1039/1131 [07:34<00:43,  2.10it/s]



 92%|█████████▏| 1040/1131 [07:34<00:43,  2.09it/s]



 92%|█████████▏| 1041/1131 [07:35<00:33,  2.69it/s]



 92%|█████████▏| 1042/1131 [07:35<00:29,  2.99it/s]



 92%|█████████▏| 1043/1131 [07:35<00:25,  3.39it/s]



 92%|█████████▏| 1044/1131 [07:36<00:39,  2.21it/s]



 92%|█████████▏| 1045/1131 [07:36<00:37,  2.28it/s]



 92%|█████████▏| 1046/1131 [07:38<00:59,  1.44it/s]



 93%|█████████▎| 1047/1131 [07:38<00:45,  1.85it/s]



 93%|█████████▎| 1048/1131 [07:38<00:34,  2.39it/s]



 93%|█████████▎| 1049/1131 [07:38<00:32,  2.56it/s]



 93%|█████████▎| 1050/1131 [07:38<00:28,  2.89it/s]



 93%|█████████▎| 1052/1131 [07:39<00:32,  2.45it/s]



 93%|█████████▎| 1053/1131 [07:40<00:34,  2.28it/s]



 93%|█████████▎| 1054/1131 [07:41<00:45,  1.69it/s]



 93%|█████████▎| 1056/1131 [07:42<00:35,  2.14it/s]



 93%|█████████▎| 1057/1131 [07:42<00:30,  2.39it/s]



 94%|█████████▎| 1058/1131 [07:42<00:26,  2.80it/s]



 94%|█████████▎| 1059/1131 [07:42<00:23,  3.01it/s]



 94%|█████████▎| 1060/1131 [07:43<00:24,  2.86it/s]



 94%|█████████▍| 1061/1131 [07:43<00:32,  2.17it/s]



 94%|█████████▍| 1062/1131 [07:44<00:40,  1.69it/s]



 94%|█████████▍| 1064/1131 [07:45<00:30,  2.17it/s]



 94%|█████████▍| 1065/1131 [07:45<00:29,  2.25it/s]



 94%|█████████▍| 1066/1131 [07:45<00:24,  2.62it/s]



 94%|█████████▍| 1067/1131 [07:46<00:23,  2.76it/s]



 94%|█████████▍| 1068/1131 [07:46<00:19,  3.24it/s]



 95%|█████████▍| 1069/1131 [07:47<00:25,  2.48it/s]



 95%|█████████▍| 1070/1131 [07:48<00:34,  1.76it/s]



 95%|█████████▍| 1071/1131 [07:48<00:25,  2.32it/s]



 95%|█████████▍| 1072/1131 [07:48<00:27,  2.16it/s]



 95%|█████████▍| 1073/1131 [07:49<00:24,  2.39it/s]



 95%|█████████▍| 1074/1131 [07:49<00:23,  2.38it/s]



 95%|█████████▌| 1075/1131 [07:49<00:20,  2.78it/s]



 95%|█████████▌| 1076/1131 [07:49<00:16,  3.35it/s]



 95%|█████████▌| 1077/1131 [07:50<00:22,  2.44it/s]



 95%|█████████▌| 1078/1131 [07:51<00:30,  1.73it/s]



 95%|█████████▌| 1080/1131 [07:52<00:22,  2.26it/s]



 96%|█████████▌| 1081/1131 [07:52<00:20,  2.41it/s]



 96%|█████████▌| 1082/1131 [07:53<00:23,  2.04it/s]



 96%|█████████▌| 1083/1131 [07:53<00:21,  2.28it/s]



 96%|█████████▌| 1084/1131 [07:53<00:17,  2.64it/s]



 96%|█████████▌| 1085/1131 [07:54<00:20,  2.26it/s]



 96%|█████████▌| 1086/1131 [07:54<00:22,  2.00it/s]



 96%|█████████▌| 1088/1131 [07:55<00:20,  2.12it/s]



 96%|█████████▋| 1089/1131 [07:55<00:16,  2.50it/s]



 96%|█████████▋| 1090/1131 [07:56<00:23,  1.72it/s]



 97%|█████████▋| 1092/1131 [07:57<00:15,  2.54it/s]



 97%|█████████▋| 1093/1131 [07:57<00:14,  2.65it/s]



 97%|█████████▋| 1094/1131 [07:58<00:19,  1.88it/s]



 97%|█████████▋| 1096/1131 [07:58<00:13,  2.54it/s]



 97%|█████████▋| 1097/1131 [07:59<00:11,  2.95it/s]



 97%|█████████▋| 1098/1131 [08:00<00:18,  1.80it/s]



 97%|█████████▋| 1099/1131 [08:00<00:14,  2.21it/s]



 97%|█████████▋| 1100/1131 [08:00<00:13,  2.36it/s]



 97%|█████████▋| 1101/1131 [08:01<00:10,  2.79it/s]



 97%|█████████▋| 1102/1131 [08:01<00:15,  1.92it/s]



 98%|█████████▊| 1104/1131 [08:02<00:10,  2.63it/s]



 98%|█████████▊| 1105/1131 [08:02<00:08,  3.17it/s]



 98%|█████████▊| 1106/1131 [08:03<00:12,  1.98it/s]



 98%|█████████▊| 1107/1131 [08:03<00:10,  2.22it/s]



 98%|█████████▊| 1108/1131 [08:04<00:09,  2.32it/s]



 98%|█████████▊| 1109/1131 [08:04<00:07,  2.80it/s]



 98%|█████████▊| 1110/1131 [08:05<00:11,  1.88it/s]



 98%|█████████▊| 1112/1131 [08:05<00:07,  2.51it/s]



 98%|█████████▊| 1113/1131 [08:05<00:05,  3.03it/s]



 98%|█████████▊| 1114/1131 [08:06<00:07,  2.16it/s]



 99%|█████████▊| 1115/1131 [08:07<00:07,  2.22it/s]



 99%|█████████▊| 1116/1131 [08:07<00:07,  2.00it/s]



 99%|█████████▉| 1117/1131 [08:07<00:05,  2.55it/s]



 99%|█████████▉| 1118/1131 [08:08<00:06,  2.16it/s]



 99%|█████████▉| 1119/1131 [08:09<00:05,  2.13it/s]



 99%|█████████▉| 1120/1131 [08:09<00:04,  2.41it/s]



 99%|█████████▉| 1121/1131 [08:09<00:03,  2.54it/s]



 99%|█████████▉| 1122/1131 [08:10<00:03,  2.52it/s]



 99%|█████████▉| 1123/1131 [08:11<00:04,  1.65it/s]



 99%|█████████▉| 1125/1131 [08:11<00:02,  2.20it/s]



100%|█████████▉| 1126/1131 [08:12<00:02,  2.40it/s]



100%|█████████▉| 1127/1131 [08:12<00:01,  2.10it/s]



100%|█████████▉| 1128/1131 [08:12<00:01,  2.38it/s]



100%|█████████▉| 1129/1131 [08:13<00:00,  2.53it/s]



100%|█████████▉| 1130/1131 [08:13<00:00,  2.69it/s]



100%|██████████| 1131/1131 [08:14<00:00,  2.29it/s]
Families:  67%|██████▋   | 2/3 [08:23<04:54, 294.53s/it]
Multiplets | family 5:   0%|          | 0/370 [00:00<?, ?it/s]



  0%|          | 0/370 [00:00<?, ?it/s]



  0%|          | 1/370 [00:04<26:40,  4.34s/it]



  1%|          | 4/370 [00:04<05:13,  1.17it/s]



  2%|▏         | 6/370 [00:04<03:11,  1.90it/s]



  2%|▏         | 8/370 [00:04<02:08,  2.81it/s]



  3%|▎         | 10/370 [00:08<05:36,  1.07it/s]



  3%|▎         | 11/370 [00:08<04:36,  1.30it/s]



  3%|▎         | 12/370 [00:09<03:55,  1.52it/s]



  4%|▍         | 14/370 [00:09<02:43,  2.18it/s]



  4%|▍         | 15/370 [00:09<02:21,  2.51it/s]



  5%|▍         | 17/370 [00:13<05:36,  1.05it/s]



  5%|▌         | 19/370 [00:13<03:46,  1.55it/s]



  6%|▌         | 21/370 [00:14<03:04,  1.89it/s]



  6%|▌         | 22/370 [00:14<02:45,  2.11it/s]



  6%|▌         | 23/370 [00:14<02:23,  2.42it/s]



  6%|▋         | 24/370 [00:14<01:58,  2.92it/s]



  7%|▋         | 25/370 [00:17<05:56,  1.03s/it]

  7%|▋         | 26/370 [00:18<04:48,  1.19it/s]



  7%|▋         | 27/370 [00:18<03:50,  1.49it/s]



  8%|▊         | 28/370 [00:18<02:59,  1.90it/s]



  8%|▊         | 29/370 [00:18<02:33,  2.22it/s]



  8%|▊         | 30/370 [00:18<02:13,  2.55it/s]



  9%|▊         | 32/370 [00:19<01:44,  3.24it/s]



  9%|▉         | 33/370 [00:22<05:09,  1.09it/s]



  9%|▉         | 34/370 [00:22<04:06,  1.37it/s]



  9%|▉         | 35/370 [00:22<03:18,  1.69it/s]



 10%|▉         | 36/370 [00:22<02:40,  2.08it/s]



 10%|█         | 37/370 [00:23<02:45,  2.01it/s]



 10%|█         | 38/370 [00:23<02:17,  2.41it/s]



 11%|█         | 39/370 [00:23<01:52,  2.93it/s]



 11%|█         | 40/370 [00:24<02:03,  2.68it/s]



 11%|█         | 41/370 [00:26<05:13,  1.05it/s]



 11%|█▏        | 42/370 [00:26<04:12,  1.30it/s]



 12%|█▏        | 43/370 [00:26<03:13,  1.69it/s]



 12%|█▏        | 44/370 [00:27<02:29,  2.19it/s]



 12%|█▏        | 45/370 [00:27<03:02,  1.78it/s]



 13%|█▎        | 47/370 [00:28<01:46,  3.02it/s]



 13%|█▎        | 48/370 [00:28<02:23,  2.24it/s]



 13%|█▎        | 49/370 [00:30<04:37,  1.15it/s]



 14%|█▎        | 50/370 [00:31<04:08,  1.29it/s]



 14%|█▍        | 52/370 [00:31<02:27,  2.15it/s]



 14%|█▍        | 53/370 [00:32<02:55,  1.80it/s]



 15%|█▍        | 54/370 [00:32<02:37,  2.00it/s]



 15%|█▌        | 56/370 [00:33<02:27,  2.12it/s]



 15%|█▌        | 57/370 [00:35<04:04,  1.28it/s]



 16%|█▌        | 58/370 [00:35<03:31,  1.47it/s]



 16%|█▌        | 59/370 [00:35<02:48,  1.84it/s]



 16%|█▌        | 60/370 [00:36<02:25,  2.13it/s]



 16%|█▋        | 61/370 [00:36<02:38,  1.95it/s]



 17%|█▋        | 62/370 [00:37<02:25,  2.11it/s]



 17%|█▋        | 63/370 [00:37<01:52,  2.73it/s]



 17%|█▋        | 64/370 [00:38<02:34,  1.98it/s]



 18%|█▊        | 65/370 [00:40<04:56,  1.03it/s]



 18%|█▊        | 68/370 [00:40<02:45,  1.82it/s]



 19%|█▊        | 69/370 [00:41<02:56,  1.70it/s]



 19%|█▉        | 70/370 [00:41<02:38,  1.89it/s]



 19%|█▉        | 71/370 [00:42<02:06,  2.36it/s]



 19%|█▉        | 72/370 [00:42<02:34,  1.93it/s]



 20%|█▉        | 73/370 [00:44<04:18,  1.15it/s]



 20%|██        | 75/370 [00:44<02:43,  1.81it/s]



 21%|██        | 76/370 [00:45<02:30,  1.95it/s]



 21%|██        | 77/370 [00:46<02:55,  1.67it/s]



 21%|██        | 78/370 [00:46<02:45,  1.77it/s]



 21%|██▏       | 79/370 [00:46<02:24,  2.02it/s]



 22%|██▏       | 80/370 [00:47<02:16,  2.13it/s]



 22%|██▏       | 81/370 [00:49<04:16,  1.13it/s]



 23%|██▎       | 84/370 [00:49<02:18,  2.07it/s]



 23%|██▎       | 85/370 [00:50<02:54,  1.64it/s]



 23%|██▎       | 86/370 [00:51<02:43,  1.73it/s]



 24%|██▍       | 88/370 [00:51<02:07,  2.22it/s]



 24%|██▍       | 89/370 [00:53<03:26,  1.36it/s]



 24%|██▍       | 90/370 [00:53<02:47,  1.67it/s]



 25%|██▍       | 91/370 [00:53<02:18,  2.02it/s]



 25%|██▍       | 92/370 [00:54<01:59,  2.32it/s]



 25%|██▌       | 93/370 [00:55<02:49,  1.64it/s]



 25%|██▌       | 94/370 [00:55<02:44,  1.68it/s]



 26%|██▌       | 96/370 [00:56<02:02,  2.24it/s]



 26%|██▌       | 97/370 [00:58<03:30,  1.30it/s]



 26%|██▋       | 98/370 [00:58<02:43,  1.67it/s]



 27%|██▋       | 99/370 [00:58<02:14,  2.01it/s]



 27%|██▋       | 100/370 [00:58<01:48,  2.49it/s]



 27%|██▋       | 101/370 [01:00<03:03,  1.46it/s]



 28%|██▊       | 102/370 [01:00<02:27,  1.82it/s]



 28%|██▊       | 103/370 [01:00<02:38,  1.69it/s]



 28%|██▊       | 105/370 [01:02<02:51,  1.54it/s]



 29%|██▊       | 106/370 [01:02<02:34,  1.71it/s]



 29%|██▉       | 107/370 [01:03<02:10,  2.01it/s]



 29%|██▉       | 108/370 [01:03<02:23,  1.82it/s]



 29%|██▉       | 109/370 [01:04<02:54,  1.49it/s]



 30%|██▉       | 110/370 [01:04<02:23,  1.81it/s]



 30%|███       | 111/370 [01:05<02:24,  1.79it/s]



 30%|███       | 112/370 [01:06<02:24,  1.78it/s]



 31%|███       | 113/370 [01:06<02:28,  1.74it/s]



 31%|███       | 114/370 [01:07<02:33,  1.67it/s]



 31%|███▏      | 116/370 [01:08<02:09,  1.97it/s]



 32%|███▏      | 117/370 [01:09<02:39,  1.58it/s]



 32%|███▏      | 118/370 [01:09<02:10,  1.93it/s]



 32%|███▏      | 119/370 [01:09<02:14,  1.87it/s]



 32%|███▏      | 120/370 [01:10<02:16,  1.83it/s]



 33%|███▎      | 121/370 [01:11<02:12,  1.88it/s]



 33%|███▎      | 122/370 [01:11<02:21,  1.75it/s]



 34%|███▎      | 124/370 [01:12<02:17,  1.78it/s]



 34%|███▍      | 125/370 [01:13<02:30,  1.62it/s]



 34%|███▍      | 126/370 [01:13<02:04,  1.96it/s]



 34%|███▍      | 127/370 [01:14<02:31,  1.60it/s]



 35%|███▍      | 128/370 [01:14<02:01,  1.99it/s]



 35%|███▍      | 129/370 [01:15<01:54,  2.11it/s]



 35%|███▌      | 130/370 [01:16<02:27,  1.63it/s]



 35%|███▌      | 131/370 [01:16<02:17,  1.74it/s]



 36%|███▌      | 132/370 [01:17<02:31,  1.58it/s]



 36%|███▌      | 133/370 [01:18<03:08,  1.25it/s]



 36%|███▌      | 134/370 [01:18<02:33,  1.54it/s]



 36%|███▋      | 135/370 [01:19<01:58,  1.98it/s]



 37%|███▋      | 136/370 [01:19<01:34,  2.47it/s]



 37%|███▋      | 137/370 [01:20<02:07,  1.83it/s]



 37%|███▋      | 138/370 [01:20<02:04,  1.86it/s]



 38%|███▊      | 139/370 [01:21<02:10,  1.77it/s]



 38%|███▊      | 140/370 [01:22<02:16,  1.68it/s]



 38%|███▊      | 141/370 [01:23<02:48,  1.36it/s]



 38%|███▊      | 142/370 [01:23<02:34,  1.47it/s]



 39%|███▉      | 144/370 [01:23<01:31,  2.47it/s]



 39%|███▉      | 145/370 [01:24<01:42,  2.20it/s]



 39%|███▉      | 146/370 [01:25<01:59,  1.88it/s]



 40%|███▉      | 147/370 [01:25<01:54,  1.94it/s]



 40%|████      | 148/370 [01:26<02:09,  1.71it/s]



 40%|████      | 149/370 [01:27<02:37,  1.40it/s]



 41%|████      | 150/370 [01:28<02:30,  1.46it/s]



 41%|████▏     | 153/370 [01:28<01:41,  2.13it/s]



 42%|████▏     | 154/370 [01:29<01:49,  1.96it/s]



 42%|████▏     | 155/370 [01:29<01:41,  2.11it/s]



 42%|████▏     | 156/370 [01:31<02:34,  1.39it/s]



 42%|████▏     | 157/370 [01:32<02:41,  1.32it/s]



 43%|████▎     | 158/370 [01:32<02:13,  1.58it/s]



 43%|████▎     | 159/370 [01:32<01:43,  2.04it/s]



 43%|████▎     | 160/370 [01:33<01:42,  2.05it/s]



 44%|████▎     | 161/370 [01:33<01:26,  2.43it/s]



 44%|████▍     | 162/370 [01:33<01:32,  2.24it/s]



 44%|████▍     | 163/370 [01:34<01:47,  1.92it/s]



 44%|████▍     | 164/370 [01:36<02:47,  1.23it/s]



 45%|████▍     | 165/370 [01:36<02:49,  1.21it/s]



 45%|████▍     | 166/370 [01:37<02:05,  1.63it/s]



 45%|████▌     | 167/370 [01:37<01:51,  1.82it/s]



 45%|████▌     | 168/370 [01:37<01:39,  2.03it/s]



 46%|████▌     | 170/370 [01:38<01:21,  2.46it/s]

 46%|████▌     | 171/370 [01:39<01:31,  2.16it/s]



 46%|████▋     | 172/370 [01:40<02:28,  1.34it/s]



 47%|████▋     | 173/370 [01:41<02:27,  1.34it/s]



 47%|████▋     | 174/370 [01:41<01:51,  1.75it/s]



 47%|████▋     | 175/370 [01:41<01:44,  1.86it/s]



 48%|████▊     | 176/370 [01:42<01:26,  2.24it/s]



 48%|████▊     | 177/370 [01:42<01:15,  2.57it/s]



 48%|████▊     | 178/370 [01:42<01:15,  2.56it/s]



 48%|████▊     | 179/370 [01:43<01:19,  2.40it/s]



 49%|████▊     | 180/370 [01:45<02:33,  1.24it/s]



 49%|████▉     | 181/370 [01:45<02:25,  1.30it/s]



 49%|████▉     | 182/370 [01:46<02:15,  1.38it/s]



 49%|████▉     | 183/370 [01:46<01:44,  1.79it/s]



 50%|████▉     | 184/370 [01:46<01:30,  2.06it/s]



 50%|█████     | 186/370 [01:47<01:12,  2.55it/s]



 51%|█████     | 187/370 [01:48<01:25,  2.13it/s]



 51%|█████     | 188/370 [01:49<02:13,  1.36it/s]



 51%|█████     | 189/370 [01:50<01:59,  1.52it/s]



 51%|█████▏    | 190/370 [01:51<02:31,  1.19it/s]



 52%|█████▏    | 191/370 [01:51<01:54,  1.57it/s]



 52%|█████▏    | 192/370 [01:51<01:28,  2.02it/s]



 52%|█████▏    | 194/370 [01:52<01:05,  2.70it/s]



 53%|█████▎    | 195/370 [01:52<01:12,  2.43it/s]



 53%|█████▎    | 196/370 [01:54<02:03,  1.41it/s]



 53%|█████▎    | 197/370 [01:54<01:47,  1.60it/s]



 54%|█████▎    | 198/370 [01:55<02:23,  1.20it/s]



 54%|█████▍    | 199/370 [01:56<01:47,  1.59it/s]



 54%|█████▍    | 200/370 [01:56<01:23,  2.04it/s]



 54%|█████▍    | 201/370 [01:56<01:07,  2.51it/s]



 55%|█████▍    | 202/370 [01:56<01:00,  2.78it/s]



 55%|█████▍    | 203/370 [01:57<01:04,  2.60it/s]



 55%|█████▌    | 204/370 [01:58<01:53,  1.46it/s]



 55%|█████▌    | 205/370 [01:58<01:41,  1.62it/s]



 56%|█████▌    | 206/370 [02:00<02:22,  1.15it/s]



 56%|█████▌    | 207/370 [02:00<01:50,  1.47it/s]



 56%|█████▌    | 208/370 [02:00<01:23,  1.95it/s]



 57%|█████▋    | 210/370 [02:01<00:55,  2.90it/s]



 57%|█████▋    | 211/370 [02:01<00:57,  2.76it/s]



 57%|█████▋    | 212/370 [02:02<01:38,  1.60it/s]



 58%|█████▊    | 213/370 [02:03<01:45,  1.48it/s]



 58%|█████▊    | 214/370 [02:04<02:04,  1.26it/s]



 58%|█████▊    | 215/370 [02:05<01:44,  1.49it/s]



 58%|█████▊    | 216/370 [02:05<01:21,  1.89it/s]



 59%|█████▊    | 217/370 [02:05<01:14,  2.06it/s]



 59%|█████▉    | 219/370 [02:06<00:57,  2.63it/s]



 59%|█████▉    | 220/370 [02:07<01:29,  1.68it/s]



 60%|█████▉    | 221/370 [02:08<01:38,  1.51it/s]



 60%|██████    | 222/370 [02:09<02:06,  1.17it/s]



 61%|██████    | 224/370 [02:09<01:17,  1.88it/s]



 61%|██████    | 225/370 [02:10<01:11,  2.04it/s]



 61%|██████    | 226/370 [02:10<00:59,  2.42it/s]



 61%|██████▏   | 227/370 [02:10<00:55,  2.59it/s]



 62%|██████▏   | 228/370 [02:12<01:30,  1.57it/s]



 62%|██████▏   | 229/370 [02:12<01:39,  1.41it/s]



 62%|██████▏   | 230/370 [02:14<01:57,  1.19it/s]



 62%|██████▏   | 231/370 [02:14<01:33,  1.49it/s]



 63%|██████▎   | 232/370 [02:14<01:09,  1.97it/s]



 63%|██████▎   | 233/370 [02:15<01:23,  1.64it/s]



 63%|██████▎   | 234/370 [02:15<01:04,  2.10it/s]



 64%|██████▍   | 236/370 [02:16<01:06,  2.02it/s]



 64%|██████▍   | 237/370 [02:17<01:26,  1.55it/s]



 64%|██████▍   | 238/370 [02:19<01:50,  1.19it/s]



 65%|██████▍   | 240/370 [02:19<01:22,  1.58it/s]



 65%|██████▌   | 241/370 [02:19<01:07,  1.90it/s]



 66%|██████▌   | 243/370 [02:20<00:57,  2.20it/s]



 66%|██████▌   | 244/370 [02:20<00:52,  2.40it/s]



 66%|██████▌   | 245/370 [02:22<01:28,  1.42it/s]



 66%|██████▋   | 246/370 [02:23<01:31,  1.35it/s]



 67%|██████▋   | 247/370 [02:23<01:19,  1.55it/s]



 67%|██████▋   | 248/370 [02:24<01:19,  1.53it/s]



 67%|██████▋   | 249/370 [02:24<01:01,  1.96it/s]



 68%|██████▊   | 250/370 [02:24<00:50,  2.36it/s]



 68%|██████▊   | 251/370 [02:25<01:00,  1.97it/s]



 68%|██████▊   | 252/370 [02:25<00:49,  2.40it/s]



 68%|██████▊   | 253/370 [02:27<01:31,  1.29it/s]



 69%|██████▊   | 254/370 [02:27<01:20,  1.44it/s]



 69%|██████▉   | 255/370 [02:28<01:09,  1.66it/s]



 69%|██████▉   | 256/370 [02:29<01:15,  1.50it/s]



 70%|██████▉   | 258/370 [02:29<00:45,  2.47it/s]



 70%|███████   | 259/370 [02:30<00:56,  1.97it/s]



 71%|███████   | 261/370 [02:31<01:10,  1.54it/s]



 71%|███████   | 262/370 [02:32<01:05,  1.65it/s]



 71%|███████   | 263/370 [02:32<01:00,  1.78it/s]



 71%|███████▏  | 264/370 [02:33<01:03,  1.67it/s]



 72%|███████▏  | 265/370 [02:33<00:52,  2.02it/s]



 72%|███████▏  | 266/370 [02:33<00:48,  2.16it/s]



 72%|███████▏  | 267/370 [02:34<00:51,  1.99it/s]



 72%|███████▏  | 268/370 [02:35<00:52,  1.96it/s]



 73%|███████▎  | 269/370 [02:36<01:22,  1.22it/s]



 73%|███████▎  | 270/370 [02:36<01:07,  1.47it/s]



 73%|███████▎  | 271/370 [02:37<00:59,  1.67it/s]



 74%|███████▎  | 272/370 [02:37<00:49,  1.99it/s]



 74%|███████▍  | 273/370 [02:38<00:48,  2.02it/s]



 74%|███████▍  | 274/370 [02:38<00:53,  1.78it/s]



 74%|███████▍  | 275/370 [02:39<00:53,  1.77it/s]



 75%|███████▍  | 276/370 [02:39<00:46,  2.02it/s]



 75%|███████▍  | 277/370 [02:41<01:11,  1.31it/s]



 75%|███████▌  | 278/370 [02:41<01:01,  1.50it/s]



 75%|███████▌  | 279/370 [02:42<01:01,  1.48it/s]



 76%|███████▌  | 280/370 [02:42<00:47,  1.89it/s]



 76%|███████▌  | 281/370 [02:43<00:48,  1.84it/s]



 76%|███████▌  | 282/370 [02:43<00:46,  1.88it/s]



 76%|███████▋  | 283/370 [02:44<00:46,  1.85it/s]



 77%|███████▋  | 284/370 [02:44<00:41,  2.09it/s]



 77%|███████▋  | 285/370 [02:45<00:58,  1.46it/s]



 77%|███████▋  | 286/370 [02:46<00:52,  1.60it/s]



 78%|███████▊  | 287/370 [02:46<00:51,  1.60it/s]



 78%|███████▊  | 288/370 [02:46<00:39,  2.08it/s]



 78%|███████▊  | 289/370 [02:47<00:42,  1.90it/s]



 78%|███████▊  | 290/370 [02:48<00:45,  1.75it/s]



 79%|███████▊  | 291/370 [02:48<00:37,  2.12it/s]



 79%|███████▉  | 292/370 [02:48<00:37,  2.06it/s]



 79%|███████▉  | 293/370 [02:50<01:02,  1.22it/s]



 80%|███████▉  | 295/370 [02:51<00:45,  1.64it/s]



 80%|████████  | 296/370 [02:51<00:42,  1.73it/s]



 80%|████████  | 297/370 [02:51<00:33,  2.19it/s]



 81%|████████  | 298/370 [02:52<00:41,  1.73it/s]



 81%|████████  | 299/370 [02:53<00:41,  1.72it/s]



 81%|████████  | 300/370 [02:53<00:35,  1.96it/s]



 81%|████████▏ | 301/370 [02:54<00:49,  1.39it/s]



 82%|████████▏ | 302/370 [02:55<00:41,  1.63it/s]



 82%|████████▏ | 303/370 [02:55<00:43,  1.55it/s]



 82%|████████▏ | 304/370 [02:56<00:33,  1.98it/s]



 82%|████████▏ | 305/370 [02:56<00:25,  2.54it/s]



 83%|████████▎ | 306/370 [02:57<00:42,  1.49it/s]



 83%|████████▎ | 307/370 [02:58<00:38,  1.65it/s]

 83%|████████▎ | 308/370 [02:58<00:33,  1.84it/s]



 84%|████████▎ | 309/370 [02:59<00:39,  1.53it/s]



 84%|████████▍ | 310/370 [02:59<00:33,  1.81it/s]



 84%|████████▍ | 311/370 [03:00<00:34,  1.72it/s]



 84%|████████▍ | 312/370 [03:00<00:30,  1.92it/s]



 85%|████████▍ | 313/370 [03:00<00:22,  2.53it/s]



 85%|████████▍ | 314/370 [03:02<00:36,  1.55it/s]



 85%|████████▌ | 315/370 [03:02<00:34,  1.60it/s]



 85%|████████▌ | 316/370 [03:02<00:27,  1.93it/s]



 86%|████████▌ | 317/370 [03:03<00:32,  1.64it/s]



 86%|████████▌ | 318/370 [03:04<00:29,  1.75it/s]



 86%|████████▌ | 319/370 [03:04<00:27,  1.85it/s]



 86%|████████▋ | 320/370 [03:05<00:27,  1.80it/s]



 87%|████████▋ | 322/370 [03:06<00:33,  1.43it/s]



 88%|████████▊ | 324/370 [03:07<00:22,  2.01it/s]



 88%|████████▊ | 325/370 [03:08<00:25,  1.75it/s]



 88%|████████▊ | 326/370 [03:09<00:30,  1.45it/s]



 88%|████████▊ | 327/370 [03:09<00:26,  1.60it/s]



 89%|████████▉ | 329/370 [03:10<00:18,  2.23it/s]



 89%|████████▉ | 330/370 [03:11<00:27,  1.45it/s]



 89%|████████▉ | 331/370 [03:11<00:21,  1.78it/s]



 90%|████████▉ | 332/370 [03:12<00:19,  1.94it/s]



 90%|█████████ | 333/370 [03:13<00:22,  1.62it/s]



 90%|█████████ | 334/370 [03:13<00:24,  1.46it/s]



 91%|█████████ | 335/370 [03:14<00:19,  1.81it/s]



 91%|█████████ | 337/370 [03:14<00:13,  2.36it/s]



 91%|█████████▏| 338/370 [03:16<00:22,  1.39it/s]



 92%|█████████▏| 340/370 [03:17<00:17,  1.69it/s]



 92%|█████████▏| 341/370 [03:17<00:15,  1.85it/s]



 92%|█████████▏| 342/370 [03:18<00:17,  1.56it/s]



 93%|█████████▎| 343/370 [03:18<00:15,  1.80it/s]



 93%|█████████▎| 344/370 [03:18<00:11,  2.25it/s]



 93%|█████████▎| 345/370 [03:19<00:10,  2.49it/s]



 94%|█████████▎| 346/370 [03:20<00:19,  1.26it/s]



 94%|█████████▍| 347/370 [03:21<00:13,  1.67it/s]



 94%|█████████▍| 348/370 [03:21<00:14,  1.48it/s]



 95%|█████████▍| 350/370 [03:22<00:11,  1.76it/s]



 95%|█████████▍| 351/370 [03:23<00:09,  1.90it/s]



 95%|█████████▌| 353/370 [03:23<00:07,  2.41it/s]



 96%|█████████▌| 354/370 [03:25<00:11,  1.34it/s]



 96%|█████████▌| 355/370 [03:25<00:09,  1.56it/s]



 96%|█████████▌| 356/370 [03:26<00:08,  1.61it/s]



 97%|█████████▋| 358/370 [03:27<00:06,  1.76it/s]



 97%|█████████▋| 360/370 [03:27<00:04,  2.22it/s]



 98%|█████████▊| 361/370 [03:28<00:04,  2.00it/s]



 98%|█████████▊| 362/370 [03:30<00:06,  1.30it/s]



 98%|█████████▊| 364/370 [03:31<00:03,  1.65it/s]



 99%|█████████▉| 366/370 [03:31<00:02,  1.83it/s]



 99%|█████████▉| 367/370 [03:32<00:01,  2.13it/s]



 99%|█████████▉| 368/370 [03:32<00:00,  2.28it/s]



100%|█████████▉| 369/370 [03:32<00:00,  2.29it/s]



100%|██████████| 370/370 [03:33<00:00,  1.73it/s]
Families: 100%|██████████| 3/3 [11:57<00:00, 239.02s/it]

Runtime: 717.077640 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]



Multiplets | family 3:   0%|          | 0/129 [00:00<?, ?it/s]




  0%|          | 0/129 [00:00<?, ?it/s]




  1%|          | 1/129 [00:01<03:34,  1.68s/it]




  4%|▍         | 5/129 [00:01<00:34,  3.57it/s]




  6%|▌         | 8/129 [00:01<00:20,  5.98it/s]




  8%|▊         | 10/129 [00:03<00:39,  3.00it/s]




 10%|█         | 13/129 [00:03<00:27,  4.19it/s]




 12%|█▏        | 15/129 [00:03<00:22,  5.16it/s]




 13%|█▎        | 17/129 [00:04<00:33,  3.32it/s]




 14%|█▍        | 18/129 [00:05<00:30,  3.68it/s]




 16%|█▌        | 20/129 [00:05<00:24,  4.52it/s]




 17%|█▋        | 22/129 [00:05<00:21,  4.90it/s]




 19%|█▊        | 24/129 [00:05<00:18,  5.64it/s]




 19%|█▉        | 25/129 [00:06<00:28,  3.60it/s]




 20%|██        | 26/129 [00:06<00:25,  4.03it/s]




 21%|██        | 27/129 [00:06<00:23,  4.34it/s]




 22%|██▏       | 28/129 [00:07<00:20,  5.02it/s]




 22%|██▏       | 29/129 [00:07<00:22,  4.48it/s]




 23%|██▎       | 30/129 [00:07<00:21,  4.59it/s]




 25%|██▍       | 32/129 [00:07<00:21,  4.60it/s]




 26%|██▌       | 33/129 [00:08<00:24,  3.99it/s]




 26%|██▋       | 34/129 [00:08<00:23,  4.02it/s]




 27%|██▋       | 35/129 [00:08<00:20,  4.48it/s]




 28%|██▊       | 36/129 [00:08<00:20,  4.64it/s]




 29%|██▊       | 37/129 [00:09<00:21,  4.34it/s]




 30%|███       | 39/129 [00:09<00:16,  5.40it/s]




 31%|███       | 40/129 [00:09<00:22,  3.98it/s]




 32%|███▏      | 41/129 [00:10<00:21,  4.07it/s]




 33%|███▎      | 42/129 [00:10<00:22,  3.79it/s]




 34%|███▍      | 44/129 [00:10<00:15,  5.49it/s]




 35%|███▍      | 45/129 [00:10<00:17,  4.75it/s]




 36%|███▋      | 47/129 [00:11<00:15,  5.40it/s]




 37%|███▋      | 48/129 [00:11<00:21,  3.70it/s]




 39%|███▉      | 50/129 [00:12<00:18,  4.17it/s]




 40%|████      | 52/129 [00:12<00:13,  5.50it/s]




 41%|████      | 53/129 [00:12<00:19,  3.98it/s]




 43%|████▎     | 55/129 [00:13<00:15,  4.78it/s]




 43%|████▎     | 56/129 [00:13<00:18,  3.88it/s]




 45%|████▍     | 58/129 [00:13<00:16,  4.35it/s]




 47%|████▋     | 60/129 [00:13<00:11,  5.97it/s]




 47%|████▋     | 61/129 [00:14<00:16,  4.09it/s]




 49%|████▉     | 63/129 [00:14<00:13,  5.00it/s]




 50%|████▉     | 64/129 [00:15<00:16,  3.99it/s]




 51%|█████     | 66/129 [00:15<00:14,  4.45it/s]




 53%|█████▎    | 68/129 [00:15<00:10,  5.99it/s]




 53%|█████▎    | 69/129 [00:16<00:14,  4.08it/s]




 55%|█████▌    | 71/129 [00:16<00:11,  5.11it/s]




 56%|█████▌    | 72/129 [00:16<00:14,  3.95it/s]




 57%|█████▋    | 74/129 [00:17<00:11,  4.64it/s]




 58%|█████▊    | 75/129 [00:17<00:10,  4.99it/s]




 60%|█████▉    | 77/129 [00:18<00:13,  3.92it/s]




 61%|██████    | 79/129 [00:18<00:10,  4.97it/s]




 62%|██████▏   | 80/129 [00:18<00:11,  4.27it/s]




 63%|██████▎   | 81/129 [00:18<00:11,  4.22it/s]




 64%|██████▍   | 83/129 [00:19<00:08,  5.12it/s]




 66%|██████▌   | 85/129 [00:19<00:10,  4.26it/s]




 67%|██████▋   | 86/129 [00:19<00:09,  4.32it/s]




 68%|██████▊   | 88/129 [00:20<00:09,  4.23it/s]




 69%|██████▉   | 89/129 [00:20<00:08,  4.74it/s]




 71%|███████   | 91/129 [00:20<00:07,  5.07it/s]




 72%|███████▏  | 93/129 [00:21<00:08,  4.19it/s]




 73%|███████▎  | 94/129 [00:21<00:08,  4.36it/s]




 74%|███████▎  | 95/129 [00:21<00:07,  4.81it/s]




 74%|███████▍  | 96/129 [00:22<00:07,  4.21it/s]




 75%|███████▌  | 97/129 [00:22<00:06,  4.68it/s]




 76%|███████▌  | 98/129 [00:22<00:07,  4.21it/s]




 78%|███████▊  | 100/129 [00:22<00:04,  6.39it/s]




 78%|███████▊  | 101/129 [00:23<00:06,  4.27it/s]




 79%|███████▉  | 102/129 [00:23<00:07,  3.71it/s]




 80%|███████▉  | 103/129 [00:23<00:06,  4.02it/s]




 81%|████████  | 104/129 [00:24<00:06,  4.01it/s]




 81%|████████▏ | 105/129 [00:24<00:05,  4.10it/s]




 82%|████████▏ | 106/129 [00:24<00:05,  3.85it/s]




 83%|████████▎ | 107/129 [00:24<00:04,  4.44it/s]




 84%|████████▎ | 108/129 [00:24<00:04,  5.21it/s]




 84%|████████▍ | 109/129 [00:25<00:03,  5.23it/s]




 85%|████████▌ | 110/129 [00:25<00:04,  4.23it/s]




 86%|████████▌ | 111/129 [00:25<00:05,  3.48it/s]




 88%|████████▊ | 113/129 [00:26<00:03,  4.54it/s]




 88%|████████▊ | 114/129 [00:26<00:03,  4.47it/s]




 89%|████████▉ | 115/129 [00:26<00:02,  4.91it/s]




 90%|████████▉ | 116/129 [00:26<00:02,  5.05it/s]




 91%|█████████ | 117/129 [00:26<00:02,  4.26it/s]




 91%|█████████▏| 118/129 [00:27<00:02,  3.76it/s]




 92%|█████████▏| 119/129 [00:27<00:02,  4.05it/s]




 93%|█████████▎| 120/129 [00:27<00:02,  4.38it/s]




 94%|█████████▍| 121/129 [00:27<00:01,  5.15it/s]




 95%|█████████▍| 122/129 [00:28<00:01,  4.54it/s]




 95%|█████████▌| 123/129 [00:28<00:01,  4.11it/s]




 96%|█████████▌| 124/129 [00:28<00:01,  4.76it/s]




 97%|█████████▋| 125/129 [00:28<00:01,  3.89it/s]




 98%|█████████▊| 126/129 [00:29<00:00,  3.95it/s]




100%|██████████| 129/129 [00:29<00:00,  4.36it/s]
Families:  33%|███▎      | 1/3 [00:29<00:59, 29.63s/it]




Multiplets | family 4:   0%|          | 0/1233 [00:00<?, ?it/s]





  0%|          | 0/1233 [00:00<?, ?it/s]





  0%|          | 1/1233 [00:02<48:51,  2.38s/it]





  0%|          | 4/1233 [00:02<09:48,  2.09it/s]





  0%|          | 6/1233 [00:02<06:06,  3.35it/s]





  1%|          | 9/1233 [00:04<09:59,  2.04it/s]





  1%|          | 12/1233 [00:04<06:33,  3.10it/s]





  1%|          | 15/1233 [00:05<04:22,  4.63it/s]





  1%|▏         | 17/1233 [00:07<08:35,  2.36it/s]





  2%|▏         | 19/1233 [00:07<07:03,  2.86it/s]





  2%|▏         | 21/1233 [00:07<06:21,  3.17it/s]





  2%|▏         | 23/1233 [00:07<04:50,  4.17it/s]





  2%|▏         | 25/1233 [00:09<08:05,  2.49it/s]





  2%|▏         | 26/1233 [00:09<07:27,  2.69it/s]





  2%|▏         | 27/1233 [00:10<07:32,  2.66it/s]





  2%|▏         | 28/1233 [00:10<07:58,  2.52it/s]





  2%|▏         | 29/1233 [00:10<06:39,  3.02it/s]





  2%|▏         | 30/1233 [00:11<07:53,  2.54it/s]





  3%|▎         | 31/1233 [00:11<06:39,  3.01it/s]





  3%|▎         | 33/1233 [00:12<06:07,  3.27it/s]





  3%|▎         | 34/1233 [00:12<06:40,  3.00it/s]





  3%|▎         | 35/1233 [00:13<08:06,  2.46it/s]





  3%|▎         | 36/1233 [00:13<06:29,  3.07it/s]

  3%|▎         | 37/1233 [00:13<05:20,  3.74it/s]





  3%|▎         | 38/1233 [00:13<07:09,  2.78it/s]





  3%|▎         | 41/1233 [00:14<05:27,  3.64it/s]





  3%|▎         | 42/1233 [00:15<07:02,  2.82it/s]





  3%|▎         | 43/1233 [00:15<07:26,  2.66it/s]





  4%|▎         | 44/1233 [00:15<06:09,  3.22it/s]





  4%|▎         | 46/1233 [00:16<06:05,  3.25it/s]





  4%|▍         | 47/1233 [00:16<05:17,  3.74it/s]





  4%|▍         | 48/1233 [00:16<04:34,  4.32it/s]





  4%|▍         | 49/1233 [00:16<05:02,  3.92it/s]





  4%|▍         | 50/1233 [00:17<08:25,  2.34it/s]





  4%|▍         | 51/1233 [00:18<07:21,  2.68it/s]





  4%|▍         | 52/1233 [00:18<07:17,  2.70it/s]





  4%|▍         | 54/1233 [00:18<05:16,  3.73it/s]





  4%|▍         | 55/1233 [00:18<04:49,  4.07it/s]





  5%|▍         | 56/1233 [00:19<04:49,  4.07it/s]





  5%|▍         | 57/1233 [00:19<04:55,  3.98it/s]





  5%|▍         | 58/1233 [00:20<07:49,  2.50it/s]





  5%|▍         | 59/1233 [00:20<07:30,  2.60it/s]





  5%|▍         | 60/1233 [00:20<06:53,  2.84it/s]





  5%|▍         | 61/1233 [00:20<06:01,  3.24it/s]





  5%|▌         | 62/1233 [00:21<05:38,  3.46it/s]





  5%|▌         | 64/1233 [00:21<03:52,  5.03it/s]





  5%|▌         | 65/1233 [00:21<05:14,  3.72it/s]





  5%|▌         | 66/1233 [00:22<07:11,  2.71it/s]





  5%|▌         | 67/1233 [00:23<08:54,  2.18it/s]





  6%|▌         | 69/1233 [00:23<05:37,  3.45it/s]





  6%|▌         | 70/1233 [00:23<05:32,  3.50it/s]





  6%|▌         | 72/1233 [00:23<04:40,  4.14it/s]





  6%|▌         | 73/1233 [00:24<05:21,  3.61it/s]





  6%|▌         | 74/1233 [00:25<07:51,  2.46it/s]





  6%|▌         | 75/1233 [00:25<08:06,  2.38it/s]





  6%|▌         | 76/1233 [00:26<07:52,  2.45it/s]





  6%|▋         | 79/1233 [00:26<04:29,  4.28it/s]





  6%|▋         | 80/1233 [00:26<04:22,  4.39it/s]





  7%|▋         | 81/1233 [00:26<04:26,  4.33it/s]





  7%|▋         | 82/1233 [00:27<07:18,  2.62it/s]





  7%|▋         | 83/1233 [00:28<07:58,  2.40it/s]





  7%|▋         | 84/1233 [00:28<07:43,  2.48it/s]





  7%|▋         | 85/1233 [00:28<06:29,  2.95it/s]





  7%|▋         | 86/1233 [00:28<05:25,  3.53it/s]





  7%|▋         | 87/1233 [00:28<05:02,  3.79it/s]





  7%|▋         | 89/1233 [00:29<03:21,  5.67it/s]





  7%|▋         | 90/1233 [00:30<06:48,  2.80it/s]





  7%|▋         | 91/1233 [00:30<08:49,  2.16it/s]





  7%|▋         | 92/1233 [00:31<07:54,  2.41it/s]





  8%|▊         | 94/1233 [00:31<05:15,  3.61it/s]





  8%|▊         | 96/1233 [00:31<03:51,  4.92it/s]





  8%|▊         | 98/1233 [00:32<05:54,  3.20it/s]





  8%|▊         | 99/1233 [00:33<07:43,  2.45it/s]





  8%|▊         | 100/1233 [00:33<06:55,  2.72it/s]





  8%|▊         | 102/1233 [00:33<04:36,  4.09it/s]





  8%|▊         | 103/1233 [00:33<04:14,  4.43it/s]





  8%|▊         | 104/1233 [00:33<04:13,  4.46it/s]





  9%|▊         | 106/1233 [00:34<06:00,  3.13it/s]





  9%|▊         | 107/1233 [00:35<08:00,  2.34it/s]





  9%|▉         | 108/1233 [00:35<07:01,  2.67it/s]





  9%|▉         | 110/1233 [00:36<04:36,  4.06it/s]





  9%|▉         | 111/1233 [00:36<04:40,  4.01it/s]





  9%|▉         | 113/1233 [00:36<03:22,  5.53it/s]





  9%|▉         | 114/1233 [00:37<07:15,  2.57it/s]





  9%|▉         | 115/1233 [00:38<07:58,  2.33it/s]





  9%|▉         | 116/1233 [00:38<07:26,  2.50it/s]





 10%|▉         | 118/1233 [00:38<05:06,  3.64it/s]





 10%|▉         | 119/1233 [00:38<05:02,  3.68it/s]





 10%|▉         | 121/1233 [00:39<04:02,  4.58it/s]





 10%|▉         | 122/1233 [00:39<05:58,  3.09it/s]





 10%|▉         | 123/1233 [00:40<08:32,  2.16it/s]





 10%|█         | 125/1233 [00:40<05:49,  3.17it/s]





 10%|█         | 127/1233 [00:41<05:08,  3.58it/s]





 10%|█         | 128/1233 [00:41<04:48,  3.83it/s]





 10%|█         | 129/1233 [00:41<04:56,  3.72it/s]





 11%|█         | 130/1233 [00:42<06:30,  2.82it/s]





 11%|█         | 131/1233 [00:43<08:25,  2.18it/s]





 11%|█         | 133/1233 [00:43<05:15,  3.49it/s]





 11%|█         | 134/1233 [00:43<05:19,  3.44it/s]





 11%|█         | 135/1233 [00:43<04:29,  4.07it/s]





 11%|█         | 136/1233 [00:44<05:58,  3.06it/s]





 11%|█         | 138/1233 [00:44<05:42,  3.20it/s]





 11%|█▏        | 139/1233 [00:45<07:10,  2.54it/s]





 11%|█▏        | 140/1233 [00:45<05:50,  3.12it/s]





 11%|█▏        | 141/1233 [00:46<06:25,  2.83it/s]





 12%|█▏        | 142/1233 [00:46<05:48,  3.13it/s]





 12%|█▏        | 143/1233 [00:46<05:00,  3.63it/s]





 12%|█▏        | 144/1233 [00:46<05:19,  3.41it/s]





 12%|█▏        | 145/1233 [00:47<04:29,  4.03it/s]





 12%|█▏        | 146/1233 [00:47<07:16,  2.49it/s]





 12%|█▏        | 147/1233 [00:48<06:38,  2.73it/s]





 12%|█▏        | 148/1233 [00:48<05:28,  3.30it/s]





 12%|█▏        | 149/1233 [00:48<06:13,  2.90it/s]





 12%|█▏        | 150/1233 [00:48<05:30,  3.28it/s]





 12%|█▏        | 151/1233 [00:49<04:43,  3.81it/s]





 12%|█▏        | 152/1233 [00:49<05:42,  3.15it/s]





 12%|█▏        | 154/1233 [00:50<05:48,  3.09it/s]





 13%|█▎        | 155/1233 [00:50<05:36,  3.20it/s]





 13%|█▎        | 156/1233 [00:50<05:25,  3.31it/s]





 13%|█▎        | 157/1233 [00:51<06:12,  2.89it/s]





 13%|█▎        | 158/1233 [00:51<04:58,  3.60it/s]





 13%|█▎        | 159/1233 [00:51<04:16,  4.18it/s]





 13%|█▎        | 160/1233 [00:51<05:19,  3.36it/s]





 13%|█▎        | 161/1233 [00:52<04:31,  3.95it/s]





 13%|█▎        | 162/1233 [00:52<05:54,  3.02it/s]





 13%|█▎        | 163/1233 [00:52<05:29,  3.25it/s]





 13%|█▎        | 164/1233 [00:53<06:22,  2.80it/s]





 13%|█▎        | 165/1233 [00:53<06:01,  2.96it/s]





 13%|█▎        | 166/1233 [00:53<05:52,  3.03it/s]





 14%|█▎        | 167/1233 [00:54<04:59,  3.56it/s]





 14%|█▎        | 168/1233 [00:54<04:18,  4.11it/s]





 14%|█▎        | 169/1233 [00:54<06:34,  2.70it/s]





 14%|█▍        | 170/1233 [00:54<05:08,  3.45it/s]





 14%|█▍        | 171/1233 [00:55<04:40,  3.79it/s]

 14%|█▍        | 172/1233 [00:56<08:33,  2.07it/s]





 14%|█▍        | 175/1233 [00:56<04:13,  4.17it/s]





 14%|█▍        | 176/1233 [00:56<05:32,  3.18it/s]





 14%|█▍        | 177/1233 [00:57<05:21,  3.28it/s]





 14%|█▍        | 178/1233 [00:57<06:21,  2.76it/s]





 15%|█▍        | 180/1233 [00:58<06:40,  2.63it/s]





 15%|█▍        | 182/1233 [00:58<05:27,  3.21it/s]





 15%|█▍        | 184/1233 [00:59<05:33,  3.15it/s]





 15%|█▌        | 186/1233 [00:59<04:56,  3.53it/s]





 15%|█▌        | 187/1233 [01:00<04:41,  3.71it/s]





 15%|█▌        | 188/1233 [01:01<06:48,  2.56it/s]





 15%|█▌        | 189/1233 [01:01<06:15,  2.78it/s]





 15%|█▌        | 191/1233 [01:01<04:13,  4.11it/s]





 16%|█▌        | 192/1233 [01:02<05:33,  3.12it/s]





 16%|█▌        | 193/1233 [01:02<05:07,  3.38it/s]





 16%|█▌        | 194/1233 [01:02<05:09,  3.35it/s]





 16%|█▌        | 195/1233 [01:02<04:53,  3.54it/s]





 16%|█▌        | 196/1233 [01:03<06:43,  2.57it/s]





 16%|█▌        | 197/1233 [01:03<05:48,  2.97it/s]





 16%|█▌        | 199/1233 [01:03<04:01,  4.28it/s]





 16%|█▌        | 200/1233 [01:04<04:55,  3.50it/s]





 16%|█▋        | 201/1233 [01:04<04:53,  3.52it/s]





 16%|█▋        | 202/1233 [01:04<04:44,  3.62it/s]





 16%|█▋        | 203/1233 [01:05<05:03,  3.39it/s]





 17%|█▋        | 204/1233 [01:05<06:43,  2.55it/s]





 17%|█▋        | 205/1233 [01:06<05:52,  2.91it/s]





 17%|█▋        | 207/1233 [01:06<04:06,  4.16it/s]





 17%|█▋        | 208/1233 [01:06<04:32,  3.76it/s]





 17%|█▋        | 209/1233 [01:07<05:51,  2.91it/s]





 17%|█▋        | 210/1233 [01:07<04:50,  3.53it/s]





 17%|█▋        | 211/1233 [01:07<05:07,  3.33it/s]





 17%|█▋        | 212/1233 [01:08<06:18,  2.70it/s]





 17%|█▋        | 213/1233 [01:08<06:01,  2.82it/s]





 17%|█▋        | 215/1233 [01:08<03:59,  4.25it/s]





 18%|█▊        | 216/1233 [01:09<05:03,  3.35it/s]





 18%|█▊        | 217/1233 [01:09<06:08,  2.76it/s]





 18%|█▊        | 219/1233 [01:10<04:56,  3.42it/s]





 18%|█▊        | 220/1233 [01:10<06:00,  2.81it/s]





 18%|█▊        | 221/1233 [01:10<05:36,  3.00it/s]





 18%|█▊        | 222/1233 [01:11<06:11,  2.72it/s]





 18%|█▊        | 223/1233 [01:11<05:03,  3.33it/s]





 18%|█▊        | 224/1233 [01:11<04:07,  4.08it/s]





 18%|█▊        | 225/1233 [01:12<05:25,  3.10it/s]





 18%|█▊        | 226/1233 [01:12<06:20,  2.65it/s]





 18%|█▊        | 227/1233 [01:12<05:13,  3.21it/s]





 18%|█▊        | 228/1233 [01:13<05:57,  2.81it/s]





 19%|█▊        | 229/1233 [01:13<05:48,  2.88it/s]





 19%|█▊        | 230/1233 [01:13<05:26,  3.07it/s]





 19%|█▊        | 231/1233 [01:14<05:12,  3.21it/s]





 19%|█▉        | 232/1233 [01:14<04:58,  3.36it/s]





 19%|█▉        | 233/1233 [01:14<04:23,  3.79it/s]





 19%|█▉        | 234/1233 [01:15<06:43,  2.47it/s]





 19%|█▉        | 235/1233 [01:15<05:58,  2.78it/s]





 19%|█▉        | 237/1233 [01:16<05:46,  2.87it/s]





 19%|█▉        | 239/1233 [01:16<04:16,  3.87it/s]





 19%|█▉        | 240/1233 [01:16<04:59,  3.32it/s]





 20%|█▉        | 241/1233 [01:17<04:53,  3.39it/s]





 20%|█▉        | 242/1233 [01:17<05:57,  2.77it/s]





 20%|█▉        | 243/1233 [01:18<05:46,  2.86it/s]





 20%|█▉        | 244/1233 [01:18<05:00,  3.29it/s]





 20%|█▉        | 245/1233 [01:18<06:42,  2.45it/s]





 20%|██        | 248/1233 [01:19<04:14,  3.87it/s]





 20%|██        | 249/1233 [01:19<04:47,  3.42it/s]





 20%|██        | 250/1233 [01:20<05:17,  3.10it/s]





 20%|██        | 251/1233 [01:20<05:02,  3.25it/s]





 20%|██        | 252/1233 [01:20<04:54,  3.33it/s]





 21%|██        | 253/1233 [01:21<06:17,  2.60it/s]





 21%|██        | 256/1233 [01:21<04:06,  3.96it/s]





 21%|██        | 257/1233 [01:22<04:38,  3.51it/s]





 21%|██        | 258/1233 [01:22<05:24,  3.01it/s]





 21%|██        | 259/1233 [01:22<04:50,  3.35it/s]





 21%|██        | 260/1233 [01:23<04:32,  3.57it/s]





 21%|██        | 261/1233 [01:23<06:15,  2.59it/s]





 21%|██▏       | 263/1233 [01:24<04:48,  3.37it/s]





 21%|██▏       | 264/1233 [01:24<05:41,  2.84it/s]





 21%|██▏       | 265/1233 [01:24<04:52,  3.31it/s]





 22%|██▏       | 266/1233 [01:25<05:54,  2.73it/s]





 22%|██▏       | 267/1233 [01:25<04:53,  3.29it/s]





 22%|██▏       | 268/1233 [01:25<05:23,  2.98it/s]





 22%|██▏       | 269/1233 [01:26<05:40,  2.83it/s]





 22%|██▏       | 270/1233 [01:26<05:12,  3.08it/s]





 22%|██▏       | 271/1233 [01:26<04:37,  3.47it/s]





 22%|██▏       | 272/1233 [01:27<05:50,  2.74it/s]





 22%|██▏       | 273/1233 [01:27<05:14,  3.05it/s]





 22%|██▏       | 274/1233 [01:28<05:59,  2.66it/s]





 22%|██▏       | 275/1233 [01:28<05:17,  3.02it/s]





 22%|██▏       | 276/1233 [01:28<06:24,  2.49it/s]





 23%|██▎       | 278/1233 [01:29<05:06,  3.12it/s]





 23%|██▎       | 280/1233 [01:30<05:48,  2.74it/s]





 23%|██▎       | 281/1233 [01:30<05:02,  3.14it/s]





 23%|██▎       | 282/1233 [01:30<04:27,  3.55it/s]





 23%|██▎       | 283/1233 [01:31<05:40,  2.79it/s]





 23%|██▎       | 284/1233 [01:31<05:11,  3.05it/s]





 23%|██▎       | 285/1233 [01:31<05:01,  3.15it/s]





 23%|██▎       | 286/1233 [01:31<04:21,  3.61it/s]





 23%|██▎       | 287/1233 [01:31<03:45,  4.20it/s]





 23%|██▎       | 288/1233 [01:32<05:37,  2.80it/s]





 23%|██▎       | 289/1233 [01:32<05:35,  2.82it/s]





 24%|██▎       | 290/1233 [01:33<05:18,  2.96it/s]





 24%|██▎       | 291/1233 [01:33<05:37,  2.79it/s]





 24%|██▎       | 292/1233 [01:33<04:56,  3.17it/s]





 24%|██▍       | 293/1233 [01:34<04:19,  3.62it/s]





 24%|██▍       | 294/1233 [01:34<04:00,  3.90it/s]





 24%|██▍       | 295/1233 [01:34<03:40,  4.25it/s]





 24%|██▍       | 296/1233 [01:35<05:39,  2.76it/s]





 24%|██▍       | 297/1233 [01:35<06:09,  2.53it/s]





 24%|██▍       | 298/1233 [01:35<05:10,  3.01it/s]





 24%|██▍       | 299/1233 [01:36<05:43,  2.72it/s]





 24%|██▍       | 300/1233 [01:36<04:49,  3.22it/s]





 24%|██▍       | 301/1233 [01:36<04:36,  3.37it/s]

 24%|██▍       | 302/1233 [01:36<03:54,  3.97it/s]





 25%|██▍       | 303/1233 [01:36<03:18,  4.69it/s]





 25%|██▍       | 304/1233 [01:37<05:07,  3.02it/s]





 25%|██▍       | 305/1233 [01:37<05:45,  2.68it/s]





 25%|██▍       | 306/1233 [01:38<05:03,  3.05it/s]





 25%|██▍       | 307/1233 [01:38<05:38,  2.74it/s]





 25%|██▍       | 308/1233 [01:38<04:41,  3.29it/s]





 25%|██▌       | 309/1233 [01:39<04:04,  3.78it/s]





 25%|██▌       | 310/1233 [01:39<03:55,  3.92it/s]





 25%|██▌       | 311/1233 [01:39<03:42,  4.14it/s]





 25%|██▌       | 312/1233 [01:39<04:51,  3.16it/s]





 25%|██▌       | 313/1233 [01:40<05:31,  2.78it/s]





 25%|██▌       | 314/1233 [01:40<05:07,  2.99it/s]





 26%|██▌       | 315/1233 [01:41<05:58,  2.56it/s]





 26%|██▌       | 317/1233 [01:41<04:27,  3.42it/s]





 26%|██▌       | 319/1233 [01:41<03:39,  4.16it/s]





 26%|██▌       | 320/1233 [01:42<04:55,  3.09it/s]





 26%|██▌       | 321/1233 [01:43<06:15,  2.43it/s]





 26%|██▌       | 323/1233 [01:43<05:24,  2.80it/s]





 26%|██▋       | 324/1233 [01:43<04:34,  3.31it/s]





 26%|██▋       | 326/1233 [01:44<04:16,  3.54it/s]





 27%|██▋       | 327/1233 [01:44<04:04,  3.71it/s]





 27%|██▋       | 328/1233 [01:45<05:36,  2.69it/s]





 27%|██▋       | 329/1233 [01:45<05:31,  2.73it/s]





 27%|██▋       | 330/1233 [01:45<04:34,  3.29it/s]





 27%|██▋       | 331/1233 [01:46<05:11,  2.89it/s]





 27%|██▋       | 332/1233 [01:46<04:22,  3.44it/s]





 27%|██▋       | 333/1233 [01:46<04:17,  3.50it/s]





 27%|██▋       | 334/1233 [01:47<04:37,  3.24it/s]





 27%|██▋       | 335/1233 [01:47<03:49,  3.91it/s]





 27%|██▋       | 336/1233 [01:47<05:58,  2.51it/s]





 27%|██▋       | 337/1233 [01:48<05:07,  2.92it/s]





 27%|██▋       | 338/1233 [01:48<04:08,  3.60it/s]





 27%|██▋       | 339/1233 [01:48<05:07,  2.91it/s]





 28%|██▊       | 340/1233 [01:49<05:24,  2.76it/s]





 28%|██▊       | 342/1233 [01:49<04:01,  3.70it/s]





 28%|██▊       | 343/1233 [01:49<03:57,  3.75it/s]





 28%|██▊       | 344/1233 [01:50<05:55,  2.50it/s]





 28%|██▊       | 346/1233 [01:50<04:33,  3.25it/s]





 28%|██▊       | 347/1233 [01:51<04:34,  3.22it/s]





 28%|██▊       | 348/1233 [01:51<04:39,  3.17it/s]





 28%|██▊       | 349/1233 [01:51<04:14,  3.47it/s]





 28%|██▊       | 350/1233 [01:52<04:24,  3.34it/s]





 28%|██▊       | 351/1233 [01:52<03:34,  4.10it/s]





 29%|██▊       | 352/1233 [01:52<05:54,  2.48it/s]





 29%|██▊       | 353/1233 [01:53<04:42,  3.11it/s]





 29%|██▊       | 354/1233 [01:53<04:35,  3.19it/s]





 29%|██▉       | 355/1233 [01:53<04:41,  3.12it/s]





 29%|██▉       | 356/1233 [01:53<03:59,  3.66it/s]





 29%|██▉       | 357/1233 [01:54<03:38,  4.00it/s]





 29%|██▉       | 358/1233 [01:54<04:47,  3.04it/s]





 29%|██▉       | 360/1233 [01:55<05:31,  2.63it/s]





 29%|██▉       | 362/1233 [01:55<04:11,  3.46it/s]





 29%|██▉       | 363/1233 [01:56<04:20,  3.34it/s]





 30%|██▉       | 364/1233 [01:56<03:53,  3.72it/s]





 30%|██▉       | 365/1233 [01:56<03:34,  4.06it/s]





 30%|██▉       | 366/1233 [01:57<04:58,  2.90it/s]





 30%|██▉       | 368/1233 [01:58<05:53,  2.45it/s]





 30%|██▉       | 369/1233 [01:58<05:14,  2.74it/s]





 30%|███       | 370/1233 [01:58<04:21,  3.30it/s]





 30%|███       | 372/1233 [01:58<03:33,  4.03it/s]





 30%|███       | 373/1233 [01:59<04:19,  3.32it/s]





 30%|███       | 374/1233 [01:59<04:53,  2.93it/s]





 30%|███       | 376/1233 [02:00<06:19,  2.26it/s]





 31%|███       | 378/1233 [02:00<04:17,  3.32it/s]





 31%|███       | 379/1233 [02:01<04:00,  3.55it/s]





 31%|███       | 380/1233 [02:01<03:45,  3.78it/s]





 31%|███       | 381/1233 [02:01<04:40,  3.04it/s]





 31%|███       | 382/1233 [02:02<04:38,  3.05it/s]





 31%|███       | 383/1233 [02:02<04:01,  3.52it/s]





 31%|███       | 384/1233 [02:03<06:17,  2.25it/s]





 31%|███▏      | 386/1233 [02:03<04:36,  3.06it/s]





 31%|███▏      | 388/1233 [02:03<03:35,  3.92it/s]





 32%|███▏      | 389/1233 [02:04<04:33,  3.09it/s]





 32%|███▏      | 390/1233 [02:04<04:27,  3.15it/s]





 32%|███▏      | 391/1233 [02:05<04:23,  3.20it/s]





 32%|███▏      | 392/1233 [02:05<05:26,  2.57it/s]





 32%|███▏      | 393/1233 [02:05<04:28,  3.13it/s]





 32%|███▏      | 394/1233 [02:06<04:06,  3.41it/s]





 32%|███▏      | 395/1233 [02:06<04:13,  3.31it/s]





 32%|███▏      | 396/1233 [02:06<03:48,  3.66it/s]





 32%|███▏      | 397/1233 [02:07<05:07,  2.72it/s]





 32%|███▏      | 399/1233 [02:07<04:00,  3.47it/s]





 32%|███▏      | 400/1233 [02:08<05:07,  2.71it/s]





 33%|███▎      | 402/1233 [02:08<04:16,  3.25it/s]





 33%|███▎      | 403/1233 [02:08<04:05,  3.38it/s]





 33%|███▎      | 405/1233 [02:09<04:38,  2.97it/s]





 33%|███▎      | 407/1233 [02:09<03:39,  3.76it/s]





 33%|███▎      | 408/1233 [02:10<04:35,  3.00it/s]





 33%|███▎      | 409/1233 [02:10<04:20,  3.17it/s]





 33%|███▎      | 410/1233 [02:11<04:39,  2.94it/s]





 33%|███▎      | 411/1233 [02:11<03:54,  3.51it/s]





 33%|███▎      | 413/1233 [02:12<04:29,  3.05it/s]





 34%|███▎      | 414/1233 [02:12<03:57,  3.46it/s]





 34%|███▎      | 415/1233 [02:12<03:34,  3.81it/s]





 34%|███▎      | 416/1233 [02:13<05:10,  2.63it/s]





 34%|███▍      | 417/1233 [02:13<05:34,  2.44it/s]





 34%|███▍      | 419/1233 [02:13<03:33,  3.81it/s]





 34%|███▍      | 420/1233 [02:13<03:16,  4.13it/s]





 34%|███▍      | 421/1233 [02:14<04:52,  2.78it/s]





 34%|███▍      | 422/1233 [02:14<03:56,  3.42it/s]





 34%|███▍      | 423/1233 [02:15<04:21,  3.09it/s]





 34%|███▍      | 424/1233 [02:15<04:47,  2.82it/s]





 34%|███▍      | 425/1233 [02:16<05:12,  2.58it/s]





 35%|███▍      | 426/1233 [02:16<04:40,  2.87it/s]





 35%|███▍      | 427/1233 [02:16<04:17,  3.12it/s]





 35%|███▍      | 428/1233 [02:16<03:27,  3.88it/s]





 35%|███▍      | 429/1233 [02:17<04:30,  2.97it/s]





 35%|███▍      | 430/1233 [02:17<04:46,  2.80it/s]





 35%|███▌      | 432/1233 [02:18<03:50,  3.48it/s]

 35%|███▌      | 433/1233 [02:18<05:51,  2.28it/s]





 35%|███▌      | 436/1233 [02:19<03:30,  3.78it/s]





 35%|███▌      | 437/1233 [02:19<04:20,  3.05it/s]





 36%|███▌      | 438/1233 [02:20<04:01,  3.30it/s]





 36%|███▌      | 439/1233 [02:20<04:03,  3.27it/s]





 36%|███▌      | 440/1233 [02:20<04:32,  2.91it/s]





 36%|███▌      | 441/1233 [02:21<05:12,  2.54it/s]





 36%|███▌      | 442/1233 [02:21<05:24,  2.44it/s]





 36%|███▌      | 443/1233 [02:21<04:20,  3.04it/s]





 36%|███▌      | 445/1233 [02:22<03:56,  3.34it/s]





 36%|███▌      | 446/1233 [02:22<03:48,  3.44it/s]





 36%|███▋      | 447/1233 [02:22<03:51,  3.40it/s]





 36%|███▋      | 448/1233 [02:23<03:25,  3.83it/s]





 36%|███▋      | 449/1233 [02:23<04:39,  2.81it/s]





 36%|███▋      | 450/1233 [02:24<04:43,  2.76it/s]





 37%|███▋      | 451/1233 [02:24<04:11,  3.11it/s]





 37%|███▋      | 453/1233 [02:24<03:48,  3.42it/s]





 37%|███▋      | 454/1233 [02:25<03:55,  3.30it/s]





 37%|███▋      | 455/1233 [02:25<04:04,  3.18it/s]





 37%|███▋      | 457/1233 [02:26<04:15,  3.04it/s]





 37%|███▋      | 458/1233 [02:26<04:01,  3.21it/s]





 37%|███▋      | 459/1233 [02:26<03:52,  3.33it/s]





 37%|███▋      | 460/1233 [02:27<03:51,  3.35it/s]





 37%|███▋      | 461/1233 [02:27<03:30,  3.66it/s]





 37%|███▋      | 462/1233 [02:27<04:20,  2.96it/s]





 38%|███▊      | 463/1233 [02:28<04:05,  3.14it/s]





 38%|███▊      | 465/1233 [02:28<04:35,  2.79it/s]





 38%|███▊      | 466/1233 [02:29<04:08,  3.09it/s]





 38%|███▊      | 467/1233 [02:29<04:15,  3.00it/s]





 38%|███▊      | 469/1233 [02:29<03:22,  3.77it/s]





 38%|███▊      | 470/1233 [02:30<03:50,  3.31it/s]





 38%|███▊      | 471/1233 [02:30<04:09,  3.06it/s]





 38%|███▊      | 472/1233 [02:30<04:04,  3.11it/s]





 38%|███▊      | 473/1233 [02:31<04:20,  2.92it/s]





 38%|███▊      | 474/1233 [02:31<03:52,  3.26it/s]





 39%|███▊      | 475/1233 [02:32<04:35,  2.75it/s]





 39%|███▊      | 476/1233 [02:32<04:58,  2.54it/s]





 39%|███▉      | 478/1233 [02:32<03:22,  3.73it/s]





 39%|███▉      | 479/1233 [02:33<04:20,  2.89it/s]





 39%|███▉      | 481/1233 [02:33<03:30,  3.57it/s]





 39%|███▉      | 482/1233 [02:34<04:00,  3.12it/s]





 39%|███▉      | 483/1233 [02:34<04:09,  3.01it/s]





 39%|███▉      | 484/1233 [02:35<05:12,  2.40it/s]





 39%|███▉      | 487/1233 [02:35<03:40,  3.38it/s]





 40%|███▉      | 488/1233 [02:36<03:50,  3.23it/s]





 40%|███▉      | 489/1233 [02:36<03:30,  3.53it/s]





 40%|███▉      | 490/1233 [02:36<04:10,  2.96it/s]





 40%|███▉      | 491/1233 [02:37<04:26,  2.78it/s]





 40%|███▉      | 492/1233 [02:37<05:14,  2.36it/s]





 40%|███▉      | 493/1233 [02:38<04:24,  2.80it/s]





 40%|████      | 494/1233 [02:38<03:36,  3.42it/s]





 40%|████      | 495/1233 [02:38<03:36,  3.42it/s]





 40%|████      | 496/1233 [02:38<03:51,  3.19it/s]





 40%|████      | 497/1233 [02:38<03:15,  3.76it/s]





 40%|████      | 498/1233 [02:39<03:39,  3.35it/s]





 40%|████      | 499/1233 [02:39<04:03,  3.01it/s]





 41%|████      | 500/1233 [02:40<04:54,  2.49it/s]





 41%|████      | 501/1233 [02:40<03:56,  3.10it/s]





 41%|████      | 502/1233 [02:40<03:13,  3.78it/s]





 41%|████      | 503/1233 [02:40<03:13,  3.77it/s]





 41%|████      | 504/1233 [02:41<04:12,  2.88it/s]





 41%|████      | 506/1233 [02:41<03:23,  3.58it/s]





 41%|████      | 507/1233 [02:42<04:29,  2.70it/s]





 41%|████      | 508/1233 [02:42<04:35,  2.63it/s]





 41%|████▏     | 509/1233 [02:42<03:51,  3.12it/s]





 41%|████▏     | 510/1233 [02:43<03:13,  3.74it/s]





 41%|████▏     | 511/1233 [02:43<03:12,  3.75it/s]





 42%|████▏     | 512/1233 [02:44<04:38,  2.59it/s]





 42%|████▏     | 514/1233 [02:44<03:06,  3.85it/s]





 42%|████▏     | 515/1233 [02:44<04:02,  2.97it/s]





 42%|████▏     | 516/1233 [02:45<04:40,  2.56it/s]





 42%|████▏     | 518/1233 [02:45<03:08,  3.80it/s]





 42%|████▏     | 519/1233 [02:45<03:26,  3.45it/s]





 42%|████▏     | 520/1233 [02:46<04:08,  2.87it/s]





 42%|████▏     | 521/1233 [02:46<03:25,  3.46it/s]





 42%|████▏     | 522/1233 [02:47<04:13,  2.80it/s]





 42%|████▏     | 523/1233 [02:47<04:16,  2.77it/s]





 42%|████▏     | 524/1233 [02:47<03:54,  3.02it/s]





 43%|████▎     | 525/1233 [02:48<04:45,  2.48it/s]





 43%|████▎     | 526/1233 [02:48<03:52,  3.04it/s]





 43%|████▎     | 527/1233 [02:48<03:40,  3.21it/s]





 43%|████▎     | 528/1233 [02:48<03:00,  3.90it/s]





 43%|████▎     | 529/1233 [02:49<03:35,  3.26it/s]





 43%|████▎     | 530/1233 [02:49<04:04,  2.88it/s]





 43%|████▎     | 531/1233 [02:50<05:18,  2.20it/s]





 43%|████▎     | 533/1233 [02:50<03:57,  2.94it/s]





 43%|████▎     | 534/1233 [02:51<03:23,  3.43it/s]





 43%|████▎     | 535/1233 [02:51<03:09,  3.68it/s]





 43%|████▎     | 536/1233 [02:51<03:13,  3.60it/s]





 44%|████▎     | 537/1233 [02:52<04:24,  2.63it/s]





 44%|████▎     | 538/1233 [02:52<04:16,  2.71it/s]





 44%|████▎     | 539/1233 [02:52<04:04,  2.84it/s]





 44%|████▍     | 540/1233 [02:53<03:25,  3.37it/s]





 44%|████▍     | 541/1233 [02:53<03:32,  3.26it/s]





 44%|████▍     | 542/1233 [02:53<04:05,  2.81it/s]





 44%|████▍     | 543/1233 [02:53<03:27,  3.32it/s]





 44%|████▍     | 545/1233 [02:54<03:47,  3.02it/s]





 44%|████▍     | 546/1233 [02:55<04:17,  2.67it/s]





 44%|████▍     | 547/1233 [02:55<03:37,  3.16it/s]





 44%|████▍     | 548/1233 [02:55<03:11,  3.57it/s]





 45%|████▍     | 549/1233 [02:55<02:45,  4.14it/s]





 45%|████▍     | 550/1233 [02:56<03:42,  3.07it/s]





 45%|████▍     | 551/1233 [02:56<03:19,  3.42it/s]





 45%|████▍     | 553/1233 [02:57<03:30,  3.23it/s]





 45%|████▍     | 554/1233 [02:57<04:12,  2.68it/s]





 45%|████▌     | 555/1233 [02:57<03:28,  3.25it/s]





 45%|████▌     | 556/1233 [02:57<03:09,  3.58it/s]





 45%|████▌     | 557/1233 [02:58<02:58,  3.78it/s]





 45%|████▌     | 558/1233 [02:58<03:14,  3.48it/s]





 45%|████▌     | 559/1233 [02:58<03:18,  3.40it/s]

 45%|████▌     | 560/1233 [02:59<02:47,  4.01it/s]





 45%|████▌     | 561/1233 [02:59<03:32,  3.16it/s]





 46%|████▌     | 562/1233 [03:00<04:45,  2.35it/s]





 46%|████▌     | 564/1233 [03:00<03:41,  3.03it/s]





 46%|████▌     | 566/1233 [03:00<03:02,  3.65it/s]





 46%|████▌     | 567/1233 [03:01<03:45,  2.96it/s]





 46%|████▌     | 568/1233 [03:01<03:08,  3.52it/s]





 46%|████▌     | 569/1233 [03:01<03:01,  3.67it/s]





 46%|████▌     | 570/1233 [03:02<04:05,  2.70it/s]





 46%|████▋     | 571/1233 [03:02<03:31,  3.13it/s]





 46%|████▋     | 572/1233 [03:03<03:30,  3.15it/s]





 46%|████▋     | 573/1233 [03:03<02:54,  3.78it/s]





 47%|████▋     | 574/1233 [03:03<04:18,  2.55it/s]





 47%|████▋     | 575/1233 [03:04<04:00,  2.73it/s]





 47%|████▋     | 577/1233 [03:04<02:37,  4.17it/s]





 47%|████▋     | 578/1233 [03:05<04:42,  2.32it/s]





 47%|████▋     | 580/1233 [03:05<03:14,  3.35it/s]





 47%|████▋     | 581/1233 [03:05<02:56,  3.70it/s]





 47%|████▋     | 582/1233 [03:06<03:40,  2.95it/s]





 47%|████▋     | 583/1233 [03:06<03:50,  2.82it/s]





 47%|████▋     | 584/1233 [03:06<03:07,  3.46it/s]





 47%|████▋     | 585/1233 [03:07<02:56,  3.66it/s]





 48%|████▊     | 586/1233 [03:07<04:14,  2.54it/s]





 48%|████▊     | 587/1233 [03:08<03:53,  2.77it/s]





 48%|████▊     | 589/1233 [03:08<03:18,  3.25it/s]





 48%|████▊     | 590/1233 [03:08<03:35,  2.99it/s]





 48%|████▊     | 591/1233 [03:09<03:28,  3.09it/s]





 48%|████▊     | 593/1233 [03:09<02:57,  3.60it/s]





 48%|████▊     | 594/1233 [03:10<03:45,  2.83it/s]





 48%|████▊     | 595/1233 [03:11<05:05,  2.09it/s]





 48%|████▊     | 598/1233 [03:11<03:04,  3.44it/s]





 49%|████▊     | 599/1233 [03:11<03:05,  3.42it/s]





 49%|████▊     | 600/1233 [03:12<03:24,  3.09it/s]





 49%|████▉     | 602/1233 [03:13<03:49,  2.74it/s]





 49%|████▉     | 603/1233 [03:13<05:03,  2.07it/s]





 49%|████▉     | 606/1233 [03:14<03:11,  3.28it/s]





 49%|████▉     | 607/1233 [03:14<02:52,  3.64it/s]





 49%|████▉     | 608/1233 [03:14<02:48,  3.70it/s]





 49%|████▉     | 609/1233 [03:14<02:24,  4.32it/s]





 49%|████▉     | 610/1233 [03:15<03:38,  2.85it/s]





 50%|████▉     | 611/1233 [03:16<05:14,  1.98it/s]





 50%|████▉     | 613/1233 [03:16<03:23,  3.05it/s]





 50%|████▉     | 615/1233 [03:17<02:48,  3.68it/s]





 50%|████▉     | 616/1233 [03:17<02:36,  3.95it/s]





 50%|█████     | 617/1233 [03:17<02:41,  3.82it/s]





 50%|█████     | 618/1233 [03:18<03:41,  2.78it/s]





 50%|█████     | 619/1233 [03:18<04:43,  2.16it/s]





 50%|█████     | 620/1233 [03:19<03:53,  2.63it/s]





 50%|█████     | 622/1233 [03:19<02:33,  3.97it/s]





 51%|█████     | 623/1233 [03:19<03:26,  2.95it/s]





 51%|█████     | 625/1233 [03:20<02:37,  3.86it/s]





 51%|█████     | 626/1233 [03:20<03:09,  3.21it/s]





 51%|█████     | 627/1233 [03:21<04:23,  2.30it/s]





 51%|█████     | 628/1233 [03:21<03:43,  2.70it/s]





 51%|█████     | 630/1233 [03:21<02:30,  4.02it/s]





 51%|█████     | 631/1233 [03:22<03:26,  2.92it/s]





 51%|█████▏    | 633/1233 [03:22<02:45,  3.62it/s]





 51%|█████▏    | 634/1233 [03:22<02:35,  3.84it/s]





 52%|█████▏    | 635/1233 [03:24<04:39,  2.14it/s]





 52%|█████▏    | 637/1233 [03:24<03:01,  3.29it/s]





 52%|█████▏    | 638/1233 [03:24<02:35,  3.82it/s]





 52%|█████▏    | 639/1233 [03:25<03:39,  2.71it/s]





 52%|█████▏    | 640/1233 [03:25<03:03,  3.23it/s]





 52%|█████▏    | 641/1233 [03:25<02:43,  3.62it/s]





 52%|█████▏    | 642/1233 [03:25<03:04,  3.21it/s]





 52%|█████▏    | 643/1233 [03:26<04:15,  2.31it/s]





 52%|█████▏    | 644/1233 [03:26<03:27,  2.84it/s]





 52%|█████▏    | 645/1233 [03:26<02:47,  3.51it/s]





 52%|█████▏    | 646/1233 [03:27<02:53,  3.38it/s]





 52%|█████▏    | 647/1233 [03:27<03:26,  2.84it/s]





 53%|█████▎    | 648/1233 [03:27<03:19,  2.94it/s]





 53%|█████▎    | 650/1233 [03:28<02:25,  4.01it/s]





 53%|█████▎    | 651/1233 [03:28<03:39,  2.65it/s]





 53%|█████▎    | 652/1233 [03:29<03:00,  3.21it/s]





 53%|█████▎    | 653/1233 [03:29<02:40,  3.61it/s]





 53%|█████▎    | 654/1233 [03:29<03:00,  3.21it/s]





 53%|█████▎    | 655/1233 [03:30<03:00,  3.19it/s]





 53%|█████▎    | 656/1233 [03:30<02:58,  3.24it/s]





 53%|█████▎    | 657/1233 [03:30<02:46,  3.45it/s]





 53%|█████▎    | 659/1233 [03:31<03:22,  2.84it/s]





 54%|█████▎    | 660/1233 [03:31<02:47,  3.43it/s]





 54%|█████▎    | 661/1233 [03:31<02:28,  3.86it/s]





 54%|█████▎    | 662/1233 [03:32<03:06,  3.06it/s]





 54%|█████▍    | 663/1233 [03:32<02:57,  3.21it/s]





 54%|█████▍    | 664/1233 [03:32<03:24,  2.78it/s]





 54%|█████▍    | 666/1233 [03:33<02:11,  4.31it/s]





 54%|█████▍    | 667/1233 [03:33<03:41,  2.55it/s]





 54%|█████▍    | 668/1233 [03:34<03:10,  2.96it/s]





 54%|█████▍    | 669/1233 [03:34<02:50,  3.31it/s]





 54%|█████▍    | 670/1233 [03:34<02:40,  3.51it/s]





 54%|█████▍    | 671/1233 [03:34<02:41,  3.47it/s]





 55%|█████▍    | 672/1233 [03:35<03:15,  2.88it/s]





 55%|█████▍    | 673/1233 [03:35<02:48,  3.33it/s]





 55%|█████▍    | 674/1233 [03:35<02:21,  3.94it/s]





 55%|█████▍    | 675/1233 [03:36<03:56,  2.36it/s]





 55%|█████▍    | 676/1233 [03:36<03:18,  2.81it/s]





 55%|█████▍    | 677/1233 [03:37<03:15,  2.84it/s]





 55%|█████▍    | 678/1233 [03:37<02:57,  3.12it/s]





 55%|█████▌    | 679/1233 [03:37<02:36,  3.54it/s]





 55%|█████▌    | 680/1233 [03:37<02:59,  3.08it/s]





 55%|█████▌    | 681/1233 [03:38<02:39,  3.47it/s]





 55%|█████▌    | 682/1233 [03:38<02:18,  3.97it/s]





 55%|█████▌    | 683/1233 [03:39<03:38,  2.51it/s]





 55%|█████▌    | 684/1233 [03:39<02:59,  3.06it/s]





 56%|█████▌    | 685/1233 [03:39<03:04,  2.97it/s]





 56%|█████▌    | 686/1233 [03:40<03:28,  2.63it/s]





 56%|█████▌    | 688/1233 [03:40<03:04,  2.95it/s]





 56%|█████▌    | 690/1233 [03:40<02:08,  4.22it/s]





 56%|█████▌    | 691/1233 [03:41<03:26,  2.62it/s]





 56%|█████▌    | 692/1233 [03:41<02:51,  3.15it/s]

 56%|█████▌    | 693/1233 [03:42<02:37,  3.43it/s]





 56%|█████▋    | 694/1233 [03:42<03:16,  2.74it/s]





 56%|█████▋    | 695/1233 [03:42<02:46,  3.22it/s]





 56%|█████▋    | 696/1233 [03:43<02:44,  3.26it/s]





 57%|█████▋    | 697/1233 [03:43<02:25,  3.69it/s]





 57%|█████▋    | 699/1233 [03:44<03:11,  2.79it/s]





 57%|█████▋    | 701/1233 [03:44<02:26,  3.64it/s]





 57%|█████▋    | 702/1233 [03:45<02:56,  3.01it/s]





 57%|█████▋    | 703/1233 [03:45<02:43,  3.24it/s]





 57%|█████▋    | 704/1233 [03:45<02:33,  3.45it/s]





 57%|█████▋    | 705/1233 [03:45<02:24,  3.65it/s]





 57%|█████▋    | 706/1233 [03:45<02:01,  4.35it/s]





 57%|█████▋    | 707/1233 [03:46<03:11,  2.74it/s]





 57%|█████▋    | 708/1233 [03:46<02:40,  3.27it/s]





 58%|█████▊    | 709/1233 [03:46<02:23,  3.66it/s]





 58%|█████▊    | 710/1233 [03:47<03:20,  2.61it/s]





 58%|█████▊    | 711/1233 [03:47<02:39,  3.28it/s]





 58%|█████▊    | 712/1233 [03:47<02:33,  3.40it/s]





 58%|█████▊    | 713/1233 [03:48<02:32,  3.40it/s]





 58%|█████▊    | 715/1233 [03:48<02:52,  3.00it/s]





 58%|█████▊    | 716/1233 [03:49<02:33,  3.38it/s]





 58%|█████▊    | 717/1233 [03:49<02:13,  3.87it/s]





 58%|█████▊    | 718/1233 [03:50<03:21,  2.56it/s]





 58%|█████▊    | 719/1233 [03:50<02:42,  3.16it/s]





 58%|█████▊    | 720/1233 [03:50<03:08,  2.73it/s]





 59%|█████▊    | 722/1233 [03:50<02:17,  3.72it/s]





 59%|█████▊    | 723/1233 [03:51<02:56,  2.89it/s]





 59%|█████▊    | 724/1233 [03:51<02:47,  3.03it/s]





 59%|█████▉    | 726/1233 [03:52<03:03,  2.76it/s]





 59%|█████▉    | 727/1233 [03:52<02:57,  2.84it/s]





 59%|█████▉    | 728/1233 [03:53<02:35,  3.25it/s]





 59%|█████▉    | 729/1233 [03:53<02:34,  3.26it/s]





 59%|█████▉    | 730/1233 [03:53<02:45,  3.04it/s]





 59%|█████▉    | 731/1233 [03:54<03:05,  2.71it/s]





 59%|█████▉    | 733/1233 [03:54<02:09,  3.85it/s]





 60%|█████▉    | 734/1233 [03:55<02:52,  2.89it/s]





 60%|█████▉    | 735/1233 [03:55<03:07,  2.65it/s]





 60%|█████▉    | 737/1233 [03:55<02:17,  3.60it/s]





 60%|█████▉    | 738/1233 [03:56<02:50,  2.91it/s]





 60%|█████▉    | 739/1233 [03:56<02:53,  2.85it/s]





 60%|██████    | 741/1233 [03:57<02:19,  3.52it/s]





 60%|██████    | 742/1233 [03:57<02:20,  3.49it/s]





 60%|██████    | 743/1233 [03:58<03:03,  2.66it/s]





 60%|██████    | 744/1233 [03:58<02:54,  2.80it/s]





 61%|██████    | 746/1233 [03:59<03:09,  2.58it/s]





 61%|██████    | 747/1233 [04:00<03:57,  2.05it/s]





 61%|██████    | 749/1233 [04:00<02:32,  3.16it/s]





 61%|██████    | 750/1233 [04:00<02:48,  2.86it/s]





 61%|██████    | 752/1233 [04:01<02:52,  2.79it/s]





 61%|██████    | 753/1233 [04:01<03:08,  2.54it/s]





 61%|██████    | 754/1233 [04:02<03:56,  2.02it/s]





 61%|██████▏   | 756/1233 [04:03<02:50,  2.79it/s]





 61%|██████▏   | 757/1233 [04:03<02:47,  2.85it/s]





 61%|██████▏   | 758/1233 [04:03<02:34,  3.07it/s]





 62%|██████▏   | 759/1233 [04:04<02:56,  2.69it/s]





 62%|██████▏   | 760/1233 [04:04<03:16,  2.41it/s]





 62%|██████▏   | 761/1233 [04:04<02:54,  2.71it/s]





 62%|██████▏   | 762/1233 [04:05<03:51,  2.04it/s]





 62%|██████▏   | 763/1233 [04:06<03:46,  2.08it/s]





 62%|██████▏   | 764/1233 [04:06<02:54,  2.68it/s]





 62%|██████▏   | 765/1233 [04:06<03:24,  2.29it/s]





 62%|██████▏   | 766/1233 [04:07<03:26,  2.26it/s]





 62%|██████▏   | 767/1233 [04:07<03:41,  2.10it/s]





 62%|██████▏   | 768/1233 [04:08<02:55,  2.66it/s]





 62%|██████▏   | 769/1233 [04:08<03:16,  2.36it/s]





 62%|██████▏   | 770/1233 [04:08<02:34,  2.99it/s]





 63%|██████▎   | 772/1233 [04:10<03:37,  2.12it/s]





 63%|██████▎   | 773/1233 [04:10<03:32,  2.16it/s]





 63%|██████▎   | 774/1233 [04:10<03:18,  2.31it/s]





 63%|██████▎   | 775/1233 [04:10<02:44,  2.78it/s]





 63%|██████▎   | 776/1233 [04:11<02:18,  3.29it/s]





 63%|██████▎   | 777/1233 [04:11<01:52,  4.07it/s]





 63%|██████▎   | 778/1233 [04:11<02:35,  2.93it/s]





 63%|██████▎   | 779/1233 [04:12<03:35,  2.10it/s]





 63%|██████▎   | 780/1233 [04:12<02:58,  2.54it/s]





 63%|██████▎   | 781/1233 [04:12<02:26,  3.08it/s]





 63%|██████▎   | 782/1233 [04:13<02:53,  2.60it/s]





 64%|██████▎   | 783/1233 [04:13<02:58,  2.52it/s]





 64%|██████▎   | 784/1233 [04:14<02:35,  2.89it/s]





 64%|██████▎   | 785/1233 [04:14<02:22,  3.13it/s]





 64%|██████▎   | 786/1233 [04:14<02:01,  3.66it/s]





 64%|██████▍   | 787/1233 [04:15<02:56,  2.53it/s]





 64%|██████▍   | 788/1233 [04:15<02:37,  2.83it/s]





 64%|██████▍   | 789/1233 [04:15<02:26,  3.03it/s]





 64%|██████▍   | 790/1233 [04:15<02:04,  3.57it/s]





 64%|██████▍   | 791/1233 [04:16<02:19,  3.18it/s]





 64%|██████▍   | 792/1233 [04:16<02:46,  2.65it/s]





 64%|██████▍   | 793/1233 [04:17<02:20,  3.14it/s]





 64%|██████▍   | 795/1233 [04:17<02:42,  2.70it/s]





 65%|██████▍   | 796/1233 [04:18<02:27,  2.96it/s]





 65%|██████▍   | 798/1233 [04:18<01:53,  3.82it/s]





 65%|██████▍   | 799/1233 [04:18<02:10,  3.34it/s]





 65%|██████▍   | 800/1233 [04:19<02:17,  3.15it/s]





 65%|██████▍   | 801/1233 [04:19<02:08,  3.37it/s]





 65%|██████▌   | 802/1233 [04:19<01:52,  3.82it/s]





 65%|██████▌   | 803/1233 [04:20<03:06,  2.30it/s]





 65%|██████▌   | 805/1233 [04:20<02:08,  3.33it/s]





 65%|██████▌   | 806/1233 [04:21<02:26,  2.92it/s]





 66%|██████▌   | 808/1233 [04:22<02:33,  2.77it/s]





 66%|██████▌   | 809/1233 [04:22<02:09,  3.27it/s]





 66%|██████▌   | 811/1233 [04:23<02:36,  2.70it/s]





 66%|██████▌   | 812/1233 [04:23<02:13,  3.14it/s]





 66%|██████▌   | 813/1233 [04:23<01:58,  3.54it/s]





 66%|██████▌   | 814/1233 [04:23<02:14,  3.12it/s]





 66%|██████▌   | 816/1233 [04:24<02:37,  2.64it/s]





 66%|██████▋   | 817/1233 [04:25<02:34,  2.69it/s]





 66%|██████▋   | 819/1233 [04:25<02:35,  2.66it/s]





 67%|██████▋   | 821/1233 [04:26<02:03,  3.33it/s]





 67%|██████▋   | 822/1233 [04:26<01:50,  3.71it/s]





 67%|██████▋   | 823/1233 [04:26<01:51,  3.68it/s]

 67%|██████▋   | 824/1233 [04:27<03:01,  2.26it/s]





 67%|██████▋   | 825/1233 [04:27<02:30,  2.71it/s]





 67%|██████▋   | 826/1233 [04:27<02:15,  3.00it/s]





 67%|██████▋   | 827/1233 [04:28<02:21,  2.87it/s]





 67%|██████▋   | 828/1233 [04:28<02:06,  3.19it/s]





 67%|██████▋   | 830/1233 [04:28<01:27,  4.61it/s]





 67%|██████▋   | 831/1233 [04:29<01:52,  3.59it/s]





 67%|██████▋   | 832/1233 [04:30<02:56,  2.27it/s]





 68%|██████▊   | 833/1233 [04:30<02:25,  2.74it/s]





 68%|██████▊   | 835/1233 [04:30<02:06,  3.14it/s]





 68%|██████▊   | 836/1233 [04:31<01:51,  3.57it/s]





 68%|██████▊   | 838/1233 [04:31<01:24,  4.66it/s]





 68%|██████▊   | 839/1233 [04:31<01:45,  3.74it/s]





 68%|██████▊   | 840/1233 [04:32<02:47,  2.34it/s]





 68%|██████▊   | 841/1233 [04:32<02:20,  2.78it/s]





 68%|██████▊   | 843/1233 [04:33<02:04,  3.13it/s]





 69%|██████▊   | 845/1233 [04:33<01:28,  4.40it/s]





 69%|██████▊   | 846/1233 [04:33<01:23,  4.66it/s]





 69%|██████▊   | 847/1233 [04:34<01:52,  3.42it/s]





 69%|██████▉   | 848/1233 [04:35<02:44,  2.34it/s]





 69%|██████▉   | 849/1233 [04:35<02:15,  2.84it/s]





 69%|██████▉   | 850/1233 [04:35<01:49,  3.49it/s]





 69%|██████▉   | 851/1233 [04:35<02:01,  3.15it/s]





 69%|██████▉   | 852/1233 [04:35<01:46,  3.58it/s]





 69%|██████▉   | 853/1233 [04:36<01:47,  3.53it/s]





 69%|██████▉   | 854/1233 [04:36<01:31,  4.13it/s]





 69%|██████▉   | 855/1233 [04:36<01:46,  3.55it/s]





 69%|██████▉   | 856/1233 [04:37<03:05,  2.04it/s]





 70%|██████▉   | 857/1233 [04:37<02:28,  2.54it/s]





 70%|██████▉   | 859/1233 [04:38<01:55,  3.25it/s]





 70%|██████▉   | 860/1233 [04:38<01:43,  3.59it/s]





 70%|██████▉   | 861/1233 [04:38<01:43,  3.60it/s]





 70%|██████▉   | 862/1233 [04:39<02:07,  2.90it/s]





 70%|███████   | 864/1233 [04:40<02:23,  2.58it/s]





 70%|███████   | 865/1233 [04:40<02:07,  2.89it/s]





 70%|███████   | 866/1233 [04:40<02:16,  2.70it/s]





 70%|███████   | 869/1233 [04:41<01:48,  3.36it/s]





 71%|███████   | 870/1233 [04:41<01:50,  3.29it/s]





 71%|███████   | 871/1233 [04:41<01:38,  3.69it/s]





 71%|███████   | 872/1233 [04:42<02:21,  2.55it/s]





 71%|███████   | 874/1233 [04:43<01:59,  3.01it/s]





 71%|███████   | 875/1233 [04:43<01:59,  3.00it/s]





 71%|███████   | 877/1233 [04:43<01:36,  3.67it/s]





 71%|███████   | 878/1233 [04:44<01:48,  3.27it/s]





 71%|███████▏  | 879/1233 [04:44<01:34,  3.75it/s]





 71%|███████▏  | 880/1233 [04:45<02:17,  2.58it/s]





Multiplets | family 5:   0%|          | 0/370 [08:48<?, ?it/s]
Multiplets | family 3:   0%|          | 0/129 [05:15<?, ?it/s]






 72%|███████▏  | 882/1233 [04:45<02:17,  2.55it/s]





 72%|███████▏  | 884/1233 [04:46<01:35,  3.66it/s]





 72%|███████▏  | 885/1233 [04:46<01:37,  3.57it/s]





 72%|███████▏  | 886/1233 [04:46<01:32,  3.77it/s]





 72%|███████▏  | 887/1233 [04:47<01:43,  3.34it/s]





 72%|███████▏  | 888/1233 [04:47<02:12,  2.60it/s]





 72%|███████▏  | 890/1233 [04:48<02:02,  2.80it/s]





 72%|███████▏  | 891/1233 [04:48<01:44,  3.27it/s]





 72%|███████▏  | 893/1233 [04:48<01:34,  3.60it/s]





 73%|███████▎  | 894/1233 [04:49<01:30,  3.77it/s]





 73%|███████▎  | 895/1233 [04:49<01:32,  3.64it/s]





 73%|███████▎  | 896/1233 [04:50<01:57,  2.88it/s]





 73%|███████▎  | 897/1233 [04:50<01:38,  3.42it/s]





 73%|███████▎  | 898/1233 [04:50<02:01,  2.76it/s]





 73%|███████▎  | 899/1233 [04:50<01:45,  3.18it/s]





 73%|███████▎  | 901/1233 [04:51<01:33,  3.54it/s]





 73%|███████▎  | 902/1233 [04:51<01:29,  3.69it/s]





 73%|███████▎  | 903/1233 [04:51<01:29,  3.68it/s]





 73%|███████▎  | 904/1233 [04:52<01:50,  2.99it/s]





 73%|███████▎  | 905/1233 [04:52<01:37,  3.36it/s]





 73%|███████▎  | 906/1233 [04:53<02:12,  2.46it/s]





 74%|███████▎  | 907/1233 [04:53<01:47,  3.03it/s]





 74%|███████▎  | 909/1233 [04:53<01:29,  3.60it/s]





 74%|███████▍  | 910/1233 [04:54<01:26,  3.75it/s]





 74%|███████▍  | 911/1233 [04:54<01:38,  3.28it/s]





 74%|███████▍  | 912/1233 [04:54<01:49,  2.94it/s]





 74%|███████▍  | 913/1233 [04:55<02:09,  2.46it/s]





 74%|███████▍  | 914/1233 [04:55<01:48,  2.94it/s]





 74%|███████▍  | 915/1233 [04:56<01:52,  2.83it/s]





 74%|███████▍  | 916/1233 [04:56<01:40,  3.16it/s]





 74%|███████▍  | 918/1233 [04:56<01:26,  3.63it/s]





 75%|███████▍  | 919/1233 [04:57<01:25,  3.69it/s]





 75%|███████▍  | 920/1233 [04:57<01:59,  2.62it/s]





 75%|███████▍  | 921/1233 [04:58<01:54,  2.72it/s]





 75%|███████▍  | 923/1233 [04:58<01:45,  2.93it/s]





 75%|███████▍  | 924/1233 [04:58<01:27,  3.51it/s]





 75%|███████▌  | 926/1233 [04:59<01:40,  3.06it/s]





 75%|███████▌  | 927/1233 [04:59<01:34,  3.22it/s]





 75%|███████▌  | 928/1233 [05:00<01:37,  3.12it/s]





 75%|███████▌  | 929/1233 [05:00<01:40,  3.01it/s]





 75%|███████▌  | 930/1233 [05:00<01:22,  3.65it/s]





 76%|███████▌  | 931/1233 [05:01<01:31,  3.30it/s]





 76%|███████▌  | 932/1233 [05:01<01:39,  3.02it/s]





 76%|███████▌  | 934/1233 [05:02<01:37,  3.07it/s]





 76%|███████▌  | 935/1233 [05:02<01:39,  3.01it/s]





 76%|███████▌  | 936/1233 [05:02<01:27,  3.38it/s]





 76%|███████▌  | 937/1233 [05:03<01:39,  2.97it/s]





 76%|███████▌  | 938/1233 [05:03<01:20,  3.65it/s]





 76%|███████▌  | 939/1233 [05:03<01:18,  3.73it/s]





 76%|███████▌  | 940/1233 [05:03<01:27,  3.35it/s]





 76%|███████▋  | 941/1233 [05:04<01:26,  3.37it/s]





 76%|███████▋  | 942/1233 [05:04<01:35,  3.06it/s]





 76%|███████▋  | 943/1233 [05:04<01:38,  2.94it/s]





 77%|███████▋  | 944/1233 [05:05<01:25,  3.38it/s]





 77%|███████▋  | 945/1233 [05:05<01:28,  3.26it/s]





 77%|███████▋  | 946/1233 [05:05<01:28,  3.23it/s]





 77%|███████▋  | 947/1233 [05:05<01:11,  4.00it/s]





 77%|███████▋  | 948/1233 [05:06<01:24,  3.38it/s]





 77%|███████▋  | 949/1233 [05:06<01:28,  3.19it/s]





 77%|███████▋  | 950/1233 [05:06<01:30,  3.13it/s]





 77%|███████▋  | 951/1233 [05:07<01:45,  2.67it/s]





 77%|███████▋  | 952/1233 [05:07<01:27,  3.22it/s]

 77%|███████▋  | 953/1233 [05:07<01:20,  3.48it/s]





 77%|███████▋  | 954/1233 [05:08<01:28,  3.15it/s]





 77%|███████▋  | 955/1233 [05:08<01:10,  3.92it/s]





 78%|███████▊  | 956/1233 [05:08<01:18,  3.55it/s]





 78%|███████▊  | 957/1233 [05:09<01:35,  2.89it/s]





 78%|███████▊  | 958/1233 [05:09<01:39,  2.76it/s]





 78%|███████▊  | 959/1233 [05:09<01:43,  2.65it/s]





 78%|███████▊  | 960/1233 [05:10<01:29,  3.05it/s]





 78%|███████▊  | 962/1233 [05:10<01:23,  3.24it/s]





 78%|███████▊  | 964/1233 [05:11<01:27,  3.06it/s]





 78%|███████▊  | 965/1233 [05:11<01:16,  3.50it/s]





 78%|███████▊  | 966/1233 [05:12<01:39,  2.69it/s]





 78%|███████▊  | 967/1233 [05:12<01:33,  2.84it/s]





 79%|███████▊  | 968/1233 [05:12<01:24,  3.12it/s]





 79%|███████▊  | 969/1233 [05:13<01:45,  2.50it/s]





 79%|███████▊  | 970/1233 [05:13<01:35,  2.75it/s]





 79%|███████▉  | 972/1233 [05:13<01:04,  4.02it/s]





 79%|███████▉  | 973/1233 [05:14<01:02,  4.17it/s]





 79%|███████▉  | 974/1233 [05:14<01:44,  2.48it/s]





 79%|███████▉  | 975/1233 [05:15<01:23,  3.08it/s]





 79%|███████▉  | 976/1233 [05:15<01:30,  2.84it/s]





 79%|███████▉  | 977/1233 [05:15<01:29,  2.87it/s]





 79%|███████▉  | 978/1233 [05:16<01:26,  2.95it/s]





 79%|███████▉  | 979/1233 [05:16<01:17,  3.28it/s]





 80%|███████▉  | 981/1233 [05:16<00:49,  5.09it/s]





 80%|███████▉  | 982/1233 [05:17<01:43,  2.42it/s]





 80%|███████▉  | 984/1233 [05:17<01:18,  3.18it/s]





 80%|███████▉  | 985/1233 [05:18<01:16,  3.23it/s]





 80%|███████▉  | 986/1233 [05:18<01:32,  2.68it/s]





 80%|████████  | 987/1233 [05:18<01:17,  3.17it/s]





 80%|████████  | 989/1233 [05:19<00:54,  4.49it/s]





 80%|████████  | 990/1233 [05:19<01:29,  2.70it/s]





 80%|████████  | 991/1233 [05:20<01:21,  2.96it/s]





 80%|████████  | 992/1233 [05:20<01:15,  3.19it/s]





 81%|████████  | 993/1233 [05:20<01:09,  3.47it/s]





 81%|████████  | 994/1233 [05:21<01:20,  2.96it/s]





 81%|████████  | 995/1233 [05:21<01:09,  3.43it/s]





 81%|████████  | 996/1233 [05:21<00:59,  3.95it/s]





 81%|████████  | 998/1233 [05:22<01:19,  2.96it/s]





 81%|████████  | 999/1233 [05:22<01:14,  3.16it/s]





 81%|████████  | 1000/1233 [05:22<01:10,  3.31it/s]





 81%|████████  | 1001/1233 [05:23<01:08,  3.41it/s]





 81%|████████▏ | 1002/1233 [05:23<01:14,  3.12it/s]





 81%|████████▏ | 1003/1233 [05:23<01:08,  3.34it/s]





 81%|████████▏ | 1004/1233 [05:23<00:58,  3.91it/s]





 82%|████████▏ | 1005/1233 [05:24<00:48,  4.67it/s]





 82%|████████▏ | 1006/1233 [05:24<01:26,  2.62it/s]





 82%|████████▏ | 1007/1233 [05:24<01:08,  3.28it/s]





 82%|████████▏ | 1008/1233 [05:25<01:12,  3.10it/s]





 82%|████████▏ | 1009/1233 [05:26<01:51,  2.01it/s]





 82%|████████▏ | 1010/1233 [05:26<01:24,  2.64it/s]





 82%|████████▏ | 1012/1233 [05:26<01:13,  3.01it/s]





 82%|████████▏ | 1014/1233 [05:27<01:00,  3.64it/s]





 82%|████████▏ | 1016/1233 [05:28<01:08,  3.18it/s]





 82%|████████▏ | 1017/1233 [05:28<01:23,  2.60it/s]





 83%|████████▎ | 1018/1233 [05:28<01:08,  3.12it/s]





 83%|████████▎ | 1019/1233 [05:29<01:13,  2.93it/s]





 83%|████████▎ | 1021/1233 [05:29<00:58,  3.60it/s]





 83%|████████▎ | 1022/1233 [05:30<01:07,  3.10it/s]





 83%|████████▎ | 1023/1233 [05:30<00:57,  3.65it/s]





 83%|████████▎ | 1024/1233 [05:30<01:01,  3.37it/s]





 83%|████████▎ | 1025/1233 [05:31<01:16,  2.70it/s]





 83%|████████▎ | 1026/1233 [05:31<01:08,  3.03it/s]





 83%|████████▎ | 1027/1233 [05:31<01:02,  3.29it/s]





 83%|████████▎ | 1028/1233 [05:31<01:08,  3.01it/s]





 83%|████████▎ | 1029/1233 [05:32<01:03,  3.22it/s]





 84%|████████▎ | 1030/1233 [05:32<01:07,  3.00it/s]





 84%|████████▎ | 1031/1233 [05:32<00:54,  3.72it/s]





 84%|████████▎ | 1032/1233 [05:33<01:10,  2.86it/s]





 84%|████████▍ | 1033/1233 [05:33<01:11,  2.79it/s]





 84%|████████▍ | 1035/1233 [05:34<01:07,  2.92it/s]





 84%|████████▍ | 1036/1233 [05:34<00:57,  3.44it/s]





 84%|████████▍ | 1037/1233 [05:34<00:55,  3.54it/s]





 84%|████████▍ | 1038/1233 [05:35<01:04,  3.02it/s]





 84%|████████▍ | 1040/1233 [05:35<01:06,  2.90it/s]





 84%|████████▍ | 1041/1233 [05:36<00:57,  3.31it/s]





 85%|████████▍ | 1042/1233 [05:36<00:49,  3.85it/s]





 85%|████████▍ | 1043/1233 [05:36<01:01,  3.07it/s]





 85%|████████▍ | 1044/1233 [05:36<00:51,  3.64it/s]





 85%|████████▍ | 1045/1233 [05:37<01:01,  3.06it/s]





 85%|████████▍ | 1046/1233 [05:37<00:58,  3.18it/s]





 85%|████████▍ | 1048/1233 [05:38<01:06,  2.79it/s]





 85%|████████▌ | 1050/1233 [05:38<00:48,  3.81it/s]





 85%|████████▌ | 1051/1233 [05:39<00:58,  3.09it/s]





 85%|████████▌ | 1052/1233 [05:39<00:50,  3.56it/s]





 85%|████████▌ | 1053/1233 [05:39<00:54,  3.31it/s]





 85%|████████▌ | 1054/1233 [05:39<00:52,  3.42it/s]





 86%|████████▌ | 1055/1233 [05:40<00:47,  3.74it/s]





 86%|████████▌ | 1056/1233 [05:40<01:05,  2.68it/s]





 86%|████████▌ | 1058/1233 [05:41<00:53,  3.27it/s]





 86%|████████▌ | 1059/1233 [05:41<00:59,  2.91it/s]





 86%|████████▌ | 1060/1233 [05:41<00:51,  3.37it/s]





 86%|████████▌ | 1061/1233 [05:42<00:50,  3.43it/s]





 86%|████████▌ | 1062/1233 [05:42<00:49,  3.45it/s]





 86%|████████▌ | 1063/1233 [05:42<00:53,  3.16it/s]





 86%|████████▋ | 1064/1233 [05:43<01:01,  2.73it/s]





 86%|████████▋ | 1066/1233 [05:44<01:02,  2.69it/s]





 87%|████████▋ | 1067/1233 [05:44<00:56,  2.94it/s]





 87%|████████▋ | 1068/1233 [05:44<00:49,  3.35it/s]





 87%|████████▋ | 1069/1233 [05:44<00:49,  3.35it/s]





 87%|████████▋ | 1071/1233 [05:45<00:56,  2.87it/s]





 87%|████████▋ | 1072/1233 [05:46<01:00,  2.66it/s]





 87%|████████▋ | 1074/1233 [05:46<00:50,  3.14it/s]





 87%|████████▋ | 1075/1233 [05:46<00:45,  3.49it/s]





 87%|████████▋ | 1076/1233 [05:46<00:38,  4.05it/s]





 87%|████████▋ | 1077/1233 [05:47<00:49,  3.13it/s]





 87%|████████▋ | 1078/1233 [05:47<00:49,  3.14it/s]





 88%|████████▊ | 1079/1233 [05:48<00:57,  2.68it/s]





 88%|████████▊ | 1080/1233 [05:48<00:52,  2.92it/s]

 88%|████████▊ | 1081/1233 [05:48<00:56,  2.69it/s]





 88%|████████▊ | 1083/1233 [05:49<00:45,  3.28it/s]





 88%|████████▊ | 1085/1233 [05:49<00:44,  3.35it/s]





 88%|████████▊ | 1086/1233 [05:50<00:45,  3.20it/s]





 88%|████████▊ | 1087/1233 [05:50<00:52,  2.79it/s]





 88%|████████▊ | 1088/1233 [05:50<00:45,  3.21it/s]





 88%|████████▊ | 1089/1233 [05:51<00:52,  2.76it/s]





 88%|████████▊ | 1091/1233 [05:51<00:37,  3.80it/s]





 89%|████████▊ | 1093/1233 [05:52<00:38,  3.64it/s]





 89%|████████▊ | 1094/1233 [05:52<00:44,  3.12it/s]





 89%|████████▉ | 1095/1233 [05:53<00:48,  2.83it/s]





 89%|████████▉ | 1096/1233 [05:53<00:44,  3.10it/s]





 89%|████████▉ | 1097/1233 [05:53<00:49,  2.76it/s]





 89%|████████▉ | 1099/1233 [05:54<00:31,  4.25it/s]





 89%|████████▉ | 1100/1233 [05:54<00:30,  4.40it/s]





 89%|████████▉ | 1101/1233 [05:54<00:37,  3.52it/s]





 89%|████████▉ | 1102/1233 [05:55<00:43,  3.01it/s]





 89%|████████▉ | 1103/1233 [05:55<00:47,  2.71it/s]





 90%|████████▉ | 1104/1233 [05:55<00:42,  3.05it/s]





 90%|████████▉ | 1105/1233 [05:56<00:50,  2.55it/s]





 90%|████████▉ | 1107/1233 [05:56<00:32,  3.84it/s]





 90%|████████▉ | 1108/1233 [05:56<00:31,  3.98it/s]





 90%|████████▉ | 1109/1233 [05:57<00:33,  3.70it/s]





 90%|█████████ | 1110/1233 [05:57<00:40,  3.07it/s]





 90%|█████████ | 1111/1233 [05:58<00:45,  2.66it/s]





 90%|█████████ | 1112/1233 [05:58<00:42,  2.86it/s]





 90%|█████████ | 1113/1233 [05:58<00:48,  2.50it/s]





 90%|█████████ | 1115/1233 [05:59<00:33,  3.52it/s]





 91%|█████████ | 1116/1233 [05:59<00:37,  3.12it/s]





 91%|█████████ | 1117/1233 [05:59<00:34,  3.32it/s]





 91%|█████████ | 1118/1233 [06:00<00:37,  3.05it/s]





 91%|█████████ | 1119/1233 [06:00<00:36,  3.10it/s]





 91%|█████████ | 1120/1233 [06:01<00:48,  2.35it/s]





 91%|█████████ | 1121/1233 [06:01<00:43,  2.59it/s]





 91%|█████████ | 1123/1233 [06:02<00:32,  3.38it/s]





 91%|█████████ | 1124/1233 [06:02<00:31,  3.47it/s]





 91%|█████████ | 1125/1233 [06:02<00:27,  4.00it/s]





 91%|█████████▏| 1126/1233 [06:03<00:39,  2.72it/s]





 91%|█████████▏| 1127/1233 [06:03<00:32,  3.25it/s]





 91%|█████████▏| 1128/1233 [06:04<00:47,  2.19it/s]





 92%|█████████▏| 1130/1233 [06:04<00:33,  3.10it/s]





 92%|█████████▏| 1132/1233 [06:04<00:24,  4.20it/s]





 92%|█████████▏| 1133/1233 [06:04<00:24,  4.12it/s]





 92%|█████████▏| 1134/1233 [06:05<00:37,  2.64it/s]





 92%|█████████▏| 1136/1233 [06:06<00:38,  2.54it/s]





 92%|█████████▏| 1138/1233 [06:06<00:30,  3.09it/s]





 92%|█████████▏| 1139/1233 [06:07<00:26,  3.51it/s]





 92%|█████████▏| 1140/1233 [06:07<00:23,  3.88it/s]





 93%|█████████▎| 1142/1233 [06:08<00:32,  2.80it/s]





 93%|█████████▎| 1144/1233 [06:08<00:30,  2.96it/s]





 93%|█████████▎| 1145/1233 [06:09<00:26,  3.31it/s]





 93%|█████████▎| 1146/1233 [06:09<00:26,  3.34it/s]





 93%|█████████▎| 1147/1233 [06:09<00:24,  3.54it/s]





 93%|█████████▎| 1148/1233 [06:09<00:21,  3.93it/s]





 93%|█████████▎| 1149/1233 [06:09<00:18,  4.57it/s]





 93%|█████████▎| 1150/1233 [06:10<00:30,  2.73it/s]





 93%|█████████▎| 1151/1233 [06:10<00:24,  3.34it/s]





 93%|█████████▎| 1152/1233 [06:11<00:28,  2.86it/s]





 94%|█████████▎| 1153/1233 [06:11<00:27,  2.95it/s]





 94%|█████████▎| 1154/1233 [06:11<00:28,  2.78it/s]





 94%|█████████▎| 1155/1233 [06:12<00:23,  3.30it/s]





 94%|█████████▍| 1157/1233 [06:12<00:22,  3.34it/s]





 94%|█████████▍| 1158/1233 [06:13<00:28,  2.63it/s]





 94%|█████████▍| 1159/1233 [06:13<00:25,  2.89it/s]





 94%|█████████▍| 1160/1233 [06:13<00:21,  3.37it/s]





 94%|█████████▍| 1161/1233 [06:14<00:25,  2.87it/s]





 94%|█████████▍| 1162/1233 [06:14<00:22,  3.17it/s]





 94%|█████████▍| 1164/1233 [06:14<00:20,  3.40it/s]





 94%|█████████▍| 1165/1233 [06:15<00:20,  3.36it/s]





 95%|█████████▍| 1166/1233 [06:15<00:23,  2.84it/s]





 95%|█████████▍| 1167/1233 [06:16<00:24,  2.73it/s]





 95%|█████████▍| 1168/1233 [06:16<00:20,  3.15it/s]





 95%|█████████▍| 1169/1233 [06:16<00:21,  2.94it/s]





 95%|█████████▍| 1170/1233 [06:16<00:18,  3.32it/s]





 95%|█████████▍| 1171/1233 [06:17<00:16,  3.75it/s]





 95%|█████████▌| 1172/1233 [06:17<00:21,  2.90it/s]





 95%|█████████▌| 1174/1233 [06:18<00:22,  2.62it/s]





 95%|█████████▌| 1176/1233 [06:18<00:15,  3.58it/s]





 95%|█████████▌| 1177/1233 [06:19<00:20,  2.77it/s]





 96%|█████████▌| 1178/1233 [06:19<00:17,  3.14it/s]





 96%|█████████▌| 1179/1233 [06:19<00:15,  3.49it/s]





 96%|█████████▌| 1180/1233 [06:20<00:16,  3.14it/s]





 96%|█████████▌| 1181/1233 [06:20<00:14,  3.59it/s]





 96%|█████████▌| 1182/1233 [06:20<00:18,  2.71it/s]





 96%|█████████▌| 1183/1233 [06:21<00:16,  3.10it/s]





 96%|█████████▌| 1185/1233 [06:21<00:15,  3.02it/s]





 96%|█████████▌| 1186/1233 [06:22<00:14,  3.26it/s]





 96%|█████████▋| 1187/1233 [06:22<00:15,  2.95it/s]





 96%|█████████▋| 1188/1233 [06:22<00:12,  3.50it/s]





 96%|█████████▋| 1189/1233 [06:22<00:12,  3.39it/s]





 97%|█████████▋| 1190/1233 [06:23<00:13,  3.11it/s]





 97%|█████████▋| 1191/1233 [06:23<00:12,  3.28it/s]





 97%|█████████▋| 1192/1233 [06:23<00:11,  3.53it/s]





 97%|█████████▋| 1193/1233 [06:24<00:11,  3.35it/s]





 97%|█████████▋| 1194/1233 [06:24<00:12,  3.15it/s]





 97%|█████████▋| 1195/1233 [06:25<00:13,  2.73it/s]





 97%|█████████▋| 1197/1233 [06:25<00:10,  3.41it/s]





 97%|█████████▋| 1198/1233 [06:25<00:10,  3.50it/s]





 97%|█████████▋| 1199/1233 [06:26<00:10,  3.38it/s]





 97%|█████████▋| 1200/1233 [06:26<00:09,  3.62it/s]





 97%|█████████▋| 1201/1233 [06:26<00:09,  3.30it/s]





 97%|█████████▋| 1202/1233 [06:27<00:09,  3.15it/s]





 98%|█████████▊| 1203/1233 [06:27<00:10,  2.91it/s]





 98%|█████████▊| 1204/1233 [06:27<00:08,  3.55it/s]





 98%|█████████▊| 1205/1233 [06:28<00:09,  2.95it/s]





 98%|█████████▊| 1206/1233 [06:28<00:07,  3.45it/s]





 98%|█████████▊| 1207/1233 [06:28<00:09,  2.87it/s]





 98%|█████████▊| 1209/1233 [06:29<00:07,  3.36it/s]





 98%|█████████▊| 1210/1233 [06:29<00:06,  3.52it/s]

 98%|█████████▊| 1211/1233 [06:29<00:06,  3.23it/s]





 98%|█████████▊| 1212/1233 [06:30<00:07,  2.89it/s]





 98%|█████████▊| 1213/1233 [06:30<00:07,  2.59it/s]





 98%|█████████▊| 1214/1233 [06:30<00:05,  3.21it/s]





 99%|█████████▊| 1215/1233 [06:31<00:05,  3.53it/s]





 99%|█████████▊| 1216/1233 [06:31<00:06,  2.65it/s]





 99%|█████████▊| 1217/1233 [06:31<00:05,  3.03it/s]





 99%|█████████▉| 1218/1233 [06:32<00:04,  3.51it/s]





 99%|█████████▉| 1219/1233 [06:32<00:03,  3.96it/s]





 99%|█████████▉| 1220/1233 [06:32<00:03,  3.51it/s]





 99%|█████████▉| 1221/1233 [06:33<00:04,  2.59it/s]





 99%|█████████▉| 1223/1233 [06:33<00:03,  2.85it/s]





 99%|█████████▉| 1224/1233 [06:34<00:03,  2.58it/s]





 99%|█████████▉| 1225/1233 [06:34<00:02,  3.20it/s]





 99%|█████████▉| 1226/1233 [06:34<00:01,  3.72it/s]





100%|█████████▉| 1227/1233 [06:34<00:01,  3.86it/s]





100%|█████████▉| 1228/1233 [06:35<00:01,  3.74it/s]





100%|█████████▉| 1229/1233 [06:35<00:01,  2.39it/s]





100%|█████████▉| 1231/1233 [06:36<00:00,  3.18it/s]





100%|█████████▉| 1232/1233 [06:36<00:00,  2.71it/s]





100%|██████████| 1233/1233 [06:37<00:00,  3.11it/s]
Families:  67%|██████▋   | 2/3 [07:06<04:05, 245.76s/it]
Multiplets | family 5:   0%|          | 0/144 [00:00<?, ?it/s]



  0%|          | 0/144 [00:00<?, ?it/s]



  1%|          | 1/144 [00:02<07:01,  2.95s/it]



  1%|▏         | 2/144 [00:03<03:16,  1.38s/it]



  2%|▏         | 3/144 [00:03<02:06,  1.11it/s]



  3%|▎         | 5/144 [00:03<01:07,  2.05it/s]



  6%|▌         | 8/144 [00:04<00:32,  4.15it/s]



  7%|▋         | 10/144 [00:06<01:20,  1.66it/s]



  9%|▉         | 13/144 [00:06<00:51,  2.52it/s]



 10%|▉         | 14/144 [00:07<00:46,  2.82it/s]



 11%|█         | 16/144 [00:07<00:33,  3.78it/s]



 12%|█▏        | 17/144 [00:09<01:15,  1.67it/s]



 12%|█▎        | 18/144 [00:09<01:09,  1.82it/s]



 14%|█▍        | 20/144 [00:10<00:51,  2.43it/s]



 15%|█▍        | 21/144 [00:10<00:43,  2.83it/s]



 15%|█▌        | 22/144 [00:10<00:42,  2.85it/s]



 17%|█▋        | 24/144 [00:10<00:30,  3.96it/s]



 17%|█▋        | 25/144 [00:12<01:21,  1.45it/s]



 19%|█▉        | 27/144 [00:13<00:53,  2.20it/s]



 19%|█▉        | 28/144 [00:13<00:45,  2.54it/s]



 20%|██        | 29/144 [00:13<00:41,  2.74it/s]



 22%|██▏       | 31/144 [00:13<00:30,  3.67it/s]



 22%|██▏       | 32/144 [00:13<00:27,  4.04it/s]



 23%|██▎       | 33/144 [00:16<01:19,  1.40it/s]



 24%|██▍       | 35/144 [00:16<00:49,  2.21it/s]



 25%|██▌       | 36/144 [00:16<00:40,  2.67it/s]



 26%|██▌       | 37/144 [00:16<00:42,  2.51it/s]



 26%|██▋       | 38/144 [00:17<00:35,  3.03it/s]



 28%|██▊       | 40/144 [00:17<00:29,  3.54it/s]



 28%|██▊       | 41/144 [00:19<01:05,  1.58it/s]



 30%|██▉       | 43/144 [00:19<00:41,  2.42it/s]



 31%|███       | 44/144 [00:19<00:34,  2.88it/s]



 31%|███▏      | 45/144 [00:20<00:37,  2.63it/s]



 32%|███▏      | 46/144 [00:20<00:31,  3.11it/s]



 33%|███▎      | 47/144 [00:20<00:25,  3.81it/s]



 33%|███▎      | 48/144 [00:20<00:28,  3.35it/s]



 34%|███▍      | 49/144 [00:22<01:05,  1.45it/s]



 36%|███▌      | 52/144 [00:22<00:34,  2.68it/s]



 37%|███▋      | 53/144 [00:23<00:35,  2.59it/s]



 38%|███▊      | 54/144 [00:23<00:30,  2.94it/s]



 39%|███▉      | 56/144 [00:23<00:29,  2.96it/s]



 40%|███▉      | 57/144 [00:25<00:50,  1.72it/s]



 41%|████      | 59/144 [00:25<00:36,  2.30it/s]



 42%|████▏     | 61/144 [00:26<00:27,  3.04it/s]



 43%|████▎     | 62/144 [00:26<00:32,  2.54it/s]



 44%|████▍     | 63/144 [00:26<00:27,  2.90it/s]



 44%|████▍     | 64/144 [00:27<00:28,  2.85it/s]



 45%|████▌     | 65/144 [00:28<00:45,  1.75it/s]



 47%|████▋     | 67/144 [00:29<00:38,  2.00it/s]



 47%|████▋     | 68/144 [00:29<00:31,  2.45it/s]



 49%|████▊     | 70/144 [00:29<00:26,  2.78it/s]



 50%|█████     | 72/144 [00:30<00:25,  2.78it/s]



 51%|█████     | 73/144 [00:31<00:32,  2.21it/s]



 51%|█████▏    | 74/144 [00:31<00:30,  2.33it/s]



 52%|█████▏    | 75/144 [00:32<00:29,  2.32it/s]



 53%|█████▎    | 76/144 [00:32<00:31,  2.18it/s]



 54%|█████▍    | 78/144 [00:32<00:19,  3.37it/s]



 55%|█████▍    | 79/144 [00:33<00:17,  3.75it/s]



 56%|█████▌    | 80/144 [00:34<00:29,  2.19it/s]



 56%|█████▋    | 81/144 [00:34<00:31,  2.03it/s]



 57%|█████▋    | 82/144 [00:34<00:24,  2.50it/s]



 58%|█████▊    | 83/144 [00:35<00:24,  2.49it/s]



 58%|█████▊    | 84/144 [00:36<00:32,  1.85it/s]



 59%|█████▉    | 85/144 [00:36<00:24,  2.42it/s]



 60%|█████▉    | 86/144 [00:36<00:19,  3.05it/s]



 60%|██████    | 87/144 [00:36<00:15,  3.71it/s]



 61%|██████    | 88/144 [00:37<00:25,  2.21it/s]



 62%|██████▏   | 89/144 [00:37<00:22,  2.47it/s]



 62%|██████▎   | 90/144 [00:38<00:19,  2.78it/s]



 63%|██████▎   | 91/144 [00:38<00:20,  2.64it/s]



 64%|██████▍   | 92/144 [00:39<00:26,  1.95it/s]



 65%|██████▍   | 93/144 [00:39<00:19,  2.57it/s]



 65%|██████▌   | 94/144 [00:39<00:17,  2.92it/s]



 66%|██████▌   | 95/144 [00:39<00:14,  3.49it/s]



 67%|██████▋   | 96/144 [00:40<00:20,  2.31it/s]



 67%|██████▋   | 97/144 [00:40<00:18,  2.53it/s]



 68%|██████▊   | 98/144 [00:41<00:16,  2.71it/s]



 69%|██████▉   | 99/144 [00:41<00:18,  2.45it/s]



 69%|██████▉   | 100/144 [00:42<00:21,  2.06it/s]



 70%|███████   | 101/144 [00:42<00:18,  2.33it/s]



 71%|███████   | 102/144 [00:42<00:16,  2.60it/s]



 72%|███████▏  | 104/144 [00:43<00:18,  2.15it/s]



 73%|███████▎  | 105/144 [00:44<00:15,  2.51it/s]



 74%|███████▎  | 106/144 [00:44<00:14,  2.55it/s]



 74%|███████▍  | 107/144 [00:45<00:17,  2.08it/s]



 75%|███████▌  | 108/144 [00:45<00:14,  2.50it/s]



 76%|███████▌  | 109/144 [00:45<00:12,  2.86it/s]



 76%|███████▋  | 110/144 [00:46<00:13,  2.61it/s]



 77%|███████▋  | 111/144 [00:46<00:12,  2.58it/s]



 78%|███████▊  | 112/144 [00:47<00:16,  1.93it/s]



 78%|███████▊  | 113/144 [00:47<00:13,  2.38it/s]



 79%|███████▉  | 114/144 [00:47<00:09,  3.01it/s]



 80%|███████▉  | 115/144 [00:48<00:15,  1.92it/s]



 81%|████████▏ | 117/144 [00:48<00:09,  2.91it/s]



 82%|████████▏ | 118/144 [00:49<00:11,  2.34it/s]



 83%|████████▎ | 119/144 [00:49<00:09,  2.60it/s]



 83%|████████▎ | 120/144 [00:50<00:10,  2.22it/s]



 84%|████████▍ | 121/144 [00:50<00:09,  2.36it/s]



 85%|████████▌ | 123/144 [00:51<00:09,  2.31it/s]



 86%|████████▌ | 124/144 [00:51<00:07,  2.71it/s]



 87%|████████▋ | 125/144 [00:52<00:06,  3.11it/s]



 88%|████████▊ | 126/144 [00:52<00:06,  2.60it/s]

 88%|████████▊ | 127/144 [00:53<00:06,  2.58it/s]



 89%|████████▉ | 128/144 [00:53<00:07,  2.25it/s]



 90%|████████▉ | 129/144 [00:54<00:06,  2.39it/s]



 91%|█████████ | 131/144 [00:54<00:05,  2.46it/s]



 92%|█████████▏| 132/144 [00:55<00:04,  2.76it/s]



 92%|█████████▏| 133/144 [00:55<00:03,  3.04it/s]



 93%|█████████▎| 134/144 [00:55<00:03,  2.56it/s]



 94%|█████████▍| 135/144 [00:56<00:03,  2.51it/s]



 94%|█████████▍| 136/144 [00:56<00:03,  2.33it/s]



 95%|█████████▌| 137/144 [00:57<00:02,  2.37it/s]



 96%|█████████▌| 138/144 [00:57<00:02,  2.84it/s]



 97%|█████████▋| 139/144 [00:58<00:02,  2.10it/s]



 97%|█████████▋| 140/144 [00:58<00:01,  2.49it/s]



 98%|█████████▊| 141/144 [00:58<00:00,  3.20it/s]



 99%|█████████▊| 142/144 [00:59<00:00,  2.22it/s]



 99%|█████████▉| 143/144 [00:59<00:00,  2.42it/s]



100%|██████████| 144/144 [00:59<00:00,  2.41it/s]
Families: 100%|██████████| 3/3 [08:06<00:00, 162.18s/it]

Runtime: 486.533448 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]



Multiplets | family 3:   0%|          | 0/17 [00:00<?, ?it/s]





  0%|          | 0/17 [00:00<?, ?it/s]





  6%|▌         | 1/17 [00:02<00:39,  2.47s/it]





 24%|██▎       | 4/17 [00:02<00:07,  1.77it/s]





 41%|████      | 7/17 [00:02<00:02,  3.52it/s]





 53%|█████▎    | 9/17 [00:04<00:04,  1.91it/s]





 65%|██████▍   | 11/17 [00:05<00:02,  2.69it/s]





 76%|███████▋  | 13/17 [00:05<00:01,  3.42it/s]





 88%|████████▊ | 15/17 [00:05<00:00,  4.27it/s]





100%|██████████| 17/17 [00:06<00:00,  2.50it/s]
Multiplets | family 3:   0%|          | 0/17 [00:06<?, ?it/s]




Multiplets | family 4:   0%|          | 0/767 [00:00<?, ?it/s]





  0%|          | 0/767 [00:00<?, ?it/s]





  0%|          | 1/767 [00:03<47:25,  3.72s/it]





  1%|          | 4/767 [00:04<09:58,  1.27it/s]





  1%|          | 6/767 [00:04<05:58,  2.12it/s]





  1%|          | 8/767 [00:04<03:59,  3.17it/s]





  1%|▏         | 10/767 [00:07<09:54,  1.27it/s]





  1%|▏         | 11/767 [00:07<08:14,  1.53it/s]





  2%|▏         | 12/767 [00:07<06:54,  1.82it/s]





  2%|▏         | 13/767 [00:08<06:03,  2.07it/s]





  2%|▏         | 14/767 [00:08<05:56,  2.11it/s]





  2%|▏         | 15/767 [00:08<04:56,  2.54it/s]





  2%|▏         | 16/767 [00:08<03:59,  3.13it/s]





  2%|▏         | 17/767 [00:11<11:58,  1.04it/s]





  3%|▎         | 20/767 [00:11<06:09,  2.02it/s]





  3%|▎         | 21/767 [00:12<06:31,  1.91it/s]





  3%|▎         | 22/767 [00:12<05:27,  2.28it/s]





  3%|▎         | 23/767 [00:12<04:34,  2.71it/s]





  3%|▎         | 24/767 [00:12<04:01,  3.07it/s]





  3%|▎         | 25/767 [00:15<10:46,  1.15it/s]





  4%|▎         | 27/767 [00:15<06:50,  1.80it/s]





  4%|▎         | 28/767 [00:15<05:37,  2.19it/s]





  4%|▍         | 29/767 [00:16<05:34,  2.21it/s]





  4%|▍         | 31/767 [00:16<04:30,  2.72it/s]





  4%|▍         | 32/767 [00:16<03:46,  3.24it/s]





  4%|▍         | 33/767 [00:18<09:07,  1.34it/s]





  4%|▍         | 34/767 [00:19<07:52,  1.55it/s]





  5%|▍         | 35/767 [00:19<06:17,  1.94it/s]





  5%|▍         | 36/767 [00:19<05:01,  2.43it/s]





  5%|▍         | 37/767 [00:19<04:47,  2.54it/s]





  5%|▌         | 39/767 [00:20<04:25,  2.74it/s]





  5%|▌         | 41/767 [00:22<07:27,  1.62it/s]





  5%|▌         | 42/767 [00:22<06:39,  1.81it/s]





  6%|▌         | 43/767 [00:23<05:52,  2.05it/s]





  6%|▌         | 45/767 [00:23<05:23,  2.23it/s]





  6%|▌         | 46/767 [00:24<04:46,  2.51it/s]





  6%|▌         | 47/767 [00:24<05:10,  2.32it/s]





  6%|▋         | 48/767 [00:24<04:16,  2.80it/s]





  6%|▋         | 49/767 [00:26<07:17,  1.64it/s]





  7%|▋         | 50/767 [00:26<07:00,  1.71it/s]





  7%|▋         | 51/767 [00:27<06:28,  1.84it/s]





  7%|▋         | 52/767 [00:27<06:25,  1.85it/s]





  7%|▋         | 53/767 [00:27<05:19,  2.24it/s]





  7%|▋         | 55/767 [00:28<05:22,  2.21it/s]





  7%|▋         | 56/767 [00:29<05:29,  2.16it/s]





  7%|▋         | 57/767 [00:29<06:02,  1.96it/s]





  8%|▊         | 58/767 [00:30<07:38,  1.55it/s]





  8%|▊         | 60/767 [00:31<05:45,  2.04it/s]





  8%|▊         | 61/767 [00:31<04:49,  2.43it/s]





  8%|▊         | 62/767 [00:31<04:32,  2.58it/s]





  8%|▊         | 63/767 [00:32<05:39,  2.07it/s]





  8%|▊         | 64/767 [00:33<05:20,  2.20it/s]





  8%|▊         | 65/767 [00:33<05:11,  2.25it/s]





  9%|▊         | 66/767 [00:34<07:11,  1.62it/s]





  9%|▊         | 67/767 [00:34<05:31,  2.11it/s]





  9%|▉         | 68/767 [00:35<06:17,  1.85it/s]





  9%|▉         | 70/767 [00:35<04:24,  2.63it/s]





  9%|▉         | 71/767 [00:36<05:34,  2.08it/s]





  9%|▉         | 72/767 [00:36<04:58,  2.33it/s]





 10%|▉         | 73/767 [00:37<04:48,  2.40it/s]





 10%|▉         | 74/767 [00:38<07:46,  1.48it/s]





 10%|▉         | 76/767 [00:39<05:35,  2.06it/s]





 10%|█         | 77/767 [00:39<04:38,  2.48it/s]





 10%|█         | 78/767 [00:39<04:40,  2.46it/s]





 10%|█         | 79/767 [00:40<06:16,  1.83it/s]





 10%|█         | 80/767 [00:41<06:11,  1.85it/s]





 11%|█         | 81/767 [00:41<05:09,  2.22it/s]





 11%|█         | 82/767 [00:42<06:52,  1.66it/s]





 11%|█         | 83/767 [00:42<06:38,  1.72it/s]





 11%|█         | 84/767 [00:42<05:15,  2.17it/s]





 11%|█         | 85/767 [00:43<04:26,  2.56it/s]





 11%|█         | 86/767 [00:43<04:19,  2.62it/s]





 11%|█▏        | 87/767 [00:44<07:20,  1.54it/s]





 12%|█▏        | 89/767 [00:45<05:09,  2.19it/s]





 12%|█▏        | 90/767 [00:46<06:49,  1.65it/s]





 12%|█▏        | 91/767 [00:46<05:23,  2.09it/s]





 12%|█▏        | 92/767 [00:46<04:31,  2.49it/s]





 12%|█▏        | 93/767 [00:47<05:10,  2.17it/s]





 12%|█▏        | 94/767 [00:47<04:11,  2.68it/s]





 12%|█▏        | 95/767 [00:48<06:56,  1.61it/s]





 13%|█▎        | 97/767 [00:49<04:59,  2.24it/s]





 13%|█▎        | 98/767 [00:50<06:15,  1.78it/s]





 13%|█▎        | 99/767 [00:50<05:16,  2.11it/s]





 13%|█▎        | 101/767 [00:50<04:40,  2.38it/s]





 13%|█▎        | 102/767 [00:51<04:21,  2.54it/s]





 13%|█▎        | 103/767 [00:52<06:08,  1.80it/s]





 14%|█▎        | 104/767 [00:52<05:45,  1.92it/s]





 14%|█▎        | 105/767 [00:53<05:13,  2.11it/s]





 14%|█▍        | 106/767 [00:53<06:03,  1.82it/s]





 14%|█▍        | 107/767 [00:53<04:47,  2.29it/s]





 14%|█▍        | 108/767 [00:54<04:46,  2.30it/s]





 14%|█▍        | 109/767 [00:55<05:29,  2.00it/s]





 14%|█▍        | 111/767 [00:56<05:48,  1.88it/s]





 15%|█▍        | 112/767 [00:56<06:00,  1.82it/s]





 15%|█▍        | 113/767 [00:56<04:48,  2.27it/s]





 15%|█▍        | 114/767 [00:58<07:03,  1.54it/s]





 15%|█▌        | 116/767 [00:58<04:22,  2.48it/s]





 15%|█▌        | 117/767 [00:58<04:53,  2.21it/s]





 15%|█▌        | 118/767 [00:59<06:03,  1.78it/s]





 16%|█▌        | 119/767 [00:59<04:49,  2.24it/s]





 16%|█▌        | 120/767 [01:00<05:13,  2.06it/s]





 16%|█▌        | 121/767 [01:00<04:42,  2.29it/s]

 16%|█▌        | 122/767 [01:02<07:03,  1.52it/s]





 16%|█▌        | 123/767 [01:02<05:36,  1.91it/s]





 16%|█▌        | 124/767 [01:02<05:03,  2.12it/s]





 16%|█▋        | 125/767 [01:03<05:25,  1.97it/s]





 16%|█▋        | 126/767 [01:03<05:36,  1.91it/s]





 17%|█▋        | 128/767 [01:04<05:05,  2.09it/s]





 17%|█▋        | 129/767 [01:04<04:20,  2.45it/s]





 17%|█▋        | 130/767 [01:05<05:46,  1.84it/s]





 17%|█▋        | 131/767 [01:06<05:14,  2.02it/s]





 17%|█▋        | 132/767 [01:06<04:33,  2.32it/s]





 17%|█▋        | 133/767 [01:06<05:03,  2.09it/s]





 17%|█▋        | 134/767 [01:07<05:04,  2.08it/s]





 18%|█▊        | 135/767 [01:07<03:59,  2.64it/s]





 18%|█▊        | 136/767 [01:08<05:25,  1.94it/s]





 18%|█▊        | 138/767 [01:09<05:13,  2.01it/s]





 18%|█▊        | 139/767 [01:09<05:19,  1.97it/s]





 18%|█▊        | 140/767 [01:10<04:22,  2.39it/s]





 18%|█▊        | 141/767 [01:10<05:05,  2.05it/s]





 19%|█▊        | 142/767 [01:11<04:59,  2.09it/s]





 19%|█▊        | 143/767 [01:11<04:00,  2.59it/s]





 19%|█▉        | 144/767 [01:12<07:26,  1.40it/s]





 19%|█▉        | 145/767 [01:13<05:35,  1.85it/s]





 19%|█▉        | 147/767 [01:13<04:43,  2.19it/s]





 19%|█▉        | 148/767 [01:14<05:27,  1.89it/s]





 20%|█▉        | 150/767 [01:14<04:06,  2.51it/s]





 20%|█▉        | 151/767 [01:15<04:26,  2.31it/s]





 20%|█▉        | 152/767 [01:16<06:43,  1.53it/s]





 20%|██        | 154/767 [01:16<04:14,  2.41it/s]





 20%|██        | 155/767 [01:17<04:53,  2.09it/s]





 20%|██        | 156/767 [01:18<05:08,  1.98it/s]





 20%|██        | 157/767 [01:18<04:35,  2.22it/s]





 21%|██        | 158/767 [01:18<04:11,  2.42it/s]





 21%|██        | 159/767 [01:19<04:40,  2.17it/s]





 21%|██        | 160/767 [01:20<06:11,  1.63it/s]





 21%|██        | 161/767 [01:20<05:27,  1.85it/s]





 21%|██▏       | 163/767 [01:21<04:01,  2.50it/s]





 21%|██▏       | 164/767 [01:21<04:42,  2.13it/s]





 22%|██▏       | 165/767 [01:22<04:29,  2.23it/s]





 22%|██▏       | 167/767 [01:23<04:46,  2.10it/s]





 22%|██▏       | 168/767 [01:24<05:15,  1.90it/s]





 22%|██▏       | 169/767 [01:24<05:05,  1.96it/s]





 22%|██▏       | 171/767 [01:25<04:11,  2.37it/s]





 22%|██▏       | 172/767 [01:25<04:15,  2.33it/s]





 23%|██▎       | 173/767 [01:25<04:20,  2.28it/s]





 23%|██▎       | 174/767 [01:26<03:38,  2.71it/s]





 23%|██▎       | 175/767 [01:27<05:18,  1.86it/s]





 23%|██▎       | 176/767 [01:27<05:51,  1.68it/s]





 23%|██▎       | 177/767 [01:28<05:03,  1.95it/s]





 23%|██▎       | 178/767 [01:28<04:32,  2.16it/s]





 23%|██▎       | 179/767 [01:29<04:42,  2.08it/s]





 23%|██▎       | 180/767 [01:29<05:35,  1.75it/s]





 24%|██▎       | 181/767 [01:30<05:27,  1.79it/s]





 24%|██▎       | 182/767 [01:30<04:52,  2.00it/s]





 24%|██▍       | 183/767 [01:31<04:30,  2.16it/s]





 24%|██▍       | 184/767 [01:31<05:38,  1.72it/s]





 24%|██▍       | 185/767 [01:32<04:18,  2.25it/s]





 24%|██▍       | 186/767 [01:32<04:18,  2.25it/s]





 24%|██▍       | 187/767 [01:32<03:40,  2.63it/s]





 25%|██▍       | 188/767 [01:33<05:40,  1.70it/s]





 25%|██▍       | 189/767 [01:34<05:25,  1.78it/s]





 25%|██▍       | 191/767 [01:35<05:02,  1.91it/s]





 25%|██▌       | 192/767 [01:35<04:53,  1.96it/s]





 25%|██▌       | 193/767 [01:36<04:11,  2.28it/s]





 25%|██▌       | 194/767 [01:36<04:01,  2.38it/s]





 26%|██▌       | 196/767 [01:37<04:56,  1.92it/s]





 26%|██▌       | 197/767 [01:38<04:46,  1.99it/s]





 26%|██▌       | 199/767 [01:39<04:32,  2.09it/s]





 26%|██▌       | 200/767 [01:39<04:37,  2.04it/s]





 26%|██▌       | 201/767 [01:39<03:51,  2.45it/s]





 26%|██▋       | 202/767 [01:40<03:38,  2.59it/s]





 27%|██▋       | 204/767 [01:41<05:00,  1.88it/s]





 27%|██▋       | 205/767 [01:41<04:37,  2.02it/s]





 27%|██▋       | 206/767 [01:42<03:50,  2.43it/s]





 27%|██▋       | 207/767 [01:43<05:28,  1.70it/s]





 27%|██▋       | 208/767 [01:43<04:25,  2.11it/s]





 27%|██▋       | 209/767 [01:43<03:41,  2.52it/s]





 27%|██▋       | 210/767 [01:43<03:22,  2.75it/s]





 28%|██▊       | 211/767 [01:44<04:28,  2.07it/s]





 28%|██▊       | 212/767 [01:45<05:34,  1.66it/s]





 28%|██▊       | 213/767 [01:45<04:17,  2.15it/s]





 28%|██▊       | 214/767 [01:45<04:11,  2.20it/s]





 28%|██▊       | 215/767 [01:46<05:07,  1.80it/s]





 28%|██▊       | 216/767 [01:47<04:58,  1.84it/s]





 28%|██▊       | 217/767 [01:47<04:27,  2.06it/s]





 29%|██▊       | 219/767 [01:48<04:21,  2.09it/s]





 29%|██▊       | 220/767 [01:48<04:11,  2.17it/s]





 29%|██▉       | 221/767 [01:49<04:18,  2.12it/s]





 29%|██▉       | 222/767 [01:49<03:32,  2.56it/s]





 29%|██▉       | 223/767 [01:50<05:12,  1.74it/s]





 29%|██▉       | 224/767 [01:51<04:43,  1.92it/s]





 29%|██▉       | 225/767 [01:51<03:52,  2.33it/s]





 29%|██▉       | 226/767 [01:51<03:02,  2.97it/s]





 30%|██▉       | 227/767 [01:52<04:48,  1.87it/s]





 30%|██▉       | 228/767 [01:52<04:00,  2.24it/s]





 30%|██▉       | 229/767 [01:53<04:20,  2.06it/s]





 30%|██▉       | 230/767 [01:53<03:54,  2.29it/s]





 30%|███       | 231/767 [01:54<04:58,  1.80it/s]





 30%|███       | 232/767 [01:54<04:38,  1.92it/s]





 31%|███       | 234/767 [01:55<03:02,  2.93it/s]





 31%|███       | 235/767 [01:56<04:44,  1.87it/s]





 31%|███       | 236/767 [01:56<03:52,  2.28it/s]





 31%|███       | 237/767 [01:56<03:56,  2.25it/s]





 31%|███       | 238/767 [01:57<03:54,  2.26it/s]





 31%|███       | 239/767 [01:58<04:50,  1.82it/s]





 31%|███▏      | 240/767 [01:58<04:44,  1.85it/s]





 32%|███▏      | 242/767 [01:58<03:03,  2.86it/s]





 32%|███▏      | 243/767 [02:00<05:20,  1.64it/s]





 32%|███▏      | 244/767 [02:00<04:53,  1.78it/s]





 32%|███▏      | 246/767 [02:01<04:37,  1.88it/s]





 32%|███▏      | 248/767 [02:02<04:06,  2.10it/s]





 32%|███▏      | 249/767 [02:02<03:33,  2.43it/s]





 33%|███▎      | 250/767 [02:02<03:21,  2.57it/s]

 33%|███▎      | 251/767 [02:03<04:43,  1.82it/s]





 33%|███▎      | 252/767 [02:04<04:51,  1.77it/s]





 33%|███▎      | 253/767 [02:04<03:53,  2.20it/s]





 33%|███▎      | 254/767 [02:05<04:42,  1.81it/s]





 33%|███▎      | 255/767 [02:06<04:36,  1.85it/s]





 33%|███▎      | 256/767 [02:06<04:15,  2.00it/s]





 34%|███▎      | 257/767 [02:06<03:46,  2.25it/s]





 34%|███▎      | 258/767 [02:06<03:00,  2.81it/s]





 34%|███▍      | 259/767 [02:07<04:22,  1.94it/s]





 34%|███▍      | 260/767 [02:08<04:22,  1.93it/s]





 34%|███▍      | 261/767 [02:08<04:11,  2.02it/s]





 34%|███▍      | 262/767 [02:09<04:12,  2.00it/s]





 34%|███▍      | 263/767 [02:09<04:32,  1.85it/s]





 34%|███▍      | 264/767 [02:10<03:56,  2.13it/s]





 35%|███▍      | 265/767 [02:10<03:30,  2.39it/s]





 35%|███▍      | 266/767 [02:10<02:57,  2.82it/s]





 35%|███▍      | 267/767 [02:11<04:24,  1.89it/s]





 35%|███▍      | 268/767 [02:12<03:55,  2.12it/s]





 35%|███▌      | 269/767 [02:12<04:10,  1.99it/s]





 35%|███▌      | 270/767 [02:13<03:58,  2.09it/s]





 35%|███▌      | 271/767 [02:13<04:47,  1.72it/s]





 35%|███▌      | 272/767 [02:14<04:19,  1.91it/s]





 36%|███▌      | 273/767 [02:14<03:36,  2.29it/s]





 36%|███▌      | 275/767 [02:15<03:52,  2.11it/s]





 36%|███▌      | 276/767 [02:15<03:50,  2.13it/s]





 36%|███▌      | 277/767 [02:16<04:48,  1.70it/s]





 36%|███▋      | 279/767 [02:18<05:05,  1.60it/s]





 37%|███▋      | 282/767 [02:18<03:28,  2.32it/s]





 37%|███▋      | 283/767 [02:19<03:38,  2.22it/s]





 37%|███▋      | 284/767 [02:19<03:43,  2.16it/s]





 37%|███▋      | 285/767 [02:20<04:31,  1.77it/s]





 37%|███▋      | 287/767 [02:22<04:58,  1.61it/s]





 38%|███▊      | 289/767 [02:22<03:30,  2.27it/s]





 38%|███▊      | 290/767 [02:22<03:25,  2.32it/s]





 38%|███▊      | 291/767 [02:23<03:21,  2.36it/s]





 38%|███▊      | 292/767 [02:23<03:21,  2.36it/s]





 38%|███▊      | 293/767 [02:24<04:34,  1.73it/s]





 38%|███▊      | 295/767 [02:26<04:48,  1.64it/s]





 39%|███▊      | 297/767 [02:26<03:30,  2.23it/s]





 39%|███▉      | 298/767 [02:26<03:07,  2.50it/s]





 39%|███▉      | 299/767 [02:26<03:05,  2.53it/s]





 39%|███▉      | 300/767 [02:27<03:05,  2.51it/s]





 39%|███▉      | 301/767 [02:28<04:46,  1.63it/s]





 40%|███▉      | 303/767 [02:29<04:33,  1.69it/s]





 40%|███▉      | 304/767 [02:30<04:00,  1.92it/s]





 40%|███▉      | 305/767 [02:30<03:14,  2.37it/s]





 40%|███▉      | 306/767 [02:30<03:54,  1.97it/s]





 40%|████      | 308/767 [02:31<03:36,  2.12it/s]





 40%|████      | 309/767 [02:32<04:08,  1.84it/s]





 41%|████      | 311/767 [02:33<04:36,  1.65it/s]





 41%|████      | 313/767 [02:34<03:12,  2.36it/s]





 41%|████      | 314/767 [02:35<04:04,  1.85it/s]





 41%|████      | 315/767 [02:35<03:22,  2.23it/s]





 41%|████      | 316/767 [02:35<03:07,  2.41it/s]





 41%|████▏     | 317/767 [02:36<03:37,  2.07it/s]





 41%|████▏     | 318/767 [02:36<03:22,  2.22it/s]





 42%|████▏     | 319/767 [02:38<05:20,  1.40it/s]





 42%|████▏     | 320/767 [02:38<04:22,  1.70it/s]





 42%|████▏     | 321/767 [02:38<03:26,  2.16it/s]





 42%|████▏     | 322/767 [02:39<03:41,  2.01it/s]





 42%|████▏     | 323/767 [02:39<03:24,  2.18it/s]





 42%|████▏     | 324/767 [02:39<03:05,  2.39it/s]





 42%|████▏     | 325/767 [02:40<02:59,  2.46it/s]





 43%|████▎     | 326/767 [02:40<03:09,  2.33it/s]





 43%|████▎     | 327/767 [02:41<05:13,  1.40it/s]





 43%|████▎     | 328/767 [02:42<03:59,  1.83it/s]





 43%|████▎     | 329/767 [02:42<03:10,  2.30it/s]





 43%|████▎     | 330/767 [02:42<03:30,  2.08it/s]





 43%|████▎     | 331/767 [02:43<03:03,  2.37it/s]





 43%|████▎     | 332/767 [02:43<02:36,  2.78it/s]





 43%|████▎     | 333/767 [02:43<02:40,  2.70it/s]





 44%|████▎     | 334/767 [02:44<03:22,  2.14it/s]





 44%|████▎     | 335/767 [02:45<05:09,  1.40it/s]





 44%|████▍     | 336/767 [02:45<04:09,  1.73it/s]





 44%|████▍     | 338/767 [02:46<03:36,  1.98it/s]





 44%|████▍     | 340/767 [02:47<03:05,  2.30it/s]





 44%|████▍     | 341/767 [02:47<02:35,  2.74it/s]





 45%|████▍     | 342/767 [02:48<03:15,  2.17it/s]





 45%|████▍     | 343/767 [02:49<04:48,  1.47it/s]





 45%|████▍     | 344/767 [02:49<03:50,  1.84it/s]





 45%|████▍     | 345/767 [02:49<02:59,  2.36it/s]





 45%|████▌     | 346/767 [02:50<03:54,  1.80it/s]





 45%|████▌     | 347/767 [02:51<03:19,  2.11it/s]





 45%|████▌     | 348/767 [02:51<03:00,  2.32it/s]





 46%|████▌     | 349/767 [02:51<02:37,  2.66it/s]





 46%|████▌     | 350/767 [02:52<03:41,  1.88it/s]





 46%|████▌     | 351/767 [02:53<05:01,  1.38it/s]





 46%|████▌     | 353/767 [02:54<03:11,  2.16it/s]





 46%|████▌     | 354/767 [02:55<03:59,  1.72it/s]





 46%|████▋     | 355/767 [02:55<03:15,  2.11it/s]





 46%|████▋     | 356/767 [02:55<02:53,  2.37it/s]





 47%|████▋     | 357/767 [02:55<02:44,  2.50it/s]





 47%|████▋     | 358/767 [02:56<03:26,  1.98it/s]





 47%|████▋     | 359/767 [02:57<04:18,  1.58it/s]





 47%|████▋     | 360/767 [02:57<03:30,  1.93it/s]





 47%|████▋     | 361/767 [02:58<03:01,  2.24it/s]





 47%|████▋     | 362/767 [02:58<03:37,  1.86it/s]





 47%|████▋     | 364/767 [02:59<02:36,  2.58it/s]





 48%|████▊     | 365/767 [02:59<02:35,  2.58it/s]





 48%|████▊     | 366/767 [03:00<03:14,  2.06it/s]





 48%|████▊     | 367/767 [03:01<03:58,  1.68it/s]





 48%|████▊     | 368/767 [03:01<03:26,  1.93it/s]





 48%|████▊     | 369/767 [03:01<02:47,  2.38it/s]





 48%|████▊     | 370/767 [03:02<03:51,  1.71it/s]





 48%|████▊     | 371/767 [03:02<02:59,  2.21it/s]





 49%|████▊     | 373/767 [03:03<02:37,  2.51it/s]





 49%|████▉     | 374/767 [03:04<03:21,  1.95it/s]





 49%|████▉     | 375/767 [03:05<03:31,  1.85it/s]





 49%|████▉     | 376/767 [03:05<03:10,  2.05it/s]





 49%|████▉     | 377/767 [03:05<02:59,  2.17it/s]





 49%|████▉     | 378/767 [03:06<04:04,  1.59it/s]





 50%|████▉     | 380/767 [03:07<02:55,  2.21it/s]

 50%|████▉     | 381/767 [03:07<02:42,  2.38it/s]





 50%|████▉     | 382/767 [03:08<03:17,  1.95it/s]





 50%|████▉     | 383/767 [03:09<03:25,  1.87it/s]





 50%|█████     | 384/767 [03:09<03:45,  1.70it/s]





 50%|█████     | 385/767 [03:09<02:53,  2.21it/s]





 50%|█████     | 386/767 [03:10<03:26,  1.84it/s]





 50%|█████     | 387/767 [03:10<03:06,  2.03it/s]





 51%|█████     | 388/767 [03:11<02:30,  2.52it/s]





 51%|█████     | 389/767 [03:11<02:42,  2.33it/s]





 51%|█████     | 390/767 [03:12<03:35,  1.75it/s]





 51%|█████     | 391/767 [03:13<03:22,  1.86it/s]





 51%|█████     | 392/767 [03:13<03:21,  1.86it/s]





 51%|█████     | 393/767 [03:13<02:34,  2.42it/s]





 51%|█████▏    | 394/767 [03:14<02:55,  2.12it/s]





 51%|█████▏    | 395/767 [03:14<02:51,  2.17it/s]





 52%|█████▏    | 396/767 [03:14<02:30,  2.46it/s]





 52%|█████▏    | 397/767 [03:15<02:23,  2.58it/s]





 52%|█████▏    | 398/767 [03:16<03:48,  1.61it/s]





 52%|█████▏    | 399/767 [03:16<03:05,  1.99it/s]





 52%|█████▏    | 400/767 [03:17<03:20,  1.83it/s]





 52%|█████▏    | 401/767 [03:17<02:47,  2.18it/s]





 52%|█████▏    | 402/767 [03:18<02:41,  2.26it/s]





 53%|█████▎    | 403/767 [03:18<03:19,  1.82it/s]





 53%|█████▎    | 404/767 [03:19<02:51,  2.11it/s]





 53%|█████▎    | 406/767 [03:20<03:54,  1.54it/s]





 53%|█████▎    | 407/767 [03:20<03:04,  1.95it/s]





 53%|█████▎    | 408/767 [03:21<02:54,  2.05it/s]





 53%|█████▎    | 409/767 [03:21<02:46,  2.15it/s]





 53%|█████▎    | 410/767 [03:22<02:49,  2.10it/s]





 54%|█████▎    | 411/767 [03:23<03:32,  1.67it/s]





 54%|█████▍    | 413/767 [03:23<02:05,  2.83it/s]





 54%|█████▍    | 414/767 [03:24<03:44,  1.58it/s]





 54%|█████▍    | 416/767 [03:25<03:14,  1.80it/s]





 54%|█████▍    | 418/767 [03:26<02:23,  2.43it/s]





 55%|█████▍    | 419/767 [03:27<03:07,  1.85it/s]





 55%|█████▍    | 420/767 [03:27<02:49,  2.05it/s]





 55%|█████▌    | 422/767 [03:28<03:16,  1.76it/s]





 55%|█████▌    | 424/767 [03:29<02:55,  1.96it/s]





 55%|█████▌    | 425/767 [03:29<02:33,  2.23it/s]





 56%|█████▌    | 426/767 [03:29<02:15,  2.51it/s]





 56%|█████▌    | 427/767 [03:30<02:49,  2.01it/s]





 56%|█████▌    | 428/767 [03:31<02:40,  2.12it/s]





 56%|█████▌    | 429/767 [03:31<02:06,  2.68it/s]





 56%|█████▌    | 430/767 [03:32<03:20,  1.68it/s]





 56%|█████▌    | 431/767 [03:32<02:32,  2.20it/s]





 56%|█████▋    | 432/767 [03:33<03:18,  1.69it/s]





 56%|█████▋    | 433/767 [03:33<02:30,  2.21it/s]





 57%|█████▋    | 434/767 [03:33<01:57,  2.84it/s]





 57%|█████▋    | 435/767 [03:34<02:31,  2.19it/s]





 57%|█████▋    | 436/767 [03:35<02:50,  1.94it/s]





 57%|█████▋    | 437/767 [03:35<02:34,  2.13it/s]





 57%|█████▋    | 438/767 [03:36<03:09,  1.74it/s]





 57%|█████▋    | 439/767 [03:36<02:45,  1.98it/s]





 57%|█████▋    | 440/767 [03:37<03:13,  1.69it/s]





 57%|█████▋    | 441/767 [03:37<02:46,  1.96it/s]





 58%|█████▊    | 442/767 [03:38<02:31,  2.14it/s]





 58%|█████▊    | 444/767 [03:39<02:38,  2.04it/s]





 58%|█████▊    | 445/767 [03:39<02:46,  1.94it/s]





 58%|█████▊    | 446/767 [03:40<02:36,  2.06it/s]





 58%|█████▊    | 447/767 [03:40<02:28,  2.16it/s]





 58%|█████▊    | 448/767 [03:41<02:55,  1.81it/s]





 59%|█████▊    | 449/767 [03:41<02:56,  1.81it/s]





 59%|█████▊    | 450/767 [03:42<02:20,  2.26it/s]





 59%|█████▉    | 452/767 [03:43<02:49,  1.86it/s]





 59%|█████▉    | 453/767 [03:43<02:28,  2.11it/s]





 59%|█████▉    | 454/767 [03:44<02:27,  2.12it/s]





 59%|█████▉    | 455/767 [03:44<02:36,  1.99it/s]





 59%|█████▉    | 456/767 [03:45<02:52,  1.80it/s]





 60%|█████▉    | 457/767 [03:45<02:35,  2.00it/s]





 60%|█████▉    | 460/767 [03:47<02:29,  2.06it/s]





 60%|██████    | 461/767 [03:47<02:17,  2.22it/s]





 60%|██████    | 462/767 [03:47<02:04,  2.45it/s]





 60%|██████    | 463/767 [03:48<02:28,  2.04it/s]





 60%|██████    | 464/767 [03:49<02:49,  1.79it/s]





 61%|██████    | 465/767 [03:49<02:18,  2.17it/s]





 61%|██████    | 466/767 [03:49<01:51,  2.70it/s]





 61%|██████    | 467/767 [03:49<01:36,  3.10it/s]





 61%|██████    | 468/767 [03:50<02:52,  1.73it/s]





 61%|██████    | 469/767 [03:51<02:35,  1.92it/s]





 61%|██████▏   | 470/767 [03:51<02:47,  1.77it/s]





 61%|██████▏   | 471/767 [03:52<03:12,  1.54it/s]





 62%|██████▏   | 472/767 [03:52<02:24,  2.05it/s]





 62%|██████▏   | 473/767 [03:53<01:55,  2.54it/s]





 62%|██████▏   | 474/767 [03:53<02:09,  2.26it/s]





 62%|██████▏   | 475/767 [03:53<01:57,  2.49it/s]





 62%|██████▏   | 476/767 [03:54<02:27,  1.98it/s]





 62%|██████▏   | 477/767 [03:55<03:04,  1.57it/s]





 62%|██████▏   | 478/767 [03:56<03:02,  1.58it/s]





 62%|██████▏   | 479/767 [03:56<02:41,  1.78it/s]





 63%|██████▎   | 481/767 [03:57<02:01,  2.36it/s]





 63%|██████▎   | 482/767 [03:57<01:53,  2.50it/s]





 63%|██████▎   | 483/767 [03:57<01:35,  2.99it/s]





 63%|██████▎   | 484/767 [03:58<02:30,  1.88it/s]





 63%|██████▎   | 485/767 [03:59<02:45,  1.70it/s]





 63%|██████▎   | 486/767 [04:00<02:58,  1.58it/s]





 63%|██████▎   | 487/767 [04:00<02:38,  1.76it/s]





 64%|██████▎   | 488/767 [04:00<02:02,  2.29it/s]





 64%|██████▍   | 489/767 [04:01<01:44,  2.65it/s]





 64%|██████▍   | 490/767 [04:01<01:39,  2.79it/s]





 64%|██████▍   | 491/767 [04:01<01:28,  3.12it/s]





 64%|██████▍   | 492/767 [04:02<02:42,  1.69it/s]





 64%|██████▍   | 493/767 [04:03<02:42,  1.69it/s]





 64%|██████▍   | 494/767 [04:04<02:56,  1.55it/s]





 65%|██████▍   | 495/767 [04:04<02:56,  1.54it/s]





 65%|██████▍   | 496/767 [04:05<02:24,  1.88it/s]





 65%|██████▍   | 497/767 [04:05<01:53,  2.39it/s]





 65%|██████▍   | 498/767 [04:05<01:57,  2.29it/s]





 65%|██████▌   | 499/767 [04:05<01:40,  2.68it/s]





 65%|██████▌   | 500/767 [04:06<02:30,  1.78it/s]





 65%|██████▌   | 501/767 [04:07<02:32,  1.74it/s]





 65%|██████▌   | 502/767 [04:08<03:37,  1.22it/s]





 66%|██████▌   | 503/767 [04:09<02:49,  1.56it/s]

 66%|██████▌   | 504/767 [04:09<02:38,  1.66it/s]





 66%|██████▌   | 505/767 [04:10<02:27,  1.78it/s]





 66%|██████▌   | 506/767 [04:10<02:03,  2.11it/s]





 66%|██████▌   | 507/767 [04:10<01:52,  2.32it/s]





 66%|██████▌   | 508/767 [04:12<03:10,  1.36it/s]





 66%|██████▋   | 510/767 [04:13<03:15,  1.32it/s]





 67%|██████▋   | 511/767 [04:14<02:42,  1.58it/s]





 67%|██████▋   | 512/767 [04:14<02:21,  1.80it/s]





 67%|██████▋   | 514/767 [04:14<01:48,  2.34it/s]





 67%|██████▋   | 515/767 [04:15<01:54,  2.20it/s]





 67%|██████▋   | 516/767 [04:16<02:33,  1.64it/s]





 67%|██████▋   | 517/767 [04:16<02:20,  1.78it/s]





 68%|██████▊   | 518/767 [04:18<03:07,  1.33it/s]





 68%|██████▊   | 520/767 [04:18<02:10,  1.90it/s]





 68%|██████▊   | 521/767 [04:18<01:47,  2.28it/s]





 68%|██████▊   | 522/767 [04:19<01:44,  2.34it/s]





 68%|██████▊   | 523/767 [04:19<01:45,  2.32it/s]





 68%|██████▊   | 524/767 [04:20<02:19,  1.75it/s]





 68%|██████▊   | 525/767 [04:21<02:19,  1.74it/s]





 69%|██████▊   | 526/767 [04:21<02:33,  1.57it/s]





 69%|██████▊   | 527/767 [04:22<02:17,  1.74it/s]





 69%|██████▉   | 528/767 [04:22<01:48,  2.20it/s]





 69%|██████▉   | 530/767 [04:23<01:45,  2.24it/s]





 69%|██████▉   | 531/767 [04:23<01:25,  2.75it/s]





 69%|██████▉   | 532/767 [04:24<02:06,  1.85it/s]





 69%|██████▉   | 533/767 [04:25<02:22,  1.64it/s]





 70%|██████▉   | 534/767 [04:25<02:07,  1.83it/s]





 70%|██████▉   | 535/767 [04:26<01:57,  1.98it/s]





 70%|██████▉   | 536/767 [04:26<02:18,  1.67it/s]





 70%|███████   | 537/767 [04:27<01:53,  2.03it/s]





 70%|███████   | 538/767 [04:27<01:27,  2.63it/s]





 70%|███████   | 539/767 [04:27<01:23,  2.73it/s]





 70%|███████   | 540/767 [04:29<02:32,  1.49it/s]





 71%|███████   | 541/767 [04:29<02:02,  1.84it/s]





 71%|███████   | 542/767 [04:29<01:42,  2.20it/s]





 71%|███████   | 543/767 [04:30<01:51,  2.01it/s]





 71%|███████   | 544/767 [04:31<02:26,  1.52it/s]





 71%|███████   | 545/767 [04:31<01:52,  1.98it/s]





 71%|███████▏  | 547/767 [04:31<01:18,  2.79it/s]





 71%|███████▏  | 548/767 [04:33<02:20,  1.56it/s]





 72%|███████▏  | 549/767 [04:33<01:49,  1.99it/s]





 72%|███████▏  | 551/767 [04:33<01:30,  2.38it/s]





 72%|███████▏  | 552/767 [04:34<02:04,  1.73it/s]





 72%|███████▏  | 553/767 [04:35<01:38,  2.16it/s]





 72%|███████▏  | 554/767 [04:35<01:25,  2.50it/s]





 72%|███████▏  | 555/767 [04:35<01:15,  2.80it/s]





 72%|███████▏  | 556/767 [04:36<02:17,  1.53it/s]





 73%|███████▎  | 557/767 [04:37<01:45,  2.00it/s]





 73%|███████▎  | 558/767 [04:37<01:45,  1.99it/s]





 73%|███████▎  | 559/767 [04:37<01:23,  2.50it/s]





 73%|███████▎  | 560/767 [04:39<02:23,  1.44it/s]





 73%|███████▎  | 561/767 [04:39<01:58,  1.74it/s]





 73%|███████▎  | 562/767 [04:40<01:58,  1.73it/s]





 74%|███████▎  | 564/767 [04:41<01:53,  1.78it/s]





 74%|███████▎  | 565/767 [04:41<01:49,  1.84it/s]





 74%|███████▍  | 566/767 [04:41<01:33,  2.15it/s]





 74%|███████▍  | 568/767 [04:43<01:58,  1.68it/s]





 74%|███████▍  | 569/767 [04:43<01:48,  1.83it/s]





 74%|███████▍  | 570/767 [04:44<01:47,  1.84it/s]





 74%|███████▍  | 571/767 [04:44<01:51,  1.75it/s]





 75%|███████▍  | 572/767 [04:45<01:45,  1.85it/s]





 75%|███████▍  | 573/767 [04:45<01:24,  2.30it/s]





 75%|███████▍  | 574/767 [04:45<01:18,  2.45it/s]





 75%|███████▍  | 575/767 [04:46<01:16,  2.51it/s]





 75%|███████▌  | 576/767 [04:47<02:10,  1.46it/s]





 75%|███████▌  | 577/767 [04:48<02:03,  1.54it/s]





 75%|███████▌  | 578/767 [04:48<01:37,  1.94it/s]





 75%|███████▌  | 579/767 [04:49<01:39,  1.89it/s]





 76%|███████▌  | 580/767 [04:49<01:34,  1.98it/s]





 76%|███████▌  | 581/767 [04:49<01:19,  2.35it/s]





 76%|███████▌  | 582/767 [04:49<01:01,  3.01it/s]





 76%|███████▌  | 583/767 [04:50<01:05,  2.80it/s]





 76%|███████▌  | 584/767 [04:51<01:57,  1.56it/s]





 76%|███████▋  | 585/767 [04:52<02:07,  1.43it/s]





 76%|███████▋  | 586/767 [04:52<01:49,  1.66it/s]





 77%|███████▋  | 587/767 [04:53<01:45,  1.71it/s]





 77%|███████▋  | 588/767 [04:53<01:39,  1.80it/s]





 77%|███████▋  | 589/767 [04:54<01:22,  2.16it/s]





 77%|███████▋  | 590/767 [04:54<01:04,  2.75it/s]





 77%|███████▋  | 591/767 [04:54<01:02,  2.81it/s]





 77%|███████▋  | 592/767 [04:56<02:05,  1.39it/s]





 77%|███████▋  | 593/767 [04:56<02:06,  1.37it/s]





 77%|███████▋  | 594/767 [04:57<01:40,  1.72it/s]





 78%|███████▊  | 595/767 [04:57<01:46,  1.62it/s]





 78%|███████▊  | 597/767 [04:58<01:07,  2.52it/s]





 78%|███████▊  | 598/767 [04:58<01:19,  2.12it/s]





 78%|███████▊  | 600/767 [05:00<01:53,  1.47it/s]





 78%|███████▊  | 601/767 [05:01<01:45,  1.57it/s]





 79%|███████▊  | 603/767 [05:01<01:14,  2.20it/s]





 79%|███████▊  | 604/767 [05:01<01:12,  2.24it/s]





 79%|███████▉  | 605/767 [05:02<01:04,  2.50it/s]





 79%|███████▉  | 606/767 [05:02<01:07,  2.40it/s]





 79%|███████▉  | 607/767 [05:03<01:10,  2.26it/s]





 79%|███████▉  | 608/767 [05:04<01:51,  1.43it/s]





 79%|███████▉  | 609/767 [05:05<01:53,  1.40it/s]





 80%|███████▉  | 611/767 [05:05<01:07,  2.33it/s]





 80%|███████▉  | 612/767 [05:06<01:17,  1.99it/s]





 80%|███████▉  | 613/767 [05:06<01:01,  2.49it/s]





 80%|████████  | 614/767 [05:06<01:03,  2.40it/s]





 80%|████████  | 615/767 [05:07<01:01,  2.45it/s]





 80%|████████  | 616/767 [05:08<01:40,  1.50it/s]





 80%|████████  | 617/767 [05:09<01:45,  1.42it/s]





 81%|████████  | 619/767 [05:09<01:03,  2.33it/s]





 81%|████████  | 620/767 [05:10<01:16,  1.92it/s]





 81%|████████  | 621/767 [05:10<01:01,  2.36it/s]





 81%|████████  | 622/767 [05:10<00:50,  2.87it/s]





 81%|████████  | 623/767 [05:11<00:59,  2.40it/s]





 81%|████████▏ | 624/767 [05:12<01:40,  1.43it/s]





 81%|████████▏ | 625/767 [05:13<02:07,  1.12it/s]





 82%|████████▏ | 626/767 [05:14<01:42,  1.37it/s]





 82%|████████▏ | 627/767 [05:14<01:19,  1.76it/s]





 82%|████████▏ | 629/767 [05:14<00:45,  3.02it/s]

 82%|████████▏ | 630/767 [05:15<01:04,  2.11it/s]





 82%|████████▏ | 631/767 [05:15<01:03,  2.15it/s]





 82%|████████▏ | 632/767 [05:16<01:14,  1.82it/s]





 83%|████████▎ | 633/767 [05:17<01:43,  1.30it/s]





 83%|████████▎ | 635/767 [05:18<01:13,  1.80it/s]





 83%|████████▎ | 638/767 [05:19<00:54,  2.36it/s]





 83%|████████▎ | 639/767 [05:19<00:53,  2.37it/s]





 83%|████████▎ | 640/767 [05:20<01:02,  2.04it/s]





 84%|████████▎ | 641/767 [05:21<01:24,  1.50it/s]





 84%|████████▍ | 643/767 [05:22<01:04,  1.91it/s]





 84%|████████▍ | 645/767 [05:22<00:44,  2.77it/s]





 84%|████████▍ | 646/767 [05:23<00:51,  2.35it/s]





 84%|████████▍ | 647/767 [05:23<00:49,  2.42it/s]





 84%|████████▍ | 648/767 [05:24<00:59,  2.01it/s]





 85%|████████▍ | 649/767 [05:25<01:17,  1.52it/s]





 85%|████████▍ | 650/767 [05:25<01:03,  1.84it/s]





 85%|████████▍ | 651/767 [05:26<01:07,  1.72it/s]





 85%|████████▌ | 652/767 [05:26<00:54,  2.13it/s]





 85%|████████▌ | 654/767 [05:27<00:39,  2.83it/s]





 85%|████████▌ | 655/767 [05:27<00:45,  2.47it/s]





 86%|████████▌ | 656/767 [05:28<01:06,  1.66it/s]





 86%|████████▌ | 657/767 [05:29<01:00,  1.82it/s]





 86%|████████▌ | 658/767 [05:29<00:58,  1.86it/s]





 86%|████████▌ | 659/767 [05:30<01:04,  1.67it/s]





 86%|████████▌ | 660/767 [05:31<01:09,  1.55it/s]





 86%|████████▋ | 662/767 [05:31<00:43,  2.43it/s]





 86%|████████▋ | 663/767 [05:31<00:38,  2.68it/s]





 87%|████████▋ | 664/767 [05:32<00:57,  1.78it/s]





 87%|████████▋ | 665/767 [05:33<00:47,  2.16it/s]





 87%|████████▋ | 666/767 [05:33<00:56,  1.79it/s]





 87%|████████▋ | 667/767 [05:34<01:00,  1.64it/s]





 87%|████████▋ | 668/767 [05:35<01:08,  1.44it/s]





 87%|████████▋ | 670/767 [05:35<00:42,  2.29it/s]





 87%|████████▋ | 671/767 [05:36<00:40,  2.40it/s]





 88%|████████▊ | 672/767 [05:36<00:42,  2.25it/s]





 88%|████████▊ | 673/767 [05:37<00:41,  2.25it/s]





 88%|████████▊ | 674/767 [05:37<00:47,  1.96it/s]





 88%|████████▊ | 675/767 [05:38<00:51,  1.78it/s]





 88%|████████▊ | 676/767 [05:39<00:58,  1.57it/s]





 88%|████████▊ | 677/767 [05:39<00:43,  2.06it/s]





 88%|████████▊ | 678/767 [05:39<00:34,  2.56it/s]





 89%|████████▊ | 679/767 [05:40<00:37,  2.38it/s]





 89%|████████▊ | 680/767 [05:40<00:37,  2.34it/s]





 89%|████████▉ | 681/767 [05:40<00:34,  2.50it/s]





 89%|████████▉ | 682/767 [05:41<00:46,  1.82it/s]





 89%|████████▉ | 683/767 [05:42<00:46,  1.80it/s]





 89%|████████▉ | 684/767 [05:42<00:48,  1.70it/s]





 89%|████████▉ | 685/767 [05:43<00:49,  1.66it/s]





 89%|████████▉ | 686/767 [05:43<00:36,  2.20it/s]





 90%|████████▉ | 687/767 [05:44<00:37,  2.13it/s]





 90%|████████▉ | 689/767 [05:44<00:26,  2.91it/s]





 90%|████████▉ | 690/767 [05:45<00:43,  1.76it/s]





 90%|█████████ | 691/767 [05:46<00:49,  1.53it/s]





 90%|█████████ | 692/767 [05:46<00:40,  1.87it/s]





 90%|█████████ | 693/767 [05:47<00:41,  1.79it/s]





 91%|█████████ | 695/767 [05:48<00:33,  2.17it/s]





 91%|█████████ | 696/767 [05:48<00:26,  2.67it/s]





 91%|█████████ | 697/767 [05:48<00:27,  2.54it/s]





 91%|█████████ | 698/767 [05:50<00:43,  1.59it/s]





 91%|█████████ | 699/767 [05:50<00:42,  1.61it/s]





 91%|█████████▏| 700/767 [05:51<00:36,  1.83it/s]





 91%|█████████▏| 701/767 [05:51<00:34,  1.93it/s]





 92%|█████████▏| 702/767 [05:51<00:31,  2.04it/s]





 92%|█████████▏| 703/767 [05:52<00:25,  2.54it/s]





 92%|█████████▏| 704/767 [05:52<00:22,  2.79it/s]





 92%|█████████▏| 705/767 [05:52<00:20,  2.98it/s]





 92%|█████████▏| 706/767 [05:54<00:40,  1.50it/s]





 92%|█████████▏| 707/767 [05:54<00:36,  1.66it/s]





 92%|█████████▏| 708/767 [05:54<00:32,  1.84it/s]





 92%|█████████▏| 709/767 [05:55<00:27,  2.08it/s]





 93%|█████████▎| 710/767 [05:55<00:26,  2.13it/s]





 93%|█████████▎| 711/767 [05:55<00:21,  2.63it/s]





 93%|█████████▎| 712/767 [05:56<00:19,  2.80it/s]





 93%|█████████▎| 713/767 [05:56<00:17,  3.16it/s]





 93%|█████████▎| 714/767 [05:57<00:36,  1.46it/s]





 93%|█████████▎| 715/767 [05:58<00:34,  1.49it/s]





 93%|█████████▎| 717/767 [05:58<00:22,  2.24it/s]





 94%|█████████▎| 718/767 [05:59<00:27,  1.78it/s]





 94%|█████████▍| 721/767 [06:00<00:19,  2.36it/s]





 94%|█████████▍| 722/767 [06:01<00:26,  1.71it/s]





 94%|█████████▍| 723/767 [06:02<00:24,  1.80it/s]





 94%|█████████▍| 724/767 [06:02<00:21,  1.98it/s]





 95%|█████████▍| 725/767 [06:03<00:21,  1.95it/s]





 95%|█████████▍| 726/767 [06:04<00:23,  1.74it/s]





 95%|█████████▌| 729/767 [06:04<00:15,  2.41it/s]





 95%|█████████▌| 730/767 [06:05<00:20,  1.82it/s]





 95%|█████████▌| 731/767 [06:06<00:18,  1.94it/s]





 95%|█████████▌| 732/767 [06:06<00:17,  1.98it/s]





 96%|█████████▌| 733/767 [06:07<00:17,  1.99it/s]





 96%|█████████▌| 734/767 [06:07<00:17,  1.87it/s]





 96%|█████████▌| 735/767 [06:08<00:13,  2.34it/s]





 96%|█████████▌| 736/767 [06:08<00:12,  2.52it/s]





 96%|█████████▌| 737/767 [06:09<00:14,  2.13it/s]





 96%|█████████▌| 738/767 [06:10<00:18,  1.59it/s]





 96%|█████████▋| 740/767 [06:10<00:12,  2.08it/s]





 97%|█████████▋| 741/767 [06:11<00:12,  2.05it/s]





 97%|█████████▋| 742/767 [06:11<00:12,  1.93it/s]





 97%|█████████▋| 743/767 [06:11<00:10,  2.30it/s]





 97%|█████████▋| 744/767 [06:12<00:09,  2.44it/s]





 97%|█████████▋| 745/767 [06:12<00:10,  2.17it/s]





 97%|█████████▋| 746/767 [06:13<00:12,  1.72it/s]





 98%|█████████▊| 748/767 [06:14<00:09,  2.11it/s]





 98%|█████████▊| 749/767 [06:14<00:08,  2.18it/s]





 98%|█████████▊| 750/767 [06:15<00:09,  1.80it/s]





 98%|█████████▊| 751/767 [06:15<00:07,  2.26it/s]





 98%|█████████▊| 752/767 [06:16<00:08,  1.80it/s]





 98%|█████████▊| 753/767 [06:16<00:06,  2.20it/s]





 98%|█████████▊| 754/767 [06:17<00:08,  1.57it/s]





 98%|█████████▊| 755/767 [06:18<00:06,  1.86it/s]





 99%|█████████▊| 757/767 [06:18<00:04,  2.24it/s]





 99%|█████████▉| 758/767 [06:19<00:04,  2.21it/s]





 99%|█████████▉| 759/767 [06:19<00:03,  2.30it/s]

 99%|█████████▉| 760/767 [06:20<00:04,  1.69it/s]





 99%|█████████▉| 761/767 [06:21<00:02,  2.11it/s]





 99%|█████████▉| 762/767 [06:21<00:03,  1.62it/s]





 99%|█████████▉| 763/767 [06:22<00:01,  2.03it/s]





100%|█████████▉| 764/767 [06:22<00:01,  2.63it/s]





100%|█████████▉| 765/767 [06:22<00:00,  2.36it/s]





100%|█████████▉| 766/767 [06:23<00:00,  2.70it/s]





100%|██████████| 767/767 [06:23<00:00,  2.00it/s]
Families:  67%|██████▋   | 2/3 [06:30<03:48, 228.37s/it]





Multiplets | family 5:   0%|          | 0/468 [00:00<?, ?it/s]






  0%|          | 0/468 [00:00<?, ?it/s]






  0%|          | 1/468 [00:05<41:09,  5.29s/it]






  1%|          | 5/468 [00:05<06:53,  1.12it/s]






  1%|▏         | 6/468 [00:05<05:27,  1.41it/s]






  2%|▏         | 9/468 [00:10<08:21,  1.09s/it]






  2%|▏         | 10/468 [00:10<07:03,  1.08it/s]






  2%|▏         | 11/468 [00:10<05:55,  1.29it/s]






  3%|▎         | 13/468 [00:11<04:16,  1.77it/s]






  3%|▎         | 14/468 [00:11<03:48,  1.98it/s]






  3%|▎         | 15/468 [00:11<03:16,  2.31it/s]






  3%|▎         | 16/468 [00:11<03:00,  2.51it/s]






  4%|▎         | 17/468 [00:15<09:07,  1.21s/it]






  4%|▍         | 18/468 [00:16<07:45,  1.03s/it]






  4%|▍         | 19/468 [00:16<05:52,  1.27it/s]






  4%|▍         | 20/468 [00:16<04:26,  1.68it/s]






  4%|▍         | 21/468 [00:16<03:28,  2.14it/s]






  5%|▍         | 22/468 [00:16<02:57,  2.51it/s]






  5%|▍         | 23/468 [00:16<02:28,  2.99it/s]






  5%|▌         | 24/468 [00:17<02:28,  2.99it/s]






  5%|▌         | 25/468 [00:20<08:51,  1.20s/it]






  6%|▌         | 26/468 [00:21<07:30,  1.02s/it]






  6%|▌         | 27/468 [00:21<05:37,  1.31it/s]






  6%|▌         | 28/468 [00:21<04:17,  1.71it/s]






  6%|▋         | 30/468 [00:21<03:08,  2.33it/s]






  7%|▋         | 31/468 [00:22<03:01,  2.41it/s]






  7%|▋         | 32/468 [00:22<03:05,  2.35it/s]






  7%|▋         | 33/468 [00:25<07:27,  1.03s/it]






  7%|▋         | 34/468 [00:25<06:36,  1.09it/s]






  8%|▊         | 36/468 [00:26<04:04,  1.77it/s]






  8%|▊         | 37/468 [00:27<04:42,  1.52it/s]






  8%|▊         | 38/468 [00:27<03:59,  1.80it/s]






  8%|▊         | 39/468 [00:27<03:31,  2.03it/s]






  9%|▊         | 40/468 [00:28<04:00,  1.78it/s]






  9%|▉         | 41/468 [00:30<07:40,  1.08s/it]






  9%|▉         | 43/468 [00:31<04:46,  1.49it/s]






  9%|▉         | 44/468 [00:31<04:23,  1.61it/s]






 10%|▉         | 45/468 [00:32<04:54,  1.43it/s]






 10%|█         | 47/468 [00:32<03:20,  2.10it/s]






 10%|█         | 48/468 [00:33<04:09,  1.69it/s]






 10%|█         | 49/468 [00:35<06:33,  1.07it/s]






 11%|█         | 51/468 [00:36<04:09,  1.67it/s]






 11%|█         | 52/468 [00:36<03:54,  1.77it/s]






 11%|█▏        | 53/468 [00:37<04:47,  1.44it/s]






 12%|█▏        | 54/468 [00:37<03:44,  1.85it/s]






 12%|█▏        | 55/468 [00:38<03:14,  2.12it/s]






 12%|█▏        | 56/468 [00:39<04:40,  1.47it/s]






 12%|█▏        | 57/468 [00:40<06:32,  1.05it/s]






 13%|█▎        | 59/468 [00:41<03:49,  1.78it/s]






 13%|█▎        | 60/468 [00:41<03:37,  1.88it/s]






 13%|█▎        | 61/468 [00:43<05:26,  1.25it/s]






 13%|█▎        | 63/468 [00:43<03:24,  1.98it/s]






 14%|█▎        | 64/468 [00:44<05:13,  1.29it/s]






 14%|█▍        | 65/468 [00:46<05:39,  1.19it/s]






 14%|█▍        | 67/468 [00:46<03:34,  1.87it/s]






 15%|█▍        | 68/468 [00:47<04:00,  1.66it/s]






 15%|█▍        | 69/468 [00:48<04:53,  1.36it/s]






 15%|█▌        | 71/468 [00:48<03:37,  1.82it/s]






 15%|█▌        | 72/468 [00:50<04:54,  1.35it/s]






 16%|█▌        | 73/468 [00:50<04:53,  1.35it/s]






 16%|█▌        | 74/468 [00:51<04:02,  1.62it/s]






 16%|█▌        | 75/468 [00:51<03:38,  1.80it/s]






 16%|█▌        | 76/468 [00:52<03:30,  1.87it/s]






 16%|█▋        | 77/468 [00:53<04:48,  1.35it/s]






 17%|█▋        | 78/468 [00:53<03:43,  1.74it/s]






 17%|█▋        | 79/468 [00:54<03:42,  1.75it/s]






 17%|█▋        | 80/468 [00:55<05:46,  1.12it/s]






 17%|█▋        | 81/468 [00:56<05:05,  1.27it/s]






 18%|█▊        | 83/468 [00:57<04:07,  1.55it/s]






 18%|█▊        | 84/468 [00:57<03:36,  1.77it/s]






 18%|█▊        | 85/468 [00:58<04:25,  1.44it/s]






 18%|█▊        | 86/468 [00:59<04:29,  1.42it/s]






 19%|█▊        | 87/468 [00:59<03:30,  1.81it/s]






 19%|█▉        | 88/468 [01:00<04:55,  1.29it/s]






 19%|█▉        | 89/468 [01:01<04:37,  1.37it/s]






 19%|█▉        | 90/468 [01:01<04:06,  1.53it/s]






 19%|█▉        | 91/468 [01:02<04:17,  1.46it/s]






 20%|█▉        | 92/468 [01:03<03:57,  1.58it/s]






 20%|█▉        | 93/468 [01:03<03:37,  1.73it/s]






 20%|██        | 94/468 [01:04<03:57,  1.57it/s]






 20%|██        | 95/468 [01:04<03:18,  1.88it/s]






 21%|██        | 96/468 [01:05<04:40,  1.33it/s]






 21%|██        | 97/468 [01:06<04:25,  1.40it/s]






 21%|██        | 98/468 [01:06<03:40,  1.68it/s]






 21%|██        | 99/468 [01:07<04:34,  1.35it/s]






 21%|██▏       | 100/468 [01:08<03:41,  1.66it/s]






 22%|██▏       | 101/468 [01:09<04:18,  1.42it/s]






 22%|██▏       | 102/468 [01:09<04:03,  1.50it/s]






 22%|██▏       | 103/468 [01:10<03:21,  1.82it/s]






 22%|██▏       | 104/468 [01:11<04:06,  1.48it/s]






 22%|██▏       | 105/468 [01:11<03:51,  1.57it/s]






 23%|██▎       | 106/468 [01:11<03:17,  1.83it/s]






 23%|██▎       | 107/468 [01:12<04:11,  1.43it/s]






 23%|██▎       | 108/468 [01:14<05:02,  1.19it/s]






 23%|██▎       | 109/468 [01:14<04:55,  1.22it/s]






 24%|██▎       | 110/468 [01:15<03:58,  1.50it/s]






 24%|██▍       | 112/468 [01:16<03:37,  1.63it/s]






 24%|██▍       | 113/468 [01:17<04:10,  1.42it/s]






 25%|██▍       | 115/468 [01:18<03:22,  1.74it/s]

 25%|██▍       | 116/468 [01:19<04:18,  1.36it/s]






 25%|██▌       | 117/468 [01:20<04:21,  1.34it/s]






 25%|██▌       | 118/468 [01:20<03:31,  1.65it/s]






 25%|██▌       | 119/468 [01:20<03:17,  1.77it/s]






 26%|██▌       | 120/468 [01:21<03:48,  1.53it/s]






 26%|██▌       | 121/468 [01:22<03:40,  1.58it/s]






 26%|██▌       | 122/468 [01:22<03:09,  1.82it/s]






 26%|██▋       | 123/468 [01:23<03:18,  1.74it/s]






 26%|██▋       | 124/468 [01:24<04:06,  1.39it/s]






 27%|██▋       | 125/468 [01:25<04:17,  1.33it/s]






 27%|██▋       | 126/468 [01:25<03:18,  1.72it/s]






 27%|██▋       | 127/468 [01:25<03:05,  1.84it/s]






 27%|██▋       | 128/468 [01:27<04:38,  1.22it/s]






 28%|██▊       | 130/468 [01:28<03:30,  1.60it/s]






 28%|██▊       | 131/468 [01:28<02:49,  1.99it/s]






 28%|██▊       | 132/468 [01:29<03:35,  1.56it/s]






 28%|██▊       | 133/468 [01:30<04:10,  1.34it/s]






 29%|██▊       | 134/468 [01:31<04:17,  1.30it/s]






 29%|██▉       | 136/468 [01:32<03:39,  1.51it/s]






 29%|██▉       | 137/468 [01:33<04:01,  1.37it/s]






 29%|██▉       | 138/468 [01:33<03:15,  1.68it/s]






 30%|██▉       | 139/468 [01:33<02:55,  1.87it/s]






 30%|██▉       | 140/468 [01:34<02:43,  2.00it/s]






 30%|███       | 141/468 [01:35<04:30,  1.21it/s]






 30%|███       | 142/468 [01:36<03:59,  1.36it/s]






 31%|███       | 143/468 [01:36<03:23,  1.59it/s]






 31%|███       | 144/468 [01:37<03:15,  1.66it/s]






 31%|███       | 145/468 [01:38<04:07,  1.31it/s]






 31%|███       | 146/468 [01:38<03:11,  1.68it/s]






 31%|███▏      | 147/468 [01:38<02:36,  2.05it/s]






 32%|███▏      | 148/468 [01:39<02:50,  1.88it/s]






 32%|███▏      | 149/468 [01:40<04:11,  1.27it/s]






 32%|███▏      | 150/468 [01:41<03:54,  1.36it/s]






 32%|███▏      | 151/468 [01:41<03:15,  1.62it/s]






 32%|███▏      | 152/468 [01:42<02:49,  1.87it/s]






 33%|███▎      | 153/468 [01:43<04:29,  1.17it/s]






 33%|███▎      | 154/468 [01:43<03:18,  1.58it/s]






 33%|███▎      | 156/468 [01:44<02:26,  2.13it/s]






 34%|███▎      | 157/468 [01:45<03:59,  1.30it/s]






 34%|███▍      | 158/468 [01:46<03:28,  1.49it/s]






 34%|███▍      | 159/468 [01:46<03:08,  1.64it/s]






 34%|███▍      | 160/468 [01:47<02:51,  1.80it/s]






 34%|███▍      | 161/468 [01:48<04:17,  1.19it/s]






 35%|███▍      | 163/468 [01:49<02:59,  1.69it/s]






 35%|███▌      | 165/468 [01:51<03:34,  1.41it/s]






 35%|███▌      | 166/468 [01:51<03:41,  1.36it/s]






 36%|███▌      | 168/468 [01:52<02:43,  1.84it/s]






 36%|███▌      | 169/468 [01:53<03:29,  1.42it/s]






 37%|███▋      | 171/468 [01:54<02:59,  1.66it/s]






 37%|███▋      | 172/468 [01:54<02:27,  2.00it/s]






 37%|███▋      | 173/468 [01:56<03:24,  1.44it/s]






 37%|███▋      | 174/468 [01:57<03:50,  1.27it/s]






 37%|███▋      | 175/468 [01:57<03:11,  1.53it/s]






 38%|███▊      | 177/468 [01:58<03:16,  1.48it/s]






 38%|███▊      | 178/468 [01:59<02:51,  1.69it/s]






 38%|███▊      | 179/468 [01:59<02:48,  1.71it/s]






 38%|███▊      | 180/468 [01:59<02:28,  1.94it/s]






 39%|███▊      | 181/468 [02:01<03:47,  1.26it/s]






 39%|███▉      | 182/468 [02:02<03:40,  1.30it/s]






 39%|███▉      | 183/468 [02:02<03:29,  1.36it/s]






 40%|███▉      | 185/468 [02:03<02:57,  1.59it/s]






 40%|███▉      | 186/468 [02:04<02:39,  1.77it/s]






 40%|███▉      | 187/468 [02:05<03:25,  1.36it/s]






 40%|████      | 188/468 [02:05<02:52,  1.62it/s]






 40%|████      | 189/468 [02:06<03:26,  1.35it/s]






 41%|████      | 190/468 [02:07<03:14,  1.43it/s]






 41%|████      | 191/468 [02:08<03:27,  1.34it/s]






 41%|████      | 192/468 [02:08<02:36,  1.77it/s]






 41%|████      | 193/468 [02:08<02:36,  1.76it/s]






 41%|████▏     | 194/468 [02:09<02:26,  1.87it/s]






 42%|████▏     | 195/468 [02:10<03:20,  1.36it/s]






 42%|████▏     | 196/468 [02:11<03:04,  1.48it/s]






 42%|████▏     | 197/468 [02:12<03:18,  1.36it/s]






 42%|████▏     | 198/468 [02:12<02:45,  1.64it/s]






 43%|████▎     | 199/468 [02:13<03:40,  1.22it/s]






 43%|████▎     | 201/468 [02:13<02:17,  1.94it/s]






 43%|████▎     | 202/468 [02:14<02:19,  1.91it/s]






 43%|████▎     | 203/468 [02:16<03:25,  1.29it/s]






 44%|████▎     | 204/468 [02:16<03:05,  1.43it/s]






 44%|████▍     | 205/468 [02:17<03:07,  1.40it/s]






 44%|████▍     | 206/468 [02:17<02:30,  1.74it/s]






 44%|████▍     | 207/468 [02:19<03:53,  1.12it/s]






 44%|████▍     | 208/468 [02:19<02:54,  1.49it/s]






 45%|████▍     | 209/468 [02:19<02:27,  1.76it/s]






 45%|████▍     | 210/468 [02:19<01:55,  2.24it/s]






 45%|████▌     | 211/468 [02:20<02:48,  1.52it/s]






 45%|████▌     | 212/468 [02:21<02:46,  1.53it/s]






 46%|████▌     | 213/468 [02:22<03:11,  1.33it/s]






 46%|████▌     | 214/468 [02:22<02:36,  1.62it/s]






 46%|████▌     | 215/468 [02:24<03:51,  1.09it/s]






 46%|████▋     | 217/468 [02:24<02:16,  1.84it/s]






 47%|████▋     | 218/468 [02:24<01:49,  2.28it/s]






 47%|████▋     | 219/468 [02:26<02:43,  1.52it/s]






 47%|████▋     | 220/468 [02:26<02:51,  1.44it/s]






 47%|████▋     | 221/468 [02:27<02:46,  1.48it/s]






 47%|████▋     | 222/468 [02:27<02:23,  1.72it/s]






 48%|████▊     | 223/468 [02:29<03:40,  1.11it/s]






 48%|████▊     | 224/468 [02:29<02:42,  1.50it/s]






 48%|████▊     | 225/468 [02:30<02:19,  1.74it/s]






 48%|████▊     | 226/468 [02:30<01:50,  2.20it/s]






 49%|████▊     | 227/468 [02:31<02:52,  1.39it/s]






 49%|████▊     | 228/468 [02:32<02:45,  1.45it/s]






 49%|████▉     | 229/468 [02:32<02:41,  1.48it/s]






 49%|████▉     | 230/468 [02:33<02:09,  1.83it/s]






 49%|████▉     | 231/468 [02:34<03:31,  1.12it/s]






 50%|████▉     | 232/468 [02:34<02:34,  1.52it/s]

 50%|████▉     | 233/468 [02:35<02:00,  1.95it/s]






 50%|█████     | 234/468 [02:35<02:28,  1.57it/s]






 50%|█████     | 235/468 [02:36<02:38,  1.47it/s]






 50%|█████     | 236/468 [02:37<02:41,  1.44it/s]






 51%|█████     | 237/468 [02:38<02:31,  1.53it/s]






 51%|█████     | 238/468 [02:38<02:04,  1.85it/s]






 51%|█████     | 239/468 [02:40<03:25,  1.12it/s]






 51%|█████▏    | 240/468 [02:40<02:49,  1.35it/s]






 52%|█████▏    | 242/468 [02:41<02:23,  1.57it/s]






 52%|█████▏    | 243/468 [02:42<02:31,  1.48it/s]






 52%|█████▏    | 244/468 [02:43<02:39,  1.40it/s]






 52%|█████▏    | 245/468 [02:43<02:06,  1.76it/s]






 53%|█████▎    | 246/468 [02:43<01:54,  1.94it/s]






 53%|█████▎    | 247/468 [02:45<03:07,  1.18it/s]






 53%|█████▎    | 248/468 [02:45<02:22,  1.55it/s]






 53%|█████▎    | 249/468 [02:45<01:48,  2.02it/s]






 53%|█████▎    | 250/468 [02:46<02:24,  1.51it/s]






 54%|█████▎    | 251/468 [02:47<02:56,  1.23it/s]






 54%|█████▍    | 252/468 [02:48<02:29,  1.44it/s]






 54%|█████▍    | 254/468 [02:49<02:06,  1.69it/s]






 54%|█████▍    | 255/468 [02:50<02:40,  1.33it/s]






 55%|█████▍    | 256/468 [02:50<02:04,  1.70it/s]






 55%|█████▍    | 257/468 [02:51<02:18,  1.52it/s]






 55%|█████▌    | 258/468 [02:52<02:56,  1.19it/s]






 55%|█████▌    | 259/468 [02:52<02:22,  1.46it/s]






 56%|█████▌    | 260/468 [02:53<02:06,  1.64it/s]






 56%|█████▌    | 261/468 [02:53<01:48,  1.91it/s]






 56%|█████▌    | 262/468 [02:54<02:30,  1.37it/s]






 56%|█████▌    | 263/468 [02:55<02:24,  1.42it/s]






 56%|█████▋    | 264/468 [02:55<01:58,  1.72it/s]






 57%|█████▋    | 265/468 [02:56<02:19,  1.45it/s]






 57%|█████▋    | 266/468 [02:57<02:45,  1.22it/s]






 57%|█████▋    | 267/468 [02:58<02:12,  1.51it/s]






 57%|█████▋    | 268/468 [02:58<01:49,  1.83it/s]






 57%|█████▋    | 269/468 [02:59<01:48,  1.83it/s]






 58%|█████▊    | 270/468 [03:00<02:19,  1.42it/s]






 58%|█████▊    | 271/468 [03:00<02:08,  1.53it/s]






 58%|█████▊    | 272/468 [03:01<02:07,  1.54it/s]






 58%|█████▊    | 273/468 [03:02<02:15,  1.44it/s]






 59%|█████▊    | 274/468 [03:03<02:30,  1.29it/s]






 59%|█████▉    | 275/468 [03:03<02:00,  1.60it/s]






 59%|█████▉    | 276/468 [03:04<02:08,  1.49it/s]






 59%|█████▉    | 277/468 [03:04<01:44,  1.83it/s]






 59%|█████▉    | 278/468 [03:05<02:03,  1.54it/s]






 60%|█████▉    | 279/468 [03:06<02:13,  1.42it/s]






 60%|█████▉    | 280/468 [03:06<02:07,  1.47it/s]






 60%|██████    | 281/468 [03:07<02:37,  1.19it/s]






 60%|██████    | 282/468 [03:08<02:21,  1.31it/s]






 60%|██████    | 283/468 [03:09<02:29,  1.24it/s]






 61%|██████    | 284/468 [03:09<01:58,  1.55it/s]






 61%|██████    | 285/468 [03:09<01:28,  2.06it/s]






 61%|██████    | 286/468 [03:10<02:04,  1.46it/s]






 61%|██████▏   | 287/468 [03:11<01:34,  1.91it/s]






 62%|██████▏   | 288/468 [03:12<02:16,  1.32it/s]






 62%|██████▏   | 289/468 [03:13<02:12,  1.36it/s]






 62%|██████▏   | 290/468 [03:13<02:18,  1.28it/s]






 62%|██████▏   | 291/468 [03:14<02:09,  1.37it/s]






 62%|██████▏   | 292/468 [03:14<01:46,  1.65it/s]






 63%|██████▎   | 294/468 [03:16<01:47,  1.63it/s]






 63%|██████▎   | 296/468 [03:17<01:57,  1.46it/s]






 63%|██████▎   | 297/468 [03:18<01:46,  1.61it/s]






 64%|██████▎   | 298/468 [03:19<02:06,  1.35it/s]






 64%|██████▍   | 299/468 [03:19<01:49,  1.54it/s]






 64%|██████▍   | 300/468 [03:20<01:47,  1.57it/s]






 65%|██████▍   | 302/468 [03:21<01:58,  1.41it/s]






 65%|██████▍   | 303/468 [03:21<01:34,  1.75it/s]






 65%|██████▍   | 304/468 [03:22<01:50,  1.49it/s]






 65%|██████▌   | 305/468 [03:23<01:38,  1.65it/s]






 65%|██████▌   | 306/468 [03:24<02:07,  1.27it/s]






 66%|██████▌   | 307/468 [03:24<01:45,  1.53it/s]






 66%|██████▌   | 308/468 [03:25<01:41,  1.57it/s]






 66%|██████▌   | 309/468 [03:25<01:32,  1.72it/s]






 66%|██████▌   | 310/468 [03:27<01:53,  1.39it/s]






 66%|██████▋   | 311/468 [03:27<01:44,  1.50it/s]






 67%|██████▋   | 312/468 [03:28<02:01,  1.29it/s]






 67%|██████▋   | 314/468 [03:29<01:49,  1.41it/s]






 67%|██████▋   | 315/468 [03:30<01:31,  1.67it/s]






 68%|██████▊   | 316/468 [03:30<01:29,  1.71it/s]






 68%|██████▊   | 317/468 [03:31<01:23,  1.82it/s]






 68%|██████▊   | 318/468 [03:32<01:47,  1.40it/s]






 68%|██████▊   | 319/468 [03:32<01:29,  1.66it/s]






 68%|██████▊   | 320/468 [03:33<01:49,  1.35it/s]






 69%|██████▊   | 321/468 [03:33<01:22,  1.77it/s]






 69%|██████▉   | 322/468 [03:35<02:02,  1.20it/s]






 69%|██████▉   | 324/468 [03:35<01:18,  1.83it/s]






 69%|██████▉   | 325/468 [03:36<01:39,  1.43it/s]






 70%|██████▉   | 326/468 [03:37<01:33,  1.52it/s]






 70%|██████▉   | 327/468 [03:38<01:43,  1.36it/s]






 70%|███████   | 328/468 [03:38<01:34,  1.49it/s]






 70%|███████   | 329/468 [03:39<01:32,  1.51it/s]






 71%|███████   | 330/468 [03:40<01:34,  1.45it/s]






 71%|███████   | 331/468 [03:40<01:21,  1.69it/s]






 71%|███████   | 332/468 [03:40<01:05,  2.08it/s]






 71%|███████   | 333/468 [03:42<01:52,  1.20it/s]






 71%|███████▏  | 334/468 [03:43<01:45,  1.27it/s]






 72%|███████▏  | 335/468 [03:43<01:37,  1.36it/s]






 72%|███████▏  | 336/468 [03:44<01:31,  1.44it/s]






 72%|███████▏  | 337/468 [03:44<01:15,  1.74it/s]






 72%|███████▏  | 338/468 [03:45<01:29,  1.45it/s]






 73%|███████▎  | 340/468 [03:46<01:06,  1.94it/s]






 73%|███████▎  | 341/468 [03:47<01:37,  1.30it/s]






 73%|███████▎  | 342/468 [03:48<01:28,  1.42it/s]






 73%|███████▎  | 343/468 [03:49<01:28,  1.42it/s]






 74%|███████▎  | 344/468 [03:49<01:23,  1.49it/s]






 74%|███████▎  | 345/468 [03:49<01:09,  1.77it/s]






 74%|███████▍  | 346/468 [03:50<01:15,  1.62it/s]

 74%|███████▍  | 347/468 [03:50<00:58,  2.08it/s]






 74%|███████▍  | 348/468 [03:51<01:08,  1.76it/s]






 75%|███████▍  | 349/468 [03:52<01:35,  1.24it/s]






 75%|███████▍  | 350/468 [03:53<01:30,  1.30it/s]






 75%|███████▌  | 351/468 [03:54<01:40,  1.16it/s]






 75%|███████▌  | 352/468 [03:54<01:17,  1.50it/s]






 75%|███████▌  | 353/468 [03:55<01:01,  1.88it/s]






 76%|███████▌  | 354/468 [03:56<01:14,  1.52it/s]






 76%|███████▌  | 355/468 [03:56<01:07,  1.67it/s]






 76%|███████▌  | 356/468 [03:56<00:58,  1.92it/s]






 76%|███████▋  | 357/468 [03:58<01:40,  1.10it/s]






 76%|███████▋  | 358/468 [03:59<01:21,  1.35it/s]






 77%|███████▋  | 359/468 [04:00<01:32,  1.18it/s]






 77%|███████▋  | 361/468 [04:00<00:56,  1.89it/s]






 77%|███████▋  | 362/468 [04:01<00:58,  1.82it/s]






 78%|███████▊  | 363/468 [04:01<01:03,  1.66it/s]






 78%|███████▊  | 364/468 [04:02<00:56,  1.83it/s]






 78%|███████▊  | 365/468 [04:04<01:34,  1.09it/s]






 78%|███████▊  | 366/468 [04:04<01:10,  1.44it/s]






 78%|███████▊  | 367/468 [04:05<01:17,  1.29it/s]






 79%|███████▊  | 368/468 [04:05<01:04,  1.54it/s]






 79%|███████▉  | 370/468 [04:06<00:50,  1.95it/s]






 79%|███████▉  | 371/468 [04:06<00:52,  1.85it/s]






 79%|███████▉  | 372/468 [04:07<00:59,  1.61it/s]






 80%|███████▉  | 373/468 [04:09<01:31,  1.04it/s]






 80%|███████▉  | 374/468 [04:10<01:17,  1.21it/s]






 80%|████████  | 376/468 [04:10<00:57,  1.61it/s]






 81%|████████  | 378/468 [04:11<00:53,  1.68it/s]






 81%|████████  | 379/468 [04:12<00:54,  1.64it/s]






 81%|████████  | 380/468 [04:12<00:45,  1.93it/s]






 81%|████████▏ | 381/468 [04:15<01:23,  1.05it/s]






 82%|████████▏ | 383/468 [04:15<01:01,  1.38it/s]






 82%|████████▏ | 384/468 [04:16<00:50,  1.65it/s]






 82%|████████▏ | 385/468 [04:16<00:45,  1.84it/s]






 82%|████████▏ | 386/468 [04:17<00:46,  1.78it/s]






 83%|████████▎ | 387/468 [04:17<00:51,  1.58it/s]






 83%|████████▎ | 388/468 [04:18<00:44,  1.79it/s]






 83%|████████▎ | 389/468 [04:20<01:17,  1.01it/s]






 83%|████████▎ | 390/468 [04:20<00:57,  1.35it/s]






 84%|████████▎ | 391/468 [04:21<01:00,  1.27it/s]






 84%|████████▍ | 393/468 [04:21<00:39,  1.88it/s]






 84%|████████▍ | 394/468 [04:22<00:35,  2.09it/s]






 84%|████████▍ | 395/468 [04:23<00:44,  1.63it/s]






 85%|████████▍ | 396/468 [04:23<00:40,  1.77it/s]






 85%|████████▍ | 397/468 [04:25<01:06,  1.07it/s]






 85%|████████▌ | 398/468 [04:25<00:54,  1.29it/s]






 85%|████████▌ | 399/468 [04:26<00:52,  1.32it/s]






 85%|████████▌ | 400/468 [04:26<00:39,  1.71it/s]






 86%|████████▌ | 401/468 [04:27<00:35,  1.90it/s]






 86%|████████▌ | 402/468 [04:27<00:28,  2.32it/s]






 86%|████████▌ | 403/468 [04:28<00:36,  1.76it/s]






 86%|████████▋ | 404/468 [04:28<00:36,  1.74it/s]






 87%|████████▋ | 405/468 [04:30<01:07,  1.07s/it]






 87%|████████▋ | 406/468 [04:31<00:48,  1.27it/s]






 87%|████████▋ | 407/468 [04:32<00:54,  1.13it/s]






 87%|████████▋ | 408/468 [04:32<00:41,  1.43it/s]






 87%|████████▋ | 409/468 [04:32<00:31,  1.87it/s]






 88%|████████▊ | 410/468 [04:32<00:26,  2.18it/s]






 88%|████████▊ | 411/468 [04:33<00:34,  1.66it/s]






 88%|████████▊ | 412/468 [04:34<00:35,  1.56it/s]






 88%|████████▊ | 413/468 [04:36<00:48,  1.13it/s]






 88%|████████▊ | 414/468 [04:36<00:38,  1.40it/s]






 89%|████████▊ | 415/468 [04:37<00:43,  1.22it/s]






 89%|████████▉ | 416/468 [04:37<00:35,  1.48it/s]






 89%|████████▉ | 417/468 [04:38<00:30,  1.67it/s]






 89%|████████▉ | 418/468 [04:38<00:22,  2.22it/s]






 90%|████████▉ | 419/468 [04:39<00:30,  1.62it/s]






 90%|████████▉ | 420/468 [04:39<00:30,  1.57it/s]






 90%|████████▉ | 421/468 [04:41<00:35,  1.32it/s]






 90%|█████████ | 422/468 [04:41<00:28,  1.60it/s]






 90%|█████████ | 423/468 [04:42<00:33,  1.34it/s]






 91%|█████████ | 424/468 [04:42<00:30,  1.42it/s]






 91%|█████████ | 425/468 [04:43<00:29,  1.45it/s]






 91%|█████████ | 426/468 [04:43<00:23,  1.82it/s]






 91%|█████████ | 427/468 [04:44<00:24,  1.64it/s]






 91%|█████████▏| 428/468 [04:45<00:23,  1.70it/s]






 92%|█████████▏| 429/468 [04:46<00:33,  1.17it/s]






 92%|█████████▏| 430/468 [04:47<00:30,  1.25it/s]






 92%|█████████▏| 431/468 [04:47<00:28,  1.30it/s]






 93%|█████████▎| 433/468 [04:49<00:22,  1.53it/s]






 93%|█████████▎| 434/468 [04:49<00:18,  1.88it/s]






 93%|█████████▎| 435/468 [04:50<00:21,  1.51it/s]






 93%|█████████▎| 436/468 [04:50<00:17,  1.83it/s]






 93%|█████████▎| 437/468 [04:51<00:24,  1.25it/s]






 94%|█████████▎| 438/468 [04:52<00:21,  1.38it/s]






 94%|█████████▍| 439/468 [04:53<00:20,  1.39it/s]






 94%|█████████▍| 441/468 [04:54<00:16,  1.59it/s]






 94%|█████████▍| 442/468 [04:54<00:14,  1.79it/s]






 95%|█████████▍| 443/468 [04:55<00:15,  1.60it/s]






 95%|█████████▍| 444/468 [04:56<00:16,  1.46it/s]






 95%|█████████▌| 445/468 [04:57<00:16,  1.36it/s]






 95%|█████████▌| 446/468 [04:57<00:13,  1.60it/s]






 96%|█████████▌| 447/468 [04:58<00:15,  1.35it/s]






 96%|█████████▌| 448/468 [04:58<00:12,  1.55it/s]






 96%|█████████▌| 449/468 [04:59<00:11,  1.65it/s]






 96%|█████████▌| 450/468 [05:00<00:11,  1.52it/s]






 96%|█████████▋| 451/468 [05:00<00:11,  1.43it/s]






 97%|█████████▋| 452/468 [05:01<00:12,  1.29it/s]






 97%|█████████▋| 453/468 [05:02<00:10,  1.41it/s]






 97%|█████████▋| 454/468 [05:03<00:09,  1.47it/s]






 97%|█████████▋| 455/468 [05:03<00:09,  1.39it/s]






 97%|█████████▋| 456/468 [05:04<00:06,  1.80it/s]






 98%|█████████▊| 457/468 [05:04<00:06,  1.68it/s]






 98%|█████████▊| 458/468 [05:05<00:05,  1.67it/s]






 98%|█████████▊| 459/468 [05:05<00:05,  1.65it/s]






 98%|█████████▊| 460/468 [05:07<00:06,  1.22it/s]

 99%|█████████▊| 461/468 [05:07<00:05,  1.31it/s]






 99%|█████████▊| 462/468 [05:08<00:03,  1.53it/s]






 99%|█████████▉| 463/468 [05:09<00:03,  1.46it/s]






 99%|█████████▉| 464/468 [05:09<00:02,  1.90it/s]






 99%|█████████▉| 465/468 [05:09<00:01,  1.78it/s]






100%|█████████▉| 466/468 [05:10<00:01,  1.65it/s]






100%|█████████▉| 467/468 [05:10<00:00,  1.95it/s]






100%|██████████| 468/468 [05:11<00:00,  1.50it/s]
Families: 100%|██████████| 3/3 [11:41<00:00, 233.99s/it]

Runtime: 701.968459 s

In [127]:
# skip dir creation if it already exist
out_dir_sm = "selected_boot_stat_SCALES"            
os.makedirs(out_dir_sm, exist_ok=True)

for diagnosis, stat_scales in selected_boot_stats.items():
    fname = f"{diagnosis}_selected_stat_scales.pkl"
    fpath = os.path.join(out_dir_sm, fname)
    with open(fpath, "wb") as f:
        pickle.dump(stat_scales, f, protocol=pickle.HIGHEST_PROTOCOL)

In [128]:
# LOAD
with open("selected_boot_stat_SCALES/ANBP_selected_stat_scales.pkl", "rb") as f:
    ANBP_sel_stat_scales = pickle.load(f)

with open("selected_boot_stat_SCALES/ANR_selected_stat_scales.pkl", "rb") as f:
    ANR_sel_stat_scales = pickle.load(f)

with open("selected_boot_stat_SCALES/BED_OSFED_selected_stat_scales.pkl", "rb") as f:
    BED_OSFED_sel_stat_scales = pickle.load(f)

with open("selected_boot_stat_SCALES/BN_selected_stat_scales.pkl", "rb") as f:
    BN_sel_stat_scales = pickle.load(f)

# rebuild general dictionary
selected_boot_stats_loaded = {
    'ANBP' : ANBP_sel_stat_scales,
    'ANR' : ANR_sel_stat_scales,
    'BED_OSFED' : BED_OSFED_sel_stat_scales,
    'BN' : BN_sel_stat_scales
}

Add observed info to dict for computing BCa CIs.

In [130]:
for diagnosis, diag_data in selected_boot_stats.items():
    for order, mults in diag_data.items():
        for mult, distro in mults.items():
            selected_boot_stats[diagnosis][order][mult] = {
                'observed_O' : o_infoptim.o_information(EDI_diags[diagnosis][list(mult)]),
                'samp_distro' : distro
            }

#### BCA

In [131]:
bca_final = {}
for diagnosis, mult_scales in selected_boot_stats.items():
    start = time.perf_counter()
    # structure: order: multiple: samp_distro
    bca_final[diagnosis] = bca_bootopt.bca_bootstrap_parallel(multiplets_dict=mult_scales, 
                                                                            X=EDI_diags[diagnosis])
    end = time.perf_counter()
    print(f"Runtime: {end - start:.6f} s")

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 104 multiplets

Families:  33%|███▎      | 1/3 [00:02<00:04,  2.31s/it]

  [BCa | family 3] 104/104 multiplets (100%)

[BCa | family 4] starting – 1357 multiplets

Families: 100%|██████████| 3/3 [00:03<00:00,  1.02s/it]

  [BCa | family 4] 1357/1357 multiplets (100%)

[BCa | family 5] starting – 219 multiplets
  [BCa | family 5] 219/219 multiplets (100%)
Runtime: 3.038750 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 26 multiplets
  [BCa | family 3] 26/26 multiplets (100%)

[BCa | family 4] starting – 1131 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  4.30it/s]

  [BCa | family 4] 1131/1131 multiplets (100%)

[BCa | family 5] starting – 370 multiplets
  [BCa | family 5] 370/370 multiplets (100%)
Runtime: 0.697037 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 129 multiplets
  [BCa | family 3] 129/129 multiplets (100%)

[BCa | family 4] starting – 1233 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  4.09it/s]

  [BCa | family 4] 1233/1233 multiplets (100%)

[BCa | family 5] starting – 144 multiplets
  [BCa | family 5] 144/144 multiplets (100%)
Runtime: 0.729806 s

Families:   0%|          | 0/3 [00:00<?, ?it/s]

[BCa | family 3] starting – 17 multiplets
  [BCa | family 3] 17/17 multiplets (100%)

[BCa | family 4] starting – 767 multiplets

Families:  67%|██████▋   | 2/3 [00:00<00:00,  5.12it/s]

  [BCa | family 4] 767/767 multiplets (100%)

[BCa | family 5] starting – 468 multiplets

Families: 100%|██████████| 3/3 [00:00<00:00,  4.62it/s]

  [BCa | family 5] 468/468 multiplets (100%)
Runtime: 0.653508 s

In [140]:
bca_final['BN'][3][(4, 5, 38)]

(0.1422196931366706,
 0.004647885587052604,
 0.1887394982661235,
 {'method': 'percentile', 'skew': 0.07344770227253146})

#### Actually filtering out the overlapping multiplets

In [146]:
filtered_diags = {} 
discarded_diags = {}
for diagnose, orders in bca_final.items():
    filtered, discarded = sel.select_multiplets_minimal(orders)
    filtered_diags[diagnose] = filtered
    discarded_diags[diagnose] = discarded

In [151]:
filtered_diags['BN'][3]

{(2, 12, 19): '',
 (4, 5, 38): '',
 (7, 25, 68): '',
 (9, 45, 55): '',
 (9, 45, 59): '',
 (9, 45, 62): '',
 (9, 55, 59): '',
 (9, 55, 62): '',
 (21, 51, 60): '',
 (22, 66, 68): '',
 (28, 47, 53): '',
 (31, 55, 62): '',
 (45, 55, 59): '',
 (45, 55, 62): '',
 (45, 59, 62): '',
 (55, 59, 62): '',
 (72, 79, 90): ''}

### FINAL STEP ( $\Omega$ - DF)

In [152]:
sel_finale = {}
for diagnosis, sel_mults in filtered_diags.items():
    sel_finale[diagnosis] = pp_bootopt.compute_omega_for_multiplets(multiplets_dict=sel_mults, 
                                                                                   X=EDI_diags[diagnosis])
    ap = sel_finale[diagnosis]
    sel_finale[diagnosis]["label"] = np.where(ap["omega"] < 0, "synergy", "redundancy")

In [156]:
sel_finale['ANR'].head()

   order       label     omega  node1  node2  node3  node4  node5
0      3  redundancy  0.209966      2     32     45   <NA>   <NA>
1      3     synergy -0.103594      3     22     39   <NA>   <NA>
2      3  redundancy  0.227318      7     16     32   <NA>   <NA>
3      3  redundancy  0.262536      7     16     49   <NA>   <NA>
4      3  redundancy  0.259711      7     32     49   <NA>   <NA>

In [165]:
print('Redundancy count:', (sel_finale['ANBP']["label"] == 'redundancy').sum())
print('Synergy count:', (sel_finale['ANBP']["label"] == 'synergy').sum())
print(len(sel_finale['ANBP']))

print('Redundancy count:', (sel_finale['ANR']["label"] == 'redundancy').sum())
print('Synergy count:', (sel_finale['ANR']["label"] == 'synergy').sum())
print(len(sel_finale['ANR']))

print('Redundancy count:', (sel_finale['BED_OSFED']["label"] == 'redundancy').sum())
print('Synergy count:', (sel_finale['BED_OSFED']["label"] == 'synergy').sum())
print(len(sel_finale['BED_OSFED']))

print('Redundancy count:', (sel_finale['BN']["label"] == 'redundancy').sum())
print('Synergy count:', (sel_finale['BN']["label"] == 'synergy').sum())
print(len(sel_finale['BN']))

Redundancy count: 26
Synergy count: 1353
1379
Redundancy count: 23
Synergy count: 1149
1172
Redundancy count: 55
Synergy count: 1191
1246
Redundancy count: 19
Synergy count: 855
874

In [159]:
# skip dir creation if it already exist
out_dir_sm = "selected_df_scales_FINAL"            
os.makedirs(out_dir_sm, exist_ok=True)

for diagnosis, df in sel_finale.items():
    fname = f"{diagnosis}_selected_df_scales.csv"
    fpath = os.path.join(out_dir_sm, fname)
    df.to_csv(fpath, index=False)